### ISSUE TITLE
[QST] Different datatype for ElementC and Element D in GEMM / Int8 Weights and Activations, Int32 Bias, and Int8 ouput

### ISSUE THREAD

**Issue by FabianSchuetze** [NVIDIA/cutlass#1001]
Thanks for this wonderful software! 

**What is your question?**
I like to do the following GEMM: Element A and Element B are int8, Element C is int32, and Element D is int8 again. When reading the header for [GEMM](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/device/gemm.h#L178), Element C and Element D seem to be assumed to be the same types. Can this somehow be generalized? 

The [functionality listing](https://github.com/NVIDIA/cutlass/blob/main/media/docs/functionality.md) (`s8 * s8 + s32 => {s32, s8}`) of course indicates that this should be possible. However, I don't see a concrete example of bias being int32 and out being int 8, and I am also not sure how I could have different data types for them.

**Comment by hwu36** [comment]
If C is a bias vector, then it is already there.  Otherwise, if C is a bias matrix, you need to do some plumbing.

**Comment by FabianSchuetze** [comment]
Thanks, @hwu36! Sorry, can you elaborate on:

> If C is a bias vector, then it is already there.

? That would be very helpful indeed.

**Comment by hwu36** [comment]
this https://github.com/NVIDIA/cutlass/commit/ce8597dc14b2e84e0661093ed255c888606ef672#diff-031fe00a2bc882ebd9811d4e47d33fc1a2410233381df5f8fe74a48c3385534f enables using different data types.  check the testbed it modifies and this gemm broadcast unit test https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/gemm_with_broadcast_f16n_f16n_f16n_tensorop_f32_sm75.cu

**Comment by FabianSchuetze** [comment]
Thanks a lot for the comments!
