### ISSUE TITLE
[QST] How to choose the best tiling strategy for certain specific problem size in CUTLASS?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#1002]
I am trying to profile the GEMM operator's performance of CUTLASS in different problem size. So I want to get the best performance for the specific problem size. I know there exists some empirical tiling strategy in https://github.com/NVIDIA/cutlass/blob/209faf7b94ce4ba573d27389fb643962e75d0581/tools/library/scripts/generator.py#L1882-L1903
So should I try them one by one or does there exist some mechanism for choosing a tiling strategy embedded in CUTLASS?
Sincerely thank you for your help! :-)

**Comment by hwu36** [comment]
profiling all of them is the best way to get the best kernel.

we also have a mode called stremk which can reduce this burden.  streamk is not on by default in the profiler, you can change here https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/generator.py#L51  .  With streamk, ideally you just need to use 128x128 for big problem and 64x64 for the small problem.

**Comment by Ther-LF** [comment]
Thank you! I will try it later! :-)
