### ISSUE TITLE
[QST] Is it possible to do permutation after conv2d_fprop?

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#1008]
**What is your question?**
Hi all,

example 39_gemm_permute shows a case to do GEMM computation with output results permuted as reshaped tensors. Is it also possible to do permutation for conv2d_fprop outputs?

thx!

**Comment by hwu36** [comment]
yes.  gemm and conv uses the same epilogue.  you need to do some plumbing first to add permutation to conv device api to use this feature in the epilogue.  second, you need to write your permutation plugin to do your customized permutation.

**Comment by mnicely** [comment]
@TUMSchieben I believe @hwu36 has answered your question, so I'm going to close this issue. Feel free to reopen if you have follow up questions.
