### ISSUE TITLE
[QST] Misaligned address when using AlignedBuffer

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#1010]
Hi, I am encountering a very strange problem when using AlignedBuffer. Here is my pseudocode:
```
    AlignedBuffer<int8_t, 1024> compute_precision;
    int8_t* compute_precision_ptr = compute_precision.data();
    if(warp_idx == 0){
      alignas(4) int8_t compute_precision_data[4];
      // Some data processing....
      FLOAT1(compute_precision_ptr[0]) = FLOAT1(compute_precision_data[0]); 
    }
```
I met the error `misaligned address` at the line:`FLOAT1(compute_precision_ptr[0]) = FLOAT1(compute_precision_data[0]); `.
I am very clear that both address of `compute_precision_ptr[0]` and `compute_precision_data[0]` is the multiple of 4 byte. And I print them out, they are `0x7fd435fffbc0` and `:0x7fd437013000`. It will also incur `misaligned address` error if I replace the code `FLOAT1(compute_precision_ptr[0]) = FLOAT1(compute_precision_data[0]); ` with :
```
      compute_precision_ptr[0] = compute_precision_data[0];
      compute_precision_ptr[1] = compute_precision_data[1];
      compute_precision_ptr[2] = compute_precision_data[2];
      compute_precision_ptr[3] = compute_precision_data[3];
```
which is also very strange.
And if I declare `alignas(4) int8_t compute_precision_data[4];` as `float compute_precision_data;` and modify the code `FLOAT1(compute_precision_ptr[0]) = FLOAT1(compute_precision_data[0]);` to `FLOAT1(compute_precision_ptr[0]) = FLOAT1(compute_precision_data); // compute_precision_data is float now`, the `misaligned address` will disappear.
I have been troubled by this problem for a long time. Sincerely thank you for your help! :-)

**Comment by Ther-LF** [comment]
My compiling command is 
`nvcc profiling_operator_int4_dev.cu  -O3 --std=c++11 --gpu-architecture=compute_80 --gpu-code=sm_80,compute_80   -L /usr/local/lib  -I /usr/local/cuda/samples/common/inc  -I /gitRepo/cutlass/include/ -I /gitRepo/cutlass/tools/util/include/ -I ../common/ -o profiling_operator_int4_dev -lcublas -lcurand`

**Comment by hwu36** [comment]
I don't know exactly what happens here.  You need to dig into SASS and PTX to find out.

Something I learnt from past experience.

1. alignas sometimes are ignored by the compiler. 
2. Inserting printf can change the program a lot.  Especially it can change the memory placement (local memory, global memory, registers).  That said, printf is still the most useful way to debug.

If you want to do a type conversion.  First, define a `Fragment` which is just `cutlass::array`. Second, use `global_load`(https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/arch/memory.h#L53) to load the data from the global memory to the `Fragment`.  Third, call `NumericArrayConverter` (https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/numeric_conversion.h#L759) to do the conversion.

`Fragment` is usually a register backed array.

**Comment by Ther-LF** [comment]
Hi, @hwu36 , thank you so much for your help!
Based on your suggestion, I have modified my code with cutlass's function in [memory.h](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/arch/memory.h), such as `global_load` and `shared_store`.
When using `shared_store`, I want to store the `cutlass::Array<int8_t, 4> compute_precision_data;` to the shared memory's address `compute_precision_ptr + i`. However, since `shared_store` is `void shared_store(uint32_t ptr, void const *src);`, I have to convert the pointer to the corresponding type like this:
 `cutlass::arch::shared_store<4>((uint32_t)(compute_precision_ptr + i), (void const*)compute_precision_data.data());`
And then I met the error:`an illegal memory access was encountered`. I am sure that the address `(compute_precision_ptr + i)` won't be illegal, so this error may be caused by conversion to int32.
I am wondering is it the wrong way for me to use `shared_store` or is there any other way to store shared memory? 
Thank you :-)

**Comment by Ther-LF** [comment]
Besides, using `cutlass::Array<int8_t, 4> compute_precision_data` instead of `alignas(4) int8_t compute_precision_data[4]` really do slove my problem! Thank you!!!!

**Comment by hwu36** [comment]
you don't have to use shared_store.  you can just use normal cuda such as `*shr_ptr = xxx`.  shared_store is a ptx wrapper which is used when we need very precise control.

**Comment by Ther-LF** [comment]
Got it, thank you!
