### ISSUE TITLE
[BUG] `kIsHeavy` Missing in Several Activations, but `LinearCombinationBiasElementwise` requires that it is set

### ISSUE THREAD

**Issue by FabianSchuetze** [NVIDIA/cutlass#1011]
**Describe the bug**
I am not sure if this is a bug or a deliberate omission but many activation function in `cutlass/epilogue/thread/activation.h` do not set the  member variable `kIsHeavy` (see the [Identity](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/thread/activation.h#L89) function). Not setting is prevents `LinearCombinationBiasElementwise` to compile with these activations. 

`LinearCombinationBiasElementwise` wants to extract the member variable from the [Epilgoue op](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/thread/linear_combination_bias_elementwise.h#L102). The compilation fails for activation function for which this variable is not set ([GELU](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/thread/activation.h#L514), e.g). 

- What is the meaning of `kIsHeavy`? Judging from [`epilogue_base`](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/epilogue_base.h#L74) a missing kIsHeavy has the same effect as setting it to false.   
- Why it is not set for some variable? 
- Should I not use the `LinearCombinationBiasElementwise` wich such activations?

**Comment by hwu36** [comment]
We missed it in several activation and we should add them.

If `IsHeavy` is true, the epilogue would not get fully unroll and it can prevent i$ explosion.  It is useful for complicated activation.

Mind creating a PR to add it to those useful to you?  Thank you.

**Comment by FabianSchuetze** [comment]
Thanks, @hwu36, for the kind and instructive comments.  

I have created a PR and look forward to the review.

**Comment by mnicely** [comment]
Closed by #1012

**Comment by FabianSchuetze** [comment]
As mentioned, closed by #1012
