### ISSUE TITLE
[DOC] gemv Warp level API

### ISSUE THREAD

**Issue by MikeChenfu** [NVIDIA/cutlass#1013]
Hello, I am working on the gemv in the cuda kernel. Each block processes one gemv. I wonder if cutlass has warp level API to support that like gemm. Thanks a lot!

**Comment by hwu36** [comment]
sorry for the late response.  it fell into crack somehow.

our gemv code is efficient and also very simple https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/gemv.h.  I think it is not hard to customize it to be a warp level code.

@NVJiangShao

**Comment by mnicely** [comment]
@MikeChenfu has your issue been resolved?

**Comment by MikeChenfu** [comment]
Yes, it works. Will close it. Thanks.
