### ISSUE TITLE
[QST] Why do I get calculation errors when I use TensorOp_d1688

### ISSUE THREAD

**Issue by piDack** [NVIDIA/cutlass#1014]
**What is your question?**

I added the following code to the generator.py script and recompiled cutlass:

```c++
def GenerateSM90_TensorOp_1688(manifest, cuda_version):
  if not CudaToolkitVersionSatisfies(cuda_version, 12, 0):
    return

  layouts = [
    (LayoutType.ColumnMajor, LayoutType.ColumnMajor, LayoutType.ColumnMajor),
    (LayoutType.ColumnMajor, LayoutType.RowMajor, LayoutType.ColumnMajor),
    (LayoutType.RowMajor, LayoutType.ColumnMajor, LayoutType.ColumnMajor),
    (LayoutType.RowMajor, LayoutType.RowMajor, LayoutType.ColumnMajor),
  ]

  math_inst = MathInstruction(
      [16,8,8],
      DataType.f64, DataType.f64, DataType.f64,
      OpcodeClass.TensorOp,
      MathOperation.multiply_add)

  min_cc = 90
  max_cc = 1024

  alignment_constraints = [1,]

  tile_descriptions = [
    #TileDescription([32, 32, 16], 5, [2, 2, 1], math_inst, min_cc, max_cc),
    TileDescription([32, 32, 32], 3, [2, 2, 2], math_inst, min_cc, max_cc,[2,2,1]),
    #TileDescription([16, 32, 16], 5, [1, 2, 1], math_inst, min_cc, max_cc),
    #TileDescription([32, 16, 16], 5, [2, 1, 1], math_inst, min_cc, max_cc),
  ]

  data_type = [DataType.f64, DataType.f64, DataType.f64, DataType.f64]

  CreateGemmOperator(manifest, layouts, tile_descriptions,
    data_type, alignment_constraints)

def GenerateSM90(manifest, cuda_version):
  ...
  GenerateSM90_TensorOp_1688(manifest, cuda_version)

```
It compiles fine and can generate binary files. But when I execute cutlass_profiler, I find that its calculation is not right on H100 machine.

```bash
 Problem ID: 1

        Provider: CUTLASS
   OperationKind: gemm
       Operation: cutlass_sm90_tensorop_d1688gemm_f64_f64_f64_f64_f64_32x16x16_1x1x1_5_nnn_align1

          Status: Success
    Verification: ON
     Disposition: Incorrect

reference_device: Incorrect
          cuBLAS: Not run

       Arguments: --gemm_kind=universal --m=32 --n=32 --k=32 --A=f64:column --B=f64:column --C=f64:column --D=f64:column  \
                  --alpha=1 --beta=0 --split_k_mode=serial --split_k_slices=1 --batch_count=512 --op_class=tensorop --accum=f64  \
                  --cta_m=32 --cta_n=16 --cta_k=16 --cluster_m=1 --cluster_n=1 --cluster_k=1 --stages=5 --warps_m=2 --warps_n=1  \
                  --warps_k=1 --inst_m=16 --inst_n=8 --inst_k=8 --min_cc=90 --max_cc=90

           Bytes: 12582912  bytes
           FLOPs: 34603008  flops
           FLOPs/Byte: 2

         Runtime: 0.0128672  ms
          Memory: 910.746 GiB/s

            Math: 2689.24 GFLOP/s
```

how can I change it? Thanks

```[tasklist]
### Tasks
```

**Comment by hwu36** [comment]
@ANIKET-SHIVAM

**Comment by piDack** [comment]
> 

Thank you very much for your reply, I tried d1684 performance has a big gap with CUBLAS, as far as I know CUBLAS uses d1688. does CUTLASS have any plan to support d1688? Thank you very much.

**Comment by hwu36** [comment]
what is your problem size?

**Comment by piDack** [comment]
> what is your problem size?

m=n=k=32

**Comment by hwu36** [comment]
this tiny gemm is a pure memroy bound kernel.  mainloop performance is not critical.   use the smallest tile size that you can find. try to change your stage number to 3 (or even 2 if it can work).

**Comment by piDack** [comment]
I apologize for not being clear about my needs, in my scenario **m=n=k=32**, but the **batch_count is more than 1024**,I found out that the actual performance is a big gap between cublas.So,I found out through nsys that the name of the kernel called by cublas is `sm90_xmma_gemm_nn_ tile32x32x32_stage3_wrapsize2x2x1_tensor16x8x8
`, I adjusted the CTA size,stage and clusher wrap size according to this name and found that the performance is a big gap with cublas, it seems that the difference in my understanding is that CUBLAS uses d1688 while cutlass uses d1684.
Finally, thank u very much for your professional and productive answers!

**Comment by mnicely** [comment]
Hi @piDack, thank you for using CUTLASS! At this time, we are not planning to add d1688 support.
