### ISSUE TITLE
[QST]how to understand "block swizzling"

### ISSUE THREAD

**Issue by Shaquille-Wu** [NVIDIA/cutlass#1017]
I heard of that cutlass apply "block swizzling" to improve L2 hitrate, 
But, I still cannot understand how cutlass to achieve this goal after reading cutlass code.
Is there anyone to teach me, or introduce some reference document?

**Comment by hwu36** [comment]
block swizzle is used to control the mapping of threadblocks to SMs.  The idea is that we want neighbouring SMs to access data close to each other to improve $ performance.

We have many different implementations in https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle.h .  Code is simple to read.  No one can outperform the others in all cases.  The default one is `Identity<8>`.

**Comment by Shaquille-Wu** [comment]
> block swizzle is used to control the mapping of threadblocks to SMs. The idea is that we want neighbouring SMs to access data close to each other to improve $ performance.
> 
> We have many different implementations in https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle.h . Code is simple to read. No one can outperform the others in all cases. The default one is `Identity<8>`.

thank you, hwu36,
you mean "threadblock swizzle" just improve the layout of shared_mem, and then, it can provide friendly layout for: 
1. reading, reading into register;
2. writing,  writing to global memory, it is friendly for  coalesced access;

above guess are right?

**Comment by hwu36** [comment]
no, it has nothing to do with shared memory and not change anything about layout.

one threadblock can be mapped to any SM in theory.  It just lets neighboring SMs to visit data close to each other in the global memory so likely L2 hit rate can be increased.

**Comment by Shaquille-Wu** [comment]
> no, it has nothing to do with shared memory and not change anything about layout.
> 
> one threadblock can be mapped to any SM in theory. It just lets neighboring SMs to visit data close to each other in the global memory so likely L2 hit rate can be increased.

Sorry, I'm wrong
I think I still cannot get what you said, would you like to show me a plain example?

**Comment by hwu36** [comment]
we have two threadblock0 and threadblock1.  they access data close to each other.  

Suppose we have two ways to map them to SMs.  The first one can map TB0 to SM 0 and TB1 to SM107, the 2nd one can map TB0 to SM0 and TB1 to SM1.  which one is better in terms of cache locality?

**Comment by Shaquille-Wu** [comment]
> we have two threadblock0 and threadblock1. they access data close to each other.
> 
> Suppose we have two ways to map them to SMs. The first one can map TB0 to SM 0 and TB1 to SM107, the 2nd one can map TB0 to SM0 and TB1 to SM1. which one is better in terms of cache locality?

2nd is correct!
thanks for your example.
I have a problem, let's still suppose that there are just 2 thread_blocks, 128 threads per block, and there total 20 SMs in our GPU 
now, the kernel launch code will be like this:
`kernel<<<2, 128>>>(in, out);`

how to confirm block0 is in SM0, and block1 is in SM1 ?

**Comment by hwu36** [comment]
we control which tile each threadblock can get here: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle.h#L137

**Comment by Shaquille-Wu** [comment]
> we control which tile each threadblock can get here: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle.h#L137

thank you very much
let me read it carefully

**Comment by Shaquille-Wu** [comment]
> we control which tile each threadblock can get here: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle.h#L137

thank you very much
let me read it carefully

**Comment by mnicely** [comment]
@Shaquille-Wu I believe @hwu36 has answered your questions, so I'll close this issue. Feel free to reopen if needed.

**Comment by ziyuhuang123** [comment]
Thank you for your excellent discussion! It really helps. But I am still wondering one thing: how the code in line 137 control block to SM relation? 

I guess, just the block will be launched according to their blockIdx.x, and that's all. Right? (If you know any block binding to SM rule, that will also be verrrrry useful!)

**Comment by hwu36** [comment]
right.

**Comment by Tom-Teamo** [comment]
> we have two threadblock0 and threadblock1. they access data close to each other.
> 
> Suppose we have two ways to map them to SMs. The first one can map TB0 to SM 0 and TB1 to SM107, the 2nd one can map TB0 to SM0 and TB1 to SM1. which one is better in terms of cache locality?

Sorry, I can't understand this. All TBs on different SMs are executed concurrently and they share L2 cache, what is the difference between these two cases? you mean that adjacent SMs accessing adjacent global data will increase the L2 cache hit rate, I wonder why.

**Comment by Tom-Teamo** [comment]
Still confused, can you helps me ? @hwu36

**Comment by hwu36** [comment]
https://en.wikipedia.org/wiki/Locality_of_reference

It explains the locality pretty well.

**Comment by Tom-Teamo** [comment]
Thanks for your reply. I think my problem is not that I don't understand the principle of locality.

In your example, block0 and block1 are in different SMs, so they can certainly execute concurrently. In this case, what is the difference between SM0 and SM107 accessing global variables close to each other and SM0 and SM1 accessing global variables close to each other? All SMs share L2 cache, so I think the first case (SM0 and SM107) also satisfies the principle of locality on global memory.

**Comment by Tom-Teamo** [comment]
Hello~Can yuo help me with this question? @hwu36

**Comment by hwu36** [comment]
your description of hw is not 100% correct.  there are some nuance here and there that let neighboring sms accessing neighboring data can improve locality.  it is a good habit to do so no matter writing cpu or gpu code.

more importantly, if all neighboring sms accessing the neighboring tiles, we can reduce the total dram accesses across all the sms and increase L2 sharing.

**Comment by salykova** [comment]
Hi @hwu36! Please correct me if Im wrong, but there is no guarantee that neighboring logical block indices (blockIdx) will be mapped to neighboring SMs or executed on one SM, unless you query SM idx during runtime. So, you can end up in a situation where blockidx.0 and blockidx.1 are mapped to SM0 and SM127 from my understanding and according the answers from the CUDA forum.

For reference: 
[What is the relationship between block_idx and sm_idx](https://forums.developer.nvidia.com/t/what-is-the-relationship-between-block-idx-and-sm-idx/267991)
[What is the sequence of SM launching?](https://forums.developer.nvidia.com/t/what-is-the-sequence-of-sm-launching/284671)

**Comment by zejun-chen** [comment]
- I think there is no assumption for the block can be scheduled to an specific SM. Any code dependent on such assumption could be dangerous. CUDA doesn't provide any methods to control the dispatcher to schedule block to a expected SM. Usually the GPGPU has a common schedule principle named least-loaded, which means schedule the next block to a SM which has least overloading. I'm not sure NV uses this principle.

- SM0 and SM1 has better locality than SM0 and SM127? I'm not sure but due to hardware design, maybe there is some locality different.

- Back to the original question: what is the block swizzling? If there is no block swizzling in tiled GEMM kernel, the launched block(align the blockIdx.x), for example, block(0,0), block(1,0), block(2,0)..., all of these blocks will load the part of the B tensor aligned the column N. There is no L2 cache locality because usually the N is not small. The cache could be evicted. The block swizzling sets a step to swizzle the block launching, for example, launch block(0,0), which is responsible for the tiled result D(0,0), then launch block(1,0), which is responsible for the tiled result D(0,1), then launch the block(2,0), which is responsible for the tiled result D(1,0) **instead of result D(0,2)**, then launch the block(3,0), which is responsible for the tiled result D(1,1) **instead of result D(0,3)**. This could have better L2 locality than no swizzling. When launching block(3,0), the source tiled A and source tiled B are all cached in L2.

**Comment by feifei-111** [comment]
thanks for comment from @zejun-chen, however, I still do not understand how block swizzling benefits L2 cache access.

1. I read the code, and threadblock_swizzle seems only give a map between original block idx and swizzled block idx (kernel is launch with swizzled grid shape)
2. if we launch block (0,0) (0,1) (0,2) (0,3) at same time, it's truly better if we choose to access D(0,0) D(0,1) D(1,0) D(1,1). and this can be achieved by using threadblock_swizzle, good
3. however, there is no evidence showing that block (0,0) (0,1) (0,2) (0,3) always be launch first, if the launch order is shuffled, we just can not get the benefit, for example, block (0,0) (1,1) (2,2) (3,3) might be launched firstly

so, the question is, are the blocks launched by order? I'm still confused.
might @hwu36 give some help?
