### ISSUE TITLE
[DOC]How to understand Swizzle in CuTe

### ISSUE THREAD

**Issue by wllqwzx** [NVIDIA/cutlass#1018]
I'm currently digging into how CuTe's Swizzle struct works when composed with a layout, and I've run into a bit of a roadblock. The existing documentation here: https://github.com/NVIDIA/cutlass/blob/main/include/cute/swizzle.hpp#L44-L57 is a little bit  challenging for me to fully grasp.

It appears that 'BBits', 'MBase', and 'SShift' can have different values when applied to tensorcore mma instructions, as seen here: https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/default_gemm_configuration.hpp. 

I'm aiming to understand the mechanics of these components to determine the appropriate values. I'd greatly appreciate any insight or assistance. Thanks in advance for your time!

**Comment by IonThruster** [comment]
To gain insight into how these values (B, M, S) affect the swizzled layout - do try out some examples (which can be run on the host). [Refer here](https://github.com/NVIDIA/cutlass/blob/a0d787b7468e06ec6bb8f183f0b066f9c8536667/test/unit/cute/core/composition.cpp#L450) : 

Once you have a baseline understanding of what they do - you can try the ones in the default gemm config. - say : 
```cpp
  auto layout = Layout<Shape<_8, _64>,
                       Stride<_64, _1>>{};
  auto swizzled_layout = composition(Swizzle<3,3,3>{}, layout);
```
Based on the layout of the shared memory and the mma instruction being used - we change the swizzle pattern to ensure both the stores and loads to and from shared memory are bank conflict free.

**Comment by wllqwzx** [comment]
> To gain insight into how these values (B, M, S) affect the swizzled layout - do try out some examples (which can be run on the host). [Refer here](https://github.com/NVIDIA/cutlass/blob/a0d787b7468e06ec6bb8f183f0b066f9c8536667/test/unit/cute/core/composition.cpp#L450) :
> 
> Once you have a baseline understanding of what they do - you can try the ones in the default gemm config. - say :
> 
> ```c++
>   auto layout = Layout<Shape<_8, _64>,
>                        Stride<_64, _1>>{};
>   auto swizzled_layout = composition(Swizzle<3,3,3>{}, layout);
> ```
> 
> Based on the layout of the shared memory and the mma instruction being used - we change the swizzle pattern to ensure both the stores and loads to and from shared memory are bank conflict free.

Thank you very much for your response and helpful advice! The examples are informative and very helpful for understanding Swizzle.
