### ISSUE TITLE
[QST] Some question about float2 vs float3 in coalesced access ?  

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/cutlass#1020]
From `s81006-volta-architecture-and-performance-optimization` I find use float2 access will effective use band width, but foat3 not, Why ?    
Natural element sizes=1B, 2B, 4B, 8B, 16B. Why other element sizes(like 3B, 6B, 12B) are not recommended ?   

![v](https://github.com/NVIDIA/cutlass/assets/38753233/97ec60d9-5a70-4ea9-a092-7c4a527906a0)

|float2| float3|       
|--------|--------|       
|![ap2](https://github.com/NVIDIA/cutlass/assets/38753233/45d67b09-cbbc-48b5-a466-95522a566000)| ![ap2-float3](https://github.com/NVIDIA/cutlass/assets/38753233/1cc4211e-552a-402f-b1fe-6c6281712c79)|

**Comment by hwu36** [comment]
i don't know the background.

but you can choose between float2 and float3, you should choose float2.  it has less memory footprint, register usage, memory bandwidth requirement.

if your data structure has to be float3, then you don't have other choices.

generally, power of two is supported better in modern computer architectures since most instructions supports it well.

**Comment by lix19937** [comment]
@hwu36 Thanks for your reply,  you can see https://www.nvidia.com/en-us/on-demand/session/gtcsiliconvalley2018-s81006/  ,  **access patterns** chapter.   I just doubt that `12-Bytes element access`, What will happen ?  How much sectors used, how `requested/ actaul_read`  ?

**Comment by lix19937** [comment]
another question 
```
A cache line is 128 bytes and maps to a 128 byte aligned segment in device memory. 
Memory accesses that are cached in both L1 and L2 are serviced with 128-byte memory transactions, whereas memory accesses that are cached in L2 only are serviced with 32-byte memory transactions. Caching in L2 only can therefore reduce over-fetch, for example, in the case of scattered memory accesses.
```  
Does it mean L1 cache line size is 128-byte, while L2 cache line size is only 32-byte ?

**Comment by hwu36** [comment]
one L1/L2 cache line is 128B, one sector is 32B. 

If one warp (32 threads) doing 12B load at the same time, you will access 384B which is 12 sectors.

I don't know what does actual_read mean.

https://forums.developer.nvidia.com/ is a better place for these general nvidia hardware questions.

**Comment by lix19937** [comment]
@hwu36  thanks.
