### ISSUE TITLE
[QST]What is the meaning of each part in the kernel name?

### ISSUE THREAD

**Issue by lk137095576** [NVIDIA/cutlass#1025]
**What is your question?**
I got some kernel like :
cutlass_80_tensorop_f16_s16816gemm_relu_f16_128x128_32x4_tn_align8
and
ampere_fp16_s16816gemm_fp16_64x64_sliced1x2_ldg8_relu_f2f_stages_64x6_tn
I want to know the mean of the name, This is some of my understanding, I don't know if it's correct:
cutlass_80: arch for A100
tensorop:   use tensor core MMA
f16_:  input fp16?
s16816gemm_:  gemm kernel use tensor core ? but it repeat with tensorop
relu_:  can be fused with relu?
f16_: output fp16?
128x128_: Mtile and Ntile 
32x4_:Ktile and Pipelining?
tn_:  input Row  Major Matrix and output Column ?
align8: alignment 8bit?

how about ampere_fp16_s16816gemm_fp16_64x64_sliced1x2_ldg8_relu_f2f_stages_64x6_tn?
what are "sliced1x2_ldg8", "f2f", "64x6"?

**Comment by lk137095576** [comment]
I got some from https://github.com/NVIDIA/cutlass/blob/main/media/docs/profiler.md
what about  ampere_fp16_s16816gemm_fp16_64x64_sliced1x2_ldg8_relu_f2f_stages_64x6_tn?

**Comment by hwu36** [comment]
these are not cutlass kernels.

**Comment by hwu36** [comment]
as to cutlass_80_tensorop_f16_s16816gemm_relu_f16_128x128_32x4_tn_align8.  it is cutlass kernel, and your guess is correct.
