### ISSUE TITLE
Sparse TensorCore Operations?

### ISSUE THREAD

**Issue by tjingrant** [NVIDIA/cutlass#103]
Hello,

I saw support for the upcoming Ampere architecture being introduced in cutlass, I wonder if there are any plans/roadmaps to support sparse matrix operations in cutlass as well? Or if there's already such support but I missed.

Many thanks!
Tian.

**Comment by kerrmudgeon** [comment]
Hello, Tian,

CUTLASS 2.2 targets NVIDIA Ampere architecture features for dense matrix operations, but there is no support for structured sparse Tensor Core operations at present. We are considering such features for a minor release in the future.

Thanks!

**Comment by tjingrant** [comment]
Thanks @kerrmudgeon having such a feature would be very helpful!
I'd also be interested in helping out in any way possible if you are short of hands.

**Comment by oscarbg** [comment]
+1

**Comment by kerrmudgeon** [comment]
We have just released CUTLASS 2.3 implementing GEMMs targeting Sparse Tensor Cores. Please have a look!

**Comment by hwu36** [comment]
If you need to run sparse gemms in cutlass profiler, you can configure like this

cmake .. -DCUTLASS_NVCC_ARCHS=80 -DCUTLASS_LIBRARY_KERNELS=spgemm

to enable all sparse gemms.  Some examples of kernel names are

cutlass_tensorop_i168128spgemm_s4_256x128_256x3_nn_align32
cutlass_tensorop_i16864spgemm_s8_256x128_128x3_nn_align16
cutlass_tensorop_s16816tf32spgemm_256x128_32x3_nn_align4
cutlass_tensorop_h16832spgemm_256x128_64x3_nn_align8
cutlass_tensorop_s16832spgemm_f16_256x128_64x3_nn_align8

You can use regular expression to reduce the kernel number that gets instantiated.

If anyone from the community is willing to help, we would like to borrow some hands on

1. Port host reference to the device and use the device reference in the profiler.  The tricky part is the meta data layout which is a reordered ColumnMajorInterleaved<2> layout.  Now we first initialized a ColumnMajorInterleaved<2> first, then call a utility method to reorder it.  We need to create a new layout ReorderedSparseMetaColumnMajorInterleaved<2> to hide the reordering part (btw, we need to do the same for the interleaved int8/int4 gemms)

2. Refactor code between sparse and dense.  The only main difference between the sparse and the dense gemm is that the sparse one has three input operands: A, B and E.  The only new code written for the sparse gemm is the shared memory load iterator.  The rest is just reusing the dense gemm components.  However, there is some redundancy in our code that can be refacotored out.  We should write sparse components like

```
struct SparseComponent {
  using Base = DenseComponent<>;
  ElementA = typename Base::ElementA;
  ElementB = typename Base::ElementB;
  ElementC = ...
 ...
}

```
Any help is welcome.  Thank you.

**Comment by tjingrant** [comment]
@hwu36 sorry I totally missed your comment. Is any one of those issues you mentioned still need helping hands? If so I may have some time after the semester ends to take a crack at them.

**Comment by hwu36** [comment]
@tjingrant , that would be very sweet if you can help us on this.  We would like to have small pull request a time which is easier to merge. E.g., one class/struct a time.  Please let me know what you would like to do. 

Our SDK example https://github.com/NVIDIA/cutlass/tree/master/examples/15_ampere_sparse_tensorop_gemm is the good starting point to understand the whole flow.

**Comment by tjingrant** [comment]
@hwu36 I can start with some refactoring work unifying code paths between sparse and dense tensor operations. The SDK example looks very helpful, thanks! I expect to have some time freed up about a month from now, and I'm also looking into getting a sparse-TensorCore enabled GPU for development, for which your suggestion would be very helpful - is RTX 3080 a good GPU for developing/experimenting with cutlass sparse TensorCore functionalities?

**Comment by hwu36** [comment]
@tjingrant , thank you again.

rtx 3080 is great for ampere development, and for game :)

**Comment by YukeWang96** [comment]
> @tjingrant , that would be very sweet if you can help us on this. We would like to have small pull request a time which is easier to merge. E.g., one class/struct a time. Please let me know what you would like to do.
> 
> Our SDK example https://github.com/NVIDIA/cutlass/tree/master/examples/15_ampere_sparse_tensorop_gemm is the good starting point to understand the whole flow.

Could we adapt this **15_ampere_sparse_tensorop_gemm** from INT4 for half, float precision on RTX3090?

**Comment by hwu36** [comment]
> Could we adapt this 15_ampere_sparse_tensorop_gemm from INT4 for half, float precision on RTX3090?

Yes.  Here is the change I made to use sparse fp16 16832

```
[haichengw@computelab-build-03 15_ampere_sparse_tensorop_gemm]$ git diff
diff --git a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
index 1b233c4..fa12b4f 100644
--- a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
+++ b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
@@ -51,11 +51,11 @@ efficiently.
 
 // The code section below describes datatype for input, output matrices and computation between
 // elements in input matrices.
-using ElementAccumulator = int32_t;                 // <- data type of accumulator
+using ElementAccumulator = float;                 // <- data type of accumulator
 using ElementComputeEpilogue = ElementAccumulator;  // <- data type of epilogue operations
-using ElementInputA = cutlass::int4b_t;             // <- data type of elements in input matrix A
-using ElementInputB = cutlass::int4b_t;             // <- data type of elements in input matrix B
-using ElementOutput = int32_t;                      // <- data type of elements in output matrix D
+using ElementInputA = cutlass::half_t;             // <- data type of elements in input matrix A
+using ElementInputB = cutlass::half_t;             // <- data type of elements in input matrix B
+using ElementOutput = float;                      // <- data type of elements in output matrix D
 
 // The code section below describes matrix layout of input and output matrices. Column Major for
 // Matrix A, Row Major for Matrix B and Row Major for Matrix C
@@ -71,11 +71,11 @@ using SmArch = cutlass::arch::Sm80;
 
 // This code section describes the tile size a thread block will compute
 using ShapeMMAThreadBlock =
-    cutlass::gemm::GemmShape<128, 128, 256>;  // <- threadblock tile M = 128, N = 128, K = 256
+    cutlass::gemm::GemmShape<128, 128, 64>;  // <- threadblock tile M = 128, N = 128, K = 256
 // This code section describes tile size a warp will compute
-using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 256>;  // <- warp tile M = 64, N = 64, K = 256
+using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 64>;  // <- warp tile M = 64, N = 64, K = 256
 // This code section describes the size of MMA op
-using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 128>;  // <- MMA Op tile M = 16, N = 8, K = 128
+using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 32>;  // <- MMA Op tile M = 16, N = 8, K = 128


```

**Comment by YukeWang96** [comment]
> > Could we adapt this 15_ampere_sparse_tensorop_gemm from INT4 for half, float precision on RTX3090?
> 
> Yes. Here is the change I made to use sparse fp16 16832
> 
> ```
> [haichengw@computelab-build-03 15_ampere_sparse_tensorop_gemm]$ git diff
> diff --git a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
> index 1b233c4..fa12b4f 100644
> --- a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
> +++ b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
> @@ -51,11 +51,11 @@ efficiently.
>  
>  // The code section below describes datatype for input, output matrices and computation between
>  // elements in input matrices.
> -using ElementAccumulator = int32_t;                 // <- data type of accumulator
> +using ElementAccumulator = float;                 // <- data type of accumulator
>  using ElementComputeEpilogue = ElementAccumulator;  // <- data type of epilogue operations
> -using ElementInputA = cutlass::int4b_t;             // <- data type of elements in input matrix A
> -using ElementInputB = cutlass::int4b_t;             // <- data type of elements in input matrix B
> -using ElementOutput = int32_t;                      // <- data type of elements in output matrix D
> +using ElementInputA = cutlass::half_t;             // <- data type of elements in input matrix A
> +using ElementInputB = cutlass::half_t;             // <- data type of elements in input matrix B
> +using ElementOutput = float;                      // <- data type of elements in output matrix D
>  
>  // The code section below describes matrix layout of input and output matrices. Column Major for
>  // Matrix A, Row Major for Matrix B and Row Major for Matrix C
> @@ -71,11 +71,11 @@ using SmArch = cutlass::arch::Sm80;
>  
>  // This code section describes the tile size a thread block will compute
>  using ShapeMMAThreadBlock =
> -    cutlass::gemm::GemmShape<128, 128, 256>;  // <- threadblock tile M = 128, N = 128, K = 256
> +    cutlass::gemm::GemmShape<128, 128, 64>;  // <- threadblock tile M = 128, N = 128, K = 256
>  // This code section describes tile size a warp will compute
> -using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 256>;  // <- warp tile M = 64, N = 64, K = 256
> +using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 64>;  // <- warp tile M = 64, N = 64, K = 256
>  // This code section describes the size of MMA op
> -using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 128>;  // <- MMA Op tile M = 16, N = 8, K = 128
> +using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 32>;  // <- MMA Op tile M = 16, N = 8, K = 128
> ```

Thanks a lot! 
It works fine, is it also possible to add support for float input and output?

**Comment by hwu36** [comment]
> It works fine, is it also possible to add support for float input and output?

Yes, you can do like below.  Note, the kernel converts fp32 to tfloat32_t implicitly because the tensor cores only supports tfloat32_t.

```
diff --git a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
index 1b233c4..8086a21 100644
--- a/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
+++ b/examples/15_ampere_sparse_tensorop_gemm/ampere_sparse_tensorop_gemm.cu
@@ -51,11 +51,11 @@ efficiently.
 
 // The code section below describes datatype for input, output matrices and computation between
 // elements in input matrices.
-using ElementAccumulator = int32_t;                 // <- data type of accumulator
+using ElementAccumulator = float;                 // <- data type of accumulator
 using ElementComputeEpilogue = ElementAccumulator;  // <- data type of epilogue operations
-using ElementInputA = cutlass::int4b_t;             // <- data type of elements in input matrix A
-using ElementInputB = cutlass::int4b_t;             // <- data type of elements in input matrix B
-using ElementOutput = int32_t;                      // <- data type of elements in output matrix D
+using ElementInputA = float;             // <- data type of elements in input matrix A
+using ElementInputB = float;             // <- data type of elements in input matrix B
+using ElementOutput = float;                      // <- data type of elements in output matrix D
 
 // The code section below describes matrix layout of input and output matrices. Column Major for
 // Matrix A, Row Major for Matrix B and Row Major for Matrix C
@@ -71,11 +71,11 @@ using SmArch = cutlass::arch::Sm80;
 
 // This code section describes the tile size a thread block will compute
 using ShapeMMAThreadBlock =
-    cutlass::gemm::GemmShape<128, 128, 256>;  // <- threadblock tile M = 128, N = 128, K = 256
+    cutlass::gemm::GemmShape<128, 128, 32>;  // <- threadblock tile M = 128, N = 128, K = 256
 // This code section describes tile size a warp will compute
-using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 256>;  // <- warp tile M = 64, N = 64, K = 256
+using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 32>;  // <- warp tile M = 64, N = 64, K = 256
 // This code section describes the size of MMA op
-using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 128>;  // <- MMA Op tile M = 16, N = 8, K = 128
+using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 16>;  // <- MMA Op tile M = 16, N = 8, K = 128
 
 // This code section describes how threadblocks are scheduled on GPU
 using SwizzleThreadBlock = cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>;  // <- ??

```

**Comment by YukeWang96** [comment]
> -    cutlass::gemm::GemmShape<128, 128, 256>;  // <- threadblock tile M = 128, N = 128, K = 256
> +    cutlass::gemm::GemmShape<128, 128, 32>;  // <- threadblock tile M = 128, N = 128, K = 256
>  // This code section describes tile size a warp will compute
> -using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 256>;  // <- warp tile M = 64, N = 64, K = 256
> +using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 32>;  // <- warp tile M = 64, N = 64, K = 256
>  // This code section describes the size of MMA op
> -using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 128>;  // <- MMA Op tile M = 16, N = 8, K = 128
> +using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 16>;

Is there any reference table for determining the value of these parameters, since I mostly find that different data types should have different parameters for these three fields. Thanks!

```
cutlass::gemm::GemmShape<128, 128, 32>;  // <- threadblock tile M = 128, N = 128, K = 256
 // This code section describes tile size a warp will compute
using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 32>;  // <- warp tile M = 64, N = 64, K = 256
 // This code section describes the size of MMA op
+using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 16>;  
```

**Comment by hwu36** [comment]
You can find plausible configurations by searching filenames containing "sparse" in https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/

also

profiler kernel generation scripts

fp16/bf16 16832 https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L1358-L1370
s8 16864 https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L1570-L1581
s4 168128 https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L1749-L1760
fp32 16816 https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L2055-L2067

For example
`[128, 64, 32], 3, [2, 2, 1]` means 128x64x32 threadblock tile size, 3 stages, 2x2x1 warps ((warp tile size) = (threadblock tile size) / (warp number) = [128/2, 128/2, 32/1]).

Common threadblock sizes are 256x128, 128x256, 128x128, 256x64, 64x256, 128x64, 64x128, 64x64.  We usually use 4 or 8 warps and common warp tile sizes are 64x64, 64x32, 32x64, 32x32.
