### ISSUE TITLE
[QST] Why int8 gemm only support row+col

### ISSUE THREAD

**Issue by linbinskn** [NVIDIA/cutlass#1030]
**What is your question?**
I found that int8 gemm implemented in cutlass only support A rowmajor and B colmajor currently. And in previous issue @hwu36 said it needs extra preprocess to support row+row. But from the mma m16n8k16 insturction and ldmatrix instruction description, it can support loading from shared and doing mma computation as fp16 without extra overhead. Seems ldmatrix + mma can be applied to both fp16 and int8. So if fp16 support row+row, why int8 can't?
The following is fp16 mma:
![image](https://github.com/NVIDIA/cutlass/assets/50486294/2751e6a5-690a-45bb-bfd6-ae56094e7616)
And int8 mma:
![image](https://github.com/NVIDIA/cutlass/assets/50486294/fe8f1070-3866-4563-bb27-daadc463cd2f)

**Comment by thakkarV** [comment]
As the int8 TV map shows, 4 elements along the K mode are packed together into a single 32b register. This entails a stride 1 along the K mode for both A and B. if the gmem does not have K major strides for A and B, a transpose must be performed on the fly to comply with this TV layout the architecture imposes.

**Comment by linbinskn** [comment]
> 

This does entail a stride 1 along K. The same problem should exist in fp16 while fp16 support row+row. And I think fp16 may using ldmatrix.trans with swizzle in shared memory to support row+row layout. If it is, int8 can be supported in same way with little modification?

**Comment by thakkarV** [comment]
LDSM doesn't support transpose for 8b operands, only 16b. That's why it can be done for fp16

**Comment by linbinskn** [comment]
> LDSM doesn't support transpose for 8b operands, only 16b. That's why it can be done for fp16

I see, It is indeed a troublesome matter. Thanks~

**Comment by linbinskn** [comment]
> LDSM doesn't support transpose for 8b operands, only 16b. That's why it can be done for fp16

I see, It is indeed a troublesome matter. Thanks~

**Comment by thakkarV** [comment]
will close this now as resolved, feel free to follow up with questions
