### ISSUE TITLE
[QST] Cutlass VS Pytorch GEMM performance

### ISSUE THREAD

**Issue by jahatef** [NVIDIA/cutlass#1032]
Trying to analyze benchmark results of GEMMs of size (2048, 4, 20608) x (20608, 82432), and see how tiling affects the performance. Cutlass GEMMs are much slower than Pytorch GEMMs. Cutlass GEMMs (using cutlass python interface) get around 5 TFLOP/s, while Pytorch GEMMs (calling `torch.nn.functional.linear`) offer 150-250 TFLOP/s. 

python code to spawn and time cutlass GEMMs:
```
   tiles = plan.tile_descriptions()

    if h >= 20608 and h <= 22272:
        td = tiles[0]
    else:
        td = tiles[1]
    plan.compile(td)
    m = 4
    k = (h*4)
    n = int(h)
    b=2048
    As, Bs, Cs, Ds, = generate_problems(b, m, n, k)
    num_warm = 0
    for i in range( num_warm + 1):
        if i == num_warm:
            start_time = time.time()
        plan.run(As, Bs, Cs, Ds, print_module=True)
    elapsed_time = (time.time() - start_time) / 20
    with open(file, 'a') as f:
        f.write(f"Elapsed time for {m}x{n}x{k}, b={b}: {elapsed_time:.4f}\n")
        f.write(f"Throughput (in TFLOP/s) for {m}x{n}x{k}, b={b}: "
            f"{(2 * b * m * n * k) / (elapsed_time * 10**12):.3f}\n") 
        f.write("-" * 80)
        f.write("\n")
```

python code to spawn PyTorch GEMMs:
```
def benchmark_mm(m, n, k, label, b=None, num_iterations=100):
    B = torch.randn((k, n)).half().to("cuda:0")
    if b is None:
        A = torch.randn((m, n)).half().to("cuda:0")
        C = torch.empty((m, k)).half().to("cuda:0")
        b = 1
    else:
        A = torch.randn((b, m, n)).half().to("cuda:0")
        C = torch.empty((b, m, k)).half().to("cuda:0")
    num_warmup_iterations = 50
    times = np.zeros(num_iterations+num_warmup_iterations)

    if label=="attention_linear_projection":
        torch.cuda.profiler.start()
    start_time = time.time()
    for i in range(num_warmup_iterations + num_iterations):
        with torch.no_grad():
            # torch.mm(A, B, out=C)
            torch.nn.functional.linear(A, B, out=C)
        torch.cuda.synchronize()
        times[i] = time.time()
    if label=="attention_linear_projection":
        torch.cuda.profiler.stop()
    times -= start_time
    times = np.diff(times)
    times = times[50:]
    median_time = np.median(times)
    print(f"Elapsed time for {label} ({m}x{n}x{k}, b={b}): {median_time:.4f}")
    print(f"Throughput (in TFLOP/s) for {label} ({m}x{n}x{k}, b={b}): "
          f"{(2 * b * m * n * k) / (median_time * 10**12):.3f}")
    return median_time
```

Also, Cutlass GEMMs have a much lower L2 cache hit rate of around 25%, whereas Pytorch achieves 40-80% L2 cache hit rate. (Through Nsight Compute)

What is the reason for the poor performance of Cutlass GEMMs? How can I make Cutlass GEMMs perform similarly to Pytorch GEMMs?

**Comment by jahatef** [comment]
Yes, I am using grouped GEMM. I was acting with the understanding that CUTLASS grouped GEMM was equivalent to Pytorch BMM. Here is the full script:

```import cutlass
import torch
import random
import time

dtype = torch.float16
plan = cutlass.op.GroupedGemm(element=dtype, layout=cutlass.LayoutType.RowMajor)

h = 20608 
m = 4
k = (h*4)
n = int(h)
b=2048
file = "cutlassBmmBenchMultipleTiles.txt"

def initialize(dtype, M, N, K):
    sizes = [(M, K), (K, N), (M, N), (M, N)]
    return [torch.randint(-3, 3, size, device='cuda').to(dtype) for size in sizes]

def generate_problems(problems, M, N, K):
    As, Bs, Cs, Ds = [], [], [], []
    A, B, C, D = initialize(dtype, M, N, K)
    for _ in range(problems-1):
        As.append(A)
        Bs.append(B)
        Cs.append(C)
        Ds.append(D)
        A, _, C, D = initialize(dtype, M, N, K)
    return As, Bs, Cs, Ds

for h in range(20608-64,20608+64,64): #range(20608-128, 22272+128+64, 64):
    tiles = plan.tile_descriptions()
    
    if h >= 20608 and h <= 22272:
        td = tiles[0]
    else:
        td = tiles[1]
    plan.compile(td)
    m = 4
    k = (h*4)
    n = int(h)
    b=2048
    As, Bs, Cs, Ds, = generate_problems(b, m, n, k)
    num_warm = 0
    for i in range( num_warm + 1):
        if i == num_warm:
            start_time = time.time()
        plan.run(As, Bs, Cs, Ds, print_module=True)
    elapsed_time = (time.time() - start_time) / 20
    with open(file, 'a') as f:
        f.write(f"Elapsed time for {m}x{n}x{k}, b={b}: {elapsed_time:.4f}\n")
        f.write(f"Throughput (in TFLOP/s) for {m}x{n}x{k}, b={b}: "
            f"{(2 * b * m * n * k) / (elapsed_time * 10**12):.3f}\n") 
        f.write("-" * 80)
        f.write("\n")


tiles = plan.tile_descriptions()

for i in range(100):
    td = tiles[i]
    plan.compile(td)
    As, Bs, Cs, Ds, = generate_problems(b, m, n, k)
    plan.run(As, Bs, Cs, Ds, print_module=True)
    num_warm = 10
    for i in range( num_warm + 20):
        if i == num_warm:
            start_time = time.time()
        plan.run(As, Bs, Cs, Ds, print_module=True)
    elapsed_time = (time.time() - start_time) / 20
    with open(file, 'a') as f:
        f.write(f"Tile description: \n {td} \n")
        f.write(f"Elapsed time for {m}x{n}x{k}, b={b}: {elapsed_time:.4f}\n")
        f.write(f"Throughput (in TFLOP/s) for {m}x{n}x{k}, b={b}: "
            f"{(2 * b * m * n * k) / (elapsed_time * 10**12):.3f}\n") 
        f.write("-" * 80)
        f.write("\n")```

**Comment by jackkosaian** [comment]
Thanks for clarifying and providing this script.

Grouped GEMM is a bit different from BMM.

In BMM, each matrix multiplication within the batch is of the same size (M x N x K). Furthermore, the batch of matrix operands are all be accessible from a common base pointer at fixed offsets. For example, if you have batch size of 3, the matrices as part of the batch for operand A may be located at `ptrA`, `ptrA + (M*K)`, `ptrA + (2*M*K)`.

In contrast, problems computed together as a single kernel in grouped GEMM can be of different sizes: we could run a GEMM of size (128 x 256 x 512) in the same kernel as a GEMM with size (1024 x 4096 x 128). Furthermore, each operand is located via a different pointer: for 3 GEMMs in a group, operands A may be located at `ptrA_0`, `ptrA_1`, `ptrA_2`.

For cases in which each problem is the same size and operands are located contiguously in memory, it's preferable to use batched GEMM. This can be done by using a normal `cutlass.op.Gemm` in the CUTLASS Python interface while setting the `batch_count` argument to your batch size (see [here](https://github.com/NVIDIA/cutlass/blob/4575443d446807b8e9d7f77185452899020ac8c9/python/cutlass/op/gemm.py#L464C4-L464C4)).

**Comment by jahatef** [comment]
I appreciate the help so far, thank you very much. Just a couple more questions:

now running like this
```
import cutlass
import torch
import random
import time

dtype = torch.float16
plan = cutlass.op.Gemm(element=dtype, layout=cutlass.LayoutType.RowMajor)

h = 20608 
m = 4
k = (h*4)
n = int(h)
b=2048
file = "cutlassBmmBenchMultipleTiles.txt"

def initialize(dtype, M, N, K, b):
    sizes = [(b, M, K), (K, N), (b, M, N), (b, M, N)]
    return [torch.randint(-3, 3, size, device='cuda').to(dtype) for size in sizes]


for h in range(20608-64,20608+64,64): #range(20608-128, 22272+128+64, 64):
    tiles = plan.tile_descriptions()
    
    if h >= 20608 and h <= 22272:
        td = tiles[0]
    else:
        td = tiles[1]
    plan.compile(td)
    m = 4
    k = (h*4)
    n = int(h)
    b=2048
    As, Bs, Cs, Ds, = initialize(dtype, m, n, k, b)
    num_warm = 10
    for i in range( num_warm + 20):
        if i == num_warm:
            start_time = time.time()
        plan.run(As, Bs, Cs, Ds, print_module=True, batch_count=b)
    elapsed_time = (time.time() - start_time) / 20
    with open(file, 'a') as f:
        f.write(f"Elapsed time for {m}x{n}x{k}, b={b}: {elapsed_time:.4f}\n")
        f.write(f"Throughput (in TFLOP/s) for {m}x{n}x{k}, b={b}: "
            f"{(2 * b * m * n * k) / (elapsed_time * 10**12):.3f}\n") 
        f.write("-" * 80)
        f.write("\n")
```
I get a `RuntimeError: CUDA Error cudaError_t.cudaErrorMisalignedAddress` error. Am I running with the correct dimensions?

What is the meaning of the tensor_D parameter? To my understanding C = AB. But I do now know where D comes into play.

Thank you so much for the help!

**Comment by jackkosaian** [comment]
Thanks for posting this whole script. This actually reveals some missing functionality in the CUTLASS Python interface. I have a fix in progress which I will post once it has been verified. Thanks!

>What is the meaning of the tensor_D parameter? To my understanding C = AB. But I do now know where D comes into play.

CUTLASS GEMM operations are "general matrix multiplies" of the form:
```
D = (alpha * A * B) + (beta * C)
```
where:
```
A is M x K
B is K x N
C is M x N
D is M x N
alpha is scalar
beta is scalar
```

This follows the [traditional formulation of GEMM](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms#Level_3), but separating out `C` and `D` so that `C` is not necessarily updated in place.

**Comment by jackkosaian** [comment]
Hi, @jahatef. The fix for the misaligned address error has been pushed. Could you try again after pulling the latest version of CUTLASS?

Note that you now no longer need to specify `batch_count` in `plan.run()`, as this is inferred from the input tensors. Thus, your call to `plan.run()` should now be:

```python
plan.run(As, Bs, Cs, Ds, print_module=True)
```
(although, you may want to drop `print_module=True`, as this is primarily for debugging purposes)

**Comment by mnicely** [comment]
@jahatef has your issue been resolved?

**Comment by jahatef** [comment]
Sorry, yes, this issue is resolved. Thank you for your swift response, and tolerating my slow reply.
