### ISSUE TITLE
[QST] Batched Gemm how to split k

### ISSUE THREAD

**Issue by wukong1992** [NVIDIA/cutlass#1033]
**What is your question?**
There are batched gemm and splitgemm respectively, but there is no combination of the two. When the batch size is small, e.g. input A(2, 32, 10000) B(2, 10000, 32) , the grid num will be 2, and sm effencicy is low.

**Comment by hwu36** [comment]
The cases that need both are less common.  If you really need it, you need to modify the kernel level gemm_universal.h to support it.  Just add a new mode that can do both the other modes can do.  You grid.k dimension needs to be used for both batch and splitk.

**Comment by wukong1992** [comment]
@hwu36 Thank you, I read the src code of cutlass, supportting this case is not hard. But I code in torch.einsum op, and torch dispatch to aten:bmm, I read through torch code, bmm is dispatched to cublas, cause cublas is opaque, so I don't know how cublas to cutlass, and how to extend to use my custom op.

**Comment by wukong1992** [comment]
I get the trace of bmm, and now there is no way to control the cublas to call custom cutlass op. Hopefully,  there will be one day torch's cuda op implementation use cutlass directly.
