### ISSUE TITLE
[QST]How to use Swizzle to design memory layout while using TensorCore MMA

### ISSUE THREAD

**Issue by fecet** [NVIDIA/cutlass#1038]
First off, I'd like to commend the ingenious design of the swizzle layout in the `CuTe` module. It's truly remarkable! 

For my specific use case, I am looking to perform some optimizations for the A100 fused kernels, and my intention is to build upon `CuTe`. However, I've noticed that within `CuTe`, the SM80 Traits (considering `MMA_Traits<SM80_16x8x8_F32TF32TF32F32_TN>` as an example) make an assumption of a k-major layout for matrices A and B. Here are the main points I'm grappling with:

1. Let's consider a basic scenario - the copying process from gmem to smem. It's apparent that one needs to design the layout for smem. From my preliminary understanding of the `CuTe` documentation and code, this process seems to involve a composition of `Swizzle` and `Layout`. What I'm keen on understanding is the pattern of how swizzle operates on layout. More explicitly, how can I determine the swizzle based on a desired layout (like the one in the `cutlass GTC slides`)? In other words, given two layouts (potentially both being 2D), how can I identify a swizzle such that `composition(swizzle, layout_input) = layout_output`?
![image](https://github.com/NVIDIA/cutlass/assets/41792945/5a7c258c-3471-450c-8105-88247c72a29d)

2. Since the gmem -> smem step has jumbled the layout, consider matrix A under TN. It's evident that it doesn't adhere to the default `SM80TNTrait`'s k-major assumption. By my understanding, I should be employing a $\text{swizzle}^{-1}$ to "unswizzle" the ALayout within MMATraits (for instance, `MMA_Traits<SM80_16x8x8_F32TF32TF32F32_TN>`). This is so that my swizzled smem can map back to the k-major 2d-layout to subsequently build a standard MMA_Atom. Is my understanding correct? If so, how can I accomplish this "unswizzle" transformation, and which function should I utilize?

Thank you in advance for any guidance on this matter. Your expertise will significantly aid my optimization efforts.

**Comment by ccecka** [comment]
1. It just takes practice to explicitly write out layouts. I recommend using `print_layout` and `print_latex` to aid in the visualization. The layout you've shown in the image appears to be
```
auto smem_atom = composition(Swizzle<2,0,3>{}, Layout<Shape<_4,_8>,Stride<_8,_1>>{});
```
which indeed produces
[layout.pdf](https://github.com/NVIDIA/cutlass/files/12384807/layout.pdf)
and you can then `tile_to_shape` to whatever you like. Note this is a 4x8 logical layout though, doesn't say anything about how the threads will partition it (and gmem) and actually perform the storage. That partitioning is performed by other Copy_Atoms or MMA_Atoms, which can be designed independently from the SMEM Layouts.

2. The MMAs are named "NT" and "TN" but they can partition any layout of data, such as the layout above. Again, you can use `print_latex` to visualize how this partitioning will occur (and hopefully design your SMEM Layout so that partitioning is "good"). No "unswizzleing" or anything layout-aware needs to occur, just construct your particular SMEM Layout and partition it with the mma, following the recipe in the CUTLASS SM80 Collective.

**Comment by mnicely** [comment]
@fecet has your issue been resolved?

**Comment by fecet** [comment]
Thanks for your help, that solve my question.

**Comment by irasin** [comment]
> 1. It just takes practice to explicitly write out layouts. I recommend using `print_layout` and `print_latex` to aid in the visualization. The layout you've shown in the image appears to be
> 
> ```
> auto smem_atom = composition(Swizzle<2,0,3>{}, Layout<Shape<_4,_8>,Stride<_8,_1>>{});
> ```
> 
> which indeed produces [layout.pdf](https://github.com/NVIDIA/cutlass/files/12384807/layout.pdf) and you can then `tile_to_shape` to whatever you like. Note this is a 4x8 logical layout though, doesn't say anything about how the threads will partition it (and gmem) and actually perform the storage. That partitioning is performed by other Copy_Atoms or MMA_Atoms, which can be designed independently from the SMEM Layouts.
> 
> 2. The MMAs are named "NT" and "TN" but they can partition any layout of data, such as the layout above. Again, you can use `print_latex` to visualize how this partitioning will occur (and hopefully design your SMEM Layout so that partitioning is "good"). No "unswizzleing" or anything layout-aware needs to occur, just construct your particular SMEM Layout and partition it with the mma, following the recipe in the CUTLASS SM80 Collective.

Hi, @ccecka, sorry to bother you here, I was wondering what the meanings of 2, 0, 3 in `Swizzle<2, 0, 3>` and how should I get theses numbers from the original image.

refer to the definition of Swizzle in https://github.com/NVIDIA/cutlass/blob/main/include/cute/swizzle.hpp, I found it used words like "bits", does it have some connection with memory address or something?
I would really appreciate it if you could give some explanation here.

**Comment by irasin** [comment]
I was very confused about the comments of Swizzle

```cpp
// A generic Swizzle functor
/* 0bxxxxxxxxxxxxxxxYYYxxxxxxxZZZxxxx
 *                               ^--^ MBase is the number of least-sig bits to keep constant
 *                  ^-^       ^-^     BBits is the number of bits in the mask
 *                    ^---------^     SShift is the distance to shift the YYY mask
 *                                       (pos shifts YYY to the right, neg shifts YYY to the left)
 *
 * e.g. Given
 * 0bxxxxxxxxxxxxxxxxYYxxxxxxxxxZZxxx
 * the result is
 * 0bxxxxxxxxxxxxxxxxYYxxxxxxxxxAAxxx where AA = ZZ xor YY
 */
```

Can you give an example of what `0bxxxxxxxxxxxxxxxYYYxxxxxxxZZZxxxx` stands for?

**Comment by ccecka** [comment]
`Swizzle` is a binary operation on the offset produced from a `Layout` or on a pointer within a `Tensor`. It operates on the bits of the offset or pointer and is parameterized by the three integers shown.

`0b` is a C++ binary literal.
https://en.cppreference.com/w/cpp/language/integer_literal

**Comment by irasin** [comment]
Thanks a lot, it is an amazing design!
