### ISSUE TITLE
std::complex<NonFloating> is non-Standard

### ISSUE THREAD

**Issue by StephanTLavavej** [NVIDIA/cutlass#104]
The C++ Standard (from C++98 to the current Working Paper [N4861](https://wg21.link/n4861)) says in [[complex.numbers]/2](https://eel.is/c++draft/complex.numbers#2) that "The effect of instantiating the template `complex` for any type other than `float`, `double`, or `long double` is unspecified." (This is the case even if the type attempts to imitate a Standard floating-point fundamental type.)

In MSVC's STL (where I'm a maintainer), we're attempting to [implement a warning](https://github.com/microsoft/STL/pull/889) about `std::complex<NonFloating>`, but we've found that Cutlass contains a few uses of this. We have an escape hatch/workaround, but we thought you'd like to know about this non-Standard usage of `std::complex`. I see at least two issues in the source code.

First, the warning that we initially observed was that `test/unit/util/complex.cu` instantiates `std::complex<cutlass::half_t>`. The comment says `Uses std::complex as a reference.` and the usage is very simple (just add/sub/mul/div) so I believe that handwritten code could be used as a reference for correct behavior:
https://github.com/NVIDIA/cutlass/blob/fd7e058d0cb3e4bf743edc530c7778a210cb168b/test/unit/util/complex.cu#L35-L37
https://github.com/NVIDIA/cutlass/blob/fd7e058d0cb3e4bf743edc530c7778a210cb168b/test/unit/util/complex.cu#L47-L48
https://github.com/NVIDIA/cutlass/blob/fd7e058d0cb3e4bf743edc530c7778a210cb168b/test/unit/util/complex.cu#L99

Second, while searching your codebase for uses of `std::complex`, I found a potential bug.

https://github.com/NVIDIA/cutlass/blob/fd7e058d0cb3e4bf743edc530c7778a210cb168b/tools/library/src/util.cu#L1180-L1190

The middle line here says `*reinterpret_cast<std::complex<tfloat32_t>*>(bytes.data())` which I suspect is a copy-paste mistake given the surrounding lines. The rest of the file reinterprets to `cutlass::complex<tfloat32_t>`:

https://github.com/NVIDIA/cutlass/blob/fd7e058d0cb3e4bf743edc530c7778a210cb168b/tools/library/src/util.cu#L713-L720
https://github.com/NVIDIA/cutlass/blob/fd7e058d0cb3e4bf743edc530c7778a210cb168b/tools/library/src/util.cu#L859-L869

**Comment by kerrmudgeon** [comment]
Thank you. We will be fixing this issue in the next CUTLASS release. Stay tuned.

**Comment by kerrmudgeon** [comment]
Closing as fixed in CUTLASS 2.3. Feel free to reopen if this warning - or any others detected by MSCV - remains in the code.

Thanks!

**Comment by StephanTLavavej** [comment]
Wonderful, thank you!
