### ISSUE TITLE
[BUG]fix CMakeLists.txt typo

### ISSUE THREAD

**Issue by zjjott** [NVIDIA/cutlass#1046]
**Describe the bug**
I Found there is a typo in CMakeCache
```
//Enable CUTLASS Tests
CUTLASS_ENABLE_TESTS:BOOL=ON}
```

It is caused by CMakeLists.txt, 
https://github.com/NVIDIA/cutlass/blob/main/CMakeLists.txt#L110
```
set(CUTLASS_ENABLE_TESTS_INIT ${CUTLASS_ENABLE_LIBRARY}})
```
there are two closing bracket

**Expected behavior**
it should be `CUTLASS_ENABLE_TESTS:BOOL=ON`

can I fix  using one PR it?

**Comment by mnicely** [comment]
Closed in v3.2
