### ISSUE TITLE
Why we are not able to get 100% utilization of tensor cores?

### ISSUE THREAD

**Issue by mkhairy** [NVIDIA/cutlass#105]
Hello,

I am wondering, why we are not able to get 100% utilization of tensor cores in CUTLASS or even CuBLAS. This was a problem in Volta, and I thought this is fixed in  Ampere with the new memcpy async and the optimizations you made. However, I looked at the CUTLASS presentation in GTC (the slide is shown below), still, the achievable GFLOPS is 240 GFLOPS/sec (77% of the maximum 310 GFLOPS/sec in Ampere). And, I think the problem is in CuBLAS as well, as you showed in the presentation that CUTLASS is within 95% of CuBLAS. So, CuBLASS probably is 250  GFLOPS/sec. 

My question, what is the reason (software or hardware) that we are not able to get 100% utilization of the tensor cores? especially we are able to achieve the maximum throughput for single-precision FP32 (99% utilization in Volta with CUTLASS or CuBLAS), but not for tensor cores.

![Screenshot from 2020-06-29 13-49-47](https://user-images.githubusercontent.com/6247665/86038764-734e2b80-ba0f-11ea-8c5f-a9ac63bc671a.png)

**Comment by timespacce** [comment]
Performance is task dependent - it is relative to the computation task and its parameters. 

**1. Computation task relativity**
The tiled GEMM-algorithm lets each thread block to compute a sub-solution of the whole GEMM. And each thread computes a sub-sub-solution. After each thread has computed a GEMM of size like (Q x 1) * (1 x Q) a new tile of data has to be loaded. The trick is to maximize the number of computation instructions and minimize the number of memory loads and stores. If your computation task consists in computing more than just a (Q x 1) * (1 x Q) GEMM per thread, then the ratio between computation instructions and memory loads/stores would be better than that of the standard GEMM and thus a higher peak performance would be achieved.

**2. Parameter sensibility**
cuBLAS and cuTLASS are amazing for square matrixes. But for example in computer vision and speech recognition the matrixes have many rows and few columns. 3x3x1024 convolution on 512x512x256 input needs to transform directly or indirectly the input in 262144x2304 matrix and multiply it with a 2304x1024 one. Thats why practical tasks like convolutions have around 5-10 TFLOP/s on V100 with activated tensor cores. In RNNs the peak performance is even smaller compared to the theoretically best.

Best Wishes,
James.

**Comment by hwu36** [comment]
CUDA 11.3 significantly improves the performance of Ampere/Turing/Volta Tensor Core kernels. See #241 .

You may want to do the benchmarking again with the latest compiler.

CUTLASS may not be able to achieve 100% SOL on Ampere, but it can get to 96%. :smile:
