### ISSUE TITLE
[QST] Why use blockIdx.z as the indexing method for batch

### ISSUE THREAD

**Issue by piDack** [NVIDIA/cutlass#1050]
**What is your question?**

In CUDA the range of blockIdx.z is [1-65535],blockIdx.x has a bigger range,why blockIdx.z is used as the index of batch in CUTLASS when gemm_universal mode=batch.

```c++
      ptr_A += threadblock_tile_offset.k() * params.batch_stride_A;
      ptr_B += threadblock_tile_offset.k() * params.batch_stride_B;
```

If blockIdx.x and blockIdx.y=1 in some special case, then is it reasonable if I use blockIdx.x as batch index by changing the code.

thanks.

**Comment by piDack** [comment]
It will cause performance slow down

**Comment by hwu36** [comment]
you need to change threadblock layout algorithms accordingly if you change the usage of grid dimensions.
