### ISSUE TITLE
[QST] How to understand "SmemLayoutAtom" in cute.

### ISSUE THREAD

**Issue by linbinskn** [NVIDIA/cutlass#1051]
**What is your question?**
Hello, I am impressed with the abstraction of cute and I try to customize kernel by using cute. I see `SmemLayoutAtom` In file default_gemm_configuration.hpp, it is defined as below
```
// F16: 128-by-128-by-64
using SmemLayoutAtom = decltype(
    composition(Swizzle<3,3,3>{},
                Layout<Shape < _8,_64>,
                       Stride<_64, _1>>{}));
```
However, I am confused with (8, 64) in Layout, what is the exact meaning of it. Is it can map to something in gpu memory multi-hierarchy?

**Comment by thakkarV** [comment]
That's just the logical (MN, K) shape of this layout, M or N depending on whether this smem layout is for A or B tensor.

**Comment by linbinskn** [comment]
> That's just the logical (MN, K) shape of this layout, M or N depending on whether this smem layout is for A or B tensor.
Actually I was confused with why setting (8, 64) here. For example, the shape should be (4, 64) if it represent warp level shape since tile size k of threadblock level is 64, 8 threads needed to process per row and 4 rows can single warp process. And if it represents threadblock(128 threads) level tile per iteration, the shape should be (16, 64) here since 8 threads needed to process per row and 16 rows can single threadblock process per iteration. However, the shape here is (8, 64). It means neither this shape is for warp nor for threadblock.

**Comment by thakkarV** [comment]
Correct.  This shape has nothing to do with mapping to any thread hierarchy. Just a layout atom for the smem data. All partitioning by the overlay threads of copy are done within the kernel on the full smem tensor. This is just the smem layout atom

**Comment by linbinskn** [comment]
So why we need it as it has nothing to do with mapping to any thread hierarchy? Can it mapping to instruction combined with thread arrangement and loop iteration(e.g. ldmatrix(.x=4) and iteration is 2).

**Comment by ccecka** [comment]
The SmemAtoms are simply the smallest layouts that encapsulate the swizzle pattern desired. These layouts will be repeated until the desired tile shape is reached. They are only a convenience and are helpful for defining larger layouts that can be defined in terms of (replications of) smaller layouts.

**Comment by mnicely** [comment]
@linbinskn has your issue been resolved?

**Comment by linbinskn** [comment]
> @linbinskn has your issue been resolved?

Yes, thanks!
