### ISSUE TITLE
[QST] What's tA/tB/tC short for in cute's example?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#1052]
**What is your question?**
Hello! I'm learning cute through ```media/docs/cute``` and ```examples/cute```. It took me some time to understand the meaning of the variable name ```tCsA```. From my understanding, it refers to a view of ```A``` on shared memory with a layout described in ```tC```. However, the variable name still confuses me a bit. Could you please clarify what is ```tC``` short for?

**Comment by thakkarV** [comment]
tC refers to the layout of the overlay threads of MMA. We read tCsA as the smem tensor A as partitioned by the overlay thread layout of C (mma)

**Comment by umiswing** [comment]
Thanks! For others who have the same question, please refer to https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/0x_gemm_tutorial.md#thread-layouts
