### ISSUE TITLE
[QST] How to use arbitrary layout collocations for operands in cutlass?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#1054]
Hi, I am using cutlass 2.x's gemm in my research. However, It seems that some operators in cutlass 2.x only have some fixed layout collocations.
In cutlass 2.x, because element-wise epilogue must use Row-Major data and gemm's epilogue is always element-wise, the gemm's result is always Row-Major which means `LayoutOut = cutlass::layout::RowMajor"`.
For `fp64 * fp64 = fp64` and `fp16 * fp16 = fp32`, they can use all the combinations of `LayoutInputA` and `LayoutInputB` which are `row * row`, `row * col`, `col * row` and `col * col`.
However, for `int8 * int8 = int32` and `int4 * int4 = int32`, they can only use the layout of `row * col = row`, which makes them really hard to use in real application.
So is there any way to solve this problem? Or should I go to use cutlass 3.x? 
Sincerely thank you for your help!

**Comment by hwu36** [comment]
The reason is that ldmaxtrix can only transpose 16 bit data, not 8 bit or 4 bit on ampere or hopper or turing.  cutlass 3.x cannot help either since it's hw restriction.

You could use a seperate kernel to transpose before gemm.  As to 8bit, you could use simt idp4a kernels which supports all the layout combinations.

**Comment by Ther-LF** [comment]
That's helpfule, @hwu36 . I have a clear understanding of my current situation.
By the way, you said that cutlass will use `ldmatrix` to transpose matrix. Does that mean that for `col * row = row`, we need to transpose operand A and operand B respectively to get `row * col = row`, and then calculate it? Is this due to the limitation of gemm memory access strategy or some hardware limitation? This question may be out of the scope of cutlass, but I'm still curious about it, can you please explain a little bit?
Besides, I searched for information about `idp4a` and it semms like `idp4a` is a simt instruction that runs on CUDA core. How do we set up cutlass to use `idp4a`? Like `MMAOp = cutlass::arch::OpClassSimt`?

**Comment by hwu36** [comment]
all tensor core instructions are row x col.  we need ldmatrix to transpose if the input is not row x col

> Besides, I searched for information about idp4a and it semms like idp4a is a simt instruction that runs on CUDA core. How do we set up cutlass to use idp4a? Like MMAOp = cutlass::arch::OpClassSimt?

correct.

**Comment by Ther-LF** [comment]
OK, Thank you very much!
