### ISSUE TITLE
[QST]Why interleaved layout can improve the performance int8 gemm

### ISSUE THREAD

**Issue by linbinskn** [NVIDIA/cutlass#1055]
**What is your question?**
It seems interleaved layout have better performance in int8 kernel compared to NT layout. I think the reason might be interleaved layout can make full use of global memory cache line without the need of large k tile size in thread block level. Is that right?

**Comment by hwu36** [comment]
you mean TN instead of NT?

**Comment by linbinskn** [comment]
A is mxk, B is nxk.
Interleaved layout can achieve better performance compared to it in int8 gemm kernel.

**Comment by hwu36** [comment]
TN = row x col

NT = col x row

**Comment by linbinskn** [comment]
> TN = row x col
> 
> NT = col x row

I see, this layout should be TN. Can you explain the reason why Interleaved layout can achieve better performance compared to TN?

**Comment by mnicely** [comment]
@linbinskn has your issue been resolved?
