### ISSUE TITLE
[QST] Does the problem size of cutlass have to be aligned?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#1058]
Hi, currently I am using cutlass 2.x, and I find that when I want to use an **arbitrary problem size** like Cublas Gemm, I ran into an error: `Error Misaligned Operand`, even though I have used **aligned leading dimension** for operands. 
I try to use cuda-gdb to find the problem, and I find that the reason for the problem is that **iterator (IteratorA, IteratorB, OutputIterator) can only configure aligned problem size**.
Due to this issue, we cannot directly replace the cublas gemm with the cutlass gemm, so I am wondering does the problem size of cutlass have to be aligned? 
Sincerely thank you for your help! :-)

**Comment by Ther-LF** [comment]
Besides, is the problem size aligned to 128bit? If yes, why 128bit? After all, the size of a coalesced access in global memory be 32 bytes (256 bit).

**Comment by hwu36** [comment]
we support small alignment gemm and convolutions.  we have templates to control the alignments.  See https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/device/gemm_universal.h#L113-L119 for example.

**Comment by Ther-LF** [comment]
Sorry for the late reply, @hwu36 . I have solved this problem according to your suggestion. 
We can make cutlass support different alignment gemms by modifying the `AlignmentA` and `AlignmentB` parameters in the Gemm template class and modifying the `Count` parameter in the Epilogue template class.
If we set them all to 1, we can solve any size problem with cutlass.
Thank you for your help! :-)
