### ISSUE TITLE
[FEA] how to implement f16 * s8 GEMM

### ISSUE THREAD

**Issue by jinluyang** [NVIDIA/cutlass#1060]
Hello, I am new to cutlass, and looking for a way to implement [A=f16] * [B=s8] GEMM. In my plan, the target kernel should either do quantization of A onchip and then do a int8 GEMM. Or do a dequantization of B onchip and do a float16 GEMM. The reason to do this is similiar to this issue https://github.com/NVIDIA/cutlass/issues/948
Although cutlass_profiler can let us specify different datatype for A and B, but if I specify A and B with different datatypes for each other, I couldn't get a result.
I couldn't find any implementation elsewhere. May I ask for some help on this please.

**Comment by mnicely** [comment]
Hi @jinluyang, we are working on this an plan to provide an implementation and example in the next release

**Comment by hwu36** [comment]
if you want an ampere one, check https://github.com/NVIDIA/cutlass/discussions/911

**Comment by mnicely** [comment]
Resolved with v3.4 release
