### ISSUE TITLE
[QST] Generate ptx from cutlass_profiler

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/cutlass#1067]
Hi, 

I am curious if there is a way to generate ptx code from cutlass profiler run directly, if not, what would be a way to generate a ptx code from a cutlass gemm implementation in general? 

Thanks.

**Comment by hwu36** [comment]
cuobjdump --dump-ptx ***.o

**Comment by MustafaFayez** [comment]
Thanks. 
Also, for anyone interested in that, you can add this to the cmake cmd while building cutlass_profiler:
 
![image](https://github.com/NVIDIA/cutlass/assets/7977794/c9d60dd0-f11b-4882-9fef-8d6ff1d7e375)

and inspect the ptx and sass of that using nsight compute.
