### ISSUE TITLE
[BUG] A wrong definition of `EpilogueArguments`

### ISSUE THREAD

**Issue by chhwang** [NVIDIA/cutlass#1075]
**Describe the bug**

On the current main branch ([e01b9b5](https://github.com/NVIDIA/cutlass/commit/e01b9b5029b7caca5a43c29f7d2714d7cf1dcae8)), `EpilogueArguments` is defined as `typename CollectiveEpilogue::Params` [here](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/sm90_gemm_tma.hpp#L108). Looks like it should be defined as `typename CollectiveEpilogue::Arguments` from the context.

**Steps/Code to reproduce bug**
I have not checked if this actually raises any errors.

**Expected behavior**
None

**Environment details (please complete the following information):**
None

**Additional context**
None

**Comment by mnicely** [comment]
Thanks for pointing this out. We'll get it fixed soon.

**Comment by thakkarV** [comment]
will be fixed in the next patch release

**Comment by mnicely** [comment]
Coming to 3.2.1 this week
