### ISSUE TITLE
[QST] How to write a split-K kernel on H100

### ISSUE THREAD

**Issue by chengyupku** [NVIDIA/cutlass#1079]
Hi,
I'm looking to write an efficient split-k kernel for H100. H100's new features like TMA load and WGMMA are used in CUTLASS 3, but split-k kernels like `kernel::GemmWithKReduction` are implemented in CUTLASS 2.x. It seems that I have to reimplement split-k kernels for CUTLASS 3, which could be time-consuming. 
Could you please provide a more efficient approach?

**Comment by jackkosaian** [comment]
HI, @chengyupku .

Split-K is enabled in CUTLASS 3 through the stream-K feature. You can set the `splits` parameter of the `Arguments` structure to make stream-K function like split-K.

The `splits` argument is found [here](https://github.com/NVIDIA/cutlass/blob/34bbadd3ff255cd5e6fe07e9281441b0b1d1be96/include/cutlass/gemm/kernel/sm90_tile_scheduler_stream_k.hpp#L120), and an example of using stream-K is [here](https://github.com/NVIDIA/cutlass/blob/34bbadd3ff255cd5e6fe07e9281441b0b1d1be96/examples/49_hopper_gemm_with_collective_builder/49_collective_builder.cu#L627-L636).

One note: we are actively making improvements to the CUTLASS 3.x stream-K. The current version is meant to provide functionality alone.

**Comment by chengyupku** [comment]
> HI, @chengyupku .
> 
> Split-K is enabled in CUTLASS 3 through the stream-K feature. You can set the `splits` parameter of the `Arguments` structure to make stream-K function like split-K.
> 
> The `splits` argument is found [here](https://github.com/NVIDIA/cutlass/blob/34bbadd3ff255cd5e6fe07e9281441b0b1d1be96/include/cutlass/gemm/kernel/sm90_tile_scheduler_stream_k.hpp#L120), and an example of using stream-K is [here](https://github.com/NVIDIA/cutlass/blob/34bbadd3ff255cd5e6fe07e9281441b0b1d1be96/examples/49_hopper_gemm_with_collective_builder/49_collective_builder.cu#L627-L636).
> 
> One note: we are actively making improvements to the CUTLASS 3.x stream-K. The current version is meant to provide functionality alone.

thank you :)
