### ISSUE TITLE
BUILD fails on changing Thread Block tile size.

### ISSUE THREAD

**Issue by navdeepkk** [NVIDIA/cutlass#108]
**This may not even be an issue, perhaps something that I didn't get right. Appologies if that is the case.** 

For the example "08_turing_tensorop_gemm", I was trying to do a tensorop using half precision inputs and single precision accumulation, so I changed the example to something like.

 ```
 using ElementAccumulator = float;                 // <- data type of accumulator
  using ElementComputeEpilogue = ElementAccumulator;  // <- data type of epilogue operations
  using ElementInputA = cutlass::half_t;                       // <- data type of elements in input matrix A
  using ElementInputB = cutlass::half_t;                       // <- data type of elements in input matrix B
  using ElementOutput = float;                      // <- data type of elements in output matrix D
   
  // The code section below describes matrix layout of input and output matrices. Column Major for
  // Matrix A, Row Major for Matrix B and Row Major for Matrix C
  using LayoutInputA = cutlass::layout::RowMajor;
  using LayoutInputB = cutlass::layout::ColumnMajor;
  using LayoutOutput = cutlass::layout::ColumnMajor;
 
The opsize is 1024x1024x1024 and the remaining config is,
  // This code section describes the tile size a thread block will compute
  using ShapeMMAThreadBlock =
            cutlass::gemm::GemmShape<32, 32, 96>;  
  // This code section describes tile size a warp will compute
  using ShapeMMAWarp = cutlass::gemm::GemmShape<32, 32, 32>; 
  // This code section describes the size of MMA op
  using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 8>;  
```

The TB tile size seems to be unnatural but, I think its valid. The build fails with error from top of the stack as
cutlass/include/cutlass/layout/tensor_op_multiplicand_sm75.h(88): error: division by zero
          detected during:
instantiation of class "cutlass::layout::TensorOpMultiplicand<ElementSize, Crosswise> [with ElementSize=16, Crosswise=96]".
**Attatched the complete error.**[log.txt](https://github.com/NVIDIA/cutlass/files/4943447/log.txt)

If I change The TB tile size to <96,32,32>, keeping other parameters same, The build is successfull but the result is incorrect. One more thing that I noticed was that the code compiles for certain TB tile sizes with a particular data layout(row/col) of the input tensors, while for some other layout it just fails.

Shouldn't `CuTLASS` compile and give correct outputs for any valid tile size that I choose? Is there something I am missing?
Thanks!

**Comment by hwu36** [comment]
Hi Navdeep,

There are some restriction of tile sizes supported by CUTLASS.  Generally, each dimension of Threadblock and warp tile sizes need to be power of two.  If the k dimension of Threadblock size is not equal to the k dimension of warp tile size, the intra-threadblock slicing will be triggered.  Generally, the intra-threadblock slice number (threadblock_k / warp_k) would also need to be power of two.  Each dimension of Threadblock tile size or warp tile size cannot be too large or too small.   Also on Turing, the Threadblock K is usually equal to 4 times the k dimension of the tensor core instruction, e.g., 32 for 16x8x8 half tensor core instruction.

You can check our unit tests in different levels (e.g. https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/warp/gemm_sm75.cu, https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/threadblock/mma_pipelined_sm75.cu, https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_f16n_f16n_f16t_tensor_op_f32_sm75.cu) and cutlass profiler for all the supported tile sizes.  Common Threadblock tile sizes are 256x128, 128x128, 128x64, 256x64, 64x64.  Common warp tile sizes are 64x64, 64x32, 32x32.  We usually use 4 warps or 8 warps per Threadblock.

Some CUTLASS kernels have less restrictions, but usually relaxing the above restrictions needs to change the source code.  

Regards,

Haicheng

**Comment by navdeepkk** [comment]
Hi Haicheng,

Thanks for the reply, It is really informative. However, I have one question and sorry again if it sounds too naive. What is the Intra-threadblock slice? Doesn't the number of partitions in the threadblock tile depend only on the (m,n) dimensions of both the thread-block and warp tile. For example, see this [TbTile.pdf](https://github.com/NVIDIA/cutlass/files/4945875/TbTile.pdf). The difference that I can figure-out when the TB-tile size in K-dim is a multiple of the K-dim of warp-tile, is that a single warp now has different partitions of Atile and Btile that it has to process. Is that what you refer to as a Intra-Threadblock slice?

Thanks!

**Comment by hwu36** [comment]
I think you got the idea.

Check the WarpCount of a Threadblock

https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/gemm/threadblock/default_mma_core_sm75.h#L97

Inside a Threadblock tile, we can further partition the tile in the k dimension and assign different parts to different warps to increase the warp level parallelism.  We just need to do some reduction (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue.h#L239) at last to add the accumulators belonging to different warps in the k dimension before writing the results to the global memory.

**Comment by navdeepkk** [comment]
Okay now I get what you are saying. Thanks for the pointers. One more thing that caught my attention though, cutlass_profiler provides almost no flexibility to set warps_m, warps_n, warps_k for the turing tensorop. Seems like the profiler only generates only a few TB sizes and only a single warp shape for each of the TB [File](https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/tools/library/scripts/generator.py#L508). Is there any particular reason for this, perhaps the chosen warp shapes perform the best? 

Thanks!

**Comment by hwu36** [comment]
Yes, only the efficient ones are included in the profiler.  If you want to take an adventure, you can add yours in https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/tools/library/scripts/generator.py#L510

**Comment by navdeepkk** [comment]
Hi @hwu36,

Just found some quick hacks/workarounds(not perfect) to insert some of the tile sizes that I wanted to try out. But there are still some problems.
1.  The script tools/library/scripts/generator.py is not capable of generating different warp level configurations for the same TB tile, for example say for a TB tile of size [128,128,32], I want to genrate 2 warp configurations [4,4,1] and [2,2,1]. The script would just genrated the config whichever was listed first in the list. 
2.  I found the reason for this was some filter checks for the kernel name. So I changed the line https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/tools/library/scripts/gemm_operation.py#L85 to, 
`inst_shape = "%d%d%d" % tuple(self.tile_description.math_instruction.instruction_shape)`
`inst_shape += math_op_string`
`inst_shape += "%d%d%d" % tuple(self.tile_description.warp_count)`
so that the generated kernel would include the warp config in its name and the filter checks would pass and `generator.py` script generates the kernel.
3. The kernel is generated but now the --waprs_m --waprs_n --waprs_k switch doesn't work while invoking cutlass_profiler. If I run an instance of the profiler with a particular TB tile size it just runs all the instances of the warp tiles that are available for it. 

Any suggestions where the source needs to be changed to make the profiler aware of the different instances of the warp level configuration.

Thanks !

**Comment by hwu36** [comment]
You can follow --cta_m --cta_n, --cta_k  to make warps_m, warps_n, warps_k work.

**Comment by navdeepkk** [comment]
Hi @hwu36, sorry didn't exaclty get what you are trying to say.

**Comment by hwu36** [comment]
I think you are saying that command line flags --waprs_m --waprs_n --waprs_k  do not work for you.  So, you can follow the code behind flags  --cta_m --cta_n, --cta_k to make --waprs_m --waprs_n --waprs_k  work for your case.
