### ISSUE TITLE
[BUG] fused_two_gemms: Is equality of major and minor version needed?

### ISSUE THREAD

**Issue by FabianSchuetze** [NVIDIA/cutlass#1081]
**Describe the bug**
The `test_run.h` [file](https://github.com/NVIDIA/cutlass/blob/main/examples/13_two_tensor_op_fusion/test_run.h#L69) requires the major and minor arch version to be *equal* to a set input (75 and 80), see:
```
  if (!(props.major == arch_major && props.minor == arch_minor)) {
    supported = false
   };
```
Is the equality really needed or could a great-or-equal test suffice? 

If created a tiny PR with the suggested changed, see https://github.com/NVIDIA/cutlass/pull/1082

**Comment by mnicely** [comment]
@FabianSchuetze has your issue been resolved?

**Comment by FabianSchuetze** [comment]
Thanks, @hwu36  and @mnicely for the reply.

The issue has been resolved. It seems that the code is tuned for a particular architecture and therefore keeping the equality is indeed desired? Shall I thus close the outstanding PR?

**Comment by FabianSchuetze** [comment]
Ok, thanks.
