### ISSUE TITLE
[QST]about gemm_universal_streamk

### ISSUE THREAD

**Issue by Shaquille-Wu** [NVIDIA/cutlass#1083]
I've read the paper about stream-k:<Stream-K_Work: centric Parallel Decomposition for Dense Matrix-Matrix Multiplication on the GPU>.
and I've read the code about stream-k in cutlass.
I found the paper and cutlass both apply this style: sk_blocks + dp_blocks, sk_blocks are executed at first, and dp_blocks at second. 
my confuse is why not dp_blocks + sk_blocks , I think this style maybe better.
I don't know my idea is right or incorrect.
So, is there anyone would like to tell me the reason?

**Comment by hwu36** [comment]
The experiments showed sk_blocks first is better.  One possible explanation is that it is more L2 friendly.  If I remember correctly, the paper explained it a little bit.

**Comment by Shaquille-Wu** [comment]
> The experiments showed sk_blocks first is better. One possible explanation is that it is more L2 friendly. If I remember correctly, the paper explained it a little bit.

thank you

**Comment by mnicely** [comment]
@Shaquille-Wu has your issue been resolved?

**Comment by Shaquille-Wu** [comment]
yes
