### ISSUE TITLE
[QST] How to construct SM90 `Params` inside the kernel?

### ISSUE THREAD

**Issue by chhwang** [NVIDIA/cutlass#1096]
**What is your question?**
I would like to call the device kernel (`GemmKernel`) directly from my own global kernel code. This looks complicated for SM90 as its `Params` is constructed by a host function `to_underlying_arguments()` that cannot be called inside the kernel. This is not an issue up to SM80 as its `Params` is equivalent with `Arguments` and it is easy to construct `Arguments` inside the kernel. Are there any easy ways to construct `Params` of SM90 inside the kernel?

**Comment by thakkarV** [comment]
TMA descriptors have to be constricted on host with a driver API and that's the true limitation here. If you're not running a TMA based kernel, you should still be able to construct the Params on device

**Comment by chhwang** [comment]
> TMA descriptors have to be constricted on host with a driver API and that's the true limitation here. If you're not running a TMA based kernel, you should still be able to construct the Params on device

@thakkarV Thanks for the comment! Is it a fundamental limitation or would it be resolved in a future version of CUDA/CUTLASS?

**Comment by thakkarV** [comment]
This is a limitation of CUDA itself for now.

**Comment by thakkarV** [comment]
Can you please tell me a bit more about what exactly you are trying to accomplish? Perhaps I can help suggest different ways that work around this limitation.

**Comment by chhwang** [comment]
@thakkarV Thank you for saying that. I am working on automatic kernel fusion that leverages CUTLASS GeMM as one component. No problem as I already have a work-around, but it would be great if we can minimize reliance of the kernel on CPU-side works.
