### ISSUE TITLE
cutlass performance evaluation

### ISSUE THREAD

**Issue by liaocs2008** [NVIDIA/cutlass#11]
Hi cutlass developers,

I tested the cutlass with cublas as provided in cuda 9.2 samples. The m, n, k are set as 640, 480 and 320 respectively.  

Following are cublas results on GTX 1080:
> /usr/local/cuda-9.2/samples/bin/x86_64/linux/release/matrixMulCUBLAS
> GPU Device 0: "GeForce GTX 1080" with compute capability 6.1
> 
> MatrixA(640,480), MatrixB(480,320), MatrixC(640,320)
> Computing result using CUBLAS...done.
> Performance= **3065.46 GFlop/s**, Time= **0.064 msec**, Size= 196608000 Ops
> Computing result using host CPU...done.
> Comparing CUBLAS Matrix Multiply with CPU results: PASS

Following are cutlass results on GTX 1080:

> ./build/tools/test/perf/cutlass_perf_test  --m=640 --n=480 --k=320 --kernels=dgemm
> 
>============================================================================
> Kernel: dgemm_nt
>     problem: 640-by-480-by-320, A: column-major, B: row-major, beta: 0
>     disposition: passed
>     runtime:     **0.872562 ms**
> 
>     performance: 225.323 GFLOPs
> 
> 
> 
> ============================================================================
> Kernel: dgemm_nn
>     problem: 640-by-480-by-320, A: column-major, B: column-major, beta: 0
>     disposition: passed
>     runtime:     0.873718 ms
> 
>     performance: 225.025 GFLOPs
> 
> 
> 
> ============================================================================
> Kernel: dgemm_tn
>     problem: 640-by-480-by-320, A: row-major, B: column-major, beta: 0
>     disposition: passed
>     runtime:     0.874086 ms
> 
>     performance: 224.93 GFLOPs
> 
> 
> 
> ============================================================================
> Kernel: dgemm_tt
>     problem: 640-by-480-by-320, A: row-major, B: row-major, beta: 0
>     disposition: passed
>     runtime:     0.874783 ms
> 
>     performance: 224.751 GFLOPs

It seems that in this case cutlass is slower than cublas. Do you mind providing your benchmark script for comparing cutlass with cublas? Moreover, what does the flags specified in kernel arguments mean, such as "s/d/h/i/nn/nt..."?

Thanks!

**Comment by kerrmudgeon** [comment]
> Moreover, what does the flags specified in kernel arguments mean, such as "s/d/h/i/nn/nt..."?

The prefix character indicates data type according to the cuBLAS conventions. "dgemm" refers to double-precision GEMM. "sgemm" refers to single-precision GEMM and is comparable to the kernel launched in the CUDA SDK example.

The suffix characters indicate layout relative to column-major format, the canonical cuBLAS layout. If you specify no layout in the kernel filter, it executes the four possible layout combinations.

My recommendation would be to run your benchmark again for --kernels=sgemm_tt to compare identical computations with the matMul CUDA SDK example where both matrix operands are row-major. Note also that the problem size you specify indicates the A matrix has 480 columns, and the B matrix has 480 rows. This implies the inner dimension K = 480. 

`./build/tools/test/perf/cutlass_perf_test --m=640 --n=320 --k=480 --kernels=sgemm_tt`

**Comment by liaocs2008** [comment]
@kerrmudgeon Thank you very much! I have found similar results to cublas. 


> ============================================================================
> Kernel: sgemm_tt
>     problem: 640-by-320-by-480, A: row-major, B: row-major, beta: 0
>     disposition: passed
>     runtime:     **0.069216** ms
> 
>     performance: 2840.5 GFLOPs
> 
> 
> 
> 
> 
> Kernel, M, N, K, Layout_A, Layout_B, Beta, Disposition, Runtime, GFLOPs
> sgemm_tt, 640, 320, 480, row, row, 0, passed, 0.069216, 2840.5

**Comment by jdemouth** [comment]
FWIW, GTX 1080 does not have a high FP64 throughput so do not expect DGEMM to skyrock on it ;)
