### ISSUE TITLE
Typo in multiply-accumulate operator

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#110]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/arch/simd.h#L88

Isn't this a typo of`d[i] = a[i] * b[i] + c[i];` ?

**Comment by hwu36** [comment]
Yes, you are right.  Thank you for catching this.  We will fix it.

**Comment by d-k-b** [comment]
This has been fixed in 2.3.

https://github.com/NVIDIA/cutlass/blob/c53f3339bb95ba52c5571134b1b3407e95a2546b/include/cutlass/arch/simd.h#L88
