### ISSUE TITLE
[QST] Is it possible to achieve "same padding" like scipy.signal.convolve did?

### ISSUE THREAD

**Issue by artmortal93** [NVIDIA/cutlass#1103]
I tried to preform batch 1D FIR filter by adapting conv2d_fprop_tensorop example, given a 2D continuous row major data layout for (M,N),which has M entry of N length 1D signal, A 1D filter of length S slide through every row and output the same N length signal response, which is exactly like scipy.signal.convolve with 'same' padding.
I guess the conv2d_tensorop should do the trick, and I already read the python example here and the discussion here:
https://github.com/NVIDIA/cutlass/blob/main/examples/python/03_basic_conv2d.ipynb
https://github.com/NVIDIA/cutlass/discussions/426

So for example, with a 2048 entry of 2048 length signal, with a 100 length filter:
N=1 H=2048 W=2048 C=1
K=1 R=1 S=100 P=2048 Q=2048
padding should be something like (0,0,49,50) 
stride= (1,1)
dilation=(1,1)
Is this correct?

I verify this setting in python conv2d jupyter notebook example that the case when 1D filter length is odd(with a 101 length filter,50 padding in both side), which has the same result with my reference code, as asymmetric padding is not required in this case, cutlass could handle it well, but I can't get it right with filter length is even case in the notebook, which require the padding to be asymmetric to achieve 'same padding' effect.

**Comment by hwu36** [comment]
yes, we assume padding are symmetric.  I think it is not hard to support asymmetric.  Search padding under https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv, and making the changes accordingly.  You can start from this file https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/conv2d_problem_size.h.

@manishucsd

**Comment by manishucsd** [comment]
CUTLASS convolutions already support asymmetric padding. `(pad_h, P)` and `(pad_w, Q)` can control padding in the input H and W dimensions, respectively. 

Please see the drawings below illustrating this in 1D. 

![Conv2dPaddingSupport](https://github.com/NVIDIA/cutlass/assets/3487276/de972846-da6d-42cf-bb19-b7afe0f48c87)

Can you try it for your cases in 2D?

**Comment by artmortal93** [comment]
> CUTLASS convolutions already support asymmetric padding. `(pad_h, P)` and `(pad_w, Q)` can control padding in the input H and W dimensions, respectively.
> 
> Please see the drawings below illustrating this in 1D.
> 
> ![Conv2dPaddingSupport](https://user-images.githubusercontent.com/3487276/269490244-de972846-da6d-42cf-bb19-b7afe0f48c87.png)
> 
> Can you try it for your cases in 2D?




I tried this command in the cutlass profiler to verify the 'same padding' setting as instruction, I am using the cutlass:12.1_latest docker image and my GPU is 3090 ampere arch:
./tools/profiler/cutlass_profiler --operation=Conv2d --Activation=f32:nhwc --Filter=f32:nhwc --Output=f32 --accumulator-type=f32 --n=1 --h=512 --w=512 --c=1 --k=1 --r=1 --s=40 --pad_h=0 --pad_w=20 --p=512 --q=512 --stride_h=1 --stride_w=1 --dilation_h=1 --dilation_w=1 

Strange that cutlass profiler only verify the wgrad operation without giving any fprop operation test as follows:

=============================
  Problem ID: 1

        Provider: CUTLASS
   OperationKind: conv2d
       Operation: cutlass_simt_swgrad_optimized_128x128_8x2_nhwc_align1

          Status: Success
    Verification: ON
     Disposition: Passed

reference_device: Passed
           cuDNN: Not run

       Arguments: --conv_kind=wgrad --n=1 --h=512 --w=512 --c=1 --k=1 --r=1 --s=40 --p=512 --q=512 --g=1 --pad_h=0 --pad_w=20  \
                  --stride_h=1 --stride_w=1 --dilation_h=1 --dilation_w=1 --Activation=f32:nhwc --Filter=f32:nhwc --Output=f32:nhwc  \
                  --conv_mode=cross --iterator_algorithm=optimized --alpha=1 --beta=0 --split_k_mode=serial --split_k_slices=1  \
                  --eq_gemm_provider=none --op_class=simt --accum=f32 --cta_m=128 --cta_n=128 --cta_k=8 --cluster_m=1  \
                  --cluster_n=1 --cluster_k=1 --stages=2 --warps_m=4 --warps_n=2 --warps_k=1 --inst_m=1 --inst_n=1 --inst_k=1  \
                  --min_cc=50 --max_cc=1024

           Bytes: 42991776  bytes
           FLOPs: 20971600  flops
           FLOPs/Byte: 0

         Runtime: 39.0116  ms
          Memory: 1.02634 GiB/s

            Math: 0.537573 GFLOP/s



=============================
  Problem ID: 1

        Provider: CUTLASS
   OperationKind: conv2d
       Operation: cutlass_simt_swgrad_optimized_256x128_8x5_nhwc_align1

          Status: Success
    Verification: ON
     Disposition: Passed

reference_device: Passed
           cuDNN: Not run

       Arguments: --conv_kind=wgrad --n=1 --h=512 --w=512 --c=1 --k=1 --r=1 --s=40 --p=512 --q=512 --g=1 --pad_h=0 --pad_w=20  \
                  --stride_h=1 --stride_w=1 --dilation_h=1 --dilation_w=1 --Activation=f32:nhwc --Filter=f32:nhwc --Output=f32:nhwc  \
                  --conv_mode=cross --iterator_algorithm=optimized --alpha=1 --beta=0 --split_k_mode=serial --split_k_slices=1  \
                  --eq_gemm_provider=none --op_class=simt --accum=f32 --cta_m=256 --cta_n=128 --cta_k=8 --cluster_m=1  \
                  --cluster_n=1 --cluster_k=1 --stages=5 --warps_m=4 --warps_n=2 --warps_k=1 --inst_m=1 --inst_n=1 --inst_k=1  \
                  --min_cc=50 --max_cc=1024

           Bytes: 42991776  bytes
           FLOPs: 20971600  flops
           FLOPs/Byte: 0

         Runtime: 72.5799  ms
          Memory: 0.551657 GiB/s

            Math: 0.288945 GFLOP/s


=============================

CSV Results:

Problem,Provider,OperationKind,Operation,Disposition,Status,conv_kind,n,h,w,c,k,r,s,p,q,g,pad_h,pad_w,stride_h,stride_w,dilation_h,dilation_w,Activation,Filter,Output,conv_mode,iterator_algorithm,alpha,beta,split_k_mode,split_k_slices,eq_gemm_provider,op_class,accum,cta_m,cta_n,cta_k,cluster_m,cluster_n,cluster_k,stages,warps_m,warps_n,warps_k,inst_m,inst_n,inst_k,min_cc,max_cc,Bytes,Flops,Flops/Byte,Runtime,GB/s,GFLOPs
1,CUTLASS,conv2d,cutlass_simt_swgrad_optimized_128x128_8x2_nhwc_align1,passed,success,wgrad,1,512,512,1,1,1,40,512,512,1,0,20,1,1,1,1,f32:nhwc,f32:nhwc,f32:nhwc,cross,optimized,1,0,serial,1,none,simt,f32,128,128,8,1,1,1,2,4,2,1,1,1,1,50,1024,42991776,20971600,0,39.0116,1.02634,0.537573
1,CUTLASS,conv2d,cutlass_simt_swgrad_optimized_256x128_8x5_nhwc_align1,passed,success,wgrad,1,512,512,1,1,1,40,512,512,1,0,20,1,1,1,1,f32:nhwc,f32:nhwc,f32:nhwc,cross,optimized,1,0,serial,1,none,simt,f32,256,128,8,1,1,1,5,4,2,1,1,1,1,50,1024,42991776,20971600,0,72.5799,0.551657,0.288945

**Comment by artmortal93** [comment]
when I force the profiler to output conv kind as --conv_kind=fprop, it dosent output anything

**Comment by manishucsd** [comment]
I found the commands I used in the profiler to demonstrate the pictures above here https://github.com/NVIDIA/cutlass/discussions/426. Let me know if this helps further to make fprop run for you?

**Comment by artmortal93** [comment]
> I found the commands I used in the profiler to demonstrate the pictures above here #426. Let me know if this helps further to make fprop run for you?

Thanks for the help, the commands from the picture seems to be not compatiable with newest cutlass version, no outout from the profiler is given. I will try to verify the case by writing some code.

**Comment by artmortal93** [comment]
> I found the commands I used in the profiler to demonstrate the pictures above here #426. Let me know if this helps further to make fprop run for you?

thanks, I modify the [16_ampere_tensorop_conv2dfprop](https://github.com/NVIDIA/cutlass/tree/main/examples/16_ampere_tensorop_conv2dfprop) example and it works.
