### ISSUE TITLE
[QST] How to use non-trival layout in CUTLASS3 GEMM

### ISSUE THREAD

**Issue by cctry** [NVIDIA/cutlass#1107]
Hello, 
I am trying to use CUTE to implement GEMM on a non-trivial layout. I define the stride like
`auto stride_A = cute::make_stride(make_stride(cute::_1{}, ncol * S), S, cute::C<0>{});`
But GemmUniversalAdapter does not take this and throws an error
`error: invalid operands to binary expression ('const cute::Underscore' and 'const cute::tuple<cute::C<1>, int>')`

How to correctly implement this?

**Comment by thakkarV** [comment]
How are you stamping out your kernel. Have you looked at example 51?

**Comment by cctry** [comment]
Thank for the reply.
I use `cutlass/test/unit/gemm/device/sm80_gemm_f16_f16_f32_tensor_op_f32.cu`as the reference, and it works fine with TagToStrideA_t. 
I looked at the GETT example, but I cannot understand the magic. Could you please help me figure out the correct implementation?

**Comment by cctry** [comment]
The mainloop and epilogue is defined as

```
using StrideA = Stride<int64_t, _1, int64_t>;
using StrideB = Stride<Stride<_1, int64_t>, _16, C<0>>;
using StrideC = Stride<int64_t, _1, int64_t>;

using CollectiveMainloop = cutlass::gemm::collective::CollectiveMma<
    DispatchPolicy, TileShape, half_t, StrideA, half_t, StrideB, TiledMma,
    GmemTiledCopyA, SmemLayoutAtomA, SmemCopyAtomA, cute::identity, // A
    GmemTiledCopyB, SmemLayoutAtomB, SmemCopyAtomB, cute::identity  // B
    >;

using CollectiveEpilogue = cutlass::epilogue::collective::DefaultEpilogue<
    StrideC, StrideC,
    cutlass::epilogue::thread::LinearCombination<half_t, 1, float, float>,
    cutlass::gemm::EpilogueDefault>;

using GemmKernel =
    cutlass::gemm::kernel:: GemmUniversal <Shape<int, int, int>, CollectiveMainloop,
                                  CollectiveEpilogue>;

```

The call site is like this
```
auto S = _16{};
auto dB = cute::make_stride(make_stride(cute::_1{}, K * S), S, cute::C<0>{});
Gemm gemm_op;
typename Gemm::Arguments arguments{
        cutlass::gemm::GemmUniversalMode::kGemm,
        make_shape(M, N, K),
        {A, make_stride(K, _1{}, _0{}), B, dB},
        {{1.0f, 0.0f}, C,
         make_stride(N, _1{}, _0{}),
         C,
         make_stride(N, _1{}, _0{})}};
```

**Comment by thakkarV** [comment]
GETTs are not supported via the SM80 mainloops yet. You'll have to customize the mainloop itself to implement GETT predication for LDGSTS based kernels. For TMA we get predication for free
