### ISSUE TITLE
[QST] How to improve the L2 cache hit rate?

### ISSUE THREAD

**Issue by ybai62868** [NVIDIA/cutlass#1115]
**What is your question?**
Recently, I am analyzing the kernel implemented by CUTLASS template using ncu.
I find that CUTLASS has more L2 Cache hit rate compared with other kernels generated by the DL compiler.
I am curious about this condition. How to improve the L2 cache hit rate and what does the CUTLASS do to improve it?

Thanks,

**Comment by hwu36** [comment]
we have several L2 swizzling algorithms to improve L2.  each one also has several parameters to tune.

**Comment by ybai62868** [comment]
Hi Haicheng,

Thanks for your information. Where can I find these special parameters for L2 swizzling algorithms? Thanks a lot

Thanks,
Yang

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/threadblock/threadblock_swizzle.h

these algorithms have templates to tune.

**Comment by ybai62868** [comment]
Hi Haicheng,

Thanks for your reference. I have understood the reason why CUTLASS kernel can have a higher L2 cache hit rate.
BTW, another interesting question is "I find that CUTLASS can have more instructions and less number of register than the kernel generated by the DL compiler".
I am curious about the optimization techniques CUTLASS applied to improve the utilization of the register. 


Thanks,

<img width="1162" alt="Screenshot 2023-10-07 at 16 37 57" src="https://github.com/NVIDIA/cutlass/assets/17467736/70f873ef-f166-490d-a906-b52a7fc1ad75">

**Comment by ybai62868** [comment]
The more instructions means the **3.95M** between kernel and shared.

**Comment by ybai62868** [comment]
Another question when I profiling the kernel generated by CUTLASS with SASS code, I find that CUTLASS kernel has a higher utilization of register files and one lDSM instruction followed with six HMMA instructions. Is the reason why CUTLASS is so powerful compared with other compiler or framework without the optimization for the register-level.

**Comment by ybai62868** [comment]
Another question when I profiling the kernel generated by CUTLASS with SASS code, I find that CUTLASS kernel has a higher utilization of register files and one LDSM instruction followed with six HMMA instructions. Is the reason why CUTLASS is so powerful compared with other compiler or framework without the optimization for the register-level.

**Comment by ybai62868** [comment]
Another question when I profiling the kernel generated by CUTLASS with SASS code, I find that CUTLASS kernel has a higher utilization of register files and one LDSM instruction followed with six HMMA instructions but others with one LDSM instruction with lots of MOV instructions. Is the reason why CUTLASS is so powerful compared with other compiler or framework without the optimization for the register-level?

**Comment by hwu36** [comment]
i don't know what dl compiler do you refer to.

cutlass is the example from nvidia to show how to use nvidia tensor cores.  we collaborate with nvcc team closely to deliver the best possible performance from c++.  any other dl compiler needs to follow cutlass's approach to match cutlass performance.  there is no rocket science used in cutlass, just common software engineering practice.

**Comment by ybai62868** [comment]
Thanks a lot! I use the kernels generated by Triton to do the comparsion. After profiling lots of cases with ncu, I have found that some optimization provided by CUTLASS and the difference between them. 

Thanks a lot！
