### ISSUE TITLE
Cannot find fragment.h

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#112]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/reduction/batched_reduction.h#L37

Even git history search, I cannot find fragment.h file. So is it a coding mistake?

**Comment by hwu36** [comment]
batched_reduction.h and batched_reduction_traits.h are old stale files that need to be deleted.  Thank you for catching this, again.  We will fix them.

**Comment by kerrmudgeon** [comment]
The CUTLASS 2.x approach is to use `cutlass::Array<T, N>` as the basic
container for all fragment objects. This is defined in
`include/cutlass/array.h`. FYI.

**Comment by d-k-b** [comment]
The stale files have been removed in 2.3.
