### ISSUE TITLE
[QST] Details of heuristic function inside the stream-K algorithm.

### ISSUE THREAD

**Issue by Ther-nullptr** [NVIDIA/cutlass#1125]
I have read the paper of stream-K and the source code of `threadblock_swizzle_streamk` method. I am confused by some of the code:

```cpp
    for (int trial_sk_blocks = min_sk_blocks; trial_sk_blocks <= max_sk_blocks; ++trial_sk_blocks)
    {
      int sk_waves = (trial_sk_blocks + avail_sms - 1) / avail_sms;
      int max_sk_iters_per_block = (sk_iters + trial_sk_blocks - 1) / trial_sk_blocks;
      int sk_iter_equiv = max_sk_iters_per_block * sk_waves;

      int num_peers = ((trial_sk_blocks + sk_tiles - 1) / sk_tiles) + 1;        // add one for alignment skew // !question1

      float iter_cost = 0.02f * float(num_peers) * float(sk_iter_equiv);

      if (trial_sk_blocks % sk_tiles == 0)
      {
        // aligned
        num_peers = (trial_sk_blocks / sk_tiles);

        iter_cost = 0.0f; // !question2
      }
     // ...
```

1. What is alignment skew? The `+1` is not appeared in the original equation of the paper.
2. When `trial_sk_blocks % sk_tiles == 0`, I can understand how the `num_peers` is calculated, but the iter_cost is set to 0, which in my understanding, not same as the original paper. 

The original equation is below:
<img width="257" alt="image" src="https://github.com/NVIDIA/cutlass/assets/71265304/cd2b96bc-9985-4af7-b951-481776ac0135">

**Comment by hwu36** [comment]
@dumerrill 

The code was fine tuned after the paper was written.
