### ISSUE TITLE
[QST] Any theory about the "layout algebra"?

### ISSUE THREAD

**Issue by eatingtomatoes** [NVIDIA/cutlass#1129]
**What is your question?**

Hi there, thank you for the work on CUTLASS3.0/CuTe. The "layout algebra" in 3.0 is much more elegant and easier to use than iterators.

I guess there should be a (formal) theory supporting the "layout algebra".  Otherwise, how do you known a complex combination of basic operators will yield what you want?

Also, I noticed that there were many issues asking about the calculation of layouts. You kindly answered them case by case. But I think such questions will be endless. as users do not know the underlying computing principles.

In fact, I have been reading the source code of CuTe recently, hoping to reverse engineer the underlying theory. But I found it difficult.

So, if there is a (formal) theory, can you provide some information about it? 

Thank you!

**Comment by ccecka** [comment]
Yes, publications are pending. We'll have a lot more information to release soon.

**Comment by eatingtomatoes** [comment]
Great! I'm looking forward to that!

**Comment by YangWang92** [comment]
> Yes, publications are pending. We'll have a lot more information to release soon.

Thanks for sharing, is the “layout algebra” related to “tensor algebra"?

**Comment by ccecka** [comment]
Only in that it's application is for tensor algebra.

**Comment by YangWang92** [comment]
By the way, I'm curious about the acronym CuTe. Does it stand for CUDA Tensor Expression? Thanks!

**Comment by eatingtomatoes** [comment]
Hi @ccecka! A month has passed, but the release does not come. Do you have a concrete schedule?

I am struggling with these code every day. Save me out, Please！
