### ISSUE TITLE
Cannot find definition of cutlass::gemm::LinearScaling

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#113]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/reduction/batched_reduction_traits.h#L74

Cannot find LinearScaling anywhere, seems it should be defined in ixgemm/linear_scaling.h, but the file is missed too.

**Comment by hwu36** [comment]
We don't have `batched_reduction_traits.h` any more.  I think this issue is not relevant now.
