### ISSUE TITLE
[FEA] Depthwise Conv3d

### ISSUE THREAD

**Issue by ShuaiShao93** [NVIDIA/cutlass#1133]
**Is your feature request related to a problem? Please describe.**
Since depthwise conv2d has been supported, shall we consider supporting depthwise conv3d as well? I assume some of the logic can be reused, so the engineering costs will not be very high? This will be super useful in the 3d detection model based on lidar.

**Comment by IonThruster** [comment]
Thanks for your suggestion @ShuaiShao93. We welcome external contributions on it at this time, and if you need help implementing it - do reach out either here or on the CUTLASS discord channel.

Tagging @mnicely.

**Comment by hwu36** [comment]
@Ethan-Yan27 , would you please tell @ShuaiShao93 how to extend depthwise conv2d to 3d?

**Comment by mnicely** [comment]
@ShuaiShao93 can you provide an details about your use case?

**Comment by ShuaiShao93** [comment]
Thanks folks! 

> can you provide an details about your use case?

I basically want to find an efficient depthwise conv3d. It turns out although other libraries like cuDNN/TensorRT support grouped conv3d, it's even slower than normal conv3d. I also profiled their kernels, and found even for a problem that's supposed to be memory bound, the memory throughput is very low. So I hope CUTLASS does some special optimization for depthwise conv.

**Comment by Ethan-Yan27** [comment]
> would you please tell @ShuaiShao93 how to extend depthwise conv2d to 3d?

The basic fundamental idea behind depthwise conv2d implementation: Using direct convolution implementation and persistent the filter in the smem and register to reduce the memory loading. 

Here is the diagram to show the basic idea. Take cta 0 as example, each mainloop iteration processes one output tile and different output tile are sharing the same input filter.

![image](https://github.com/NVIDIA/cutlass/assets/7465441/427aee7a-ed1d-41ca-8132-e9c392ba9dc0)

To implement depthwise conv3d, we should take the **depth** dim into account for different CTA iterators. Here are 3 most important files.
- Input Activation iterator: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/threadblock/depthwise_fprop_activation_tile_access_iterator_direct_conv_optimized.h
- Input filter iteratior: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/threadblock/depthwise_fprop_filter_tile_access_iterator_direct_conv_optimized.h
- Ouput tile iterator: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/predicated_tile_iterator_direct_conv.h

This [commit](https://github.com/NVIDIA/cutlass/commit/c975e2ccbb2dbf13024568b37ffa3498ed0b3aed#diff-c33c1831eb1ee365e755651324cb25f70e0e8e891495db646cc3f417aeab1167) published the depthwise conv2d, please search this the keyword `direct_conv` / `depthwise` ... to find other related codes.

**Comment by ShuaiShao93** [comment]
Thanks! I'll see what I can do here.

**Comment by yupatrick22** [comment]
@Ethan-Yan27 very nice pics, but there seems small typo issue for cta1, the activation channel range should be always 31-63, and the final ouput of iteration 0 and 1, the output Q should be 0-7

**Comment by Ethan-Yan27** [comment]
Thanks, nice catch. Updated.
