### ISSUE TITLE
[QST] Is there a reason why DefaultMmaCore isn't specialised based on the arch tag?

### ISSUE THREAD

**Issue by joerowell** [NVIDIA/cutlass#1137]
**What is your question?**
I've been looking at the DefaultMMA recently, and I've noticed that none of the inner ```MMACore``` objects are instantiated based on the tag. That is, they all look somewhat like this:

https://github.com/NVIDIA/cutlass/blob/112590114d72fcd6188a01d67a51627277dde505/include/cutlass/gemm/threadblock/default_mma.h#L442-L445

But some of the provided specialisations are quite broad. For example, the default template parameters in ```default_mma_core.h``` would mean that almost any caller could instantiate the specialisation in ```default_mma_core_sm80.h```:

https://github.com/NVIDIA/cutlass/blob/112590114d72fcd6188a01d67a51627277dde505/include/cutlass/gemm/threadblock/default_mma_core_sm80.h#L1225-L1252

Is this intentional? The reason why I ask is the default in DefaultMMACore enables only L2 caching (i.e caching reads from global memory), which I think it might be unintentional in general.

**Comment by hwu36** [comment]
what do you mean `DefaultMMACore enables only L2 caching `?

**Comment by joerowell** [comment]
Hi,

Sorry, what I mean is that the default arguments for the non-specialized ```DefaultMMACore``` struct sets the caching parameters to ```cutlass::arch::CacheOperation::Global```:

https://github.com/NVIDIA/cutlass/blob/112590114d72fcd6188a01d67a51627277dde505/include/cutlass/gemm/threadblock/default_mma_core.h#L98-L103

To my understanding (I'd happily be corrected btw!) this means that there's [no L1 caching](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cache-operators). That is, I'm assuming that ```cutlass::arch::CacheOperation::Global``` mandates ```.cg```, which does no L1 caching.

**Comment by hwu36** [comment]
We don't want L1 caching for gemm since gemm does not need to revisit data.  Note, only 128bit load can have this option.

**Comment by joerowell** [comment]
Ah of course! Thanks very much for that.

Still, the higher level question about tags remains for other settings.

**Comment by hwu36** [comment]
>  the higher level question about tags remains for other settings.

i don't get this part.  Why it is a problem?  We want our code as general as possible.

**Comment by mnicely** [comment]
@joerowell has your issue been resolved?

**Comment by joerowell** [comment]
Sorry for the delayed response. Yes, I'm happy to close this.
