### ISSUE TITLE
[QST] Skinny fp8 gemm on H100

### ISSUE THREAD

**Issue by divchenko** [NVIDIA/cutlass#1139]
I'm trying to get the best perf of a 'skinny' gemm on fp8 matrices on H100. My gemm MxNxK is 16x14336x4096 or 32x14336x4096 or 64x14336x4096 . This should obviously be heavily memory-bound.
I'm running cutlass profiler (I vary --m=16/32/64):
```
cmake .. -DCUTLASS_NVCC_ARCHS=90a -DCUTLASS_LIBRARY_KERNELS=cutlass3x_sm90_tensorop_s64x128x32gemm_e4m3_ -DCUTLASS_LIBRARY_IGNORE_KERNELS=bf16,f16
./tools/profiler/cutlass_profiler --output=/tmp/cutlass.out --operation=Gemm --m=16 --n=14336 --k=4096
```
but the the best memory b/w I get is ~2.2TB/sec, which nsight compute rates at ~68% of memory b/w.

I've also tried to write kernel by hand following fp8 example and play w/ different tiles to match https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#asynchronous-warpgroup-level-matrix-shape , but I'm always peaking at ~70% of memory b/w.
Is this the best number I can get? Can I get closer to 80% or more?

**Comment by divchenko** [comment]
These seem to be the best:
cutlass3x_sm90_tensorop_s64x128x32gemm_e4m3_e4m3_f32_f32_e5m2_64x128x128_1x2x1_0_tnn_align16_warpspecialized_pingpong_fp8_fastaccum_epi_nosmem
cutlass3x_sm90_tensorop_s64x128x32gemm_e4m3_e4m3_f32_f32_e5m2_64x128x128_1x2x1_0_tnn_align16_warpspecialized_pingpong_fp8_fastaccum_epi_tma
Here's the full list: https://gist.github.com/divchenko/a32d50e5771190291a55efec9aaa814d

Regarding flops, I see a quite low number even on m=64: 286 TFLOP/sec, which has ~7x room to grow. nsight compute profiler corroborates w/ this finding.
It's fine to waste compute as long as I can get better memory b/w.

**Comment by thakkarV** [comment]
Can you try a larger cluster size of 1x4x1 for the two kernel recipes that are performing better?

**Comment by divchenko** [comment]
Tiny bit better
2241.57 GiB/s
2238.46 GiB/s

**Comment by thakkarV** [comment]
hmm... seems like margin of error delta to me

**Comment by divchenko** [comment]
Larger cluster size. I will try cublas later today.

**Comment by divchenko** [comment]
First and second kernels respectively, but yeah, seems like a margin of error

**Comment by divchenko** [comment]
Tried cublas, it's a bit worse, ~65% of memory b/w. Here's the kernel it chooses : sm90_xmma_gemm_e4m3e4m3_e4m3f32_f32_tn_n_tilesize128x64x128_warpgroupsize2x1x1_algo2_execute_segment_k_off_kernel__5x_cublas
It's basically based on their example https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuBLASLt/LtFp8Matmul/sample_cublasLt_LtFp8Matmul.cu

**Comment by hwu36** [comment]
@ANIKET-SHIVAM @IonThruster

**Comment by IonThruster** [comment]
Firstly, I believe 64x14336x4096 is expected to be memory bound, since the flops/byte is too low. Also based on the comment above I just tried to run this specific test on latest CUTLASS 3.2.1 + [CTK 12.2.2](https://developer.nvidia.com/cuda-downloads) : 
```bash
./cutlass_profiler --kernels=cutlass3x_sm90_tensorop_s64x128x32gemm_e4m3_e5m2_f32_f32_e4m3_64x128x128_1x2x1_0_tnn_align16_warpspecialized_pingpong_fp8_fastaccum_epi_tma --m=64 --n=14336 --k=4096 --profiling-iterations=10000
``` 

And I see :
```bash
         Bytes: 62652416  bytes
           FLOPs: 7518027776  flops
           FLOPs/Byte: 119

         Runtime: 0.0231348  ms
          Memory: 2539.16 GiB/s

          Math: 324966 GFLOP/s
``` 

Which is a bit better than than what you see. Some things to try : 
* Upgrade to latest i.e [CTK 12.2.2](https://developer.nvidia.com/cuda-toolkit-archive)
* Try altering [this](https://github.com/NVIDIA/cutlass/blob/v3.2.1/include/cute/atom/copy_traits_sm90_tma.hpp#L679) line to : 
```c++
CUtensorMapL2promotion  tma_l2Promotion = CU_TENSOR_MAP_L2_PROMOTION_L2_256B;
```

**Comment by mnicely** [comment]
@divchenko is your issue resolved?

**Comment by divchenko** [comment]
@mnicely  yes, thank you!

**Comment by divchenko** [comment]
resolve
