### ISSUE TITLE
Coord::at<>() version instead of Coord::at(int)

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#114]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/layout/pitch_linear.h#L89
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/layout/pitch_linear.h#L93
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/layout/pitch_linear.h#L97
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/layout/pitch_linear.h#L101

All above 4 function calls of Coord::at could be determined at compiling time, so its template version might slightly improve the performance. Ex. `this->at<kContiguous>()`

**Comment by hwu36** [comment]
Sorry, I don't get it.  `kContiguous` and `kStrided` are all compile time constants for `PitchLinearCoord`.  So, they are essentially the same.  See this https://godbolt.org/z/eqzcqv

IMO, `at()` is a little easier to read than `at<Dim>()`

**Comment by Peter9606** [comment]
Thanks for making it clear for me. Really appreciate it.
