### ISSUE TITLE
[QST] Knowing compute types

### ISSUE THREAD

**Issue by gaodaheng** [NVIDIA/cutlass#1144]
I want to known, if type_a=bf16 type_b=bf16 and type_c=fp32, what is the cal type? tf32 or fp16?

**Comment by thakkarV** [comment]
What do you mean by cal type?

**Comment by mnicely** [comment]
@gaodaheng I'm assuming you mean compute type?

**Comment by gaodaheng** [comment]
> I'm assuming you mean compute type?

> @gaodaheng I'm assuming you mean compute type?

yes, if input is bf16, what is the compute type?

**Comment by thakkarV** [comment]
Fp32
