### ISSUE TITLE
[QST] Possibly misleading parameter name for cute's `*_prodcut`

### ISSUE THREAD

**Issue by cloudhan** [NVIDIA/cutlass#1148]
**What is your question?**

Take `local_tile` as an example,
```cpp
  auto layout = make_layout(make_shape(15, 15));
  std::vector<int> buffer(size(layout));
  auto tensor = make_tensor(buffer.data(), layout);
  for (int i = 0; i < size(tensor); i++) {
    tensor(i) = i;
  }
  print_tensor(tensor);
  std::cout << "\n";
/*
Outputs:
raw_ptr_32b(0x561660f21eb0) o (15,15):(_1,15):
    0   15   30   45   60   75   90  105  120  135  150  165  180  195  210
    1   16   31   46   61   76   91  106  121  136  151  166  181  196  211
    2   17   32   47   62   77   92  107  122  137  152  167  182  197  212
    3   18   33   48   63   78   93  108  123  138  153  168  183  198  213
    4   19   34   49   64   79   94  109  124  139  154  169  184  199  214
    5   20   35   50   65   80   95  110  125  140  155  170  185  200  215
    6   21   36   51   66   81   96  111  126  141  156  171  186  201  216
    7   22   37   52   67   82   97  112  127  142  157  172  187  202  217
    8   23   38   53   68   83   98  113  128  143  158  173  188  203  218
    9   24   39   54   69   84   99  114  129  144  159  174  189  204  219
   10   25   40   55   70   85  100  115  130  145  160  175  190  205  220
   11   26   41   56   71   86  101  116  131  146  161  176  191  206  221
   12   27   42   57   72   87  102  117  132  147  162  177  192  207  222
   13   28   43   58   73   88  103  118  133  148  163  178  193  208  223
   14   29   44   59   74   89  104  119  134  149  164  179  194  209  224
*/


  print_tensor(local_tile(tensor, make_tile(5, 5), make_coord(0, 0)));
  std::cout << "\n";

/*
Outputs:
raw_ptr_32b(0x561660f21eb0) o (5,5):(_1,15):
    0   15   30   45   60
    1   16   31   46   61
    2   17   32   47   62
    3   18   33   48   63
    4   19   34   49   64
*/
```

The tile here, somehow means something we are going to work on that is spatially "contiguous", a,k,a, a tile is repeated, and we select the (0,0)-th one of them.

Lets take [`blocked_product`](https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/02_layout_operations.md#blocked-product-the-intuitive-tiling) and [`logical_product`](https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/02_layout_operations.md#logical-product) as examples, in the linked docs, they both got `(Layout tile, Layout layout)` as arguments.

```cpp
  auto inner_tile = make_tile(_2{}, _2{});
  auto inner_layout = make_layout(make_shape(_2{}, _2{}));
  auto outer = make_layout(make_shape(_3{}, _3{}));
  std::cout << "logical_product:\n";
  print(logical_product(inner_layout, outer));
  std::cout << "\n";
  print(logical_product(outer, inner_layout));
  std::cout << "\n";
  print(logical_product(outer, inner_tile));
/*
Outputs:
logical_product:
((_2,_2),(_3,_3)):((_1,_2),(_4,_12))
((_3,_3),(_2,_2)):((_1,_3),(_9,_18))
((_3,_2),(_3,_2)):((_1,_3),(_3,_1))
*/

  std::cout << "\n\ntiled_product:\n";
  print(tiled_product(inner_layout, outer));
  std::cout << "\n";
  print(tiled_product(outer, inner_tile));
/*
tiled_product:
((_2,_2),_3,_3):((_1,_2),_4,_12)
((_3,_3),_2,_2):((_1,_3),_3,_1)
*/

  std::cout << "\n\nblocked_product:\n";
  print_layout(blocked_product(inner_layout, outer));
  std::cout << "\n";
/*
blocked_product:
((_2,_3),(_2,_3)):((_1,_4),(_2,_12))
       0    1    2    3    4    5 
    +----+----+----+----+----+----+
 0  |  0 |  2 | 12 | 14 | 24 | 26 |
    +----+----+----+----+----+----+
 1  |  1 |  3 | 13 | 15 | 25 | 27 |
    +----+----+----+----+----+----+
 2  |  4 |  6 | 16 | 18 | 28 | 30 |
    +----+----+----+----+----+----+
 3  |  5 |  7 | 17 | 19 | 29 | 31 |
    +----+----+----+----+----+----+
 4  |  8 | 10 | 20 | 22 | 32 | 34 |
    +----+----+----+----+----+----+
 5  |  9 | 11 | 21 | 23 | 33 | 35 |
    +----+----+----+----+----+----+
*/
```
And we can observe the `inner` (the tile) is repeated as `outer`, which is what the docs is saying, but the code state the param list as `(Layout layout, Layout tile)`, which I think the names are mistakenly swapped.

The following is the `*_product` APIs, 

```cpp
logical_product(Layout<LShape,LStride> const& layout,
                Layout<TShape,TStride> const& tile)
logical_product(Layout<LShape,LStride> const& layout,
                IntTuple               const& tile)

tiled_product(Layout<LShape,LStride> const& layout,
              Tile                   const& tile)

blocked_product(Layout<TShape,TStride> const& block,
                Layout<UShape,UStride> const& layout)
```

**Comment by cloudhan** [comment]
Also the `print(logical_product(outer, inner_tile));` that is, take `(Layout layout, Tile tile)` as args, produces really weird result `((_3,_2),(_3,_2)):((_1,_3),(_3,_1))`, like a mixing of raked product with different strides... :(

**Comment by ccecka** [comment]
Here's a comment/documentation I just wrote for `logical_divide(Tensor, Tiler)`:
```
// Apply a Tiler to the Tensor.
//
// Consider a Tensor with shape (A,B,x,y)
// And a Tiler that is:
//
// * A Layout with shape (BLK_A,BLK_B)
// ** Result Tensor shape ((BLK_A,BLK_B),Rest).
// ** That is, the Tensor and Tiler are treated as 1D for the tiling.
// ** See logical_divide(Layout,Layout)
//
// * A Tile<Layout...> with shape <BLK_A,BLK_B>
// ** Result Tensor shape ((BLK_A,a),(BLK_B,b),x,y).
// ** Each mode of the Tile<Layout...> is applied to the corresponding mode of the Tensor.
// ** See logical_divide(Layout,Tuple)
//
// * A Shape (BLK_A,BLK_B)
// ** Result Tensor shape ((BLK_A,a),(BLK_B,b),x,y).
// ** Equivalent to applying Tile<BLK_A:_1,BLK_B:_1>.
// ** See logical_divide(Layout,Tuple) and logical_divide(Layout,Int)
//
// Note that the Tile<Layout...>/Shape Tilers must be weakly_congruent to the Tensor
```

The same applies to `logical_product(Layout, Tiler)`.
- `logical_product(Layout, Layout)` treats the Layouts as 1D entities.
- `logical_product(Layout, Tile<Layouts...>)` applies `logical_product` to corresponding modes of `Layout` and `Tile<Layout...>`.
- `logical_product(Layout, Shape)` is a shortcut for applying `Tile<Layouts...>` where the `Layout...`s all have stride-1.

Then, the `blocked_product` and `raked_product` variants rearrange the modes for more common, intuitive cases.

Thus, your last "weird" case is applying `logical_product` by-mode:
```
(3,3):(1,3) x <2,2>
(3:1 x <2>, 3:3 x <2>)
(3:1 x 2:1, 3:3 x 2:1)
((3,2):(1,3), (3,2):(3,1))
((3,2),(3,2)):((1,3),(3,1))
```

**Comment by ccecka** [comment]
Though `logical_product(Layout, Tile<Layouts...>)` certainly does have applications in broadcasting modes (stride-0 layouts) and in more advanced blocking and raking of Layouts, I do agree that `logical_product(Layout, Shape)` doesn't really have any real applications and could potentially be a pitfall.

I'll consider issuing an error in that case.

Otherwise, you seem to be concerned about the parameter names, which I'll also revisit in my next documentation pass.

**Comment by cloudhan** [comment]
Still very confusing, could you explain a bit about the notations cute team are using, A,B,x,y,BLK_A,BLK_B,a,b. I think there must be some conventions are established, but I am not sure what they stand for.

In terms of `logical_divide(Tensor, Tiler)`, what is a Tiler actually?
Is tiler a tiling pattern and the division reveals the tile? Or is it a tile and the division reveals the pattern? If it is the latter case, I would call it Tilee instead.

**Comment by ccecka** [comment]
Overloading the words Tile and Tilee and Pattern is not very productive.

A Tiler can be many things:
1) A `Layout`.   (X,(Y,Z)):(dx,(dy,dz))
2) A `Tile<Layout...>`. A tuple of Layouts.  <L0, <L1, L2>>
3) A `Shape`. But this is just shorthand for a tuple of Layouts with stride-1.

(1) `logical_product(Layout, Layout)` and `logical_divide(Layout, Layout)` are the core operations. Once you understand what these do (and think of them in 1D), you understand all of it.
(2) Recursively apply (1) by-mode. For each corresponding mode of the Layout and the Tiler, apply (1). This is often the simplest way from 1D to ND.
(3) Essentially the same as (2), but call `make_layout` on the shape extent first to generate a default Layout.
