### ISSUE TITLE
comment error

### ISSUE THREAD

**Issue by reveriel** [NVIDIA/cutlass#115]
https://github.com/NVIDIA/cutlass/blob/86931fef8538008a1a92036732b3eb7fe47b25d0/include/cutlass/gemm/gemm.h#L99

comment should be "rank=3"

**Comment by reveriel** [comment]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/gemm/gemm.h#L277

should be "batch dimension"

**Comment by hwu36** [comment]
Thank you for catching these.  We will fix them.

**Comment by kerrmudgeon** [comment]
Closing as fixed in CUTLASS 2.3.
