### ISSUE TITLE
[QST] Volta shared memory layout example

### ISSUE THREAD

**Issue by ssiu** [NVIDIA/cutlass#1158]
Hi, I am currently studying these slides: https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9593-cutensor-high-performance-tensor-operations-in-cuda-v2.pdf

I was wondering if there's any sample code for loading data from global memory to shared memory as shown in page 23?

Can I also ask why there does not exist ```copy_sm70.hpp``` in  ```cutlass/include/cute/arch``` and ```copy_traits_sm70.hpp``` in ```cutlass/include/cute/atom```? 

Thanks!

**Comment by thakkarV** [comment]
No special copy atoms are needed for Volta as all copies were thread copies with CUDA C++ exposure. The Default/Universal copy is sufficient pre Ampere
