### ISSUE TITLE
redundant definition of matrix layout

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#116]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/layout/matrix.h#L448

Matrix layout concept defined above is redundant and conflict with cutlass::MatrixLayout defined here:

https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/matrix_traits.h#L36

**Comment by hwu36** [comment]
matrix_traits.h would be depreciated.  Please use cutlass::layout::Matrix

**Comment by d-k-b** [comment]
The deprecated matrix_traits.h has been removed in 2.3.
