### ISSUE TITLE
[QST] question about cutlass int8 *int8 = int32 kernel

### ISSUE THREAD

**Issue by zwshan** [NVIDIA/cutlass#1163]
**What is your question?**
Hello, I am very interested in INT8 matrix multiplication in Cutlass, but I have encountered some confusion while trying to use it. Let's assume we have a matrix A multiplied by matrix B (the original matrix data format is both fp32).

My first question is: If I quantize both matrix A and matrix B to INT8 (with scale factors, scale A and scale B), and I use the int8 * int8 = int8 API in Cutlass, then when I want to de-quantize the INT8 result matrix back to fp32,  I simply need to multiply the INT8 result by scale A and scale B.  However, if I use int8 * int8 = int32, how should I de-quantize it?

My second question is: Suppose I have a series of consecutive matrix multiplications, where the output of the previous matrix multiplication is the input for the next one. Do I need to quantize and de-quantize before and after each matrix multiplication, or should I only quantize before the first matrix multiplication and de-quantize after the last matrix multiplication? I would greatly appreciate your assistance in answering these questions.

**Comment by zwshan** [comment]
@alexsamardzic hello, could you please help me answer the question?

**Comment by zwshan** [comment]
hello, @manishucsd could you please help me?

**Comment by manishucsd** [comment]
Q1) Are you looking for `int32_t` to float de-quantization? If that is what you are looking for find all the conversions [numeric_conversion.h](https://github.com/manishucsd/cutlass/blob/main/include/cutlass/numeric_conversion.h)

Q2) I think you are asking for GEMM-GEMM fusion with de-quantization and scaling involved? 

Ideally, if the output of previous GEMM is quantized, you should keep it quantized until it reachs registers (closer to the math units) for the performance reasons from pure GEMM perspective, but you might need some scaling (additional operations) for handling accuracy. The scaling can also be fused in the mainloop of the second GEMM. 

Can list out your sequence operations with data types and problem shapes? Hopefully, we can provide insights once we have more details of what you trying to implement.

**Comment by zwshan** [comment]
```c++
__global__ void quantize_int8(signed char *input_int,
			      float *input,       
			      int index_maximum,
			      int N) {
  int block_id = blockIdx.x;
  int thread_id = threadIdx.x;  
  int id = block_id*blockDim.x + thread_id;
  
  if (id < N) {
    float max_value = abs(input[index_maximum-1]);
    signed char value = (signed char)(((float)127 / max_value) * input[id]);
    input_int[id] = value;
  }
}

__global__ void dequantize_int8(float *output,
				int *output_int,
				float *input, int index_maximum,
				float *bias,
				float weight_scale,
				int N) {
  int block_id = blockIdx.x;
  int thread_id = threadIdx.x;  
  int id = block_id*blockDim.x + thread_id;
  
  if (id < N) {
    float input_scale = (float)127 / abs(input[index_maximum-1]);
    float scale = input_scale * weight_scale;
    output[id] = bias[id] + output_int[id]/(float)scale;
  }
}

cudaError_t CutlassInt8TN(
			  int M,
			  int N,
			  int K,
			  int alpha,
			  signed char const *A,
			  int lda,
			  signed char const *B,
			  int ldb,
			  int beta,
			  int *C,
			  int ldc) {
  typedef cutlass::gemm::WmmaGemmTraits<
    cutlass::MatrixLayout::kRowMajor,      // layout of A matrix
    cutlass::MatrixLayout::kColumnMajor,   // layout of B matrix
    cutlass::Shape<128, 128, 128>,         // threadblock tile size
    signed char,                           // A type
    signed char,                           // B type
    int,                                   // D type
    cutlass::gemm::LinearScaling<int>,     // functor to do the math in the epilogue
    int,                                   // accumulator type
    cutlass::Shape<128, 32, 32>,           // warp tile size
    cutlass::Shape<16, 16, 16>,            // WMMA instruction tile size
    16,                                    // scalars every time a thread loads from A
    16                                     // scalars every time a thread loads from B
    >
    WmmaGemmTraits;
```

Thank you very much! The code I shared uses an older version of Cutlass to perform matrix quantization from fp32 to int8 and then conducts matrix multiplication, ultimately de-quantizing back to fp32.  Now, I want to refactor this code using the latest version of Cutlass, and this code will be used within a for loop. To optimize the performance of this code during the refactoring, what steps should I take to ensure that it runs efficiently?

**Comment by zwshan** [comment]
> Q2) I think you are asking for GEMM-GEMM fusion with de-quantization and scaling involved?
> 
> Ideally, if the output of previous GEMM is quantized, you should keep it quantized until it reachs registers (closer to the math units) for the performance reasons from pure GEMM perspective, but you might need some scaling (additional operations) for handling accuracy. The scaling can also be fused in the mainloop of the second GEMM.
> 
I'm sorry, I'm not particularly clear about the meaning of "GEMM-GEMM fusion with de-quantization and scaling involved." If you could clarify this, I would greatly appreciate it. Additionally, if you could guide me on how to implement fp32 to int8 in the latest version of Cutlass for the code I've listed, I would be very thankful.

**Comment by zwshan** [comment]
> ```c++
> __global__ void quantize_int8(signed char *input_int,
> 			      float *input,       
> 			      int index_maximum,
> 			      int N) {
>   int block_id = blockIdx.x;
>   int thread_id = threadIdx.x;  
>   int id = block_id*blockDim.x + thread_id;
>   
>   if (id < N) {
>     float max_value = abs(input[index_maximum-1]);
>     signed char value = (signed char)(((float)127 / max_value) * input[id]);
>     input_int[id] = value;
>   }
> }
> 
> __global__ void dequantize_int8(float *output,
> 				int *output_int,
> 				float *input, int index_maximum,
> 				float *bias,
> 				float weight_scale,
> 				int N) {
>   int block_id = blockIdx.x;
>   int thread_id = threadIdx.x;  
>   int id = block_id*blockDim.x + thread_id;
>   
>   if (id < N) {
>     float input_scale = (float)127 / abs(input[index_maximum-1]);
>     float scale = input_scale * weight_scale;
>     output[id] = bias[id] + output_int[id]/(float)scale;
>   }
> }
> 
> cudaError_t CutlassInt8TN(
> 			  int M,
> 			  int N,
> 			  int K,
> 			  int alpha,
> 			  signed char const *A,
> 			  int lda,
> 			  signed char const *B,
> 			  int ldb,
> 			  int beta,
> 			  int *C,
> 			  int ldc) {
>   typedef cutlass::gemm::WmmaGemmTraits<
>     cutlass::MatrixLayout::kRowMajor,      // layout of A matrix
>     cutlass::MatrixLayout::kColumnMajor,   // layout of B matrix
>     cutlass::Shape<128, 128, 128>,         // threadblock tile size
>     signed char,                           // A type
>     signed char,                           // B type
>     int,                                   // D type
>     cutlass::gemm::LinearScaling<int>,     // functor to do the math in the epilogue
>     int,                                   // accumulator type
>     cutlass::Shape<128, 32, 32>,           // warp tile size
>     cutlass::Shape<16, 16, 16>,            // WMMA instruction tile size
>     16,                                    // scalars every time a thread loads from A
>     16                                     // scalars every time a thread loads from B
>     >
>     WmmaGemmTraits;
> ```
> 
> Thank you very much! The code I shared uses an older version of Cutlass to perform matrix quantization from fp32 to int8 and then conducts matrix multiplication, ultimately de-quantizing back to fp32. Now, I want to refactor this code using the latest version of Cutlass, and this code will be used within a for loop. To optimize the performance of this code during the refactoring, what steps should I take to ensure that it runs efficiently?

How can i use [numeric_conversion.h](https://github.com/manishucsd/cutlass/blob/main/include/cutlass/numeric_conversion.h) in my code, please?

**Comment by zwshan** [comment]
I have read some blog to know how to make it work. Please make this issue open until I give a reply, thanks.
