### ISSUE TITLE
typo for thread map in epilogue

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#117]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/epilogue/threadblock/default_thread_map_simt.h#L71

Is this the typo of below ?
`static_assert(
      !(ThreadblockShape::kM % WarpShape::kM) &&
      !(ThreadblockShape::kN % WarpShape::kN), "Divisibility");`

**Comment by hwu36** [comment]
Yes, you are right again.  Thank you for catching that.  We will fix it.

**Comment by d-k-b** [comment]
Fixed with 2.3. 

https://github.com/NVIDIA/cutlass/blob/c53f3339bb95ba52c5571134b1b3407e95a2546b/include/cutlass/epilogue/threadblock/default_thread_map_simt.h#L70-71
