### ISSUE TITLE
[DOC] CUTLASS 3.3 changelog change request 

### ISSUE THREAD

**Issue by manishucsd** [NVIDIA/cutlass#1170]
Suggesting a change to the changelog for CUTLASS 3.3

## Current ChangeLog
```md
New [Mixed Precision Hopper GEMMs](https://github.com/NVIDIA/cutlass/blob/main/examples/55_hopper_mixed_dtype_gemm) support covering 16-bit x 8-bit input types with optimal performance.
New [Mixed Precision Ampere GEMMs](https://github.com/NVIDIA/cutlass/commit/7d8317a63e0a978a8dbb3c1fb7af4dbe4f286616) with support for canonical layouts (TN) and {fp16, bf16} x {s8/u8}. They also include fast numeric conversion recipes and warp level shuffles to achieve optimal performance.
```

## Suggested change
```
New [Mixed-Input Hopper GEMMs](https://github.com/NVIDIA/cutlass/blob/main/examples/55_hopper_mixed_dtype_gemm) support covering 16-bit x 8-bit input types with optimal performance.
New [Mixed-Input Ampere GEMMs](https://github.com/NVIDIA/cutlass/pull/1084) with support for canonical layouts (TN) and {fp16, bf16} x {s8/u8}. They also include fast numeric conversion recipes and warp level shuffles to achieve optimal performance.
```

### Summary and rationale for the suggested changes
1. `Mixed-Precision` to `Mixed-Input`. [`Mixed-Precision`](https://arxiv.org/abs/1710.03740) is taken by the GEMM data-type where inputs (DataType(`operandA`) == DataType(`operandB`) are mixed with a different accumulation data type (`F16*F16+F32` and `BF16*BF16+F32`). The code uses [cutlass::arch::OpMultiplyAddMixedInputUpcast](https://github.com/manishucsd/cutlass/blob/main/include/cutlass/arch/mma.h#L73) tag to navigate and communicate that input data types are mixed. It would be good to set a nomenclature that is consistent and distinguishes between `Mixed-Precision` and `Mixed-Input` use-case. 

2. Update the hyperlink for `Mixed Precision Ampere GEMMs` to the [PR#1084](https://github.com/NVIDIA/cutlass/pull/1084) which has detailed description, steps to only compile Ampere mixed-input GEMMs, reproduce performance results, and a performance graph.

**Comment by mnicely** [comment]
We've moved to Mixed "Input"
