### ISSUE TITLE
Build issue on Windows / VSCode 2019 ( blocking Pytorch to upgrade Cutlass )

### ISSUE THREAD

**Issue by kadeng** [NVIDIA/cutlass#1171]
In Pytorch we're seeing a build failure on Windows with VS 2019, Cuda 11.8 and Cutlass 3.2.2 ( likely also with 3.3 ) that's currently blocking Pytorch to upgrade to Cutlass 3.2.2 or later.

[Pytorch PR 112762](https://github.com/pytorch/pytorch/pull/112762)
[Failing CI Job, with relevant line highlighted](https://github.com/pytorch/pytorch/actions/runs/6737625795/job/18315492490#step:10:9795)

We also might have identified what the problem is: The build failure logs the following error info (among other things): 
"cannot call non-constexpr function "cutlass::const_min".  

This const_min function ( from cutlass/fast_math.h ) has been declared as "constexpr" up to 3.2.0, but since 3.2.1 it's using a macro "CUTLASS_CONSTEXPR_IF_CXX17" that might not be doing the right thing for the Windows VSCode 2019 / CUDA 11.8 combination from the failing CI job.

**Comment by hwu36** [comment]
@mhoemmen

**Comment by kadeng** [comment]
Here is an attempt at a hotfix that I'm running through the Pytorch CI at the moment: 

https://github.com/NVIDIA/cutlass/compare/44c704eae85da352d277d6f092f41412772f70e4...0f7235ccefa10b9589ba0b767ac51c68ee0154de

**Comment by d-k-b** [comment]
@kadeng, if cutlass is being used as a header-only library as part of another build, please ensure the /Zc:__cplusplus flag is being applied when using msvc as the host compiler. This will ensure the __cplusplus flag is set appropriately for the selected compilation standard.

Example usage in CUTLASS builds.
https://github.com/NVIDIA/cutlass/blob/1d7f2a207ec215e037099f4ba5632ccfa0249673/CMakeLists.txt#L390

Documentation from Microsoft
https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170

**Comment by kadeng** [comment]
Thanks, I'm trying that ..

**Comment by kadeng** [comment]
That solved it, thanks.
