### ISSUE TITLE
redundant check on Iterations definition

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#118]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/pitch_linear_thread_map.h#L102

Is below a simpler version of above line ?
`Detail::ShapeVec::kStrided / (kThreads / Detail::ShapeVec::kContiguous)`

**Comment by Peter9606** [comment]
Another same question here
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/pitch_linear_thread_map.h#L678

**Comment by hwu36** [comment]
Yes, you are right.  We will fix it.  Thank you.

**Comment by hwu36** [comment]
Actually, we cannot do that.  The compiler will evaluate for both paths and you will get divide by zero error when compiling `04_tile_iterator`.

BTW, `04_tile_iterator` is a good resource for you to get familiar with global iterator.

**Comment by Peter9606** [comment]
I got it. Thank you.
