### ISSUE TITLE
About Delta of PitchLinearTilePolicyStripminedThreadContiguous 

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#119]
Per my understanding and also according to the comment here https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/pitch_linear_thread_map.h#L111
, "delta" should be in the units of elements, so is below line 
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/pitch_linear_thread_map.h#L154
 a typo of `using Delta = layout::PitchLinearShape<kThreads * kElementsPerAccess, 1>;  `

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-58

**Comment by hwu36** [comment]
This threadmap is used by GEMV which is not tested and maybe needs to be redone.

From code below `initial_offset()`, I guess Delta should be `layout::PitchLinearShape<kElementsPerAccess, 1>`.  Every thread is going to access `Iterations::kContiguous * kElementsPerAccess` contiguous elements in `Iterations::kContiguous` iterations.  Every iteration every thread accesses kElementsPerAccess data.  But, that is just my guess.

**Comment by Peter9606** [comment]
Thanks for your replying.
I didn't realized that it's used for GEMV, would you let me know how can I tell that from the code? Sounds it's other threadmap that should be used by GEMM for CUDA core, does it?

**Comment by hwu36** [comment]
You just need to grep.  Here is my grep results

./gemm/kernel/default_gemv.h:106:        cutlass::transform::PitchLinearTilePolicyStripminedThreadContiguous<
./gemm/threadblock/default_gemv_core.h:85:                            

```
cutlass::transform::PitchLinearTilePolicyStripminedThreadContiguous<
./gemm/threadblock/default_gemv_core.h:95:                            cutlass::transform::PitchLinearTilePolicyStripminedThreadContiguous<
./gemm/threadblock/default_gemv_core.h:105:                            cutlass::transform::PitchLinearTilePolicyStripminedThreadContiguous<
./transform/pitch_linear_thread_map.h:140:struct PitchLinearTilePolicyStripminedThreadContiguous
```

Basically, we use `PitchLinearStripminedThreadMap` for simt kernels and `PitchLinearWarpRakedThreadMap` for tensor core kernels.

**Comment by manishucsd** [comment]
`/include/cutlass/gemm/threadblock/default_mma_core_*` are good files to scroll through to know which ThreadMap is used for which operation:

**SIMT**: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/default_mma_core_simt.h#L154
**TensorOp**: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/default_mma_core_sm75.h#L139
