### ISSUE TITLE
[QST] cpp11.cu compiles with c++14

### ISSUE THREAD

**Issue by chsigg** [NVIDIA/cutlass#1198]
I think [cpp11.cu](https://github.com/NVIDIA/cutlass/blob/6e60b9b17c5e6734488dbb7401b5c55ccb37feba/test/unit/core/cpp11.cu#L76) should be comparing against (from https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html) `201103L`.

Although I vaguely remember that with a newer compiler, it can be difficult to test old standard compatibility. So maybe it just needs a comment that this is the best workable solution.

Feel free to close without comment, I just noticed the discrepancy between the code and the error message below.

**Comment by hwu36** [comment]
@kerrmudgeon

**Comment by hwu36** [comment]
that file is removed in 3.5
