### ISSUE TITLE
wrong shape definition for PitchLinearTilePolicyStripminedThreadStrided 

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#120]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/pitch_linear_thread_map.h#L184

Above code has an assumption that template parameter "ElementsPerAccess" is always 1 which seems not correct.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-57

**Comment by hwu36** [comment]
Sorry for the late response.

This one is used by GEMV which is not actively maintained now.  However, it does not mean it is not important.  More than welcome to help us resurrect it.
