### ISSUE TITLE
[QST] question about epilogue

### ISSUE THREAD

**Issue by zwshan** [NVIDIA/cutlass#1208]
**What is your question?**
If I don not need epilogue compute, can I remove it in my int8 cutlass matmul?
If I discard the epilogue, will the computation speed be faster than int8 matrix multiplication with the epilogue?

**Comment by JieRen98** [comment]
I think:
1. Yes, you can, or by setting scale kind to Nothing, check [here](https://github.com/NVIDIA/cutlass/blob/b5d8a5d9ccb435268e2215144dca162b0fc6a826/include/cutlass/epilogue/thread/scale_type.h#L58).
2. It will not be much faster, in practice.

**Comment by zwshan** [comment]
thanks

**Comment by hwu36** [comment]
the benefit mainly comes from I$.  If your kernel has lots of instruction, then yes, it can improve the performance.
