### ISSUE TITLE
Is a static_assert needed to ensure ShapeInAccesses is divisible by WarpThreadArrangement 

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#121]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/transform/pitch_linear_thread_map.h#L244

What if ShapeInAccesses isn't divisible by WarpThreadArrangement? Will one iteration is missed in this situation?

**Comment by hwu36** [comment]
Yeah, we can add an static_assert here.  I am sure we miss lots of such asserts.  Please refer to https://github.com/NVIDIA/cutlass/tree/4dac7490e6a846893595de352c57f2bf118796c1/test/unit/gemm for all plausible shapes.

**Comment by hwu36** [comment]
These are added: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/pitch_linear_thread_map.h#L251-L257
