### ISSUE TITLE
[QST]CUTLASS code auto-completion and navigation

### ISSUE THREAD

**Issue by jeejeeli** [NVIDIA/cutlass#1216]
**What is your question?**
When developing cutlass programs based on vscode, auto-completion and code navigation do not work well. Are there any good solutions for this? PS: I have installed clangd extension

**Comment by hwu36** [comment]
@d-k-b @mhoemmen

**Comment by JieRen98** [comment]
Use Clion

**Comment by jeejeeli** [comment]
> Use Clion

thanks for your reply,I want to know  if there is a better solution when use vscode

**Comment by mhoemmen** [comment]
Some developers use Visual Studio Code from their Windows systems to access files and perform builds on a remote (usually Linux) workstation.  Here are Microsoft's instructions for that.

https://code.visualstudio.com/docs/remote/ssh

I don't generally use Visual Studio Code for CUTLASS on Windows.  Visual Studio (not Code) does a fair job with auto-completion and code navigation.

**Comment by jeejeeli** [comment]
> Some developers use Visual Studio Code from their Windows systems to access files and perform builds on a remote (usually Linux) workstation. Here are Microsoft's instructions for that.
> 
> https://code.visualstudio.com/docs/remote/ssh
> 
> I don't generally use Visual Studio Code for CUTLASS on Windows. Visual Studio (not Code) does a fair job with auto-completion and code navigation.

Get it, thanks~
