### ISSUE TITLE
[QST] How to use cutlass in tensorrt_llm plugin?

### ISSUE THREAD

**Issue by yuanjiechen** [NVIDIA/cutlass#1220]
**What is your question?**
Hello, thanks for your project.
cutlass version: 2.10
device RTX 3090
I want to implement a W4A4 conv quantization in tensorrt_llm by cutlass.
Follow the example and document, I write the plugin and cutlass codes.
But it has huge amount of internal compile error, the build test on cutlass is passed.
I provide the code related to cutlass, can you provide some advise for debug?
I use TensorRef in plugin because the pointer provider by tensorrt is device side tensor, I want to construct the object and send it to Arguments.
Thanks
[quantConvKernels.cu.txt](https://github.com/NVIDIA/cutlass/files/13507296/quantConvKernels.cu.txt)
[quantConvKernels.h.txt](https://github.com/NVIDIA/cutlass/files/13507298/quantConvKernels.h.txt)
[err.txt](https://github.com/NVIDIA/cutlass/files/13507325/err.txt)

**Comment by hwu36** [comment]
first, on sm80 you can follow this to choose tile shapes: https://github.com/NVIDIA/cutlass/blob/main/test/unit/conv/device/conv2d_fprop_implicit_gemm_s4nhwc_s4nhwc_s32nhwc_tensor_op_s32_sm80.cu#L105-L107

as to your error, do you use nvcc to compile?

**Comment by hwu36** [comment]
if it uses make, you can use `make VERBOSE=1` to see the actual command line.  you error looks like you compiler does not recognize `<<< >>>` which is used by device kernel launch.

**Comment by rawnhenry** [comment]
Hi @yuanjiechen - It sounds like you are using the release branch of TRT-LLM. We have already updated TRT-LLM to depend on CUTLASS 3.3 in the main branch [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/3rdparty).

I would suggest using the main branch for your development.

**Comment by yuanjiechen** [comment]
I update my kernel file which contain cutlass from .cpp to .cu, but the problem still exist.
And I find the root cause of the make error.
First, the function call sequence is: quantConvPlugin(enqueue)->quantConvKernels(invokeGeneralQuantConv)->cutlass kernels.
Then, if I comment the "include quantConvKernels" in quantConvPlugin.h.21, we can pass the make.
But check the make log before and after comment, the quantConvKernels.cu/.h has already done for compile.
Besides, I update the kernel namespace to cutlass::conv::kernels, similar to cutlass, still not work.
[quantConvplugin.zip](https://github.com/NVIDIA/cutlass/files/13543555/quantConvplugin.zip)

**Comment by jackkosaian** [comment]
@yuanjiechen , what values of `N H W C K R S P Q` are you using in your example?

**Comment by yuanjiechen** [comment]
Hi @jackkosaian ,
N = 128, H = 32, W = 32, C = 32
K = 128, R = 3, S = 3, P = 32, Q = 32
Thanks

**Comment by jackkosaian** [comment]
Thanks for the details.

Can you also tell me the stride, dilation, and padding values you used?

I'll look into the alignment issue that you mentioned.

Regarding easier support for int4: the CUTLASS Python interface doesn't currently provide data type definitions -- input tensor are expected to be a numpy/torch/etc. tensor with a given element type defined by these libraries. Right now, if numpy/torch/etc. does not provide an implementation of a given data type, a technique similar to what you did must be used. We may reconsider this in the future if need be.

**Comment by yuanjiechen** [comment]
Hi @jackkosaian ,
Stride, dilation, and padding are all (1, 1).

**Comment by hwu36** [comment]
channel 3 is bad since it is 12bit.  i would imagine it needs to be at least 32bit.  cutlass has some special kernel for small channel size: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/convolution.h#L115  grep this word in conv/device unit tests for examples.  pay attention to the alignment settings.
