### ISSUE TITLE
[BUG] gemm universal streamk core dump when cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags return sm_occupancy_ is 0

### ISSUE THREAD

**Issue by Xseventh** [NVIDIA/cutlass#1223]
this kernel will run with:
Floating point exception (core dumped)

cuda version: 12.2
kernel config:
GemmUniversal with StreamK
A bf16 B bf16 C bf16 accum_dtype fp32
ThreadblockShape: 256 256 32
WarpShape: 64 64 32
Stage=1
I debug with logging find the coredump when call get_blocks, and sm_occupancy is 0.
sm_occupancy is construct by cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags, it returns the value is 0.
I understand that the configuration of BlockTile and WarpTile here may not be reasonable, but I would like to know if this kernel should be able to execute normally?
 how to correct fix this problem

**Comment by mnicely** [comment]
@Xseventh has your issue been resolved?

**Comment by Xseventh** [comment]
> @Xseventh has your issue been resolved?

I changed the Kernel configuration to another one and haven’t followed up on this problem recently.

**Comment by Xseventh** [comment]
> @Xseventh has your issue been resolved?

I recently learned that GemmUniversal shouledn't use Stage=1, maybe we can add some static_assert to make it better

**Comment by mnicely** [comment]
Thanks @Xseventh. I'll talk to the team about this.

**Comment by mnicely** [comment]
It looks like Stage=# is dependent on the hardware (i.e., Turing support Stage=1)

**Comment by mnicely** [comment]
Going to close for now. Reopen if needed.
