### ISSUE TITLE
[FEA] Can I use copy to store register value into shared memory?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1233]
Now I have tCrC, and I want to store them into shared memory. Can copy function do that? Thanks!

**Comment by ziyuhuang123** [comment]
I mean, using CuTe.

**Comment by ccecka** [comment]
If you've created your `tCrC` using some partitioner, then that same partitioner should be applied to an smem tensor. For example, we usually see this pattern:

```cpp
Tensor gC = ...                                          // (BLK_M,BLK_N)
Tensor sC = make_tensor(make_smem_ptr(ptr), shape(gC));  // (BLK_M,BLK_N)

auto thr_mma = tiled_mma.get_slice(thread_idx);

Tensor tCgC = thr_mma.partition_C(gC);                   // (MMA,MMA_M,MMA_N)
Tensor tCsC = thr_mma.partition_C(sC);                   // (MMA,MMA_M,MMA_N)
Tensor tCrC = thr_mma.make_fragment_C(tCgC);             // (MMA,MMA_M,MMA_N)

...

copy(tCrC, tCsC);
copy(tCsC, tCgC);
// or
copy(tCrC, tCgC);
```

**Comment by ziyuhuang123** [comment]
I noticed you are using "auto thr_mma = tiled_mma.get_slice(thread_idx);"
So what is its difference with: "auto tAgA = local_partition(gA, tA, threadIdx.x);                  // (THR_M,THR_K,k)"
??

**Comment by ccecka** [comment]
The first is partitioning with respect to an MMA `tiled_mma` (which is usually used to create `tCxY` partitioned tensors) and the second is partitioning with respect to the thread layout `tA`.

**Comment by ziyuhuang123** [comment]
Emmmm, so the output is the same, right? I mean, outputs are just "tensor" type, no matter how I get a "tensor", I can do "copy(tCrC, tCsC);" and cute will find a way to do the copy?

Thank you!!!

**Comment by ccecka** [comment]
No, they are not related.

I suggest you review the existing documentation and wait for our updated documentation+examples coming soon.

**Comment by ziyuhuang123** [comment]
Wow! That's cool! Actually I am writing relavant code pushed by my supervisor, haha.... Can not wait too long~He is a nice guy, I mean, anyway I am also interested in cute by myself also. 

Eagerly waiting for your update!

**Comment by ziyuhuang123** [comment]
Currently I only see one example code.... Do you possibly know more codes written by cute?

**Comment by ziyuhuang123** [comment]
Oh, I noticed most gemm codes are written using previous cutlass.... Maybe I should use older version...? Because that doc is more....

**Comment by mnicely** [comment]
Closing due to inactivitly
