### ISSUE TITLE
[QST]What is operator? How we use operator? (To access tensor elements)

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1235]
**What is your question?**
```
Array access
Users access a Tensor's elements in one of three ways:

operator(), taking as many integral arguments as the number of modes, corresponding to the element's (possibly) multidimensional logical index;

operator(), taking a Coord (an IntTuple of the logical indices); or

operator[], taking a Coord (an IntTuple of the logical indices).
```

I see this in the document. But I do not understand.... In example code, we do not need to access specific tensor value, we just insert all of them into gemm function. But, just for interest, what does here mean? Any example? Thank you!!!

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
I don't understand your question. The operators are accessing the underling values within the tensor by accepting an input coordinate and returning either a Tensor or a single value for that coordinate. These are eventually used when the tensor is dispatched to the atom within the MMA.
