### ISSUE TITLE
[QST] Where can I find cutlass3 code?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1239]
Hi! I have learnt cute (although still confused, haha) So I am wondering what code is written using cutlass3? All codes in 

[examples](https://github.com/NVIDIA/cutlass/tree/4a1709e17e021c483b10303be8d30c72a5b3aecb/examples) are using cutlass3, right?

**Comment by ziyuhuang123** [comment]
Emmmm, in example code, which one is fully optimized? Because I know lots of techniques, which one is mature enough? Thank you!!!!

**Comment by thakkarV** [comment]
example 48 and newer are based on CUTLASS 3 and use CuTe
Any Sm90 kernel in CUTLASS uses CuTe
