### ISSUE TITLE
[QST] how debug cutlass code？

### ISSUE THREAD

**Issue by zwshan** [NVIDIA/cutlass#1259]
**What is your question?**
Hello, I recently implemented an operator using Cutlass. The results are correct when the hidden layer size is small, but when the hidden layer size is large, I cannot obtain the correct results. I have carefully examined the code and cannot identify any issues. Can you please advise on how I should debug the code in this situation

**Comment by hwu36** [comment]
let one matrix to be sequential (0,1,2,...etc).  the other one to be identical.  then the result should be sequential.  if not, it is easy to spot which tile is wrong.  then you know which thread is wrong.
