### ISSUE TITLE
Is the access offset correct when ThreadMap::Iterations::kContiguous is greater than 1

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/cutlass#126]
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L557
I think the correct access offset would be
```
int access_offset =  stride_idx * ThreadMap::Delta::kStrided * stride_ / Layout::kFactor + iteration_contigous_ * (ThreadMap::Delta::kContiguous / kCrosswise) * Layout::kFactor * (kCrosswise / ThreadMap::kElementsPerAccess);
```
When this `Iterator` is used in the kernel of interleaved integer tensor op kernel, the `Delta` shape is computed for`RowMajor` or `ColumnMajor`. But in shared memory the layout is different, the access offset will be different. We cannot use `Delta` to compute access offset directly.  
It seems the code is copied from `RegularTileAccessIterator` for layout `TensorOpMultiplicandCongruous`.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-53

**Comment by hwu36** [comment]
I stared at your equation for two hours and I think I understand it now.  I agree with you that your equation is more general and can cover more  cases including those that are not used by our current kernels.  However, I think the 2nd half of your code can be simplified like this

```
Layout::kFactor * (kCrosswise / ThreadMap::kElementsPerAccess) 
= Layout::kTileShapeContiguous * kElementsPerAccess / kCrosswise * kCrosswise / kElementsPerAccess
= Layout::kTileShapeContiguous
```

which is a constant 8.  This constant means every shared memory line has 8 accesses.

The underlying assumption is that every `kCrosswise` elements in the contiguous dimension would span a shared memory line during shared memory swizzling.  `ThreadMap::Delta::kContiguous` cannot be smaller than `kCrosswise` which is the smallest unit needed by the shared memory swizzling.

I am going to add an assert for `kFactor > 0`, an assert for `ThreadMap::Delta::kContiguous >= kCrosswise`, and change the code to

```+ iteration_contigous_ * (ThreadMap::Delta::kContiguous / kCrosswise) * Layout::kTileShapeContiguous```

Thank you very much!  You truly understand the most tricky part.

**Comment by xiaocenxiaocen** [comment]
Thank you for your reply.  
I think a stronger assert `!(ThreadMap::Delta::kContiguous % kCrosswise)` should be used.

**Comment by hwu36** [comment]
Yeah, I agree.
