### ISSUE TITLE
[QST] example 13_two_tensor_op_fusion, what to do with no relu

### ISSUE THREAD

**Issue by harryhan618** [NVIDIA/cutlass#1263]
Hello, I just found the example 13_two_tensor_op_fusion. And I'm trying to extract this example for general purpose.

But I want to get Z=X@W1@W2, so I try to replace [this line](https://github.com/NVIDIA/cutlass/blob/30ec1a464961df8e511a1562976a7a8527e1e554/examples/13_two_tensor_op_fusion/fused_two_gemms_grouped_f16_sm80_rf.cu#L201) `EpilogueOutputOp0` and `EpilogueOutputOp1` with `LinearCombination<half_t, 8, float, float>`. But I fail to compile.

Could you kindly help me with what's going wrong?

**Comment by hwu36** [comment]
my guess is don't change `InstructionShape::kM * InstructionShape::kN / 32`

**Comment by mnicely** [comment]
@harryhan618 has your issue been resolved?
