### ISSUE TITLE
[QST] Row Major epilogue operands in SM90 GEMMs

### ISSUE THREAD

**Issue by alihassanijr** [NVIDIA/cutlass#1265]
Can SM90 WGMMAs built with collective builders support row-major layouts for epilogue operands (C/D)?

`cutlass_library` is only emitting kernel instantiations with column-major epilogues:

* [16-bit](https://github.com/NVIDIA/cutlass/blob/main/python/cutlass_library/generator.py#L4335-L4340)
* [16-bit custom alignment](https://github.com/NVIDIA/cutlass/blob/main/python/cutlass_library/generator.py#L4505-L4514)
* [32-bit](https://github.com/NVIDIA/cutlass/blob/main/python/cutlass_library/generator.py#L4653-L4658)
* [32-bit custom alignment](https://github.com/NVIDIA/cutlass/blob/main/python/cutlass_library/generator.py#L4777-L4786)

Thank you.

**Comment by thakkarV** [comment]
Yes. Row major output tensor layouts are fully supported by both TMA and the direct store epilogues.

**Comment by alihassanijr** [comment]
Thank you.
