### ISSUE TITLE
[QST] TMA copy dependency on `cuTensorMapEncodeTiled`

### ISSUE THREAD

**Issue by alihassanijr** [NVIDIA/cutlass#1267]
**What is your question?**

TMA copy atoms appear to depend on [cuTensorMapEncodeTiled](https://github.com/NVIDIA/cutlass/blob/main/include/cute/atom/copy_traits_sm90_tma.hpp#L708-L720) for initializing TMA descriptor, which is part of cuda toolkit. Would it be possible to implement this without this dependency and not have to link with cuda?

**Comment by thakkarV** [comment]
Unfortunately there's no way to construct TMA descriptors right now other than using this driver API
