### ISSUE TITLE
What is the meaning of the magic number of `FastNumericArrayConverter`?

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/cutlass#127]
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/numeric_conversion.h#L1090  
What is the difference of the rounding behavior between the `NumericArrayConverter` and `FastNumericArrayConverter` for conversion from float to int8_t?

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/epilogue/thread/linear_combination_clamp.h#L405

This version is useful only when problem_size_K <= 256 for signed int8 gemm or problem_size_K <= 128 for unsigned int8 gemm.  This version maybe faster in some cases.  To make it run even faster, you can move `+ 1262485504` from this line https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/numeric_conversion.h#L1066 to here https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/gemm/kernel/gemm.h#L238
Just initialize the `accum` with `1262485504`.  If you want to know how it works, you need to dig into fp32 format to understand.  

The always safe and regular version is here https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/epilogue/thread/linear_combination_clamp.h#L232

**Comment by xiaocenxiaocen** [comment]
So if the value of accumulator is greater than `256*128`, the `FastNumericArrayConverter` will cause precision issue?

**Comment by hwu36** [comment]
you'll get completely wrong results.

**Comment by d-k-b** [comment]
@xiaocenxiaocen, closing for now. Reopen if you have further issues.
