### ISSUE TITLE
why same src and dst are used for mov.b32?

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#128]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/include/cutlass/arch/memory.h#L167

Could anyone explain why move data to data is required here? Thanks.

**Comment by hwu36** [comment]
Consider it as a programming trick.  It enforces this piece of ptx code to both read and write `data`, then the compiler would initialize `data` to 0 before `setp`.  If you remove this `mov` line, the compile would not initialize `data` properly which is not the intention and would generate the wrong results when `ld.global` is not executed.

**Comment by Peter9606** [comment]
Got it, thank you very much!
