### ISSUE TITLE
[QST]question about cutlass epilogue customization

### ISSUE THREAD

**Issue by zwshan** [NVIDIA/cutlass#1288]
**What is your question?**
May I ask if the epilogue of Cutlass supports customization? I hope to achieve the functionality of performing bias addition after the matmul operation in Cutlass. Additionally, I would like to apply different activation functions to different regions (for example, sigmoid and tanh). Is it possible to implement this? If so, could you please teach me how to do it？

**Comment by hwu36** [comment]
Yes, you can do any elementwise operation you want.  Are you using cutlass 2.x or 3.x?  Which architecture?

**Comment by zwshan** [comment]
> Yes, you can do any elementwise operation you want. Are you using cutlass 2.x or 3.x? Which architecture?

I am using 3.x and A100 sm80, could you help me?

**Comment by zwshan** [comment]
![8701704719135_ pic](https://github.com/NVIDIA/cutlass/assets/62176674/290a3c6a-82af-4d77-a08d-d50cced89c27)
Can cutlass do this? @hwu36

**Comment by hwu36** [comment]
@thakkarV to comment on how to do it with 3.x on A100.

**Comment by jackkosaian** [comment]
cc @apuaaChen for thoughts on how to do this with CUTLASS 3.x SM80 EVT (likely would need some added ops)

**Comment by hwu36** [comment]
this should be similar to epilogue scatter fusion since it needs to compute row number, too.

**Comment by thakkarV** [comment]
this is pretty easy to do in the CUTLASS 3 epilogues, but not something you can do OOTB so you will have to make a minor modification for a custom epi. One additional branch to dispatch to the activation function depending on the coordinate of the output tensor. You have access to the coordinate tensors already for the purpose of predicated stores to gmem, so just use those. https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/collective/sm70_epilogue_vectorized.hpp#L230

**Comment by thakkarV** [comment]
btw, I do not want to discourage you from using the 3.x API on Ampere, its totally kosher, we just recommend 2.x API for best performing Ampere kernels since they are well tuned over the years.

**Comment by zwshan** [comment]
thank you everyone！you help me a lot. I will try it morning.

**Comment by mnicely** [comment]
@zwshan have you resolved your issue?

**Comment by apuaaChen** [comment]
Hi! It can be supported by adding a new node. In order to get the row number, you can following the examples here
https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/fusion/visitor_store.hpp#L749-L752
The coord at line 749 is the row number, column number, batch number.
