### ISSUE TITLE
Enable test level control in clang environment 

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#129]
https://github.com/NVIDIA/cutlass/blob/4dac7490e6a846893595de352c57f2bf118796c1/CMakeLists.txt#L172

A line after above is missed to enable test level control in clang environment
`list(APPEND CUTLASS_CUDA_CLANG_FLAGS -DCUTLASS_TEST_LEVEL=${CUTLASS_TEST_LEVEL})
`
Inserting above cmake code, the CUTLASS_TEST_LEVEL works under clang.

**Comment by hwu36** [comment]
Thank you, we will fix it.

**Comment by d-k-b** [comment]
Should be fixed in CUTLASS 2.3!
