### ISSUE TITLE
[QST] How to use splitk in cutlass python?

### ISSUE THREAD

**Issue by Miroier** [NVIDIA/cutlass#1295]
**What is your question?**

Background: A100, nvidia-cutlass 3.3.0.0

When k is much larger than m n , I want to find a cutlass kernel with faster running time than cupy.dot because cupy.dot does not reach the peak performance of A100. My data size is m=n=128,k=16384. I used cutlass profiler to find a potentially faster kernel. But I found that there is no way to specify split_k_mode and split_k_slices in cutlass.op.Gemm.

**Comment by jackkosaian** [comment]
Good catch. This is currently missing from `cutlass.op.Gemm`. We will add it soon.

**Comment by Miroier** [comment]
If I want to use splitk in python, is it a feasible way to write the c++ code first, compile it into dynamic libraries and then load the dynamic libraries with python's ctypes? Or do you have any other better suggestion?

**Comment by jackkosaian** [comment]
My suggestion would be to use tools like Pybind to create Python-C++ bindings for calling into a CUTLASS C++ kernel via Python.

For example, you can take a look at how PyTorch CUDA extensions can be created for a CUTLASS kernel by following [this unit test](https://github.com/NVIDIA/cutlass/blob/acba5beee568792da609ef27275fe9e459a36a25/test/python/cutlass/emit/pytorch.py#L122-L131). If you set `jit=False` [here](https://github.com/NVIDIA/cutlass/blob/acba5beee568792da609ef27275fe9e459a36a25/test/python/cutlass/emit/pytorch.py#L131), you can build an offline library called "gemm_mod", by running `python setup.py install` on the generated `setup.py` file. You can also inspect the contents of the generated `gemm_mod.cu` and `gemm_mod.cpp` to see how the C++-Python bindings are set up.

You could follow a similar pattern by pasting your desired CUTLASS C++ kernel into `gemm_mod.cu`. You may need to make some slight changes to other parts of the generated files to match your kernels.

If you follow the steps in that notebook, but set `jit=False`
