### ISSUE TITLE
[QST]serial splitK gemm， semaphore deadlock。

### ISSUE THREAD

**Issue by YuQ-sudo** [NVIDIA/cutlass#1296]
**What is your question?**
when using serial splitK gemm to solve problem size of  1024x832x4096, there is a dead lock in semaphore  wait.
when I Comment out this code,dead lock disappears,but it comes to wrong result.
Can someone tell me how to fix dead lock or  some potential reasons that might cause this.
    // Wait on the semaphore - this latency may have been covered by iterator construction
    if (params.mode == GemmUniversalMode::kGemm && params.grid_tiled_shape.k() > 1) {
        
      // For subsequent threadblocks, the source matrix is held in the 'D' tensor.
      if (threadblock_tile_offset.k()) {
        iterator_C = iterator_D;
      }

      // semaphore.wait(threadblock_tile_offset.k());

    }

**Comment by YuQ-sudo** [comment]
I try to  use cutlass_profiler to test sgemm of different kernels. for example,ThreadBlockShape 128x64x8  warpShape 32 x 32 x 8.  It's  still blocked  in  semaphore wait function.

**Comment by hwu36** [comment]
any other kernels running at the same time?  do you modify any code?

**Comment by hwu36** [comment]
what is your splitk slices do you use?

**Comment by hwu36** [comment]
also what is your hardware?

**Comment by YuQ-sudo** [comment]
there is no other kernels running at the same time. In fact, I‘m trying to run cutlass in amd hardware of simt arch. So I modify some code of ptx, not including splitK. I try to use slices of 2,4,8, nothing works.

**Comment by hwu36** [comment]
No guarantee that it works on other non nvda hw.

**Comment by thakkarV** [comment]
Can you repro this on NVIDIA hardware?

**Comment by YuQ-sudo** [comment]
Ok, I will have a try on nvidia hardware.

**Comment by YuQ-sudo** [comment]
I have try it on nvidia hardware, it works fine. It seems that may be the hardware causes the error.
