### ISSUE TITLE
[QST] Question on customize epilogue reduction

### ISSUE THREAD

**Issue by zejia-lin** [NVIDIA/cutlass#1301]
**What is your question?**

Hello, I found that many epilogues are element-wise. I wondered if it could be customized to sum up a `2*2` tile instead of an element-wise operation. That is, for `D = AB + C`, where A is a `(m*2, k)` matrix, B is a `(k, n*2)` matrix, and C, D is `(m, n)` matrix . While AB produces a `(m*2, n*2)` matrix, is it possible to sum up every `2*2` tile of the output matrix and produce a `(m, n)` matrix?

Many thanks for any advice.

<img width="471" alt="image" src="https://github.com/NVIDIA/cutlass/assets/41103526/34f123a8-b4e1-49d7-93e0-fe06ae8436d5">

**Comment by hwu36** [comment]
which hardware do you use?  what is the data type?  do you want to use tensor cores?

**Comment by zejia-lin** [comment]
I am using A100, both cutlass 2.x and 3.x is suitable for me. The data type of A and B are `int8` with `int32` accumulation, C and D are `int32`. I do want to use tensor core. 

I simplified my question for clarity, in fact I have a complex kernel rather than summing up the `2*2` tile, which takes `2*2` elements and returns `1` element. If there is such functionality listed below, this may be easily done.
1. can operate on the accumulation fragment after performing GEMM and before writing to global memory. Possibly the epilogue stage, I guess.
2. can change the load and store pattern of C and D. Because A, B are 2m-by-2n-by-k matrices, and produce a 2m-by-2n matrix. My kernel works on the 2m-by-2n matrix and produces a m-by-n matrix, which is the dimension of C and D.

Specifically, If not using cutlass, the pseudo code of my kernel looks like

```cpp
#define idx(i, j, ld) ((i) + (j) * (ld))

__global__ void my_epilogue(size_t m, size_t n, const int *Acc, size_t lda, int *C, size_t ldc){
    size_t tx = threadIdx.x + blockIdx.x * blockDim.x;
    size_t ty = threadIdx.y + blockIdx.y * blockDim.y;
    int tmp;
    for(int i = 0; i < 2; ++i){
        for(int j = 0; j < 2; ++j){
            tmp += Acc[idx(tx * 2 + i, ty * 2 + j, lda)];
        }
    }
    C[idx(tx, ty, ldc)] = tmp;
}
```

**Comment by hwu36** [comment]
in 2.x, you can get row coordinate from `row_offset + thread_start_row_` in https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h#L398  

every threads own several fragments.  every fragment owns `kElementsPerAccess` consecutive data in the same row.  you can first do 1x2 reduction here. then do more reduction with different threads in the next row. 

you can first dump row coordinates and check the mapping between thread id and row coordinate.  all the mapping information you need is actually in `ThreadMap`  (https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h#L71)

don't forget to change the memory pointer at last (https://github.com/NVIDIA/cutlass/blob/acba5beee568792da609ef27275fe9e459a36a25/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h#L414) for the new coordinates.

**Comment by zejia-lin** [comment]
Thank you for the detailed reply. I'll try it later.

**Comment by mnicely** [comment]
@zejia-lin have you resolved your issue?

**Comment by zejia-lin** [comment]
I am sorry for the late response. I found I was not able to resolve it under reasonable efforts. I am closing this issue.
