### ISSUE TITLE
Best Order For Performance

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/cutlass#131]
Hi, I've noticed in cuBLAS that there is a penalty when performing the transposes needed for row-major input and output relative to pure column major. For CUTLASS complex tensor examples, we have the extra luxury that the planar input and output forces us to do conversions to that format from the native cuComplex. Given that we have the freedom to transform into any format we'd like on input and output, is there a difference in performance for row versus column-major with CUTLASS complex on tensor cores? Should we also try to stick to the computations being column-majored? Note I'm only asking in the case of the NN transform.

I should also mention (and this is a separate issue), but I cannot get the profile to output anything, no matter what I try. I compiled only for complex tensor core support, and it won't run any of the profiler tests, and there are no errors:
```
 ./tools/profiler/cutlass_profiler --operation=Gemm --gemm_kind=planar_complex --op_class=tensorop
 ./tools/profiler/cutlass_profiler --operation=Gemm --gemm_kind=planar_complex --op_class=tensorop  --m 8 --n 8 --k 8
 ./tools/profiler/cutlass_profiler --operation=Gemm --gemm_kind=planar_complex --op_class=tensorop  --m 8 --n 8 --k 8 --providers=cutlass
 ./tools/profiler/cutlass_profiler --operation=Gemm --gemm_kind=planar_complex --op_class=tensorop  --m 8 --n 8 --k 8 --min_cc=75 --max_cc=75
 ./tools/profiler/cutlass_profiler --operation=Gemm --gemm_kind=planar_complex --op_class=tensorop  --m 8 --n 8 --k 8 --min_cc=75 --max_cc=75 --batch_count=1000
```

**Comment by kerrmudgeon** [comment]
Column-major * row-major ("NT") GEMMs typically achieve the highest performance for nearly every math instruction (except integer-valued TensorCore operations).  These have the fewest number of integer arithmetic instructions and typically also have simpler Shared Memory layouts.

If you have the option of folding transposes into the layout transformations, I'd recommend transposing the 'B' operand and calling the "NT" kernels.

**Comment by cliffburdick** [comment]
Thanks @kerrmudgeon! Right when you wrote that I recompiled the cutlass_profiler with all kernels enabled, and I confirmed what you had said. The difference was small between NT and NN, but TN/TT it was a large difference (about 20% on a V100). I will stick with your suggestion.

**Comment by zlf111** [comment]
@kerrmudgeon Hi, I observed different phenomena on my RTX 3080 Ti 3080 laptop. I ran the **simpleCublas** example from the CUDA Toolkit samples and set **cublasSetMathMode (handle, CUBLAS_TENSOR_OP_MATH)**;. Then I added some precise timing code. I tested several sizes, such as m=n=k=1024, 1048, 4096. I found that the **TN** case was always slightly **better** than the **NT** case. So, has NVIDIA now done some special optimization for the TN case?

**Comment by mnicely** [comment]
TN usually has some hw optimizations or less overhead.
