### ISSUE TITLE
[QST] Can int8_t be type of ElementA and ELementB in gemm_softmax (in example 35) ?

### ISSUE THREAD

**Issue by MingZwhy** [NVIDIA/cutlass#1310]
I compiled the example 35 (gemm_softmax) successfully, but when I changed the type of ElementA and ElementB into int8_t, I met 
Imcomplete Type Error. As we know s8 * s8 + float = float is absolutely supported in cutlass gemm, I guess s8 should also be allowed in gemm_softmax. Can anyone give me some suggestions?

**Comment by hwu36** [comment]
you need to change the tile size to what s8 uses.  https://github.com/NVIDIA/cutlass/blob/main/examples/35_gemm_softmax/gemm_softmax.cu#L214-L216  you can find some s8 friendly tile sizes in https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/gemm_s8t_s8n_s32n_tensor_op_s32_sm80.cu

@yzhaiustc to follow

**Comment by yzhaiustc** [comment]
Thanks @hwu36 for tagging.

Yes int8 should be supported as long as s8-friendly params are selected. If you find any further issues please let me know - I'm glad to help fixing it.

**Comment by MingZwhy** [comment]
> you need to change the tile size to what s8 uses. https://github.com/NVIDIA/cutlass/blob/main/examples/35_gemm_softmax/gemm_softmax.cu#L214-L216 you can find some s8 friendly tile sizes in https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/gemm_s8t_s8n_s32n_tensor_op_s32_sm80.cu
> 
> @yzhaiustc to follow

Thanks a lot!
I found I forgot to set AccumulatorType to be int32_t when ElementA and ElementB are both int8_t type. When this param is set correctly, gemm_softmax works.
