### ISSUE TITLE
[QST] how to avoid register spill for example 48

### ISSUE THREAD

**Issue by zhang662817** [NVIDIA/cutlass#1311]
commit id: 757275f2796bb901575c633e2a32bc76ca84ffec
device arch: hopper;

change LayoutA to cutlass::layout::ColumnMajor;
change LayoutB to cutlass::layout::RowMajor;  
![image](https://github.com/NVIDIA/cutlass/assets/20987824/6e699c3a-d450-40b8-b405-04e567b60617)

kernel will run RS kernel;

profiling result: 
![image](https://github.com/NVIDIA/cutlass/assets/20987824/05a797b2-c332-49c4-8c3c-818aa6140b6e)

register spill;

change Tile to Shape<_128, _64, _32>;

no change.

How to config to avoid register spill

**Comment by zhang662817** [comment]
![image](https://github.com/NVIDIA/cutlass/assets/20987824/7229bc68-e352-4a63-a060-1e63d3ed0a34)
explicit total Reg size: 128 * (64 + 16) * 2 * 4 / 1024.0 = 80K， which far less than sm regfile 256K;

Is explicit total register size calculation right?

Thanks.

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
tagging @IonThruster and @ANIKET-SHIVAM as well

**Comment by thakkarV** [comment]
@zhang662817 have you been able to use the NT layout TF32 kernel from the CUTLASS profiler? You can copy its configuration since we know that one does not spill and has great performance.

**Comment by zhang662817** [comment]
@thakkarV  @ANIKET-SHIVAM 
Our case is ElementA=float, LaoutA=ColumnMajor, ElementB=float, LayoutB=RowMajor;
How to avoid register spill for these cases? and Why does register spill?

**Comment by thakkarV** [comment]
> What's the difference bewteen float and tf32? In culass, float uses tf32 tcore and tf32 alse uses 32 bit in storage in shared smem and register file, is right?

If you set op class to tensor op and set ftype to fp32, the kernel will do numeric conversion in the kernel after loading data from gmem. If you set it to tf32, no conversion will be performed.

What CUDA toolkit are you using? There were some fixes in the compiler that affected the performance of tf32 kernels in 12.1 and 12.2. They should not spill with a 128x64x32 tile shape for ping-pong and 128x128x32 tile shape for cooperative.

**Comment by zhang662817** [comment]
@thakkarV  cuda 12.2; pytorch docker: 23.10-py3.

Thanks.

**Comment by thakkarV** [comment]
have you tried out the kernel from profiler corresponding to this layout ? I forget the optimized configuration that does not spill for TF32, but it is present in our profiler and I would recommend using that

**Comment by mnicely** [comment]
@zhang662817 has your issue been resolved?
