### ISSUE TITLE
[QST]How to control the layout of simt accumulators

### ISSUE THREAD

**Issue by mammoth831** [NVIDIA/cutlass#1313]
Hi, @ccecka

For the following tiled mma:
```c++
#include <cute/tensor.hpp>
#include <cute/atom/mma_atom.hpp>

using namespace cute;

int main() {
  using TiledMma = TiledMMA<
                    MMA_Atom<UniversalFMA<float>>,
                    Layout<Shape<_2, _2, _1>, Stride<_2, _1, _1>>,
                    Tile<Layout<Shape<_2, _4, _1>, Stride<_4, _1, _0>>,
                         Layout<Shape<_2, _4, _1>, Stride<_4, _1, _0>>, Underscore>>;

  print_latex(TiledMma{});
}
```

Each thread has a 4x4 accumlator arranged in col-major layout. It is convenient to do STG.128 for a col-major dst matrix directly. 

However, we cannot do it without shuffle for a row-major dst matrix. Namely, we cannot get 4 from `decltype(max_common_vector(accumulators, tCgC))::value` for a row-major dst matrix in the epilogue.

How to get a row-major accumlator like this, then we can also do STG.128 directly in this situation. Maybe we can hardcode the layout of the accumulator register for a specific case, but I want to know how to do it when we are using the default general collective pipeline.

```c++
---------------------------------------------------------
| T0V0 | T0V1 | T0V2 | T0V3 | T1V0 | T1V1 | T1V2 | T1V3 |
---------------------------------------------------------
| T0V4 | T0V5 | T0V6 | T0V7 | T1V4 | T1V5 | T1V6 | T1V7 |
---------------------------------------------------------
.....
```

**Comment by ccecka** [comment]
I thought `make_fragment_like` or `make_tensor_like` would function here, but it appears those are broken for these applications and should be repaired. I'll include a fix for this in my next release of documentation and CuTe examples, thanks!

The easiest thing you can do at the moment, it appears, is order the tensor yourself:
```cpp
  using TiledMma = TiledMMA<
                    MMA_Atom<UniversalFMA<float>>,
                    Layout<Shape<_2, _2, _1>, Stride<_2, _1, _1>>,
                    Tile<Layout<Shape<_2, _4, _1>, Stride<_4, _1, _0>>,
                         Layout<Shape<_2, _4, _1>, Stride<_4, _1, _0>>, Underscore>>;

  TiledMma tiled_mma;
  ThrMMA thr_mma = tiled_mma.get_slice(0);
  //print_latex(TiledMma{});

  // (BLK_M, BLK_N)
  Tensor gC = make_tensor((float*) nullptr, make_shape(Int<32>{}, Int<32>{}), make_stride(42, Int<1>{}));
  // (MMA, MMA_M, MMA_N)
  Tensor tCgC = thr_mma.partition_C(gC);

  //Tensor tCrC = thr_mma.make_fragment_C(tCgC);
  //Tensor tCrC = make_tensor_like(tCgC);
  Tensor tCrC = make_tensor<float>(make_ordered_layout(shape(tCgC), Step<_0,_2,_1>{}));

  print(tCgC); print("\n");
  print(tCrC); print("\n");
```
where `make_ordered_layout` generates strides for the given shape following the order of the `Step` argument.

**Comment by mammoth831** [comment]
`make_ordered_layout` generates expected stride for me, but it changes the original method to allocate accumulators.

https://github.com/NVIDIA/cutlass/blob/9385141f19d87d9fb4c24fb29b65d0e8facd55a7/include/cutlass/gemm/kernel/sm70_gemm.hpp#L235

It seems that I have to allocate new accumulators in my custom epilogue and then copy to it if I don't modify `sm70_gemm.hpp` ?

```c++
using AccStep = conditional_t<detail::is_major<1, StrideC>(), Step<_0,_2,_1>, Step<_0,_1,_2>>
Tensor tmp = make_tensor<float>(make_ordered_layout(shape(tCgC), AccStep{}));
MUTE_UNROLL
for (int i = 0; i < size(tmp); ++i) 
  tmp(i) = accumulators(i);
// do something...
```

Will the new version provide more flexible Stride control during `partition_fragment_C`? Then we can directly get the desired accumulators.

**Comment by ccecka** [comment]
That `partition_fragment_C` pattern has no hope of matching any other data layout because it takes no other data layout. I don't recommend that and it should be fixed in the `sm70_gemm.hpp` as well.

I do recommend using one of the following methods
```cpp
  Tensor accumulators = thr_mma.make_fragment_C(tCsC);
  Tensor accumulators = make_fragment_like(tCsC);
  Tensor accumulators = make_tensor<float>(make_ordered_layout(shape(tCgC), Step<_0,_2,_1>{}));
```
which have the option of inspecting `tCsC` or `tCgC` and attempting to "match" the layout. In general, it's better to pass the previously partitioned smem tensor because it is almost always static. As you've pointed out, I would also like to enhance `make_tensor_like` and `make_fragment_like` to inspect layouts that may have dynamic strides (like `tCgC` often does) and "match" those layouts as best as possible as well.

**Comment by mammoth831** [comment]
got it. thanks!
