### ISSUE TITLE
[FEA] W4A8 gemm surpport.

### ISSUE THREAD

**Issue by Ageliss** [NVIDIA/cutlass#1316]
It seems we had INT4.GEMM and INT8.GEMM, even FP8.GEMM, but actually activations in LLMs are hard to be compressed. We sometime use W4A8 in the gemm, however, we first uncompress the two-INT4 stored in one INT8 and carry out the INT8.GEMM. This is ugly and very slow due to the memory reading and writing for INT4 decompress to INT8 process.

[FEA]: I ask for the surpport for INT4 * INT8 and output INT32/8.

W-A-KV bits:
<img width="946" alt="image" src="https://github.com/NVIDIA/cutlass/assets/11551984/c6b45c7f-3452-413a-8c7f-780d20bd7c3e">
figure is citing from the LLM.QAT paper.

**Comment by hwu36** [comment]
several sources: 

w4a8 is already supported on hopper. check 3.3 and 3.4 changelog

on ampere, https://github.com/NVIDIA/cutlass/pull/1190 adds int4 support (@alexsamardzic ).  FastTransformer also has it which requires a special layout (https://github.com/NVIDIA/cutlass/discussions/911 @rhenry-nv).  there is also a paper (https://arxiv.org/abs/2311.09550) about a w4a8 product solution.

**Comment by Ageliss** [comment]
> several sources:
> 
> w4a8 is already supported on hopper. check 3.3 and 3.4 changelog
> 
> on ampere, #1190 adds int4 support (@alexsamardzic ). FastTransformer also has it which requires a special layout (#911 @rhenry-nv). there is also a paper (https://arxiv.org/abs/2311.09550) about a w4a8 product solution.

Thanks very much for your reply.

**Comment by alexsamardzic** [comment]
I'm now working on this feature - #1413 is created, so this issue could be closed.
