### ISSUE TITLE
What does tensor_Scale0 means in B2b_gemm and how can I pass bias of the first gemm to B2b_gemm?

### ISSUE THREAD

**Issue by MingZwhy** [NVIDIA/cutlass#1319]
I want to use gemm_relu_gemm_relu fusedop shown in example-two_tensor_op,
But when I try to find how to set an argument for B2bgemm, I checked the b2b_interleaved_gemm_run.h:
`    //
    // Initialize the GEMM operator
    //

    typename B2bGemm::Arguments arguments{
      mode,
      problem_size_0,
      problem_size_1,
      tensor_A0.device_ref(),
      tensor_B0_reordered.device_ref(),
      tensor_C0.device_ref(),
      tensor_Scale0.device_ref(),
      tensor_Bias0.device_ref(),
      tensor_B1_reordered.device_ref(),
      {tensor_Bias1.device_data(), typename B2bGemm::LayoutC::Stride(0)},
      tensor_D1.device_ref(),
      batch_stride_A0,
      batch_stride_B0,
      batch_stride_B1,
      batch_stride_C1,
      batch_stride_D1,
      batch_stride_Bias0,
      batch_stride_Scale0,
      {alpha0, beta0},
      {alpha1, beta1},
      batch_count,
    };` 
I'm confused about the meaning of tensor_Scale0, and I see in example/fused_two_gemms_s8_sm80_rf.cu, beta0 is set to 0 and reference said `//Fused kernel has built-in bias, setting beta=0`, what should I do if I hope bias0 is scaled? Thanks for your suggestions!

**Comment by hwu36** [comment]
@jwang323

**Comment by jwang323** [comment]
The example only support scaling on the output of A0*B0, but not the bias. This is what we typically see in a GEMM operation:
D0 = scale * A0*B0 + bias

I guess what you want is a scalable residual matrix C0, i.e.
D0 = alpha * A0*B0 + beta * C0 + bias

Unfortunately we don't support that in the b2b GEMM fuse example. You'll need to define your own iterators to load C0 and beta, and change the example accordingly.
