### ISSUE TITLE
Slow Compilation

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/cutlass#132]
Hi, I updated to CUTLASS 2.2, and am only looking to compile the row-major complex tensor core kernels for compute capability 7.0+. I used this filter: `-DCUTLASS_NVCC_ARCHS="70;75;80" -DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_*gemm_planar_complex`, but this takes upwards of 45 minutes to compile with make -j 32 on an 40-core machine. Is there any way to speed this up? Is setting the operation (NN/NT/etc) the last way to filter down for this type? I can't see anything specific to row-major -- will it treat TT the same as row-major?

**Comment by manishucsd** [comment]
You are currently compiling 1634 kernel instances. You can list all the kernel instances that are being compiled in the build folder: 

```
/build $ ls -R tools/library/generated/gemm/ 
tools/library/generated/gemm/:
all_gemm_operations.cu                                                               cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_hh_align2.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_ch_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_cc_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_hh_align8.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_cn_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_ch_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_hn_align1.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_ct_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_cn_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_hn_align2.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_hc_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_ct_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_hn_align8.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_hh_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_hc_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_ht_align1.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_hn_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_hh_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_ht_align2.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_ht_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_hn_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_ht_align8.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_nc_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_ht_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_nc_align1.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_nh_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_nc_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_nc_align2.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_nn_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_nh_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_nc_align8.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_nt_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_nn_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_nh_align1.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_tc_align8.cu
cutlass_tensorop_bf16_s16816gemm_planar_complex_array_bf16_128x64_32x3_nt_align8.cu  cutlass_tensorop_f16_s884gemm_planar_complex_f16_64x64_32x2_nh_align2.cu        cutlass_tensorop_s16816gemm_planar_complex_array_bf16_64x64_32x4_th_align8.cu
```

You can filter based on input data types, accumulation type, and tile sizes. If you just want complex kernels with f32 accumulation on f16 input use something like:
`-DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_f16_s*gemm_planar_complex*f16*`
This should bring the kernels down to 482. 

I don't quite follow your last comment:

>  I can't see anything specific to row-major -- will it treat TT the same as row-major?

but you can generate only TT kernels using a regex like: `cmake ../cutlass/ -DCUTLASS_NVCC_ARCHS="70;75;80" -DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_*gemm_planar_complex*tt*` This result in compiling 104 kernel instances.

You further control what you want to generate precisely by editing generator.py

**Comment by d-k-b** [comment]
@manishucsd's advice for generating a smaller set of kernels will result in fastest compile times, but if you do want to compile many kernels to explore the options you might speed up compilation by setting `CUTLASS_UNITY_BUILD_ENABLED=ON` when running cmake. The unity build option reduces the set of object files generated and linked which can significantly speed up compiles in some cases.

**Comment by cliffburdick** [comment]
Thanks @manishucsd and @d-k-b! In regards to my row-major comment, there's a choice for which order to pass the data in for A/B, as well as the operation on it. So all combinations of Row/Column and N/T/C for both A and B. I was wondering if everything in the kernel name is relative to column-major, such that passing TT is really a row-major A and B.

**Comment by hwu36** [comment]
See this comment: https://github.com/NVIDIA/cutlass/issues/130#issuecomment-691096729

**Comment by cliffburdick** [comment]
> See this comment: [#130 (comment)](https://github.com/NVIDIA/cutlass/issues/130#issuecomment-691096729)

@hwu36 is that really true? I notice if I do row-major input on A/B it's always column-major output. You cannot choose the output of C, so I assumed it's always column-major.

**Comment by hwu36** [comment]
This is what that comment talks about.  To make sure the output is column major, cutlass profiler swaps and transpose the input operands internally.  You can open the auto generated .cu files in `tools/library/generated/gemm/` to see what is actually executed inside cutlass.

**Comment by cliffburdick** [comment]
@hwu36 if row-major is faster, and I give it two row-major inputs, what's the reason for it providing column-major outputs right now? 

For what it's worth, the filter `-DCUTLASS_NVCC_ARCHS="70;75;80" -DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_*gemm_planar_complex*tt* -DCUTLASS_UNITY_BUILD_ENABLED=ON` still takes more than 10 minutes to compile with 32 cores

**Comment by cliffburdick** [comment]
Adding one more comment, which I think is where some of the confusion is: The tensor core complex examples use the wrapper `gemm_planar_complex` instead of instantiating the templated functions directly. I believe that the recommended way to actually use CUTLASS in an application is to *not* use `gemm_planar_complex`, since that requires compiling/linking, and instead try to figure out what it does under the covers for each particular architecture. Is that correct?

**Comment by mnicely** [comment]
Can you try adding `-DCUTLASS_ENABLE_TESTS=OFF`?

**Comment by cliffburdick** [comment]
Thanks @mnicely, disabling unit tests seems to have decreased the compilation time significantly. I'll close this issue.

**Comment by hwu36** [comment]
Two more points,

1. Choosing direct make target can save compilation time.  (https://github.com/NVIDIA/cutlass/blob/master/media/docs/quickstart.md#build-and-run-cutlass-unit-tests)  Common targets is like `make cutlass_profiler`, `make cultass_test_unit_gemm_warp`, `make cutlass_lib`, `make 11_planar_complex_array`

2.  The row major epilogue is not really faster than a column major epilogue, but the row major one is easier to implement because the layout of the tensor core instruction is row major.  We implemented a column major epilogue in cutlass 1.x.
