### ISSUE TITLE
[QST]How to `Copy_Atom` with data type conversion?

### ISSUE THREAD

**Issue by jcao-ai** [NVIDIA/cutlass#1322]
**What is your question?**
For example, here the copy primitive is define from gmem to smem
```c++
using GmemTiledCopyQKV = decltype(
    make_tiled_copy(Copy_Atom<Gmem_copy_struct, Element>{},
                    GmemLayoutAtom{},
                    Layout<Shape<_1, _8>>{}));  // Val layout, 8 vals per read
```
Is it possible that the `src` is of type `FP8` and `dst` is of type `FP16`

**Comment by ccecka** [comment]
There is no such instruction, so there will be a round-trip through registers and no vectorization, but have you tried `UniversalCopy<cute::float_e4m3_t, cute::half_t>`?

For vectorization + conversion, you would write the copy-to-rmem -> transform -> copy-to-smem yourself:
```cpp
Tensor gA = ...    // FP8
Tensor sA = ...    // FP16

Tensor tAgA = ...  // Partitioned
Tensor tAsA = ...  // Partitioned

Tensor tArA_8  = make_fragment_like(tAgA);
Tensor tArA_16 = make_fragment_like(tAsA);

cute::copy_aligned(tAgA, tArA_8);
cute::transform(tArA_8, tArA_16, FP8->FP16);
cute::copy_aligned(tArA_16, tAsA);
```
