### ISSUE TITLE
random error with sm80_mma_multistage and sm70_epilogue_vectorized

### ISSUE THREAD

**Issue by mengchihe** [NVIDIA/cutlass#1326]
Hi:
I'm using cutlass3 on sm80 gpu with MainloopSm80CpAsync in sm80_mma_multiage.hpp to run gemm and Epilogue in sm70_epilogue_vectorized.hpp to store the output which will use shared memory.

The question is that I will get random result when I use the above two templates to run a gemm. I'm not sure whether the mainloop miss a sync at the end, because the result is right if I add cp_async_wait<0>() and __syncthreads() at the end of the mainloop. Maybe without this sync the additional async copy in mainloop will cover the data in shared memory write by epilogue?

Or maybe I use the epilogue with wrong template params because I didn't find and example of sm70_epilogue_vectorized.

Thanks

**Comment by thakkarV** [comment]
Yes, this is a legit bug that I found myself a few weeks ago as well. This will get fixed in 3.5 release, and the fix is to insert 
`cp_async_wait<0>(); __syncthread();` at the end of the mainloop.
