### ISSUE TITLE
[QST] different EVT-based epilogues for hopper and pre-hopper

### ISSUE THREAD

**Issue by mammoth831** [NVIDIA/cutlass#1327]
Hi, @hwu36  @thakkarV 
For pre-hopper, it is the visitor's responsibility to do every load, compute and store(e.g. the dst ptr is a member of the visitor and the visitor should write the final results to gmem, though the op is called VisitorAuxStore).
https://github.com/NVIDIA/cutlass/blob/6e3df975a2ca2a8c7bd3261f4a1d2042f8a26d26/include/cutlass/epilogue/threadblock/epilogue_with_visitor_callbacks.h#L141
https://github.com/NVIDIA/cutlass/blob/6e3df975a2ca2a8c7bd3261f4a1d2042f8a26d26/include/cutlass/epilogue/threadblock/epilogue_with_visitor.h#L78-L79

But it seems that these params are still part of the CollectiveEpilogue for hopper.  The epilogue itself will try to load C and store D, while the Sm90AuxLoad/Store is only used to load/store some extra inputs/outputs.

https://github.com/NVIDIA/cutlass/blob/6e3df975a2ca2a8c7bd3261f4a1d2042f8a26d26/include/cutlass/epilogue/collective/sm90_epilogue_tma_warpspecialized.hpp#L201-L207

Here are some questions:
1. The pre-hopper's impl looks better since it fully depends on EVT. Is hopper's impl for performance reasons?
2. It seems there is no EVT-based `CollectiveEpilogue` for pre-hopper. Which impl method is preferred if anyone wants to support it? 

thanks.

**Comment by hwu36** [comment]
@richardmcai @apuaaChen, could you please answer this?

**Comment by mammoth831** [comment]
Make sense. Thanks for your reply!
