### ISSUE TITLE
[QST] What is "fast accumulation" for fp8?

### ISSUE THREAD

**Issue by dchen496** [NVIDIA/cutlass#1329]
**What is your question?**

Hi, I see references in CUTLASS (and CuBLAS for that matter) to a "fast accumulation" mode for FP8. The CuBLAS documentation says this:

> When enabled, problem execution might be faster but at the cost of lower accuracy because intermediate results will not periodically be promoted to a higher precision. 

It seems that turning fast accumulation on enables some warp specialized schedules though, which don't seem to obviously correspond to the accumulation precision. Is there better documentation about this anywhere?

**Comment by hwu36** [comment]
cublas doc is the best one.
