### ISSUE TITLE
[QST] Sparse GEMM runs much worse than Dense GEMM in some cases

### ISSUE THREAD

**Issue by jimwu6** [NVIDIA/cutlass#1335]
I am benchmarking sparse and dense GEMMs through the cutlass profiler. I am seeing that sparse GEMMs run **slower** than dense GEMMs in the same scenario. For example, compare the best times through these two commands:
```
../tools/profiler/cutlass_profiler --operation=gemm --m=768 --n=4096 --k=4096 --A=bf16 --B=bf16 --C=bf16 --D=bf16 --batch_count=1 --profiling-iterations=5 --warmup-iterations=1 --output=report.csv

../tools/profiler/cutlass_profiler --operation=spgemm --m=768 --n=4096 --k=4096 --A=bf16 --B=bf16 --C=bf16 --D=bf16 --batch_count=1 --profiling-iterations=5 --warmup-iterations=1 --output=report.csv
```

Some setup details
- H100
- CUDA 12.3 (I get more or less the same results on CUDA 12.2)

The best dense time I get is 0.0457472 while the best sparse time I get is 0.0742464.

This is similar across sizes for MNK (e.g. increase M to be 4096), and specifically the batch_size=1 performs fairly poorly, and batch_size=2 the sparse is still a bit slower than the dense version.

Is there any way to improve the performance of the sparse kernels?

**Comment by thakkarV** [comment]
This is expected on H100 as we have optimized H100 kernels for dense Gemm but not sparse yet. The sparse kernels you're running are most certainly Ampere ones recompiled for hopper. We have hopper sparse on our roadmap for sometime middle of 2024

**Comment by jimwu6** [comment]
Thanks for the response, that makes sense. I've rerun the benchmarks on A100 and the results seem to be closer, however there are still some areas where the sparse kernels are about 30-50% slower than the dense ones.

E.g. take the settings above, take M=768, N=4096, K=4096. My best run time for dense is 0.105734 and my best run time for sparse is 0.150016. This is on A100. Is this still the expected result?

**Comment by thakkarV** [comment]
@hwu36

**Comment by hwu36** [comment]
Could you please paste the logs of the best kernel of sparse and dense on A100?

**Comment by jimwu6** [comment]
I have the result from the profiler in a csv in this [gist](https://gist.github.com/jimwu6/d2b766f12fed3831894c4d991b12f84f) for the best ones.

**Comment by hwu36** [comment]
your sparse one is running a small tile 64x128 which your dense one is running a big 256x128?  have you tried 256x128 or 128x256 or 128x128 for sparse?

**Comment by jimwu6** [comment]
The tile size is referring to cta_{m, n, k}, correct? If so, my first thought is that the cutlass_profiler should be running all possible configurations it has given the settings I selected, and since I didn't specify explicitly any of those it should running. I went back to try manually setting e.g. `--cta_m=128`, but that ended not running anything (which I believe means that the kernel/doesn't exist or can't be found?). This is the same for f16 and bf16.

I believe I should have installed all the possible kernels, since my install process was the following:
```
cmake .. -DCUTLASS_NVCC_ARCHS=80
make cutlass_profiler -j12
```

and I didn't select any specific kernels to exclude/include.

**Comment by hwu36** [comment]
you could add `-DCUTLASS_LIBRARY_KERNELS=bf16_s16832spgemm_bf16_*_tt_align8` to cmake to enable all sparse gemm tile sizes.

**Comment by jimwu6** [comment]
Using that flag produces no new kernels, which is verified by no additional results in the cutlass_profiler.

**Comment by hwu36** [comment]
what do you see when you run this command

`ls $BUILD/tools/library/generated/gemm/80/bf16_s16832spgemm_bf16/`

this is what I have

```
[haichengw@computelab-build-2 build_90a]$ ls tools/library/generated/gemm/80/bf16_s16832spgemm_bf16/
all_sm80_bf16_s16832spgemm_bf16_gemm_operations.cu		    cutlass_tensorop_bf16_s16832spgemm_bf16_128x64_64x3_tt_align8.cu   cutlass_tensorop_bf16_s16832spgemm_bf16_64x128_64x6_tt_align8.cu
cutlass_tensorop_bf16_s16832spgemm_bf16_128x128_128x3_tt_align8.cu  cutlass_tensorop_bf16_s16832spgemm_bf16_256x128_64x3_tt_align8.cu  cutlass_tensorop_bf16_s16832spgemm_bf16_64x256_64x4_tt_align8.cu
cutlass_tensorop_bf16_s16832spgemm_bf16_128x128_64x3_tt_align8.cu   cutlass_tensorop_bf16_s16832spgemm_bf16_256x64_128x3_tt_align8.cu  cutlass_tensorop_bf16_s16832spgemm_bf16_64x64_128x3_tt_align8.cu
cutlass_tensorop_bf16_s16832spgemm_bf16_128x256_64x3_tt_align8.cu   cutlass_tensorop_bf16_s16832spgemm_bf16_256x64_64x3_tt_align8.cu   cutlass_tensorop_bf16_s16832spgemm_bf16_64x64_64x4_tt_align8.cu
cutlass_tensorop_bf16_s16832spgemm_bf16_128x64_128x4_tt_align8.cu   cutlass_tensorop_bf16_s16832spgemm_bf16_64x128_128x3_tt_align8.cu
```

**Comment by jimwu6** [comment]
I have the same contents as you. However the profiler only seem to run the 64x128, even when I don't specify cta.
I am running exactly
```
../tools/profiler/cutlass_profiler --operation=spgemm --m=768 --n=4096 --k=4096 --A=bf16 --B=bf16 --C=bf16 --D=bf16 --batch_count=1 --profiling-iterations=5 --warmup-iterations=1 --output=report.csv
```

**Comment by hwu36** [comment]
what if you just do `../tools/profiler/cutlass_profiler --m=768 --n=4096 --k=4096`

**Comment by jimwu6** [comment]
The only sparse GEMMs that don't have `--cta_m=64 --cta_n=128` are those which are f32 or s4 or s8 in its inputs.

**Comment by hwu36** [comment]
you need to use tn (row x col) layout for f32, s4,  s8.

**Comment by mnicely** [comment]
@jimwu6 have your issues been resolved?
