### ISSUE TITLE
[QST] `sm70` `mma.sync` layout

### ISSUE THREAD

**Issue by jeromeku** [NVIDIA/cutlass#1338]
**What is your question?**
Looking at the `mma` instruction for `sm70`, specifically [here](https://github.com/NVIDIA/cutlass/blob/47a3ebbea9860e14c095b52c4e6e2db33340f572/include/cutlass/arch/mma_sm70.h#L515-L537) for `mma.sync.aligned.m8n8k4.f32.f16.f16.f32`, each thread accumulates 8 floats [`Fragment C/D`](https://github.com/NVIDIA/cutlass/blob/47a3ebbea9860e14c095b52c4e6e2db33340f572/include/cutlass/arch/mma_sm70.h#L494).  

However, the output shape of this tensor-core `mma` is `8x8 = 64` values.  How are threads mapped to the outputs if there are only 64 values in the output but each thread accumulates to 8 output registers (`32 * 8 = 256` in total)?  Which of these register values is "valid"?

**Comment by thakkarV** [comment]
64 accumulators across 8 threads is 8 accumulator per thread. Not sure what inconsistency you are pointing out? Volta MMA is 8 thread wide

**Comment by thakkarV** [comment]
closing for now. please reopen if you have more questions.
