### ISSUE TITLE
[QST] Is s8 * s8 = {s32, s8} supported in cuTe?

### ISSUE THREAD

**Issue by MingZwhy** [NVIDIA/cutlass#1342]
Is s8 * s8 = {s32, s8} supported in cuTe?

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
Without more info than what you've given, all I can say is "yes". The int8 atoms exist for all archs

**Comment by MingZwhy** [comment]
**Sorry about ambiguous questions.**
In the example in cutlass/examples/cute/tutorial/sgemm_nt_1.cu
`  using TA = float;
  using TB = float;
  using TC = float;
  using TI = float;`
When I try to set TA and TB to be int8_t and TC, TI to be int32_t,
I found there is no error during runtime but the output cute_result are all zero.
So I want to make sure if s8 * s8 = {s32, s8} is allowed in this example.
Thanks for your suggestions!

**Comment by MingZwhy** [comment]
> Without more info than what you've given, all I can say is "yes". The int8 atoms exist for all archs

Sorry about ambiguous questions.
In the example in cutlass/examples/cute/tutorial/sgemm_nt_1.cu
  using TA = float; using TB = float; using TC = float; using TI = float;
When I try to set TA and TB to be int8_t and TC, TI to be int32_t,
I found there is no error during runtime but the output cute_result are all zero.
So I want to make sure if s8 * s8 = {s32, s8} is allowed in this example.
Thanks for your suggestions!

**Comment by MingZwhy** [comment]
> Without more info than what you've given, all I can say is "yes". The int8 atoms exist for all archs

**Sorry about ambiguous questions.**
In the example in cutlass/examples/cute/tutorial/sgemm_nt_1.cu
  `using TA = float; using TB = float; using TC = float; using TI = float;`
When I try to set TA and TB to be int8_t and TC, TI to be int32_t,
I found there is no error during runtime but the output cute_result are all zero.
So I want to make sure if s8 * s8 = {s32, s8} is allowed in this example.
Thanks for your suggestions!

**Comment by mnicely** [comment]
@MingZwhy has your question been answered?

**Comment by MingZwhy** [comment]
> @MingZwhy has your question been answered?

sry I forgot to close the issue, I will do it now.
