### ISSUE TITLE
[QST]Composition does not work as expected.

### ISSUE THREAD

**Issue by jcao-ai** [NVIDIA/cutlass#1353]
**What is your question?**
It is a simple `composition` problem between two simple layouts.
```C++
      0   1   2
    +---+---+---+
 0  | 0 | 2 | 4 |
    +---+---+---+
 1  | 1 | 3 | 5 |
    +---+---+---+
auto m_2x3_col_major = make_layout(make_shape(2, 3));

      0   1   2
    +---+---+---+
 0  | 0 | 1 | 2 |
    +---+---+---+
 1  | 3 | 4 | 5 |
    +---+---+---+
auto m_2x3_row_major = make_layout(make_shape(2, 3), make_stride(3, 1));

      0   1
    +---+---+
 0  | 0 | 1 |
    +---+---+
 1  | 2 | 3 |
    +---+---+
auto composed = composition(m_2x3_col_major, m_2x3_row_major);
print_layout(composed);
```
I would expect the result layout `composed` to be:
```
      0   1   2
    +---+---+---+
 0  | 0 | 1 | 2 |
    +---+---+---+
 1  | 3 | 4 | 5 |
    +---+---+---+
```
but it is not. Further more, shouldn't the domain of `R` and `B` be compatible ?

Cutlass version: *v3.4.0*
Thanks.

**Comment by jcao-ai** [comment]
If I change 
```auto m_2x3_col_major = make_layout(make_shape(2, 3));```
to 
```auto m_2x3_col_major = make_layout(make_shape(6)); ```

It works as expected. So I guess it is some issue (`shape_div`? It occurs when static integer is used) related to shape of layout `A`. 
I don't know if it is a bug or just a constraint which is not declared.

**Comment by jcao-ai** [comment]
@ccecka I guess you are the one I should turn to hh. :)

**Comment by ccecka** [comment]
Your example fails the [divisibility condition](https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/02_layout_algebra.md#computing-composition). The divisibility condition has nothing to do with compatibility. As you noticed, the divisibility condition is checked statically but not dynamically -- dynamic checks would incur unacceptable cost, though I am considering disallowing all provably-unsafe (mostly dynamic) compositions which would include this one.
