### ISSUE TITLE
CuTe documentation -- 02_layout_algebra.md has a wrong example in Complement section

### ISSUE THREAD

**Issue by HydraQYH** [NVIDIA/cutlass#1359]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/02_layout_algebra.md#complement-examples
In markdown file line 344.

**Describe the problems or issues found in the documentation**
Result shape is wrong, original text is:
* `complement(4:2, 24)` is `(2,4):(1,8)`. Note that `(4,(2,4)):(2,(1,8))` has cosize `24`. The "hole" in `4:2` is filled with `2:1` first, then everything is repeated 4 times with `4:8`.

The result should be `(2,3):(1,8)`, the wrong result`(4,(2,4)):(2,(1,8))` has cosize `32` not `24`.

**Steps taken to verify documentation is incorrect**
I write a example code and print the result layout:
```Cpp
void layout_algebra_2(void) {
    using namespace cute;
    auto vec = make_layout(make_shape(Int<4>{}), make_stride(Int<2>{}));
    print(vec);
    std::cout << std::endl;
    auto res = complement(vec, Int<24>{});
    print_layout(res);
    std::cout << std::endl;
}
```
The result is:
(_4):(_2)
(_2,_3):(_1,_8)

**Suggested fix for documentation**
It should be:
* `complement(4:2, 24)` is `(2,3):(1,8)`. Note that `(4,(2,3)):(2,(1,8))` has cosize `24`. The "hole" in `4:2` is filled with `2:1` first, then everything is repeated 3 times with `3:8`.

Can I start a PR to fix this small issue?

**Comment by ccecka** [comment]
Thanks! I've already got this one fixed and it will be included in the next documentation update.

**Comment by HydraQYH** [comment]
> Thanks! I've already got this one fixed and it will be included in the next documentation update.

Okay, I will close this issue.

**Comment by HydraQYH** [comment]
Error fixed, it will be included in the next documentation update.
