### ISSUE TITLE
Suspicious Profiler Results

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/cutlass#136]
I ran the cutlass_profiler on the A100 with the following parameters:

`cutlass_profiler  --op_class=tensorop --m=3456 --n=4096 --k=8192`

After sorting the results, I noticed that there are some values that appear to be far higher than the theoretical peak of the card. The file below shows a peak throughput of 2.1PFLOPS in one case, and there are several more above 400TFLOPS as well.

[max.gemm.csv.zip](https://github.com/NVIDIA/cutlass/files/5301540/max.gemm.csv.zip)

I'm assuming it's not doing any sparse computations since this is CUTLASS 2.2.

**Comment by cliffburdick** [comment]
I believe these are b1 and u4 computations.

**Comment by hwu36** [comment]
b1 tensor op can reach peta flops on A100.  enjoy ;)

**Comment by cliffburdick** [comment]
@hwu36 that's what I get for thinking there's a bug, then realizing the card is just far faster than any other numbers I've seen before.
