### ISSUE TITLE
[QST] How to pass a cute::Tensor as parameter to a device function?

### ISSUE THREAD

**Issue by ZhangZhiPku** [NVIDIA/cutlass#1363]
I am writing a device function like:
```
__device__ void func(cute::Tensor tensor){...}
```

I want to call it like:
```
auto A = cute::make_tensor(...);
func(A);
```

However I got an error says: argument list for class template "cute::Tensor" is missing.
How can I pass a tensor as parameter to a function?

**Comment by ZhangZhiPku** [comment]
Besides, I rewrite this function to:
```
__device__ void func(float* tensor){...}
```

And call it like:
```
auto A = cute::make_tensor(...);
func(A.data());
```

There is another error says: no instance of function template "func" matches the argument list, argument types are cute::gmem_ptr<float *>.
How can I get the data pointer inside a tensor?

**Comment by thakkarV** [comment]
Tensor is a template type. The signature of your device function will be something like this:

```cpp
template <class Engine, class Layout>
auto
func(cute::Tensor<Engine, Layout> tensor) {
  // blah
}

```

**Comment by mnicely** [comment]
@ZhangZhiPku let us know if that works and we can close this issue

**Comment by ZhangZhiPku** [comment]
It works fine, thank you!
