### ISSUE TITLE
[QST] `SmemLayoutAtom` Layouts

### ISSUE THREAD

**Issue by jeromeku** [NVIDIA/cutlass#1364]
**What is your question?**
What is the logic behind choosing `SmemLayoutAtom` layouts?

Specifically, looking at the `cutlass::gemm` unit test [gemm configs](https://github.com/NVIDIA/cutlass/blob/a8f2c80db0564c74f4efccac71993b971dfc448b/test/unit/gemm/device/default_gemm_configuration.hpp#L78-L114) for `sm80`:
```cpp

template <typename Element, typename Layout, int Alignment, int SizeK>
struct DefaultGemm_TensorOpSm80_OperandA;

template <>
struct DefaultGemm_TensorOpSm80_OperandA<half_t, layout::RowMajor, 8, 64>
{
  // Smem
  using SmemLayoutAtom = decltype(
    composition(Swizzle<3,3,3>{},
                Layout<Shape < _8,_64>,
                       Stride<_64, _1>>{}));
  using SmemCopyAtom = Copy_Atom<SM75_U32x4_LDSM_N, half_t>;

  // Gmem
  using GmemTiledCopy = decltype(
    make_tiled_copy(Copy_Atom<SM80_CP_ASYNC_CACHEALWAYS<cute::uint128_t>, half_t>{},
                    Layout<Shape <_16,_8>,
                           Stride< _8,_1>>{},
                    Layout<Shape < _1,_8>>{}));
};

/// Operand A - Column-major (M-major)
template <int SizeK>
struct DefaultGemm_TensorOpSm80_OperandA<half_t, layout::ColumnMajor, 8, SizeK>
{
  // Smem
  using SmemLayoutAtom = decltype(
    composition(Swizzle<3,3,3>{},
                Layout<Shape <_64, _8>,
                       Stride< _1,_64>>{}));
  using SmemCopyAtom = Copy_Atom<SM75_U16x8_LDSM_T, half_t>;

  // Gmem
  using GmemTiledCopy = decltype(
    make_tiled_copy(Copy_Atom<SM80_CP_ASYNC_CACHEALWAYS<cute::uint128_t>, half_t>{},
                    Layout<Shape <_16, _8>,
                           Stride< _1,_16>>{},
                    Layout<Shape < _8, _1>>{}));
};

// Because the F32F16 TiledMMA is A-B symmetric, we can reuse the DefaultOperands

// Operand B - Column-Major (K-major)
template <int Alignment, int SizeK>
struct DefaultGemm_TensorOpSm80_OperandB<half_t, layout::ColumnMajor, Alignment, SizeK>
     : DefaultGemm_TensorOpSm80_OperandA<half_t, layout::RowMajor,    Alignment, SizeK>
{};

// Operand B - Row-Major (N-major)
template <int Alignment, int SizeK>
struct DefaultGemm_TensorOpSm80_OperandB<half_t, layout::RowMajor,    Alignment, SizeK>
     : DefaultGemm_TensorOpSm80_OperandA<half_t, layout::ColumnMajor, Alignment, SizeK>
{};
```

It seems that the `SmemLayoutAtom` layout takes the form of `Shape<Alignment, SizeK>, Stride<SizeK, _1>` and `Shape<SizeK, Alignment>, Stride<_1, SizeK>` where `SizeK` is the tile size `K` processed by a block.

When defining layouts for `Operand B`, the layouts are reversed -- i.e., `RowMajor` B < -- > `ColMajor` A and vice versa, which makes sense since the `CuTe` convention is that `B` is `N x K`.  

Hoping someone can shed light on the following:

-  If we look at the `ColMajor` version of the configurations defined above, we seek that the `SmemLayoutAtom` is `Shape<SizeK, Alignment>, Stride<_1, SizeK>`.  But for `Operand B`, the first `Shape` mode is `N`, not `K`.
 
- The logic and heuristics -- namely `SizeK` and `Alignment` -- for choosing `SmemLayoutAtom`, and how these then affect the downstream `SmemLayout` when these atoms are `tile_to_shape`d to the final smem layout?

- How is `SmemLayoutAtom` affected by / affect `GmemTiledCopy` shapes (e.g., using an `128` bit-wide `cp_async`) and shared to register copying using a `CopyOp` such as `ldmatrix`?

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
- I am not sure where you see `Shape<SizeK, Alignment>, Stride<_1, SizeK>` . No smem layout atom has size K as the first mode of the shape. All smem layouts here have a rank-2 shape MK for A, NK for B. Otherwise 
- These layout atoms are simply picking the right swizzle type for the layouts. Tile to shape simply repeats it to a larger shape when the collective is constructed with them.
- Design of the smem layouts is the most invovled part of Volta and Ampere kernels. It involves tradeoffs between
    + vectorization size of gmem store to smem
    + vectorization size of smem loads to rmem
    + bank conflicts during gmem store to smem
    + bank conflicts during smem loads to rmem
    + dynamic strides in the partitioning layout of smem

These layouts here may not necessarily be the best ones for all data types, but are intended to get you most of the way (90% + perf)

**Comment by jeromeku** [comment]
Given the template:
```cpp
template <typename Element, typename Layout, int Alignment, int SizeK>
struct DefaultGemm_TensorOpSm80_OperandA;
```
I was matching the `Alignment` and `SizeK` to the instantiated types, e.g.:
```cpp
template <>
struct DefaultGemm_TensorOpSm80_OperandA<half_t, layout::RowMajor, 8, 64>
{
  // Smem
  using SmemLayoutAtom = decltype(
    composition(Swizzle<3,3,3>{},
                Layout<Shape < _8,_64>,
                       Stride<_64, _1>>{}));
  using SmemCopyAtom = Copy_Atom<SM75_U32x4_LDSM_N, half_t>;
```
I.e., I was matching the `Alignment` to `8` and `SizeK` to `64`.  

How / why were these chosen, and why are this shape flipped when the `Operand` layout is `ColumnMajor`?
```cpp
 using SmemLayoutAtom = decltype(
    composition(Swizzle<3,3,3>{},
                Layout<Shape <_64, _8>,
                       Stride< _1,_64>>{}));
```
