### ISSUE TITLE
Profiler For Complex Planar

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/cutlass#137]
Hi, I wanted to see if I can use the cutlass profile for complex planar layouts, but it doesn't seem to want to run those. I used cmake as follows: `cmake -H./ -B./build  -DCUTLASS_NVCC_ARCHS="80"  -DCUTLASS_ENABLE_TESTS=OFF`, but when I run the whole set of benchmarks with varying parameters, the complex planar kernels don't seem to be included in the set. Is there a way to enable these?

**Comment by kerrmudgeon** [comment]
Unfortunately, this is not yet supported. The examples are the only existing test environment to measure performance of planar complex kernels at this time.

Would this be of value?

**Comment by cliffburdick** [comment]
Hi @kerrmudgeon in terms of value to the project it's probably low since it seems like most people don't care about complex support, but it's useful for what we're doing. We have a benchmark already based on Google Benchmark that can do the m/n/k dimension, but the cutlass_profiler has many more options that are useful, such as changing the accumulator type, or varying the warp size. I would say if you think it's useful for others it might be worth adding.

**Comment by manishucsd** [comment]
@cliffburdick thanks for bringing this is to our attention. We have made a note of it. Indeed CUTLASS profiler comes in handy when profiling kernels :). 

If you end up implementing it we would be happy to review and include it as a pull request. Closing this issue.
