### ISSUE TITLE
[QST] how can i do w4a8 (int4 * int8) using cutlass?

### ISSUE THREAD

**Issue by yyfcc17** [NVIDIA/cutlass#1370]
i see int4 * fp8 is supported on hopper gpus, 

but for gpus like a30 and a100, there is no fp8 support, so i need to use int4 * int8, two int4 is packed into a int8,

how can i accomplish this kind of mixed gemm using cutlass?

thanks!

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/pull/1190

@alexsamardzic

**Comment by alexsamardzic** [comment]
My PR is (will be) about `F16`/ `S4`, and will cover also `BF16`/`S4`, `F16`/ `U4` and `BF16`/ `U4` MM on Ampere; through an earlier work of @manishucsd, CUTLASS already supports these for `S8` and `U8` instead of `S4` and `U4`, respectively, on Ampere.  And that's about it regarding mixed data-types MM, thus what OP would need is not in the works yet, but may be an interesting follow-up.

**Comment by yyfcc17** [comment]
thanks for reply. 

since LLM w8a8 is almost solved by PTQ methods, and w4a4 is too aggressive for PTQ methods, w4a8 PTQ is a good option for further optimization.

in my own experiments, the LLM's performance degradation is minor under w4a8 (per-channel * per-token) PTQ settings. and there is also a paper about it: https://arxiv.org/abs/2311.09550, the performance seems promising.

trt-llm already supported w4a8 PTQ & inference on hopper, but only for fp8.

is it possible to extend your PR to support w4a8 (int4 * int8) on Ampere? @alexsamardzic

**Comment by alexsamardzic** [comment]
It would be better to open another PR.  Namely, the combination of data-types that my PR intends to handle is rather tricky regarding loading data from shared memory to registers, that I believe should not be the case for `S4`/`S8` MM.  Also, there isn't much to share between the two - all of data conversion, reshuffling `S4` data between threads, and finally the tests, should be different for `S4`/`S8`.

**Comment by alexsamardzic** [comment]
I'm now working on this feature - #1413 is created, so this issue could be closed.

**Comment by yyfcc17** [comment]
@alexsamardzic that's great, thank you!
