### ISSUE TITLE
[BUG] Build failed with nvcc "-G" on H100

### ISSUE THREAD

**Issue by fei-xx** [NVIDIA/cutlass#1373]
**Describe the bug**
The build of `examples/54_hopper_fp8_warp_specialized_gemm/54_hopper_fp8_warp_specialized_gemm.cu` fail when adding `-G` to nvcc; but without `-G`, the build works well.

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

```
nvcc -t=0 \
-lineinfo -g -G \
-DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_DEBUG_TRACE_LEVEL=1 \
-w -gencode=arch=compute_90a,code=[sm_90a,compute_90a] \
-O1 -std=c++17 --expt-relaxed-constexpr \
-Xcompiler=-fPIC -Xcompiler=-fno-strict-aliasing -Xcompiler -fvisibility=hidden \
-Xcompiler=-Wconversion \
-I/home/fff/git/cutlass/include \
-I/home/fff/git/cutlass/tools/library/include \
-I/home/fff/git/cutlass/tools/library/src \
-I/home/fff/git/cutlass/tools/util/include \
-I/home/fff/git/cutlass/examples/common/ \
-I/usr/local/cuda-12.1/targets/x86_64-linux/include/ \
-L/usr/local/cuda-12.1/lib64 -L/usr/local/cuda-12.1/lib64/stubs -lcuda -lcudart \
-o test_54.out /home/fff/git/cutlass/examples/54_hopper_fp8_warp_specialized_gemm/54_hopper_fp8_warp_specialized_gemm.cu
```

**Expected behavior**
```
nvcc warning : '--device-debug (-G)' overrides '--generate-line-info (-lineinfo)'
ptxas /tmp/tmpxft_0006f883_00000000-6_54_hopper_fp8_warp_specialized_gemm.ptx, line 24246; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_0006f883_00000000-6_54_hopper_fp8_warp_specialized_gemm.ptx, line 24246; error   : Unknown symbol '__unnamed_1_param_0'
ptxas fatal   : Ptx assembly aborted due to errors
```

**Environment details (please complete the following information):**
 Azure H100 VM

**Additional context**

- gcc
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- nvcc
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```
- nvidia-smi
```
NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2  
```

**Comment by hwu36** [comment]
Would you please double check if you are using nvcc 12.3?  This issue is supposed to be fixed in 12.3 as confirmed by two github users already.

**Comment by fei-xx** [comment]
@hwu36 Confirmed it uses nvcc 12.3. I'm the user [at this issue](https://github.com/NVIDIA/cutlass/issues/1044#issuecomment-1974291945). I could compile the code there with `-G`, but not the above example code.

**Comment by hwu36** [comment]
thank you.  i can reproduce and it is reported to nvcc team now.

**Comment by fei-xx** [comment]
> thank you. i can reproduce and it is reported to nvcc team now.

@hwu36 kindly follow up with any updates?

**Comment by hwu36** [comment]
We have a compiler engineer actively working on it.
