### ISSUE TITLE
[cute gemm]

### ISSUE THREAD

**Issue by yangjianfengo1** [NVIDIA/cutlass#1374]
I found that the performance of GEMM(https://github.com/NVIDIA/cutlass/blob/main/examples/cute/tutorial/sgemm_nt_1.cu)  is not good enough. May I ask if there are any other examples of GEMM built using CUTE with better performance? Thank you very much.

**Comment by thakkarV** [comment]
They're coming in the next two weeks along with the 3.5 release :)

**Comment by yangjianfengo1** [comment]
very thanks.
