### ISSUE TITLE
[QST] Constraint of Tensor Layout in FP8 GEMM Kernel

### ISSUE THREAD

**Issue by AndySong20** [NVIDIA/cutlass#1376]
Currently, the “NT” format does not seem to be supported by fp8 gemm kernel. I'd like to know the root cause and whether the performance of  splited tranpose and gemm kernels is better than fused kernel when using the "NT" format.

**Comment by hwu36** [comment]
> whether the performance of splited tranpose and gemm kernels is better than fused kernel when using the "NT" format.

yes.

**Comment by AndySong20** [comment]
Thanks, get it

**Comment by mnicely** [comment]
@AndySong20 Is your question answered?

**Comment by AndySong20** [comment]
yes
