### ISSUE TITLE
[QST] Build hangs on AWS p3.2xlarge Ubuntu

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1378]
```bash
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
$ /usr/local/cuda/bin/nvcc --version
...
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
$ uname -a
Linux ip-... 5.15.0-1052-aws #57~20.04.1-Ubuntu SMP Mon Jan 15 17:04:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ lscpu
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             8
On-line CPU(s) list:                0-7
Thread(s) per core:                 2
Core(s) per socket:                 4
...
$ git clone ... && cd ...
$ mkdir build && cd build
$ cmake .. -DCUTLASS_NVCC_ARCHS=70 -DCUTLASS_ENABLE_TESTS=OFF -DCUTLASS_UNITY_BUILD_ENABLED=ON
$ make cutlass_profiler -j9
```

The last message displayed is 
`[ 86%] Built target cutlass_library_conv2d_sm70_s884dgrad_optimized_f16`

This machine isn't super-powerful, but anecdotally I did try ramping it up to a larger machine and it hung at the same location. 

`top` indicates the CPU is all being used up by the process.

**Comment by hwu36** [comment]
what is your gcc and nvcc version?  what if you just use `make cutlass_profiler -j1`.  do you see forward progress?

**Comment by ericauld** [comment]
Will try

**Comment by ericauld** [comment]
@hwu36  `make cutlass_profiler -j1` seems to hang at about 6%, after printing the message
`[  6%] Building CUDA object tools/library/CMakeFiles/cutlass_library_objs.dir/cutlass_library_objs.unity.a2ea0bb712b9.cu.o`

**Comment by hwu36** [comment]
What about not using unity build?

**Comment by ericauld** [comment]
Trying

**Comment by ericauld** [comment]
@hwu36 That worked! Thank you

**Comment by mnicely** [comment]
@ericauld can we close this issue?
