### ISSUE TITLE
[QST] Understanding `retile_*`

### ISSUE THREAD

**Issue by HanGuo97** [NVIDIA/cutlass#1387]
First of all, thanks for this amazing library!

This might seem like a naive/newbie question, but I'm having trouble understanding what `retile_*` (e.g., `retile_S`) does. A specific example I'm looking at is the vectorized epilogue [example](https://github.com/NVIDIA/cutlass/blob/v3.4.1/include/cutlass/epilogue/collective/sm70_epilogue_vectorized.hpp#L208-L212).

It'd be helpful if someone could explain (1) what `retile` does in general, and (2) how I should interpret/understand the role of `retile_S` and `partition_D` in the epilogue example.

Thanks in advance for the help!!

**Comment by thakkarV** [comment]
https://github.com/NVIDIA/cutlass/issues/1356

**Comment by HanGuo97** [comment]
Thanks for the quick response. So `retile` essentially provides an alternative view of the same underlying data so that it's compatible with another (tiled) copy operation?

**Comment by thakkarV** [comment]
it composes it with another partitioner's V layout so that a partitioned tensor's layout gets "reindexed" for this new partitioning pattern.

**Comment by HanGuo97** [comment]
Got it, thanks again for the quick + useful response!
