### ISSUE TITLE
Convolution implementation using CUTLASS template library

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/cutlass#139]
# Motivation
The current CUTLASS does not provide a 2D direct convolution implementation. However the convolution operator is important in image processing. A direct convolution using CUTLASS will be useful in many aspects, for example
* Research in modified convolutions, such as (Unshared convolution/ Locally connected layers). These operators lacks efficient implementation but they are the key operations in some applications of computer vision. This is also mentioned in this [issue](https://github.com/NVIDIA/cutlass/issues/20).
* Custom activations for convolution. The most efficient way of performing a fused operation for convolution and activation is via `cudnnConvolutionBiasActivationForward`. However this routine currently supports only two activation. If we have an efficient GEMM-based convolution implementation, it will be nice for users to expand it to support more activations. 
* Better GEMM understanding and better utilizing full hardware potential. 
# Our implementation
We (megvii team) implemented GEMM-based convolution using CUTLASS. Currently the implementation includes
* Integer Convolution using SIMT operator for sm_61/70/75
* Integer Convolution using TensorOp operator for sm_75

The code [(MegEngine/cutlass)](https://github.com/MegEngine/cutlass) is implemented with around 5K lines of code. We plan to upstream the code with several pull requests.  We wonder the CUTLASS's developers' opinion about this plan. @kerrmudgeon @hwu36 
# Upstream process
We will format and reorganize our code for ease of review. We will split the code into several pull requests, and upstream the implementations gradually. It would be nice if the CUTLASS's developers could provide a clang-format configuration for us.

**Comment by kerrmudgeon** [comment]
Thank you for your interest in CUTLASS! We're excited you've found it useful in creating a convolution implementation. We wanted to reach out and let you know that we are preparing to release our own support for convolution in CUTLASS. We hope that it will be useful for your work as well.

Our plan is to provide implementations of 2D and 3D convolution, including forward and backwards passes in NHWC layout. This will implement most supported data types including single-precision, half-precision, bfloat16, TensorFloat32, int8, and int4.

This version will be released as CUTLASS 2.4 soon.

**Comment by YangWang92** [comment]
Hi Andrew @kerrmudgeon, will this version support implicit im2col based convolution? Thanks a lot!

**Comment by sunlex0717** [comment]
Hi Andrew @kerrmudgeon. When do you expect we can see the release of CUTLASS 2.4? : ). I am very excited to use your convolution implementations !

**Comment by kerrmudgeon** [comment]
CUTLASS 2.4 implementing Implicit GEMM Convolution is coming very soon. Please watch this space for updates.

**Comment by kerrmudgeon** [comment]
We have just released CUTLASS 2.4. Please have a look and let us know what you think!
