### ISSUE TITLE
[QST]

### ISSUE THREAD

**Issue by yangjianfengo1** [NVIDIA/cutlass#1394]
**What is your question?**
Hello, I now need to implement an int8 matrix multiplied by A * B=C, where A has a shape of m * k and B has a shape of k * n. When I copy B's data from shared memory to a register, B needs to be transposed. Do you have an ldmatrix for int8, similar to SM75_U8x16-LDSM-T？

**Comment by hwu36** [comment]
int8 tensor core only supports row x col.  ldmatrix cannot transpose 8bit data.  so you have to run row x col gemm.

**Comment by yangjianfengo1** [comment]
very thanks
