### ISSUE TITLE
[QST] Unsigned INT8 GEMM 

### ISSUE THREAD

**Issue by jomivaan** [NVIDIA/cutlass#1395]
I am developing a gemm for int8*int8 using tensor cores and while in the process of doing so I got a lot of "incomplete type is not allowed". I solved the problem by following what the comments in [this post](https://github.com/NVIDIA/cutlass/issues/1106) say. However, since I will try to optimize the GPU usage etc, I cannot simply do what the comments say blindly without fully understanding. Basically, I would like to understand the "what" and "why" of this comment: "every data type has its own sets of usable threadblock/warp/instruction shapes". Thank you.

**Comment by thakkarV** [comment]
kernels are optimized for their flop/byte (arithmetic intensity) and balanced against the latency of loading data. int8 needs a larger K extent in the tile shape so the same number of bits are loaded from gmem when compared to a smaller tile shape used for an fp16 data type

**Comment by jomivaan** [comment]
Oh I see. Just to confirm if I understood correctly. To always load the same amount of data from the global memory, we need to balance K taking into account the bit size of the data we are working with. Is that correct? Thank you for the response.

**Comment by thakkarV** [comment]
yes, that's right. the tile shapes are in units of logical elements, so we need to change that if we want to change the data types while keeping the size of each loaded stage the same across kernels.

**Comment by jomivaan** [comment]
Thank you for the help. I will close the thread.
