### ISSUE TITLE
[QST] Tile is not evenly divisible

### ISSUE THREAD

**Issue by HuaYZhao** [NVIDIA/cutlass#1397]
**What is your question?**
I'm doing matrix multiplication manually with cute
```
  Tensor A = make_tensor(make_gmem_ptr(Aptr), make_shape(m, k), make_stride(k, Int<1>{}));
  Tensor B = make_tensor(make_gmem_ptr(Bptr), make_shape(n, k), make_stride(k, Int<1>{}));
  Tensor C = make_tensor(make_gmem_ptr(Cptr), make_shape(m, n), make_stride(n, Int<1>{}));

  Tensor gA = local_tile(A, make_tile(Int<kTileM>{}, Int<kTileK>{}), make_coord(iy, _));
  Tensor gB = local_tile(B, make_tile(Int<kTileN>{}, Int<kTileK>{}), make_coord(ix, _));
  Tensor gC = local_tile(C, make_tile(Int<kTileM>{}, Int<kTileN>{}), make_coord(iy, ix));
```
When m=10, kTileM=16, I observe that gA will repeat A to fill up to the size of kTileM, and then the memory addresses of the rest of the thread will start to get confused.

I observed this using print tensor
![image](https://github.com/NVIDIA/cutlass/assets/37064550/86c98a28-a445-44f8-ae14-9cd0a75c5cb4)

I want to know how to handle this non-divisible situation. Are there any examples in cute that you can refer to

**Comment by thakkarV** [comment]
There is a dedicated document on how to handle predication in the cute markdown docs.

**Comment by thakkarV** [comment]
https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/0y_predication.md

**Comment by HuaYZhao** [comment]
Ok, thanks, I forgot to read this one, I'll give it a try, but I feel the documentation should be accompanied by some code examples

**Comment by thakkarV** [comment]
It is. Our Sm80 mainloop implements predication: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L504

**Comment by HuaYZhao** [comment]
I see, thank you very much for your timely reply, I am experimenting

**Comment by HuaYZhao** [comment]
I have a new problem, and I think I fulfilled the predicate normally
```
  // Allocate predicate tensors for m and n
  auto tApA = make_tensor<bool>(make_shape(size<1>(tAsA_copy), size<2>(tAsA_copy)), Stride<_1, _0>{});
  auto tBpB = make_tensor<bool>(make_shape(size<1>(tBsB_copy), size<2>(tBsB_copy)), Stride<_1, _0>{});

  // Construct identity layout for sA and sB
  auto cA = make_identity_tensor(make_shape(size<0>(sA), size<1>(sA))); // (BLK_M,BLK_K) -> (blk_m,blk_k)
  auto cB = make_identity_tensor(make_shape(size<0>(sB), size<1>(sB))); // (BLK_N,BLK_K) -> (blk_n,blk_k)

  // Repeat the partitioning with identity layouts
  auto tAcA = g2s_thr_copy_a.partition_S(cA); // (CPY, CPY_M, CPY_K, kStage) -> (blk_m,blk_k)
  auto tBcB = g2s_thr_copy_b.partition_S(cB); // (CPY, CPY_M, CPY_K, kStage) -> (blk_n,blk_k)

  // Set predicates for m bounds
  CUTLASS_PRAGMA_UNROLL
  for (int m = 0; m < size<0>(tApA); ++m)
  {
    tApA(m, 0) = get<0>(tAcA(0, m, 0)) < M; // blk_m coord < residue_m
  }
  // Set predicates for n bounds
  CUTLASS_PRAGMA_UNROLL
  for (int n = 0; n < size<0>(tBpB); ++n)
  {
    tBpB(n, 0) = get<0>(tBcB(0, n, 0)) < N; // blk_n coord < residue_n
  }
```
I printed it and observed it seemed fine；
![image](https://github.com/NVIDIA/cutlass/assets/37064550/11945c4b-c361-4c91-b1ef-a71661500cbb)


My new problem is that when I type M<16, i.e. cannot divide TileM exactly, I print my global A and I find that it changes every time, as shown in the picture the first time


> **What is your question?** I'm doing matrix multiplication manually with cute
> 
> ```
>   Tensor A = make_tensor(make_gmem_ptr(Aptr), make_shape(m, k), make_stride(k, Int<1>{}));
>   Tensor B = make_tensor(make_gmem_ptr(Bptr), make_shape(n, k), make_stride(k, Int<1>{}));
>   Tensor C = make_tensor(make_gmem_ptr(Cptr), make_shape(m, n), make_stride(n, Int<1>{}));
> 
>   Tensor gA = local_tile(A, make_tile(Int<kTileM>{}, Int<kTileK>{}), make_coord(iy, _));
>   Tensor gB = local_tile(B, make_tile(Int<kTileN>{}, Int<kTileK>{}), make_coord(ix, _));
>   Tensor gC = local_tile(C, make_tile(Int<kTileM>{}, Int<kTileN>{}), make_coord(iy, ix));
> ```
> 
> When m=10, kTileM=16, I observe that gA will repeat A to fill up to the size of kTileM, and then the memory addresses of the rest of the thread will start to get confused.
> 
> I observed this using print tensor ![image](https://private-user-images.githubusercontent.com/37064550/312367075-86c98a28-a445-44f8-ae14-9cd0a75c5cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODY2NDEsIm5iZiI6MTcxMDM4NjM0MSwicGF0aCI6Ii8zNzA2NDU1MC8zMTIzNjcwNzUtODZjOThhMjgtYTQ0NS00NGY4LWFlMTQtOWNkMGE3NWM1Y2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAzMTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MzJhMGViODE1ZTA1OTBhYjAxOTgwNDFiYzdkY2Q0MTdlOTc3NGQ4Y2NiNWNkZjZlODM4MzIzNTg4NTA5MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAzDgHXqH6DkeE9f3VmP86LE5TX6hgziIaEqa6rK5Eo)
> 
> I want to know how to handle this non-divisible situation. Are there any examples in cute that you can refer to


I conducted further experiments and found that if I commented out the last copy back to gC, the gA would not change;
```
cute::copy(tCrC, tCgC);
```
If my M is exactly 16 and TileM is 16, then gA is not going to change
The problem only occurs when M is not divisible and there is a copy-back gC operation

**Comment by HuaYZhao** [comment]
> It is. Our Sm80 mainloop implements predication: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L504

Where is there a unit test or something that allows me to run this code？

**Comment by irasin** [comment]
Hi, all!
I was wondering how the predication handles the address misaligned problem when K is not divisible by TileK.

**Comment by irasin** [comment]
Hi, @thakkarV, thanks for your reply.
It seems the shift mechanism is basicly the same between sm80 and sm90 mma multistage code. So I think my question is still  unsolved,
https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/collective/sm80_mma_multistage.hpp#L549 can only handle the case where k is the multiple of 8 due to the requirement of cp.async src alignment.

**Comment by thakkarV** [comment]
If the input shape is not aligned to the instruction alignment, that shape is not computable by the kernel. you have to reduce the vectorization size if you want to compute on lower alignment

**Comment by irasin** [comment]
Got it, thanks a lot~
