### ISSUE TITLE
[QST] Does GEMM support vectors of alpha and beta?

### ISSUE THREAD

**Issue by ken012git** [NVIDIA/cutlass#1398]
**What is your question?**
I checked the related issues https://github.com/NVIDIA/cutlass/issues/1155 and https://github.com/NVIDIA/cutlass/issues/1000, but I am still not sure if GEMM supports vectors of alpha and beta.

If I have input matrices with shapes: x (1, M, K), w: (K, N), b: (N), alpha: (M), beta: (N). alpha and beta are shared across the batch (bsize=1 now) for simplicity, and I want to perform `alpha*matmul(x, w) + beta*b`. Which API or example has the closest function I want? Thanks!

**Comment by ken012git** [comment]
Hello, I think it is supported, still but not sure how to use it. 
https://github.com/NVIDIA/cutlass/blob/ffa34e70756b0bc744e1dfcc115b5a991a68f132/include/cutlass/epilogue/thread/scale_type.h#L51-L60

https://github.com/NVIDIA/cutlass/blob/ffa34e70756b0bc744e1dfcc115b5a991a68f132/include/cutlass/epilogue/thread/linear_combination_relu.h#L274-L279

A similar issue I found here https://github.com/NVIDIA/cutlass/issues/568

**Comment by hwu36** [comment]
@apuaaChen , could you comment on how to support it via evt?

**Comment by apuaaChen** [comment]
Hi! 

The pattern can be constructed through EVT. You can try to follow the [example 47 streamk_broadcast](https://github.com/NVIDIA/cutlass/blob/main/examples/47_ampere_gemm_universal_streamk/ampere_gemm_universal_streamk_broadcast.cu#L177-L239) to construct the epilogue. Your pattern should be something like
```c++
using OutputTileThreadMap = cutlass::epilogue::threadblock::OutputTileThreadLayout<
  ThreadblockShape, 
  WarpShape, 
  ElementC, 
  AlignmentC, 
  EVTEpilogueStages
>;
// Accumulator
using Accum = cutlass::epilogue::threadblock::VisitorAccFetch;
// alpha
using Alpha = cutlass::epilogue::threadblock::VisitorColBroadcast<
    OutputTileThreadMap, ElementC,
    cute::Stride<_1,_0,int32_t>
>;

// mul
using Mul0 = cutlass::epilogue::threadblock::VisitorCompute<
    cutlass::multiplies, ElementCompute, ElementCompute,
    cutlass::FloatRoundStyle::round_to_nearest
>:

// alpha * accumulator
using EVTMul0 = cutlass::epilogue::threadblock::Sm80EVT<
    Mul0, Alpha, Accum>;

// beta
using Beta = cutlass::epilogue::threadblock::VisitorRowBroadcast<
    OutputTileThreadMap, ElementC,
    cute::Stride<_0, _1, int32_t>  // StrideMNL
>;

// b
using B = cutlass::epilogue::threadblock::VisitorRowBroadcast<
    OutputTileThreadMap, ElementC,
    cute::Stride<_0, _1, int32_t>  // StrideMNL
>;

// mul
using Mul1 = cutlass::epilogue::threadblock::VisitorCompute<
    cutlass::multiplies, ElementCompute, ElementCompute,
    cutlass::FloatRoundStyle::round_to_nearest
>:

// beta * b
using EVTMul1 = cutlass::epilogue::threadblock::Sm80EVT<
    Mul1, Beta, B>;
    
// add
using Add = cutlass::epilogue::threadblock::VisitorCompute<
    cutlass::plus, ElementOutput, ElementCompute,
    cutlass::FloatRoundStyle::round_to_nearest
>;

// alpha * accumulator + beta * b
using EVTAdd = cutlass::epilogue::threadblock::Sm80EVT<
    Add, EVTMul0, EVTMul1>;
    
using D = cutlass::epilogue::threadblock::VisitorAuxStore<
    OutputTileThreadMap, ElementOutput, cutlass::FloatRoundStyle::round_to_nearest,
    cute::Stride<int64_t, _1, int64_t> // StrideMNL
>;

using EVTD = cutlass::epilogue::threadblock::Sm80EVT<
    D,
    EVTAdd>;
```

**Comment by ken012git** [comment]
Thanks!
