### ISSUE TITLE
[QST] `uint4/int4` Mixed Type Tensorcore MMA using `Cutlass 3.x / CuTe`

### ISSUE THREAD

**Issue by jeromeku** [NVIDIA/cutlass#1399]
Attempting to implement something similar to this Hopper [example](https://github.com/NVIDIA/cutlass/tree/main/examples/55_hopper_mixed_dtype_gemm) using Cutlass 3.x / CuTe for `Ampere`.

Partitioning shared memory with a tensorcore MMA atom such as `MMA_Atom<SM80_16x8x16_F32F16F16F32_TN>`, I get the correct thread / value mapping as long as `CuTe` `array_subyte / iterator` is used as the underlying pointer type.  However, when copying from `smem -> registers`, tensorcore copy atoms such as ` SM75_U32x4_LDSM_N` can no longer be used given the access size.

If I use a `DefaultCopy` atom to copy from `smem` to `registers` instead, the proper thread layout is maintained, however, memory access is inefficient since the copying is no-longer `128b` per thread.  

- Is there a workaround for this in the Hopper example that I'm missing?
- I've read PR https://github.com/NVIDIA/cutlass/pull/1190 and understand the need for shuffling to achieve the conformant tensor-core layout using `Cutlass 2.x`; wondering if there is an easier way to achieve this using `Cutlass 3.x / CuTe` primitives?

Thanks!

**Comment by thakkarV** [comment]
for 4b types, you would need the same kind of shuffling as is implemented in #1190 and we don't have any convenient abstractions in CuTe to implement collectives shuffles. however, you can still use the same MMA and copy atoms to partition your input and output tensors you call shuffles on to make the coord->index mapping easy for you.

**Comment by jeromeku** [comment]
In the Hopper [example](https://github.com/NVIDIA/cutlass/tree/main/examples/55_hopper_mixed_dtype_gemm), are copies from `smem -> registers` for `4b` types using a `DefaultCopy` and hence facing the same inefficient memory access pattern per above?  (I don't have access to `H100` to test on).

**Comment by hwu36** [comment]
@rhenry-nv

**Comment by rhenry-nv** [comment]
Yes, Hopper uses an inefficient load pattern. For F16 x INT4, it will use `ld.shared.u8`. We tried to use `ldmatrix` (with no shuffle to check perf upside) and didn't observe a noticeable performance difference for our problem shapes of interest. As a result, we kept the inefficient pattern.
