### ISSUE TITLE
Could CUTLASS provide a code format configuration, (for example a .clang-format script) ?

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/cutlass#140]
As mentioned in this [issue](https://github.com/NVIDIA/cutlass/issues/139), it would be nice if CUTLASS provided a code format configuration, so that we could reorganize our code for ease of review.

**Comment by Peter9606** [comment]
Seemed the format applied on conventional is different, personally I prefer this over the one applied for other part. Could you please share this version format ?

**Comment by mnicely** [comment]
We don't have a clang-format scripts. We carefully format everything during our manual integration.
