### ISSUE TITLE
[QST] How in profiler settings splitk slices can be greater then 1 if splitk mode is serial?

### ISSUE THREAD

**Issue by ankutalev** [NVIDIA/cutlass#1407]
Hello!
I'm trying to detect best launch configuration for my problem size 

```
./cutlass_profiler  --operation=Gemm  --A:s8=row --B:s8:column --D=s32:column --m=1536 --k=3840 --n=1 --gemm_kind=universal --split_k_mode=parallel,serial --split_k_slices=1,2,3,4,5,6 --output=tmp.txt
```

And the best configuration I get is following:
```
16,CUTLASS,gemm,cutlass_tensorop_i16832gemm_s8_32x128_128x4_tn_align16,passed,success,universal,1536,1,3840,s8:row,s8:column,s32:column,s32:column,1,0,serial,2,1,heuristic,tensorop,s32,32,128,128,1,1,1,4,1,4,1,16,8,32,80,1024,5908224,11799552,1,0.0148787,369.821,793.049
```

which is confusing to me - in my understanding `kSlices` only meaningfull when `splitK=parallel`, not serial.

If I'm correct , then what exactly this configuration measures?

If I'm wrong, how can I reproduce this results in terms of `DefaultGemmUniversal::Arguments` ? Is it `kGemm` with batchsize == 2 or something different?

Thanks!

**Comment by thakkarV** [comment]
- They're both using parallel computation. The serial or parallel setting is only referring to the reductions being either serial or parallel.

**Comment by ankutalev** [comment]
> * They're both using parallel computation. The serial or parallel setting is only referring to the reductions being either serial or parallel.

Okay, I got this part, thanks!

But this question 

> how can I reproduce this results in terms of DefaultGemmUniversal::Arguments ? Is it kGemm with batchsize == 2 or something different?

still here.

**Comment by ankutalev** [comment]
Nevermind, figured by myself, thanks.
