### ISSUE TITLE
[DOC] dead link for pycutlass examples

### ISSUE THREAD

**Issue by nyck33** [NVIDIA/cutlass#1408]
## Report incorrect documentation

https://github.com/NVIDIA/cutlass/blob/v3.0.0/tools/library/scripts/pycutlass/examples/40_cutlass_py is a dead link.

**Location of incorrect documentation**
[Provide links and line numbers if applicable.
](https://github.com/NVIDIA/cutlass/blob/v3.0.0/tools/library/scripts/pycutlass/examples/40_cutlass_py)

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

There are no examples.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

I cloned the cutlass repo and was reading the Python folder readme for Cutlass Python interface and it had link to Pycutlass in version 3.0.0 and then tried that link to see examples.

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

Can you provide examples if and only if Pycutlass allows me to make more optimizations than the Python Interface?  Ie. more granular control over parameters, etc.  I'm new to Cutlass so just scratching the surface but want to do somethign like they did in this paper: https://www.researchgate.net/publication/376780991_Tailoring_CUTLASS_GEMM_using_Supervised_Learning 
where they found optimal configuration parameters for using Cutlass for GEMM operations.  If the Python interface provides the same level of granular control I don't need to see Pycutlass examples.    

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

Please see above.  I want to see examples because I find them very helpful in learning new tools, libraries and frameworks.

**Describe the documentation you'd like**

Please answer my questions above and provide examples if necessary.

**Steps taken to search for needed documentation**
List any steps you have taken:

I'm going to start with the Python interface and then look at Pycutlass ocne I am bit mroe comfortable.

**Comment by jackkosaian** [comment]
Hi,

Is the hyperlink you are referring to that with text `$CUTLASS_PATH/examples/40_cutlass_py` [here](https://github.com/NVIDIA/cutlass/blob/v3.0.0/tools/library/scripts/pycutlass/README.md)?

Good catch on that link being broken.

However, since PyCUTLASS has been deprecated that path no longer exists in the main branch of CUTLASS.

I encourage you to check out the CUTLASS Python interface in the main branch here: https://github.com/NVIDIA/cutlass/tree/main/python
