### ISSUE TITLE
[BUG] GEMM silently miscalculates on some specific shapes

### ISSUE THREAD

**Issue by ZiyueHuang** [NVIDIA/cutlass#1412]
**Describe the bug**
The result of GEMM on shape `8 x 8192 x 8192` (m, n, k) is correct, but is silently wrong on shape `8 x 12288 x 8192` (m, n, k).

**Steps/Code to reproduce bug**
```python
import numpy as np
import random

import cutlass
import torch


m = 8
n = 12288
k = 8192

dtype = np.float16
type_A = np.float16
type_B = np.float16
type_C = np.float16
type_D = np.float16

np.random.seed(1234)
random.seed(1234)

scope_min = -3
scope_max = 3
tensor_A = np.ceil(np.random.uniform(low=scope_min, high=scope_max, size=(m, k)).astype(type_A))
tensor_B = np.ceil(np.random.uniform(low=scope_min, high=scope_max, size=(n, k)).astype(type_B))
tensor_C = np.ceil(np.random.uniform(low=scope_min, high=scope_max, size=(m, n)).astype(type_C))
tensor_D = np.zeros(tensor_C.shape).astype(type_D)

alpha = np.float16(1.)
beta = np.float16(0.)

tensor_A = torch.tensor(tensor_A, dtype=torch.float16, device=torch.device('cuda:0'))
tensor_B = torch.tensor(tensor_B, dtype=torch.float16, device=torch.device('cuda:0'))
tensor_C = torch.tensor(tensor_C, dtype=torch.float16, device=torch.device('cuda:0'))
tensor_D = torch.tensor(tensor_D, dtype=torch.float16, device=torch.device('cuda:0'))

plan = cutlass.Gemm(element=dtype, layout=cutlass.LayoutType.RowMajor, layout_B=cutlass.LayoutType.ColumnMajor, element_accumulator=np.float32)
plan.run(tensor_A, tensor_B, tensor_D, tensor_D, print_module=True)

out = torch.nn.functional.linear(tensor_A, tensor_B)
np.testing.assert_allclose(tensor_D.cpu().numpy(), out.cpu().numpy(), rtol=1e-03, atol=1e-05)
```

This script fails with messages:

```
// Gemm operator cutlass_tensorop_f16_s16816gemm_f16_256x128_64x3_tn_align8
using cutlass_tensorop_f16_s16816gemm_f16_256x128_64x3_tn_align8_base =
  typename cutlass::gemm::kernel::DefaultGemmUniversal<
    cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,
    cutlass::half_t, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8,
    cutlass::half_t, cutlass::layout::RowMajor,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 128, 64>,
    cutlass::gemm::GemmShape<64, 64, 64>,
    cutlass::gemm::GemmShape<16, 8, 16>,
    cutlass::epilogue::thread::LinearCombination<cutlass::half_t, 8, float, float>,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<1>,
    3,
    cutlass::arch::OpMultiplyAdd
>::GemmKernel;

// Define named type
struct cutlass_tensorop_f16_s16816gemm_f16_256x128_64x3_tn_align8_type :
  public cutlass_tensorop_f16_s16816gemm_f16_256x128_64x3_tn_align8_base { };

Mismatched elements: 89872 / 98304 (91.4%)
Max absolute difference: 3300.
Max relative difference: 1.823
 x: array([[2164., 2244., 2334., ..., 1837., 2436., 2396.],
       [1755., 1990., 2096., ..., 1483., 2092., 1882.],
       [1534., 2220., 1702., ..., 1973., 1791., 2022.],...
 y: array([[2164., 2244., 2334., ..., 2576., 2274., 1914.],
       [2368., 1756., 1933., ..., 1934., 2242., 2024.],
       [1692., 1716., 1765., ..., 1975., 1789., 2026.],...
```

But pass with shape `8 x 8192 x 8192`.

**Environment details (please complete the following information):**
- cutlass-3.4.1; torch 2.0.1; A100-SXM4-40GB
- CUDA 11.7 (locally installed and configured PATH, not system installed); Driver Version: 450.156.00  & CUDA Version: 11.4 (system installed).
- `pip install -e .` with `cuda-python==11.8.0`.

**Comment by jackkosaian** [comment]
Hi, @ZiyueHuang.

You are using FP32 accumulation for your CUTLASS kernel.

Can you check whether PyTorch is using FP32 accumulation?

You may need to set `torch.backends.cuda.matmul.allow_fp16_reduced_precision_reduction = False` to enable FP32 accumulation. See [here](https://pytorch.org/docs/stable/notes/numerical_accuracy.html#reduced-precision-reduction-for-fp16-and-bf16-gemms) for details.

**Comment by ZiyueHuang** [comment]
Hi @jackkosaian ,

Thanks for your response. I added `torch.backends.cuda.matmul.allow_fp16_reduced_precision_reduction = False` after `import torch` in the above script, but it does not work. Still fails for `8 x 12288 x 8192` but pass for `8 x 8192 x 8192`.

**Comment by ZiyueHuang** [comment]
@thakkarV @hwu36 Could you please also take a look?

**Comment by hwu36** [comment]
```
[haichengw@ipp2-1606 build_90a]$ ./tools/profiler/cutlass_profiler --m=8 --n=12288 --k=8192



=============================
  Problem ID: 1

        Provider: CUTLASS
   OperationKind: gemm
       Operation: cutlass_tensorop_f16_s16816gemm_f16_256x128_64x3_tn_align8

          Status: Success
    Verification: ON
     Disposition: Passed

reference_device: Passed
          cuBLAS: Not run
           cuDNN: Not run

       Arguments: --gemm_kind=universal --m=8 --n=12288 --k=8192 --A=f16:row --B=f16:column --C=f16:column --D=f16:column  \
                  --alpha=1 --beta=0 --split_k_mode=serial --split_k_slices=1 --batch_count=1 --raster_order=heuristic  \
                  --op_class=tensorop --accum=f32 --cta_m=256 --cta_n=128 --cta_k=64 --cluster_m=1 --cluster_n=1 --cluster_k=1  \
                  --stages=3 --warps_m=4 --warps_n=2 --warps_k=1 --inst_m=16 --inst_n=8 --inst_k=16 --min_cc=80 --max_cc=1024  \
                 

           Bytes: 201654272  bytes
           FLOPs: 1610809344  flops
           FLOPs/Byte: 7

         Runtime: 0.163752  ms
          Memory: 1146.89 GiB/s

            Math: 9836.88 GFLOP/s


=============================

CSV Results:

Problem,Provider,OperationKind,Operation,Disposition,Status,gemm_kind,m,n,k,A,B,C,D,alpha,beta,split_k_mode,split_k_slices,batch_count,raster_order,op_class,accum,cta_m,cta_n,cta_k,cluster_m,cluster_n,cluster_k,stages,warps_m,warps_n,warps_k,inst_m,inst_n,inst_k,min_cc,max_cc,Bytes,Flops,Flops/Byte,Runtime,GB/s,GFLOPs
1,CUTLASS,gemm,cutlass_tensorop_f16_s16816gemm_f16_256x128_64x3_tn_align8,passed,success,universal,8,12288,8192,f16:row,f16:column,f16:column,f16:column,1,0,serial,1,1,heuristic,tensorop,f32,256,128,64,1,1,1,3,4,2,1,16,8,16,80,1024,201654272,1610809344,7,0.163752,1146.89,9836.88
```
i can run it with cutlass profiler.  your B matrix is pretty big.  have you check all the memory operation is correct.  e.g. the return value of cuda malloc.  btw, 11.7 is not good with tensor core code.  better using a different one.

@jackkosaian , could you try it through our python interface.

**Comment by ZiyueHuang** [comment]
@hwu36 Thanks for your help. `cutlass_profiler` works fine.

```
./tools/profiler/cutlass_profiler --operation=Gemm --gemm_kind=universal --A=f16:row --B=f16:column --m=8 --n=12288 --k=8192 --accumulator-type=f32 --min_cc=80 --max_cc=80 --kernels="*align8"
```

This passes with many kernels, for example, `cutlass_tensorop_f16_s16816gemm_f16_128x128_32x3_tn_align8`.

But why the python interface fails?

**Comment by jackkosaian** [comment]
This error is occurring due to the way that the Python interface interprets problem shapes.

`tensor_B` is initialized to be of size `(n,k)`. I assume that this is being done because `torch.nn.functional.linear` expects that B is of shape `(n,k)`.

Under the hood, the CUTLASS Python interface uses the shapes of operands A and B to detemine the problem shape; we use `m = A.shape[0], n = B.shape[1], k = A.shape[1]`. Thus, when you pass in A of shape (8, 8192) and B of shape (12288, 8192), it interprets the GEMM to be of size 8x8192x8192, whereas it should really be 8x12288x8192. This explains why the code you pasted is passing when `k == n`.

I see that you are passing in `layout_B = cutlass.LayoutType.ColumnMajor`. I assume that this is in attempt to transpose the row-major torch tensor. Currently, the CUTLASS Python interface doesn't assume that an operand needs to be transposed to get the correct shape if a column-major tag is used -- it is assumed that the shape of the tensor passed in as an operand represents `k x n` for B.

We could potentially detect that a tensor passed in is a torch tensor, and, thus, that data is represented in row-major order and  that problem shape should be updated if the user passes in that they want to treat the operand as column major.

Without a change like this, you could get your code working through the following changes:
1. Change the initialization of `B` so that it is of shape (k, n)
2. Remove  `layout_B=cutlass.LayoutType.ColumnMajor` in the initialization of `cutlass.op.Gemm`
3. Change the second operand in `torch.nn.functional.linear` to be `tensor_B.transpose(0,1)`
