### ISSUE TITLE
[QST] GEMM Batched or Single?

### ISSUE THREAD

**Issue by jomivaan** [NVIDIA/cutlass#1414]
I am creating a program that will perform approximately 80 GEMMs (independent),  using GemmBatched. However, when I was to use streams, I did not find a way to do so. Is it possible to use Cuda Streams in GemmBatched to maximize concurrency? Would it make more sense to do 80 simple GEMMs (each one associated to a stream) instead of 1 Batched GEMM ?
Thank you for the help.

**Comment by jackkosaian** [comment]
By "independent," do you mean that these GEMMs can have different shapes and strides?

If so, it sounds like your workload might be a good fit for CUTLASS's grouped GEMM.

You can see examples and documentation on this [here ](https://github.com/NVIDIA/cutlass/blob/main/examples/24_gemm_grouped/gemm_grouped.cu) and [here](https://github.com/NVIDIA/cutlass/blob/main/examples/57_hopper_grouped_gemm/57_hopper_grouped_gemm.cu).

Note that [example 24](https://github.com/NVIDIA/cutlass/blob/main/examples/57_hopper_grouped_gemm/57_hopper_grouped_gemm.cu) (which is linked above) also shows an example of how to run batched GEMM in CUDA streams (see [here](https://github.com/NVIDIA/cutlass/blob/629f4653c3ea3db3264030382956fabe715f3436/examples/24_gemm_grouped/gemm_grouped.cu#L819-L1153)).

**Comment by jomivaan** [comment]
Hello,
No, all of them have the same shapes and strides. I have looked at those examples before and could not understand them 100%. At example 24, in line 1056 a "batch_count " is specified and then at 1081 a stream is attributed (from my understanding) to compute that batch. Isn't this doing the exactly the same as the the BatchedGemm? I may have misunderstood the example though.  
From the last link, to run batched GEMMs with Cuda Streams, I have to use Grouped GEMM, is that correct? So I would split the 80 independent GEMMs into (for example) 10 batches each with 8 GEMMs and attribute them to 8 streams? 
Again, thank you.

**Comment by hwu36** [comment]
you just need 1 stream to run batch gemm.  every gemm will have its own batch id.  you could take a look at this example https://github.com/NVIDIA/cutlass/blob/main/examples/05_batched_gemm/batched_gemm.cu to help you understand at first.

cutlass batch gemm is the same as cublas batch gemm.

**Comment by jomivaan** [comment]
> you just need 1 stream to run batch gemm. every gemm will have its own batch id. you could take a look at this example https://github.com/NVIDIA/cutlass/blob/main/examples/05_batched_gemm/batched_gemm.cu to help you understand at first.
> 
> cutlass batch gemm is the same as cublas batch gemm.

Hello, I used that example as a foundation for my implementation. So, by using the batched GEMM I will be limited to just 1 stream, if I understood correctly. Is there any gain by switching to the Grouped GEMM (to do a Batched GEMM) and using more streams? Thank you.

**Comment by jomivaan** [comment]
> group gemm just uses 1 stream too. batch gemm requires every gemm has the same size, group gemm has no such restriction.

Oh ok ok. So the best option is to use (for example), 10 batches of 8 GEMMs each associated to a stream instead of 80 GEMMS in 1 batch for 1 stream. Using either Batched or Grouped, it all comes to how I create the batches, correct? Thank you.

**Comment by thakkarV** [comment]
You will get better perf if you just one a single batched/ptr array/grouped GEMM on a single stream

**Comment by jeejeelee** [comment]
> group gemm just uses 1 stream too. batch gemm requires every gemm has the same size, group gemm has no such restriction.

Hi,It seems that group gemm doesn't support split-k. Is this correct?

Are there any alternative methods to achieve  group gemm with split-k functionality?
