### ISSUE TITLE
Typo for SIMT padding

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#142]
https://github.com/NVIDIA/cutlass/blob/c2b80ad4e4f8b60a65500bd04c8fecddff2ba355/include/cutlass/gemm/threadblock/default_mma_core_simt.h#L392

Per my understanding, this should be `MatrixShape<kPaddingM, 0>,`, even though the kPaddingM and kPaddingN have the same value, conceptually it's not correct.

**Comment by d-k-b** [comment]
This should be fixed in 2.4, please reopen if we missed it, though.
