### ISSUE TITLE
[FEA]grouped GEMM FP8 support via CUTLASS Python interface

### ISSUE THREAD

**Issue by dominicshanshan** [NVIDIA/cutlass#1422]
Wondering if grouped GEMM FP8 are support in CUTLASS Python interface, in the current main-branch found it only support FP16/FP32/BF16/INT8/INT32 datatype

**Comment by dominicshanshan** [comment]
found it! case closed

**Comment by ZhongYingMatrix** [comment]
> found it! case closed
Hello, may I ask where exactly should I configure this? From my understanding, it seems that the current grouped GEMM in CUTLASS [Python interface](https://github.com/NVIDIA/cutlass/blob/v3.4.1/python/cutlass/op/gemm_grouped.py) is not that in [hopper example](https://github.com/NVIDIA/cutlass/blob/v3.4.1/examples/57_hopper_grouped_gemm/57_hopper_grouped_gemm.cu), thus I wonder if FP8 supported?

**Comment by jackkosaian** [comment]
FP8 grouped GEMM is not currently supported in the CUTLASS Python interface, as we have yet to add the CUTLASS 3.x grouped GEMM API to the Python interface.
