### ISSUE TITLE
[BUG] Can't build cutlass3.5 on windows10, Visual Studio 2019 v16.11.27, cuda 12.0.

### ISSUE THREAD

**Issue by RongRongRongRong** [NVIDIA/cutlass#1425]
Hi, I use Visual Studio 2019 v16.11.27 to build the example 16-ampere_tensorop_conv2dfprop.cu of cutlass 3.5, but there are lots "auto is not allowed here" errors in include\cute\numeric\integral_constant.hpp.
My system:
windows10,
Cuda version:12.0
C++17,
Visual Studio 2019 v16.11.27.

**Comment by thakkarV** [comment]
@mhoemmen

**Comment by mhoemmen** [comment]
@RongRongRongRong Thank you for reporting this issue!  Could you please share your CMake options?  We do test MSVC builds, but it would be helpful to know e.g., your `CUTLASS_NVCC_ARCHS` setting.

**Comment by RongRongRongRong** [comment]
> @RongRongRongRong Thank you for reporting this issue! Could you please share your CMake options? We do test MSVC builds, but it would be helpful to know e.g., your `CUTLASS_NVCC_ARCHS` setting.

Thanks for your reply, I've resolved the issue. I used the CUDA template in Visual Studio to generate and build the project solution. At first, I changed the C++ language standard in the project's properties to C++17, but I found that this didn't work. After adding the compilation options -std=c++17 -Xcompiler="/Zc:__cplusplus" in the command line, I successfully compiled and ran the program.

**Comment by mhoemmen** [comment]
@RongRongRongRong Thanks for the report and for your interest in CUTLASS!

The normal way that we recommend building CUTLASS is to run CMake first to generate the MSVC project solution.  Please refer to the Windows build documentation in `media/docs/build/building_in_windows_with_visual_studio.md`.

https://github.com/NVIDIA/cutlass/blob/main/media/docs/build/building_in_windows_with_visual_studio.md

CMake knows to set all those compilation options for you.
