### ISSUE TITLE
[BUG] Can't build cutlass3.5 on windows10, Visual Studio 2019 v16.11.27, cuda 12.0.

### ISSUE THREAD

**Issue by RongRongRongRong** [NVIDIA/cutlass#1426]
Hi, I use Visual Studio 2019 v16.11.27 to build the example 16-ampere_tensorop_conv2dfprop.cu of cutlass 3.5, but there are lots of "auto is not allowed here" errors in include\cute\numeric\integral_constant.hpp.
My system:
windows10,
Cuda version:12.0
C++17,
Visual Studio 2019 v16.11.27.

**Comment by hwu36** [comment]
@mhoemmen

**Comment by mhoemmen** [comment]
@RongRongRongRong Thanks for reporting!  May I ask what CMake options you are using?  How are you running CMake?
