### ISSUE TITLE
Question, what does this constraint mean

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#143]
https://github.com/NVIDIA/cutlass/blob/c2b80ad4e4f8b60a65500bd04c8fecddff2ba355/test/unit/gemm/device/simt_sm50.py#L220

I don't quite understand the meaning of this constraint. It's kind of something related to register size, but could someone explain it in detail, such as what does 8*32 stand for?

Thanks!

**Comment by hwu36** [comment]
Sorry for the late response.

You are right.  This piece of code skips generating SIMT kernels that need more than 64 (8 x 8 ) accumulator registers.  Every register is 32 bit.

**Comment by Peter9606** [comment]
Thank you!
