### ISSUE TITLE
[QST]Can I use cutlass to implement the vbatch of MAGMA?

### ISSUE THREAD

**Issue by Qwesh157** [NVIDIA/cutlass#1434]
**What is your question?**
MAGMA proposes vbatched-routine to execute a group of small GEMM in a singel kernel. It uses the gridDim.z dimension in CUDA
grid to batch the small GEMMs, and in different gridDim.z it have different thread block shape for each GEMM. I'm not quiet familiar with cutlass,can these be achieved？

**Comment by thakkarV** [comment]
Yes we support all types of batched GEMMs

**Comment by Qwesh157** [comment]
> Yes we support all types of batched GEMMs

but what should i do if i want to use different thread block shape and warp shape for different size GEMM in a single kernel?

**Comment by mnicely** [comment]
I think you want to use the Grouped GEMM. It will handle all the implementation details

**Comment by jackkosaian** [comment]
Hi, @Qwesh157. Using a different tile shape and warp shape per GEMM in the same kernel isn't currently supported by either batched GEMM or grouped GEMM in CUTLASS, and it is not currently on the road map.

**Comment by Qwesh157** [comment]
@jackkosaian Thanks for replying, i'll keep on following cutlass
