### ISSUE TITLE
[QST] Strided dgrad conv epilogue does not use fast divmod

### ISSUE THREAD

**Issue by ZelboK** [NVIDIA/cutlass#1436]
https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/predicated_tile_iterator_strided_dgrad.h#L315-L318

This piece of code can be replaced by using fast divmod.  The same can be applied to the store function below.

**Comment by ZelboK** [comment]
@hwu36

**Comment by hwu36** [comment]
@manishucsd

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/main/media/docs/efficient_gemm.md
https://github.com/NVIDIA/cutlass/blob/main/media/docs/implicit_gemm_convolution.md

also our gtc cutlass talks mentioned the basic concepts, conv, strided dgrad in details.

**Comment by manishucsd** [comment]
Yes, you can replace these lines with `fast_divmod`. I remember doing this change and surprisingly the performance dropped a couple of TFLOP/s. Feel free to make a change and report before/after performance numbers.

**Comment by mammoth831** [comment]
> Yes, you can replace these lines with `fast_divmod`. 

hi, the `p_` and `q_` are computed from `start_r` and `start_s` (`start_r`->`start_h_`->`p_`), while `start_r` and `start_s` is decided by the thread block idx. 

Do you mean to construct the `fast_divmod` object on the device directly? If so, I think maybe we have to do the raw `divmod` here. Int32 `divmod` only takes about 20 instructions which is much cheaper than calculating the multiplier and shift of `fast_divmod`.

**Comment by ZelboK** [comment]
**BEFORE**
line:
`int n = npq_offset / (p_ * q_);`
translates to 
[before_first_line_sass.txt](https://github.com/NVIDIA/cutlass/files/14826990/before_first_line_sass.txt)
line:
`int residual = npq_offset % (p_ * q_);`
translates to 
[before_second_line_sass.txt](https://github.com/NVIDIA/cutlass/files/14826999/before_second_line_sass.txt)

***AFTER***
this code:
```
params_.divmod(n, residual, npq_offset);
params_.divmod_two(p, q, residual);
```
leads to 
```
2651	0000000f 00c699a0	      ISETP.NE.AND P4, PT, R9, 0x1, PT 	133	0	0									


2720	0000000f 00c69df0	      ISETP.NE.AND P0, PT, R42, 0x1, PT 	149	0	0									
2721	0000000f 00c69e00	      IMAD.MOV.U32 R40, RZ, RZ, R11 	150	0	0									
2722	0000000f 00c69e10	@P0   IMAD.HI.U32 R2, R40, R2, RZ 	149	0	0									
2723	0000000f 00c69e20	      MOV R11, R7 	150	0	0									
2724	0000000f 00c69e30	      IMAD.MOV.U32 R7, RZ, RZ, R0 	150	0	0									
2725	0000000f 00c69e40	      IMAD.MOV.U32 R0, RZ, RZ, R40 	150	0	0									
2726	0000000f 00c69e50	@P0   SHF.R.U32.HI R0, RZ, R43, R2 	150	0	0
```
assembly

Last 3 columns are:
`Live Registers, Warp Stall Sampling, Instructions Executed`

the `FastDivmod` was formed like this:

```
    params_.divmod = FastDivmod(p_*q_);
    params_.divmod_two = FastDivmod(params_.problem_size.Q);
```
all tests pass. 

Tangential: Does anyone know of a more convenient way to extract relevant assembly in ncu-ui? I like how it will correlate your source code to the assembly but it doesn't give you an option to extract exclusively those lines... Feels like an easy feature

**Comment by ZelboK** [comment]
Like @manishucsd has stated I am consistently seeing that these changes are performing more poorly.

(quick ss)
![image](https://github.com/NVIDIA/cutlass/assets/122740063/65f30e09-0c35-480e-a420-e2bb357401ee)

from running 

```
./tools/profiler/cutlass_profiler  --kernels=cutlass_tensorop_f16_s16816dgrad_optimized_f16_* --n=34 --h=28 --w=28 --c=256 --k=256 --r=3 --s=3 --pad_h=1 --pad_w=1 --stride_h=2 --stride_w=2 --dilation_h=1 --dilation_w=1
```
with these variables

```
cmake .. -DCUTLASS_NVCC_ARCHS=80 -DCUTLASS_LIBRARY_KERNELS="cutlass_tensorop_f16_s16816dgrad_optimized_f16_*" -DCMAKE_CUDA_FLAGS="-lineinfo"
```
(no debug flag)

**Comment by hwu36** [comment]
Thank you @ZelboK.

> I refactor store_with_byte_offset to also use FastDivmod the performance improves

We need it for both store and load.  store is actually more important.

> On my 3080

FP32 accumulation is throttled.  So let us just use fp16 accumulation.  Kernel name is `cutlass_tensorop_h16816dgrad_optimized_*`

> cmake .. -DCUTLASS_NVCC_ARCHS=80

IIRC, 3080 can use 86 to compile.

What problem size or kernel does every line in your performance table use?

Also, could you please run this problem size

`--n=34 --h=28 --w=28 --c=512 --k=1024 --r=1 --s=1 --pad_h=0 --pad_w=0 --stride_h=2 --stride_w=2 --dilation_h=1 --dilation_w=1`

**Comment by manishucsd** [comment]
Is it also worth to have only store numbers in the above table?

**Comment by hwu36** [comment]
The followup needs some exploration from yourself.  You may not need to do anything, or you may need to make some small changes like the first one.  I have not looked into it very deep myself.

Dgrad can be used as deconv (or transposed conv).   @masahi contributed deconv in cutlass 2.9 (https://github.com/NVIDIA/cutlass/tree/main/examples/34_transposed_conv2d).  We want the output of deconv is not packed.  For example, the output problem size is 34x28x28x256, but the output tensor specified by the user can be 34x32x32x512.  The user wants to have some bubbles (e.g. 0s) in the output data.  This maybe already supported or maybe not.  That is the first thing needs to be figured out.

We have the similar requirements to the regular fprop conv.  https://github.com/NVIDIA/cutlass/pull/1437 was written to meet this request.  When we use packed output, fprop conv can reuse the same epilogue as gemm which is https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h (Ignore scatter and permute code in this file).  The main difference between the packed and non packed cod is what you are already familiar with

```
          Stride tensor_coord = CoordinateDecompositionLittleEndian<kStrideRank>(row_offset + thread_start_row_, params_.divmod);

          LongIndex tensor_offset = dot(tensor_coord, params_.tensor_stride);
```

It decomposes the row number into n, p, q and use the stride to compute the new row number.
