### ISSUE TITLE
[QST] how consumer_release works?

### ISSUE THREAD

**Issue by mammoth831** [NVIDIA/cutlass#1438]
https://github.com/NVIDIA/cutlass/blob/8f7d2789b8b04418ac01e515019dc3b74b249070/include/cutlass/gemm/collective/sm90_mma_tma_gmma_ss.hpp#L474-L495

Why we need `consumer_release`  here? I think the `warpgroup_wait<K_PIPE_MMAS>` already ensures the oldest wgmma is completed and then it's safe to do the following TMA. The `consumer_release` just performs `arrive` on the empty barriers and it seems no one else will try to wait for the empty barrier's status or phase(Some functions may do it, but not in this kernel...).

Or it is just trying to sync within the cluster(looks like it is using the arrive function with `cta_id`)?

**Comment by thakkarV** [comment]
Producer acquire needs to check that barrier arrival before reclaiming that buffer for more TMAs
