### ISSUE TITLE
[QST]Cannot get correct copyAtom

### ISSUE THREAD

**Issue by YuQ-sudo** [NVIDIA/cutlass#1440]
**What is your question?**
when I try to construct tiled copy A, I cannot get the correct layout. Config Shown as below.(Cute Version 3.2.1)
template <>
struct Copy_Traits <TestCopy>
{
  // Logical thread id to thread idx (warp)
  using ThrID = Layout<_64>;
  // Map from (src-thr,src-val) to bit
  using SrcLayout = Layout<Shape<_64,_4>,
                           Stride<_128,_32>>;
  // Map from (dst-thr,dst-val) to bit
  using DstLayout = Layout<Shape<Shape<_16,_4>,Shape<_2,_2>>,
                           Stride<Stride<_32,_2048>,Stride<_512,_1024>>>;
  // Reference map from (thr,val) to bit
  using RefLayout = DstLayout;
}

template <>
struct MMA_Traits<Test_MMA_NT>
{
  using ElementDVal = float;
  using ElementAVal = float;
  using ElementBVal = float;
  using ElementCVal = float;

  using Shape_MNK = Shape<_16,_16,_8>;
  using ThrID   = Layout<_64>;
  using ALayout = Layout<Shape<Shape<_16, _4>,_2>,
                  Stride<Stride<_1,_32>,_16>>;
  
  using BLayout = Layout<Shape <Shape <_16, _4>,_2>,
                         Stride<Stride< _1,_32>,_16>>;
  using CLayout = Layout<Shape <Shape <_16, _4>, _4>,
                         Stride<Stride< _1,_16>,_64>>;
};

 {
    using namespace cute;
    using s2r_copy_op = TestCopy;
    using s2r_copy_traits = Copy_Traits<s2r_copy_op>;
    using s2r_copy_atom = Copy_Atom<s2r_copy_traits, float>;
    auto tiled_mma = make_tiled_mma(Test_MMA_NT{},
                                      Layout<Shape<_1,_1,_1>>{},
                                      Layout<Shape<_2,_2,_1>>{});
    auto s2r_tiled_copy_a = make_tiled_copy_A(s2r_copy_atom{}, tiled_mma);
    print_latex("TestCopy", s2r_tiled_copy_a);
  }
![image](https://github.com/NVIDIA/cutlass/assets/55684266/f6929da6-042d-4d9c-9a7a-b7245a8b763d)
figure1 and figure2 is the test result. The DstLayout is ok, however SrcLayout seems to be error, which should be the shape of figure3. So I get confused, don't know  what went wrong. Could you please provide some advice？

**Comment by thakkarV** [comment]
I'm confused. Your MMA and copy atoms are 64 threads wide and don't have a shape or layouts I've seen before. Can you please point to the PTX docs for which MMA you're trying to add support for? It also seems like what you want in this case isn't an atom rather a tiled mma and copy

**Comment by YuQ-sudo** [comment]
sorry, I just miss the code "auto s2r_tiled_copy_a = make_tiled_copy_A(s2r_copy_atom{}, tiled_mma);"  yeah, you are right.I just try to use cute  on other platform instead of Nvidia. In this case, what I want is the correct tiled_copy.As shown the SrcLayout isn't what I expect. Any suggestions will be appreciated.

**Comment by thakkarV** [comment]
Sorry. CuTe is heavily codesigned for NVIDIA GPU architecture.
