### ISSUE TITLE
[QST] Why we use three sync in sgemm_1?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1442]
I am learning this example: 
https://github.com/NVIDIA/cutlass/blob/c4e3e122e266644c61b4af33d0cc09f4c391a64b/examples/cute/tutorial/sgemm_1.cu#L209-L211

**What is your question?**
```
    cp_async_fence();        // Label the end of (potential) cp.async instructions
    cp_async_wait<0>();      // Sync on all (potential) cp.async instructions
    __syncthreads();         // Wait for all threads to write to smem
```

Why we have three sync in sgemm_1???

**Comment by cloudhan** [comment]
On some new archtectures say sm_80, the very basic form `copy(...)`, that is, without specifying the copy atom, might generate cp.async instruction. So you need further safety guarantee.

**Comment by JINO-ROHIT** [comment]
similar question, why do we need to do this? `cp_async_fence();` what happens if i skip this?
