### ISSUE TITLE
[QST]In cute, how to control register amount? What is the meaning of "Tile" in make_tiled_mma?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1447]
https://github.com/reed-lau/cute-gemm/blob/25952de314daf740ec637a3bb7bb145605fd5edb/gemm-simple.cu#L84-L86

I learnt [0t_mma_atom](https://github.com/NVIDIA/cutlass/blob/c4e3e122e266644c61b4af33d0cc09f4c391a64b/media/docs/cute/0t_mma_atom.md)

I know a mma will compute a certain part, like here we use "SM80_16x8x8_F16F16F16F16_TN" so it is 16-8-16(MNK), 
```
make_tiled_mma(mma_atom{}, 
                      make_layout(Shape<_2, _2, _1>{}), 
                      make_layout(Shape<_1, _2, _1>{}))
```
Above will let compute tile to be M=16*2*1=32, N=8*2*2=32, K=16*1*1=16. And I know, first layout 2,2,1, will influence the total threads per block, and the second layout 1,2,1, will influence the register per thread?

So know I change 1, 2, 1 into 1, 1, 1, and expect register will decrease a lot! maybe 50%? or at least 30-40%. But I get register from 186(1, 2, 1) into 194(1, 1, 1). Why!?!? What is the meaning of Tile in make_tiled_mma???

**Comment by ziyuhuang123** [comment]
I guess, just guess, if we have a tile 32, 32, 16, maybe we will first compute 32, 16, 16, and then compute the other 32, 16, 16, so the register will increase? Actually, how to control register is of course important.

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
This code is not up to date with the latest version of the CUTLASS API, so the question is not really relevant anymore. I recommend reading our tutorial code instead, or asking @reed-lau about this specific example from his repo.
