### ISSUE TITLE
[QST]How MMA_M, MMA_N, MMA_K computed in cute?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1448]
I know make_tiled_mma will create a mma_tile, and then along M, N, K we will get MMA_M, MMA_N, MMA_K dimensions. So inside cute::gemm, we will loop across MMA_M, MMA_N, MMA_K one by one?

**Comment by YichengDWu** [comment]
Yes. First you have a MMA atom and you will use them to make a MMA tile, then use the tile to partition the compute tile. For example, if you start with the 16-8-16 MMA atom, and the layout of atoms being (3,4,2), that is equivalently to say you create a bigger MMA atom of size 48-32-32, and it uses  32*3*4*2 threads to run in parallel. Finally, if the compute tile has size 96-96-64, then you get extra dimensions (MMM_M, MMA_N, MMA_K)=(96/48, 96/32, 64/32) and they are running sequentially.
