### ISSUE TITLE
[QST] Question about zipped_divide example

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1449]
In the `02_layout_algebra` doc, we have the illustrative example

```text
Layout Shape : (M, N, L, ...)
Tiler Shape  : <TileM, TileN>

logical_divide : ((TileM,RestM), (TileN,RestN), L, ...)
zipped_divide  : ((TileM,TileN,...), (RestM,RestN,L,...))
tiled_divide   : ((TileM,TileN,...), RestM, RestN, L, ...)
flat_divide    : (TileM, TileN, ..., RestM, RestN, L, ...)
```
Why does the line for `zipped_divide` not read
```text
zipped_divide  : ((TileM,TileN), (RestM,RestN,L,...))
```
Since the tiler has only two entries with no ellipses it would seem that the first mode of the result would not need ellipses, unless I'm misunderstanding.

**Comment by ccecka** [comment]
You're right, that's a typo. Thanks!
