### ISSUE TITLE
[QST] Best way to implement a custom iterator?

### ISSUE THREAD

**Issue by andylolu2** [NVIDIA/cutlass#1450]
I want to implement block-sparse GEMM (fp16 x fp16 -> fp32), except that my inputs are fully materialized, dense matrices. I have chosen the sparsity block size to match the GEMM block size so all I need to do is skip over certain blocks on the threadblock level, conditioned on some blockwise mask.

Which entry point into CUTLASS would be the easiest to implement this? I see that CUTLASS 2.X has the "Iterator" concept which seems to apply nicely to my problem. Is there an equivalent interface for 3.X? I am targeting sm75/80.

**Comment by cloudhan** [comment]
With cute (3.x), you just need to operate on cute::Tensor and iterate through integer index (or coord). How to tile your data and program is fully up to you. So your question with cute might just transform into where you should put your
```
if (shoud_skip(coord)) continue;
```

**Comment by andylolu2** [comment]
I was just wondering whether there is already a suitable interface defined by the device-level/threadblock-level/warp-level gemm algorithms or is the only way to rewrite everything "from scratch".
