### ISSUE TITLE
[BUG] Indexing bug in `get_layoutB_TV`?

### ISSUE THREAD

**Issue by andylolu2** [NVIDIA/cutlass#1457]
I haven't actually run into any issues but found something that looks a bit suspicious in `cute/atom/mma_atom.hpp`. Just wanted to flag it.

https://github.com/NVIDIA/cutlass/blob/19f3cc33f1642b490ed7126ea0141f79c0045527/include/cute/atom/mma_atom.hpp#L486-L507

In line 497, shouldn't it be `make_shape (size<2>(thr_layout_vmnk_), size<3>(thr_layout_vmnk_))` instead of `make_shape (size<1>(thr_layout_vmnk_), size<2>(thr_layout_vmnk_))`?

Please close the issue if this is intended.

**Comment by ccecka** [comment]
This is intended, just a bit esoteric and cryptic -- I'll keep this in mind to find a more clear implementation.

As stated in the comment, the goal of the `btile` is to map `(ThrV,(ThrN,Thr_K)` [correcting the comment] to `(ThrV,(ThrM,ThrN,ThrK))`. That is, to insert a `ThrM` mode that represents the projection of the threads in the m-mode. This makes it compatible with the codomain of the `thridx_2_thrid` layout afterwards.

To accomplish that, we compose the `ThrN` mode only with `(ThrM,ThrN):(_0,_1)` to insert the "dummy" or "projected-out" `ThrM` mode with stride-0. An equivalent strategy could manipulate the `thridx_2_thrid` layout to account for the same projection or just `insert` this mode manually.

**Comment by andylolu2** [comment]
Makes sense!
I made a tiny PR #1458 to fix the comment error you mentioned, together with some other variable/comment naming issues in the file.

**Comment by ccecka** [comment]
Thanks! Approved
