### ISSUE TITLE
Example 08_turing_tensorop_gemm EXTREMELY SLOW versus 00_basic_gemm

### ISSUE THREAD

**Issue by TheNewSound** [NVIDIA/cutlass#146]
I am benchmarking example _08_turing_tensorop_gemm_ **versus** _00_basic_gemm_ using int8 input matrices, int32 output/accumulate.

Compiled using CUDA 10.2, running on CUDA 10.2, target architecture = SM_75, running on a RTX2080Ti.

Am I doing something wrong in my code? Or are tensor cores extremely slow?

Benchmarking code: 
Git: https://github.com/TheNewSound/cutlass/tree/original

[00_basic_gemm
](https://github.com/TheNewSound/cutlass/blob/original/examples/00_basic_gemm/basic_gemm.cu)
[08_turing_tensorop_gemm
](https://github.com/TheNewSound/cutlass/blob/original/examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu)
![image](https://user-images.githubusercontent.com/1410503/99571405-8d46d580-29d3-11eb-99a5-4c0a5a10c57b.png)

_08_turing_tensorop_gemm_ seems to be extremely slow versus _00_basic_gemm_ ?

**Comment by hwu36** [comment]
What is your k dimension size?

**Comment by TheNewSound** [comment]
> What is your k dimension size?

k=m=n

**Comment by TheNewSound** [comment]
I just see I am benchmarking the wrong method..........................................

**Comment by hwu36** [comment]
You can use cutlass_profiler to do this.

https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md
