### ISSUE TITLE
Supports for s4 and s8 GEMM on Python? 

### ISSUE THREAD

**Issue by mlpen** [NVIDIA/cutlass#1463]
Hi, 

There are supports for using cutlass on Python https://github.com/NVIDIA/cutlass/blob/main/python/README.md, so I am wondering if there is a plan to support s4 and s8 GEMM on Python. 
If not, is there any resource that I can use if I want to implement them by myself? 

Thanks!

```[tasklist]
### Tasks
```

**Comment by jackkosaian** [comment]
The CUTLASS Python interface does support s8 GEMMs. Unit tests that show examples of using these are [here](https://github.com/NVIDIA/cutlass/blob/main/test/python/cutlass/gemm/gemm_s8_sm80.py) and [here](https://github.com/NVIDIA/cutlass/blob/main/test/python/cutlass/gemm/gemm_s8_sm90.py).

The CUTLASS Python interface does not currently support s4. You can see this issue for some details related to this: https://github.com/NVIDIA/cutlass/issues/756

**Comment by mlpen** [comment]
Thank you so much for the prompt response! This is helpful.
