### ISSUE TITLE
[QST] PyTorch + CUTLASS Batched GEMM Kernel - Expression Must be Constant

### ISSUE THREAD

**Issue by nickjeliopoulos** [NVIDIA/cutlass#1474]
Good evening, all. I am attempting to compile a minimal [CUTLASS](https://github.com/NVIDIA/cutlass/releases/tag/v3.4.1) GEMM example in a PyTorch project. I want to write a simple CUTLASS kernel and be able to call it from PyTorch.

I have a minimal example that refuses to compile.
**setup.py**
```
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension

setup(
    ### Minimal Example Args
    name="gorby",
    install_requires=["torch >= 2.1", "pybind11"],
    ### PyTorch C++/CUDA Examples
    ext_modules=[
        #CUDAExtension(
        #    name="gorby_vector_add", sources=["gorby_vector_add.cu"]
        #),
        #CUDAExtension(
        #    name="gorby_nvtx", sources=["gorby_nvtx.cpp"]
        #),
        CUDAExtension(
            name="gorby_sdpa", sources=["gorby_sdpa.cu"],
            include_dirs=['C:\\Users\\neliopou\\Documents\\PhD\\Github\\cutlass\\include']
        ),
    ],
    cmdclass={"build_ext": BuildExtension},
)
```

**gorby_sdpa.cu** - taken from CUTLASS https://github.com/NVIDIA/cutlass/blob/main/examples/05_batched_gemm/batched_gemm.cu
```
// CUTLASS
#include "cutlass/cutlass.h"
#include "cutlass/layout/matrix.h"
#include "cutlass/gemm/device/gemm_array.h"
#include "cutlass/gemm/device/gemm_batched.h"

cudaError_t cutlass_array_sgemm(
  int m,
  int n,
  int k,
  float alpha,
  float const * const *A,
  int lda,
  float const * const *B,
  int ldb,
  float * const *C,
  int ldc,
  float beta,
  int batch_count) {

  using Gemm = cutlass::gemm::device::GemmArray<
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor
  >;

  Gemm gemm_op;

  cutlass::Status status = gemm_op({
    {m, n, k},
    A, lda,
    B, ldb,
    C, ldc,
    C, ldc,
    {alpha, beta},
    batch_count
  });

  if (status != cutlass::Status::kSuccess) {
    return cudaErrorUnknown;
  }

  return cudaSuccess;
}
```
I run `MAX_JOBS=4 python setup.py develop` to compile and get the following output
[build.txt](https://github.com/NVIDIA/cutlass/files/14952917/build.txt)

The errors seem to indicate some type problem originating from CUTLASS and I am not sure how to proceed.
* Windows Version10.0.19045 Build 19045
* GPU: NVIDIA RTX 3090 Ti
* CUDA 11.8
* Compiler: MSVC 2019 14.29.30133
* PyTorch 2.2.2+cu118

**Comment by thakkarV** [comment]
CC @jackkosaian

**Comment by jackkosaian** [comment]
The issue is likely that your `setup.py` script does not indicate that C++17 should be used.

The first error you're getting,
```
include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): error: expression must have a constant value
```
is complaining that the result of `cutlass::const_min` is not constant in [this line](https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/include/cutlass/gemm/threadblock/default_mma_core_simt.h#L533).

`cutlass::const_min` is defined [here](https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/include/cutlass/fast_math.h#L738-L741).

Note that it contains the `CUTLASS_CONSTEXPR_IF_CXX17` macro. This macro resolves to `constexpr` only if one is using C++17 or higher (see [here](https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/include/cutlass/detail/helper_macros.hpp#L149-L155)). Thus, without using C++17, `const_min` will not return a constant value, and, thus, can't be used in assigning a member defined as `static const`.

You can enforce your build to use C++17 by adding the following `extra_compile_args` to `setup.py`:
```python
        CUDAExtension(
            name="gorby_sdpa", sources=["gorby_sdpa.cu"],
            include_dirs=['C:\\Users\\neliopou\\Documents\\PhD\\Github\\cutlass\\include'],
            extra_compile_args={
              'cxx': ['-std=c++17'],
              'nvcc': ['-std=c++17', ],
           },
        ),
```

**Comment by nickjeliopoulos** [comment]
Thanks for your response! Sadly, this did not seem to change the log - Here's the generated `build.ninja`
It seems like we are compiling with C++17 still.
[build.ninja.txt](https://github.com/NVIDIA/cutlass/files/14961310/build.ninja.txt)

HOWEVER, I just did some digging and it seems like manually modifying [helper_macros.hpp](https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/include/cutlass/detail/helper_macros.hpp#L149-L155) and commenting out the C++17 check allows my code to compile.

This led me to find somehow there is a mismatch between the `_cplusplus` macro and MSVC's `_MSVC_LANG` (which seems to e the correct C++ version) - I printed the values of these macros with `pragma message`:
`_cplusplus = 199711L`
`_MSVC_LANG = 201703L `

Making the following change in `helper_macros.hpp` seems to handle the issue:
```
#if (201700L <= __cplusplus)
#define CUTLASS_CONSTEXPR_IF_CXX17 constexpr
#define CUTLASS_CXX17_OR_LATER 1
#else
#define CUTLASS_CONSTEXPR_IF_CXX17
#define CUTLASS_CXX17_OR_LATER 0
#endif
```

```
#ifndef _MSVC_LANG  
#define MSCV_LANG _MSVC_LANG
#else
#define MSCV_LANG 0
#endif

#if (201700L <= __cplusplus || 201700L <= _MSVC_LANG)
#define CUTLASS_CONSTEXPR_IF_CXX17 constexpr
#define CUTLASS_CXX17_OR_LATER 1
#else
#define CUTLASS_CONSTEXPR_IF_CXX17
#define CUTLASS_CXX17_OR_LATER 0
#endif
```

**Comment by d-k-b** [comment]
The CUTLASS cmake system sets a lot of compile options for the CUTLASS kernels. If you are not using CUTLASS via cmake but rather just including the cutlass headers and compiling on your own, then you'll need to ensure similar settings are included.

For the issue you are seeing, see https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/CMakeLists.txt#L439-453 , these lines set the appropriate msvc flag to ensure the language feature flags are setup properly during compilation.

**Comment by nickjeliopoulos** [comment]
Thanks for your help. The least intrusive solution (arguably not very proper, however) is to add the `/Zc:__cplusplus` flag via PyTorch's `cpp_extension` module when we import it in `setup.py`:
```
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension, COMMON_MSVC_FLAGS
COMMON_MSVC_FLAGS += ['/Zc:__cplusplus']
...
```

This seems to be the easiest fix for someone just trying to build CUTLASS on Windows / MSVC with PyTorch.

I suppose a better solution would be to handle this within PyTorch rather than within CUTLASS.
