### ISSUE TITLE
[QST] What is the easiest way to partition/slice a tensor in CUTE to get a subtensor?

### ISSUE THREAD

**Issue by srikantvv** [NVIDIA/cutlass#1476]
For example, if I have a tensorA (_256,_64):(_64,_1). I want to get a subtensor with the first two columns to end up with a shape tensorB (_2, _64):(_64,_1). Something with logical_divide seems to be the way, but it is haven't been able to figure out the easiest way.

**Comment by ccecka** [comment]
If you just want that "first" subtensor
```cpp
Tensor my_2x64 = composition(my_256x64, Shape<_2,_64>{});
```
and if you want the slice off any of those subtensors
```cpp
Tensor tmp = flat_divide(my_256x64, Shape<_2,_64>{});    // (_2,_64,_128,_1)
Tensor my_2x64 = tmp(_,_,my_idx0,my_idx1);
```

**Comment by irasin** [comment]
Hi, @ccecka 
It looks like that `composition`  does not work for tensor

here is my test code

```cpp

    {
        auto my_256x64 = make_tensor<float>(Shape<_256, _64>{}, LayoutRight{});
        Tensor my_2x64 = composition(my_256x64, Shape<_2,_64>{});
    }
```
and I got function not found error

![image](https://github.com/NVIDIA/cutlass/assets/25549893/af9e3a9f-bebd-4583-a8f4-fb192a6945d5)

**Comment by ccecka** [comment]
Ah, right. `composition(Tensor, Layout)` is intentionally not defined because it implicitly slices off the "first" subtensor. Use a `divide` to tile a tensor and make the slice explicit instead.

**Comment by irasin** [comment]
Thanks. But I was wondering why not remove the `composition(Tensor, Layout)` API from the documentation? This can be very confusing.

**Comment by ccecka** [comment]
I don't believe it is in the documentation? It should only appear erroneously in this thread.

**Comment by irasin** [comment]
While, it does exist.
In https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/03_tensor.md#tiling-a-tensor
![image](https://github.com/NVIDIA/cutlass/assets/25549893/047e6dad-6674-4aea-98ec-12c3dbf433c7)


And in https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/03_tensor.md#thread-value-partitioning
![image](https://github.com/NVIDIA/cutlass/assets/25549893/9c9d3bb3-5896-47a4-805b-01c606d8b7f4)

Maybe we should not use the terminology `composition` in the `tensor` doc.

**Comment by ccecka** [comment]
I've very surprised that `composition(Tensor, Layout)` doesn't exist, even if it's just for testing and documentation/explanation.

I suppose it should be added (even though it is of little use in real applications).
