### ISSUE TITLE
[QST]Array in cute and in cutlass

### ISSUE THREAD

**Issue by leizhao1234** [NVIDIA/cutlass#1478]
What are the differences between the array type in CUTE and the array in CUTLASS? Could you explain why an array is re-implemented in CUTE?

**Comment by hwu36** [comment]
@thakkarV

**Comment by thakkarV** [comment]
Honestly, no good technical reason. So my answer won't be satisfying to you. There's some subtleties in their usage and semantics but generally they serve similar purposes.
