### ISSUE TITLE
[FEA]  FP8 grouped gemm kernel without TMA

### ISSUE THREAD

**Issue by masahi** [NVIDIA/cutlass#1483]
We want to try a smaller tile size M than 128, which better fits our workload. I'm assuming that the requirement on the tile size M being a multiple of 128 comes from TMA, but for small problem sizes that we encounter in practice, TMA might be an overkill. 

According to @hwu36, this is not currently supported.

**Comment by hwu36** [comment]
@ANIKET-SHIVAM

**Comment by IonThruster** [comment]
`BLOCK_M >= 128` requirement likely comes from the fact only `cooperative` kernel support exists today in CUTLASS 3.5.  If support for other kernel schedules is added (`tma_warpspecialized` or `tma_warpspecialized_pingpong`) - we can go as low as 64 since FP8 MMA instruction size is `64xNx32`.

@masahi : could you share the problem shape for your specific group-gemm for us to better recommend the next steps ?

**Comment by thakkarV** [comment]
Additionally, for really small values of M, you are likely do be b/w bound anyway, for which you can likely get roofline perf from recompiling CUTLASS 2.x Ampere kernels (without or without stream K)

**Comment by masahi** [comment]
> Additionally, for really small values of M, you are likely do be b/w bound anyway, for which you can likely get roofline perf from recompiling CUTLASS 2.x Ampere kernels (with or without stream K)

We did observe that the sm80 kernel is faster for small `M`. Are you suggesting that the 2.x Ampere kernels compile with FP8?

**Comment by masahi** [comment]
> `BLOCK_M >= 128` requirement likely comes from the fact only `cooperative` kernel support exists today in CUTLASS 3.5. If support for other kernel schedules is added (`tma_warpspecialized` or `tma_warpspecialized_pingpong`) - we can go as low as 64 since FP8 MMA instruction size is `64xNx32`.
> 
> @masahi : could you share the problem shape for your specific group-gemm for us to better recommend the next steps ?

I'm working on LLM inference. The problem shape `M` is dynamic and depends on the number of requests in a batch (let's call it "batch size"). The batch size can be as small as 20, for example, and those 20 requests are dynamically routed to 8 experts (or groups) in Mixtral. So even if all 20 requests are routed to a single expert, the problem size `M` is 20 (and 0 for all other experts). 

Such problem shapes might be ridiculously small from your perspective, but we can't always keep the batch size big to minimize latency. `BLOCK_M = 64` is still too big according to the description above, but certainly much better.

**Comment by ANIKET-SHIVAM** [comment]
Hi @masahi,
you can try to expand the CpAsyncWarpSpecialized Hopper kernels (such as [sm90_gemm_warpspecialized_pingpong.hpp](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/sm90_gemm_warpspecialized_pingpong.hpp) to FP8 Grouped Gemm by using components from the TMA Hopper Grouped Gemm kernel.

I believe the Group Tile Scheduler should be easy to plugin: [sm90_tile_scheduler_group.hpp](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/sm90_tile_scheduler_group.hpp) 

You can then change the pointers to A and B based on the group index: https://github.com/NVIDIA/cutlass/blob/7d49e6c7e2f8896c47f586706e67e1fb215529dc/include/cutlass/gemm/kernel/sm90_gemm_warpspecialized_pingpong.hpp#L344C12-L344C19

And the epilogue from the TMA Hopper example (cutlass::epilogue::PtrArrayNoSmemWarpSpecialized) should work as it is too.
