### ISSUE TITLE
[QST] Context on "Collective" vs "Cooperative"

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1485]
Could you help me to separate the terms "collective" and "cooperative" in my mind? Is a cooperative group (never / sometimes / always) (an instance of / contain / contained in) a Collective?

**Comment by thakkarV** [comment]
A collective is a temporal microkernel composed of one or more tiled MMAs and copies orchestrated via arch specific synchronization 

A cooperative gemm/copy is a more user friendly (convenient) wrapper around a tiled MMA or copy where you only care about the input and output tensors and not necessarily the partitioning patterns of desire control over the exact thread layouts. They include no temporal component to them -- all iteration spaces and associated synchro are left to the user.

A collective may or ma not chose to use a cooperative mma or copies but collectives are a superset (incorporating a temporal component to them)

**Comment by ericauld** [comment]
How can I bring into sharper relief in my mind the "temporality" of a collective as opposed to a cooperative? Is there an extra parameter to a collective's API, or part of the implementation which highlights the "temporality"?

**Comment by thakkarV** [comment]
All collectives take in a k tiler iterator and k tile count. Collectives also accept the concrete tiled MMA and copies via their template APIs since they're a performance first interface
