### ISSUE TITLE
Does the CUTLASS based Implicit GEMM convolution support BiasAdd(per channel) operation？

### ISSUE THREAD

**Issue by xiaocenxiaocen** [NVIDIA/cutlass#149]
It seems we have to modify the thread-level epilogue op to support BiasAdd(per channel) operation. And the entry of device function for Implicit Convolution operator does not support passing a pointer of a bias tensor. This has to be modified as well.

**Comment by manishucsd** [comment]
https://github.com/NVIDIA/cutlass/blob/master/examples/17_fprop_per_channel_bias/fprop_per_channel_bias.cu
