### ISSUE TITLE
[FEA] C++ 20 concepts support?

### ISSUE THREAD

**Issue by andylolu2** [NVIDIA/cutlass#1493]
It is really hard to use CUTLASS due to the large (nested) template classes which has poor IDE support (e.g. autocompletion).

[C++ 20 concepts](https://en.cppreference.com/w/cpp/language/constraints) is meant to be a solution to this. I was wondering whether there are any plans to integrate concepts into the CUTLASS repository.

**Comment by thakkarV** [comment]
We've wanted to adopt C++20 but there are no immediate plans to do so right now due to considerations for customer toolchain support. Are there concrete cases where you think CUTLASS could be simpler and friendlier to use by adopting concepts?
