### ISSUE TITLE
[DOC] CuTe documentation questions, resolving confusion, and a potential doc-only patch

### ISSUE THREAD

**Issue by manishucsd** [NVIDIA/cutlass#1497]
1. The layout at line 208 [here](https://github.com/NVIDIA/cutlass/compare/main...manishucsd:cutlass:patch-1#diff-eb60548665e48e0dd8d9f65f793a0a7896c84b5b2365a6250e440004cd74b0faL208) does not seem to be concatenated layout. If that is indeed true, please see the [patch](https://github.com/NVIDIA/cutlass/compare/main...manishucsd:cutlass:patch-1) and we can fix it avoid the confusion. 

2. [01_layout.md:L103](https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/01_layout.md?plain=1#L103) 
```
`cosize(A) = A(size(A) - 1) + 1`
```
This is true for the cases when layout function is a monotonically non-decreasing function from coordinates (integers) to indices (integers). Thus, not true for layouts with -ve strides or swizzle. Correct? 

cc: @ccecka,  @thakkarV , @IonThruster

**Comment by ccecka** [comment]
If this helps, then sure.

For symmetry change line 224 to

> 3. ` = ((5,1):(16,4), (2,2):(80,4))`. Composed Layout as concatenation of sublayouts.

**Comment by ccecka** [comment]
Correct, it's not accurate for negative strides (but the implementation does actually account for them). We've left that out for simplicity. In general, negative strides are rare and inconsistently supported throughout CuTe as-is.

Unfortunately, the `cosize` does not consider swizzles.
```cpp
// Return the codomain size of a mode
template <int... Is, class A, class O, class B>
CUTE_HOST_DEVICE constexpr auto
cosize(ComposedLayout<A,O,B> const& layout)
{
  // XXX Should consider swizzle here
  return cosize<Is...>(layout.layout_b());
}
```
which could be incorrect if (1) the codomain of `layout_b` is not a superset of `layout_a` and/or (2) the swizzle is non-contracting. These cases are very rare, but it could be a potential source of bugs.

**Comment by manishucsd** [comment]
@ccecka , Thanks for confirming on 1. and 2. 
For 1., I have submitted the PR#1498.  
For 2., yeah agreed that these are rare cases. I will leave it you folks if it make sense to include it as a part of the documentation.
