### ISSUE TITLE
[DOC] Typo in logical divide 1D example

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1511]
https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/02_layout_algebra.md#logical-divide-1-d-example

A = (2, 4, 3) : (4, 1, 8)
B = (4 : 1)

I get logical_divide(A, B) = (4:1, (2,3):(4, 8)) not (2,2),(2,3)):((4,1),(2,8)).

**Comment by ccecka** [comment]
There are a few typos on that example that are being fixed here
https://github.com/NVIDIA/cutlass/pull/1486
