### ISSUE TITLE
[QST] two files are included in each other

### ISSUE THREAD

**Issue by wzhcz8902** [NVIDIA/cutlass#1514]
https://github.com/NVIDIA/cutlass/blob/5c447dd84f8ae0e1d48ff9a2eae26ce8c4958101/include/cutlass/gemm/warp/default_mma_tensor_op.h#L121
https://github.com/NVIDIA/cutlass/blob/5c447dd84f8ae0e1d48ff9a2eae26ce8c4958101/include/cutlass/gemm/warp/default_mma_tensor_op_sm80.h#L43

`default_mma_tensor_op.h` includes `default_mma_tensor_op_sm80.h`, while the later also includes the former. Is this a problem?

**Comment by d-k-b** [comment]
@wzhcz8902, this is a standard design pattern used in some libraries to reduce the number of headers most users need to include. The key is that the _base_ header includes the _specialized_ header at the bottom and the _specialized_ header includes the _base_ header at the top. This ensures the proper ordering of text when the code is processed.
