### ISSUE TITLE
[QST] sm70 and sm80 CuTe examples are tiling ordinary float multiplication?

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1520]
In the sm_70.cu and sm_80.cu CuTe examples, am I understanding correctly that they are tiling ordinary float multiplication, and not any complex MMA instruction? 

https://github.com/NVIDIA/cutlass/blob/5c447dd84f8ae0e1d48ff9a2eae26ce8c4958101/examples/cute/tutorial/sgemm_sm80.cu#L335

https://github.com/NVIDIA/cutlass/blob/5c447dd84f8ae0e1d48ff9a2eae26ce8c4958101/examples/cute/tutorial/sgemm_sm70.cu#L297

**Comment by thakkarV** [comment]
That's right, but you should be able to swap them for any other atom from that arch and it should just work
