### ISSUE TITLE
[BUG] cutlass::half_t 's max value seems to be 2048

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#1521]
**Describe the bug**
I am using `cutlass::reference::host::BlockFillSequential(matrix.host_data(), matrix.capacity());` to fill my tensor `matrix`. However, I find that when `matrix.capacity()` is larger than `2047`, for these data whose index is after `2047`, their values are all `2048`.

And here is the code of `cutlass::reference::host::BlockFillSequential`:

```
template <
  typename Element
>
void BlockFillSequential(
  Element *ptr,
  int64_t capacity,
  Element v = Element(1),
  Element s = Element(0)) {
  int i = 0;

  while (i < capacity) {
    cutlass::ReferenceFactory<Element, (cutlass::sizeof_bits<Element>::value <
                                        8)>::get(ptr, i) = s;

    s = Element(s + v);
    ++i;
  }
}
```

**Steps/Code to reproduce bug**
I try to reproduce the bug using this simple code:

```
#include "cutlass/half.h"
#include <iostream>

int main(int argc, char const *argv[])
{
  cutlass::half_t s = cutlass::half_t(2047);
  cutlass::half_t v = cutlass::half_t(1);
  s = cutlass::half_t(s + v);
  std::cout << s << std::endl;
  s = cutlass::half_t(s + v);
  std::cout << s << std::endl;
  s = cutlass::half_t(s + v);
  std::cout << s << std::endl;
  return 0;
}
```

**Expected behavior**
By using `nvcc ./test.cu -I path-to-cutlass/include` and `./a.out`, you will get
`
2048
2048
2048
`

**Comment by jackkosaian** [comment]
What you're experiencing is the result of the floating-point numeric representation. A floating-point value can only express a limited set of values. 2049 cannot be represented in FP16: you can try entering it in [here](https://evanw.github.io/float-toy/). Thus, in your example, 2048 + 1 always equals 2048.

You can replicate this same behavior using `torch.float16`:
```
>>> x = torch.tensor([2047.], dtype=torch.float16)
>>> y = torch.tensor([1.], dtype=torch.float16)
>>> x+y
tensor([2048.], dtype=torch.float16)
>>> x+y+y
tensor([2048.], dtype=torch.float16)
>>> x+y+y+y
tensor([2048.], dtype=torch.float16)
```
