### ISSUE TITLE
[DOC] Atom SM90_64x128x16_F16F16F16F16_TN

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1522]
In the `0t_mma_atom.md` doc it refers to the `SM90_64x128x16_F16F16F16F16_TN` atom, but grepping through the codebase, this is the only time that string appears. I wonder if the atom got renamed.

**Comment by ccecka** [comment]
Looks like this was renamed to `SM90_64x128x16_F16F16F16_SS<transposeA, transposeB>` without updating the documentation. We'll get that fixed, thanks
