### ISSUE TITLE
[QST] Understanding the layouts around tensor core ops

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1524]
Where can I learn more about the rationale of the layouts of tensor core operations? For instance, `SM70_8x8x4_F32F16F16F32_NT` has thread layout
```C++
SM70_QuadPair = Layout<Shape <_4, _2>,
                             Stride<_1,_16>>;
```
and thread value layout for C
```C++
SM70_8x8_32b  = Layout<Shape <Shape <_2, _2,_2>,Shape <_2,_2, _2>>,
                             Stride<Stride<_1,_16,_4>,Stride<_8,_2,_32>>>;
```
I think I understand the "how" but not the "why". Maybe part of the answer is that it's a hardware design choice that I the programmer don't need to understand?

**Comment by thakkarV** [comment]
The MMA traits are our fundamental truths of the hardware architecture and beyond the control of a software programmer. You can think of them as the transcription of the PTX ISA documentation. The "why" behind the way they are is a function of micro architecture design tradeoff made for that architecture at the time. Arch tradeoffs are not something we can discuss on GitHub unfortunately.
