### ISSUE TITLE
[QST] Is it possible to compose two `Swizzle`s with different shift bits?

### ISSUE THREAD

**Issue by armbuster** [NVIDIA/cutlass#1531]
**What is your question?**

I would like to store data in shared memory according to the layout described by `composition(Swizzle<3,0,3>{}, Swizzle<1,2,1>{});` This composition does not compile because of [this](https://github.com/NVIDIA/cutlass/blob/033d9efd2db0bbbcf3b3b0650acde6c472f3948e/include/cute/swizzle.hpp#L127) static assertion which only allows composition between two `Swizzle`s with the same shift.

I spent a while with pencil and paper, and I don't think I can create the layout I want with only 1 `Swizzle`. Do you have any suggestions for what to do?

**Comment by ccecka** [comment]
Cool question, I think I encountered something like this once upon a time as well and considered generalizing the swizzle representation. The current `Swizzle` cannot represent this function.

In principle it's possible, but I just had to draw the line somewhere. I imagine that you could define your own swizzle function (perhaps as the functional composition of two existing ones) and get a layout evaluation working via the generic `ComposedLayout`, it just wouldn't have all of the optimizations (analysis and decay) that normal swizzle layouts have. But at least you could evaluate it and detect its existence.

**Comment by armbuster** [comment]
thanks!!
