### ISSUE TITLE
[QST] Row major for int8 matrix multiplications?

### ISSUE THREAD

**Issue by hychiang-git** [NVIDIA/cutlass#1533]
**What is your question?**
As I read the document and the examples, the configurations I found for int8 x int8=int8 matrix multiplication is either RowMajor x ColumnMajor = ColumnMajor ([gemm_s8t_s8n_s8n](https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/gemm_s8t_s8n_s8n_tensor_op_s32_sm80.cu)) or RowMajor x ColumnMajor = RowMajor ([gemm_s8t_s8n_s8t](https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/gemm_s8t_s8n_s8t_tensor_op_s32_sm80.cu)).

Is there any work around for the use case for RowMajor x RowMajor= RowMajor? 
Suppose I have matrices shapes: [M K] x [K N] = [M N] and I hope not to perform transpose that involves memory copy.
```
  using ElementInputA = int8_t; // <- data type of elements in matrix A
  using ElementInputB = int8_t; // <- data type of elements in matrix B
  using ElementAccumulator = int32_t;
  using ElementOutput = int8_t;

  using LayoutInputA = cutlass::layout::RowMajor; //  A [M K]
  using LayoutInputB = cutlass::layout::RowMajor; //  B [K N]
  using LayoutOutput = cutlass::layout::RowMajor; // C [M N]
```

**Comment by IonThruster** [comment]
It's possible to do Row x Row - but not as performant, since we need to transpose in the fly. @hwu36
