### ISSUE TITLE
close

### ISSUE THREAD

**Issue by Jellards** [NVIDIA/cutlass#1541]

**Comment by Jellards** [comment]
> **What is your question?**
> 
> 1. copy v3.5.0 cutlass/include as a thirdparty;
> 2. modify cmakefile cutlass as a interface library
> 
> add_library(cutlass INTERFACE) target_compile_features(cutlass INTERFACE cxx_std_17) target_include_directories( cutlass INTERFACE " <BUILD_INTERFACE:{CMAKE_CURRENT_LIST_DIR}/../thirdparty/cutlass/v3_5_0/include>)" // for render target_link_libraries(hars INTERFACE cutlass) endif()
> 
> 3.build with vs2022，errors below:
> 
> D:\code\hars\thirdparty\cutlass\v3_5_0\include\cutlass/float8.h(521): error : "half" is ambiguous 1> operator half() const { 1> ^ 1> 1>D:\code\hars\thirdparty\cutlass\v3_5_0\include\cutlass/float8.h(730): error : "half" is ambiguous 1> operator half() const { 1> ^ 1> 1>D:\code\hars\thirdparty\cutlass\v3_5_0\include\cutlass/half.h(420): error : "half" is ambiguous 1> half_t & operator=(half const &x) { 1> ^ 1> 1>D:\code\hars\thirdparty\cutlass\v3_5_0\include\cutlass/half.h(456): error : "half" is ambiguous 1> half to_half() const { 1> ^ 1> 1>D:\code\hars\thirdparty\cutlass\v3_5_0\include\cutlass/half.h(462): error : "half" is ambiguous 1> return half(raw); 1> ^
> 
> Anyone know what the reason is?

Is nvcc compile cause this? header library defaultly use msbuild compiler，not nvcc( .cu files). I need to set some options to use nvcc to compile the header library? how?

**Comment by thakkarV** [comment]
@d-k-b

**Comment by d-k-b** [comment]
Can you provide some details about the library/application you are linking cutlass with? Does it include CUDA language support already, for instance? Does it compile other `.cu` files successfully?

**Comment by Jellards** [comment]
> Can you provide some details about the library/application you are linking cutlass with? Does it include CUDA language support already, for instance? Does it compile other `.cu` files successfully?

1)Yes, include cuda config, see below;
if (USE_CUDA)
enable_language(CUDA)
set_target_properties(hars PROPERTIES CUDA_ARCHITECTURES native)
if(MSVC)
set_target_properties(hars PROPERTIES COMPILE_OPTIONS -Xcompiler)
endif()
2) Yes, compile successfully,see below:
if ((batch >= param.b_inout) || (out_c >= param.c_out) || 
    (out_c >= param.c_out) || (out_h >= param.h_out)) return;
const int TILE_SIZE = WMMA_M * WMMA_K;
const int warpM = out_w / warpSize;

wmma::fragment<wmma::matrix_a, WMMA_M, WMMA_N, WMMA_K, __half, wmma::row_major> a_frag;
wmma::fragment<wmma::matrix_b, WMMA_M, WMMA_N, WMMA_K, __half, wmma::row_major> b_frag;
wmma::fragment<wmma::accumulator, WMMA_M, WMMA_N, WMMA_K, __half> c_frag;

wmma::load_matrix_sync(c_frag, bias + out_c * TILE_SIZE, WMMA_N, wmma::mem_row_major);

const int offset = batch * param.b_stride_in + out_h * param.h_stride_in + warpM * TILE_SIZE;
for (int in_c = 0; in_c < param.c_in; in_c++) {
    const int input_offset = offset + in_c * param.c_stride_in;
    const int weight_offset = (in_c + out_c * param.c_in) * TILE_SIZE;
    wmma::load_matrix_sync(a_frag, input + input_offset, WMMA_K);
    wmma::load_matrix_sync(b_frag, weight + weight_offset, WMMA_N);
    wmma::mma_sync(c_frag, a_frag, b_frag, c_frag);
}

const int output_offset =
    batch * param.b_stride_out + out_c * param.c_stride_out + out_h * param.h_stride_out + warpM * TILE_SIZE;
wmma::store_matrix_sync(output + output_offset, c_frag, WMMA_N, wmma::mem_row_major);

**Comment by Jellards** [comment]
include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): error : expression must have a constant value
include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): note #2703-D: cannot call non-constexpr function "cutlass::const_min"
include\cutlass/fast_math.h(740): here
detected during:
1>            instantiation of class "cutlass::gemm::threadblock::DefaultMmaCore<Shape_, WarpShape_, cutlass::gemm::GemmShape<1, 1, 1>, ElementA_, cutlass::layout::RowMajor, ElementB_, cutlass::layout::RowMajor, ElementC_, LayoutC_, cutlass::arch::OpClassSimt, 2, Operator_, false, cutlass::arch::CacheOperation::Global, cutlass::arch::CacheOperation::Global, cutlass::ComplexTransform::kNone, cutlass::ComplexTransform::kNone, false> [with Shape_=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape_=cutlass::gemm::GemmShape<32, 64, 8>, ElementA_=float, ElementB_=float, ElementC_=float, LayoutC_=cutlass::layout::RowMajor, Operator_=cutlass::arch::OpMultiplyAdd]"
include\cutlass/gemm/threadblock/default_mma.h(170): here
1>            instantiation of class "cutlass::gemm::threadblock::DefaultMma<ElementA, LayoutA, kAlignmentA, ElementB, LayoutB, kAlignmentB, ElementAccumulator, LayoutC, cutlass::arch::OpClassSimt, ArchTag, ThreadblockShape, WarpShape, InstructionShape, 2, Operator, false, cutlass::gemm::SharedMemoryClearOption::kNone, GatherA, GatherB, PermuteALayout, PermuteBLayout> [with ElementA=float, LayoutA=cutlass::layout::RowMajor, kAlignmentA=1, ElementB=float, LayoutB=cutlass::layout::RowMajor, kAlignmentB=1, ElementAccumulator=float, LayoutC=cutlass::layout::RowMajor, ArchTag=cutlass::arch::Sm50, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape=cutlass::gemm::GemmShape<32, 64, 8>, InstructionShape=cutlass::gemm::GemmShape<1, 1, 1>, Operator=cutlass::arch::OpMultiplyAdd, GatherA=false, GatherB=false, PermuteALayout=cutlass::layout::NoPermute, PermuteBLayout=cutlass::layout::NoPermute]"

**Comment by Jellards** [comment]
> include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): error : expression must have a constant value include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): note #2703-D: cannot call non-constexpr function "cutlass::const_min" include\cutlass/fast_math.h(740): here detected during: 1> instantiation of class "cutlass::gemm::threadblock::DefaultMmaCore<Shape_, WarpShape_, cutlass::gemm::GemmShape<1, 1, 1>, ElementA_, cutlass::layout::RowMajor, ElementB_, cutlass::layout::RowMajor, ElementC_, LayoutC_, cutlass::arch::OpClassSimt, 2, Operator_, false, cutlass::arch::CacheOperation::Global, cutlass::arch::CacheOperation::Global, cutlass::ComplexTransform::kNone, cutlass::ComplexTransform::kNone, false> [with Shape_=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape_=cutlass::gemm::GemmShape<32, 64, 8>, ElementA_=float, ElementB_=float, ElementC_=float, LayoutC_=cutlass::layout::RowMajor, Operator_=cutlass::arch::OpMultiplyAdd]" include\cutlass/gemm/threadblock/default_mma.h(170): here 1> instantiation of class "cutlass::gemm::threadblock::DefaultMma<ElementA, LayoutA, kAlignmentA, ElementB, LayoutB, kAlignmentB, ElementAccumulator, LayoutC, cutlass::arch::OpClassSimt, ArchTag, ThreadblockShape, WarpShape, InstructionShape, 2, Operator, false, cutlass::gemm::SharedMemoryClearOption::kNone, GatherA, GatherB, PermuteALayout, PermuteBLayout> [with ElementA=float, LayoutA=cutlass::layout::RowMajor, kAlignmentA=1, ElementB=float, LayoutB=cutlass::layout::RowMajor, kAlignmentB=1, ElementAccumulator=float, LayoutC=cutlass::layout::RowMajor, ArchTag=cutlass::arch::Sm50, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape=cutlass::gemm::GemmShape<32, 64, 8>, InstructionShape=cutlass::gemm::GemmShape<1, 1, 1>, Operator=cutlass::arch::OpMultiplyAdd, GatherA=false, GatherB=false, PermuteALayout=cutlass::layout::NoPermute, PermuteBLayout=cutlass::layout::NoPermute]"

@thakkarV @d-k-b Any idea?

**Comment by Jellards** [comment]
> build error log:
> 
> > include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): error : expression must have a constant value include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): note #2703-D: cannot call non-constexpr function "cutlass::const_min" include\cutlass/fast_math.h(740): here detected during: 1> instantiation of class "cutlass::gemm::threadblock::DefaultMmaCore<Shape_, WarpShape_, cutlass::gemm::GemmShape<1, 1, 1>, ElementA_, cutlass::layout::RowMajor, ElementB_, cutlass::layout::RowMajor, ElementC_, LayoutC_, cutlass::arch::OpClassSimt, 2, Operator_, false, cutlass::arch::CacheOperation::Global, cutlass::arch::CacheOperation::Global, cutlass::ComplexTransform::kNone, cutlass::ComplexTransform::kNone, false> [with Shape_=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape_=cutlass::gemm::GemmShape<32, 64, 8>, ElementA_=float, ElementB_=float, ElementC_=float, LayoutC_=cutlass::layout::RowMajor, Operator_=cutlass::arch::OpMultiplyAdd]" include\cutlass/gemm/threadblock/default_mma.h(170): here 1> instantiation of class "cutlass::gemm::threadblock::DefaultMma<ElementA, LayoutA, kAlignmentA, ElementB, LayoutB, kAlignmentB, ElementAccumulator, LayoutC, cutlass::arch::OpClassSimt, ArchTag, ThreadblockShape, WarpShape, InstructionShape, 2, Operator, false, cutlass::gemm::SharedMemoryClearOption::kNone, GatherA, GatherB, PermuteALayout, PermuteBLayout> [with ElementA=float, LayoutA=cutlass::layout::RowMajor, kAlignmentA=1, ElementB=float, LayoutB=cutlass::layout::RowMajor, kAlignmentB=1, ElementAccumulator=float, LayoutC=cutlass::layout::RowMajor, ArchTag=cutlass::arch::Sm50, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape=cutlass::gemm::GemmShape<32, 64, 8>, InstructionShape=cutlass::gemm::GemmShape<1, 1, 1>, Operator=cutlass::arch::OpMultiplyAdd, GatherA=false, GatherB=false, PermuteALayout=cutlass::layout::NoPermute, PermuteBLayout=cutlass::layout::NoPermute]"
> 
> @thakkarV @d-k-b Any idea?

When I  set /Zc:__cplusplus flags， nvcc compile error  :
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

**Comment by Jellards** [comment]
> > build error log:
> > > include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): error : expression must have a constant value include\cutlass/gemm/threadblock/default_mma_core_simt.h(533): note #2703-D: cannot call non-constexpr function "cutlass::const_min" include\cutlass/fast_math.h(740): here detected during: 1> instantiation of class "cutlass::gemm::threadblock::DefaultMmaCore<Shape_, WarpShape_, cutlass::gemm::GemmShape<1, 1, 1>, ElementA_, cutlass::layout::RowMajor, ElementB_, cutlass::layout::RowMajor, ElementC_, LayoutC_, cutlass::arch::OpClassSimt, 2, Operator_, false, cutlass::arch::CacheOperation::Global, cutlass::arch::CacheOperation::Global, cutlass::ComplexTransform::kNone, cutlass::ComplexTransform::kNone, false> [with Shape_=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape_=cutlass::gemm::GemmShape<32, 64, 8>, ElementA_=float, ElementB_=float, ElementC_=float, LayoutC_=cutlass::layout::RowMajor, Operator_=cutlass::arch::OpMultiplyAdd]" include\cutlass/gemm/threadblock/default_mma.h(170): here 1> instantiation of class "cutlass::gemm::threadblock::DefaultMma<ElementA, LayoutA, kAlignmentA, ElementB, LayoutB, kAlignmentB, ElementAccumulator, LayoutC, cutlass::arch::OpClassSimt, ArchTag, ThreadblockShape, WarpShape, InstructionShape, 2, Operator, false, cutlass::gemm::SharedMemoryClearOption::kNone, GatherA, GatherB, PermuteALayout, PermuteBLayout> [with ElementA=float, LayoutA=cutlass::layout::RowMajor, kAlignmentA=1, ElementB=float, LayoutB=cutlass::layout::RowMajor, kAlignmentB=1, ElementAccumulator=float, LayoutC=cutlass::layout::RowMajor, ArchTag=cutlass::arch::Sm50, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 8>, WarpShape=cutlass::gemm::GemmShape<32, 64, 8>, InstructionShape=cutlass::gemm::GemmShape<1, 1, 1>, Operator=cutlass::arch::OpMultiplyAdd, GatherA=false, GatherB=false, PermuteALayout=cutlass::layout::NoPermute, PermuteBLayout=cutlass::layout::NoPermute]"
> > 
> > 
> > @thakkarV @d-k-b Any idea?
> 
> When I set /Zc:__cplusplus flags，the same error. ![image](https://private-user-images.githubusercontent.com/38233498/332701141-e855a105-7fab-442f-b00b-e67f4c1a3e1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM0NTEsIm5iZiI6MTcxNjM2MzE1MSwicGF0aCI6Ii8zODIzMzQ5OC8zMzI3MDExNDEtZTg1NWExMDUtN2ZhYi00NDJmLWIwMGItZTY3ZjRjMWEzZTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MzIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjY2I2NzBkZjVjNDU1ZGVkYzQzNWI4ZjM5NmEyMmE0NDZkZTBhMTk3NDAyYjI5YzRlYmM5ODIxY2Y5NjI5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LAJDQlP9OqC9xND1V_ykwpwX3w4343wXcA1Lwv5KG_4)

**Comment by Jellards** [comment]
typename GemmBatchedCuda_F32_F32_Linear_AlignCuda_Row_Row_Sm86::Arguments arguments{
     problem_size,
     {(float *)weight->DevicePtr(), C},
     (int64_t)(0),
     {(float *)input->DevicePtr(), H * W},
     (int64_t)(C * H * W),
     {(float *)bias->DevicePtr(), H * W},
     (int64_t)(0),
     {(float *)output->DevicePtr(), H * W},
     (int64_t)(N * H * W),
     {1.f},
     B};

weight（layout NC rowmajor）,input(layout CHW rowmajor), output(layout NHW rowmajor)，bias(layout N rowmajor)
weight x input = NHW rowmajor, how to add bias to NHW rowmajor

@thakkarV
