### ISSUE TITLE
[QST] In a TiledMMA, why can't C and D be in smem?

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1548]
A conceptual question: I notice that there are no overloads for `cute::gemm` where all of A, B, C, D are in smem. Why not? On the surface it seems to me that a `TiledMMA` has (maybe only sometimes) all the information it needs to figure out how the accumulator registers should be handled. But C and D are always assumed to be in rmem, iiuc.

**Comment by thakkarV** [comment]
They totally can be in smem. You can partition and consume an smem tensor for C and D just fine. It's just not a common usecase.

**Comment by ccecka** [comment]
No, @thakkarV, the `cute::gemm` overloads for smem allocate rmem fragments and perform copies. These overloads only occur for A and B at the moment. Could always add C and D smem overloads to `cute::gemm` that would also allocate fragments for the accumulators and copy from rmem to partitioned smem at the end of the accumulation. In general, I'm not a fan of those partitioned smem overloads anyway...

See `cooperative_gemm` for a gemm that actually takes full shared tiles of smem for A, B, and C and performs the partitioning within for each. Perhaps that fits your use case better.

**Comment by ericauld** [comment]
Thanks @ccecka, that's helpful context. I don't prefer the smem overloads myself, I was just curious.

**Comment by thakkarV** [comment]
@ccecka Right I was making a comment that there's no fundamental reason why that's not possible. Cooperative GEMM is what @ericauld seems to be looking for though
