### ISSUE TITLE
[BUG] print_layout seems to change the swizzle mode of its input

### ISSUE THREAD

**Issue by rawnhenry** [NVIDIA/cutlass#1559]
**Describe the bug**
When printing a layout with `print(layout)`, I see description `Sw<3,4,3> o smem_ptr[16b](unset) o (_8,_64):(_64,_1)`. However, when printing with `print_layout(layout)`, the description is `Sw<3,3,3> o _0 o (_8,_64):(_64,_1)`. 

It isn't clear why the swizzles would be different depending on how the layout is printed. I was expecting to see a `Sw<3,4,3>` regardless of the method used to print.

**Steps/Code to reproduce bug**
Copy the snippet below and place it in a file inside the cutlass folder called `test.cu`. Compile using `nvcc test.cu -o test.exe -I./include -std=c++17`

The SHA `39c6a83f231d6db2bc6b9c251e7add77d68cbfb4` prints `Sw<3,4,3>` in print_layout. However, tot (`637b15906358191cb4238af419d408a65819d7ec`) prints `Sw<3,3,3>` inside `print_layout`.

```
#include "include/cute/layout.hpp"
#include "include/cute/tensor.hpp"

using namespace cute;


int main() {

  using smem_atom = GMMA::Layout_K_SW128_Atom<cute::half_t>;
  auto atom = smem_atom{};

  printf("\n");
  print(atom);
  printf("\n");
  print_layout(atom);
  printf("\n");

  return 0;
}
```

**Expected behavior**
I expect the descriptions of `print(layout)` and `print_layout(layout)` to match.

**Comment by thakkarV** [comment]
@ccecka former seems to be printing the layout as a PD swizzle, and the latter as a PID swizzle

**Comment by ccecka** [comment]
Yes, printing an unbound PDSL converts it to a PISL for printing.

If a PDSL is unbound to a pointer, we assume it will be bound to a fully aligned pointer and only then can the equivalent PISL offsets be printed.

**Comment by rawn-openai** [comment]
OK, that makes a lot of sense. I have a follow up question here. I have some code like:

```
  using SmemLayoutA = typename Gemm::GemmKernel::CollectiveMainloop::SmemLayoutA;
  printf("\n");
  print(SmemLayoutA{});
  printf("\n");
  auto layout = SmemLayoutA{}(_,_,cute::Int<0>{});
  print(layout);
```

This prints:
```
Sw<3,4,3> o smem_ptr[16b](unset) o (_128,_64,_7):(_64,_1,_8192)
Sw<3,4,3> o _0 o (_128,_64):(_64,_1)
```

Why does the slice give what appears to be a PID swizzle?

I was expected us to propagate the fact that we have an unbound 16b smem pointer through the slice. Why is that assumption wrong?

**Comment by rawnhenry** [comment]
OK, that makes a lot of sense. I have a follow up question here. I have some code like:

```
  using SmemLayoutA = typename Gemm::GemmKernel::CollectiveMainloop::SmemLayoutA;
  printf("\n");
  print(SmemLayoutA{});
  printf("\n");
  auto layout = SmemLayoutA{}(_,_,cute::Int<0>{});
  print(layout);
```

This prints:
```
Sw<3,4,3> o smem_ptr[16b](unset) o (_128,_64,_7):(_64,_1,_8192)
Sw<3,4,3> o _0 o (_128,_64):(_64,_1)
```

Why does the slice give what appears to be a PID swizzle?

I was expected us to propagate the fact that we have an unbound 16b smem pointer through the slice. Why is that assumption wrong?

**Comment by rawnhenry** [comment]
Ok, that makes sense too. Thank you for the help!
