### ISSUE TITLE
OutputTileShape 

### ISSUE THREAD

**Issue by haibo91** [NVIDIA/cutlass#156]
why would layout be divided into 4 dimensions in the epilogue phase?

**Comment by kerrmudgeon** [comment]
The structure of the accumulator fragments varies between the so-called "SIMT" GEMM kernels (e.g. SGEMM and DGEMM), Volta Tensor Cores, and Tensor Cores for NVIDIA Turing and NVIDIA Ampere architectures. We needed a 5-d iteration space to be sufficiently generate to cover all arrangements and vector lengths.
