### ISSUE TITLE
Warp Group MMA vs Warp MMA

### ISSUE THREAD

**Issue by OrenLeung** [NVIDIA/cutlass#1560]
why do warp group MMA have higher performance than warp mma?

since each warp has its own independent scheduler, how does all 4 warps within an SM doing a "group" mma make it faster?
![image](https://github.com/NVIDIA/cutlass/assets/47992694/ff2f29d5-7bd3-4f0a-8bc5-853ec247e252)

**Comment by thakkarV** [comment]
Unfortunately the answer to this question is beyond the scope of what we can discuss in a public forum.
