### ISSUE TITLE
[QST] (BUG?)The stride of TensorNCxHWx seems to be confusing  when C is smaller than Interleave

### ISSUE THREAD

**Issue by gujiewen** [NVIDIA/cutlass#1562]
In https://github.com/NVIDIA/cutlass/blob/637b15906358191cb4238af419d408a65819d7ec/include/cutlass/layout/tensor.h#L367
the stride of  TensorNCxHWx was computed with
```
  static TensorNCxHWx packed(TensorCoord const &extent) {
    return TensorNCxHWx(
      make_Coord(
        kInterleave * extent.w(),
        kInterleave * extent.w() * extent.h(),
        extent.h() * extent.w() * extent.c()
      )
    );
  }
```
Howerver, when c is smaller than Interleave (for example, n == 2, c == 16, h == 3, w == 3, and TensorNCxHWx<32>), based on the above code, it seems to be TensorNCxHWx<16> but not 32.  Another world, no padding when c is smaller than interleave. 
Is it  by design, or is it a bug? 
Maybe this will be better?
```
// extent.h() * extent.w() * extent.c()
kInterleave * extent.w() * extent.h() * ((extent.c() + kInterleave - 1) / kInterleave)
```
```[tasklist]
### Tasks
```

**Comment by gujiewen** [comment]
Stil waiting for an answer

**Comment by thakkarV** [comment]
@hwu36 do you know who would know?

**Comment by hwu36** [comment]
C is supposed to be multiple of interleave. We can add an assert if there is none.  We have it in can_implement in the device level.

**Comment by gujiewen** [comment]
> C is supposed to be multiple of interleave. We can add an assert if there is none. We have it in can_implement in the device level.

Got it. Thanks.
