### ISSUE TITLE
[FEA] Add cuTensorMapEncodeTiled to CudaHostAdapter

### ISSUE THREAD

**Issue by drisspg** [NVIDIA/cutlass#1566]
# Summary
We are currently working on integrating a fp8 scaled matmul kernel written using Cutlass into PyTorch. PyTorch has the constraint that it can be linked against the cuda driver api. There is one symbol/direct call to a cuda driver api `cuTensorMapEncodeTiled` that is causing issues. 

We have a temporary workaround here: https://github.com/pytorch/pytorch/pull/125204#discussion_r1618787335

There was a suggestion to add this symbol to CudaHostAdapter so as to add one more layer of indirection. This would greatly aid in PyTorch in its utilization of Cutlass.

**Comment by hwu36** [comment]
@kerrmudgeon

**Comment by drisspg** [comment]
Curious if there is any update here?

**Comment by thakkarV** [comment]
3.5.1 will ship with this before end of week

**Comment by thakkarV** [comment]
@drisspg please verify and close? I think this is done, but follow up work is required in https://github.com/NVIDIA/cutlass/issues/1624?

**Comment by thakkarV** [comment]
Closing as done with #1700
