### ISSUE TITLE
[QST] CUTLASS kernels appear to be significantly slower than CuBLAS for an fp16 gemm on `sm_75`

### ISSUE THREAD

**Issue by armbuster** [NVIDIA/cutlass#1567]
**What is your question?**
I want to compare the performance of CUTLASS kernels to `cublasHgemm`, which gives me ~50,000 GFLOP/s on a T4 card, with m,n,k = 4096,4096, 4096.

I have tried passing various wildcard to the `--kernel` argument of the cutlass profiler to try to select the right kernel, but cannot find one that achieves comparable performance to `cublasHgemm`. Basically I want a `TensorOp` kernel with data type `f16 * f16 + f16 => f16`, what should I pass to the profiler to benchmark all kernels of this type?

**Comment by thakkarV** [comment]
the only options you should need are the following:

```
  [enum]      --gemm_kind                                       Variant of GEMM (e.g. universal, gemm, planar_complex, planar_complex_array)
  [int]       --m,--problem-size::m                             M dimension of the GEMM problem space
  [int]       --n,--problem-size::n                             N dimension of the GEMM problem space
  [int]       --k,--problem-size::k                             K dimension of the GEMM problem space
  [tensor]    --A                                               Tensor storing the A operand
  [tensor]    --B                                               Tensor storing the B operand
  [tensor]    --C                                               Tensor storing the C operand
  ```
  
  so something like `./cutlass_profiler --operation=Gemm --A=f16:column --B=f16:row --C:f16:column`
  
  read more here: https://github.com/NVIDIA/cutlass/blob/main/media/docs/profiler.md

**Comment by armbuster** [comment]
thanks vijay!! I tried that, and the fastest kernel I could find is `cutlass_simt_hgemm_256x128_8x2_tt_align1` which achieves ~36,000 GFLOP/s, short of `cublasHgemm` ~50,000 GFLOP/s .

Just to confirm, I should expect comparable performance to cublas? If so, I guess this would mean I did something wrong when buliding CUTLASS, like perhaps excluding the kernel I am looking for from the build by mistake?

**Comment by thakkarV** [comment]
this depends on the problem shape, tile size, load balancing, your compiler version, and a few other factors. In general, the best kernel out of CUTLASS compiled with an up to date CUDA toolkit should not be too far off from cuBLAS

**Comment by armbuster** [comment]
thanks!!
