### ISSUE TITLE
[QST] Equality of shapes

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1568]
Hi, I was going through the example `sgemm_sm80.cu` and was wondering about the static assert

```c++
CUTE_STATIC_ASSERT_V(  shape(tCrA) ==   shape(tCsA));                // (MMA,MMA_M,MMA_K)
```

so I added some print statements and got

```text
tCsA : smem_ptr[32b](…) o (_1,_8,_8,_3):(_0,_16,_128,_1024)
tCrA : ptr[32b](…) o (_1,_8,_8):(_0,_1,_8)

shape(tCrA) : (_1,_8,_8)
shape(tCsA) : (_1,_8,_8,_3)
shape(tCrA) == shape(tCsA) : _1
```

Is this expected? Thanks

**Comment by ccecka** [comment]
Thanks for pointing that out, looks like a holdover from implementing lex and colex comparisons with short-circuits. But `==` needs to be symmetric -- doesn't look like this behavior is actually used in many places, but I'll get this fixed.

**Comment by ericauld** [comment]
Sounds good, if you feel it's appropriate I'd be happy to fix it myself, otherwise maybe I can look for a more suitable issue where I can contribute.
