### ISSUE TITLE
Cleanup compiler warnings

### ISSUE THREAD

**Issue by igormp** [NVIDIA/cutlass#157]
Opening this issue to keep track of the progress with this issue as discussed in #151 

>So, I think we'd love to have pull request(s) fixing the warnings first and a final pull request to add -Wall -Werror to CMake.

I'll try to work on it this week (finally got a new CPU that doesn't need 2 hours+ to compile the project) if nobody else snatches this issue first :slightly_smiling_face:

**Comment by hwu36** [comment]
Thank you very much for attacking this important issue, @igormp .

I think you don't need to build the whole project which takes long time.  You can start with

`make cutlass_test_unit_gemm_device`
 
and/or

`make cutlass_test_unit_conv_device`

**Comment by d-k-b** [comment]
Thanks, @igormp, for helping out! Please let us know which compilers you are using, as we'll likely need to guard the application of -Wall -Werror with a range of known-good compilers so we don't break builds on other versions.

**Comment by igormp** [comment]
> I think you don't need to build the whole project which takes long time. You can start with

Thanks for the tip, but currently it takes around 5 minutes to build everything, so it isn't much of a hassle anymore.

> Thanks, @igormp, for helping out! Please let us know which compilers you are using, as we'll likely need to guard the application of -Wall -Werror with a range of known-good compilers so we don't break builds on other versions.

I'll try to give better details when I open the PR, but I'm currently doing everything using GCC 10.2.0 and nvcc release 11.2, V11.2.67

**Comment by hwu36** [comment]
Your compiler looks good.

**Comment by d-k-b** [comment]
@igormp, CUTLASS 2.5 introduced `CUTLASS_UNUSED()` and `CUTLASS_NOT_IMPLEMENTED()`.

https://github.com/NVIDIA/cutlass/blob/8f09b82b12cbea6943d54fd4f66c0a769b719f58/include/cutlass/cutlass.h#L34-40

```
#define CUTLASS_UNUSED(expr) do { (void)(expr); } while (0)

#if defined(_MSC_VER)
  #define CUTLASS_NOT_IMPLEMENTED() assert(0 && __FUNCSIG__)
#else
  #define CUTLASS_NOT_IMPLEMENTED() assert(0 && __PRETTY_FUNCTION__)
#endif
```

With a sample use case in https://github.com/NVIDIA/cutlass/blob/8f09b82b12cbea6943d54fd4f66c0a769b719f58/include/cutlass/arch/memory_sm75.h#L121-127.

**Comment by mnicely** [comment]
@d-k-b Has this been closed?

**Comment by igormp** [comment]
As discussed in #162, I guess it's fair to close this issue.

Feel free to open it in case I'm wrong.
