### ISSUE TITLE
[QST] Is  there grouped_gemv

### ISSUE THREAD

**Issue by hanzz2007** [NVIDIA/cutlass#1572]
i have problem shapes(mnk): 1x512x3072 and 1x512x1029 or more,  how can i batch compute these using grouped_gemm or gourped_gemv ？

**Comment by mnicely** [comment]
[Hopper] https://github.com/NVIDIA/cutlass/tree/main/examples/57_hopper_grouped_gemm
[Ampere] https://github.com/NVIDIA/cutlass/tree/main/examples/24_gemm_grouped

**Comment by thakkarV** [comment]
There is no grouped GEMV but we have an optimized GEMV that you can customize to implemented (and contribute if you would like) a grouped GEMV
