### ISSUE TITLE
[BUG] Circular Dependency in Header Files

### ISSUE THREAD

**Issue by gavinchen430** [NVIDIA/cutlass#1576]
"cute/atom/copy_traits_sm90_tma.hpp" include "cute/algorithm/prefetch.hpp"
"cute/algorithm/prefetch.hpp" include "cute/atom/copy_atom.hpp"
 "cute/atom/copy_atom.hpp" inlcude "cute/atom/copy_traits_sm90_tma.hpp" if nvcc version is greater than 12

**Comment by thakkarV** [comment]
closed by https://github.com/NVIDIA/cutlass/pull/1623
