### ISSUE TITLE
[QST] Unknown CMake command "cutlass_example_add_executable"

### ISSUE THREAD

**Issue by soohyung-jang** [NVIDIA/cutlass#1581]
When I try to build using cmake, I get an error message 

Unknown CMake command "cutlass_example_add_executable".

My Environment
- cmake version 3.29.5
- nvcc version 12.2
- gcc version 11.4

CUDACXX is specified following guide.

**Comment by d-k-b** [comment]
Can you provide the entire cmake command and the platform/os you are building on? I did a trivial test with the versions you gave above and did not hit the same error.

**Comment by sean-jang00** [comment]
Sorry, I made a mistake in specifying the build path. I checked cmake and build are working today. Thank you.

**Comment by d-k-b** [comment]
Great, glad you got it working.
