### ISSUE TITLE
[QST] how to run profiler with fp16 accumulator for GEMM?

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/cutlass#1583]
Hi ~,

It seems to me that currently profiler only support fp32 for GEMM by default, if I want fp16 acc, how to compile those kernels with fp16 acc enabled?

Thx~

**Comment by thakkarV** [comment]
CUTLASS library generator by default doesn't stamp out these kernels. You can add them yourself by modifying the generator.py file and they should show up during profiler runs

**Comment by leiwen83** [comment]
> CUTLASS library generator by default doesn't stamp out these kernels. You can add them yourself by modifying the generator.py file and they should show up during profiler runs

@thakkarV ,

Thx for the hint, but I go throught the generator.py and find:
```
https://github.com/NVIDIA/cutlass/blob/main/python/cutlass_library/generator.py#L2332C1-L2337C1
def GenerateSM80_TensorOp_16816(manifest, cuda_version):
....
    MathInstruction(                                  \
      [16, 8, 16],                                    \
      DataType.f16, DataType.f16, DataType.f16,       \
      OpcodeClass.TensorOp,                           \
      MathOperation.multiply_add),

```

does it mean generator already support the fp16 accumulator?

**Comment by thakkarV** [comment]
Sorry, I thought you were asking about Hopper specifically. For ampere, have you tried building with `-DCUTLASS_LIBRARY_KERNELS=*sm80*` ? That should result in a profiler build with this config.

**Comment by leiwen83** [comment]
seems use below command could generate fp16 acc gemm

```
cmake ..  -DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_h*gemm*
```
