### ISSUE TITLE
Note: The main loop does not support Base::kWarpGemmIterations == 2.

### ISSUE THREAD

**Issue by haibo91** [NVIDIA/cutlass#159]
Why don't support Base: : kWarpGemmIterations = = 2 in gemm/threadblock/mma_pipelined.h ? I did the unit tests and found it was successful when Base: : kWarpGemmIterations = 2.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-48

**Comment by hwu36** [comment]
sm75 slice-k kernels can use `kWarpGemmIterations == 2`.  One example is https://gitlab-master.nvidia.com/dlarch-fastkernels/cutlass/-/blob/dev/test/unit/gemm/device/gemm_f16n_f16t_f16t_tensor_op_f16_slicedk_sm75.cu.

In these kernels, more than one warp is allocated in the k dimension, so every warp has less than normal 4 iterations to run.  They maybe useful when threadblock size is small.
