### ISSUE TITLE
[QST]What is the difference between `TensorOp` and  `WmmaTensorOp`

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/cutlass#1590]
I'm reading this documentation: https://github.com/NVIDIA/cutlass/blob/main/media/docs/functionality.md
And I see this:
```
TensorOp - Use Tensor Core MMA
SpTensorOp - Use Sparse Tensor Core MMA
WmmaTensorOp - Use WMMA abstraction to use Tensor Core MMA
```

What is the difference between `TensorOp` and  `WmmaTensorOp`?

**Comment by alexarmbr** [comment]
I dont work for NVIDIA but I can give my unofficial answer

First of all, they are two different ways to use tensor cores. Take a look at [this](https://docs.nvidia.com/cuda/parallel-thread-execution/#warp-level-matrix-multiply-accumulate-instructions). PTX provides two interfaces to tensor cores - `wmma` and `mma`. My understanding of the key difference between them is that `wmma` abstracts away the loading of matrix elements into registers in preparation for the tensor core instructions, whereas when using the `mma` API you have control over this, this control can be helpful for reducing shared memory bank conflicts if the data is coming from shared memory. The other difference is that `wmma` is part of CUDA C++ ([here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#warp-matrix-functions)), whereas if you want to use the `mma` API you need to inline the PTX into your kernel.  Basically `wmma` is more user friendly, portable, and potentially less performant, `mma` is less abstracted, gives you more fine grain control.

But I think part of why CUTLASS exists is to prevent you from having to worry about this type of distinction, so if you are choosing which kernel to run, i'd just pick the fastest!

**Comment by thakkarV** [comment]
Avoid using WMMA if you can

**Comment by ghostplant** [comment]
Hello @thakkarV, when running cutlass_profiler, I found that `*_sptensorop_*` is geneally faster than `_tensorop` when running a 4Kx4Kx4K GEMM. Why is that? Is it safe to always choose `*_sptensorop_*` to deal with a dense 4096x4096x4096 Gemm computation?

**Comment by ghostplant** [comment]
> sptensorop uses the structured sparse MMA, which is why you see it being faster

Thanks, that's reasonable if some area of GEMM inputs are sparse. But if considering a dense GEMM computation whose 2 inputs are standard without any sparse region, can "_sptensorop_" still be faster than `_tensorop_`?

**Comment by thakkarV** [comment]
Sparse GEMM forces structures sparsity. It's a totally different kernel and has implications on your workload characteristics.

**Comment by thakkarV** [comment]
right

**Comment by ghostplant** [comment]
Thank you, then looks like 860Tflops is the peak that cutlass can achieve for dense GEMM.

**Comment by thakkarV** [comment]
Yes on hopper that sounds about right.
