### ISSUE TITLE
[QST] Are the `T` and `N` in TCOs expressing performance hints?

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1592]
In operations like `SM80_16x8x8_F16F16F16F16_TN`, what exactly is the meaning of `TN`? I understand the operation has precise preconditions about which values will be in which registers. And that functions like `ThrMMA<TiledMMA<SM80_16x8x8_F16F16F16F16_TN, ...>>::partition_B(my_B)` should work no matter what the stride of `my_B` is. So is the `N` (for example) expressing something like "this TCO has been designed such that the sequence
```c++
auto tBmB = my_thr_mma.partition_B(my_B)
Tensor rB = my_thr_mma.make_fragment_B(tBmB)
copy(tBmB, rB)
```
and the reverse has been optimized for k-major layouts of `my_B`, and  is expected to perform much better in that circumstance"?

**Comment by ccecka** [comment]
Approximately, yes. 

That is technically what those those tensor cores were designed for and why are they named that way. In practice, the connection is weaker and more like how you obverse: it's simply an alternate partitioning pattern that may or may not be more advantageous for particular SMEM layouts.

**Comment by thakkarV** [comment]
> In practice, the connection is weaker and more like how you obverse:

One major caveat: this is only possible because these operations provide their inputs to the TC from registers AND threads can do arbitrary byte accesses into shared memory. TN is no longer a hint for Hopper MMAs that source their operands from smem because that is now being read by the TC directly.
