### ISSUE TITLE
Result Error for 1-bit Tensorcore on SM86

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#160]
Hi, All

I found that when I compile the following **1-bit tensorcore GEMM** for SM86 by CUDA 11.1 on RTX3090,

```
using ElementOutput = int32_t;
using ElementAccumulator = int32_t;
using ElementCompute = int32_t;

using Gemm = cutlass::gemm::device::Gemm<
      cutlass::uint1b_t, cutlass::layout::RowMajor, cutlass::uint1b_t,
      cutlass::layout::ColumnMajor, ElementOutput, cutlass::layout::RowMajor,
      ElementAccumulator, cutlass::arch::OpClassTensorOp, cutlass::arch::Sm75,
      cutlass::gemm::GemmShape<128, 256, 512>,
      cutlass::gemm::GemmShape<64, 64, 512>,
      cutlass::gemm::GemmShape<8, 8, 128>,
      cutlass::epilogue::thread::LinearCombination<
          ElementOutput, 128 / cutlass::sizeof_bits<ElementOutput>::value,
          ElementAccumulator, ElementCompute>,
      cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>, 2, 128, 128,
      false, cutlass::arch::OpXorPopc>; 
```

The output result is always wrong for the matrix with N=M=K < 8192, i.e., **Failed to pass the verification**. 
While for N=M=K >= 8192, such as 8192, 16384, it can pass the verification test.

One more thing to note is that if I choose the GEMM test example based on SM80, such as the one shown below, 
It will always trigger the cutlass internal runtime error during the GEMM initialization. While for SM75 it won't trigger such problem only has the results correctness concern. 

```
using ElementOutput = int32_t;
using ElementAccumulator = int32_t;
using ElementCompute = int32_t;

using Gemm = cutlass::gemm::device::Gemm<
    cutlass::uint1b_t, cutlass::layout::RowMajor, cutlass::uint1b_t,
    cutlass::layout::ColumnMajor, ElementOutput, cutlass::layout::ColumnMajor,
    ElementAccumulator, cutlass::arch::OpClassTensorOp, cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<128, 256, 1024>,
    cutlass::gemm::GemmShape<64, 64, 1024>,
    cutlass::gemm::GemmShape<16, 8, 256>,
    cutlass::epilogue::thread::LinearCombination<
        ElementOutput, 128 / cutlass::sizeof_bits<ElementOutput>::value,
        ElementAccumulator, ElementCompute>,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>, 3, 128, 128,
    false, cutlass::arch::OpXorPopc>;
```

**Comment by hwu36** [comment]
1. SM75 88128

I modified https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/testbed.h#L374-L383 to test 512, 1024, 2048, and 4096.  They all pass.

2. SM86 168256
SM86 (100KB) has less shared memory compared with SM80 (160KB).  Thus, 3 stage 128x256x1024 is not supported by SM86, but is supported by SM80.  You can calculate the shared memory requirement like this (128 x 1024 + 256 x 1024) x 3 / 8 = 144KB
128 - threadblock tile M
256 - threadblock tile N
1024 - threadblock tile K
3 - stage
8 - 8bits/byte

You can try 3 stage 128x128x1024.

**Comment by YukeWang96** [comment]
> 1. SM75 88128
> 
> I modified https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/testbed.h#L374-L383 to test 512, 1024, 2048, and 4096. They all pass.
> 
> 1. SM86 168256
>    SM86 (100KB) has less shared memory compared with SM80 (160KB).  Thus, 3 stage 128x256x1024 is not supported by SM86, but is supported by SM80.  You can calculate the shared memory requirement like this (128 x 1024 + 256 x 1024) x 3 / 8 = 144KB
>    128 - threadblock tile M
>    256 - threadblock tile N
>    1024 - threadblock tile K
>    3 - stage
>    8 - 8bits/byte
> 
> You can try 3 stage 128x128x1024.

Problem solved, I forget to initialize the output and reference output matrix with zeros.
