### ISSUE TITLE
[QST] How to make Main loop fusion for floats

### ISSUE THREAD

**Issue by satyabhagavan** [NVIDIA/cutlass#1602]
**What is your question?**

The mainloop fusion examples provided in [25_ampere_fprop_mainloop_fusion ](https://github.com/NVIDIA/cutlass/tree/main/examples/25_ampere_fprop_mainloop_fusion) and [26_ampere_wgrad_mainloop_fusion](https://github.com/NVIDIA/cutlass/tree/main/examples/26_ampere_wgrad_mainloop_fusion) use half-precision (float16). I want to adapt these examples to work with single-precision (float32). I changed the element types and tile shapes to support floats, but the examples are failing. To understand why, I examined the [scale_bias_relu_transform.h](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/warp/scale_bias_relu_transform.h) file. I believe changes are needed there. Could anyone guide me on how to achieve correctness with floats? Additionally, the activation function used is ReLU. Is it possible to implement the LeakyReLU activation function in the mainloop fusion? If so, how can this be done?

**Comment by thakkarV** [comment]
@hwu36

**Comment by satyabhagavan** [comment]
@hwu36 I implemented in the same way by defining leaky_alpha as float(0.1), by doing that I am getting nans at the output. Do I need to change the 'MmaElements' and 'MmaCols' in the [scale_bias_relu_transform.h](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/warp/scale_bias_relu_transform.h) file in converting to floats.

**Comment by hwu36** [comment]
Yes.  You'd better dump the value of matrix, bias, scale first to see if every thread owns the right data.  You can use 1,2,3,4... to initialize a small matrix to do that.

Mainloop fusion is the most difficult one.  If possible, you'd better do the fusion in the previous kernel epilogue, which is easier and has better performance.
