### ISSUE TITLE
[QST] cutlass fails during tensorflow assembly

### ISSUE THREAD

**Issue by zkbitcoin** [NVIDIA/cutlass#1603]
cutlass is used in building kernels in tensorflow 

I took a look in cutlass_archive/include/cutlass/matrix.h and indeed set_slice3x3 is not defined however set_slice_3x3 is

did not want to submit a bug and alarm anyone as I am new to project structure, also file matrix.h appears not to have changed 

when I modified include file to point to set_slice_3x3 compilation succeeds just fine

its really strange , in fact I searched whole project for set_slice3x3 and is nwhere to be found 

let know if you need more data from me on this, somehow I feel its not a bug.. hence question category 

ERROR: /home/a/.cache/bazel/_bazel_a/46cc6e345e09372840ba05860089f3a0/external/local_xla/xla/service/gpu/kernels/BUILD:368:13: Compiling xla/service/gpu/kernels/cutlass_gemm_kernel_bf16xbf16_to_bf16.cu.cc failed: (Exit 1): clang failed: error executing command (from target @local_xla//xla/service/gpu/kernels:cutlass_gemm_kernel_bf16xbf16_to_bf16) /usr/lib/llvm-19/bin/clang -MD -MF bazel-out/k8-opt/bin/external/local_xla/xla/service/gpu/kernels/_objs/cutlass_gemm_kernel_bf16xbf16_to_bf16/cutlass_gemm_kernel_bf16xbf16_to_bf16.cu.pic.d ... (remaining 130 arguments skipped)
In file included from external/local_xla/xla/service/gpu/kernels/cutlass_gemm_kernel_bf16xbf16_to_bf16.cu.cc:16:
In file included from external/cutlass_archive/include/cutlass/gemm/device/gemm_universal.h:43:
In file included from external/cutlass_archive/include/cutlass/gemm/threadblock/threadblock_swizzle.h:45:
In file included from external/cutlass_archive/include/cutlass/gemm/threadblock/threadblock_swizzle_streamk.h:58:
In file included from external/cutlass_archive/include/cutlass/core_io.h:51:
external/cutlass_archive/include/cutlass/matrix.h:7848:7: error: no member named 'set_slice3x3' in 'Matrix<type-parameter-0-0, 3, 3>'; did you mean 'set_slice_3x3'?
 7848 |     m.set_slice3x3({
      |       ^
external/cutlass_archive/include/cutlass/matrix.h:7150:12: note: 'set_slice_3x3' declared here
 7150 |   Matrix & set_slice_3x3(Matrix<Element, 3, 3> const &m, int i = 0, int j = 0) {
      |            ^
external/cutlass_archive/include/cutlass/matrix.h:14008:7: error: no member named 'set_slice3x3' in 'Matrix<type-parameter-0-0, 4, 4>'; did you mean 'set_slice_3x3'?
 14008 |     m.set_slice3x3({
       |       ^
external/cutlass_archive/include/cutlass/matrix.h:12862:12: note: 'set_slice_3x3' declared here
 12862 |   Matrix & set_slice_3x3(Matrix<Element, 3, 3> const &m, int i = 0, int j = 0) {
       |            ^
external/cutlass_archive/include/cutlass/matrix.h:14028:7: error: no member named 'set_slice3x3' in 'Matrix<type-parameter-0-0, 4, 4>'; did you mean 'set_slice_3x3'?
 14028 |     m.set_slice3x3({
       |       ^
external/cutlass_archive/include/cutlass/matrix.h:12862:12: note: 'set_slice_3x3' declared here
 12862 |   Matrix & set_slice_3x3(Matrix<Element, 3, 3> const &m, int i = 0, int j = 0) {
       |            ^
3 errors generated when compiling for sm_60.
Target //tensorflow/tools/pip_package:wheel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 24.995s, Critical Path: 8.74s
INFO: 21 processes: 16 internal, 5 local.
FAILED: Build did NOT complete successfully

**Comment by zkbitcoin** [comment]
checking xla package next, could be they misspelled method name in their project but how did it pass standard build checks ?

**Comment by thakkarV** [comment]
This doesn't seem to be CUTLASS but at a glance

**Comment by zkbitcoin** [comment]
> external/cutlass_archive/include/cutlass/matrix.h

well, external/cutlass_archive/include/cutlass/matrix.h is where set_slice3x3 is unresolved but set_slice_3x3' is

xla includes it in external/local_xla/xla/service/gpu/kernels/cutlass_gemm_kernel_bf16xbf16_to_bf16.cu.cc:16 

(from stack trace)

**Comment by thakkarV** [comment]
That's a custom kernel written in XLA using CUTLASS, not an off the self one from our repo. It seems like the slice 3x3 stuff is also an dxtension and not a cutlass method

**Comment by zkbitcoin** [comment]
> That's a custom kernel written in XLA using CUTLASS, not an off the self one from our repo. It seems like the slice 3x3 stuff is also an dxtension and not a cutlass method

but its there .. in nvidia cutlass repo 

https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/matrix.h#L7828

**Comment by mnicely** [comment]
>possible clang version mangles something ? 
It's possible we don't support cuda-clang. You may want to reach out to the XLA team

**Comment by lucifer1004** [comment]
@zkbitcoin I tried simply replacing all `set_slice3x3` (actually only 4 occurrences) within `cutlass` with `set_slice_3x3` and succeeded to compile the examples with `clang++`. Hope this might help you.

**Comment by lucifer1004** [comment]
This should have been fixed by #1784 , @zkbitcoin could you please check again?
