### ISSUE TITLE
[QST]

### ISSUE THREAD

**Issue by ganeshcolfax** [NVIDIA/cutlass#1605]
**We see that for FP8 GEMM only TNN is supported in the cutlass_prolifer generated kernels and in the examples directory cutlass as well. Are there any fp8 kernel with other layouts like TTT/TTN shipped as reference? We are in need of such layouts for FP8 GEMM**

**Comment by thakkarV** [comment]
They are supported already but maybe not getting stamped out by default. You can just add them in the cutlass library generator and they should show up in the profiler

**Comment by ganeshcolfax** [comment]
Thank you. It'll be a good learning for us to understand how to add a kernel in cutlass library generator. Pointers will be useful here. Thank you once again.

**Comment by thakkarV** [comment]
https://github.com/NVIDIA/cutlass/blob/main/python/cutlass_library/generator.py#L5634
