### ISSUE TITLE
[QST] Cutlass Pytorch emit

### ISSUE THREAD

**Issue by wookjeHan** [NVIDIA/cutlass#1606]
**What is your question?**
Hi Team, I am trying to export CUTLASS kernel (`GEMM` with `silu` activation) to a PyTorch CUDA extension following the [tutorial](https://github.com/NVIDIA/cutlass/blob/main/examples/python/02_pytorch_extension_grouped_gemm.ipynb)

My target dtypes for both input and output are are `bfloat16` so I wrote the following code.

```
import cutlass
import torch
dtype = torch.bfloat16
plan = cutlass.op.Gemm(element=dtype, element_accumulator=torch.float32, layout=cutlass.LayoutType.RowMajor)
plan.activation="silu"
op = plan.construct()
gemm_silu = cutlass.emit.pytorch(op, name='gemm_silu', cc=plan.cc, sourcedir='out', jit=True)
```
However, this code fails with a `KeyError: <DataType.bf16: 16>` and I think the main cause is there is no `bf16` type in [torch.types.h](https://pytorch.org/cppdocs/api/file_torch_csrc_api_include_torch_types.h.html).

What would be the standard way to export and use a CUTLASS kernel to a PyTorch CUDA extension for the bfloat16 data type?

Thanks!

**Comment by thakkarV** [comment]
@jackkosaian

**Comment by wookjeHan** [comment]
Sorry, but I noticed that there is at::kBFloat16 type!
I will close the issue as I resolved it!
