### ISSUE TITLE
[QST] Last 10 Slides of Cutlass talk

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1607]
Hi, I was just watching the Cutlass talk from the Cuda Mode board that Pradeep and Vijay gave. Very educational, and I thank you.
We didn’t get time to go deep on the last 10 slides (“Advanced optimizations”). Would anyone from the team care to chat informally with our Cutlass working group about this content? It seems to go beyond the recent GTC talks, which is fantastic. They’re just what we need – hard-won heuristics about how these components interact, beyond the whitepapers and manuals.

Or maybe you’re giving or have given another talk on this material that I could watch.

I would be happy to edit and release it as a short video, if you decide you want to.

Eric

Slides: https://drive.google.com/file/d/18sthk6IUOKbdtFphpm_jZNXoJenbWR8m/view

**Comment by thakkarV** [comment]
what additional content would you like in addition to what we talk about in these slides as well as the CUDA MODE talk?

**Comment by ericauld** [comment]
If the relevant content is all able to be understood from the slides, we can just use those. Thanks
