### ISSUE TITLE
[QST] Calling sgemm kernel in cpp utilizing installed cutlass library

### ISSUE THREAD

**Issue by dscotthunter** [NVIDIA/cutlass#1609]
Hello, 

What is the best way to call a simple sgemm kernel in cpp? Explicitly, I would like to call with `element_A = element_B = element_C = cutlass::library::NumericTypeID::kF32` and `layout_A = layout_B = cutlass::library::LayoutTypeID::kRowMajor`. Based on the example for calling from cpp [here](https://github.com/NVIDIA/cutlass/blob/main/examples/60_cutlass_import/main.cpp), I tried the following code, but it is not succeeding due to `status` being `cutlass::Status::kErrorNotSupported`. Here is the code I am using to try this example:
```cpp
#include <iostream>

#include <cutlass/cutlass.h>
#include <cutlass/library/handle.h>

int main(int argc, char ** argv) {

    const uint M = 4;
    const uint K = 2;
    const uint N = 4;
    float alpha = 1.0, beta = 1.0;

    float *A = nullptr, *B = nullptr, *C = nullptr;
    cudaMalloc((void **)&A, sizeof(float) * M * K);
    cudaMalloc((void **)&B, sizeof(float) * K * N);
    cudaMalloc((void **)&C, sizeof(float) * M * N);

    cutlass::library::Handle handle;

    cutlass::Status status = handle.gemm( 
        M,
        N,
        K,
        cutlass::library::NumericTypeID::kF32,
        cutlass::library::NumericTypeID::kF32,
        &alpha,
        cutlass::library::NumericTypeID::kF32,
        cutlass::library::LayoutTypeID::kRowMajor,
        cutlass::library::ComplexTransform::kNone,
        A,
        M,
        cutlass::library::NumericTypeID::kF32,
        cutlass::library::LayoutTypeID::kRowMajor,
        cutlass::library::ComplexTransform::kNone,
        B,
        K,
        &beta,
        cutlass::library::NumericTypeID::kF32,
        C,
        M,
        C,
        M
    );
    cudaFree(A);
    cudaFree(B);
    cudaFree(C);
    if ( status ==  cutlass::Status::kErrorNotSupported ){
        std::cout << "not supported" << std::endl;
    }

    return 0;
}

```
Is there an example that shows how to do this simple example? Sorry about this simple question, and thank you for the help.

**Comment by dscotthunter** [comment]
I believe this is relevant as well to the example given [here](https://github.com/NVIDIA/cutlass/blob/main/media/docs/quickstart.md#cutlass-library), which is similar to the above but uses `kColumnMajor`. When I try this example from the docs, I also see the `cutlass::Status::kErrorNotSupported` from the above in the `kRowMajor `case. Is it expected that this example from the docs is hitting this not supported message?

**Comment by thakkarV** [comment]
this totally depends on which kernels you are compiling into the CUTLASS library, which is defined by -DCUTLASS_LIBRARY_KERNELS.

**Comment by dscotthunter** [comment]
Awesome, that makes sense, thank you for the help!
