### ISSUE TITLE
Unable to use nv-nsight-cu-cli on cutlass_profiler

### ISSUE THREAD

**Issue by jackkosaian** [NVIDIA/cutlass#161]
I'm trying to profile some of the kernels run by `cutlass_profiler` using `nv-nsight-cu-cli`, but receive an error when attempting to do so.

I perform the following:
```bash
$ mkdir build && cd build
$ cmake .. -DCUTLASS_NVCC_ARCHS=75 -DCUTLASS_LIBRARY_KERNELS=cutlass_simt_sgemm*
$ make cutlass_profiler -j$(nproc)
$ sudo /usr/local/cuda/bin/nv-nsight-cu-cli --target-processes all ./tools/profiler/cutlass_profiler --kernels=cutlass_simt_sgemm_128x128_8x2_nn_align1  --m=128 --n=128 --k=128
==PROF== Connected to process 4900 (/home/ubuntu/cutlass/build/tools/profiler/cutlass_profiler)
==ERROR== The application returned an error code (11)
==WARNING== No kernels were profiled
```
Running the above `cutlass_profiler` command without `nv-nsight-cu-cli` works fine and the benchmark passes.

I'm able to run examples from the `examples` directory under `nv-nsight-cu-cli`:
```bash
$ make test_examples_00_basic_gemm
$ sudo /usr/local/cuda/bin/nv-nsight-cu-cli --target-processes all ./examples/00_basic_gemm/00_basic_gemm
==PROF== Connected to process 4960 (/home/ubuntu/cutlass/build/examples/00_basic_gemm/00_basic_gemm)
==PROF== Profiling "InitializeMatrix_kernel" - 1: 0%....50%....100% - 13 passes
==PROF== Profiling "InitializeMatrix_kernel" - 2: 0%....50%....100% - 13 passes
==PROF== Profiling "InitializeMatrix_kernel" - 3: 0%....50%....100% - 13 passes
==PROF== Profiling "InitializeMatrix_kernel" - 4: 0%....50%....100% - 13 passes
.
.
.
```

Is there anything I'm missing in being able to run `cutlass_profiler` under `nv-nsight-cu-cli`? I apologize if I've missed something silly or if this question has been asked elsewhere (a quick search within the CUTLASS repo did not yield any relevant results). I greatly appreciate any help. Thanks!

### Platform
* AWS g4dn.xlarge instance
* T4 GPU
* CUDA 10.2
* Driver 440.64
* CUTLASS commit: ccb697bac77fcc898e9c897b2c90aa5b60ac72fb

**Comment by hwu36** [comment]
First of all, thank you for using CUTLASS.

I tried the latest compiler and nsight on T4 with driver 455.  It works fine.  You can report nsight issues in https://forums.developer.nvidia.com/c/development-tools/nsight-compute/114.

Also, `nvprof` still works great on T4, maybe you can switch to use `nvprof` instead.

**Comment by jackkosaian** [comment]
Thank you for your quick response!

I am able to profile `cutlass_profiler` using `nvprof` after upgrading the driver. Thanks!
