### ISSUE TITLE
[QST] Benchmark #15 error. "void cutlass::arch::ldsm not implemented"

### ISSUE THREAD

**Issue by dhjoo98** [NVIDIA/cutlass#1610]
**What is your question?**

Hello, I am trying to run the example15 ampere_sparse_tensorop_gemm on A100, CUDA 12.2

CUTLASS was compiled with 
   cmake .. -DCUTLASS_NVCC_ARCHS=80 -DCUTLASS_ENABLE_CUBLAS=ON -DCUTLASS_ENABLE_CUDNN=OFF 

example 15 was built with 
   nvcc -I ${CUTLASS_LOC}/cutlass/include -I ${CUTLASS_LOC}/cutlass/tools/util/include -I ${CUTLASS_LOC}/cutlass/examples/common -std=c++17 

Upon running the program, I get repeated messages of "void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4] not implemented". 

I cannot pinpoint what is going wrong.

**Comment by dhjoo98** [comment]
note that compiled version of the same example that builds with CUTLASS runs correctly.

**Comment by thakkarV** [comment]
>nvcc -I ${CUTLASS_LOC}/cutlass/include -I ${CUTLASS_LOC}/cutlass/tools/util/include -I ${CUTLASS_LOC}/cutlass/examples/common -std=c++17

You are using a custom command line it seems. did you try building with the makefile that CUTLASS CMake spits out? we do not support users if they are using custom build files

**Comment by lvzongting** [comment]
You need add arch flag  --generate-code=arch=compute_80,code=[sm_80]

Here is an example:

nvcc -I/home/lzt/workplace/cutlass/include -I/home/lzt/workplace/cutlass/examples/common -I/home/lzt/workplace/cutlass/build/include -I/home/lzt/workplace/cutlass/tools/util/include -isystem /usr/local/cuda/include --generate-code=arch=compute_80,code=[sm_80] ampere_sparse_tensorop_gemm.cu -o ampere_sparse_tensorop_gemm

Additional,  code for each arch is listed below:
NVIDIA Hopper Architecture:   90a
NVIDIA Ampere Architecture:   80
NVIDIA Turing Architecture:      75
NVIDIA Volta Architecture:         70
NVIDIA Pascal Architecture:       60;61
NVIDIA Maxwell Architecture:    50;53
