### ISSUE TITLE
What is the layout of the Batched Stride GEMM when A C is row major and B is col major？

### ISSUE THREAD

**Issue by Tangesion** [NVIDIA/cutlass#1613]
I'm interested in batched strided gemm C= A*B what is the layout of the matrix when A C is **row major** and B is **col major**
By Example [https://github.com/NVIDIA/cutlass/blob/main/examples/05_batched_gemm/batched_gemm.cu](url)
In this Example A B C are **col major.** 
Now I want to perform the matrix multiplication of int4, the corresponding A and C can only be row major, the point I'm wondering is whether the matrix layout, especially the batched layout, will change, or is it still the same as the layout in example.

**Comment by thakkarV** [comment]
you can just change the layouts of your tensors to match what you want them to be
