### ISSUE TITLE
[QST] about swizzle_layout

### ISSUE THREAD

**Issue by bluebabyxp** [NVIDIA/cutlass#1615]
The below two comments seems conflict, does the later one means is_constant true?
// Test the sliced layout for hit_X & hit_Y for potential decay
    if constexpr (is_constant<false, decltype(hit_ZandY)>::value)
    { // Hits on Y AND Z, so it's not reducible
      return cute::make_tuple(composition(swizzle, offset_only_zy, sliced_layout), offset_anti_zy);
    }

**Comment by thakkarV** [comment]
trivial doc error. will be fixed in the next release
