### ISSUE TITLE
[BUG] undefined symbol: cuTensorMapEncodeTiled on CUTLASS 3.5.1

### ISSUE THREAD

**Issue by cora-codes** [NVIDIA/cutlass#1624]
In CUTLASS 3.5.1, `tensorMapEncodeTiled` was added to `CudaHostAdapter` to allow PyTorch integration without [nasty workarounds](https://github.com/pytorch/pytorch/pull/125204). However, it seems like even with 3.5.1 the problem has persisted and I still get `undefined symbol: cuTensorMapEncodeTiled` when trying to import my PyTorch extension.

(cc @thakkarV)

**Comment by cora-codes** [comment]
Seems like the solution here is changing `cute/atom/copy_traits_sm90_tma.hpp` to use `CudaHostAdapter`?

**Comment by thakkarV** [comment]
@kerrmudgeon @ccecka

**Comment by thakkarV** [comment]
we will work on this and hopefully add it within the next couple of weeks

**Comment by zifeitong** [comment]
I am able to workaround it by LD_PRELOAD the driver library:
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libcuda.so`

**Comment by MARD1NO** [comment]
> In CUTLASS 3.5.1, `tensorMapEncodeTiled` was added to `CudaHostAdapter` to allow PyTorch integration without [nasty workarounds](https://github.com/pytorch/pytorch/pull/125204). However, it seems like even with 3.5.1 the problem has persisted and I still get `undefined symbol: cuTensorMapEncodeTiled` when trying to import my PyTorch extension.
> 
> (cc @thakkarV)

maybe you should add cuda lib in torch cuda extension?, like: 
```python
libraries = ["cuda"]

CUDAExtension(
...
libraries=libraries,
)
```

**Comment by shunfan-shao** [comment]
We would like to propose addressing direct driver API usage by using runtime API to retrieve the function pointer. This approach is also described in [CUDA programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#using-tma-to-transfer-multi-dimensional-arrays). The flag `CUTLASS_ENABLE_DIRECT_CUDA_DRIVER_CALL` can be configured to control which method is to take. 

@cora-codes could you help verify whether this approach meets the requirements for PyTorch's usecase?

**Comment by saagarjha** [comment]
Following up on @cora-codes's behalf. Your PR seems reasonable but I will note that `cudaGetDriverEntryPointByVersion` was added very recently, so this code won't compile on anything but the latest toolchain. Maybe it would be fine to use `cudaGetDriverEntryPoint` here?

**Comment by thakkarV** [comment]
@saagarjha @cora-codes  can you please make sure the MR we just merged https://github.com/NVIDIA/cutlass/pull/1700 meets your needs? We would like to tag 3.5.1 here if this is enough to unblock PyTorch adoption.

**Comment by cora-codes** [comment]
Yes, it works for our needs - thank you so much!
