### ISSUE TITLE
ldmatrix instruction

### ISSUE THREAD

**Issue by LANSHANGH** [NVIDIA/cutlass#1635]
Is your feature request related to a problem? Please describe.
About the ldmatrix instruction called by the SM75_U16x4_LDSM_T method in the copy_sm75.hpp file

Describe the solution you'd like
I'm curious why not every thread in warp accesses consecutive 16*16 matrix fragments, because then every thread in warp can also use efficient store instructions such as store.v4 when accessing shared memory after the computation is done.

Describe alternatives you've considered
I am curious why the PTX documentation describes that when the ldmatrix instruction is called to read four 88 matrices, the matrix fragment held by each thread in a warp is not a continuous matrix fragment, but a fragment of an 88 matrix accessed by each thread instead of a continuous fragment of a 16*16 matrix accessed by each thread.

Additional context
Regarding the ldmatrix instruction called by the SM75_U16x4_LDSM_T method in copy_sm75.hpp file, I am curious why the PTX documentation describes that when calling the ldmatrix instruction to read four 88 matrices, The matrix fragment held by each thread in a warp is not a continuous matrix fragment, but a fragment of an 88 matrix accessed by each thread, rather than a continuous fragment of a 1616 matrix accessed by each thread. I wonder why not every thread in warp accesses a continuous 1616 matrix fragment, because then, Each thread in warp can also use efficient store instructions, such as store.v4, when accessing shared memory after the calculation is complete. Can you answer this question for me

**Comment by thakkarV** [comment]
these are internal details of ISA design that we do not really discuss or document, nor do we discuss hypotheticals about alternative ISA choices. if you have specific questions about how to use LDSM, please open another thread.
