### ISSUE TITLE
[QST] Error: Could not detect active GPU device ID [CUDA driver is a stub library]

### ISSUE THREAD

**Issue by JadeRay** [NVIDIA/cutlass#1636]
**What is your question?**
build error on H800 machine. Seems that it didn't recoginize GPU device. Envioronment listed below:

nvidia-smi
NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2

g++ --version
g++ (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake --version
cmake version 3.25.0-rc2

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99

[ 94%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/symm_cf32n_cf32n_tensor_op_fast_f32_rs_sm80.cu.o
[ 94%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/symm_f64_f64_tensor_op_f64_sm90.cu.o
[ 94%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/hemm_cf64h_cf64n_cf64n_tensor_op_ls_f64_sm80.cu.o
[ 94%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/symm_cf64_cf64_cf64_tensor_op_f64_sm90.cu.o
*** Error: Could not detect active GPU device ID [CUDA driver is a stub library]
make[3]: *** [test/unit/cute/msvc_compilation/CMakeFiles/test_unit_cute_msvc_compilation.dir/build.make:70: test/unit/cute/msvc_compilation/CMakeFiles/test_unit_cute_msvc_compilation] Error 1
make[2]: *** [CMakeFiles/Makefile2:31999: test/unit/cute/msvc_compilation/CMakeFiles/test_unit_cute_msvc_compilation.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 94%] Built target cutlass_test_unit_substrate
[ 94%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/hemm_cf64h_cf64n_cf64n_tensor_op_rs_f64_sm80.cu.o
[ 94%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/hemm_cf32h_cf32n_tensor_op_f32_ls_sm80.cu.o
[ 97%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/hemm_cf64h_cf64n_cf64n_tensor_op_ls_f64_gaussian_sm80.cu.o
[ 97%] Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_blas3.dir/hemm_cf64_cf64_cf64_tensor_op_f64_sm90.cu.o

**Comment by JadeRay** [comment]
other information:

ll /usr/lib64/libcuda.so*
lrwxrwxrwx 1 root root       12 May 27 12:37 /usr/lib64/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       21 Jun 28 11:07 /usr/lib64/libcuda.so.1 -> libcuda.so.535.129.03
-rwxr-xr-x 1 root root        0 May 27 12:37 /usr/lib64/libcuda.so.470.103.01
-rwxr-xr-x 1 root root 29372496 Apr 19 17:44 /usr/lib64/libcuda.so.535.129.03

**Comment by thakkarV** [comment]
this does not seem to be a CUTLASS issue?

**Comment by mnicely** [comment]
You may want to try the CUDA Developer forums https://forums.developer.nvidia.com/c/accelerated-computing/cuda/206
