### ISSUE TITLE
[QST] TMA Reduce ADD

### ISSUE THREAD

**Issue by flytigerw** [NVIDIA/cutlass#1637]
Hey, I found that SM90_TMA_REDUCE_ADD is supported in cutlass. I am wondering whether this can ensure the atomicity when multiple threadblocks write back to the same gmem area .

**Comment by flytigerw** [comment]
Thanks. So maybe I should use SM90_TMA_REDUCE_ADD together with a global mutex to enuse synchronization across multiple threadblocks, right ?

**Comment by thakkarV** [comment]
Yes
