### ISSUE TITLE
The implementation of 1-bit matrix multiplication

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#164]
Hi, All

I just wondering whether could I find the underlying implementation of 

```
using Gemm = cutlass::gemm::device::Gemm<
            cutlass::uint1b_t, cutlass::layout::RowMajor, 
            cutlass::uint1b_t, cutlass::layout::ColumnMajor, 
            ElementOutput, cutlass::layout::RowMajor,
            ElementAccumulator, cutlass::arch::OpClassTensorOp, cutlass::arch::Sm75,
            cutlass::gemm::GemmShape<128, 256, 512>,
            cutlass::gemm::GemmShape<64, 64, 512>,
            cutlass::gemm::GemmShape<8, 8, 128>,
            cutlass::epilogue::thread::LinearCombination<
            ElementOutput, 128 / cutlass::sizeof_bits<ElementOutput>::value,
            ElementAccumulator, ElementCompute>,
            cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>, 2, 128, 128,
            false, cutlass::arch::OpXorPopc>;
```

Thanks!

**Comment by hwu36** [comment]
What do you mean underlying implementation?  Every kernel is the combination of several {device, kernel, threadblock, warp, thread} modules.  Those modules are highly reused by different kernels.

The top device level module is here https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/device/gemm.h#L217

**Comment by YukeWang96** [comment]
> What do you mean underlying implementation? Every kernel is the combination of several {device, kernel, threadblock, warp, thread} modules. Those modules are highly reused by different kernels.
> 
> The top device level module is here
> 
> https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/device/gemm.h#L217

Hi,

I wonder if I can get its warp-level implementation such as wmma function call

**Comment by hwu36** [comment]
warp level mma module is here

https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L270

The wmma call is here https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/mma_sm75.h#L1133

**Comment by manishucsd** [comment]
> > What do you mean underlying implementation? Every kernel is the combination of several {device, kernel, threadblock, warp, thread} modules. Those modules are highly reused by different kernels.
> > The top device level module is here
> > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/device/gemm.h#L217
> 
> Hi,
> 
> I wonder if I can get its warp-level implementation such as wmma function call

All of the GEMM warp-level implementation details are here (iterators and mma operators): https://github.com/NVIDIA/cutlass/tree/master/include/cutlass/gemm/warp

You seem to particularly interested in mma operator (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op.h)

**Comment by YukeWang96** [comment]
> > > What do you mean underlying implementation? Every kernel is the combination of several {device, kernel, threadblock, warp, thread} modules. Those modules are highly reused by different kernels.
> > > The top device level module is here
> > > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/device/gemm.h#L217
> > 
> > 
> > Hi,
> > I wonder if I can get its warp-level implementation such as wmma function call
> 
> All of the GEMM warp-level implementation details are here (iterators and mma operators): https://github.com/NVIDIA/cutlass/tree/master/include/cutlass/gemm/warp
> 
> You seem to particularly interested in warp-level mma operator:https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op.h
> 
> warp-level wmma-based mma operator:
> https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_wmma.h

Hi, 

After add some print statement to the 

cutlass/include/cutlass/gemm/warp/mma_tensor_op_wmma.h at[ Line 197](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op_wmma.h#L197)

Then I  rerun the `cmake .. -DCUTLASS_NVCC_ARCHS=86` and `make` the example again.
However, I didn't notice any output when calling the GEMM.  

Is there any step I missed for making this change to take effect? 
Thanks!

**Comment by YukeWang96** [comment]
> warp level mma module is here
> 
> https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L270
> 
> The wmma call is here
> 
> https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/mma_sm75.h#L1133

I found two similar class that carries MmaTensorOp, which one is the acutal one I call when build the GEMM?

[MmaTensorOp](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L161)

[MmaTensorOpwmma](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op_wmma.h#L83)

Thanks!

**Comment by YukeWang96** [comment]
> > warp level mma module is here
> > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L270
> > 
> > The wmma call is here
> > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/mma_sm75.h#L1133
> 
> I found two similar class that carries MmaTensorOp, which one is the acutal one I call when build the GEMM?
> 
> [MmaTensorOp](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L161)
> 
> [MmaTensorOpwmma](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op_wmma.h#L83)
> 
> Thanks!

Ok, I got to know it actually calls **MmaTensorOp**.  

However, the print statement at [smma_sm75](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/mma_sm75.h#L1133) doest not make difference?

Could please help me?

**Comment by YukeWang96** [comment]
> > > warp level mma module is here
> > > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L270
> > > 
> > > The wmma call is here
> > > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/mma_sm75.h#L1133
> > 
> > 
> > I found two similar class that carries MmaTensorOp, which one is the acutal one I call when build the GEMM?
> > [MmaTensorOp](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op.h#L161)
> > [MmaTensorOpwmma](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_tensor_op_wmma.h#L83)
> > Thanks!
> 
> Ok, I got to know it actually calls **MmaTensorOp**.
> 
> However, the print statement at [smma_sm75](https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/arch/mma_sm75.h#L1133) doest not make difference?
> 
> Could please help me?

Problem Solved,
I should use `cmake .. -DCUTLASS_NVCC_ARCHS=75` when compiling the project to enable the SM75 compilation.

**Comment by YukeWang96** [comment]
> > > What do you mean underlying implementation? Every kernel is the combination of several {device, kernel, threadblock, warp, thread} modules. Those modules are highly reused by different kernels.
> > > The top device level module is here
> > > https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/device/gemm.h#L217
> > 
> > 
> > Hi,
> > I wonder if I can get its warp-level implementation such as wmma function call
> 
> All of the GEMM warp-level implementation details are here (iterators and mma operators): https://github.com/NVIDIA/cutlass/tree/master/include/cutlass/gemm/warp
> 
> You seem to particularly interested in warp-level mma operator:https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op.h
> 
> warp-level wmma-based mma operator:
> https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_wmma.h

Hi,

I found that at the higher level, for example, the block-level, cutlass exposes the `struct template` [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/default_mma_core_sm75.h), where could I found its class/object implementation?

**Comment by hwu36** [comment]
> I found that at the higher level, for example, the block-level, cutlass exposes the struct template here, where could I found its class/object implementation?

Different modules are in different files.  

Main loop is here https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_pipelined.h

The iterator to load the data from the global memory is here https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/predicated_tile_iterator.h#L146

The iterator to store the data to the shared memory is here https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L427

**Comment by YukeWang96** [comment]
> > I found that at the higher level, for example, the block-level, cutlass exposes the struct template here, where could I found its class/object implementation?
> 
> Different modules are in different files.
> 
> Main loop is here https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_pipelined.h
> 
> The iterator to load the data from the global memory is here
> 
> https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/predicated_tile_iterator.h#L146
> 
> The iterator to store the data to the shared memory is here
> 
> https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L427

Got it, Thanks a lot! 
Just one more question.
is there any support from  CUTLASS for Sparse 1-bit matrix-matrix (i.e., SpMM 1-bit data) on Tensorcore? 
I just check the lowest precision for Sparse-MM is about 4-bit on Tensorcore.

Thanks!

**Comment by hwu36** [comment]
> is there any support from CUTLASS for Sparse 1-bit matrix-matrix (i.e., SpMM 1-bit data) on Tensorcore?
> I just check the lowest precision for Sparse-MM is about 4-bit on Tensorcore.

Sparse tensor core only supports s4, s8, fp16, bfloat16, tfloat32 input

**Comment by YukeWang96** [comment]
> > is there any support from CUTLASS for Sparse 1-bit matrix-matrix (i.e., SpMM 1-bit data) on Tensorcore?
> > I just check the lowest precision for Sparse-MM is about 4-bit on Tensorcore.
> 
> Sparse tensor core only supports s4, s8, fp16, bfloat16, tfloat32 input

Hi, 

is there any option that we can overlap the execution of two `gemm_op()` for 1-bit GEMM in CUTLASS? Something like put the kernel on different `streams` in a CUDA kernel.

Thanks a lot!

**Comment by hwu36** [comment]
You can provide stream when running the device level operator.  For example,

https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/device/gemm.h#L469
