### ISSUE TITLE
[BUG] example 57 Hopper Grouped GEMM Disposition failed

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/cutlass#1642]
**Describe the bug**
when i ran example 57 i got a disposition failed error
**Steps/Code to reproduce bug**
cloned and built the examples using make cutlass_examples
**Expected behavior**
Disposition failed
**Environment details (please complete the following information):**
inside the pytorch docker container 24.06-py3, Driver Version: 550.54.15      CUDA Version: 12.5, on H100 SXM 80GB

**Additional context**
nothing else

**Comment by thakkarV** [comment]
@ANIKET-SHIVAM

**Comment by ANIKET-SHIVAM** [comment]
Please try Grouped GEMM with the new 3.5.1 updates (https://github.com/NVIDIA/cutlass/pull/1623) for CUDA 12.5.
There was a bug fix in the PTX, CUTLASS code has been adjusted accordingly.

**Comment by MustafaFayez** [comment]
Thank you!
