### ISSUE TITLE
[QST] Getting `CUDA error: misaligned address` when calculating GEMM with a small matrix, and multiple other questions on understanding Cutlass.

### ISSUE THREAD

**Issue by Jacfger** [NVIDIA/cutlass#1643]
Right now I was looking a library and trying to poke around and realize they're using Cutlass. But because I can't find much of any documentation on this library, nor I have used anything like this before, I had a lot of questions on what's happening on what I've observed.

1. Why am I seeing `CUDA error: misaligned address` when doing GEMM on a really small matrices. 

I want know how dp4a works and I'm testing for it, and during the testing, I made a matrix (or a vector) with size `(1, 16)` and another matrix `(16, 16)` (all shapes here are counting in 4-bits `int`). But somehow when I try to solve this with GEMM, I'm getting `CUDA error: misaligned address`. But if the size is 32, i.e. vector of `(1, 32)` multiply by `(32, 32)` matrix, the programs run fine and I'm seeing my expected results. (As we can see in the code below, because I'm actually using `cutlass::int4b_t`, so the actual shape of the array is a `int8_t` of size `(1, 8)` and `(16, 8)`.)

```
void matmul_host(const uint8_t *A, const uint8_t *B, uint32_t M, uint32_t N, uint32_t K, int32_t *C)
{
    using Gemm = cutlass::gemm::device::Gemm<
            cutlass::int4b_t,                // ElementA
            cutlass::layout::RowMajor,       // LayoutA
            cutlass::int4b_t,                // ElementB
            cutlass::layout::ColumnMajor,    // LayoutB
            int32_t,                         // ElementOutput
            cutlass::layout::RowMajor,       // LayoutOutput
            int32_t,                         // ElementAccumulator
            cutlass::arch::OpClassTensorOp,  // tag indicating Tensor Cores
            cutlass::arch::Sm80  // tag indicating target GPU compute architecture  // TODO: This is just for compiling on my laptop temporarily. Should be higher when doing benchmarking.
    >;

    Gemm gemmOp;
    using GemmCoord = cutlass::gemm::GemmCoord;

    typename Gemm::Arguments arguments{
            {static_cast<GemmCoord::Index>(M), static_cast<GemmCoord::Index>(N), static_cast<GemmCoord::Index>(K)},
            {(cutlass::int4b_t *) A,           K},
            {(cutlass::int4b_t *) B,           K},
            {C,                                N},
            {C,                                N},
            {1,                                0}
    };

    auto status = gemmOp(arguments);
    ensure(status == cutlass::Status::kSuccess,
           cutlassGetStatusString(status));
}
```

2. How should I understand ColumnMajor and RowMajor?

I generally just have a hard time understanding it. Because when I swap RowMajor to ColumnMajor (So both Layout are RowMajor), compilation error happens. I'm not so sure what they actually represent as of right now. Where I can know more about it? Because I thought it means the reading direction of the matrix raw data, but then switching LayoutB to `RowMajor` generates hundreds lines of template error. But if it means the reading direction of the raw data representation then it shouldn't be like this?

3. Why default it's LayoutA is ColumnMajor and LayoutB is RowMajor? Does it matter?

So in normal matrix multiplication sense I would believe A being in RowMajor and B being in ColumnMajor make a bit more sense, because that's how human do matrix multiplication. But ColumnMajor A and RowMajor B would maximizing the use of cached matrix C, I believe? Would there be any performance penalty choosing one over another, or does it depends?

4. How do I know which one template is actually being instantiate?

Like sure I know the instantiation of the tempalte matches here. But is there anyway to confirm I actually used dp4a but not other operations?
https://nvidia.github.io/cutlass/structcutlass_1_1gemm_1_1thread_1_1Mma_3_01Shape___00_01int8__t_00_01layout_1_1ColumnMajor_00_013f3785e722edc6e9aab6f866309b8623.html#a1429b2efb3fcf27381763368fa49ac4b

I'm both new to CUDA programming (TMI, yesterday I spent 4 hours to figure out that launching kernel threads on GPU 0 causes `Error Internal` when all the matrices were put in another GPU) and Cutlass, and I'm really hoping for some guidance to understand this library. I can just blindly make the size a multiple of 32, but it wouldn't help me understand this elegant way to do GEMM using CUDA.

Much thanks.

**Comment by Jacfger** [comment]
I figured it's probably because CUDA for some reason is expecting the dimension `8` in `128x128x8` has to be aligned (which correspond to 32). Though I'm not sure why the `128x128` is fine to just ignore.

**Comment by thakkarV** [comment]
The major dimension has to be a multiple of the alignment you have chosen

**Comment by Jacfger** [comment]
> The major dimension has to be a multiple of the alignment you have chosen

So in my case, rhe major dimension is 8, and because IDP4A works by fitting 4 integers into a int32, there needs to be 8*4=32 int4?

**Comment by thakkarV** [comment]
Yes, you would need your problem size to be multiples of 32 along the major dim provided you are using 128b load operations. you can also relax this requirement by dropping to 64b or 32b loads for more flexibility at the cost of performance
