### ISSUE TITLE
[QST] Understanding layouts in CuTe MMA atom traits

### ISSUE THREAD

**Issue by alexsamardzic** [NVIDIA/cutlass#1644]
Am looking into [MMA traits for `SM80_16x8x8_F32TF32TF32F32_TN`](https://github.com/NVIDIA/cutlass/blob/56b46e2d13875b46b8f6a03f9f5ac91e2bfdc01a/include/cute/atom/mma_traits_sm80.hpp#L163).  The `ALayout` and `BLayout` defined by this traits struct should describe thread/value distributions depicted [here](https://docs.nvidia.com/cuda/parallel-thread-execution/#mma-1688-a-tf32) and [here](https://docs.nvidia.com/cuda/parallel-thread-execution/#mma-1688-b-tf32), respectively, in the PTX manual.

I used following code to print these layouts:
```
#include <stdio.h>

#include <cute/layout.hpp>

using namespace cute;

int main() {
  auto la = Layout<
      Shape<Shape<_4, _8>, Shape<_2, _2>>,moot 
      Stride<Stride<_16, _1>, Stride<_8, _64>>>{};
  auto lb = Layout<Shape<Shape<_4, _8>, _2>, Stride<Stride<_8, _1>, _32>>{};

  print_layout(la);
  printf("\n");
  print_layout(lb);
  printf("\n");

  return 0;
}
```

For example, for thread #0 and layout A, the code prints:
```
        0     1     2     3 
    +-----+-----+-----+-----+
 0  |   0 |   8 |  64 |  72 |
    +-----+-----+-----+-----+
```
and for thread #0 and layout B, the code prints:
```
       0    1 
    +----+----+
 0  |  0 | 32 |
    +----+----+
```

Now, what confuses me is that `TN` should mean that input `A` is in row-major order, and that input `B` is in column-major order.  However, the coordinates printed above (and also coordinates for other thread/value pairs) seems as if `16x8` tile of input `A` is "considered" in column-major, and `8x8` tile of input `B` is "considered" in row-major order.  By "considered", I mean here if we look values from tiles in the pics from the PTX manual linked above as stored contiguously, but I understand this is moot because the tile values are not contiguous at this point, but distributed over threads registers.  So my question is: how to properly interpret these linear coordinates from the layout printouts, for both input `A` and input `B`?

**Comment by thakkarV** [comment]
see https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/0t_mma_atom.md
