### ISSUE TITLE
I also noticed that the option of FP8 operand and FP16 accumulator is excluded in `ss_op_selector` and `rs_op_selector`, even though this is accommodated by the PTX ISA and otherwise has `MMA_Traits` structs defined for it (F16E4M3E4M3 etc.). This is done by the following code:

### ISSUE THREAD

**Issue by ylz1104** [NVIDIA/cutlass#1646]
I also noticed that the option of FP8 operand and FP16 accumulator is excluded in `ss_op_selector` and `rs_op_selector`, even though this is accommodated by the PTX ISA and otherwise has `MMA_Traits` structs defined for it (F16E4M3E4M3 etc.). This is done by the following code:
```
// FP16 accumulator
  if constexpr (is_same_v<ElementC, half_t>) {
    static_assert(is_same_v<ElementA, half_t>, "Element types for AB must be half if ElementC is half.");
    static_assert(is_same_v<ElementB, half_t>, "Element types for AB must be half if ElementC is half.");
```
    
Was this intentional or is this an oversight?

_Originally posted by @jayhshah in https://github.com/NVIDIA/cutlass/issues/1268#issuecomment-1885397465_

**Comment by thakkarV** [comment]
just an oversight. we do not really have a use for them today, but if you do you are welcome to add them or ask us to add them.
