### ISSUE TITLE
[QST] About "Threadblock Swizzle", why need this?

### ISSUE THREAD

**Issue by YuanTao1995** [NVIDIA/cutlass#1648]
After read  code at cutlass/include/cutlass/gemm/threadblock/threadblock_swizzle.h, I have some question as follows.  For example, I launch a kernel<<<(16, 1, 1), (128, 1,1)>>> and  use params.swizzle_log_tile==2, so that will be:      (16, 1, 1) --> (4, 4, 1)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15  
-->
 0  4  8  12
 1  5  9  13
 2  6 10  14
 3  7 11  15

As i know, 
1. The order of block execution is correlated to blockIdx(x -> y -> z).
2. Also, the execution of each block on which SM is determined by the hardware and cannot be controlled by programmers. 

So, why dont i launch as (4, 4, 1) instead?  why do i need block level swizzle? **Could  it improve performance(l2 hit rate.) indeed**?

**Comment by thakkarV** [comment]
yes, it is to improve locality

**Comment by lyx-111111** [comment]
I also want to know the difference between (16,1,1)and (4,4,1)，why it can improve l2 hit rate
