### ISSUE TITLE
Fast elementwise reduction for Multiple Matrices in CUTLASS

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#165]
Hi, All 

**Is there any efficient way for the fast elementwise reduction of several matrices into one matrix in CUTLASS?**

For example, originally I have 6 MxN matrics, and I want to reduce all these matrices into one matrix by adding all elements at the same position (x,y). And Finally, we get 1 MxN matrix as the output.

My current implementation is slow by calling a separate CUDA kernel.

```
// mat_size = M * N;
// blocksize = 1024;
// kernel dim: <<< mat_size/blocksize,  blocksize>>>
// bit_mat:  [nbits, mat_size]
// s32_mat:  [mat_size]
// nbits = 6 

__global__ 
void bit_compostion(unsigned* bit_mat, unsigned* s32_mat, const unsigned nbits, const unsigned mat_size){
const unsigned tid = blockIdx.x * blockDim.x + threadIdx.x;
if (tid < mat_size){
    # pragma unroll        
    for (unsigned cur_bit = 0; cur_bit < nbits; cur_bit++){
        const unsigned source_id = cur_bit * mat_size + tid;
        const unsigned target_id  = tid;

        s32_mat[target_id] += bit_mat[source_id];
    }
 }
}
```

Thanks!

**Comment by timespacce** [comment]
You want to aggregate X many matrices - each of dimension A x B (number of elements R = A * B).

The flaw of your approach is that you do **nbits** many global stores and elements are not adjacent in memory. Try to do as few as possible and to access adjacent elements.

**I)** If the matrices are stored adjacent - Y_1, Y_2, Y_3 - .. - Y_X - then you won't profit from WARPS and SIMT. In this case the best algorithm would be the one you do. So start R many threads. Each sums up X many elements, without any intermediate shared memory storage, and then stores the result directly in the output.

**II)** If the matrices are stored elementwise - Y_1_1, Y_2_1, Y_3_1 - .. Y__X_R - then you can start R * X many threads with X many warps. Each thread stores the current element in shared memory and then via SIMT the whole warp is summed up. This would be most efficient for 32 matrices. For your case of only 6 perhaps not that much.

The algorithm you try to implement doesn't reuse memory that much - therefore the current NVIDIA GPU Architectures can't speed it as much as they do for example in the GEMM field.

Best Wishes,
James.

**Comment by YukeWang96** [comment]
> You want to aggregate X many matrices - each of dimension A x B (number of elements R = A * B).
> 
> The flaw of your approach is that you do **nbits** many global stores and the elements are not adjacent in memory. Try to do as few as possible and to access adjacent elements.
> 
> **I)** If the matrices are stored adjacent - Y_1, Y_2, Y_3 - .. - Y_X - then you won't profit from WARPS and SIMT. In this case the best algorithm would be the one you do. So start R many threads. Each sums up X many elements, without any intermediate shared memory storage, and then stores the result directly in the output.
> 
> ```
>     unsigned result = 0;
>     #pragma unroll
>     for (unsigned cur_bit = 0; cur_bit < nbits; cur_bit++){
>         result += bit_mat[cur_bit * mat_size + tid]
>     }
>     s32_mat[tid] = result;
> ```
> 
> **II)** If the matrices are stored elementwise - Y_1_1, Y_2_1, Y_3_1 - .. Y__X_R - then you can start R * X many threads with X many warps. Each thread stores the current element in shared memory and then via SIMT the whole warp is summed up. This would be most efficient for 32 matrices. For your case of only 6 perhaps not that much.
> 
> The algorithm you try to implement doesn't reuse memory that much - therefore the current NVIDIA GPU Architectures can't accelerate it as much as they do for example in the GEMM field.
> 
> Best Wishes,
> James.

Could I leverage the GEMM for such a reduction? 

For example, I have A(M x N x nbits) as the input matrix. Then I do GEMM with A (M x N x nbits) and  B (nbit x 1), where all element s in B is one. Then I can get C (M x N). Maybe I can get higher FLOPs.

**Comment by timespacce** [comment]
Yes, you can, but only if B consists only of 1's. Because only then the GEMM would get you the sum of all matrices.

GEMM leads to nbits many multiplications and additions per output value. In the previous case you need no multiplications. Also the overhead of B leads to twice as many global reads per output value. I doubt that this would be more performant, but you can try it out.
