### ISSUE TITLE
[QST] How to understand iter mode from ThrMMA::partition_fragment_{A,B,C}?

### ISSUE THREAD

**Issue by cloudhan** [NVIDIA/cutlass#1651]
**What is your question?**

Take `partition_fragment_A` as an example:
```c++
#include "cute/tensor.hpp"
using namespace cute;

int main() {
  auto tiled_mma = make_tiled_mma(SM80_16x8x8_F32F16F16F32_TN{});
  auto a = make_tensor(make_shape(_16{}, _64{}));
  auto thr_mma = tiled_mma.get_thread_slice(0);
  print(thr_mma.partition_A(a)), print("\n");
  print(thr_mma.partition_fragment_A(a)), print("\n");
}
```

produces

```
ptr[8b](0x7ffdeea72eb0) o ((_2,_2),_1,_8):((_16,_8),_0,_128)
ptr[16b](0x7ffdeea72e70) o ((_2,_2),_1,_8):((_1,_2),_0,_4)
```

For `partition_A`, the result is pretty reasonable, the MMA work on an A Tile of shape 16x8 in a compact way, work on 16x64 tile with iter size 8, stride 128 is right as expected by sliding the Tile to the right by 128 elements.

For `partition_fragment_A`, the iter stride is `4`, how should I interpret the stride here? From my understanding, the fragment-izing is designed for vectorization along the first mode (0th mode), so in principle it should not affect the strides of other iter modes.

**Comment by ccecka** [comment]
`partition_A` returns a subtensor of the input tensor as you observe. If the input is smem, the result will be an smem subtensor. In your code, your input tensor has a `8b` value type and the output is a subtensor of that tensor.

`partition_fragment_A` returns a new (usually registers) tensor with the same shape as the input tensor for direct consumption by the MMA. Each thread gets it's own fragment and we would like that allocation to be compact. In your code, your input tensor has an `8b` value type, but the MMA consumes tensors with a `16b` value type (`half_t` or `F16` in the name), so you get back a new register tensor of 2*2*8 `half_t`s.

**Comment by cloudhan** [comment]
OK, it suddenly make sense to me now. `partition_A` create a view (ViewEngine tensor), so the iter mode stride will not be affected. The `fragment` APIs however always operate on Tensors with ArrayEngine. It is small enough to fit in to the registers, so the iter modes must also be as compact as possible. So the stride `_4` is just the number of elements between fragments, instead of view of Tiles.

Thanks

**Comment by cloudhan** [comment]
Asides from that, the confusion seems to arise from the naming of `partition_fragment_A`, partition generally create a view, but here it create a new tensor. Better consider make it explicit as `make_fragment_A(partition_A(...))`
