### ISSUE TITLE
[QST] (Warp-Specialized) Persistent Kernel design vs Stream-K

### ISSUE THREAD

**Issue by HanGuo97** [NVIDIA/cutlass#1654]
**What is your question?**

Hi, this could be a very naive questin, but I have long been baffled by "persistent kernel design." I was trying understand the concept via the [doc](https://github.com/NVIDIA/cutlass/blob/main/media/docs/efficient_gemm.md#warp-specialization), and have some questions. Notably,

> Persistent thread blocks launched to occupy as many SMs as mentioned in the [KernelHardwareInfo](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/kernel_hardware_info.hpp) struct. These persistent thread blocks are used to tile the output and thus (potentially) compute multiple output tiles through their lifetime. The main benefit this adds is amortization of the thread-block launch and kernel prologue overheads which are typical of all kernels.

It seems to me that this is more or less Stream-K? Are they the same concept, or I have misunderstood something?

Thanks in advance for your time!

**Comment by thakkarV** [comment]
Stream K is a load balancer implemented using persistence but persistence need not entail any load balancing.

**Comment by HanGuo97** [comment]
Ah interesting, thanks for the explanation. So if I understand correctly, "persistence kernel" is a somewhat broad term, and Stream-K is an instantiation of persistence kernel with load balancing?

**Comment by thakkarV** [comment]
correct

**Comment by HanGuo97** [comment]
Thanks again!
