### ISSUE TITLE
[BUG]example49 error with: --m=2048 --n=20480 --k=5120 --l=2

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1660]
I compiled example 49 using H100, and I get this:

```
./49_collective_builder --m=2048 --n=20480 --k=5120 --l=2
Automatically-selected schedule and stage count: Passed
Automatically-selected schedule with 5 stages: Passed
TMA schedule with automatically-selected stage count: Passed
Warp-specialized TMA schedule with automatically-selected stage count: Passed
Ping-pong warp-specialized TMA schedule with automatically-selected stage count: Passed
terminate called after throwing an instance of 'cutlass::cuda_exception'
  what():  std::exception
Aborted (core dumped)
```

**Comment by ziyuhuang123** [comment]
Additionally, more bugs appear when m is larger:

```
./49_collective_builder --m=4096 --n=20480
 --k=5120 --l=2
Automatically-selected schedule and stage count: Passed
Automatically-selected schedule with 5 stages: Passed
TMA schedule with automatically-selected stage count: Passed
terminate called after throwing an instance of 'cutlass::cuda_exception'
  what():  std::exception
Aborted (core dumped)
```

**Comment by thakkarV** [comment]
@IonThruster

**Comment by jackkosaian** [comment]
Can you please list the CUDA version you're using?

I haven't been able to reproduce this on H100.

**Comment by jackkosaian** [comment]
Thanks!

I'm still not able to reproduce with that compiler.

A few more questions:
1. Are you running on H100 SXM or PCIe?
2. What commit are you using for CUTLASS?
3. What are the CMake commands you're using?
4. Are you on Linux or Windows?

**Comment by ziyuhuang123** [comment]
nvidia-smi
Mon Jul 29 21:44:50 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:1B:00.0 Off |                    0 |
| N/A   24C    P0             69W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |


1.  I think.... SXM?
2. I downloaded it three days ago...
3. 
```
mkdir build && cd build
cmake .. -DCUTLASS_NVCC_ARCHS=90a
```
4. Linux

Well...my computer can not connect to the Internet, does this matter? I am busy now, I can check more tomorrow, thanks!!!

**Comment by ziyuhuang123** [comment]
Well, I find it's my typo...Sorry!
