### ISSUE TITLE
Bit-decomposition of a uint32 matrix by CUTLASS GEMM

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#167]
Hi, All

Is there any efficient way for the fast elementwise decomposition of an int32 matrix into several 1-bit matrices?

> For example, originally I have one `MxN` matrix, and I want to decompose this matrix into three matrices based on the last three bits of each element inside this matrix.  Therefore, I will get the expanded matrix with `3xMxN`.   Then I can use this matrix to initialize the 1-bit GEMM in CUTLASS.

My current idea is that if there is some option of GEMM template in CUTLASS that can specify the `AND & SHIFT` in place of the original `Add` in the traditional GEMM operator, then this problem can be reduced as the GEMM for acceleration. For example, `(nbits x 1) x (1 x M x N) => (nbits x M x N)`.

**Comment by hwu36** [comment]
uint1b_t is defined here
https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/integer_subbyte.h#L155

Our subbyte operations are in this file

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/subbyte_reference.h

Maybe not directly usable for you, but you may get some ideas.
