### ISSUE TITLE
[QST] "Bulk copy" term for 1D TMA?

### ISSUE THREAD

**Issue by ericauld** [NVIDIA/cutlass#1682]
**What is your question?**

Question about terminology: Is the phrase "bulk copy" (as opposed to "TMA") used here to mean specifically the non-`.tensor` `cp.async.bulk` operations – ie. the ones that don't need a `CUtensorMap`? If so, is that common terminology outside the Cutlass world? 

https://github.com/NVIDIA/cutlass/blob/06b21349bcf6ddf6a1686a47a137ad1446579db9/include/cute/atom/copy_traits_sm90_tma.hpp#L488

I gather this is a somewhat loose way to refer to it, which is fine, of course

**Comment by thakkarV** [comment]
your understanding is correct
