### ISSUE TITLE
[QST] How to reconcile WGMMA swizzled layouts presented in PTX docs with CUTLASS GmmaDescriptor canonical layouts

### ISSUE THREAD

**Issue by jayhshah** [NVIDIA/cutlass#1688]
**What is your question?**

I'm trying to reconcile the description of GmmaDescriptor canonical layouts presented in the comments of the `make_gmma_desc` method with the pictures of swizzled core matrix layouts for WGMMA that I see in the [PTX documentation](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#asynchronous-warpgroup-level-matrix-shared-memory-layout-swizzling-modes). For simplicity let's just focus on the Major-K case. Then CUTLASS [says the following](https://github.com/NVIDIA/cutlass/blob/36cbfcf483cc9d2ee65a55c199176ce96da1e33e/include/cute/atom/mma_traits_sm90_gmma.hpp#L179):

```
* Each GmmaDescriptor Major-K describes a canonical layout of the form
*
* LayoutType::INTERLEAVE : Swizzle<0,4,3> o smem_ptr o ((8,m),(T,2)):((1T,SBO),(1,LBO))
* LayoutType::B32        : Swizzle<1,4,3> o smem_ptr o ((8,m),(T,2)):((2T,SBO),(1, T ))
* LayoutType::B64        : Swizzle<2,4,3> o smem_ptr o ((8,m),(T,2)):((4T,SBO),(1, T ))
* LayoutType::B128       : Swizzle<3,4,3> o smem_ptr o ((8,m),(T,2)):((8T,SBO),(1, T ))
```

I don't understand how these layouts are describing the same thing as the PTX pictures for 64 and 128 byte swizzling. For example, the strides for 64 and 128 byte swizzle, and the way that the canonical layouts are prepared using the `GMMA::Layout` atoms for SW64 or SW128 passed into `tile_to_shape`, are such that the WGMMA 64x(32 byte) MxK tile is implicitly fitted into a larger 64x(64 byte) and 64x(128 byte) tile, but this isn't apparent from examining the PTX pictures, which depict swizzled groupings of core matrices within a single WGMMA tile extending both across K and across M.

Would this be related to non-default choices for "matrix base offset" of the [matrix descriptor](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#matrix-descriptor-format)? This appears to always be set to 0 in CUTLASS.

**Comment by thakkarV** [comment]
> which depict swizzled groupings of core matrices within a single WGMMA tile extending both across K and across M.

How you lay out core matrices within smem is totally up to you. The LBO and SBO parameters of the smem desc let you then tell the MMA what the layout within smem is. For this reason, there is no single canonical way to lay out a set of core matrices within smem.
