### ISSUE TITLE
Performance difference between CUTLASS and cuBLAS

### ISSUE THREAD

**Issue by ptillet** [NVIDIA/cutlass#169]
Hi!

I have been benchmarking the `cutlass_tensorop_f16_s884gemm_f16_128x128_32x2_tn_align8` kernel provided by CUTLASS and observe that the performance is quite a bit lower than a kernel with a very similar name from cuBLAS.

My setup is as follows: I added a for loop there https://github.com/NVIDIA/cutlass/blob/master/tools/profiler/src/cublas_helpers.cpp#L265 to call cuBLAS 100 times and compiled CUTLASS with:
```
cmake .. -DCUTLASS_NVCC_ARCHS='70' -DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_f16_s884gemm_f16_128x128_32x2_tn_align8;
make -j8 cutlass_profiler;
```

Then, running
```
nvprof ./tools/profiler/cutlass_profiler  --m=8192 --n=8192 --k=8192
```
Shows
```
// CUTLASS
26.44%  1.31549s       111  11.851ms  11.049ms  12.006ms  void cutlass::Kernel<cutlass_tensorop_f16_s884gemm_f16_128x128_32x2_tn_align8>(cutlass_tensorop_f16_s884gemm_f16_128x128_32x2_tn_align8Params)
// cuBLAS
22.13%  1.10069s       100  11.007ms  10.174ms  11.330ms  void cutlass::Kernel<cutlass_70_tensorop_f16_s884gemm_f16_128x128_tn_align8>(cutlass_70_tensorop_f16_s884gemm_f16_128x128_tn_align8Params)

```
 which seems to show that cuBLAS (100 TFLOPs) is about 7-8% faster than CUTLASS (93 TFLOPS) despite running the same tiling configuration. Am I missing something? And if not, can anything be done about it?
 
 Edit: This is the NVCC version I am compiling CUTLASS with:
 ```
 nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
 ```
 Thanks!

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-46

**Comment by sunlex0717** [comment]
I think it is because of the programming language.
CUTLASS is pure CUDA C++ with some PTX codes. 
CUBLAS is close-source library developed by Nvidia Engineers. Some assemble-level optimizations could be applied but we do not know.
From a user's perspective, I think 7-8% difference is reasonable.

**Comment by hwu36** [comment]
@sunlex0717 

CUDA 11.3 significantly improves the performance of Ampere/Turing/Volta Tensor Core kernels.  See #241 .  Programming language is no an issue now :smile:
