### ISSUE TITLE
[QST] movematrix is not used

### ISSUE THREAD

**Issue by kf-zhang** [NVIDIA/cutlass#1692]
**What is your question?**
I've observed that the movematrix instruction, documented [here](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html?highlight=stmatrix#warp-level-matrix-instructions-movmatrix), is capable of performing matrix transposition. However, I haven't come across any examples of its usage. Is there a particular reason for this?

**Comment by thakkarV** [comment]
we have not needed it for anything yet.

**Comment by kf-zhang** [comment]
I believe this could be useful for int8/fp8 GEMM operations where ldmatrix cannot process transposed matrices. In these situations, it can be used to transpose the matrix. How do you handle such cases?

**Comment by manishucsd** [comment]
```
movmatrix.sync.aligned.shape.trans.type d, a;

.shape  = {.m8n8};
.type   = {.b16};
```

`movematrix` is also supported for b16 (16-bit data).`ldmatrix` can transpose data while moving from shared memory to registers. Unless, you need data in registers in two different layouts, I don't see the use case of `movematrix`.  `ldmatrix` is more than enough for all the typical use-cases.

**Comment by kf-zhang** [comment]
One scenario for utilizing movmatrix is in FP8 attention, where the matrix V needs to be transposed. The current implementation (as seen [here](https://github.com/Dao-AILab/flash-attention/blob/3669b25206d5938e3cc74a5f7860e31c38af8204/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp#L54)) employs ldmatrix, byte_perm, and stmatrix to transpose V in shared memory. Could using movmatrix allow us to transpose V directly in registers?
