### ISSUE TITLE
[QST] Example for GroupedGemm Int8 Version

### ISSUE THREAD

**Issue by StarrickLiu** [NVIDIA/cutlass#1699]
**What is your question?**

Hello,

I am looking for an example of the Int8 version of GroupedGemm in Cutlass. Currently, I have only found examples using FP16, but my project requires computations using Int8.

I would like to know:

Does Cutlass support an Int8 version of GroupedGemm?

If supported, are there any relevant code examples or documentation available for reference?

If not currently supported, are there any plans to add this functionality in future versions?

Thank you very much for your help and suggestions!

**Comment by StarrickLiu** [comment]
Additionally, if I want to adapt this GroupedGemm to different SM architectures, should I follow the guidelines for setting ThreadblockShape, WarpShape, and InstructionShape as outlined in this document:
https://github.com/NVIDIA/cutlass/blob/main/media/docs/functionality.md

**Comment by jackkosaian** [comment]
Yes, CUTLASS does support INT8 in grouped GEMM (in both the 2.x and 3.x versions of CUTLASS grouped GEMM). From your second comment including questions about `WarpShape`, I assume you're asking about the 2.x interface outlined in example 24 -- please correct me if I'm wrong.

To change example 24 to use INT8, you should update the template parameters for the grouped GEMM to use INT8 data types and other parameters compatible with INT8. You can follow an example of these template parameters for a single GEMM [here](https://github.com/NVIDIA/cutlass/blob/7192f4ab230bb721fa8d4d3df33886dbe86cdc59/test/unit/gemm/device/gemm_s8t_s8n_s32n_tensor_op_s32_sm80.cu#L58-L67).

Yes, you can follow that document.

**Comment by StarrickLiu** [comment]
> Yes, CUTLASS does support INT8 in grouped GEMM (in both the 2.x and 3.x versions of CUTLASS grouped GEMM). From your second comment including questions about `WarpShape`, I assume you're asking about the 2.x interface outlined in example 24 -- please correct me if I'm wrong.
> 
> To change example 24 to use INT8, you should update the template parameters for the grouped GEMM to use INT8 data types and other parameters compatible with INT8. You can follow an example of these template parameters for a single GEMM [here](https://github.com/NVIDIA/cutlass/blob/7192f4ab230bb721fa8d4d3df33886dbe86cdc59/test/unit/gemm/device/gemm_s8t_s8n_s32n_tensor_op_s32_sm80.cu#L58-L67).
> 
> Yes, you can follow that document.

Thank you for your response. I have an additional question regarding the Warp Shapes:

According to the table in https://github.com/NVIDIA/cutlass/blob/main/media/docs/functionality.md#warp-level-matrix-multiply-with-tensor-cores, the relationship between Instruction Shape and Warp Shapes is as follows:

|**Opcode Class** | **Instruction Shape** | **Warp Shapes**                            |
|-----------------|-----------------------|--------------------------------------------|
| **TensorOp**    | 16-by-8-by-32         | 32x32x32, 32x64x32, 64x32x32, 64x64x32     |

I understand this to mean that the Instruction Shape (16,8,32) only supports Warp Shapes (32,32,32), (32,64,32), (64,32,32), and (64,64,32).

However, in the following example:
https://github.com/NVIDIA/cutlass/blob/7192f4ab230bb721fa8d4d3df33886dbe86cdc59/test/unit/gemm/device/gemm_s8t_s8n_s32n_tensor_op_s32_sm80.cu#L58-L67

It uses Instruction Shape (16,8,32) with Warp Shape (64,64,128).

Why is this combination allowed? Isn't the K dimension strictly limited according to the table? Could you please explain this apparent discrepancy?

@jackkosaian

**Comment by hwu36** [comment]
the table is not completed.  the k dimension of the warp shape can be 64 and 128.  now we also support some small warp shape sizes like m/n can be 16.

you could check https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/CMakeLists.txt#L428-L432 for the combinations.

**Comment by StarrickLiu** [comment]
> the table is not completed. the k dimension of the warp shape can be 64 and 128. now we also support some small warp shape sizes like m/n can be 16.
> 
> you could check https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/CMakeLists.txt#L428-L432 for the combinations.

Really helpful!
