### ISSUE TITLE
Typo in for iterations

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#170]
https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/warp/mma_simt_tile_iterator.h#L451

kN and kM should be kColumn and kRow respectively

**Comment by hwu36** [comment]
Yes, you are right.  We will fix it.  Thank you.

**Comment by hwu36** [comment]
It was fixed.
