### ISSUE TITLE
Inefficient shared memory operation at matrix tile initialization

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#171]
Hi, All

I want to initialize a dense matrix tile in shared memory (for CUTLASS GEMM later on) from the sparse format (e.g., COO, CSR). However, I found it becomes the performance bottleneck compared with the later on GEMM.  Here is my code, I use a warp of threads to load a chunk of CSR sparse matrix (**cover the edges across several nodes**) as dense tile. `edgeToColumn` and `edgeToRow` is an auxiliary list for the row/column index conversion within a dense tile. `BLK_W ` and `BLK_H` is the width and height of a tile. `WARP_SIZE` is 32. `sparse_A` is a dense tile in shared memory with the shape of `[BLK_H, BLK_W]`. `sparse_AToX_index` is a vector with the shape of `[1, BLK_W]`.

> 		for (unsigned eIdx = eIdx_start + laneid; eIdx < eIdx_end; eIdx += WARP_SIZE){
> 			unsigned col = edgeToColumn[eIdx];
> 			if (i * BLK_W <= col && col < (i + 1) * BLK_W){			// if the edge in the current tile.
> 				unsigned row = edgeToRow[eIdx] % BLK_H;
> 				sparse_A[row * BLK_W + col % BLK_W] = 1;		// set the edge of the sparse_A.
> 				sparse_AToX_index[col % BLK_W] = edgeList[eIdx];	// record the mapping from sparse_A colId to rowId of dense_X.
> 			}		
> 		}
> 		

Based on my test, these two lines

>   		sparse_A[row * BLK_W + col % BLK_W] = 1;		// set the edge of the sparse_A.
>   		sparse_AToX_index[col % BLK_W] = edgeList[eIdx];	// record the mapping from sparse_A

Takes the most of execution time (more than 95%).
**Is there any way to improve it?**

Thanks!

**Comment by hwu36** [comment]
1. Does your for loop have fixed trip count?  If so, you need to add `#pragma unroll` to fully unroll the loop.
2. My understanding is that `sparse_A[]` is stored in the shared memory.  Have you swizzled the data to remove the bank conflict.
3. Where is `sparse_AToX_index` stored?  If it is in the shared memory, you need to make sure it is bank conflict free like above.  If it is supposed to be in the register file, you need to let the compiler know that `col % BLC_W` is compile time constant, otherwise it would be lowered into using local memory which is very slow.

**Comment by YukeWang96** [comment]
Thanks!

1. I attached the shared memory layout for `sparse_A`,  where the red color box indicates the edges and `eIdx` only iterates through these red boxes. **One thing I found very challenge here is that `edgeToColumn ` and `edgeToColumn ` cannot be determined statically at compile time.**
![main-Page-10](https://user-images.githubusercontent.com/18487372/105751250-9afc6800-5efa-11eb-976e-da1612cfd448.png)

2. regarding the third point you suggest,  `sparse_AToX_index ` is also in the shared memory.

**Comment by hwu36** [comment]
Does every thread access 32bit data a time from `sparse_A`?  Can you add thread id inside a warp (thread id from 0 to 31) into your diagram to see if you have bank conflict or not?

**Comment by YukeWang96** [comment]
Thanks a lot! I update the thread mapping to the corresponding box.
![main-Page-10 (1)](https://user-images.githubusercontent.com/18487372/105766809-0c461600-5f0f-11eb-943b-682fa218e9d5.png)

**Comment by hwu36** [comment]
yeah, you have bank conflicts.  For example, t0, t8, and t15 conflict each other.

**Comment by YukeWang96** [comment]
Thanks!

I find another problem when two warps are concurrently writing the shared memory even in disjoint space. The data written by the second warp will be lost. Here is my code example. The shared memory space written by warpid-0 is ok, while the data in space written by warpid-1 is lost.

```
for (unsigned idx = warpId + laneid; idx < W * H; idx += warpSize){
          unsigned dense_rowIdx = idx % W;				
          unsigned dense_dimIdx = idx / W;									
          unsigned target_idx = warpId * W * H + idx;
 	  dense_X[target_idx] = in_mat[source_idx];
 }
```

**Comment by YukeWang96** [comment]
> yeah, you have bank conflicts. For example, t0, t8, and t15 conflict each other.

For solving the bank conflict, could you please give me some suggestions? since the `row` and `col` here can only be determined at runtime 

Thanks a lot!

**Comment by hwu36** [comment]
can you just load data that is needed into the shared memory?  If there are dependence between two loads, you can use software pipeline to hide the latency.

**Comment by YukeWang96** [comment]
is there any example/tutorial about the software pipeline in CUDA that I can reference?
Thanks a lot!

**Comment by hwu36** [comment]
Cutlass mainloop used before Ampere uses double buffer in gmem->smem and smem->sm as well.

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_pipelined.h

**Comment by YukeWang96** [comment]
Is there any way that I can use the registers in place of shared memory? 
How can I use the register that they can be shared among all threads from a warp?

Thanks!

**Comment by hwu36** [comment]
you can use shuffle https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-shfl-sync to exchange data between threads belonging to the same warp.

**Comment by YukeWang96** [comment]
Is it possible to embed some PTX assembly in my CUDA code?
For example, at the beginning of each warp. 

1) Allocate a set of registers for each block/warp;
2) Each thread would use these registers based on their thread laneid (i.e., each thread will know which register it will read and write).

Any suggestion or recommendation on this?

**Comment by YukeWang96** [comment]
Also, one more follow up is.

> I am wondering whether the case in wmma::fragment for Tensor Core computation, where all registers from a warps of threads build this fragment, How could I know which register I access from each thread? for example, in thread, when I call a_frag.x[t]. 

In this way, I can simply bypass the shared memory.

**Comment by hwu36** [comment]
> Is it possible to embed some PTX assembly in my CUDA code?
> For example, at the beginning of each warp.
> 
>     Allocate a set of registers for each block/warp;
>     Each thread would use these registers based on their thread laneid (i.e., each thread will know which register it will read and write).
> 
> Any suggestion or recommendation on this?

I don't see how this can work. This also sounds like some registers are wasted.

**Comment by hwu36** [comment]
> How could I know which register I access from each thread?

I don't think you can know that.  You need to use mma ptx like cutlass.
