### ISSUE TITLE
Seems to be a mistake in integer_subtype.h

### ISSUE THREAD

**Issue by qliu93** [NVIDIA/cutlass#172]
Hi, there seems to be a mistake in integer_subtype.h:

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/integer_subbyte.h#L146

Maybe `return rhs < *this;` or `return !(*this <= rhs);` ?

**Comment by hwu36** [comment]
You are right.  Good catch.

Let us go with `!(rhs <= *this)`

**Comment by d-k-b** [comment]
Fixed in 2.5.
