### ISSUE TITLE
[BUG] CMakeLists.txt file is missing a double quote " at Line 237

### ISSUE THREAD

**Issue by Shreya-gaur** [NVIDIA/cutlass#1726]
**Describe the bug**

The CMakeLists.txt file is missing a double quote at Line 237
![image](https://github.com/user-attachments/assets/cd624746-c96c-430f-ae49-46ae8ffac599)

It is causing build issues.

**Comment by thakkarV** [comment]
@shunfan-shao @hwu36

**Comment by thakkarV** [comment]
@Shreya-gaur would you like to make an MR fixing this ?

**Comment by Shreya-gaur** [comment]
Done! 

https://github.com/NVIDIA/cutlass/pull/1727
