### ISSUE TITLE
[QST] How to compile and run `examples/35_gemm_softmax` ? 

### ISSUE THREAD

**Issue by hxdtest** [NVIDIA/cutlass#1728]
**What is your question?**
When I run `examples/35_gemm_softmax`， I use `nvcc  --expt-relaxed-constexpr -I /mnt5/xuantai.hxd/cutlass/include   -I /mnt5/xuantai.hxd/run_cutlass/cutlass_gemm_softmax  -I /mnt5/xuantai.hxd/cutlass/tools/util/include gemm_softmax.cu  -o run  -std=c++17 ` to compile the file. But the ouputs are `void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4] not implemented
Device synchronize failed with error unspecified launch failure`? Is there anything wrong with compile commands?

**Comment by thakkarV** [comment]
Your command line flags are wrong. Please use the cutlass cmake build system or replicate its flags.
