### ISSUE TITLE
example gemm crash

### ISSUE THREAD

**Issue by zhang662817** [NVIDIA/cutlass#174]
for example 14_ampere_tf32_tensorop_gemm:
const int length_m = 5120; --> const int length_m = 2;
const int length_n = 4096; --> const int length_n = 2;
const int length_k = 4096; --> const int length_k = 2;
example crash: 
terminate called after throwing an instance of 'cutlass::cuda_exception'
  what():  std::exception
Aborted (core dumped)

and m = n = k = 1, result is right. Can you help explain it?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-44

**Comment by hwu36** [comment]
In short, the alignment of operands A, B, C, D needs to be aligned with the size of the global load/store.  You can change the load/store size when you set the templates.

Here is what I did to the example to run a 2x2x2 gemm.

```
diff --git a/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu b/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu
index 84eadc5..4282d0c 100644
--- a/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu
+++ b/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu
@@ -85,7 +85,7 @@ using SwizzleThreadBlock = cutlass::gemm::threadblock::GemmIdentityThreadblockSw
 // This code section describes the epilogue part of the kernel
 using EpilogueOp = cutlass::epilogue::thread::LinearCombination<
     ElementOutput,                                     // <- data type of output matrix
-    128 / cutlass::sizeof_bits<ElementOutput>::value,  // <- the number of elements per vectorized
+    2,  // <- the number of elements per vectorized
                                                        // memory access. For a byte, it's 16
                                                        // elements. This becomes the vector width of
                                                        // math instructions in the epilogue too
@@ -109,13 +109,15 @@ using Gemm = cutlass::gemm::device::Gemm<ElementInputA,
                                          ShapeMMAOp,
                                          EpilogueOp,
                                          SwizzleThreadBlock,
-                                         NumStages>;
+                                         NumStages,
+                                         2,
+                                         2>;
 
 int run() {
 
-  const int length_m = 5120;
-  const int length_n = 4096;
-  const int length_k = 4096;
+  const int length_m = 2;
+  const int length_n = 2;
+  const int length_k = 2;
```

This function https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/gemm/kernel/gemm.h#L134 checks the problem size is supported or not.  We can call it inside the example.

**Comment by hwu36** [comment]
I forgot to add that the best perf can be achieved if the problem size is multiple of 16B because we can then use 16B load/store instructions which are most efficient.
