### ISSUE TITLE
[QST]What is @ in cute's step?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1744]
**What is your question?**
    Tensor mA_mkl = mainloop_params.tma_load_a.get_tma_tensor(make_shape(M,K,L)); 
    Tensor gA_mkl = local_tile(mA_mkl, TileShape{}, make_coord(_,_,_), Step<_1, X,_1>{});

ArithTuple(_0,_0,_0) o (2048,2048,1):(_1@1,_1@0,_1@2)
mA_mkl shape
ArithTuple(_0,_0,_0) o (_128,_64,16,32,1):(_1@1,_1@0,_128@1,_64@0,_1@2)
gA_mkl shape
I printed cute's data, what does the @ mean? I think the step here, like mA_mkl, should not be 1?

**Comment by ccecka** [comment]
https://github.com/NVIDIA/cutlass/blob/main/media/docs/cute/0z_tma_tensors.md
