### ISSUE TITLE
[QST]Why copy has barrier inside? And if only one copy will be stuck？

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1748]
**What is your question?**
Why are there barriers inside the copy operation? I tried commenting out one of the copies (A) or (B), and it caused the program to hang. Why does this happen?

![Image](https://github.com/user-attachments/assets/d5dcb6e6-28a5-4093-9a46-4ce79037d85a)

**Comment by thakkarV** [comment]
You need to update the transaction count if you're modifying the size of bytes moved per stage.
