### ISSUE TITLE
[QST] Guidance on Customized Convolution Kernels Using Cutlass3.0 / CuTe

### ISSUE THREAD

**Issue by phantaurus** [NVIDIA/cutlass#1749]
**What is your question?**

I've recently been working on writing kernels using CuTe to perform customized GEMM operations and fuse them into a single kernel. My next goal is to implement a convolution, with the potential to fuse multiple convolutions and GEMMs together.

I've gone through the documentation on implicit GEMM and briefly reviewed the Cutlass implementation. From what I understand, performing convolution might require defining iterators that form a series of loops to execute the correct sequence of GEMMs. (E.g., in a 3x3 convolution, the process probably involves looping 9 times, with global memory Tensors initialized with different offsets each time). It seems that CUTLASS implements this iterator design, which suggests that I may need to familiarize myself with these iterators to write a custom convolution kernel.

However, I also noticed that in CUTLASS 3, cute::Layout subsume the iterators, which makes me wonder if using CuTe alone might be sufficient for this task. (E.g., maybe there is a CuTe API that can just create an overlapping layout with one dimension to be (3,3), which can naturally be used for 3x3 conv? maybe there is an API that handles strides too, given that CuTe layout stride can naturally be used to represent conv strides) Unfortunately, I'm struggling to find examples of convolution implementations using CuTe.

I would greatly appreciate any guidance on the best approach for writing a customized convolution kernel using CUTLASS 3.0.

Thank you so much!

**Comment by thakkarV** [comment]
Yes all of this is covered by the cutlass 3 API for convolutions. Take a look at example 59 to build your understanding and then use the collectives out of cutlass/conv/collective to write your custom fused kernels

**Comment by phantaurus** [comment]
I read example 59 and also checked collective APIs. This is exactly what I need. Thank you so much!
