### ISSUE TITLE
[FEA] FP8 Convolution

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/cutlass#1750]
**Is your feature request related to a problem? Please describe.**
I was wondering if CUTLASS is planning to support FP8 inputs of Conv kernels (output can be FP16 or FP32)

**Describe alternatives you've considered**
TRT already has such kernels:
sm90_xmma_fprop_implicit_gemm_e4m3f16_e4m3f32_f32_nhwckrsc_nhwc_tilesize256x128x64_cgasize1x2x1_warpgroupsize2x1x1_g1_bias_f16_execute_segment_k_off_kernel_trt

Thanks!

**Comment by thakkarV** [comment]
we already support fp8 conv on Hopper OOTB

**Comment by MustafaFayez** [comment]
oh cool, I only tried with cutlass profiler and couldn't find it. Could you point out an example for that?

**Comment by thakkarV** [comment]
they are not generated by the library by default so you won't see them in the profiler, but if you change the element dtypes for A and B to fp8, it will just work.

**Comment by MustafaFayez** [comment]
Thanks a lot!
