### ISSUE TITLE
[FEA] CUDA API [cudaGetDriverEntryPointByVersion]

### ISSUE THREAD

**Issue by SunNy820828449** [NVIDIA/cutlass#1755]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use CUTLASS to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

The api [cudaGetDriverEntryPointByVersion] from MR 1700 can't be found in cuda before 12.5。

**Comment by thakkarV** [comment]
it uses the `cudaGetDriverEntryPoint` API not `cudaGetDriverEntryPointByVersion`

**Comment by SunNy820828449** [comment]
thanks
