### ISSUE TITLE
Finding kernel name

### ISSUE THREAD

**Issue by mahmoodn** [NVIDIA/cutlass#177]
Hi,
In the output of `nsys profile --trace=cuda` of a program, I see this kernel

```
 Time(%)  Total Time (ns)  Instances    Average     Minimum    Maximum                                                    Name                    
 -------  ---------------  ---------  -----------  ---------  ----------  ----------------------------------------------------------------------------------------------------
    32,0   13.508.755.722      2.929  4.612.070,0    356.703  74.678.548  void cutlass::Kernel<cutlass_80_tensorop_s1688gemm_128x128_32x3_nn_align1>(cutlass_80_tensorop_s168…
```
I wasn't able to find that kernel in CUTLASS. I guess the kernel name is composed at runtime. May I know how?

**Comment by manishucsd** [comment]
Kernels are composed by this script by CMAKE command: https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py

You should be able to find kernels in your build folder. Follow the path `$your_build_folder/tools/library/generated/`
