### ISSUE TITLE
[BUG] Simple matrix rotation could not compile

### ISSUE THREAD

**Issue by lucifer1004** [NVIDIA/cutlass#1783]
**Describe the bug**
The following program could not compile:

```cpp
#include "cutlass/matrix.h"

int main() {
  using Element = float;
  cutlass::Matrix<Element, 3, 3> A;
  cutlass::Matrix<Element, 3, 1> B;
  A.rotation(0.2f, B);
}
```

The error was 

```
cutlass/include/cutlass/matrix.h(7828): error: class "cutlass::Matrix<float, 3, 3>" has no member "set_slice3x3"
      m.set_slice3x3({
```

The reason might be that `set_slice3x3` renamed to `set_slice_3x3` but there are still several occurrences remaining. It should be simple to fix.

**Comment by thakkarV** [comment]
yep, seems like it. CC @yzhaiustc @hwu36
