### ISSUE TITLE
[QST] conda or pip package for cutlass missing

### ISSUE THREAD

**Issue by chakpongchung** [NVIDIA/cutlass#1819]
**What is your question?**
Is there a reason why we do not want to have conda or pip package for cutlass? 

I am thinking about using cutlass in a conda environment for a c++ project. pip package could be better if we don't need to resolve difficult dependencies issues through SAT solver in conda

**Comment by leofang** [comment]
conda packages are already available if you do `conda install -c conda-forge cutlass`. What is missing there?

**Comment by leofang** [comment]
The CUTLASS team also maintains a wheel for pip-install: https://pypi.org/project/nvidia-cutlass/

**Comment by chakpongchung** [comment]
Thanks. For some reason they did not show up in my search in conda channel earlier.
