### ISSUE TITLE
DataType Conversion in CUTLASS

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#184]
Hi, All

I am currently looking for the way of data type conversion in CUTLASS.
For example, I have a matrix of `uint32` and I want to convert it to `uint4` for GEMM computation in CUTLASS.
is there any API that can do such conversion directly in CUTLASS?

Thanks!

**Comment by manishucsd** [comment]
This should help: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/numeric_conversion.h

**Comment by hwu36** [comment]
If the number of int32 is multiple of 8, you can use this one to do the conversion https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/numeric_conversion.h#L1129.

The remainder would eventually need to call the constructor of int4b_t to do the conversion https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/integer_subbyte.h#L80

**Comment by YukeWang96** [comment]
Thanks a lot for your help!

I have one more follow up question. I check the function list page of CUTLASS. I notice one entry with 
```
TensorOp | 80 | 11.0+ | s4 * s4 + s32 => {s32, s4} | { T } x { N } => {N,T} | example
```
Does this mean that I can put two `uint4` input matrices and get a `uint4` output matrix for Tensor Core GEMM computation?

**Comment by hwu36** [comment]
Yes.  In cutlass profiler call cutlass_tensorop_u4_i16864gemm_u4_* gemm in ampere and cutlass_tensorop_u4_i8832gemm_u4_* in turing.

**Comment by YukeWang96** [comment]
I notice another thing is that almost all test cases examples use
```
using ElementOutput = int32_t;
using ElementAccumulator = int32_t;
using ElementCompute = int32_t;
```

is it possible to set it to 
```
using ElementOutput = cutlass::int4b_t;
using ElementAccumulator = cutlass::int4b_t;
using ElementCompute = cutlass::int4b_t;
```

to get a `uint4` output matrix?

**Comment by hwu36** [comment]
ElementAccumulator has to be int32 it is decided by the tensor core instruction.
ElementOutput can be set as int4b_t
ElementCompute is usually int32_t or float depends on your alpha, beta value.  If you choose to use float, you need to choose to use clamp version of pointwise epilogue functor.

Here is how we configure cutlass_tensorop_u4_i16864gemm_u4_256x128_128x3_tn_align32

using cutlass_tensorop_u4_i16864gemm_u4_256x128_128x3_tn_align32_base =
  typename cutlass::gemm::kernel::DefaultGemmUniversal<
    cutlass::uint4b_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 32,    // transposed B operand
    cutlass::uint4b_t, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 32,    // transposed A operand
    cutlass::uint4b_t, cutlass::layout::RowMajor,
    int32_t,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 128, 128>,
    cutlass::gemm::GemmShape<64, 64, 128>,
    cutlass::gemm::GemmShape<16, 8, 64>,
    cutlass::epilogue::thread::LinearCombinationClamp<
      cutlass::uint4b_t,
      8,
      int32_t,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    3,
    cutlass::arch::OpMultiplyAddSaturate
>::GemmKernel;

**Comment by YukeWang96** [comment]
Thanks, it works!

I want to call several  `gemm_op()` sequentially, since there is a data dependency between these GEMMs, the output of one GEMM will become the input of the next GEMM.

Should  the `cudaDeviceSynchronize()` also work for CUTLASS?

**Comment by hwu36** [comment]
> Should the cudaDeviceSynchronize() also work for CUTLASS?

Yes.

**Comment by rongzhao-zhang** [comment]
Hi, in numeric_conversion.h, I can only find the conversion methods on scalars or Array classes. How can I perform type conversion directly on Conv operands which is of type TensorRef? Should I first put it in an Array container? Thanks!

**Comment by hwu36** [comment]
I guess your data is still in the (shared|global) memory.  You need to use an `iterator` or anything you have to load the data into a `Fragment` which is essentially an `Array`.  Then you can do the conversion.  `Fragment` is a register backed array.
[Here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L202-L203) is an example of how `Fragment` is defined.

**Comment by rongzhao-zhang** [comment]
Thanks! Let me try.

**Comment by rongzhao-zhang** [comment]
Is that OK to directly convert FP32 to int4b and lower-bit types (int2b and int1b)? I can only find examples converting between FP16 and FP32, or among integer types.

**Comment by hwu36** [comment]
> Is that OK to directly convert FP32 to int4b and lower-bit types (int2b and int1b)? I can only find examples converting between FP16 and FP32, or among integer types.

I haven't tried it myself, but I guess it actually works.  However, I recommend to explicitly to convert `fp32` to `int32` and then `int32` to subbytes so that you can have the fine control of things like rounding mode.

Example code is [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_clamp.h#L393-L401).  The `fp32` to `int32`part needs to move to `NumericArrayConverter` in `numeric_conversion.h`.  PR is welcome.

**Comment by rongzhao-zhang** [comment]
Hi, I find that there is a type conversion example in [conversion.cu](https://github.com/NVIDIA/cutlass/blob/master/test/unit/core/numeric_conversion.cu). It seems that we can use `reinterpret_cast` to directly convert data in global memory to Array. 
```
test::core::kernel::convert<Destination, Source, kN><<< grid, block >>>(
    reinterpret_cast<cutlass::Array<Destination, kN> *>(destination.device_data()),
    reinterpret_cast<cutlass::Array<Source, kN> const *>(source.device_data())
  );
```
Does that mean I don't need Iterators to load data to registers explicitly?

**Comment by hwu36** [comment]
> Does that mean I don't need Iterators to load data to registers explicitly?

You can write your code like the unit test.

**Comment by rongzhao-zhang** [comment]
> > Does that mean I don't need Iterators to load data to registers explicitly?
> 
> You can write your code like the unit test.

Will it be slower than on the register-backed Array? It seems that the unit test code simply reinterprets a pointer on the global memory to an Array pointer, so the operations should happen on the global memory rather than registers. 

Would you mind telling me more about how to use the Iterator? I have read the code for several days but am still at a loss, sorry for my poor C++ background. I have a few element-wise operations to do, such as type conversion, scaling, and rounding, but I cannot figure out which way is optimal. Really appreciate your kind help!

**Comment by rongzhao-zhang** [comment]
Ahh, I see, thank you so much!!!
