### ISSUE TITLE
[QST] example_60 cmake error

### ISSUE THREAD

**Issue by haeunlee99** [NVIDIA/cutlass#1849]
When I set, export CUTLASS_DIR=/disk/cutlass/build/install, and run cmake .. for example_60 in build directory, it gives me this error.

> -- Using CUTLASS specified at /disk/cutlass/build/install.
> CMake Error at /disk/cutlass/build/NvidiaCutlassConfig.cmake:9 (include):
>   include could not find requested file:
> 
>     /disk/cutlass/build/NvidiaCutlassTargets.cmake
> Call Stack (most recent call first):
>   CMakeLists.txt:47 (find_package)
> 
> 
> -- CUTLASS: /disk/cutlass/build/
> -- Configuring incomplete, errors occurred!
> See also "/disk/cutlass/examples/60_cutlass_import/build/CMakeFiles/CMakeOutput.log".

If I set, export CUTLASS_DIR=/disk/cutlass/build, I still get same error. 

When I type "find . -name NvidiaCutlassTargets.cmake" in "/disk/cutlass/build", I get below so NvidiaCutlassTargets.cmake does exist. 

> ./install/lib/cmake/NvidiaCutlass/NvidiaCutlassTargets.cmake
> ./CMakeFiles/Export/lib/cmake/NvidiaCutlass/NvidiaCutlassTargets.cmake

When I change "include("${NvidiaCutlass_CMAKE_DIR}/NvidiaCutlassTargets.cmake")" to "include("/disk/cutlass/build/install/lib/cmake/NvidiaCutlass/NvidiaCutlassTargets.cmake")", it compiles. 

What is the possible issue...? I am new to cmake. Why is "NvidiaCutlass_CMAKE_DIR" not being detected correctly?
I am pretty sure rest of build has succeeded.

**Comment by thakkarV** [comment]
@d-k-b can you help please?

**Comment by thakkarV** [comment]
@haeunlee99 please include your build steps to reproduce this and all relevant software version info

**Comment by haeunlee99** [comment]
I am sorry, but if you don't mind could you help me with below issue instead?
I am adding few logic operations (4 __byte_perm) after copy and before MMA and it gives me significant performance drop. 
(450 / 650 TFLOPS)
I have some unclear understanding about pipeline with I am fixing. 
I seems like adding 14 more logic operations barely gives performance drop so I guess pipeline is destroyed. 
I did temporal resolution to build so this issue can be closed. 

This is another question I posted : 
https://github.com/NVIDIA/cutlass/issues/1852

Thanks!
