### ISSUE TITLE
Why cannot access more than 1 element in contiguous direction

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#186]
https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_analytic.h#L89

Fond at least some cases get passed even comment out this constraint, so what's the reason that put the constraint here?

**Comment by hwu36** [comment]
This assert checks that there is only one iteration to load data in the contiguous dimension (C dimension in NHWC), not one element.   Every thread still loads 128 bit data.

In all the cases that we currently support now, we won't need to have more than 1 iteration.  This iterator is built upon this assumption.  If your customized case needs more than one iteration in the contiguous dimension, you need to change several places.  For example, you need to add one more For-loop in https://github.com/NVIDIA/cutlass/blob/ccb697bac77fcc898e9c897b2c90aa5b60ac72fb/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_analytic.h#L136 to go over the contiguous dimension.

Also, you need to make sure your global memory scheme can match with your shared memory scheme.

**Comment by Peter9606** [comment]
fairly clear now, thanks very much!
