### ISSUE TITLE
[FEA]question about Cute supports uint1b_t GeMM

### ISSUE THREAD

**Issue by CalebDu** [NVIDIA/cutlass#1863]
I want to develop customized fusion GeMM kernel for uint1b_t dtype in Cute.  I note that Cute has no official example and test about uint1b_t GeMM and MMA_Trait only instantiate ```struct MMA_Traits<SM80_16x8x256_S32U1U1S32_TN_XORPOPC>``` with wrong ABLayout. So I create PRs to fix wrong ABLayout and append more supports for MMA_Traits and MMA_op for uint1b_t in PR https://github.com/NVIDIA/cutlass/pull/1856.
After then, I start to implement simple GeMM for uint1b_t. But I find Cute doesn't seem to support subbyte pack and unpack like [SubbyteReference](https://github.com/NVIDIA/cutlass/blob/cc3c29a81a140f7b97045718fb88eb0664c37bd7/include/cutlass/subbyte_reference.h#L106)in Cutlass.  It leads to my customized gemm gets wrong result.
![Image](https://github.com/user-attachments/assets/468e6895-6200-464b-94a3-12a63bf4516e)

To prove it, I do a simple test as above code, I create a ```A```  Cultass tensor with shape (1024, 128) in uint1b_t dype and initialize it with 0x1.  Cutlass support pack 8 uint1b_t into 1 uint8_t. so ```A``` is allocated  1024*128/8 =16 kB memory. Then I use ```A.device_data()``` ptr to build a Cute Tensor. print both A tensor as following.   Cutlass A Tensor print correct result. But Cute A tensor print 255 (0x11111111)  becaute uint1b_t stored in uint8_t without bit pack and unpack. 
 ![Image](https://github.com/user-attachments/assets/47195696-6ec6-4eb2-9e05-9bfb86096c45)
![Image](https://github.com/user-attachments/assets/240a98c8-1b4a-4502-ba03-142728d488d3)

I want to know how cute can support uint1b_t GeMM with pack/unpack to get correct result. I can help submit PR.

**Comment by thakkarV** [comment]
> It leads to my customized gemm gets wrong result.

Not having sub-byte pack/unpack should not lead to the GEMM getting incorrect results if you are using `SM80_16x8x256_S32U1U1S32_TN_XORPOPC` because the MMA itself does not require any unpacking of the bits unless your GMEM inputs are not K major.

**Comment by CalebDu** [comment]
A/B Tensor are both  K major. I find cute has ```array_subbyte.hpp``` to support subbyte dtype. maybe It's not about subbyte packing/unpacking. I need more attempts to locate the problem.

**Comment by ccecka** [comment]
You can create a packed CuTe tensor like this:
```cpp
Tensor mA = make_tensor(make_gmem_ptr<uint1b_t>(my_ptr), my_layout_of_1b);
```
which creates a "packed" pointer from `my_ptr`. Similarly with rmem or smem:
```cpp
Tensor sA = make_tensor(make_smem_ptr<uint1b_t>(my_s_ptr), my_layout_of_1b);
Tensor rA = make_tensor<uint1b_t>(my_layout_of_1b);
```

It looks like you're creating it with a raw `uint1b_t*`? CuTe cannot assume that pointer means "packed" safely.

**Comment by CalebDu** [comment]
@ccecka you're right. The root cause is how to  call```make_gmem_ptr ```. 
![Image](https://github.com/user-attachments/assets/1096846d-3dad-4dba-86b2-9b23211afae4)
I use ```old version``` to initialize cute Tensor in GeMM kernel and  ```print_tensor``` show 255(0x11111111) per uint1b_t element with  wrong GeMM result.
Following your example as ```new version```.  ```print_tensor``` show 1(0x1) per uint1b_t element with correct GeMM result.
![Image](https://github.com/user-attachments/assets/2c0feb4a-c803-445e-9d92-5a5fdd670628)
![Image](https://github.com/user-attachments/assets/a11ad937-836d-4f9f-b0e2-dd15113d2d22)

```new version ``` calls ```recast_ptr```  correctly.  
The CUTE documentation should mention the differences here to avoid other users encountering the same problem
ccecka, thank your help!
