### ISSUE TITLE
Pooling in CUTLASS Conv

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#188]
Hi, All

Is there any option to add the pooling (such as 2x2 max/min/mean pooling) after the cutlass convolution? 

Thanks!

**Comment by hwu36** [comment]
We don't have pooling code now. Want to upstream one?  can be a separate kernel at first. :)

**Comment by YukeWang96** [comment]
Thanks!

is there any existing high-performance implementation of pooling in CUDA? 
I currently know that cuDNN may have this pooling building block, but it is not open-sourced.

**Comment by hwu36** [comment]
Sorry, I don't know.  But I think it is pretty easy to implement.  Just launch as many threads as possible to saturate the memory bandwidth.
