### ISSUE TITLE
[QST] How to reshape or flatten a shape(layout)?

### ISSUE THREAD

**Issue by ZhangZhiPku** [NVIDIA/cutlass#1893]
I can not find a proper method to change the layout of a tensor.

if I have a tensor like:

```
A = cute::Tensor(some_ptr, make_shape(1, 2, 3, 4));
```

I don't know how to merge the axis 1 and axis 2(axis start with 0), and get a tensor like B:[1, 6, 4].

Could you give me an example for doing so?

**Comment by thakkarV** [comment]
"changing" layouts can mean a lot of things. It could either require physical data movement or could be a purely logical transformation of the tensor's view. if it is the former, you have to set up a copy and do the transpose yourself. if it is a logical reinterpretation of the view then composition should take care of it.

```
auto target = make_layout(make_shape(1,6,4));
composition(A, target);
```
