### ISSUE TITLE
[QST] Can I profile a grouped_gemm kernel?

### ISSUE THREAD

**Issue by chenhongyu2048** [NVIDIA/cutlass#1902]
**What is your question?**

Hi all, I would like to know whether I can profile a `grouped_gemm` kernel using the cutlass profile and get its best settings?
I've observed that in the cutlass's example code, it uses default `ThreadblockShape` setting. Is this enough for a good performance? And what should I do if I want to get the best performance possible?
p.s., in my work, only M is changing, while N and K are not.
Thanks for your reply.

**Comment by chenhongyu2048** [comment]
Or it is decided bt calculating the `threadblock_count = Gemm::sufficient(this->options.problem_sizes.data(), this->options.problem_count)`?

**Comment by jackkosaian** [comment]
`cutlass_profiler` does not currently support profiling grouped GEMM kernels. The best way currently is to use [example 24](https://github.com/NVIDIA/cutlass/blob/main/examples/24_gemm_grouped/gemm_grouped.cu) or [example 57](https://github.com/NVIDIA/cutlass/blob/main/examples/57_hopper_grouped_gemm/57_hopper_grouped_gemm.cu), which report runtime, and change the template parameters to fit your example.

**Comment by chenhongyu2048** [comment]
> `cutlass_profiler` does not currently support profiling grouped GEMM kernels. The best way currently is to use [example 24](https://github.com/NVIDIA/cutlass/blob/main/examples/24_gemm_grouped/gemm_grouped.cu) or [example 57](https://github.com/NVIDIA/cutlass/blob/main/examples/57_hopper_grouped_gemm/57_hopper_grouped_gemm.cu), which report runtime, and change the template parameters to fit your example.

Thank you very much for your reply, I think I'll try it later.
