### ISSUE TITLE
[QST]Request for __hsub2-like Function for fp8 Vectorized Subtraction in CUDA

### ISSUE THREAD

**Issue by Zhao-Dongyu** [NVIDIA/cutlass#1903]
Hi CUDA Team,

I am currently working with fp8 data and am looking for a CUDA function similar to __hsub2 that can perform vectorized subtraction specifically for fp8 data types. Given the growing interest in low-precision formats for efficient computations, having native support for fp8 operations would be incredibly useful.

Is there a native CUDA function that can achieve vectorized subtraction for fp8 data? Or, are there plans to include such functionality in future CUDA releases?

Thank you for considering this request!

**Comment by jcao-ai** [comment]
For low precision, I believe most ops(+-*/) results need to be promoted to at least 16 or 32 bit size.  And this is a problem related to hardware/intrinsic team, not cutlass.
