### ISSUE TITLE
[QST] Grouped gemms for float/double

### ISSUE THREAD

**Issue by wajihboukaram** [NVIDIA/cutlass#1916]
Hello, 
I'm trying to use grouped gemms for single and double precision numbers.
I modified the grouped gemm example 24 and modified the types to use floats instead of half precision.

So these lines:
  using ElementA = cutlass::half_t;
  using ElementB = cutlass::half_t;
  using ElementOutput = cutlass::half_t;
  using ElementAccumulator = float;
to these:
  using ElementA = float;
  using ElementB = float;
  using ElementOutput = float;
  using ElementAccumulator = float;

It failed to compile with pages upon pages of compiler errors. For example

/home/wajihbk/cutlass/include/cutlass/gemm/warp/mma_tensor_op_policy.h(58): error: incomplete type "cutlass::arch::Mma<cutlass::gemm::threadblock::DefaultMmaCore<cutlass::gemm::GemmShape<128, 128, 32>, cutlass::gemm::GemmShape<64, 64, 32>, cutlass::gemm::GemmShape<16, 8, 16>, cutlass::gemm::kernel::detail::MapArguments<float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, cutlass::layout::ColumnMajor, true>::ElementA, cutlass::gemm::kernel::detail::MapArguments<float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, cutlass::layout::ColumnMajor, true>::LayoutA, cutlass::gemm::kernel::detail::MapArguments<float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, cutlass::layout::ColumnMajor, true>::ElementB, cutlass::gemm::kernel::detail::MapArguments<float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, cutlass::layout::ColumnMajor, true>::LayoutB, float, cutlass::gemm::kernel::detail::MapArguments<float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 8, cutlass::layout::ColumnMajor, true>::LayoutC, cutlass::arch::OpClassTensorOp, 4, cutlass::gemm::device::DefaultGemmConfiguration<cutlass::arch::OpClassTensorOp, cutlass::arch::Sm80, float, float, float, float>::Operator, false, cutlass::arch::CacheOperation::Always, cutlass::arch::CacheOperation::Always, cutlass::ComplexTransform::kNone, cutlass::ComplexTransform::kNone, false>::InstructionShape, 32, cutlass::tfloat32_t, cutlass::layout::RowMajor, cutlass::tfloat32_t, cutlass::layout::ColumnMajor, float, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>" (aka "cutlass::arch::Mma<cutlass::gemm::GemmShape<16, 8, 16>, 32, cutlass::tfloat32_t, cutlass::layout::RowMajor, cutlass::tfloat32_t, cutlass::layout::ColumnMajor, float, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>") is not allowed
    using MmaShape = typename Operator::Shape;
                              ^

And there's a large amount of these types of errors. I attach the full make log for the modified example.
The original example compiles just fine. 
Can anyone point me in the right direction to resolving these errors or the proper way to use different types of the gemm operands?
Thanks.

[make_log.txt](https://github.com/user-attachments/files/17610235/make_log.txt)

**Comment by jackkosaian** [comment]
The instruction shape template parameter used for the FP16 kernels will not be compatible with those for FP32 and FP64, so that template parameter will need to be changed.

You can see examples of setting these template parameters validly for FP32 [here ](https://github.com/NVIDIA/cutlass/blob/19f51596e8be9fe87d583616466581ab5740c19d/test/unit/gemm/device/gemm_f32n_f32n_f32t_tensor_op_f32_sm80.cu#L60-L81) and FP64 [here](https://github.com/NVIDIA/cutlass/blob/19f51596e8be9fe87d583616466581ab5740c19d/test/unit/gemm/device/gemm_f64n_f64t_f64t_tensor_op_f64_sm80.cu#L57-L78).

**Comment by wajihboukaram** [comment]
Thanks, that seems to work. I had to set the alignment to 4 as well for it to compile. 
Are the template parameters documented somewhere?

**Comment by jackkosaian** [comment]
It's partially outlined [here ](https://github.com/NVIDIA/cutlass/blob/main/media/docs/gemm_api.md) and [here](https://github.com/NVIDIA/cutlass/blob/main/media/docs/terminology.md).
