### ISSUE TITLE
[QST] What does "l" in "mnkl" mean in cutlass?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#1939]
**What is your question?**
Hi! I find some variable name in cutlass's source code contains shorthand `mnkl`, e.g. `blk_coord_mnkl`. What does `l` mean in this shorthand?

**Comment by thakkarV** [comment]
Batch

**Comment by rknoche6** [comment]
Number of splits along the k-dimension.

**Comment by thakkarV** [comment]
@rknoche6 younare incorrect.
