### ISSUE TITLE
[QST] predicate_tensor does not work properly when rank of src and  dst  is 1 in copy_if

### ISSUE THREAD

**Issue by CalebDu** [NVIDIA/cutlass#1940]
I have a src  smem tensor fp16 with ```shape ((8, 1))```  rank 1 and a dst gmem tensor and predicate tensor with same shape as src tensor. I want to invoke  ```copy_if``` with ```Copy_Atom<UniversalCopy<cute::uint128_t>, half>```  and use predicate tensor to handle bound as following code.  
``` c++
copy_if(
    copy_c,
    [&](auto... coords) {
      return elem_less(pred(_0{}, coords...), shape(C));
    },
    src_c, dst_c);
```
But dst tensor result is wrong because predicate_tensor does not work properly when rank of src and  dst  is 1 in copy_if. 
https://github.com/NVIDIA/cutlass/blob/8aa95dbb888be6d81c6fbf7169718c5244b53227/include/cute/algorithm/copy.hpp#L164C1-L166C13

I try to fix it, like following code.  And get correct result.

``` c++
  if constexpr (SrcLayout::rank == 1) {   // Dispatch the copy
    if(pred()) {
      copy_atom.call(src, dst);
    }
  }
```
Is it right for cute ```copy_if```` design? Can I submit PR for this fix ?

**Comment by CalebDu** [comment]
@ccecka

**Comment by ccecka** [comment]
I noticed this a while ago too and just merged in a fix almost identical to your's. That should be released with the next CUTLASS release.

**Comment by CalebDu** [comment]
> I noticed this a while ago too and just merged in a fix almost identical to your's. That should be released with the next CUTLASS release.

I get it.
