### ISSUE TITLE
[QST] Does TMA overlap memory copy from/to global memory address from another GPU return by cudaIpcGetMemHandle?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#1943]
**What is your question?**
Hi! If a global memory address from another GPU (both with P2P and nvlink support)on the same node return by cudaIpcGetMemHandle is passed to cutlass kernel with TMA support, does TMA overlap such inter-GPU memory copy with CUDA Core or Tensor Core? And how does TMA and nvlink finish such memory copy between different GPU?

**Comment by thakkarV** [comment]
TMA knows nothing about the memory being on remote or local GPU.
