### ISSUE TITLE
[QST] How to build specific example kernels?  Fails with "Unknown CMake command "cutlass_example_add_executable""

### ISSUE THREAD

**Issue by lessw2020** [NVIDIA/cutlass#1945]
**What is your question?**
Trying to build a couple kernels in the example and always fails due to:
~~~
Unknown CMake command "cutlass_example_add_executable"
~~~
Have tried from within the example dir itself and from the root of examples, both via the mkdir build / cd build / cmake .. and with and without kernel target.

I recall hitting this issue last time I installed Cutlass and figured it out but have since forgotten...and posting this as it ideally shouldn't be this hard to leverage the examples :)  (a readme in the examples dir to show what to do?) 

Appreciate clarification on how to build a given example kernel.
Thanks!

**Comment by jackkosaian** [comment]
You can find the cmake targets for individual examples [here](https://github.com/NVIDIA/cutlass/blob/8aa95dbb888be6d81c6fbf7169718c5244b53227/examples/CMakeLists.txt#L83).

An example of using this would be:
```bash
git clone git@github.com:NVIDIA/cutlass.git
cd cutlass
mkdir build && cd build
cmake .. -DCUTLASS_NVCC_ARCHS="80"
make 24_gemm_grouped
```

The resulting binary should be in `build/examples/24_gemm_grouped/`

**Comment by lessw2020** [comment]
Hi @jackkosaian  - fantastic, thanks a ton for the info. 
Works like a charm now:
"Built target 24_gemm_grouped"

**Comment by lessw2020** [comment]
closing as resolved.
