### ISSUE TITLE
Peak Performance INT1, INT4, INT8, INT16, INT32 for RTX3090 Tensorcore

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#195]
Hi,

is there any reference for the peak performance of INT1, INT4, INT8, INT16, INT32 for RTX3090 on Tensorcore?
Just want to compare my current CUTLASS GEMM versus the theoretical peak performance.

Thanks!

**Comment by hwu36** [comment]
Others can correct me, but I don't think so.

As to running tensor cores on 3090, see this https://discuss.tvm.apache.org/t/rfc-byoc-nvidia-cutlass-integration/9147/24?u=hwu36

**Comment by YukeWang96** [comment]
Thanks a lot!
