### ISSUE TITLE
[QST]int4b_t dataptr question

### ISSUE THREAD

**Issue by liuyt929** [NVIDIA/cutlass#1955]
**What is your question?**
hi~
excuse me,I have some problems when using s4t_s4n_s4t_sm80 gemm, can I create a **cutlass::int4_b***  data_ptr ,and malloc elements_number/2 byte for it. And create a tensorref for it, then directly use it as the output_ref for the gemm op. 
like this
`cutlass::int4b_t* output_int4;
  cudaMalloc((void**)&output_int4, M*N/2);  
  cutlass::TensorRef<cutlass::int4b_t,cutlass::layout::ColumnMajor> out_ref(
  output_int4,cutlass::layout::ColumnMajor::packed(cutlass::MatrixCoord(M,N)));`

Can I get the right answer if I do so?
I have tried a lot, but the result is always wrong, I wonder how I can receive the result correctly.
Thanks!

**Comment by thakkarV** [comment]
We can't help you debug without proper repro steps
