### ISSUE TITLE
how does the threadblock_tile_offset read the global memory in gemm_splitk_parallel.h ?

### ISSUE THREAD

**Issue by pily1** [NVIDIA/cutlass#1957]
**What is your question?**
I test the example 06_splitK_gemm in 2080ti gpu,I want to know how does the threadblock read the global memory,I debug into the cutlass/include/cutlass/gemm/kernel/gemm_splitk_parallel.h file,I find the typename Mma::IteratorA iterator_A and the mma(gemm_k_iterations,accumulators,iterator_A,iterator_B,accumulators),but I can't find the mma‘s code implementation .
where can I find the mma code implementation ?

**Comment by osayamenja** [comment]
Here's an example instantiation of the [IteratorA](https://github.com/NVIDIA/cutlass/blob/b0e09d7cd371eded41f7c1e057caf1593c27ba55/test/unit/gemm/threadblock/mma_pipelined_testbed.h#L160), you can search for more from within the unit tests directory.

**Comment by pily1** [comment]
@osayamenja think you very much, I find it
