### ISSUE TITLE
Pipeline Stage in GEMM and CONV

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#199]
Hi, All

I benchmarked the GEMM kernel and notice that the pipeline stage could impact the performance a lot. For example, for CUTLASS 1-bit GEMM on RTX3090 compiled with sm80, 3 pipeline stage gives 1060TFLOPs while 4 pipeline stage gives 1227 TFLOPs. 

**Where should I check the implementation of such a pipeline in CUTLASS  GEMM and CONV?**

Thanks!

**Comment by Peter9606** [comment]
Per my understanding, the most important implementation about stages is under threadblock level, so for gemm see [mma_multistage.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_multistage.h) and [mma_pipelined.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_pipelined.h), for conv see [implicit_gemm_pipelined.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_pipelined.h) and [implicit_gemm_multistage.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_multistage.h).

**Comment by hwu36** [comment]
1. When running on 3090, compiled to sm86, not sm80.  Compiler would enable features only exist in sm86.
2. I said earlier, please check https://discuss.tvm.apache.org/t/rfc-byoc-nvidia-cutlass-integration/9147/24?u=hwu36 for running tensor cores on 3090
3. Ampere architecture would require multi-stage software pipeline to implement efficient tensor core kernels.  mma_multistage.h and implicit_gemm_multistage.h listed @Peter9606 are the such mainloops for ampere.  The exact best stage number needs to be tuned for the kernel and the gpu.
