### ISSUE TITLE
[QST] Two questions about warp specialized ping-pong kernel

### ISSUE THREAD

**Issue by danielhua23** [NVIDIA/cutlass#1992]
**What is your question?**
Dear cutlass team,
I wanna consult two questions when I was studying warp specialized ping-pong kernel, below is the screenshot of “Speaking tensor cores" slides，just as what I have circled and framed，I have understood why we should do like it. But my questions are：

1. each Tensor Core Ops always started before each TMA load was done, which part of code implemented it? I guess it is

```  
auto barrier_token = pipeline.consumer_try_wait(smem_pipe_read);
pipeline.consumer_wait(smem_pipe_read, barrier_token);
int read_stage = smem_pipe_read.index();
warpgroup_arrive();
```
 If not, Could you pls point me to the right code?

2. as the pic, data of TMA loads are alternately fed into consumer1 and consumer2, how is it controlled to different consumer? by mainloop_pipeline_consumer_state of each consumer warp group?

Thanks a ton for your time!
![Image](https://github.com/user-attachments/assets/b5d5a5de-38cd-4914-8288-661d9c2011b9)

**Comment by danielhua23** [comment]
cc @jackkosaian @thakkarV

**Comment by thakkarV** [comment]
Yes and yes

**Comment by danielhua23** [comment]
thanks~
