### ISSUE TITLE
[QST]How to Use and Evaluate Prefetch in CUTLASS?

### ISSUE THREAD

**Issue by ziyuhuang123** [NVIDIA/cutlass#1995]
I saw the PREFETCH implementation in cutlass/include, but couldn't find its usage in the examples. Does anyone know how to use it and its effectiveness?

**Comment by thakkarV** [comment]
use and effectiveness of prefetch is extremely workload and kernel specific. YMMV and there isn't any kernel that uses it OOTB in CUTLASS itself
