### ISSUE TITLE
[BUG] Where is 3.6.0 release?

### ISSUE THREAD

**Issue by ankutalev** [NVIDIA/cutlass#2012]
Hello!

According to [CHANGELOG.md](https://github.com/NVIDIA/cutlass?tab=readme-ov-file#cutlass-360) latest version of CUTLASS is 3.6.0, but there is no proper git tag and there is no such release in [releases](https://github.com/NVIDIA/cutlass/releases?q=3.6.0&expanded=true)

I wonder, how the release can disappear.

Thanks!

**Comment by mnicely** [comment]
It has been tagged.
