### ISSUE TITLE
1-bit CONV

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#202]
Hi, All

Is there any available implementation in CUTLASS for 1-bit CONV? 

Thanks!

**Comment by manishucsd** [comment]
Hi, 

We have not tried it in unit tests ourselves. However, all underlying template components should already be implemented.

You are welcome to try it out in the unit tests. You can use the 1-bit threadblock-, warp-, and instruction-shape same as that in [gemm](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_b1t_b1n_s32n_tensor_op_s32_sm80.cu) for the respective arch. 

Let us know if it works just out of the box. 

Best

**Comment by YukeWang96** [comment]
Hi, 

I try two types of settings, but both of them failed at compilation due to something like `incomplete type error`.
The setting I use are

First,
```
using ElementInputA = cutlass::uint1b_t;              // Data type of elements in input tensor
using ElementInputB = cutlass::uint1b_t;              // Data type of elements in input tensor
using ElementOutput = int32_t;              // Data type of elements in output tensor

using LayoutInputA = cutlass::layout::TensorNHWC;
using LayoutInputB = cutlass::layout::TensorNHWC;
using LayoutOutput = cutlass::layout::TensorNHWC;

using MMAOp = cutlass::arch::OpClassTensorOp;
using SmArch = cutlass::arch::Sm80;
using ThreadblockShape = cutlass::gemm::GemmShape<128, 256, 1024>;  // Threadblock tile shape
using WarpShape = cutlass::gemm::GemmShape<64, 64, 1024>;         // Warp tile shape
using InstructionShape = cutlass::gemm::GemmShape<16, 8, 256>;    // TensorCore instruction shape
using SwizzleThreadBlock = cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>;
constexpr int NumStages = 3;
static cutlass::conv::IteratorAlgorithm const IteratorAlgorithm = cutlass::conv::IteratorAlgorithm::kAnalytic;
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationClamp<ElementOutput,
                                                64 / cutlass::sizeof_bits<ElementOutput>::value,
                                                int32_t,
                                                float>;

using Conv2dFpropKernel = typename cutlass::conv::kernel::DefaultConv2dFprop<
  ElementInputA, LayoutInputA,
  ElementInputB, LayoutInputB,
  ElementOutput, LayoutOutput,
  ElementAccumulator,
  MMAOp,
  SmArch,
  ThreadblockShape,
  WarpShape,
  InstructionShape,
  EpilogueOp,
  SwizzleThreadBlock,
  NumStages,
  cutlass::arch::OpMultiplyAddSaturate,
  cutlass::conv::IteratorAlgorithm::kAnalytic
>::Kernel;
```

Second,
```
using ElementInputA = cutlass::uint1b_t;              // Data type of elements in input tensor
using ElementInputB = cutlass::uint1b_t;              // Data type of elements in input tensor
using ElementOutput = int32_t;                            // Data type of elements in output tensor

using LayoutInputA = cutlass::layout::TensorNHWC;
using LayoutInputB = cutlass::layout::TensorNHWC;
using LayoutOutput = cutlass::layout::TensorNHWC;

using MMAOp = cutlass::arch::OpClassTensorOp;
using SmArch = cutlass::arch::Sm75;
using ThreadblockShape = cutlass::gemm::GemmShape<128, 256, 512>;  // Threadblock tile shape
using WarpShape = cutlass::gemm::GemmShape<64, 64, 512>;         // Warp tile shape
using InstructionShape = cutlass::gemm::GemmShape<8, 8, 128>;    // TensorCore instruction shape
using SwizzleThreadBlock = cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>;
constexpr int NumStages = 3;
static cutlass::conv::IteratorAlgorithm const IteratorAlgorithm = cutlass::conv::IteratorAlgorithm::kAnalytic;
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationClamp<ElementOutput,
                                                64 / cutlass::sizeof_bits<ElementOutput>::value,
                                                int32_t,
                                                float>;

using Conv2dFpropKernel = typename cutlass::conv::kernel::DefaultConv2dFprop<
  ElementInputA, LayoutInputA,
  ElementInputB, LayoutInputB,
  ElementOutput, LayoutOutput,
  ElementAccumulator,
  MMAOp,
  SmArch,
  ThreadblockShape,
  WarpShape,
  InstructionShape,
  EpilogueOp,
  SwizzleThreadBlock,
  NumStages,
  cutlass::arch::OpMultiplyAddSaturate,
  cutlass::conv::IteratorAlgorithm::kAnalytic
>::Kernel;
```

Could you please help me to check it? 
Thanks!

**Comment by hwu36** [comment]
You need to change `cutlass::arch::OpMultiplyAddSaturate` to `cutlass::arch::OpMultiplyAdd`.  See https://github.com/NVIDIA/cutlass/blob/50bf00e5f28c96ff8d6408097a6133c3542e411a/include/cutlass/arch/mma_sm80.h#L2010 . 

If you want to test performance, I recommend you to use `cutlass::conv::IteratorAlgorithm::kOptimized` instead of `cutlass::conv::IteratorAlgorithm::kAnalytic`

**Comment by YukeWang96** [comment]
it works now,
Thanks a lot!

**Comment by rongzhao-zhang** [comment]
Hi, thanks a lot for the really helpful questions and answers.
I have a question about the count of the epilogue. 
@hwu36 said that when output is int32, we should use
`128 / cutlass::sizeof_bits<ElementOutput>::value`
but in the unit test `conv2d_fprop_implicit_gemm_s4nhwc_s4nhwc_s32nhwc_tensor_op_s32_sm75.cu`, I find
`
using ElementC           = int32_t;
... ...
cutlass::epilogue::thread::LinearCombination<
  ElementC,
  64 / cutlass::sizeof_bits<ElementC>::value,
  ElementAccumulator,
  ElementCompute
  >,`
Is there a conflict? 
May I know the rule here for the determination of LinearCombination::Count, e.g. for architecture SM75. 
Thanks so much!
Best

**Comment by rongzhao-zhang** [comment]
Besides, in `09_turing_tensorop_conv2dfprop`, when the output type is int4, `using ElementOutput = cutlass::int4b_t;`, the epilogue is 
```
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationClamp<
    ElementOutput,                                     // Data type of output matrix.
    8,                                                 // The number of elements per vectorized.
                                                       // memory access. This becomes the vector width of
                                                       // math instructions in the epilogue too.
    ElementAccumulator,                                // Data type of accumulator
    ElementComputeEpilogue>;                           // Data type for alpha/beta in linear combination
```
Here `LinearCombination::Count` is 8, which equals to `32 / cutlass::sizeof_bits<ElementOutput>::value`. I am quite confused. 
Can anyone help me out?

**Comment by rongzhao-zhang** [comment]
#

> Good question. Ideally, we want to use `128 / cutlass::sizeof_bits<ElementOutput>::value`. 128 stands for the max size (128bit) the store instruction supports. Use 128bit store instruction can reduce the instruction count and fully utilize the memory bandwidth.
> 
> However, if the output size is 4 bit. One 128bit store instructions can output 128/4 = 32 elements. If we let `N` threads to output the elements in the same row, it would require 32N elements in a row. However, we may just don't have enough data in a row sometimes.
> 
> To make things simpler, you can use 128 at first. If you got a compilation error in the epilogue, switch to use 64 or 32.
> 
> We should automate this one day.

Got it. Thanks a lot!
