### ISSUE TITLE
BUG when transfering data from global memory to shared memory

### ISSUE THREAD

**Issue by Light-of-Hers** [NVIDIA/cutlass#203]
The `PredicatedTileIterator` loads data from global memory to register fragment:
https://github.com/NVIDIA/cutlass/blob/50bf00e5f28c96ff8d6408097a6133c3542e411a/include/cutlass/transform/threadblock/predicated_tile_iterator.h#L304-L333
The `RegularTileIterator` stores data from register fragment to shared memory:
https://github.com/NVIDIA/cutlass/blob/50bf00e5f28c96ff8d6408097a6133c3542e411a/include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear.h#L170-L193

Their loop structures are same (outer-loops are through strided dimension; inner-loops are through contiguous dimension). Therefore, when the matrices in global memory and shared memory have different layouts (row-major vs column-major), and `ThreadMap::Iterations::kStrided` and `ThreadMap::Iterations::kContiguous` are all greater than 1, the data loading from global memory will be placed in a wrong place in shared memory.

For example, the following GEMM configuration will cause problems, although it can pass compilation
```C++
using Element = float;
using Layout = cutlass::layout::RowMajor;
using MMAOp = cutlass::arch::OpClassSimt;
using SmArch = cutlass::arch::Sm70;
using ShapeMMAThreadBlock = cutlass::gemm::GemmShape<4, 32, 64>;
using ShapeMMAWarp = cutlass::gemm::GemmShape<4, 32, 64>;

using ShapeMMAOp = cutlass::gemm::GemmShape<1, 1, 1>;
using Gemm =
    cutlass::gemm::device::Gemm<Element, Layout, Element, Layout, Element,
                                Layout, Element, MMAOp, SmArch,
                                ShapeMMAThreadBlock, ShapeMMAWarp, ShapeMMAOp>;
```

**Comment by Peter9606** [comment]
Per my understanding, the key to the correctness of memory is matrix layout, as long as correct layout is used for accessing memory, the major difference doesn't matter.

**Comment by hwu36** [comment]
The issue here is similar to #122 .

To make your case work, you need to do this change to https://github.com/NVIDIA/cutlass/blob/50bf00e5f28c96ff8d6408097a6133c3542e411a/include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear.h#L170-L193

```
@@ -181,13 +181,9 @@ public:
       CUTLASS_PRAGMA_UNROLL
       for (int c = 0; c < ThreadMap::Iterations::kContiguous; ++c) {
 
-        int idx = c + s * ThreadMap::Iterations::kContiguous;
+        int idx = s + c * ThreadMap::Iterations::kStrided;
         access_ptr[c * ThreadMap::Delta::kContiguous /
-                   ThreadMap::kElementsPerAccess] = frag_ptr[idx];
-      }
-
-      if (s + 1 < ThreadMap::Iterations::kStrided) {
-        byte_pointer += increment_strided_;
+                   ThreadMap::kElementsPerAccess + s * increment_strided_ / sizeof(Element)] = frag_ptr[idx];
       }
     }
   }
```
However, it will break other kernels, so we cannot apply this change.  The root cause is that some operand needs transpose (row->col in this case) and the transposed case reuse the same iterator as those that don't need transpose.  This trick only works when the strided iteration after transpose is 1.

I can add an assertion somewhere.

**Comment by Light-of-Hers** [comment]
> The issue here is similar to #122 .
> 
> To make your case work, you need to do this change to
> 
> https://github.com/NVIDIA/cutlass/blob/50bf00e5f28c96ff8d6408097a6133c3542e411a/include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear.h#L170-L193
> 
> ```
> @@ -181,13 +181,9 @@ public:
>        CUTLASS_PRAGMA_UNROLL
>        for (int c = 0; c < ThreadMap::Iterations::kContiguous; ++c) {
>  
> -        int idx = c + s * ThreadMap::Iterations::kContiguous;
> +        int idx = s + c * ThreadMap::Iterations::kStrided;
>          access_ptr[c * ThreadMap::Delta::kContiguous /
> -                   ThreadMap::kElementsPerAccess] = frag_ptr[idx];
> -      }
> -
> -      if (s + 1 < ThreadMap::Iterations::kStrided) {
> -        byte_pointer += increment_strided_;
> +                   ThreadMap::kElementsPerAccess + s * increment_strided_ / sizeof(Element)] = frag_ptr[idx];
>        }
>      }
>    }
> ```
> 
> However, it will break other kernels, so we cannot apply this change. The root cause is that some operand needs transpose (row->col in this case) and the transposed case reuse the same iterator as those that don't need transpose. This trick only works when the strided iteration after transpose is 1.
> 
> I can add an assertion somewhere.

OK. Thanks.
