### ISSUE TITLE
Lack namespace

### ISSUE THREAD

**Issue by zhiqi-0** [NVIDIA/cutlass#205]
Hi, just found in `device_memory.h`
 https://github.com/NVIDIA/cutlass/blob/50bf00e5f28c96ff8d6408097a6133c3542e411a/tools/util/include/cutlass/util/device_memory.h#L266 that potentially misses the namespace `device_memory::` before `copy_device_to_device`.

**Comment by hwu36** [comment]
Do you get any compilation errors.  The caller and the callee are in the same namespace, I think it should be okay.

**Comment by Peter9606** [comment]
> Do you get any compilation errors. The caller and the callee are in the same namespace, I think it should be okay.

Seems caller is in cutlass:: and callee is in cutlass::device_memory::

**Comment by hwu36** [comment]
Yes, you are right.  We will fix it.

**Comment by d-k-b** [comment]
Fixed with https://github.com/NVIDIA/cutlass/pull/251
