### ISSUE TITLE
Using kernels generated by Cutlass

### ISSUE THREAD

**Issue by zhiqi-0** [NVIDIA/cutlass#206]
Hi,
I want to use the kernels generated by cutlass, but I can't find any example code. Specifically, I find generated kernels in `build/tools/library/generated/gemm/`, and I want to use the generated kernel in `cutlass_tensorop_tf32_s1688gemm_tf32_256x128_16x3_tt_align4.cu`. So how can I leverage this kernel for computation?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-43

**Comment by hwu36** [comment]
You can take a look at https://github.com/NVIDIA/cutlass/blob/master/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu.  Change the templates to the ones that used in `cutlass_tensorop_tf32_s1688gemm_tf32_256x128_16x3_tt_align4.cu`

**Comment by zhiqi-0** [comment]
I tried to change the implementation to match with the generated kernel, but it still has some performance gap (~20%). And most of all, I get confused from the output of cutlass_profiler and implementation code in generated kernels:

cutlass_profiler gets the profiling output like this:
```
=============================
  Problem ID: 1

        Provider: CUTLASS
   OperationKind: gemm
       Operation: cutlass_tensorop_s1688gemm_tf32_256x128_16x3_tt_align4

          Status: Success
    Verification: ON
     Disposition: Passed

reference_device: Passed
          cuBLAS: Not run

       Arguments: --gemm_kind=universal --m=384 --n=16000 --k=12288 --A=tf32:row --B=tf32:row --C=f32:column --alpha=1  \
                  --beta=0 --split_k_slices=1 --batch_count=1 --op_class=tensorop --accum=f32 --cta_m=256 --cta_n=128  \
                  --cta_k=16 --stages=3 --warps_m=4 --warps_n=2 --warps_k=1 --inst_m=16 --inst_n=8 --inst_k=8 --min_cc=80  \
                  --max_cc=1024

           Bytes: 829882368  bytes
           FLOPs: 151007232000  flops

         Runtime: 1.4508  ms
          Memory: 532.733 GiB/s

            Math: 104086 GFLOP/s


=============================
```
If I understand it correctly, the `--A=tf32:row and --B=tf:row` are in `RowMajor` layout.

However, the impl in this kernel looks like this:
```c++
using cutlass_tensorop_tf32_s1688gemm_tf32_256x128_16x3_tt_align4_base = 
  typename cutlass::gemm::kernel::DefaultGemmUniversal<
    cutlass::tfloat32_t, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 4,    // transposed B operand
    cutlass::tfloat32_t, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 4,    // transposed A operand
    cutlass::tfloat32_t, cutlass::layout::RowMajor,
    float,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<256, 128, 16>,
    cutlass::gemm::GemmShape<64, 64, 16>,
    cutlass::gemm::GemmShape<16, 8, 8>,
    cutlass::epilogue::thread::LinearCombination<
      cutlass::tfloat32_t,
      4,
      float,
      float
    >,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    3,
    cutlass::arch::OpMultiplyAdd
>::GemmKernel;
```
The layout of matrix A and matrix B is `ColumnMajor`. This looks confusing, and I'm not sure how the layout of Matrix A, Matrix B and Matrix C should be specified.

**Comment by hwu36** [comment]
In fact, Cutlass only implemented row major epilogue which is the same as the tensor core accumulator layout.  To match with cublas, the profiler needs to output column major.  So we do this transform

A:row x B:row = C: col  ---> B:col x A: col = C:row

**Comment by manishucsd** [comment]
Here is some [documentation](https://github.com/NVIDIA/cutlass/blob/master/media/docs/gemm_api.md#efficient-epilogue) on CUTLASS epilogue implementation to help you.

**Comment by zhiqi-0** [comment]
Thanks, now this looks much more clear to me!
