### ISSUE TITLE
Unit tests fails on GTX 1060

### ISSUE THREAD

**Issue by maomran** [NVIDIA/cutlass#21]
I am using GTX 1060 GPU which I think it is Pascal Arch. with CUDA V9.2, I tried to run the  unit test but they all failed.

**Comment by kerrmudgeon** [comment]
We have verified CUTLASS 2.x on the Pascal architecture, and all unit tests are expected to pass. 

Consider checking out the current codebase and trying this again. We also recommend the [CUDA 10.2 Toolkit](https://developer.nvidia.com/cuda-downloads) for best performance.
