### ISSUE TITLE
How to profile gemm parallel split k 

### ISSUE THREAD

**Issue by heathergithub** [NVIDIA/cutlass#215]
Hi,
I didn't find a "split k mode" parameter in the Gemm operation help: "./cutlass_profiler --operation=Gemm --help". 

So when I specify --split_k_slices=4, for example in below profiler command,
./cutlass_profiler --split_k_slices=4 --kernels=cutlass_simt_s8_igemm_s8_128x128_32x2_tt_align1
does it means it's a serial reduction?

How can I profile parallel reuction for gemm operation? 

Thanks!

**Comment by hwu36** [comment]
The profiler currently does not support parallel reduction for gemm now.

**Comment by manishucsd** [comment]
We welcome the addition of parallel reductions to Gemm by the community. 

You can follow Conv2d which does support parallel split-k in the profiler use `--operation=Conv2d --split-k-mode=parallel`
