### ISSUE TITLE
Compilation error in 3D Convolution

### ISSUE THREAD

**Issue by rongzhao-zhang** [NVIDIA/cutlass#224]
Hi, when I was trying to modify a 2D convolution example to a 3D one, I got a compilation error about tile iterator, saying
`cutlass/include/cutlass/conv/threadblock/implicit_gemm_multistage.h(273): error: class "cutlass::transform::threadblock::RegularTileIterator<cutlass::MatrixShape<128, 16>, ElementInputA, cutlass::layout::RowMajorTensorOpMultiplicandCrosswise<16, 16>, 0, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::layout::PitchLinearShape<16, 128>, 128, cutlass::layout::PitchLinearShape<2, 16>, 8>, 16>" has no member "set_iteration_index" 
... ...`

The error trace seems to be:
`result.status = implicit_gemm_op.initialize(arguments, workspace.get());` 
-> 
`cudaError_t result = cudaFuncSetAttribute(cutlass::Kernel<ImplicitGemmKernel>,
                                    cudaFuncAttributeMaxDynamicSharedMemorySize,
                                    smem_size);`
-> 
`op(params, *shared_storage);` -> somewhere I cannot figure out.

The error file and the .cu file are attached here.
[err.txt](https://github.com/NVIDIA/cutlass/files/6257717/err.txt)
[turing_tensorop_conv3dfprop_i8.cu.txt](https://github.com/NVIDIA/cutlass/files/6257720/turing_tensorop_conv3dfprop_i8.cu.txt)

And the compilation command is
`nvcc -forward-unknown-to-host-compiler -DCUTLASS_ENABLE_CUBLAS=1 -DCUTLASS_ENABLE_CUDNN=1 \
	-I/home/rongzhao/github/cutlass/include -I/home/rongzhao/github/cutlass/examples/common \
	-I/home/rongzhao/github/cutlass/build/include -I/usr/local/cuda-10.2/include \
	-I/home/rongzhao/github/cutlass/tools/util/include -O3 -DNDEBUG \
	-Xcompiler=-fPIE -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_TEST_LEVEL=0 -DCUTLASS_DEBUG_TRACE_LEVEL=0 \
	-Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing \
	-gencode=arch=compute_75,code=[sm_75,compute_75] -std=c++11 -MD \
	-x cu \
	-c /home/rongzhao/github/cutlass/examples/09_turing_tensorop_conv2dfprop_my/turing_tensorop_conv3dfprop_i8.cu \
	-o turing_tensorop_conv3dfprop_i8.cu.o`

Could you help me figure out where the problem is? Many thanks to your very kind help!

**Comment by rongzhao-zhang** [comment]
Ahh, I find that if I change `cutlass::conv::IteratorAlgorithm::kOptimized` to `kAnalytic`, then it works! Does this mean there are some bugs in the optimized iterator algorithm? What should I do to use the optimized iterator algorithm? Thanks a lot!

**Comment by hwu36** [comment]
We didn't add sm75 to 3d fprop in `include/cutlass/conv/kernel/default_conv3d_fprop.h`.  Would you please try to add below lines of code

```
--- a/include/cutlass/conv/kernel/default_conv3d_fprop.h
+++ b/include/cutlass/conv/kernel/default_conv3d_fprop.h
@@ -284,6 +284,115 @@ struct DefaultConv3dFprop <
 
 /////////////////////////////////////////////////////////////////////////////////////////////////
 
+/// Defines a kernel for Conv3dFprop specialization for Analytic Iterator Algorithm
+/// and 2 stage pipeline.
+template <
+  typename ElementA,
+  typename LayoutA,
+  typename ElementB,
+  typename LayoutB,
+  typename ElementC,
+  typename LayoutC,
+  typename ElementAccumulator,
+  typename ArchTag,
+  typename ThreadblockShape,
+  typename WarpShape,
+  typename InstructionShape,
+  typename EpilogueOutputOp,
+  typename ThreadblockSwizzle,
+  typename MathOperatorTag
+>
+struct DefaultConv3dFprop <
+  ElementA,
+  LayoutA,
+  ElementB,
+  LayoutB,
+  ElementC,
+  LayoutC,
+  ElementAccumulator,
+  arch::OpClassTensorOp,
+  ArchTag,
+  ThreadblockShape,
+  WarpShape,
+  InstructionShape,
+  EpilogueOutputOp,
+  ThreadblockSwizzle,
+  2,
+  MathOperatorTag,
+  IteratorAlgorithm::kOptimized
+> {
+
+  // Define the core components from GEMM
+  using MmaCore = typename cutlass::gemm::threadblock::DefaultMmaCore<
+      ThreadblockShape, WarpShape, InstructionShape, ElementA, layout::RowMajor,
+      ElementB, layout::ColumnMajor, ElementAccumulator, layout::RowMajor, arch::OpClassTensorOp,
+      2, MathOperatorTag>;
+
+  // Define iterators over tiles from the A operand
+  using ThreadMapA = typename MmaCore::IteratorThreadMapA;
+  using IteratorA =
+    cutlass::conv::threadblock::TileIterator<
+      cutlass::conv::threadblock::Conv3dFpropActivationTileAccessIteratorOptimized<
+        cutlass::MatrixShape<ThreadblockShape::kM, ThreadblockShape::kK>,
+        ElementA,
+        LayoutA,
+        ThreadMapA
+      >
+    >;
+
+  using SmemIteratorA = typename MmaCore::SmemIteratorA;
+
+  // Define iterators over tiles from the B operand
+  using ThreadMapB = typename MmaCore::IteratorThreadMapB;
+  using IteratorB =
+    cutlass::conv::threadblock::TileIterator<
+      cutlass::conv::threadblock::Conv3dFpropFilterTileAccessIteratorOptimized<
+        cutlass::MatrixShape<ThreadblockShape::kK, ThreadblockShape::kN>,
+        ElementB,
+        LayoutB,
+        ThreadMapB
+      >
+    >;
+
+  using SmemIteratorB = typename MmaCore::SmemIteratorB;
+
+  // Warp-level GEMM components
+  using WarpMmaTensorOp = typename MmaCore::MmaTensorOp;
+  using MmaPolicy = typename MmaCore::MmaPolicy;
+
+  // Define the Mma
+  using Mma = threadblock::ImplicitGemmPipelined<
+    ThreadblockShape,
+    IteratorA,
+    SmemIteratorA,
+    IteratorB,
+    SmemIteratorB,
+    ElementC,
+    LayoutC,
+    MmaPolicy
+  >;
+
+  // Define the epilogue
+  using Epilogue = typename detail::DefaultConvEpilogue<
+    ArchTag,
+    ThreadblockShape,
+    WarpMmaTensorOp,
+    1,
+    EpilogueOutputOp
+  >::Epilogue;
+
+  // Define the kernel
+  using Kernel = cutlass::conv::kernel::ImplicitGemmConvolution<
+    Mma,
+    Epilogue,
+    ThreadblockSwizzle,
+    conv::Operator::kFprop,
+    Conv3dProblemSize
+  >;
+};
+
+/////////////////////////////////////////////////////////////////////////////////////////////////
+
```

**Comment by hwu36** [comment]
BTW, you can below line of your code

    64 / cutlass::sizeof_bits<ElementOutput>::value,  // The number of elements per vectorized.

to

    128 / cutlass::sizeof_bits<ElementOutput>::value,  // The number of elements per vectorized.

to improve the epilogue efficiency.

**Comment by rongzhao-zhang** [comment]
Thanks a lot for your code and suggestion! It works now!
