### ISSUE TITLE
Input output channel constraint on INT1 CONV

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#229]
**Hi, All**

I notice a constraint on INT1 CONV, where the input and output channel must be divisible by 128. Otherwise, the CUTLASS CONV execution will crash will a memory access error.

Is this correct?

**Thanks**

**Comment by manishucsd** [comment]
This is true for all data types: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_optimized.h#L393

You can call [cutlass::conv::device::ImplicitGemmConvolutions::can_implement(Arguments const &args)](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/device/implicit_gemm_convolution.h#L94)

to check if your problem size pass the constraints and then call `cutlass::conv::device::ImplicitGemmConvolutions::operator()`

**Comment by hwu36** [comment]
This alignment restriction is easy to relax.  We already did so for gemm.  See this [loop](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_multistage.h#L258-L265) in GEMM , it splits a 128bit load into multiple smaller load.

We welcome a PR to do the same to the convolution.
