### ISSUE TITLE
Question about nvprof result on cutlass_perf_test

### ISSUE THREAD

**Issue by sczhengyabin** [NVIDIA/cutlass#23]
Tested sgemm performance with cutlass_perf_test, the shared_efficiency on pascal cards is around 50%.

How could the shared_efficiency not be 100% when shared_st_bank_conflict and shared_ld_bank_conflict were both 0?

**Comment by kerrmudgeon** [comment]
I think more details would be necessary to diagnose performance problems you may be having.

Generally, many tile sizes are possible which spatially partition the problem into independent threadblocks which then occupy the GPU. If the number of threadblocks is not evenly divisible by the number of Streaming Multiprocessors, tail effects and load imbalance may result in lower average utilization.

You may also consider using CUTLASS 2.x which may have better performance on Pascal cards. Volta and Turing performance, however, is expected to be better than Pascal.

Closing for now. Feel free to reopen.

Thanks!
