### ISSUE TITLE
Implementation of NCDHW layout for 3D convolution

### ISSUE THREAD

**Issue by rongzhao-zhang** [NVIDIA/cutlass#231]
Hi, I am trying to use the CUTLASS library for 3D convolution with PyTorch. As PyTorch uses an `NCDHW` tensor format for 3D convolution, it seems that I have to do dimension permutation for every layer to fit the PyTorch tensors to CUTLASS. May I know whether there is an easy way to implement an `NCDHW` layout in CUTLASS?

Besides, in `include/cutlass/layout/vector.h`, I find there is an `NCHW` layout and an `NCxHWx` layout. What is the difference between them? And in the examples, I find that `NCxHWx` should be used together with the `CxRSKx` layout for weight. What is the rule for selecting compatible activation and weight layout? Can I modify based on `NCxHWx` and `CxRSKx` layouts to get the `NCxDHWx` and `CxRSKTx` layouts which are compatible with PyTorch's 5D tensor?

Many thanks for your kind help!

**Comment by manishucsd** [comment]
Please find all the layouts available for convolutions in the link here:

TensorNHWC 4D tensor layout: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L58
TensorNDHWC 5D tensor layout: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L481
TensorNCHW 4D layout: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L195

To implement TensorNCDHW 5D tensor layout can you follow [TensorNCHW](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L195) and one more dimension after C in NCHW? We welcome a PR for this layout. 

NCxHWx is interleaved layout aimed to improve performance for the integer data types. 
Interleaved layouts (NCxHWx):
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L276
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L375

**Comment by hwu36** [comment]
> I find there is an NCHW layout and an NCxHWx layout. What is the difference between them?

`NCHW` is just like https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L109-L111
In `NCxHWx`, `x=32` for int8 conv and `x=64` for int4 conv.  The definition is in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L331-L333.  It is used together with `CxRSKX`.  Take NC32HW32 as an example, you can view it as this:
The fastest changing dimension is a fixed 32 element `C`,
Next is `W`,
Next is `H`,
Next dimension has fixed `C/32`
Last is `N`
This is the layout used by cuDNN and TensorRT. Note, to use this layout, you need to reorder the filter data as [this](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_testbed_interleaved.h#L168-L169) before the conv kernel to have an efficient epilogue.

**Comment by Peter9606** [comment]
> Please find all the layouts available for convolutions in the link here:
> 
> `TensorNHWC` 4D tensor layout: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L58
> `TensorNDHWC` 5D tensor layout: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L481
> `TensorNCHW` 4D layout: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L195
> 
> To implement `TensorNCDHW` 5D tensor layout can you follow [TensorNCHW](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L195) and add one more dimension `D` after `C` in `NCHW`? We welcome a PR for this layout.

I‘m confused, for so far I can only see the support for NHWC and NCxHWx convolution in current CUTLASS. So to support NCDHW, isn't supporting NCHW the first step?

**Comment by manishucsd** [comment]
There is already an `NCHW` layout implementation in CUTLASS, we are not using the layout in convolution implementation though. We use NHWC for CUTLASS implementation. We also have `NDHWC` layout and convolution 3D implementation using `NDHWC`. However, if you need `NCDHW` layout, you will need to implement the layout first.

**Comment by Peter9606** [comment]
May I ask the reason why NCHW convolution isn't supported in CUTLASS?

**Comment by rongzhao-zhang** [comment]
> There is already an `NCHW` layout implementation in CUTLASS, we are not using the layout in convolution implementation though. We use NHWC for CUTLASS implementation. We also have `NDHWC` layout and convolution 3D implementation using `NDHWC`. However, if you need `NCDHW` layout, you will need to implement the layout first.

Hi, I just tried to use the NCHW layout for 2D convolution, but it did not work.

I modify based on [example 09](https://github.com/NVIDIA/cutlass/blob/master/examples/09_turing_tensorop_conv2dfprop/turing_tensorop_conv2dfprop.cu), the main changes are 1) the layout of activation, filter, and output (to NCHW); 2) the output_size() function; 3) data types. 

My .cu files are
[turing_tensorop_conv2dfprop_f32_nchw.cu.txt](https://github.com/NVIDIA/cutlass/files/6303480/turing_tensorop_conv2dfprop_f32_nchw.cu.txt)
[turing_tensorop_conv2dfprop_i8_nchw.cu.txt](https://github.com/NVIDIA/cutlass/files/6303481/turing_tensorop_conv2dfprop_i8_nchw.cu.txt)
for float and int8_t, respectively. Both files can be compiled successfully with the `cutlass::conv::IteratorAlgorithm::kAnalytic` flag, but failed with the `cutlass::conv::IteratorAlgorithm::kOptimized` flag. I run the programs with specified data shape `--n=16 --c=16 --h=16 --w=16 --k=32 --r=3 --s=3`. And the NHWC version of both files can run well.

For f32 type, the program can run, but the outputs (obtained by setting the `--save-workspace` flag) are all zeros. What's worse, when setting the `--ref-check` flag, it causes core dumped. The error info is shown in [err_f32.txt](https://github.com/NVIDIA/cutlass/files/6303530/err_f32.txt).

For int8_t type, the program failed with `cudaEventSynchronize() failed: misaligned address`, and the outputs are also all zeros.

Could you give me some hints on implementing convolution with the NCHW layout? Thanks a lot!

**Comment by rongzhao-zhang** [comment]
BTW, is there a convienient way to transpose between NCHW and NHWC?

**Comment by hwu36** [comment]
If you want to write a `NCHW` kernel, the first step is attending @manishucsd 's GTC talk today :)

Before you do anything, would you please use nvprof or nsight to see what cuDNN kernel is running behind pytorch?

**Comment by hwu36** [comment]
NHWC vs. NCHW : https://docs.nvidia.com/deeplearning/performance/dl-performance-convolutional/index.html#tensor-layout

**Comment by manishucsd** [comment]
> May I ask the reason that NCHW convolution isn't supported in CUTLASS?

We also recommend the talk this GTC 2021: [Tensor Core Performance on NVIDIA GPUs: The Ultimate Guide [S32008]](https://gtc21.event.nvidia.com/media/Tensor%20Core%20Performance%20on%20NVIDIA%20GPUs%3A%20The%20Ultimate%20Guide%20%5BS32008%5D/1_n10ea3ct)

**Comment by rongzhao-zhang** [comment]
> If you want to write a `NCHW` kernel, the first step is attending @manishucsd 's GTC talk today :)
> 
> Before you do anything, would you please use nvprof or nsight to see what cuDNN kernel is running behind pytorch?

1) May I know the title of @manishucsd 's GTC talk? Thanks!

2) I use nvprof on a sample pytorch script (just repeats a 2D convolution). It seems to be working on the `winograd_nonfused` kernel. The following is the output 
```
==23775== NVPROF is profiling process 23775, command: python main.py 10000
==23775== Profiling application: python main.py 10000
==23775== Warning: 311 records have invalid timestamps due to insufficient device buffer space. You can configure the buffer space using the option --device-buffer-size.
==23775== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   34.79%  999.01ms      9938  100.52us  97.408us  109.09us  volta_sgemm_128x64_nn
                   28.91%  830.35ms      9938  83.552us  81.088us  87.519us  void cudnn::winograd_nonfused::winogradForwardOutput4x4<float, float>(cudnn::winograd_nonfused::WinogradOutputParams<float, float>)
                   17.70%  508.30ms      9938  51.146us  49.056us  57.120us  void cudnn::winograd_nonfused::winogradForwardData4x4<float, float>(cudnn::winograd_nonfused::WinogradDataParams<float, float>)
                   17.40%  499.67ms      9937  50.283us  49.568us  52.768us  _ZN2at6native27unrolled_elementwise_kernelIZZZNS0_15add_kernel_cudaERNS_14TensorIteratorEN3c106ScalarEENKUlvE_clEvENKUlvE2_clEvEUlffE_NS_6detail5ArrayIPcLi3EEE16OffsetCalculatorILi2EjESD_ILi1EjENS0_6memory15LoadWithoutCastENSG_16StoreWithoutCastEEEviT_T0_T1_T2_T3_T4_
                    1.18%  33.768ms      9938  3.3970us  3.0720us  13.216us  void cudnn::winograd_nonfused::winogradForwardFilter4x4<float, float>(cudnn::winograd_nonfused::WinogradFilterParams<float, float>)
                    0.03%  756.90us         4  189.22us  1.0560us  747.58us  [CUDA memcpy HtoD]
                    0.00%  6.5920us         4  1.6480us  1.5680us  1.8240us  [CUDA memset]
      API calls:   51.35%  2.84516s        10  284.52ms  6.3620us  2.84472s  cudaMalloc
                   40.92%  2.26722s     50000  45.344us  3.2740us  404.83us  cudaLaunchKernel
                    6.01%  333.09ms         4  83.272ms     457ns  194.33ms  cudaFree
                    1.25%  69.416ms    250033     277ns     206ns  348.19us  cudaGetDevice
                    0.24%  13.055ms     10000  1.3050us  1.1360us  24.706us  cudaEventRecord
                    0.13%  7.1522ms     40000     178ns     104ns  275.14us  cudaGetLastError
                    0.03%  1.3979ms         6  232.98us  170.77us  333.24us  cuDeviceTotalMem
                    0.02%  1.3466ms       570  2.3620us     103ns  138.96us  cuDeviceGetAttribute
                    0.02%  1.0264ms         4  256.60us  238.46us  269.72us  cudaGetDeviceProperties
                    0.01%  792.50us         3  264.17us  7.4160us  756.31us  cudaMemcpyAsync
                    0.01%  431.49us         1  431.49us  431.49us  431.49us  cudaHostAlloc
                    0.00%  153.55us         6  25.591us  16.635us  37.625us  cuDeviceGetName
                    0.00%  117.91us         8  14.738us  1.3450us  100.71us  cudaStreamCreateWithFlags
                    0.00%  104.03us         3  34.677us  4.6160us  89.002us  cudaStreamSynchronize
                    0.00%  63.500us       169     375ns     279ns  1.8300us  cudaFuncSetAttribute
                    0.00%  40.155us         4  10.038us  5.0800us  22.967us  cudaMemsetAsync
                    0.00%  11.818us        28     422ns     326ns  1.2760us  cudaEventCreateWithFlags
                    0.00%  10.681us         1  10.681us  10.681us  10.681us  cudaMemcpy
                    0.00%  8.9920us        29     310ns     219ns  1.0280us  cudaDeviceGetAttribute
                    0.00%  6.3410us        34     186ns     139ns     672ns  cudaGetDeviceCount
                    0.00%  5.9300us         2  2.9650us  2.5540us  3.3760us  cuDeviceGetPCIBusId
                    0.00%  5.9140us         4  1.4780us  1.2940us  1.6720us  cudaStreamCreateWithPriority
                    0.00%  4.0080us         3  1.3360us     621ns  2.4120us  cudaSetDevice
                    0.00%  2.2990us         8     287ns     128ns     680ns  cuDeviceGet
                    0.00%  1.9300us         5     386ns     245ns     820ns  cuDeviceGetCount
                    0.00%  1.4780us         6     246ns     155ns     423ns  cuDeviceGetUuid
                    0.00%  1.3620us         1  1.3620us  1.3620us  1.3620us  cudaHostGetDevicePointer
                    0.00%  1.2080us         1  1.2080us  1.2080us  1.2080us  cudaDeviceGetStreamPriorityRange
                    0.00%  1.2000us         2     600ns     574ns     626ns  cuInit
                    0.00%     871ns         2     435ns     312ns     559ns  cuDriverGetVersion
```

**Comment by illava** [comment]
> > There is already an `NCHW` layout implementation in CUTLASS, we are not using the layout in convolution implementation though. We use NHWC for CUTLASS implementation. We also have `NDHWC` layout and convolution 3D implementation using `NDHWC`. However, if you need `NCDHW` layout, you will need to implement the layout first.
> 
> Hi, I just tried to use the NCHW layout for 2D convolution, but it did not work.
> 
> I modify based on [example 09](https://github.com/NVIDIA/cutlass/blob/master/examples/09_turing_tensorop_conv2dfprop/turing_tensorop_conv2dfprop.cu), the main changes are 1) the layout of activation, filter, and output (to NCHW); 2) the output_size() function; 3) data types.
> 
> My .cu files are
> [turing_tensorop_conv2dfprop_f32_nchw.cu.txt](https://github.com/NVIDIA/cutlass/files/6303480/turing_tensorop_conv2dfprop_f32_nchw.cu.txt)
> [turing_tensorop_conv2dfprop_i8_nchw.cu.txt](https://github.com/NVIDIA/cutlass/files/6303481/turing_tensorop_conv2dfprop_i8_nchw.cu.txt)
> for float and int8_t, respectively. Both files can be compiled successfully with the `cutlass::conv::IteratorAlgorithm::kAnalytic` flag, but failed with the `cutlass::conv::IteratorAlgorithm::kOptimized` flag. I run the programs with specified data shape `--n=16 --c=16 --h=16 --w=16 --k=32 --r=3 --s=3`. And the NHWC version of both files can run well.
> 
> For f32 type, the program can run, but the outputs (obtained by setting the `--save-workspace` flag) are all zeros. What's worse, when setting the `--ref-check` flag, it causes core dumped. The error info is shown in [err_f32.txt](https://github.com/NVIDIA/cutlass/files/6303530/err_f32.txt).
> 
> For int8_t type, the program failed with `cudaEventSynchronize() failed: misaligned address`, and the outputs are also all zeros.
> 
> Could you give me some hints on implementing convolution with the NCHW layout? Thanks a lot!

IMO, simply change layout is not working, the output is by default row major(GEMM_M * GEMM_N) and doesn't take any layout information.

one simplest implantation for this is like (for fprop implicit img2col nchw)
```c++
// for fprop
int GEMM_M = N ;
int GEMM_N = K * P * Q;
int GEMM_K = C * H * W; // take too much space
for (int gemm_m = 0; gemm_m < GEMM_M; ++gemm_m)
{
    int n = gemm_m;
    for (int gemm_n = 0; gemm_n < GEMM_N; ++gemm_n)
    {
        int k = gemm_n / (P * Q);
        int kpq_residual = gemm_n % (P * Q);
        int p = kpq_residual / Q;
        int q = kpq_residual % Q;
        Accumulator accum = 0;
        for (int gemm_k = 0; gemm_k < GEMM_K; ++gemm_k)
        {
            int c = gemm_k / (H * W);
            int chw_residual = gemm_k % (H * W);
            int h = chw_residual / W;
            int w = chw_residual % W;

            int r = (h - p * stride_h + pad_h) / dilation_h; // is filter_tensor set to 0 for not divide up ?
            int s = (w - q * stride_w + pad_w) / dilation_w;

            if (mode == convolution) {r = R - 1 - r; s = S - 1 - s;}

            ElementA a = activation_tensor.at({n, c, h, w});
            ElementB b = filter_tensor.at({k, c, r, s});
            accum += a * b;
        }
        C[gemm_m * K + gemm_n] = accum;
    }
}
```

**Comment by rongzhao-zhang** [comment]
> IMO, simply change layout is not working, the output is by default row major(GEMM_M * GEMM_N) and doesn't take any layout information.
> 
> one simplest implantation for this is like (for fprop implicit img2col nchw)
> ...
Yes, but I think in CUTLASS things are arranged in a hierarchical and abstract way. It seems that the low-level code underneath the NCHW layout hasn't been implemented, so it is problematic to simply change NHWC to NCHW.

**Comment by hwu36** [comment]
> May I know the title of @manishucsd 's GTC talk? Thanks!

https://github.com/NVIDIA/cutlass/discussions/223

A little more about NHWC vs. NCHW from cuDNN's perspective

https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#tensor-ops-tensor-transformations-conversion

**Comment by rongzhao-zhang** [comment]
> > May I know the title of @manishucsd 's GTC talk? Thanks!
> 
> #223
> 
> A little more about NHWC vs. NCHW from cuDNN's perspective
> 
> https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#tensor-ops-tensor-transformations-conversion

Thanks!

**Comment by mnicely** [comment]
@rongzhao-zhang we you able to get NCDHW implemented?

**Comment by FabianSchuetze** [comment]
Thanks for the wonderful discussion here. 

When working with tensor provided by pytorch, you recommend transposing them before using the cutlass convolution? Do you have a sample code I could learn from for the transposition kernel? Also related to #344 .

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/main/tools/util/include/cutlass/util/device_nchw_to_nhwc.h
