### ISSUE TITLE
Is conv2d kernel initialization time measured in cutlass profile?

### ISSUE THREAD

**Issue by illava** [NVIDIA/cutlass#232]
Conv2d profiler is calling the `run(stream)` method and seems does not have the initialization? When do initialization take place and is it measured in cutlass profiling loops?

The `memset` for parallel split-k is not necessary and costly, BTW.
https://github.com/NVIDIA/cutlass/blob/c77a52445972fd52210d718d5cc606b37b117e56/include/cutlass/conv/device/implicit_gemm_convolution.h#L170

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-39

**Comment by hwu36** [comment]
`initialize()` is called [here](https://github.com/NVIDIA/cutlass/blob/master/tools/profiler/src/conv2d_operation_profiler.cu#L665-L668) which is not included in the profiling run.
