### ISSUE TITLE
Missed avoiding duplicated include 

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#233]
https://github.com/NVIDIA/cutlass/blob/c77a52445972fd52210d718d5cc606b37b117e56/include/cutlass/transform/thread/transpose.h#L29

`#pragma once` is missed

**Comment by hwu36** [comment]
PR please? :)

btw, a better way is to use intrinsic `__byte_perm` (https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__INT.html#group__CUDA__MATH__INTRINSIC__INT_1g0b8b8156fe619205bf8d65acd8f29131) instead of inline ptx `prmt` in this file.

**Comment by hwu36** [comment]
example is here: https://github.com/NVIDIA/cutlass/blob/c77a52445972fd52210d718d5cc606b37b117e56/include/cutlass/numeric_conversion.h#L1303-L1305

**Comment by hwu36** [comment]
It was fixed.
