### ISSUE TITLE
With Int8x32, 16_ampere_tensorop_conv2dfprop has results miscompared

### ISSUE THREAD

**Issue by ocwins** [NVIDIA/cutlass#234]
I copied the source code and made some modifications to test if it's working with Int8x32 configuration.

```
using ElementAccumulator = int32_t;        // Data type of accumulator
using ElementComputeEpilogue = float;              // Data type of epilogue computation (alpha, beta)
using ElementInputA = int8_t;             // Data type of elements in input tensor
using ElementInputB = int8_t;             // Data type of elements in input tensor
using ElementOutput = int8_t;                       // Data type of elements in output tensor

using LayoutInputA = cutlass::layout::TensorNCxHWx<32>; 
using LayoutInputB = cutlass::layout::TensorCxRSKx<32>; 
using LayoutOutput = cutlass::layout::TensorNCxHWx<32>;
```

```
 Options() :
        help(false),
        input_size(256, 10, 9, 256),
        filter_size(256, 3, 3, 256),
        padding(1, 1, 1, 1),
        conv_stride(1, 1),
        dilation(1, 1),
        reference_check(true),
        measure_performance(true),
        iterations(20),
        save_workspace(false),
        alpha(1),
        beta(0),
        benchmark(false) { }
```

With TensorNHWC, it passed. Do I miss something ?

**Comment by ocwins** [comment]
I have tried reordering tensor b, but it didn't work too.
```

 cutlass::reorder_convK<32, 32>(
        tensor_b_reordered.host_ref(), tensor_b.host_ref(), implicit_gemm_problem_size(Conv2dFpropKernel::kConvolutionalOperator, problem_size));
    tensor_b_reordered.sync_device();

    // Construct ImplicitGemm::Argument structure with conv2d 
    // problem size, data pointers, and epilogue values
    typename ImplicitGemm::Arguments arguments{
      problem_size,
      tensor_a.device_ref(),
      tensor_b_reordered.device_ref(),
      tensor_c.device_ref(),
      tensor_c.device_ref(),
      {options.alpha, options.beta},
        };
    
```

**Comment by hwu36** [comment]
Have you changed your epilogue elementwise to something like this

```
    cutlass::epilogue::thread::LinearCombinationClamp<
      ElementC,
      64 / cutlass::sizeof_bits<ElementC>::value,
      ElementAccumulator,
      ElementCompute                                                                                  
    >,
```

you need to use `LinearCombinationClamp` to prevent float->int overflow.  You need to use `64` instead of `128` which is required by the interleaved layout.

You also need to use `cutlass::arch::OpMultiplyAddSaturate` instead of `cutlass::arch::OpMultiplyAdd` which also prevents int overflow.

Have you changed the instruction shape to 16x8x32 the size of int tensor op?

This also looks strange `reorder_convK<32, 32>`.  I think you just need one `32`.

You can take a look at our unit test as an example: https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32_sm80.cu

**Comment by ocwins** [comment]
> 
> 
> Have you changed your epilogue elementwise to something like this
> 
> ```
>     cutlass::epilogue::thread::LinearCombinationClamp<
>       ElementC,
>       64 / cutlass::sizeof_bits<ElementC>::value,
>       ElementAccumulator,
>       ElementCompute                                                                                  
>     >,
> ```
> 
> you need to use `LinearCombinationClamp` to prevent float->int overflow. You need to use `64` instead of `128` which is required by the interleaved layout.
> 
> You also need to use `cutlass::arch::OpMultiplyAddSaturate` instead of `cutlass::arch::OpMultiplyAdd` which also prevents int overflow.
> 
> Have you changed the instruction shape to 16x8x32 the size of int tensor op?
> 
> This also looks strange `reorder_convK<32, 32>`. I think you just need one `32`.
> 
> You can take a look at our unit test as an example: https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32_sm80.cu

I have changed these settings, but I may not be careful enough, I will check again.

btw, the “run_nonfused_conv2d_fprop_optimized_s8_sm80” in example "13_two_tensor_op_fusion" passed with “Release" configuration but failed with "Debug"  (VS2019), which is weird.

**Comment by ocwins** [comment]
> you need to use `LinearCombinationClamp` to prevent float->int overflow. You need to use `64` instead of `128` which is required by the interleaved layout.

Thank you. 

I just changed the ConverterOp of reference implementation (from NumericConverter to NumericConverterClamp)， but forgot this one. Then I changed almost everything in several hours but not this one because I thought I have changed it.

**Comment by ocwins** [comment]
> 
> This also looks strange `reorder_convK<32, 32>`. I think you just need one `32`.
> 

I have a question about the need of reordering. In my understanding, the Tensors and Views already carried layout information, and the data generated in these examples are meaningless, why do we need reorder their contents ?

**Comment by hwu36** [comment]
To make sure every thread has 8 consecutive int8_t elements in the registers.  Then we don't need to go through the shared memory and just dump these 8 elements to the global memory directly.  This is also why we use `64` in the epilogue which stands for 64bitt per store.

**Comment by ocwins** [comment]
> 
> 
> To make sure every thread has 8 consecutive int8_t elements in the registers. Then we don't need to go through the shared memory and just dump these 8 elements to the global memory directly. This is also why we use `64` in the epilogue which stands for 64bitt per store.

I know this. 

What I mean is that: with meaningless generated data, without reordering,  kernels can run well and give results.  Could we directly use B as they are correctly ordered ? After all the data are randomly generated.

Why do we need reordering data in this case ? because the reference implementation need reordering to get same results ?

**Comment by hwu36** [comment]
> because the reference implementation need reordering to get same results ?

Yes.

We can create a new layout to do the reordering under the hood, but it is not there now.
