### ISSUE TITLE
Code improvement about iterators' parameter of convolution

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#238]
Reading the code about iterators' parameter of convolution makes me fell some inconsistent

- The way of constructing parameter is different for iterator A and B,  obtain via `getParams()` vs. delegated in iterator constructor
- Long name param got aliased to 'Params' but isn't used, Ex. `Conv2dFpropActivationIteratorOptimizedParams<Layout>`
- Plain Params is defined multiple times, Ex `Conv3dDgradOutputGradientTileAccessIteratorAnalytic::Params`, `Conv3dDgradFilterTileAccessIteratorAnalytic::Params`
- Not all parameters definitions are concentrated into convXd_params.h

Are those on purpose or need a tidy up?

**Comment by hwu36** [comment]
These are due to some internal reasons.  They will be changed in the future.
