### ISSUE TITLE
Does Template argument ElementC conceptually overlap with ElementAccumulator?

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#244]
https://github.com/NVIDIA/cutlass/blob/c77a52445972fd52210d718d5cc606b37b117e56/include/cutlass/conv/kernel/default_conv2d_fprop.h#L50-L71

When `ElementC` is used, it's used as accumulator data type passed to `threadblock::ImplictGemmPiplined`, then why not use `ElementAccumulator` instead? I also observed that `ElementC` isn't used anywhere in a definition that is for multiple stage gemm. Do they conceptually overlap with each other?

**Comment by hwu36** [comment]
`ElementC` is the data type of tensor `C` and `D` in the global memory.  `ElementAccumulator` is the data type used to do `mma`.  These two can be different.

Currently `threadblock::ImplictGemmPiplined` requires to pass in `ElementC` (it is not actually used inside `threadblock::ImplictGemmPiplined`), but `threadblock::ImplictGemmPiplined` does not require it.

**Comment by Peter9606** [comment]
> `ElementC` is the data type of tensor `C` and `D` in the global memory. `ElementAccumulator` is the data type used to do `mma`. These two can be different.
> 

Why does conv op need a tensor `C`?

**Comment by Peter9606** [comment]
> Currently `threadblock::ImplictGemmPiplined` requires to pass in `ElementC` (it is not actually used inside `threadblock::ImplictGemmPiplined`), but `threadblock::ImplictGemmPiplined` does not require it.

I see what you mean, but isn't a better way that just eliminate the requirement of `ElementC` from `threadblock::ImplicitGemmPipelined`?

**Comment by Peter9606** [comment]
> Currently `threadblock::ImplictGemmPiplined` requires to pass in `ElementC` (it is not actually used inside `threadblock::ImplictGemmPiplined`), but `threadblock::ImplictGemmPiplined` does not require it.

I see what you mean, but isn't a better way that just eliminate the requirement of `ElementC` from `threadblock::ImplicitGemmPipelined`?

**Comment by hwu36** [comment]
`ElementC` is not and should not be used inside `threadblock::ImplicitGemmPipelined`, but sometimes having some redundant template arguments around can make things convenient.

For example, if some struct uses `threadblock::ImplicitGemmPipelined`, then it can get `ElementC` pretty easily.

I don't have strong feelings of keeping it or deleting it.  If you don't like it, feel free to delete it and see if everything builds and then create a PR.

**Comment by Peter9606** [comment]
> `ElementC` is not and should not be used inside `threadblock::ImplicitGemmPipelined`, but sometimes having some redundant template arguments around can make things convenient.
> 
> For example, if some struct uses `threadblock::ImplicitGemmPipelined`, then it can get `ElementC` pretty easily.
> 

Thanks for your explanation.

> I don't have strong feelings of keeping it or deleting it. If you don't like it, feel free to delete it and see if everything builds and then create a PR.

I'm totally okay with this redundant.
