### ISSUE TITLE
[FEA] Would group conv be supported in cutlass future release?

### ISSUE THREAD

**Issue by ginowu** [NVIDIA/cutlass#248]
As group convolution is one important operator(eg. in ResNext: https://arxiv.org/pdf/1611.05431.pdf) in CV models, is there any plan to support it in future release?

Thanks a lot!

**Comment by hwu36** [comment]
not in 2.6 :smile:

**Comment by decioren** [comment]
I'd like to have that one too... 2.7??

**Comment by hwu36** [comment]
Noted.

I know cutlass is hot.  It is used by many researchers and productised by quite a few companies.  We get requests to add new functionalities all the time.

One thing that the community can do to help us to fulfil these requests is that creating more PRs, making more clones, giving us more github stars, making your success story with cutlass public.  Your support is very valuable to us. :smile:

**Comment by yxchng** [comment]
any updates on this?

**Comment by hwu36** [comment]
We are working on this.  @loo-loo

**Comment by hwu36** [comment]
group conv is supported in 2.10.  we will keep improving it.
