### ISSUE TITLE
Potentially redundant assignment of `threadblock_tile_{offset,idx}`?

### ISSUE THREAD

**Issue by jackkosaian** [NVIDIA/cutlass#249]
Hi all,

In the both `include/cutlass/gemm/kernel/gemm_universal.h` and `include/cutlass/conv/kernel/implicit_gemm.h`, the variables `threadblock_tile_offset` and `threadblock_tile_idx` appear to be set identically and redundantly:

`include/cutlass/gemm/kernel/gemm_universal.h`: [first assignment](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L345), [second assignment](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L453)
`include/cutlass/conv/kernel/implicit_gemm.h`: [first assignment](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/implicit_gemm_convolution.h#L262), [second assignment](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/implicit_gemm_convolution.h#L329)

My apologies if this is by design -- I haven't dug through to see if there are cases where any difference between the two calls is expected.

Thanks,
Jack

**Comment by hwu36** [comment]
Yes, we need to do some refactoring work in the device level code.  But, we will defer that after 2.6 release.

**Comment by jackkosaian** [comment]
Got it. Thanks!
