### ISSUE TITLE
Is there a way to fill a tensor with another tensor?

### ISSUE THREAD

**Issue by zheng95z** [NVIDIA/cutlass#252]
Like if we have a tensor:
`cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> dst({1024, 128})`
can we fill it with another tensor:
`cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> src({1, 128})`

**Comment by hwu36** [comment]
I don't think so.  But you can use `host_data()` (https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/host_tensor.h#L238) to get the pointer to do anything you like.

**Comment by hwu36** [comment]
A more elegant way is to use `host_view()` to get `TesnorView` to initialize data like what is did in https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/reference/host/tensor_fill.h
