### ISSUE TITLE
wrong result of simt gemm with 128x128x16 tile size

### ISSUE THREAD

**Issue by FindDefinition** [NVIDIA/cutlass#254]
Params:
float32 Simt
TileShape: 128, 128, 16
Warp Shape: 32, 64, 16
TTT (row major, row major, row major)

when use 128x128x16 tile size, the padding of smem A is 2, so the stride of smem iter A is 130, but the lane mma shape is still 4.
the stride in this [stmt](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_simt_tile_iterator.h#L177) isn't divisible by lane mma shape.

**Comment by hwu36** [comment]
Just as you said, this tile size is not supported.  We can add a static_assert somewhere.

**Comment by FindDefinition** [comment]
I solve this problem by add a sub access, use padding as element per access if padding is smaller than previous element per access.
this [unit test](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/simt_sgemm_tt_sm50.cu#L1641) shouldn't pass too. is this test passed in your environment?

**Comment by hwu36** [comment]
This test failed in my end too.  I guess we never really tested any non L0 tests.

I am afraid even your sub access solution can run this tile size, but it still has bank conflict problem.

**Comment by FindDefinition** [comment]
you are right, i will remove this tile size in my code.

**Comment by FindDefinition** [comment]
@hwu36 I have finished my python simulator of gemm with auto bank conflict detection, no bank conflict defected when using sub access.
so the problem of 128x128x16 should be waste of selectors, not bank conflict?

**Comment by hwu36** [comment]
What do you see when you run with nsignt/nvopt? Any bank conflicts?

What do you mean "waste of selectors"?

**Comment by FindDefinition** [comment]
@hwu36 
I use nvprof to find bank conflicit:
```sudo nvprof --events shared_ld_bank_conflict,shared_st_bank_conflict ```
and find no bank conflicit for 128x128x16/32x64x16, 64x64x16/32x32x16 and 64x128x16/32x64x16:
```
    Kernel: gemm::main::Simt_f32f32f32f32f32nnn_m64n128k16m32n64k16_2::gemm_kernel(gemm::main::gpSimt_f32f32f32f32f32nnn_m64n128k16m32n64k16_2::GemmParams)
          1                   shared_ld_bank_conflict           0           0           0           0
          1                   shared_st_bank_conflict           0           0           0           0
```
the selectors is described in GTC ppt (volta arch). I'm not familiar with it.
