### ISSUE TITLE
Conv2d performance issue for large n & for small c and k.

### ISSUE THREAD

**Issue by zheng95z** [NVIDIA/cutlass#255]
Dear community,

I'm currently doing an inference task with Conv2d and Gemm using an RTX TITAN.

The Gemm part works very well, with problem size {64, 1280*720, 128}:

![image](https://user-images.githubusercontent.com/28353492/117308108-c86e8f80-aeb3-11eb-8cfc-d34eb914784a.png)

(Here I put the profiler's result for convenience. The FLOPS is nearly 15G and the runtime is merely 0.737ms, which is pretty close to my implementation.)

Then, I naively thought that the Conv2d part would be just as good.

In my implementation, one of my problem size for Conv2d is as follows:

```
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationClamp<
    cutlass::half_t,                 // Data type of output matrix.
    8,                                    // The number of elements per vectorized.
                                           // memory access. This becomes the vector width of
                                           // math instructions in the epilogue too.
    float,                               // Data type of accumulator
    float>;                            // Data type for alpha/beta in linear combination


using Conv2dFpropKernel = typename cutlass::conv::kernel::DefaultConv2dFprop<
  cutlass::half_t, cutlass::layout::TensorNHWC,
  cutlass::half_t, cutlass::layout::TensorNHWC,
  cutlass::half_t, cutlass::layout::TensorNHWC,
  float,
  cutlass::arch::OpClassTensorOp,
  cutlass::arch::Sm75,
  cutlass::gemm::GemmShape<128, 128, 32>,
  cutlass::gemm::GemmShape<64, 64, 32>,
  cutlass::gemm::GemmShape<16, 8, 8>,
  EpilogueOp ,
  cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>,
  2,
  cutlass::arch::OpMultiplyAdd,
  cutlass::conv::IteratorAlgorithm::kOptimized
>::Kernel;

cutlass::conv::Conv2dProblemSize problem_size(
	{ 1280*720, 8, 8, 6 }, // input
	{ 2, 3, 3, 6 }, // kernel
	{ 1, 1, 1, 1 }, // padding
	{ 1, 1 }, // stride
	{ 1, 1 },
	{ 1280*720, 8, 8, 2 }, // output
	cutlass::conv::Mode::kConvolution, // mode
	1);
```

Then I noticed that there is a misalignment since `c=6` and `k=2`. So I simply referred to #246, and set `AlignmentA` and `AlignmentB` to 2 (Also change the 8 in `EpilogueOp` to 2).

As a result, the runtime is up to 55ms, which is totally unacceptable. At that time I felt that I was doing something wrong.

So I then went to the profiler for verifying this. The profiler does not support `c=6` and `k=2`, so I set `c=k=8`. Besides, it can not be fed in `n=1280*720` so I set `n=65536`:

![image](https://user-images.githubusercontent.com/28353492/117309578-22238980-aeb5-11eb-848c-7d5f1915744e.png)

The FLOPS is 4.8G and the runtime is 6.28ms. I also did a group of experiments, comparing with the Gemm case:

| Operation      | GFLOPS | Runtime | GFLOPS / Runtime |
| -------------- | ------ | ------- | ---------------- |
| Gemm           | 15.2   | 0.73ms  | 20.82            |
| Conv (k=c=8)   | 4.8    | 6.28ms  | 0.76             |
| Conv (k=c=16)  | 19.4   | 6.31ms  | 3.07             |
| Conv (k=c=32)  | 77     | 6.51ms  | 11.82            |
| Conv (k=c=64)  | 309    | 14.47ms | 21.35            |
| Conv (k=c=128) | 1128   | 33.12ms | 34.04            |

Note that when c&k < 32, the runtime is always up to 6ms.

I've read the assumptions of the CUTLASS Implicit GEMM implementation in [here](https://github.com/NVIDIA/cutlass/blob/master/media/docs/implicit_gemm_convolution.md#cutlass-convolution-implementation). However, my question is:

- The increase in FLOPS is not always linearly reflected in the increase in runtime, is it?
- What could I do to get the runtime of my question_size down to a normal level? In this case, my GFLOPS is merely 248.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-32

**Comment by hwu36** [comment]
Several points first:

1. Dont't use `LinearCombinationClamp`, but use `LinearCombination`.  The former is for integer kernels.

2. Use small alignment will cause performance drop.  It is expected.

3. > The increase in FLOPS is not always linearly reflected in the increase in runtime, is it?
  No.  It is linear only when the problem size is big which is compute bound, but it is not your case.

4. > What could I do to get the runtime of my question_size down to a normal level? In this case, my GFLOPS is merely 248.
  Can you run your problem size with cudnn and uses nvopt/nsight to see which kernel does it use?

**Comment by zheng95z** [comment]
Thanks, @hwu36. The `LinearCombinationClamp` is a typo BTW.

I'm going to run this with the cudnn and then get back to here.

Meanwhile, I'm wondering, in cutlass, is the problem size with c&k < 32 destined to have a high runtime close to the case c&k=32? (In this case, they are always up to 6ms.)

**Comment by hwu36** [comment]
> Meanwhile, I'm wondering, in cutlass, is the problem size with c&k < 32 destined to have a high runtime close to the case c&k=32? (In this case, they are always up to 6ms.)

Yes.  More precisely up to `threadblock::kK`

**Comment by illava** [comment]
> What could I do to get the runtime of my question_size down to a normal level? In this case, my GFLOPS is merely 248.
The img2col shape(m, n, k) in your case have very little n = 6, you can try reduce threadblock Gemm shape in n direction. The rest of is it is padded by 0 and do a waste of calculation.
`  cutlass::gemm::GemmShape<128, 8, 32>,
  cutlass::gemm::GemmShape<64, 8, 32>,
  cutlass::gemm::GemmShape<16, 8, 8>,` and may use SIMT kernels in cutlass.

**Comment by zheng95z** [comment]
@hwu36 Hi, I just finished running my problem size on cudnn and profiled it using the Nsight Compute.

Here is the result:

![image](https://user-images.githubusercontent.com/28353492/117434219-fb219200-af5e-11eb-9f41-144af8fb51cb.png)

BTW the runtime on cudnn (65ms) is a little larger than the runtime (50ms) on cutlass.

**Comment by hwu36** [comment]
I don't see the cudnn kernel name, but anyway cutlass is already 20% faster than cudnn so cudann cannot help us here.

What you can try is:

1. Use simt conv as suggested by @illava which uses smaller threadblock::kK
2. Half `ThreadblockShape::kK` and `WarpShape::kK` (It may work)
3. Try different swizzle function in https://gitlab-master.nvidia.com/dlarch-fastkernels/cutlass/-/blob/dev/include/cutlass/gemm/threadblock/threadblock_swizzle.h  ( GemmIdentityThreadblockSwizzle<1>, GemmIdentityThreadblockSwizzle<2>, GemmIdentityThreadblockSwizzle<4>, GemmIdentityThreadblockSwizzle<8>, GemmHorizontalThreadblockSwizzle) 

One thing I noticed is that you use volta 8x8x4 tensor core instruction on turing, have you tried turing 16x8x8 tensor core instruction?

**Comment by zheng95z** [comment]
Hi @hwu36 & @illava, thanks for your kind help.

> Use simt conv as suggested by @illava which uses smaller threadblock::kK

Simt conv is surly faster than tensorop on our problem size. Thanks. But I still have some questions:

- Is the instruction shape of simt conv always `cutlass::gemm::GemmShape<1, 1, 1>`?
- @illava also suggested that change the threadblock shape' n to 8, i.e. `cutlass::gemm::GemmShape<128, 8, 32>`, but it seems this will cause build errors. #108 is informative, however according to it, `cutlass::gemm::GemmShape<128, 8, 32>` seems valid. I think it would be great if you put something like #108 to the docs to explain everything concerning these shapes.

> Half ThreadblockShape::kK and WarpShape::kK (It may work)

- It surely works, thanks.

> One thing I noticed is that you use volta 8x8x4 tensor core instruction on turing, have you tried turing 16x8x8 tensor core instruction?

- That's my fault. I built the profiler in the wrong way.

BTW, I test the problem size with c&k < 32 on an RTX 3090 using sm80 tensorop and simt. I put the result (fastest) here just for information.

Tensorop with c&k = 8, 16, 24:

Provider | OperationKind | Operation | z | Status | conv_kind | n | h | w | c | k | r | s | p | q | pad_h | pad_w | stride_h | stride_w | dilation_h | dilation_w | Activation | Filter | Output | conv_mode | iterator_algorithm | alpha | beta | split_k_mode | split_k_slices | eq_gemm_provider | op_class | accum | cta_m | cta_n | cta_k | stages | warps_m | warps_n | warps_k | inst_m | inst_n | inst_k | min_cc | max_cc | Bytes | Flops | Runtime | GB/s | GFLOPs
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CUTLASS | conv2d | cutlass_tensorop_s1688fprop_optimized_f16_128x64_32x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 8 | 8 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f16:nhwc | f16:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | tensorop | f32 | 128 | 64 | 32 | 2 | 2 | 2 | 1 | 16 | 8 | 8 | 75 | 1024 | 1.04E+10 | 6.89E+10 | 31.033 | 311.538 | 2219.94
CUTLASS | conv2d | cutlass_tensorop_s1688fprop_optimized_f16_128x64_32x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 16 | 16 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f16:nhwc | f16:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | tensorop | f32 | 128 | 64 | 32 | 2 | 2 | 2 | 1 | 16 | 8 | 8 | 75 | 1024 | 2.08E+10 | 2.74E+11 | 31.7343 | 609.308 | 8624.06
CUTLASS | conv2d | cutlass_tensorop_s1688fprop_optimized_f16_128x64_32x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 24 | 24 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f16:nhwc | f16:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | tensorop | f32 | 128 | 64 | 32 | 2 | 2 | 2 | 1 | 16 | 8 | 8 | 75 | 1024 | 3.11E+10 | 6.14E+11 | 32.4898 | 892.709 | 18909.4


Simt with c&k = 2, 4, 8, 16, 24:

Provider | OperationKind | Operation | Disposition | Status | conv_kind | n | h | w | c | k | r | s | p | q | pad_h | pad_w | stride_h | stride_w | dilation_h | dilation_w | Activation | Filter | Output | conv_mode | iterator_algorithm | alpha | beta | split_k_mode | split_k_slices | eq_gemm_provider | op_class | accum | cta_m | cta_n | cta_k | stages | warps_m | warps_n | warps_k | inst_m | inst_n | inst_k | min_cc | max_cc | Bytes | Flops | Runtime | GB/s | GFLOPs
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CUTLASS | conv2d | cutlass_simt_cf32_cfprop_optimized_cf32_64x64_8x3_nhwc | passed | success | fprop | 921600 | 8 | 8 | 2 | 2 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | cf32:nhwc | cf32:nhwc | cf32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | simt | cf32 | 64 | 64 | 8 | 3 | 4 | 2 | 1 | 1 | 1 | 1 | 50 | 1024 | -1.3E+09 | 1.79E+10 | 145.303 | -8.33389 | 123.402
CUTLASS | conv2d | cutlass_simt_sfprop_optimized_128x32_8x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 4 | 4 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f32:nhwc | f32:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | simt | f32 | 128 | 32 | 8 | 2 | 2 | 1 | 1 | 1 | 1 | 1 | 50 | 1024 | 9.44E+09 | 1.75E+10 | 23.3135 | 376.994 | 748.869
CUTLASS | conv2d | cutlass_simt_sfprop_optimized_128x32_8x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 8 | 8 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f32:nhwc | f32:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | simt | f32 | 128 | 32 | 8 | 2 | 2 | 1 | 1 | 1 | 1 | 1 | 50 | 1024 | 1.89E+10 | 6.89E+10 | 23.5315 | 747.003 | 2927.62
CUTLASS | conv2d | cutlass_simt_sfprop_optimized_128x32_8x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 16 | 16 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f32:nhwc | f32:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | simt | f32 | 128 | 32 | 8 | 2 | 2 | 1 | 1 | 1 | 1 | 1 | 50 | 1024 | 3.77E+10 | 2.74E+11 | 42.0195 | 836.665 | 6513.12
CUTLASS | conv2d | cutlass_simt_sfprop_optimized_128x32_8x2_nhwc | passed | success | fprop | 921600 | 8 | 8 | 24 | 24 | 3 | 3 | 8 | 8 | 1 | 1 | 1 | 1 | 1 | 1 | f32:nhwc | f32:nhwc | f32:nhwc | cross | optimized | 1 | 0 | serial | 1 | none | simt | f32 | 128 | 32 | 8 | 2 | 2 | 1 | 1 | 1 | 1 | 1 | 50 | 1024 | 5.66E+10 | 6.14E+11 | 61.4959 | 857.526 | 9990.26

**Comment by hwu36** [comment]
> Is the instruction shape of simt conv always cutlass::gemm::GemmShape<1, 1, 1>?

Yes.  However, cutlass should be able to use `hfma2`.  See https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/thread/mma_sm60.h

> @illava also suggested that change the threadblock shape' n to 8, i.e. cutlass::gemm::GemmShape<128, 8, 32>, but it seems this will cause build errors. #108 is informative, however according to it, cutlass::gemm::GemmShape<128, 8, 32> seems valid. I think it would be great if you put something like #108 to the docs to explain everything concerning these shapes.

I don't think `Threadblock::kN=8` is something we intend to support.  The smallest Threadblck::kN we plan to support in some cases is 32.  64 is the one that should be supported in all cases.  That said, we wrote our kernels as general as possible so that sometimes some uncommon tile sizes work well in some cases even though we don't have those in mind when we wrote our kernels.
