### ISSUE TITLE
CUTLASS start from Device Tensor

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#260]
**Hi, All**

I see most of the examples shows we should start from a host tensor
```
cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> A({M, K});
```

Is there any way for us to start the GEMM of CUTLASS from a DeviceTensor directly? 

For example, in the hidden layer of a MLP, we just pass the deviceTensor instead of copy it back to host.

Thanks!

**Comment by YukeWang96** [comment]
Ok, I see. so I need to 1) allocate a GPU device memory by using `cudaMalloc`, 2) define the data layout. 
I just have one more question, 

>  How does the `TensorRef ` determines the `dataType`. The above two steps are ok for `float` and `int`, what about the `half`, `int8`, `int4` and `int1`.

**Comment by hwu36** [comment]
The kernel knows the types of the Elements which are in the template argument lists.

**Comment by YukeWang96** [comment]
I encounter another problem when I try to provide the `int8`, `int4`, and `int1` as the typename for the template of the `cutlass::Tensor_ref<int8, layout>`, it will report the error.

```
error: no instance of constructor "cutlass::TensorRef<Element_, Layout_>::TensorRef [with Element_=ElementInputB, Layout_=LayoutInputB]" matches the argument list argument types are: (ElementOutput *)

detected during instantiation of "cutlass::TensorRef<out_Element_, out_Layout_> MLP_hidden_layer(int, int, int, cutlass::TensorRef<out_Element_, out_Layout_> &) [with out_Element_=ElementOutput, out_Layout_=LayoutOutput]" 
```

However, when I was using `float` or `half_t`, no such compilation error is reported.
is there any solution for this?

Thanks!

**Comment by hwu36** [comment]
It should work.

You can see [here](https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/host_tensor.h#L266) for how `HostTensor` uses `TensorRef`

**Comment by YukeWang96** [comment]
ok, I figure it out.  

It is the type mismatch between the defined `GEMM` and the `argument`.
I am wondering for those hidden layers, if the input layer output is `int32`, I have to have one more quantization step to convert `int32` --> `int8` for the next layer input. And there is no such a `GEMM` that can do `int8 * int8 --> int8`, is this correct?

Thanks!

**Comment by hwu36** [comment]
> And there is no such a GEMM that can do int8 * int8 --> int8, is this correct?

What do you mean?  or idp4a or int tensor core gemms can do  int8 * int8 --> int8.

**Comment by YukeWang96** [comment]
Yes, I mean for 
> int tensor core gemms can do int8 * int8 --> int8

**Comment by hwu36** [comment]
[here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_s8t_s8n_s8t_tensor_op_s32_sm80.cu)  is the unit tests doing this.

**Comment by YukeWang96** [comment]
Got it! 
Thanks!

**Comment by YukeWang96** [comment]
> [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_s8t_s8n_s8t_tensor_op_s32_sm80.cu) are the unit tests doing this.

I can also find the `int4 * int4 --> int4`, however, I didn't find the `uint1 * uint1 --> uint1`. 
Does cutlass officially support this?

**Comment by hwu36** [comment]
we have b1 x b1 -> s32.  I can find an application that needs to do b1 x b1 -> b1
