### ISSUE TITLE
Incorrect conv2d result with interleaved layouts.

### ISSUE THREAD

**Issue by ocwins** [NVIDIA/cutlass#263]
```
 // The code section below describes datatype for input, output tensors and computation between
 // elements 
using ElementAccumulator = int32_t;//cutlass::half_t;        // Data type of accumulator
using ElementComputeEpilogue = int32_t;              // Data type of epilogue computation (alpha, beta)
using ElementInputA = int8_t;//cutlass::half_t;             // Data type of elements in input tensor
using ElementInputB = int8_t;// cutlass::half_t;             // Data type of elements in input tensor
using ElementOutput = int8_t;                       // Data type of elements in output tensor

using LayoutInputA = cutlass::layout::TensorNCxHWx<32>; //TensorNCxHWx<32>; //TensorNHWC;
using LayoutInputB = cutlass::layout::TensorCxRSKx<32>; //TensorCxRSKx<32>; //TensorNHWC;
using LayoutOutput = cutlass::layout::TensorNCxHWx<32>; //TensorNCxHWx<32>; //TensorNHWC;

// This code section describes whether you want to use tensor cores or regular SIMT cores on GPU SM
using MMAOp = cutlass::arch::OpClassTensorOp;

// This code section describes CUDA SM architecture number
using SmArch = cutlass::arch::Sm80;

#if 1
// This code section describes the tile size a thread block will compute
using ThreadblockShape = cutlass::gemm::GemmShape<64, 64, 64>;  // Threadblock tile shape

// This code section describes tile size a warp will compute
using WarpShape = cutlass::gemm::GemmShape<32, 64, 64>;         // Warp tile shape
#else
// This code section describes the tile size a thread block will compute
using ThreadblockShape = cutlass::gemm::GemmShape<32, 32, 32>;  // Threadblock tile shape

// This code section describes tile size a warp will compute
using WarpShape = cutlass::gemm::GemmShape<16, 32, 32>;         // Warp tile shape
#endif

// This code section describes the size of MMA op
using InstructionShape = cutlass::gemm::GemmShape<16, 8, 32>;    // TensorCore instruction shape

// This code section describes how threadblocks are scheduled on GPU
using SwizzleThreadBlock = cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<1>;

// Number of pipelines you want to use
constexpr int NumStages = 2;

// This code section describe iterator algorithm selected is Analytic or Optimized
static cutlass::conv::IteratorAlgorithm const IteratorAlgorithm = cutlass::conv::IteratorAlgorithm::kOptimized;

// This code section describes the epilogue part of the kernel, we use default value
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationClamp<
    ElementOutput,                                     // Data type of output matrix.    
    64 / cutlass::sizeof_bits<ElementOutput>::value,  // The number of elements per vectorized.
    //8 * InstructionShape::kN / 32,                    // memory access. This becomes the vector width of
                                                       // math instructions in the epilogue too.
    ElementAccumulator,                                // Data type of accumulator
    ElementComputeEpilogue>;                           // Data type for alpha/beta in linear combination
    //cutlass::epilogue::thread::ScaleType::OnlyAlphaScaling>;

using Conv2dFprop = typename cutlass::conv::kernel::DefaultConv2dFprop <
    ElementInputA, LayoutInputA,
    ElementInputB, LayoutInputB,
    ElementOutput, LayoutOutput,
    ElementAccumulator,
    MMAOp,
    SmArch,
    ThreadblockShape,
    WarpShape,
    InstructionShape,
    EpilogueOp,
    SwizzleThreadBlock,
    NumStages,
    cutlass::arch::OpMultiplyAddSaturate,
    IteratorAlgorithm
>;
using Conv2dFpropKernel = Conv2dFprop::Kernel;

using ImplicitGemm = cutlass::conv::device::ImplicitGemmConvolution<Conv2dFpropKernel>;
```

```
/////////////////////////////////////////////////////////////////////////////////////////////////

enum {
    N = 4,
    H = 4,
    W = 4,
    C = 64,
    R = 1,
    S = 1,
    K = 32,    
    };



/////////////////////////////////////////////////////////////////////////////////////////////////

template <int N, int H, int W, int C, typename Fun> static cudaError_t
init_ncxhw(int8_t *dev_p, Fun &&fun) {
    static_assert(C % 32 == 0, "???");
    static_assert(C >= 32, "???");
    size_t constexpr sz = N * H * W * C;
    int8_t d[sz];
    int i = 0;
    for (int n = 0; n < N; ++n) {
        for (int c = 0; c < C / 32; ++c) {
            for (int hw = 0; hw < H * W; ++hw) {
                for (int x = 0; x < 32; ++x, ++i) {
                    d[i] = fun(n, hw, c * 32 + x);
                    }
                }
            }
        }
    return cudaMemcpy(dev_p, d, sz, cudaMemcpyHostToDevice);
    }

template <int R, int S, int K, int C, typename Fun> static cudaError_t
init_cxrsk(int8_t *dev_p, Fun &&fun) {
    static_assert(C % 32 == 0, "???");
    static_assert(C >= 32, "???");
    size_t constexpr sz = R * S * K * C;
    int8_t d[sz];
    int i = 0;
    for (int c = 0; c < C / 32; ++c) {
        for (int rs = 0; rs < R * S; ++rs) {
            for (int k = 0; k < K; ++k) {
                for (int x = 0; x < 32; ++x, ++i) {
                    d[i] = fun(rs, k, c * 32 + x);
                    }
                }
            }
        }
    return cudaMemcpy(dev_p, d, sz, cudaMemcpyHostToDevice);
    }

template <int value> int
make_value(int n, int hw, int c) {
    return value;
    }

extern "C" size_t
cutlass_test(void **p) {
    //
    // Define arguments for CUTLASS Convolution
    //

    cutlass::conv::Mode mode = cutlass::conv::Mode::kCrossCorrelation;

    // Split K dimension into 1 partitions
    int split_k_slices = 1;
    auto ConvOp = Conv2dFpropKernel::kConvolutionalOperator;
    // Construct Conv2dProblemSize with user defined output size
    cutlass::conv::Conv2dProblemSize problem_size(
        { 4, 4, 4, 64 },    // input size (NHWC)
        { 32, 1, 1, 64 },   // filter size (KRSC)
        { 0, 0, 0, 0 },     // padding (pad_h, _, pad_w, _)
        { 1, 1 },           // stride (stride_h, stride_w)
        { 1, 1 },           // dilation (dilation_h, dilation_w)
        { 4, 4, 4, 32 }     // output size (NPQK)
    );

    int8_t *a, *b, *c, *d;
    auto input_sz = problem_size.activation_size();
    auto filter_sz = problem_size.filter_size();
    auto output_sz = problem_size.output_size();
    auto err = cudaMalloc(&a, input_sz);        cuda_assert(err);
    err = cudaMalloc(&b, filter_sz);            cuda_assert(err);
    err = cudaMalloc(&c, output_sz);           cuda_assert(err);
    err = cudaMalloc(&d, output_sz);           cuda_assert(err);

    auto with_cxrsk = [](int rs, int k, int c) { return k / 8; };
#if 1    
    err = init_ncxhw< N, H, W, C>(a, make_value<1>);         cuda_assert(err);
#else
    err = cudaMemset(a, 1, sz);         cuda_assert(err);
#endif
#if 1
    err = init_cxrsk<R, S, K, C>(b, make_value<1>);         cuda_assert(err);
#else
    cudaMemset(b, 1, filter_sz);
#endif    

    err = cudaMemset(c, 0, output_sz); cuda_assert(err);
    err = cudaMemset(d, 0, output_sz); cuda_assert(err);



    // Construct ImplicitGemm::Argument structure with conv2d 
    // problem size, data pointers, and epilogue values
    typename ImplicitGemm::Arguments arguments{
      problem_size,
      a,
      b,
      c,
      d,
        {1, 0},
        };

    //
    // Initialize CUTLASS Convolution
    //

    ImplicitGemm implicit_gemm_op;

    size_t workspace_size = implicit_gemm_op.get_workspace_size(arguments);

    // Allocate workspace memory
    cutlass::device_memory::allocation<uint8_t> workspace(workspace_size);

    auto status = implicit_gemm_op.can_implement(arguments);
    CUTLASS_CHECK(status);

    status = implicit_gemm_op.initialize(arguments, workspace.get());
    CUTLASS_CHECK(status);

    //
    // Launch initialized CUTLASS kernel
    //
    status = implicit_gemm_op();

    CUTLASS_CHECK(status);
    
    int8_t *host;
    err = cudaHostAlloc(&host, output_sz, 0); cuda_assert(err);
    err = cudaMemcpy(host, d, output_sz, cudaMemcpyDeviceToHost); cuda_assert(err);
    *p = host;
    return output_sz;
    }
```

Got this result:

> 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

It seems that only one image was calculated (4 total)

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-31

**Comment by ocwins** [comment]
Another question, does "TensorCxRSKx" mean that: if x is 32, except every 32 Cs, K is the dimension varying fastest in memory?

**Comment by hwu36** [comment]
You need to reorder the filter tensor when using interleaved conv like [this](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_testbed_interleaved.h#L168-L169).

You may first check the correctness using the interleaved testbed like this [unit test](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32_sm80.cu#L641-L677).

`TensorCxRSKx` is defined [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L430-L432)

**Comment by ocwins** [comment]
> 
> 
> You need to reorder the filter tensor when using interleaved conv like [this](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_testbed_interleaved.h#L168-L169).
> 
> You may first check the correctness using the interleaved testbed like this [unit test](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32_sm80.cu#L641-L677).


In my sample, both activation tensor and filter tensor are filled with all one. so I don't think the reordering is necessary in this case. And this sample is small and easy to check: every elements in outputs shall be 1 * 64 (0x40). 

So I feel something wrong, but I can't find it.

**Comment by ocwins** [comment]
> 
> `TensorCxRSKx` is defined [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L430-L432)

so extent.n is K, w and h are r and s, am I right ?

**Comment by hwu36** [comment]
I made these changes to use your problem sizes

```
--- a/test/unit/conv/device/conv2d_testbed_interleaved.h
+++ b/test/unit/conv/device/conv2d_testbed_interleaved.h
@@ -402,6 +402,7 @@ bool TestAllInterleavedConv2d(
 
   InterleavedTestbedConv2d<ImplicitGemm, InterleavedK> testbed;
 
+#if 0
   //
   // Get conv problem sizes to run conv operator 
   //
@@ -473,35 +474,34 @@ bool TestAllInterleavedConv2d(
       }
     }
   }
-
-#if 0
+#endif
+#if 1
   // Sweep split-k-slice using serial and prallel reduction with non-unity alpha and non-zero beta for 
   // a single conv2d problem size. Convolution unit tests take a long time to run so only sweep parameters 
   // which are abolutely neccessary to catch functional bugs. The below code does provide option to sweep 
   // alpha and beta for local testing, but only runs one value for alpha and beta.
   cutlass::conv::Conv2dProblemSize conv2d_split_k_test_size (
-      {1, 17, 11, 288},   // input size (NHWC)
-      {160, 3, 3, 288},   // filter size (KRSC)
-      {1, 1, 1, 1},       // padding (pad_h, _, pad_w, _)
+      {4, 4, 4, 64},   // input size (NHWC)
+      {32, 1, 1, 64},   // filter size (KRSC)
+      {0, 0, 0, 0},       // padding (pad_h, _, pad_w, _)
       {1, 1},             // stride (stride_h, stride_w)
       {1, 1}              // dilation (dilation_h, dilation_w)
     );
 
   cutlass::conv::SplitKMode split_k_modes [] = {
-    cutlass::conv::SplitKMode::kSerial,
-    cutlass::conv::SplitKMode::kParallel,
+    cutlass::conv::SplitKMode::kSerial
   };
 
   int split_k_slices[] = {
-    1, 2, 3, 4, 201
+    1
   };
 
   double problem_alpha[] = {
-    2.0
+    1.0
   };
 
   double problem_beta[] = {
-    2.0
+    0.0
   };
 
   for (auto split_k_mode : split_k_modes) {
```
and I can pass this unit test

```
[haichengw@ipp1-0273 build80]$ ./test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_s32_interleaved --gtest_filter="SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32.64x64_64x6_32x32x64"
Note: Google Test filter = SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32.64x64_64x6_32x32x64
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32
[ RUN      ] SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32.64x64_64x6_32x32x64
[       OK ] SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32.64x64_64x6_32x32x64 (289 ms)
[----------] 1 test from SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32 (289 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (289 ms total)
[  PASSED  ] 1 test.
```

**Comment by hwu36** [comment]
Then, I made these changes

```
--- a/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32_sm80.cu
+++ b/test/unit/conv/device/conv2d_fprop_implicit_gemm_s8ncxhwx_s8cxrskx_s8ncxhwx_tensor_op_s32_sm80.cu
@@ -656,7 +656,7 @@ TEST(SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_
     cutlass::arch::OpClassTensorOp,
     cutlass::arch::Sm80,
     cutlass::gemm::GemmShape<64, 64, 64>,
-    cutlass::gemm::GemmShape<32, 32, 64>,
+    cutlass::gemm::GemmShape<32, 64, 64>,
     cutlass::gemm::GemmShape<16, 8, 32>,
     cutlass::epilogue::thread::LinearCombinationClamp<
       ElementC,
@@ -665,7 +665,7 @@ TEST(SM80_Device_Conv2d_Fprop_Optimized_ImplicitGemm_s8ncxhwx_s8cxrskx_s8ncxhwx_
       ElementCompute
     >,
     cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<1>,
-    6,
+    2,
     cutlass::arch::OpMultiplyAddSaturate,
     cutlass::conv::IteratorAlgorithm::kOptimized
   >::Kernel;
```
to use your tile size and it still pass.
