### ISSUE TITLE
Why clamp to [-8, 7] for uint4b_t

### ISSUE THREAD

**Issue by qliu93** [NVIDIA/cutlass#265]
Hi,

I noticed that EpilogueOp `LinearCombinationClamp` for `ElementDst = cutlass::uint4b_t` clamps `intermediate` to `[-8, 7]`:

```
ElementCompute const kClamp =
    ElementCompute((1U << (sizeof_bits<ElementOutput>::value - 1)) - 1);

intermediate = max_accumulator(intermediate, -kClamp - ElementCompute(1));
intermediate = min_accumulator(intermediate, kClamp);
```

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_clamp.h#L223

Why not `[0, 15]`? Is this a feature or a bug? 

Thanks

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-30

**Comment by hwu36** [comment]
It is a bug.  We did not consider the case of unsigned int.  Need to choose the clamp operation based on the `Element` type?  Interested in creating a pull request?

**Comment by hwu36** [comment]
Some code for reference:

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/numeric_conversion.h#L532-L541

**Comment by hwu36** [comment]
For arch >= sm72, we supposed to use hardware to do the clamp when packing/converting multiple s32 to s4.  https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/numeric_conversion.h#L1169-L1198

are you trying to convert to u4 on an older arch?

**Comment by qliu93** [comment]
Hi hwu36,

thanks for your reply. I searched `NumericConverterClamp` in cutlass repo and found that this converter is only used in host functions. It seems that `NumericConverter` in device function can also clamp values correctly using `cvt` ptx instructions. So I wonder when is it necessary to use `LinearCombinationClamp` instead of `LinearCombination`?

**Comment by hwu36** [comment]
`LinearCombinationClamp` is supposed to be used when doing int->fp32->int.  fp32->int part needs clamping.

`LinearCombination` is for the case that does not do fp32->int.

**Comment by qliu93** [comment]
:+1:

**Comment by qliu93** [comment]
I think here we should use `kClampMin` and `kClampMax` too : )

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_clamp.h#L226
