### ISSUE TITLE
Which matrix is actually sparse when profiling spgemm?

### ISSUE THREAD

**Issue by xyyaman** [NVIDIA/cutlass#267]
The formula of structured sparse GEMM is:  D = alpha * A*B + beta * C.  
So if I want to profile a sparse gemm with a problem size of M=N=K=8192, and I use this command:

> cutlass_profiler --operation=SparseGemm --m=8192 --n=8192 --k=8192 --device=0 --warmup-iterations=5 --accumulator-type=f16 --A=f16:row --B=f16:row --profiling-iterations=1

then which matrix of A, B and C is actually sparse?
Can I speficy matrix A to be sparse while B and C are dense?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-29

**Comment by hwu36** [comment]
A has to be sparse and B has to be dense.

**Comment by xyyaman** [comment]
> A has to be sparse and B has to be dense.

Thanks for the relpy.
Is matrix A 50% sparse? Can I speficy the sparsity of A?

**Comment by hwu36** [comment]
> Is matrix A 50% sparse?

Yes

> Can I speficy the sparsity of A?

No.  It is a hard requirement from the sparse tensor core instruction.
