### ISSUE TITLE
data layout TensorNCWH support

### ISSUE THREAD

**Issue by decioren** [NVIDIA/cutlass#269]
It seems that none of the examples use TensorNCHW. 
Trying to naively replace the original TensorNHWC layout with NCHW in the 'ampere_tensorop_conv2dfprop' example results in 'cudaEventSynchronize() failed: misaligned address' error. 
Running the example with command line parameters:  '--n=32 --h=256 --w=256 --c=256 --k=256 --r=1 --s=1'
Is there a way to make NCHW work? It is the most common layout in input data for DL...

**Comment by hwu36** [comment]
Please check the discussion in https://github.com/NVIDIA/cutlass/issues/231

**Comment by mnicely** [comment]
@decioren can we close this issue?
