### ISSUE TITLE
Bug in reference conv3d

### ISSUE THREAD

**Issue by BernardoCovas** [NVIDIA/cutlass#271]
https://github.com/NVIDIA/cutlass/blob/0f1056390d30f840f35f882a73c2a7b20ce424a3/tools/util/include/cutlass/util/reference/device/convolution.h#L276

I was getting strange results, replaced with:

```
filter_t = problem_size.T - 1 - T;
```

**Comment by hwu36** [comment]
Yes, you are right.

**Comment by BernardoCovas** [comment]
https://github.com/NVIDIA/cutlass/pull/272
