### ISSUE TITLE
NVCC compile shared library

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#273]
I want to use NVCC to compile the shared library for my CUTLASS application. However, I found one problem is that even the following simple example for building the shared library could not work. 

Here is the command I use for compiling and running.
```
nvcc --compiler-options '-fPIC' -o liblibrary.so --shared library.cu
nvcc -Xcompiler -I./ main.cu -L. -llibrary
nvcc -I./ main.cu -L. -llibrary
export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH 
./a.out
```

There are several files. <br>
`library.cu`
```
#ifndef LIB1_H_INCLUDED
#define LIB1_H_INCLUDED

void print_value ( int x );
__global__ void cuda_hello();

#endif /* LIB1_H_INCLUDED */
```
`library.cuh`
```
#include "library.cuh"
#include <stdio.h>

void print_value( int x )
{
    printf("%d\n", x);
}

__global__ void cuda_hello(){
    printf("Hello World from GPU!\n");
}

```

`main.cu`

```
#include <stdio.h>
#include "library.cuh"

int main ( void )
{
    print_value(10);
    cuda_hello<<<1,1>>>(); 
    return 0;
}
```

However, **it will not print any output, is there anything wrong?** while `print_value` from CPU host can print the output correctly.

**Comment by hwu36** [comment]
@d-k-b

**Comment by d-k-b** [comment]
Can you put `cudaDeviceSynchronize()` after you call cuda_hello? The program may be exiting before the kernel can be launched and completed. Just looking over your setup, it seems like the build code should work. Note, beyond this simple example, I would recommend using CMake (or some other build system) for this so it can build details for you : )

**Comment by YukeWang96** [comment]
Hi @d-k-b, I just try to put the `cudaDeviceSynchronize()` after my call for `cuda_hello`, it still can only output 10 without printing the `Hello World from GPU!` , is there any other possible reason?

also for CMake is there any example that I follow to achieve the same goal?

Thanks!

**Comment by d-k-b** [comment]
Try calling `cudaGetLastError()`, perhaps the CUDA runtime is failing to launch the kernel for some reason.

For CMake, take a look at this example https://github.com/robertmaynard/code-samples/tree/master/posts/cmake. Just change `STATIC` to `SHARED` in the add_library call.

**Comment by YukeWang96** [comment]
I just put `cudaGetLastError()` to my code after the kernel code, however, it does not output any error message. I can try the CMAKE method.

**Comment by d-k-b** [comment]
> I just put `cudaGetLastError()` to my code after the kernel code, however, it does not output any error message.

You'll have to check the return value of that method against cudaSuccess. See https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__ERROR.html#group__CUDART__ERROR_1g3529f94cb530a83a76613616782bd233 .

**Comment by YukeWang96** [comment]
This is the code I tried, but still no output for the error message.

```
int main ( void )
{
    print_value(10);
    cuda_hello<<<1,1>>>(); 
    gpuErrchk( cudaDeviceSynchronize());
    gpuErrchk( cudaGetLastError());
    return 0;
}
```
where `gpuErrchk` is defined as:

```
#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }
inline void gpuAssert(cudaError_t code, const char *file, int line, bool abort=true)
{
   if (code != cudaSuccess) 
   {
      fprintf(stderr,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
      if (abort) exit(code);
   }
}
```
