### ISSUE TITLE
Edits for single-pass translation

### ISSUE THREAD

**Issue by seanbaxter** [NVIDIA/cutlass#275]
Is there going to be a branch for single-pass compilers? Thrust and CUB are being refactored to support single-pass in branches like [this](https://github.com/allisonvacanti/thrust/tree/if_target).

At some point I'd like to have the chance to compile on Circle. I have two different single-pass dispatch strategies documented here:
https://github.com/seanbaxter/circle/blob/master/cuda/README.md

**Comment by hwu36** [comment]
Hi Sean,

It has been a while. 10 years?  Nice to see your circle compiler move forward rapidly.

We are busy with adding more kernels to CUTLASS and I don't think we have the bandwidth to add single-pass support by ourselves.  If you want to do it yourself, we are happy to help.

Don't forget to leave us a github star :smile: 

Haicheng

**Comment by seanbaxter** [comment]
Hi Haicheng. Yes, 10 years I think. I miss our lunches!

You guys will have to make these changes sooner or later to compile on NVC++, and I wouldn't want to take the fun away from you. Good luck.
