### ISSUE TITLE
failed in 00_basic_gemm

### ISSUE THREAD

**Issue by TonyYHsieh** [NVIDIA/cutlass#278]
yu-hsieh@/home/LOCAL/yu-hsieh/Source/Cutlass/1_study/cutlass/build/examples/00_basic_gemm$  ./00_basic_gemm 64 64 64 1 0
Failed to copy C_cutlass matrix to C_reference: invalid argument

# size of allocation miss rows.
diff --git a/examples/00_basic_gemm/basic_gemm.cu b/examples/00_basic_gemm/basic_gemm.cu
index 70d632e..98aea3d 100644
--- a/examples/00_basic_gemm/basic_gemm.cu
+++ b/examples/00_basic_gemm/basic_gemm.cu
@@ -187,7 +187,7 @@ cudaError_t InitializeMatrix(float *matrix, int rows, int columns, int seed = 0)
 cudaError_t AllocateMatrix(float **matrix, int rows, int columns, int seed = 0) {
   cudaError_t result;

-  size_t sizeof_matrix = sizeof(float) * columns;
+  size_t sizeof_matrix = sizeof(float) * rows * columns;

   // Allocate device memory.
   result = cudaMalloc(reinterpret_cast<void **>(matrix), sizeof_matrix);

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-26

**Comment by hwu36** [comment]
Thanks.  Fixed now.
