### ISSUE TITLE
cutlass::half vs half_t in CUDA/cuDNN

### ISSUE THREAD

**Issue by YukeWang96** [NVIDIA/cutlass#279]
Hi,

I am looking for merging some layers from cuDNN with CONV and GEMM in CUTLASS. 

> However, I found that the `cutlass::half_t` can not be replaced by `half_t` in CUDA that is used for cuDNN. 
> If I use `half_t` in compiling CONV or GEMM of CUTLASS it will report errors like ``no instance....''.

Is there any solution for this, since I want the output of cuDNN to become the input of CUTLASS and vice versa.

Thanks!

**Comment by manishucsd** [comment]
Can you paste the code you are trying out? 

The code snippet below might help resolve your problem:

```cpp
template <typename T>
inline cudnnDataType_t cuDNN_DataType() {
  return CUDNN_DATA_FLOAT;
}

template <>
inline cudnnDataType_t cuDNN_DataType<cutlass::half_t>() {
  return CUDNN_DATA_HALF;
}

template <>
inline cudnnDataType_t cuDNN_DataType<float>() {
  return CUDNN_DATA_FLOAT;
}
```

How are you calling CUTLASS kernels? 
If you call the way profiler does, i.e., using [convolution_operation.h](https://github.com/NVIDIA/cutlass/blob/master/tools/library/src/conv2d_operation.h#L52) wrapper. It gets you an object of `ConvDescription`. You can use the way profiler call cuDNN for verification: https://github.com/NVIDIA/cutlass/blob/master/tools/profiler/src/cudnn_helpers.h#L162
