### ISSUE TITLE
cutlass 1.1 build fails on Jetson TX2

### ISSUE THREAD

**Issue by dongxiao92** [NVIDIA/cutlass#29]
**Environment:**
CUDA: CUDA 9.0
nvcc: release 9.0, V9.0.252
gcc:  5.4.0 20160609
operation system: Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Thu Mar 1 20:49:20 PST 2018 aarch64 aarch64 aarch64 GNU/Linux

**Operations:**
 mkdir build
 cd build
 cmake -DCUTLASS_NVCC_ARCHS=62 ..
 make -j4

The error messages are listed as follows:
make[2]: *** 
[  1%] Building NVCC (Device) object examples/01_tensor_view/CMakeFiles/01_tensor_view.dir/01_tensor_vew_generated_tensor_view.cu.o
[  4%] Built target gtest
[  5%] Building NVCC (Device) object examples/00_basic_gemm/CMakeFiles/00_basic_gemm.dir/00_basic_gemmgenerated_basic_gemm.cu.o
[  6%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_per_test_generated_wmma_integer_gemm.cu.o
[  8%] Building NVCC (Device) object examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir02_cutlass_utilities_generated_cutlass_utilities.cu.o
[  9%] Linking CXX executable 01_tensor_view
[  9%] Built target 01_tensor_view
[ 10%] Building NVCC (Device) object examples/03_strided_batched_gemm/CMakeFiles/03_strided_batched_gem.dir/03_strided_batched_gemm_generated_strided_batched_gemm.cu.o
nvidia@tegra-ubuntu:~/dongxiao/cutlass-1.1.0% cd build          [ 13%] Built target 00_basic_gemm
[ 14%] Building NVCC (Device) object examples/04_tile_iterator/CMakeFiles/04_tile_iterator.dir/04_tile_iterator_generated_tile_iterator.cu.o
/home/nvidia/dongxiao/cutlass-1.1.0/examples/02_cutlass_utilities/cutlass_utilities.cu(150): error: calling a __device__ function("__half") from a __host__ function("Cutlass_FP16_SgemmNN") is not allowed

/home/nvidia/dongxiao/cutlass-1.1.0/examples/02_cutlass_utilities/cutlass_utilities.cu(155): error: cmalling a __device__ function("__half") from a __host__ function("Cutlass_FP16_SgemmNN") is not allowerd

2 errors detected in the compilation of "/tmp/tmpxft_00004c2c_00000000-4_cutlass_utilities.cpp4.ii".
CMake Error at 02_cutlass_utilities_generated_cutlass_utilities.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/nvidia/dongxiao/cutlass-1.1.0/build/examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir//./02_cutlass_utilities_generated_cutlass_utilities.cu.o

examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir/build.make:368: recipe for target 'examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir/02_cutlass_utilities_generated_cutlaass_utilities.cu.o' failed

[examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir/02_cutlass_utilities_generated_cutlass_utilities.cu.o] Error 1
CMakeFiles/Makefile2:527: recipe for target 'examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir/all' failed
make[1]: *** [examples/02_cutlass_utilities/CMakeFiles/02_cutlass_utilities.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 16%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_peerf_test_generated_sgemm.cu.o
[ 17%] Linking CXX executable 03_strided_batched_gemm
[ 17%] Built target 03_strided_batched_gemm
[ 18%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perf_test_generated_dgemm.cu.o
[ 20%] Linking CXX executable 04_tile_iterator
[ 20%] Built target 04_tile_iterator
[ 21%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perf_test_generated_hgemm.cu.o
[ 22%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perf_test_generated_igemm.cu.o
[ 24%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perrf_test_generated_wmma_gemm.cu.o
[ 25%] Building NVCC (Device) object tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perrf_test_generated_wmma_binary_gemm.cu.o
^Ctools/test/perf/CMakeFiles/cutlass_perf_test.dir/build.make:1968: recipe for target 'tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perf_test_generated_igemm.cu.o' failed
make[2]: *** [tools/test/perf/CMakeFiles/cutlass_perf_test.dir/gemm/cutlass_perf_test_generated_igemm.cu.o] Interrupt
CMakeFiles/Makefile2:311: recipe for target 'tools/test/perf/CMakeFiles/cutlass_perf_test.dir/all' failed
make[1]: *** [tools/test/perf/CMakeFiles/cutlass_perf_test.dir/all] Interrupt
Makefile:83: recipe for target 'all' failed

**Comment by kerrmudgeon** [comment]
Thank you. This issue was the result of using host-side conversion to CUDA's half type from float. This was not available in CUDA 9, so we have worked around this using reinterpret_cast<> from cutlass::half_t.

Should be fixed in `master`.
