### ISSUE TITLE
A confusion about double buffering

### ISSUE THREAD

**Issue by AndrewBoWen666** [NVIDIA/cutlass#291]
As decribed in [Piplining](https://github.com/NVIDIA/cutlass/blob/master/media/docs/efficient_gemm.md), there two buffer, one is shared memory buffer, the ohter is register buffer used for double buffering. However, the LDS and LDG use the same LD/ST units, which means this two buffer cannot be done at the same time. So does the two buffering implementation really help for maximum throughput? In my expriment, the througput increased as soly using register buffering instead of buffer both register and shared memory.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-23

**Comment by hwu36** [comment]
Yes, double buffering helps a lot.

Are you doing experiments on T4 which is power limited?

**Comment by AndrewBoWen666** [comment]
I am doing it on Jetson Xavier. In my understanding, as the CUDA core doing the FFMA using the oprands stored in a blocking of registers, there should be another a bunch of registers fetching the oprands from the shared memory. At this moment, both CUDA cores and LD/ST units are busy. But, from the link I quoted, it can be seen the load global instruction is also being conducted at this time. How can this be possible if the LD/ST units are used for fetching the data from SMEM to registers? Could you please help me explain this confusion? Thanks a lot. @hwu36

**Comment by hwu36** [comment]
Jetson is power limited.  It makes sense to use one stage on it to make the kernel less compute bounded to save the power.

**Comment by AndrewBoWen666** [comment]
What do you mean by one stage? @hwu36

**Comment by hwu36** [comment]
double buffer = 2 stage.  1 stage is not using double buffer.  In ampere, we can even use stage > 2 by using `cp.async` to keep the pipeline busy.

**Comment by AndrewBoWen666** [comment]
But I think this issue is irrelevant with power saving. The key is how can load global be done at the same time as load share is being conducted. @hwu36

**Comment by hwu36** [comment]
Just like any modern processors, GPU can have many memory transactions on the fly in the same time.

**Comment by AndrewBoWen666** [comment]
Is LDG and LDS sharing same hardware unit? @hwu36

**Comment by hwu36** [comment]
We cannot comment on our hardware details.  But, LDG and LDS can execute in the same time.

**Comment by AndrewBoWen666** [comment]
I understand your restrictions. If this is the case i will review my code to see whether I use shared memory buffer properly. Great thanks.
