### ISSUE TITLE
the problem of gemm loop paramter K 

### ISSUE THREAD

**Issue by Four-clover** [NVIDIA/cutlass#294]
hi，recently i studied the implementation of gemm in cutlass and read related docs (https://github.com/NVIDIA/cutlass/blob/master/media/docs/efficient_gemm.md ). I found that in the pseudo code of  Hierarchical Structure, the step size of warp_k and mma_k are both MmaK. in my opinion, the step size of warp_k should be WarpTileK?

**Comment by hwu36** [comment]
Good catch.  We will fix it.

**Comment by hwu36** [comment]
It was fixed.
