### ISSUE TITLE
What's the difference between 'TensorOpMultiplicandCrosswise' and 'TensorOpMultiplicandCongruous'？

### ISSUE THREAD

**Issue by ocwins** [NVIDIA/cutlass#296]
I have read the code but can't find the difference. They are just wrappers around 'TensorOpMultiplicand', both of them are implemented by codes almost identical.

And I can't well understand the term "Crosswise" (as a type argument of 'TensorOpMultiplicand' or as a word in struct's name), neither "Congruous". I searched in documents (readme, articles, etc) but I didn't find a definition.

Any hints are appreciated.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-20

**Comment by hwu36** [comment]
You are mostly right.  These two layouts are used for shared memory swizzling.  They two share the base layout implementation which is essentially (row % 4) ^ (col ^ 4).  We have a utility tool https://github.com/NVIDIA/cutlass/tree/master/examples/03_visualize_layout to help you visualize different layouts.

`TensorOpMultiplicandCrosswise` and `TensorOpMultiplicandCongruous` are also used as tags to select different shared memory store/load implementations.

The congruous store: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L49-L220

The crosswise store: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L418-L611

The congruous load: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L79-L288

The crosswise load: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L1295-L1846

(Note we have variants other than the above to handle different corner cases)

In congruous layout, gemm-k dimension is not the fastest changing dimension, or not the contiguous dimension.  For example, operand A column major, operand B row major.

In crosswise layout, gemm-k dimension is the fastest changing dimension, or the contiguous dimension.  For example, operand A row major, operand B column major.  The term `crosswise` is the number of elements in the k-dimension that one software stage has (or one threadblock tile has).

**Comment by ocwins** [comment]
Thank you. 

I still don't have a image in my head about why a layout is called 'crosswise' or 'congruous' (why not call a layout 'congruous' if gemm-k dimension is contiguous, but an opposite naming methods?), but it's more clear to me now.
