### ISSUE TITLE
A problem of include path

### ISSUE THREAD

**Issue by enp1s0** [NVIDIA/cutlass#299]
I'm using CUTLASS 2.5 with these compiler options.
```
nvcc -I/path/to/cutlass/include ...
```
The `cutlass/epilogue/threadblock/epilogue.h` includes `cutlass/util/index_sequence.h` in CUTLASS 2.6 but this header file is not existed in `/path/to/cutlass/include`.
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue.h#L57

Do I need to add an include path as follows to use CUTLASS 2.6?
```
nvcc -I/path/to/cutlass/include -I/path/to/cutlass/tools/include ...
```

**Comment by hwu36** [comment]
Yes.  You already figured it out.

You are so quick. We haven't announced the release yet. :smile:

**Comment by enp1s0** [comment]
@hwu36 Thank you for your reply.

Is this temporary and will it change when CUTLASS 2.6 is released?

**Comment by hwu36** [comment]
I think it would be better adding that include path even before 2.6.  We put some non core functionalities in that path.

**Comment by enp1s0** [comment]
@hwu36 Thank you for your helpful advice.
