### ISSUE TITLE
Question about threadblock rasterization

### ISSUE THREAD

**Issue by donglinz** [NVIDIA/cutlass#302]
Hi,

From CUTLASS document: https://github.com/NVIDIA/cutlass/blob/master/media/docs/efficient_gemm.md#threadblock-rasterization
> These map consecutively launched threadblocks to packed two-dimensional regions of the partitioned GEMM problem to increase the probability that these will access the same tiles of global memory at approximately the same time.

Looks the swizzle functions are used to improve L2 hit rate by increase the probability that different threadblocks access the same global memory at approximately the same time. 

However, thread block dispatch/scheduling is a non-deterministic procedure and the policy has not formally been published yet. I am confusing on how does this optimization take place. Is there any concrete example to demonstrate this performance gain?

Thanks!

**Comment by hwu36** [comment]
The basic idea is just let neighbouring threadblocks access neighbouring data.  We don't have an equation or algorithm to say which swizzling algorithm works best for a given problem size and hardware.  The current default one is based on our experiments.  It may not be the best for your case.  Unfortunately, the only way to pick the best rasterization algorithm is just brutally try them all.

**Comment by donglinz** [comment]
Good to know :) Thanks.

**Comment by sebftw** [comment]
Hey, I was considering implementing something similar in my own project.
Do you know what the speed-up was from doing this?
Did you make any observations when trying out swizzling algorithms @hwu36 ?

I assume you just found that neighboring threadblocks seem to get scheduled to the same SM. I guess reading %smid can help - but any solution would not necessarily generalize to different architectures, or possibly even CUDA-versions, if these things change the GigaThread scheduler.

**Comment by hwu36** [comment]
> Do you know what the speed-up was from doing this?

It depends.  Now our profiler uses `GemmIdentityThreadblockSwizzle<8>` by default.  You can try 4, 2, 1 to run your workloads.  Usually small chips prefer small number.  I don't think we have a good solution that can work well for any problem sizes on any architecture.  We are welcome the community to improve it.
