### ISSUE TITLE
Using profiler to search cublas kernel

### ISSUE THREAD

**Issue by gbxu** [NVIDIA/cutlass#304]
# environment
docker image:
nvcr.io/nvidia/pytorch:21.07-py3
More detailed software version, see : https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-07.html#rel_21-07
# compiling profiler with enabling cublas & cudnn
```
cd cutlass && mkdir build && cd build
cmake .. -DCUTLASS_NVCC_ARCHS=70 -DCUTLASS_ENABLE_TESTS=OFF -DCUTLASS_UNITY_BUILD_ENABLED=ON -DCUTLASS_ENABLE_CUBLAS=ON -DCUTLASS_ENABLE_CUDNN=ON  -DCUTLASS_LIBRARY_KERNELS=all
make -j
```
it shows,
```
...
-- cuBLAS: /usr/local/cuda/lib64/libcublas.so
-- cuBLAS: /usr/local/cuda/include
-- Configuring cuBLAS ... done.
-- Configuring cuDNN ...
-- cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
-- cuDNN: /usr/include
-- Configuring cuDNN ... done.
...
```

# Failed to profile cublas kernels
I can search cutlass kernels with commands as follows.
```
./tools/profiler/cutlass_profiler --algorithm-mode=best --profiling-enabled=True --providers=cutlass --operation=Gemm --m=512 --n=256 --k=128 
```
While it fails when I try to search some cublas kernels like
```
./tools/profiler/cutlass_profiler --algorithm-mode=best --profiling-enabled=True --providers=cublas,cudnn --operation=Gemm --m=512 --n=256
```
It confuses me that in [profiler.md](https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md) shows the possibility of using cublas as the kernel impl. provider.

**Comment by hwu36** [comment]
Off the shelf cutlass cannot be used to profile cublas/cudnn.  We will clean the document and help message.

Thanks for catching this.

**Comment by hwu36** [comment]
It was fixed in the profiler document.
