### ISSUE TITLE
Is RowMajor tensor essentially transposed here?

### ISSUE THREAD

**Issue by xue-fc** [NVIDIA/cutlass#309]
I notice that kAdvanceRank is inversed when construting an underlying iterator for RowMajor tensor. But the data of tensors accessed by these iterators has not been transposed. I think transposing RowMajor tensorA is necessary and when it happens in GEMM? 
https://github.com/NVIDIA/cutlass/blob/a01feb93d9ea1d081e39f0fae3710288c325e3c1/include/cutlass/transform/threadblock/predicated_tile_iterator.h#L631-L638
I got this confusion at example 07_volta_tensorop_gemm when LayoutInputA, LayoutInputB and LayoutInputC are RowMajor.
Thank you very much!

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-17

**Comment by hwu36** [comment]
Take `07_volta_tensorop_gemm` as an example.

At first, Matrix A set `kAdvanceRank` to 1 and Matrix B set `kAdvanceRank` to 0. (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/default_mma.h#L202-L212).

Next, as you noticed that, the value for the row major is inverted. So, Matrix A has 0 and Matrix B has 1.

Finally, in the base class (https://github.com/NVIDIA/cutlass/blob/a01feb93d9ea1d081e39f0fae3710288c325e3c1/include/cutlass/transform/threadblock/predicated_tile_access_iterator_params.h#L231-L238), the gemm-k dimension for Matrix A is in the contiguous dimension, and gemm-k dimension for Matrix B is in the strided dimension.

`kAdvanceRank` is used to tell which dimension (contiguous or strided) of the Matrix A/B is the gemm-k dimension.
