### ISSUE TITLE
automatically add int128 flag when NVC++ is used

### ISSUE THREAD

**Issue by jeffhammond** [NVIDIA/cutlass#310]
Support for 128-bit integers is a recent addition to the NVIDIA C++ compiler (https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-ref-guide/#data-typesc-cpp-type-keywords), which means that it is now possible to build CUTLASS files that use these.

I wonder if CUTLASS could add the CMake convenience that automatically employs the `-Mint128` flag when the NVC++ compiler is used.  It's not hard to do it manually, but only if one is sufficiently experienced with NVC++ to know that this feature has been added and that there is a special flag for it.

This works today:
```
cmake .. -DCMAKE_CXX_COMPILER=nvc++ -DCMAKE_CXX_FLAGS="-Mint128"
```

My hope is that the second argument is not necessarily in the future.

**Comment by hwu36** [comment]
@kerrmudgeon and @d-k-b , thoughts about how to support `nvc++` ?

**Comment by mnicely** [comment]
@jeffhammond are you building CUTLASS with nvc++?

**Comment by jeffhammond** [comment]
I build everything I can with NVHPC compilers, for obvious reasons 😃

**Comment by jeffhammond** [comment]
This is trivial to fix. Please do it.
