### ISSUE TITLE
How to do tensor transposition in cutlass?

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/cutlass#316]
Like the operation in torch below, how to convert it into cutlass code?

a=a.reshape(2, 32,32,32).permute(0,2,3,1)
and
w=tw.reshape(8,4,2,2,8,4, 9).permute(3, 6,0,2,4, 1,5)

Thx

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-14

**Comment by hwu36** [comment]
cutlass does not have transpose code, but it is not difficult to write one your own.  The kernel just need to load from old position and store to the new position.

You need to launch enough threads to make sure that it is memory bounded.

**Comment by leiwen83** [comment]
Yes, transpose itself is not a difficult task. However write a efficient transpose kernel which fully hit peak memory bandwidth is difficult...
I think the key to build the most efficient transpose kernel is to fully make use of r/w coalesce toward global memory. but how to break various task into tile, seem difficult...

**Comment by hwu36** [comment]
Transposition is a small and cheap kernel compare with gemm or conv. You just need a fast enough implementation. 

If you need to write a fancy one, you can leverage the shared memory to do the fast transposition.
  
I think it is hard to use just one templated kernel to do arbitrary transposition. More realistic way is to write specialized kernels to do common transposition such as nchw to nhwc.
