### ISSUE TITLE
CUTLASS results incorrect

### ISSUE THREAD

**Issue by d4l3k** [NVIDIA/cutlass#32]
I tried building the 00_basic_gemm project and when I run it it says "CUTLASS results incorrect". I'm also getting some weird results with my own code.

Details:
CUTLASS 1.1.0
CUDA release 9.2, V9.2.88
Tesla M40 GPU
CMake Flags: -DCUTLASS_NVCC_ARCHS=35;50;60;70

Compiling and running the same code on a Tesla P4 passes without any issues.

**Comment by d4l3k** [comment]
@kerrmudgeon Any thoughts/eta for a fix?

**Comment by YSZhuoyang** [comment]
Same here.

Built successfully and ran tests with cutlass v1.1, nv driver 410.66 on Ubuntu 18.04, gtx 960m GPU failed.

**Comment by kerrmudgeon** [comment]
Unfortunately, we believe this problem affects all GPUs in the Maxwell architecture. We have not yet root caused it. 

Pascal, Volta, and Turing are okay.

Will report back when we have updates.

**Comment by d4l3k** [comment]
@kerrmudgeon Any updates?

**Comment by kerrmudgeon** [comment]
CUTLASS 1.2 mainly contributes optimizations for batched GEMM targeting Tensor Cores on Volta and Turing as well as optimizations for problems with small GEMM-M and GEMM-N dimensions.

We have not addressed the issue you and others have reported regarding CUTLASS on the Maxwell architecture, however. We are looking into it.

**Comment by azazhu** [comment]
any updates?

**Comment by kerrmudgeon** [comment]
Yes! We have root caused this problem and are preparing a patch coming soon.

Thank you for being patient.

**Comment by kerrmudgeon** [comment]
I have pushed a patch to the master branch. Can you verify that it resolves the correctness problem on Maxwell?

**Comment by YSZhuoyang** [comment]
Tried it again in the same environment and I saw all tests were passed.

**Comment by kerrmudgeon** [comment]
Good to hear. 

I think this is safe to close. Feel free to re-open if you still have problems.
