### ISSUE TITLE
help wanted: Can I call a gemm function in each block?

### ISSUE THREAD

**Issue by Line233** [NVIDIA/cutlass#320]
I have a special batch matrix multiplication as following:
shape of A is(M1+M2+M3...MG, K), shape of B is (G, K, N)
M1 != M2... != MG
A and B are divided into G groups in dimension 1(started with 0), each group has A'( Mi, K) and B'(K,N) to compute the result with shape (Mi,N). All results of G groups are catenated to (M1+M2+M3...MG, N).
I want to use each block to compute a group, how can I implement it efficiently? Or can I call a gemm function in each block?
Thanks!

**Comment by hwu36** [comment]
you can use this `kArray` mode

see https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L426-L427

**Comment by Line233** [comment]
> https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L426-L427

Thanks, but it there any docs about this mode? I can't find it anywhere.

**Comment by hwu36** [comment]
[Example 18](https://github.com/NVIDIA/cutlass/blob/master/examples/18_ampere_fp64_tensorop_affine2_gemm/ampere_fp64_tensorop_affine2_gemm.cu) uses `GemmUniversal` and you can take a look at it.

Mode is set up [here](https://github.com/NVIDIA/cutlass/blob/master/examples/18_ampere_fp64_tensorop_affine2_gemm/ampere_fp64_tensorop_affine2_gemm.cu#L214).

You need to create four pointer arrays by yourself to store the pointers of matrices A, B, C and D.

Also when you launch the kernel, `grid.z` should equal to your `G`.  So, I think you need to set `batch_count` [here](https://github.com/NVIDIA/cutlass/blob/master/examples/18_ampere_fp64_tensorop_affine2_gemm/ampere_fp64_tensorop_affine2_gemm.cu#L216) to `G`

**Comment by kerrmudgeon** [comment]
I think there is a subtle distinction between the 'array' form of the batched GEMM implemented in CUTLASS and the request here. Namely, it seems that this issue requests that each 'batch index' have its own problem size. @Line233  can you confirm the following basic functional description?

```c++
struct Problem {
  int G;
  int const *M;
  int const *N;
  int const *K;
  T const *alpha;
  T const **A;
  int const *lda;
  T const **B;
  int const *ldb;
  T const *beta;
  T const **C;
  int const *ldc;
  T       **D;
  int const *ldd;
};

void Gemm(
  int M, int N, int K, 
  T alpha, 
  T const *A, int lda, 
  T const *B, int ldc, 
  T beta, 
  T const *C, int ldc, 
  T *D, int ldd) {

    /// familiar GEMM
}

void GroupedGemm(Problem problem) {
  for (int g_idx = 0; g_idx < G; ++g_idx) {
    
    int M = problem.M[g_idx];
    int N = problem.N[g_idx];
    int K = problem.K[g_idx];

    T const *A = problem.A[g_idx];
    int lda = problem.lda[g_idx];

    T const *B = problem.B[g_idx];
    int ldb = problem.ldb[g_idx];

    T const *C = problem.C[g_idx];
    int ldc = problem.ldc[g_idx];

    T *D = problem.D[g_idx];
    int ldd = problem.ldd[g_idx];

    T alpha = problem.alpha[g_idx];
    T beta = problem.beta[g_idx];

    Gemm(M, N, K, alpha, A, lda, B, ldb, beta, C, ldc, D, ldd);
  }  
}
```

If this matches your request, some additional effort will be needed to:
- use a persistent model so a single grid of CTAs can accommodate arbitrary problem dimensions
- match potentially irregular problem sizes to a balanced CTA distribution
- tune for various critical points in the space of problem sizes

@Line233   - Can you suggest some specific problem sizes and group counts that would be of interest? 
For example, you might consider the following to be important use cases
- G very large (hundreds or thousands) with M*N*K approximately the size of one CTA tile
- G = 1, performance critical for all MNK
- G = tens, MNK relatively large

Having specific numbers here might help with the tuning process.

**Comment by Line233** [comment]
> [Example 18](https://github.com/NVIDIA/cutlass/blob/master/examples/18_ampere_fp64_tensorop_affine2_gemm/ampere_fp64_tensorop_affine2_gemm.cu) uses `GemmUniversal` and you can take a look at it.
> 
> Mode is set up [here](https://github.com/NVIDIA/cutlass/blob/master/examples/18_ampere_fp64_tensorop_affine2_gemm/ampere_fp64_tensorop_affine2_gemm.cu#L214).
> 
> You need to create four pointer arrays by yourself to store the pointers of matrices A, B, C and D.
> 
> Also when you launch the kernel, `grid.z` should equal to your `G`. So, I think you need to set `batch_count` [here](https://github.com/NVIDIA/cutlass/blob/master/examples/18_ampere_fp64_tensorop_affine2_gemm/ampere_fp64_tensorop_affine2_gemm.cu#L216) to `G`

It seems not suitable for my request as each group has a different problem size.

**Comment by Line233** [comment]
@kerrmudgeon 
yes, this function is what I need. Specifically, N and K is fixed, only M is dynamic for each group.
In fact, the shape of A is (Batch,M,K), M=\sum(M_i), and the shape of B is (Batch,G,K,N).
K and N is tens, and M_i can varifies between thousands and tens.

Can I use dynamic parallelism to solve this problem like the following structure.
`__global__ solve_a_group(T A, T B, T out, T group_index)
{
    int b=blockIdx.x;
    int g=blockIdx.y;
    // launch a gemm function to solve problem in batch b and group g.
}

__global__ group_mm(T A, T B, T out, T group_index)
{
    dim3 blocks(batch, group);
    dim3 threads(1);
    gemm<blocks, threads>(A,B,out,group_index])
}`

**Comment by Line233** [comment]
@kerrmudgeon 
yes, this function is what I need. Specifically, N and K is fixed, only M is dynamic for each group.
In fact, the shape of A is (Batch,M,K), M=\sum(M_i), and the shape of B is (Batch,G,K,N).
K and N is tens, and M_i can varifies between thousands and tens.

Can I use dynamic parallelism to solve this problem like the following structure.
```c++
__global__ solve_a_group(T A, T B, T out, T group_index)
{
    int b=blockIdx.x;
    int g=blockIdx.y;
    // launch a gemm function to solve problem in batch b and group g.
}

__global__ group_mm(T A, T B, T out, T group_index)
{
    dim3 blocks(batch, group);
    dim3 threads(1);
    gemm<blocks, threads>(A,B,out,group_index])
}```

**Comment by mnicely** [comment]
@Line233 can you check if out new Grouped GEMM functionality solves your use case?

https://github.com/NVIDIA/cutlass/tree/master/examples/24_gemm_grouped
