### ISSUE TITLE
[Question] Why does shared memory needed in epilogue?

### ISSUE THREAD

**Issue by donglinz** [NVIDIA/cutlass#321]
In epilogue such as LinearCombinationRelu, all elements are processed element-wisely, so why does shared memory needed? 

In file cutlass/include/cutlass/epilogue/threadblock/epilogue.h, accumulator data had a round-trip to shared memory before perform alpha/beta scaling, I understand in the slice-k case cutlass use smem to aggregate partial-accumulation result across threadblock-k dimension. Do we have any other case/justification that smem is necessary in the epilogue stage?

**Comment by hwu36** [comment]
Shared memory is used to maximize the usage of the vectorized global memory store.  Take Ampere `s1681gemm` as an example.  After the mainloop, only neighbouring two 32-bit elements owned by a thread are consecutive.  After the round trip of shared memory visit, four 32-bit elements data owned by a thread are consecutive, then we can use `st.global.128b` to store the result.

**Comment by donglinz** [comment]
Awesome, thanks.
