### ISSUE TITLE
Question on OutputTileShape

### ISSUE THREAD

**Issue by donglinz** [NVIDIA/cutlass#322]
What does these fields meaning, especially for group, cluster, and tile?
```
/// Tuple defining point in output tile
template <
  int Column,
  int Row,
  int Group,
  int Cluster,
  int Tile
>
struct OutputTileShape {
  static int const kColumn = Column;
  static int const kRow = Row;
  static int const kGroup = Group;
  static int const kCluster = Cluster;
  static int const kTile = Tile;

  static int const kCount = kColumn * kRow * kGroup * kCluster * kTile;
};
```

Thanks a lot:)

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-12

**Comment by hwu36** [comment]
The epilouge supports 5D tensor and every dimension needs a name.

If you only care about gemm, just pay attention to Row and Column.  Others are all 1s.

**Comment by donglinz** [comment]
Seems in GEMM epilogue OutputTileThreadMap, group, cluster, and tile may be non 1s. May I have some context on this 5D tiling?

https://github.com/NVIDIA/cutlass/blob/538592dea4aac36ff87118096df9128bd470d01b/include/cutlass/epilogue/threadblock/default_thread_map_tensor_op.h#L91

https://github.com/NVIDIA/cutlass/blob/538592dea4aac36ff87118096df9128bd470d01b/include/cutlass/epilogue/threadblock/default_thread_map_tensor_op.h#L92

**Comment by hwu36** [comment]
Sorry, what I really meant before is that `ThreadMap::Iterations` in [predicated_tile_iterator.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h) are all 1s in `kGroup`, `kCluster`, and `kTile` in the case of GEMM.  So, the values in these three dimensions are not relevant.

If you want to dig deep, you can use the common values `ThreadblockShape = <kM:128, kN:128, kK:32>`, `Detail::kTensorOpRows = 8`, `Detail::WarpCount = <kM:2, kN:2, kK:1>` in this [line](https://github.com/NVIDIA/cutlass/blob/538592dea4aac36ff87118096df9128bd470d01b/include/cutlass/epilogue/threadblock/default_thread_map_tensor_op.h#L91) and walk through these [templates](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/output_tile_thread_map.h#L247-L274) to see why these iterations are always 1.
