### ISSUE TITLE
cutlass convolution vs cuDNN

### ISSUE THREAD

**Issue by rckjhn** [NVIDIA/cutlass#323]
Do you have any tables of comparisons?

**Comment by manishucsd** [comment]
You can find a list of functionality available in CUTLASS convolutions [here](https://github.com/NVIDIA/cutlass/blob/master/media/docs/functionality.md#device-level-implicit-gemm-convolution) 

Some performance comparison of (CUTLASS 2.5 + CUDA 11.3 toolkit) vs. (cuDNN) is available in our GTC 2021 talk [Accelerating Convolution with Tensor Cores in CUTLASS [S31883]](https://gtc21.event.nvidia.com/media/Accelerating%20Convolution%20with%20Tensor%20Cores%20in%20CUTLASS%20%5BS31883%5D/1_ofvh631z). You can download the slides after you login, and the performance results are on slide 7. 
Are you able to access this?

Kindly, note that we are about to release CUTLASS 2.7 with CUDA 11.4. We have improved both the functionality and performance from the last publicly released performance comparisons against cuDNN. You can use CUTLASS profiler to check how well CUTLASS convolutions perform for your use cases. Thanks! Manish

**Comment by rckjhn** [comment]
Thanks!
