### ISSUE TITLE
Convolution with 3 channels

### ISSUE THREAD

**Issue by mabdullahsoyturk** [NVIDIA/cutlass#333]
I was trying to run a convolution layer on an image with the shape of 227x227x3 but apparently the Channel count (C) must be a multiple of 32 (I don't get why we need this assumption). Here is the command that I use:

```bash
./examples/09_turing_tensorop_conv2dfprop/09_turing_tensorop_conv2dfprop  --n=1 --h=227 --w=227 --c=3 --k=96 --r=11 --s=11
``` 

I get "Invalid problem." error.

But when I run the profiler with same dimensions, it seems to be working fine. Here is the command for the profiler:

```bash
./tools/profiler/cutlass_profiler --operation=conv2d --n=1 --h=227 --w=227 --c=3 --k=96 --r=11 --s=11
```

How can I run a convolution described above in my own application? I am simply trying to run a few layers of AlexNet on images.

**Comment by zihaozou** [comment]
Hi, did you find a way to overcome this issue? I am new to this project and still struggle on this problem

**Comment by hwu36** [comment]
To get the best perf, you can pad your channel to 4 and use `FixedChannel` (https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_fixed_channels_f16nhwc_f16nhwc_f16nhwc_tensor_op_f32_sm80.cu#L176) to run it with alignment equals to 4 (https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_fixed_channels_f16nhwc_f16nhwc_f16nhwc_tensor_op_f32_sm80.cu#L154).

padding code is here: https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/device_nhwc_padding.h

**Comment by ioeddk** [comment]
Is the few channels kernel available for SM75?

**Comment by hwu36** [comment]
yes
