### ISSUE TITLE
GEMM with Limited resources

### ISSUE THREAD

**Issue by nnaron** [NVIDIA/cutlass#334]
I know that GEMM is working and optimized very well, but I need to keep some part of GPU free. So here I am looking for a way to limit hGEMM (cublasGemmEx) to use just half of the GPU. Do we have any API or documentation that help me to understand how to specialize it. 

I think this kind of GEMM is done by Tensor Core. So do we have any chance to modify? Is it similar for Volta and Ampere because I think in Volta double and single GEMM is working with Cuda core?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-8

**Comment by hwu36** [comment]
Do you ask us how to do it in cublas?  https://forums.developer.nvidia.com/c/accelerated-computing/gpu-accelerated-libraries/12 is a better place to ask cublas question.

I don't know any cublas API can do it.  If you run small problem size, cublas usually will pick a small kernel to do it, but the runtime of small problem size is short so it is hard and not very useful for you to do something else in parallel.

**Comment by nnaron** [comment]
> Do you ask us how to do it in cublas? https://forums.developer.nvidia.com/c/accelerated-computing/gpu-accelerated-libraries/12 is a better place to ask cublas question.
> 
> I don't know any cublas API can do it. If you run small problem size, cublas usually will pick a small kernel to do it, but the runtime of small problem size is short so it is hard and not very useful for you to do something else in parallel.

I ma calling cublas but what I am seeing inside of profile trace in nsys-ui is a cutlass kernel. 
**cutlass_80_tensorop_d884_gemm_128x64_16x13_nn_align1**

**Comment by hwu36** [comment]
> I ma calling cublas but what I am seeing inside of profile trace in nsys-ui is a cutlass kernel.
cutlass_80_tensorop_d884_gemm_128x64_16x3_nn_align1

Yes, cublas calls cutlass kernels.  The threadblocks that are going to be used for this kernel are `problem_size_m / 128 * problem_size_n / 64`.  Every SM can run 2 such threadblocks.  Do you have spare SMs in your case?

**Comment by nnaron** [comment]
> > I ma calling cublas but what I am seeing inside of profile trace in nsys-ui is a cutlass kernel.
> > cutlass_80_tensorop_d884_gemm_128x64_16x3_nn_align1
> 
> Yes, cublas calls cutlass kernels. The threadblocks that are going to be used for this kernel are `problem_size_m / 128 * problem_size_n / 64`. Every SM can run 2 such threadblocks. Do you have spare SMs in your case?

I want to keep free some small numbers of SMs during GEMM for other kernel. I need parallel executation of GEMM and a small kernel. My understaning about Tensor Core is not enought. I was thinking Tensor Core is something extera to CUDA core, but it seems not and they have shared resources so runing another kernel on the CUDA core is not possible. Is it correct?  

Is half version of GEMM also calling cutlas kernels? I mean A&B as the input in half and result in single.

**Comment by hwu36** [comment]
> I was thinking Tensor Core is something extera to CUDA core, but it seems not and they have shared resources so runing another kernel on the CUDA core is not possible. Is it correct?

Tensor cores are extra to CUDA cores, but they share some resources such as registers.  However, it has nothing to do if two kernels can run in parallel or not.  As long as the SM is free, the 2nd kernel can grab the SM.

> Is half version of GEMM also calling cutlas kernels? I mean A&B as the input in half and result in single.
Maybe yes or maybe no.  You need to use nsight or nvprof to verify it.
