### ISSUE TITLE
replace cublasGemmEx with cutlass equivalent

### ISSUE THREAD

**Issue by nnaron** [NVIDIA/cutlass#340]
Hi, 

I am just started to learn about cutlass and replace cublas code  with cutlass equivalent. I am reading some example but they are complex with lots of defenitons. 

If I want to replace this code in an easy way, which example can help me? 

I am seeing some example, but it seems that they are diferent. 

https://github.com/NVIDIA/cutlass/blob/master/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu
https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu

ALGO  = CUBLAS_GEMM_DFALT_TENSOR_OP;
 cublasGemmEx( queue->cublas_handle(),
  cublas_trans_const( MagmaNoTrans ), cublas_trans_const( MagmaNoTrans ),
  int(maxn-(nextj+nextjb)), int(m-nextj), int(jb),
  &c_neg_one, dAtrsm2_hp,               CUDA_R_16F, int(maxm),
  dApanel_hp,               CUDA_R_16F, int(jb),
  &c_one,     dAT(nextj, nextj+nextjb), CUDA_R_32F, int(lddat),

**Comment by hwu36** [comment]
For a GEMM D = alpha x (A x B) + beta x C

Would you please tell me the following info?

- Hardware (Volta, Turing, Ampere?)
- A: Layout (ColumMajor or RowMajor), datatype (fp16?)
- B: Layout (ColumMajor or RowMajor), datatype (fp16?)
- D: Layout (ColumMajor or RowMajor), datatype (fp16?)
- alpha, beta value?
- problem size (m, n, k)

**Comment by nnaron** [comment]
I should mention something else also. I want to keep under control the GEMM resource utilisation. I mean first version that utilise all GPU resources and another one that keep free 32 SMs.

**Comment by hwu36** [comment]
Volta and Ampere tensor cores are different.  You cannot run Volta tensor core kernels on Ampere.  Let us start with Volta.  [Example 7 ](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu) is what you need.

You just need to change [here](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu#L141-L142) to column major.

Change [here](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu#L209-L211) to your problem size.

That is it.  You should have a functional kernel.  Different problem size needs to use different tile sizes.  You can use [cutlass profiler](https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md) to find the best tile size for your problem size and then change [here](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu#L150-L154) to be your tile size.

> Also I need to do this GEMM in a fast way, maybe by losing some kind of accuracy. Do we have some trick to hide the cost of converting or using other data type? Can I save fp32 part as tf32?

No.  Usually if you convert from big float type to small float type, you can get performance improvement. However, your input is already fp16, the smallest float data type.

> I want to keep under control the GEMM resource utilisation. I mean first version that utilise all GPU resources and another one that keep free 32 SMs.

I don't know how to do it and I cannot think a scenario that it is useful.

**Comment by hwu36** [comment]
Volta and Ampere tensor cores are different.  You cannot run Volta tensor core kernels on Ampere.  Let us start with Volta.  [Example 7 ](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu) is what you need.

You just need to change [here](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu#L141-L142) to column major.

Change [here](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu#L209-L211) to your problem size.

That is it.  You should have a functional kernel.  Different problem size needs to use different tile sizes.  You can use [cutlass profiler](https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md) to find the best tile size for your problem size and then change [here](https://github.com/NVIDIA/cutlass/blob/master/examples/07_volta_tensorop_gemm/volta_tensorop_gemm.cu#L150-L154) to be your tile size.

> Also I need to do this GEMM in a fast way, maybe by losing some kind of accuracy. Do we have some trick to hide the cost of converting or using other data type? Can I save fp32 part as tf32?

No.  Usually if you convert from big float type to small float type, you can get performance improvement. However, your input is already fp16, the smallest float data type.

> I want to keep under control the GEMM resource utilisation. I mean first version that utilise all GPU resources and another one that keep free 32 SMs.

I don't know how to do it and I cannot think a scenario that it is useful.

**Comment by nnaron** [comment]
> 
>    I want to keep under control the GEMM resource utilisation. I mean first version that utilise all GPU resources and another one that keep free 32 SMs.
> 
> I don't know how to do it and I cannot think a scenario that it is useful.
Here I am seeing some configuration. 

https://nvidia.github.io/cutlass/default__gemm__configuration_8h_source.html

Like: 

struct DefaultGemmConfiguration<
 ....
using ThreadblockShape = GemmShape<128, 256, 32>;
198  using WarpShape = GemmShape<64, 64, 32>;
199  using InstructionShape = GemmShape<16, 8, 8>;
...

There you can see that some times the values are different,
...
using ThreadblockShape = GemmShape<128, 128, 32>;
102  using WarpShape = GemmShape<32, 64, 32>;
103  using InstructionShape = GemmShape<1, 1, 4>;
...


using ThreadblockShape = GemmShape<128, 256, 64>;
311  using WarpShape = GemmShape<64, 64, 64>;
312  using InstructionShape = GemmShape<8, 8, 16>;

Do these things not help control the resources consumed for keeping some SMs free?

**Comment by hwu36** [comment]
After your change, every threadblock may use less resources, but you have 4x threadblocks.

You can just build with

`make 07_volta_tensorop_gemm -jxx`

**Comment by mnicely** [comment]
@nnaron have all your questions been answered?
