### ISSUE TITLE
Use cutlass in MAGMA

### ISSUE THREAD

**Issue by nnaron** [NVIDIA/cutlass#342]
Hi, 

Today I wanted to try cutlas inside of MAGMA. I added include path to the [MAGMA](https://icl.cs.utk.edu/projectsfiles/magma/doxygen/index.html) Makefile.

MAGMA_INC += -I/home/xxx/cutlass/include

MAGMA_INC += -I/home/xxx/cutlass/tools/util/include

After that I added inside of MAGMA code like this: 

 #include "cutlass/cutlass.h"
 #include <cutlass/numeric_types.h>
 #include <cutlass/core_io.h>
 #include <cutlass/numeric_types.h>
 #include <cutlass/gemm/device/gemm.h>
 #include <cutlass/util/host_tensor.h>

Or for doing something like example 07: 

 #include "cutlass/cutlass.h"
 #include "cutlass/gemm/device/gemm.h"
 #include "cutlass/util/host_tensor.h"
 #include "cutlass/util/reference/device/gemm.h"
 #include "cutlass/util/reference/host/tensor_compare.h"
 #include "cutlass/util/reference/host/tensor_copy.h"
 #include "cutlass/util/reference/host/tensor_fill.h"
 #include "cutlass/util/tensor_view_io.h"
 #include "helper.h"

 But I am seeing lots of warning and some errors like this: 

/home/xxx/cutlass/include/cutlass/epilogue/warp/tile_iterator_tensor_op.h: At global scope:
/home/xxx/cutlass/include/cutlass/epilogue/warp/tile_iterator_tensor_op.h:71:9: error: declaration of ‘using TensorRef = class cutlass::TensorRef<Element_, cutlass::layout::RowMajor>’ ch
anges meaning of ‘TensorRef’ [-fpermissive]
   71 |   using TensorRef = TensorRef<Element, Layout>;         ///< Tensor Reference object
      |         ^~~~~~~~~

/home/xxx/cutlass/include/cutlass/gemm/device/gemm.h:460:34: error: expected primary-expression before ‘<’ token                                                                          
  460 |     cutlass::Kernel<GemmKernel><<<grid, block, smem_size, stream>>>(params_);                                                                                                         
      |                                  ^                                                                                                                                                    
/home/xxx/cutlass/include/cutlass/gemm/device/gemm.h:460:67: error: expected primary-expression before ‘>’ token                                                                          
  460 |     cutlass::Kernel<GemmKernel><<<grid, block, smem_size, stream>>>(params_);                                                                                                         
      |                                                                   ^           

in file included from /home/xxx/cutlass/include/cutlass/transform/threadblock/predicated_tile_iterator.h:40,                                                                              
                 from /home/xxx/cutlass/include/cutlass/gemm/threadblock/default_mma.h:37,                                                                                                
                 from /home/xxx/cutlass/include/cutlass/gemm/kernel/default_gemm.h:53,                                                                                                    
                 from /home/xxx/cutlass/include/cutlass/gemm/device/gemm.h:39,                                                                                                            
                 from src/xshgetrf_gpu.cpp:25:                                                                                                                                                
/home/xxx/cutlass/include/cutlass/transform/threadblock/predicated_tile_access_iterator.h:613:9: error: declaration of ‘using TensorView = class cutlass::TensorView<Element_, cutlass::la
yout::ColumnMajor>’ changes meaning of ‘TensorView’ [-fpermissive]                                                                                                                            
  613 |   using TensorView = TensorView<Element, Layout>;                                                                                                                                     
      |         ^~~~~~~~~~                                                                                                                                                                    
In file included from /home/xxx/cutlass/include/cutlass/transform/pitch_linear_thread_map.h:37,                                                                                           
                 from /home/xxx/cutlass/include/cutlass/epilogue/threadblock/epilogue.h:52,                                                                                               
                 from /home/xxx/cutlass/include/cutlass/gemm/kernel/default_gemm.h:44,                                                                                                    
                 from /home/xxx/cutlass/include/cutlass/gemm/device/gemm.h:39,                                                                                                            
                 from src/xshgetrf_gpu.cpp:25:                                                                                                                                                
/home/xxx/cutlass/include/cutlass/tensor_view.h:56:7: note: ‘TensorView’ declared here as ‘class cutlass::TensorView<Element_, cutlass::layout::ColumnMajor>’                             
   56 | class TensorView : public TensorRef<Element_, Layout_> {

**Comment by hwu36** [comment]
What compiler do you use?  Can you show me nvcc command line used by your make system.

You can first try to add `-fpermissive` as suggested by your compiler.

**Comment by mnicely** [comment]
@nnaron were you able to resolve your problem?

**Comment by MARD1NO** [comment]
I have test the option with -fpermissive and it solve the same problem!
