### ISSUE TITLE
Max number of streams can be overlapped ?

### ISSUE THREAD

**Issue by ocwins** [NVIDIA/cutlass#354]
I have written a custom kernel using cutlass Conv2D/GEMM components to satisfy my need. In my situation, the problem size of one data-set can't be very large. 

With my configuration, One kernel employs 6 blocks (gird size 6, 1, 1). I want to create  *multiprocessors number / blocks number* streams to execute them in parallel and keep most SMs busy. Using larger data-set has negative impact in my program (not caused by programming, it's a nature characteristics of the problem itself).

On RTX3090 which has 82 SMs, I can only make 8 streams active at same time (for concurrent/overlapped kernel execution), I guess there are at most 6x8=48 SMs participated. Using more streams does not have any effect. I have tried with 8 streams, 40 streams, 80 streams and 13 streams (13 * 6 = 78 < 82).

Are there any limits/rules to use streams in this way?

**Comment by hwu36** [comment]
Default max concurrent streams is 8.  To override it, you need to set env `CUDA_DEVICE_MAX_CONNECTIONS`. See https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars for the details

Also kernel launch overhead is not trivial.  It is possible that when the 1st kernel is finished, not all streams are launched.

**Comment by ocwins** [comment]
> 
> 
> Default max concurrent streams is 8. To override it, you need to set env `CUDA_DEVICE_MAX_CONNECTIONS`. See https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars for the details
> 
> Also kernel launch overhead is not trivial. It is possible that when the 1st kernel is finished, not all streams are launched.

Thank you. 

I have found it yesterday, and played a while. I can't get a 13-fold increase in throughput, there is about 15% performance loss. The kernel launch overhead should not be the reason, in my case, the concurrent execution perform well when I use Nsight System to verify them.

Logically, I can't override it in my program, can I?

Btw, information like this shall be put it in a more prominent place or around titles like concurrent kernel execution in the manual. Another thing is Nsight System 2021.3 and 2021.4 keeps "failed to start" and no one reply to similar subjects like this in official forum. And previous version can't record streams > 8.

**Comment by hwu36** [comment]
Large number of streams can also have negative impact on cache locality.

**Comment by ocwins** [comment]
> 
> 
> Large number of streams can also have negative impact on cache locality.

Got it.

Is there a way to override the max concurrent streams (and other settings like `CUDA_LAUNCH_BLOCKING` and `CUDA_AUTO_BOOST `) by program itself ? an API or something else.  I tried using system API to set env vars in my program, but it didn't work. I think the reason is the cuda context has already be initialized. I haven't tried cudaDeviceReset, nor forking a new process after changing the env variable.

Or because they are configuration made by computer's user/admin, so programs can't change them. Are there any API to directly query them from current cuda context (but not system API to access env vars) ?

**Comment by hwu36** [comment]
Sorry, I don't know the answer to these.

**Comment by mnicely** [comment]
@ocwins I suggest you move your stream and Nsight issues to our Developer Forums
1. Streams - https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-programming-and-performance/7
2. Nsight - https://forums.developer.nvidia.com/c/development-tools/106
