### ISSUE TITLE
Too restrict alignment checking in kernel gemm

### ISSUE THREAD

**Issue by ginowu** [NVIDIA/cutlass#362]
Assume M = 1471, N = 256, K = 512, and A in row major, B in row major, C in row major, kAlignmentA = kAlignmentB = kAlignmentC = 8,

This configuration would fail in can_implement function of device gemm at line: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm.h#L180

Here when checking the alignment, it's better check consider data layout. For example, A is in row major, we could only consider (problem_size.k() % kAlignmentA), which is good for my case.

And for above case, if not calling can_implement, the gemm result is OK.

**Comment by hwu36** [comment]
You are absolutely correct.  Do you want to create a PR?

**Comment by ginowu** [comment]
> You are absolutely correct. Do you want to create a PR?

Sure, will create PR later, thanks!

**Comment by masahi** [comment]
@ginowu Any update? I've just hit this issue where `A` is row major and I was puzzled why I got an alignment error on the row size of A...

**Comment by hwu36** [comment]
We relaxed the alignment check in 2.9.  Only the leading dimension size/stride needs to be the multiple of the alignment.  Check https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L414-L439 for the details.
