### ISSUE TITLE
half / int8 complex matrix vector multiplication implementation suggestion

### ISSUE THREAD

**Issue by hongyx11** [NVIDIA/cutlass#368]
Hi, 

I want to implement half / int8 complex matrix vector multiplication for my project purpose. Currently cublas doesn't support it.

May I ask what's the best way to do it?

I'm also reading the cutlass code and may I ask why cutlass want to implement its own half datatype instead of using half in cuda?

Best,
Yuxi

**Comment by mnicely** [comment]
> I want to implement half / int8 complex matrix vector multiplication for my project purpose.
Are you saying your matrix is in `half` and your vector is in `int8`?

> I'm also reading the cutlass code and may I ask why cutlass want to implement its own half datatype instead of using half in cuda?

If you look at https://github.com/NVIDIA/cutlass/blob/1ac4559d125042d577792c6cb933dd2fbb01a1a9/include/cutlass/half.h you'll see CUTLASS is importing and using `cuda_fp16.h`.

**Comment by hongyx11** [comment]
Okay, Thank you so much!

**Comment by hwu36** [comment]
Our gemv unit tests are [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemv.cu).

You may need to add `complex<half_t>` and `complex<int8>` `Mma `operator in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma_sm50.h

**Comment by hongyx11** [comment]
> Our gemv unit tests are [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemv.cu).
> 
> You may need to add `complex<half_t>` and `complex<int8>` `Mma `operator in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma_sm50.h

Thanks, I will have a look!
