### ISSUE TITLE
06_SplitK_gemm Question

### ISSUE THREAD

**Issue by hongyx11** [NVIDIA/cutlass#369]
[tile can be viewed as a 2d matrix) is 128x128x4096, then we launch a singled a thread-block taking](https://github.com/NVIDIA/cutlass/blob/6b69c79ac3b208e22db1c65c00865be287533554/examples/06_splitK_gemm/splitk_gemm.cu#L32)

Hi,

I'm reading the notes for example 06_splitK_gemm, and I'm not sure what the note means. In the note, it says when launching 128x128x4096 will take a single SM of 84 SMs on V100. 

My question is Does thread-block tile size refer to dimension of thread block?
isn't the limit of thread is (1024, 1024, 64)?
what does the note really mean?

Thanks,
Yuxi

**Comment by mnicely** [comment]
Yes, the thread limit for a thread block on a single SM is (1024, 1024, 64). Within a CUDA kernel the data can be divided up and loaded in many fashions. The takeaway is that Split-K is used for better distribution of workloads.

**Comment by hongyx11** [comment]
I see, Thanks for the reply!
