### ISSUE TITLE
Understanding the serpentine visitation

### ISSUE THREAD

**Issue by gillbam** [NVIDIA/cutlass#370]
Hello,
When reading the code in cutlass\include\cutlass\gemm\thread\mma_sm50.h, I would like to know how to understand the serpentine visitation properly when MMA op is used , the comments say "Serpentine visitation order maximizing reuse of Ra". Does this indicate that the register usage could be higher with Serpentine visitation and why?

Thanks!

**Comment by hwu36** [comment]
> Does this indicate that the register usage could be higher

No.  It just means when we doing mma, we first fix Ra and change Rb.  When all Rb is visited, we change Ra to the next.  It has no impact on how many registers are used.  It just keep reusing Ra as much as possible to improve the register level locality.
