### ISSUE TITLE
int8 convolution for OpClassSimt

### ISSUE THREAD

**Issue by ShaderManager** [NVIDIA/cutlass#371]
```c++
cutlass::conv::kernel::DefaultConv2dFprop <
	int8_t, cutlass::layout::TensorNHWC,
	int8_t, cutlass::layout::TensorNHWC,
	int8_t, cutlass::layout::TensorNHWC,
	int32_t,
	cutlass::arch::OpClassSimt,
	cutlass::arch::Sm61,
	cutlass::gemm::GemmShape<64, 128, 128>, // ThreadBlock shape
	cutlass::gemm::GemmShape<32, 64, 128>, // WarpTile shape
	cutlass::gemm::GemmShape<1, 1, 4>, // Instruction shape
	cutlass::epilogue::thread::LinearCombinationClamp<int8_t, 4, int32_t, float>,
	cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<1>,
	2, // NumStages,
	cutlass::arch::OpMultiplyAddSaturate,
	cutlass::conv::IteratorAlgorithm::kOptimized,
	cutlass::conv::StrideSupport::kStrided
>::Kernel;
```

This kernel for int8 convolution on Sm61 architecture (which implies dp4a instruction) emits error while trying to store fragment to shared memory here: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_pipelined.h#L208
More specifically loop loads `Fragment = cutlass::Array<int8_t, 16, false>` and tries to call `store` on iterator with `Fragment = cutlass::Array<int8_t, 64, false>`

I assume this happens because https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear_2dthreadtile.h#L400 and https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/conv2d_tile_iterator.h#L76 specify different-sized `Fragment` type.

Is this a bug in the code or I specify invalid thread-block/warp shapes?

P.S.: Corresponding kernel for `OpTensorOp/Sm75` architecture compiles without errors

**Comment by hwu36** [comment]
We currently do not support `idp4a` convolution.  We support int8 tensor core convolution starting from sm75 though.

As you already noticed that our convolution algorithm tries to reuse the gemm implementation.  However, our `idp4a` gemm implementation cannot be used by the convolution.

**Comment by wllvcxz** [comment]
Hi,

I got the same problem when trying to instantiate a `dp4a` convolution. Is there some guidance i can follow to implement the `dp4a` convolution?

Thanks.

**Comment by hwu36** [comment]
It is not a small project.  You first need to implement a interleaved<4> idp4A gemm, then build a interleaved<4> idp4A conv on top of it.

You need to study how idp4A non interleaved gemm works, then take a look at interleaved<32> int tensor core gemm and conv.
