### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by theoqian** [NVIDIA/cutlass#372]
Hi cutlass team, I'm trying to debug cutlass project in vscode via cuda-gdb. But the break points in kernels never hit. I got 'Module containing this breakpoint has not yet loaded or the breakpoint address could not be obtained.' in vscode debuger. And if I set '-G' to 'NVCC_FLAGS' in CMakeList.txt I got 'line xxx not in file'. Could you please show me how to debug the project correctly? Thanks.

**Comment by hwu36** [comment]
Don't use cuda-gdb to debug any heavy templated CUDA code.  We just insert printf to dump the information to debug.  We have some utilities to help you to do it.  Check this [example](https://github.com/NVIDIA/cutlass/tree/master/examples/02_dump_reg_shmem) .

Also `-G` can cause miscompilation in cuda 11.4 and 11.5

**Comment by theoqian** [comment]
Thanks. I also find a solution here https://forums.developer.nvidia.com/t/cuda-gdb-cannot-set-break-point-in-device-function-defined-in-a-header-h-file/78233
