### ISSUE TITLE
cutlass kernel uses too many shared memories, resulted in low SM occupancy and SM SOL%

### ISSUE THREAD

**Issue by void-main** [NVIDIA/cutlass#380]
## Summary
We're upgrading our GPU card from `T4` to `A10` for inference, however, the GEMM performance doesn't meet the expectations.

## How to reproduce
We wrote a simple test pytorch program:

```
import torch
import numpy as np

with torch.cuda.device(0):
    tensor1 = torch.randn(1, 20480, 128).cuda()
    tensor2 = torch.randn(1, 128, 256).cuda()

    res = torch.matmul(tensor1, tensor2)
```

And collect profiling data with `Nsight Compute`. On T4 (CUDA 10.2, which uses `volta_sgemm_128x64_nn`) the overall GPU usage looks great:
<img width="1315" alt="CleanShot 2021-12-13 at 21 50 59@2x" src="https://user-images.githubusercontent.com/552990/145824422-5277ad87-b97b-4b6f-8d7b-3321f0e7ac0d.png">

However, when running the same code on A10 (CUDA 11.4, which uses `cutlass_80_tensorop_s1688gemm_256x64_nn_align4`), the kernel only uses 40% of the GPU:
<img width="1307" alt="CleanShot 2021-12-13 at 21 53 22@2x" src="https://user-images.githubusercontent.com/552990/145824802-61336ad6-3f61-4825-ab5e-1b8b6fe027ab.png">

And the SM Occupancy is pretty low (8.33%), which is limited by shared memory according to Nsight Compute:
<img width="1273" alt="CleanShot 2021-12-13 at 21 53 37@2x" src="https://user-images.githubusercontent.com/552990/145824898-e9019982-af6b-4960-be3b-b22e01e0272c.png">

## Questions
Since the GEMM kernel is so important in AI inference, we wonder is the performance expected? What makes the GEMM kernel not performing well (why it's taking more shared memories than on T4)? And how could we improve it in our application?

Thank you very much!

**Comment by hwu36** [comment]
In general, Ampere kernels consume more shared memory because Ampere tile size is bigger and stage number is larger.

As to your case, I'd like to know a little more.  What is your input and output data types? fp16 or fp32?

**Comment by void-main** [comment]
Turns out we are comparing Tensor core to CUDA core, which makes no sense. Thanks for the rely. Closing this issue.
