### ISSUE TITLE
[BUG] Installing with HEADERS ONLY Set Does Not Include All Necessary Headers - v2.8.0

### ISSUE THREAD

**Issue by depaulmillz** [NVIDIA/cutlass#387]
In v2.8.0, when installing through CPack and CMake with CUTLASS_ENABLE_HEADERS_ONLY set ON, the files in tools/util/include are not installed. The files are however referenced throughout the headers cutlass. For example: include/cutlass/epilogue/threadblock/epilogue.h references a header in util. This prevents using the library if its been installed as header only.

To reproduce the bug, run `cmake` with `-DCUTLASS_ENABLE_HEADERS_ONLY=ON`. Then in the build directory run `cpack -G ZIP`. After unzipping you will notice the include folder does not contain the util folder.

I think when `CUTLASS_ENABLE_HEADERS_ONLY=ON` that the headers in util should be included.

**Comment by hwu36** [comment]
@d-k-b, would you please take a look at the PR ?

**Comment by d-k-b** [comment]
Fix with https://github.com/NVIDIA/cutlass/pull/388.
