### ISSUE TITLE
Accumulate in different type than input/output

### ISSUE THREAD

**Issue by orentropp** [NVIDIA/cutlass#39]
I am writing gemm for my own types. Input/output type is 32bit, but the accumulation needs to be 64bit.
I have all the +*= operators implemented so I can work with multiply add, but cannot get the code to compile.
Is there an example of how to do this?
Also, for epilogue, I need no operation except that I have impleneted the code
outputType = AccumulatorType 
to do the proper math (not just casting). Is this adaquate or do I need something else?

It seems that a Cub like approach to operators can simplify the API a lot. Operators can be passed along with their parameters to make a very simple Host side interface.
Thanks!

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-67

**Comment by d-k-b** [comment]
Can you push a branch with an updated example or unit tests with your changes? It should be possible to use a different accumulation type, but if there are no tensor core configurations that match the types well the code will fall back to a more traditional unrolled software loop. What GPUs are you targeting as well?
