### ISSUE TITLE
[QST] Is there layout convert for the device memory?

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/cutlass#399]
Hi,

I want to do some layout conversion, like NCHW<->NHWC, or NCx32HW<->NCxHW32.
I see there is transform and matrix layout code, not sure whether it could be served for the device memory layout conversion purpose.

Thx,
Lei

**Comment by hwu36** [comment]
At this moment, we don't have a out-of-box solution.  If you don't care of the performance, the easiest thing you can do is just using two `HostTensor` `t1`, `t2` with NHWC and NCHW layouts.  Then,

`t1.at{n, h, w, c} = t2.at{n, c, h, w};`

**Comment by leiwen83** [comment]
I see. Thx
