### ISSUE TITLE
error: more than one conversion function from "half" to a built-in type applies

### ISSUE THREAD

**Issue by jeng1220** [NVIDIA/cutlass#4]
Hi all,
I met  a error thrown by nvcc compiler when I used CUTLASS library to implement Hgemm (FP16 GEMM). Following log as error message:
```
error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
```

This error was caused at https://github.com/NVIDIA/cutlass/blob/master/cutlass/gemm/epilogue_function.h : 88
```
class blas_scaled_epilogue
{
   //...ignore...​

        inline __device__
        bool must_init_addend()
        {
            return (beta != scalar_t(0)); // <-- here, "scalar_t" was defined as half (FP16) type, beta was a member variable of this class
        }
   //...ignore...​
};
```

Do you guys know how to solve this error ?

**Comment by jeng1220** [comment]
Just answer myself...
Specifying GPU architecture (-arch=sm_xx) as compiler flag can solve this error.

**Comment by lobanov-m** [comment]
This error also appears if you set GPU architecture that does not support fast FP16 (i.e. sm_35, sm_52). Setting it to sm_70 (for example) allows to compile, but you could not use it if your GPU does not support it.

**Comment by lobanov-m** [comment]
Understood, thank you. I wrote it just for information to help someone who can find this topic in Google, like me.

**Comment by SakuraRiven** [comment]
Hi, we also meet this question, but it does not work when I add the following into my CMakeLists.txt
```
set(CMAKE_CUDA_ARCHITECTURES 86)
or
set(CUDA_ARCHITECTURE_FLAGS "86")
```
So, what is the correct way to set cuda architecture in cmake?

**Comment by YLSnowy** [comment]
After testing, it was determined that the version of nvcc --version did not match the actual version. My nvcc-version was 11.8, but the conda environment was installed with 12.1, which caused the above problem. This problem was solved after changing the version.

**Comment by andychenbruce** [comment]
For me I think the error dissapeared after changing conda's `cuda-toolkit` to match the version of cuda from `nvidia-smi`

Before `cuda-toolkit` was 12.4, and the output of `nvidia-smi` is
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
```
so doing `conda install cuda-toolkit=12.1` downgraded from 12.4 to 12.1
