### ISSUE TITLE
Could there be a direct way to do type conversion when storing to global

### ISSUE THREAD

**Issue by edimetia3d** [NVIDIA/cutlass#40]
The default output type of IGEMM is `int32_t`, In my situation, I need to store the ans as a fixed-point number in a  `uint8_t`.

 It's easy to do the caculation as isuue #17  mentioned. But when I want to save the data , I have to do some intrusive modification in `struct GemmGlobalIteratorCd` and `struct Store`.  Though the modification is simple, I did a lot of tests to figure out how the global store works.

So , I hope there could be a better solution in future.

**Comment by edimetia3d** [comment]
If someone need the similar function, here is my  solution https://github.com/edimetia3d/cutlass/commit/8fc8e3724d9d887b7c48f9ca11c27de39d1ae254

**Comment by kerrmudgeon** [comment]
It looks like you have addressed this reasonably well.

Fwiw, the CUTLASS 2.x codebase should support this case relatively well, accommodating any arbitrary functor applied to the epilogue including type conversion.

Thanks for posting!
