### ISSUE TITLE
Multiple initializations cost[QST]

### ISSUE THREAD

**Issue by JustLuoyu** [NVIDIA/cutlass#405]
**What is your question?**
Assume that I have two convolutions executing on one kernel with different problem sizes.  What I can come up with is: 
`ImplicitGemm implicit_gemm_op;
implicit_gemm_op.can_implement(argumentsA);
implicit_gemm_op.initialize(argumentsA, workspaceA.get());
implicit_gemm_op()
implicit_gemm_op.can_implement(argumentsB);
implicit_gemm_op.initialize(argumentsB, workspaceB.get());
implicit_gemm_op()`

Can these can_implement and initialize API calls be the performance issue? or there is a better way for it. Will the constructor of ImplicitGemm in a runtime-process function be the performance issue?

**Comment by JustLuoyu** [comment]
Maybe can_implement should be used with workspace' malloc, only call once.

**Comment by JustLuoyu** [comment]
I've looked through the source codes, I think the constructor won't be a problem.
But this puzzles me:

```
/// Runs the kernel using initialized state.
  Status operator()(cudaStream_t stream = nullptr) {
    return run(stream);
  }

  /// Runs the kernel using initialized state.
  Status operator()(
    Arguments const &args, 
    void *workspace = nullptr, 
    cudaStream_t stream = nullptr) {
    
    Status status = initialize(args, workspace, stream);
    
    if (status == Status::kSuccess) {
      status = run(stream);
    }

    return status;
  }
```

**The second operator shouldn't be in an initialized state.** 

Now I think the class of ImplicitGemmConvolution is just a way to launch the template kernel.

**Comment by hwu36** [comment]
You can use this version of `operator()`: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/device/implicit_gemm_convolution.h#L270-L272

**Comment by JustLuoyu** [comment]
Tested. Kernel's initialization is not a time-consuming operation.
