### ISSUE TITLE
Multiplication of int8 type in large-scale asymmetric matrices performs poor.

### ISSUE THREAD

**Issue by PHILHHHHHe** [NVIDIA/cutlass#41]
I try using Tensor core with IWMMA by RTX2080, but it did not seem to work properly when the in8 matrix is: M = 100W N =16~512 K=384 and  it is only up to 28 Tflops/s which severely declines.

When matrix dimensions are M=N=K=4096, it is up to 64TFlops/s. But I think there is still a certain distance from the peak using Tensor core.

The 05_wmma example I use is from cutlass.

How can I operate to reach 90TFlop/s?
I am very eager to find a solution. Thanks.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-66

**Comment by PHILHHHHHe** [comment]
@kerrmudgeon Sincerely hope to get your reply.

**Comment by hwu36** [comment]
> How can I operate to reach 90TFlop/s?

wmma is easy to use, but it cannot help you reach the peak.  you need to use `mma.sync` directly to get the best performance (https://github.com/NVIDIA/cutlass/blob/c805593ebe488826858b1675599513cdbb2c141a/include/cutlass/arch/mma_sm75.h#L478).

Check this new example: https://github.com/NVIDIA/cutlass/blob/master/examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu
