### ISSUE TITLE
Question about fused per-channel bias-add[QST]

### ISSUE THREAD

**Issue by gillbam** [NVIDIA/cutlass#410]
**Why do not we fuse the scale-bias with conv weights directly? **
sth like:
scale-bias & conv weights -> cb weights 
cb weights & activations -> `implicit_gemm_multistage.h` -> cb results

Instead, [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_fprop_fusion_multistage.h), we load the bn weights and conv weights from memory separately via `IteratorScaleBias`, `WarpIteratorScaleBias_ ` and others.  I think we could save those iterators by directing merging two weights offline?

**Comment by hwu36** [comment]
For tensor core bounded kernels, we can insert some non tensor core operations such as memory accesses or cuda core computations for free.  They will be hidden by the tensor core computations.

**Comment by gillbam** [comment]
Thanks for the reply.
