### ISSUE TITLE
[QST] Int8 support for Dgrad+Wgrad conv2d

### ISSUE THREAD

**Issue by xxtemp** [NVIDIA/cutlass#411]
It seems that for now there is only int8 support for Fprop conv2d.
Is there a planned future support for Dgrad and Wgrad as well? Where should I start if I want to try to implement it on my own with ARCH_MMA_SM80 support?

**Comment by xxtemp** [comment]
Thanks a lot for the detailed answer.

I initially posted the question here to find a way to avoid the overhead of transposing the filter data when calculating Dgrad, but I guess I can always keep 2 versions of the same data, one transposed and one isn't. Then the problem becomes just like fprop and the performance hit shouldn't be drastic.
Wgrad is different in my case because I don't have the data in advance (to prepare a transposed version) and I believe it would be way faster to use fp16 than transposing it manually.
Anyway, thanks again. I will close the issue soon.

**Comment by hwu36** [comment]
Are you building a framework based on cutlass?

**Comment by xxtemp** [comment]
Not yet, but I'm thinking about it.
Basically what we have is a solution for int8 training (forward+backward) that worked well with many of the typical CNNs and causes no degradation in accuracy. My problem is, simulating this int8 quantization between every two layers takes some time, and I end up with training time that is longer than when using the actual fp32 model, even though every multiplication that is done in the network is 8bx8b. I expect there to be a dedicated HW in the future that would allow me to have a very decent speed-up.
So in the meantime, until a dedicated HW solution arrives, I was curious to see if I could speed things up by using cutlass. I'm afraid I won't be able to reach the peak performance I was hoping for, since as you mentioned ldmatrix does not work with int8 data, but it's still worth testing with Fprop+Dgrad in int8 and Wgrad in fp16.

**Comment by hwu36** [comment]
Interesting.  Keep me posted and I am happy to help if you have any questions.

Generally, you can do the forward pass in int8 and backward in fp16.  cutlass allows the input and output to use different data types and even alignments.

**Comment by xxtemp** [comment]
Thanks! I really appreciate your help.

I have another question, I'm not sure if I should post it here or open a new issue. If you think I should start a new one please let me know.
In Cudnn there's a function for both Dgrad and Wgrad (cudnn_convolution_backward, returns a tuple with both Dgrad and Wgrad), given that they both share the same data, that is faster than calculating each one separately. Is there something similar in Cutlass that I could try?
