### ISSUE TITLE
[QST]cuSPARSE

### ISSUE THREAD

**Issue by wxthu** [NVIDIA/cutlass#418]
I just wonder know whether cuSPARSE has been integrated into CUTLASS and how I call this API

**Comment by hwu36** [comment]
cuSPARSE is one level above CUTLASS.  So far, the only sparse kernel available inside cutlass is sparse tensor core gemm kernel.  Please check https://github.com/NVIDIA/cutlass/tree/master/examples/15_ampere_sparse_tensorop_gemm

**Comment by wxthu** [comment]
thanks so much
