### ISSUE TITLE
[QST]Sample code cannot run

### ISSUE THREAD

**Issue by wxthu** [NVIDIA/cutlass#420]
when I run the sample in the QuickStart and following compiling errors occured. I wonder that if I need link some other libraries?
![image](https://user-images.githubusercontent.com/73052387/157148275-4dcb9c7b-ff49-4afe-b3e8-e26c3e2c7c30.png)

**Comment by hwu36** [comment]
I noticed that you used `g++`.  You need to use `nvcc` to build NVIDIA GPU kernels.  Also, we usually use `.cu` suffix in the GPU file name.

**Comment by wxthu** [comment]
> I noticed that you used `g++`. You need to use `nvcc` to build NVIDIA GPU kernels. Also, we usually use `.cu` suffix in the GPU file name.

Thanks so much for you reply! As a novice for cuda programming and CUTLASS, I try to run the sample code in the guide as following :
![image](https://user-images.githubusercontent.com/73052387/157158740-4842ad29-3f12-431d-8803-d7149f9f697d.png)
but when I run binary file, I met some errors and very confused:
![image](https://user-images.githubusercontent.com/73052387/157158948-17b0c7ab-fdd6-437e-aae8-66150addfb23.png)

**Comment by hwu36** [comment]
what gpu do you have?   i think you need to specify sm75.  `-arch=sm_75 -gencode=arch=compute_75,code=sm_75`

**Comment by wxthu** [comment]
> what gpu do you have? i think you need to specify sm75. `-arch=sm_75 -gencode=arch=compute_75,code=sm_75`

I run the code on NVIDIA GeForce RTX 3090

**Comment by hwu36** [comment]
Okay then change 75 to 86
