### ISSUE TITLE
[BUG] 23_ampere_gemm_operand_reduction_fusion error - results miscompared

### ISSUE THREAD

**Issue by chenyang78** [NVIDIA/cutlass#423]
**Describe the bug**
I am not sure if I mis-used the command line options or hit an actual bug in the example. Passing ```--split-k-slices=2 --parallel-split-k``` gave me mismatched results. 

**Steps/Code to reproduce bug**
```
# assume that we've checked out the repo and are in the repo root folder
$ git rev-parse HEAD
b2e1e97cb1e1a14def379fdb848351248bcfc771
$ mkdir build
$ cd build
$ cmake .. -DCUTLASS_NVCC_ARCHS=80
$ make 23_ampere_gemm_operand_reduction_fusion
$ ./examples/23_ampere_gemm_operand_reduction_fusion/23_ampere_gemm_operand_reduction_fusion --split-k-slices=2 --parallel-split-k
ERROR - results miscompared.
ID,M,N,K,SplitK-Slices,Parallel-SplitK,Runtime
gemm_1,1024,1024,1024,2,1,0
```

**Expected behavior**

I would expect the test passed.

**Comment by hwu36** [comment]
ACK.  I will investigate.  Should be something silly.  It used to work.

**Comment by hwu36** [comment]
The code is mostly correct.  The alpha, beta values passed to the reduction kernel is not correct.  If you set them as alpha=1, beta=0.  The result is correct.

I will check what is going wrong in the reduction kernel side soon.

**Comment by hwu36** [comment]
I know the problem.  When doing parallel splitk, alpha in the gemm needs to set to 1 and beta in the gemm needs to be set to 0.  The reduction kernel will use the alpha and beta value set by the users.

Changes like below can pass the test

```
--- a/examples/23_ampere_gemm_operand_reduction_fusion/ampere_gemm_operand_reduction_fusion.cu
+++ b/examples/23_ampere_gemm_operand_reduction_fusion/ampere_gemm_operand_reduction_fusion.cu
@@ -398,8 +398,10 @@ Result profile(Options const &options) {
   tensor_reduction.sync_device();
 
   // Initialize alpha for dot product computation
-  ElementComputeEpilogue alpha = ElementComputeEpilogue(options.alpha);
-  ElementComputeEpilogue beta = ElementComputeEpilogue(options.beta);
+  ElementComputeEpilogue alpha = options.parallel_split_k ? ElementComputeEpilogue(1)
+                                                          : ElementComputeEpilogue(options.alpha);
+  ElementComputeEpilogue beta = options.parallel_split_k ? ElementComputeEpilogue(0)
+                                                         : ElementComputeEpilogue(options.beta);
 
   cutlass::gemm::GemmUniversalMode mode = options.parallel_split_k ? 
                      cutlass::gemm::GemmUniversalMode::kGemmSplitKParallel :
@@ -455,6 +457,10 @@ Result profile(Options const &options) {
 
   if (options.parallel_split_k && batch_count > 1) {
     // reduce gemm
+
+    ElementComputeEpilogue alpha = ElementComputeEpilogue(options.alpha);
+    ElementComputeEpilogue beta = ElementComputeEpilogue(options.beta);
+
     int splitk_gemm_stride = options.problem_size.m();
 
     cutlass::layout::RowMajor splitk_gemm_layout(splitk_gemm_stride);
@@ -531,10 +537,10 @@ Result profile(Options const &options) {
     gemm_device
       (
         options.problem_size,
-        alpha, 
+        ElementComputeEpilogue(options.alpha),
         tensor_a.device_ref(),
         tensor_b.device_ref(),
-        beta, 
+        ElementComputeEpilogue(options.beta),
         tensor_c.device_ref(), 
         tensor_ref_d.device_ref()
       );
```

**Comment by hwu36** [comment]
Do you like to file a PR?

**Comment by chenyang78** [comment]
@hwu36 Thank you so much for the prompt fix! Yes, I am happy to make a PR. Before I do that, may I ask a couple of questions to make myself understand this example better? 

(1) With this change, when we pass ```--parallel-split-k```, we end up using different alpha and beta values for the first gemm op (i.e. the one with ```cutlass::gemm::GemmUniversalMode::kGemmSplitKParallel```) and the second gemm op (i.e. the reference gemm_device kernel)? I am not sure my understanding is correct or not, but seems kGemmSplitKParallel only changes the way in which we compute a Gemm by K-tiling, i.e. we split both A and B along the K dimension, do Gemm computations on small tiles and then accumulate the sub Gemm computations into C. So, I would expect the first gemm op gave us the same result for the same alpha and beta with and without ```--parallel-split-k```. However, seems it's not the case. I guess I don't really understand what the first Gemm op computes with the follow arguments

```
  typename Gemm::Arguments arguments{                                           
      mode,                                                                       
      options.problem_size,                                                       
      batch_count,
      ...
```
For example, let's say MxNxK = 16x8x16 and batch_count = 2(which is the same as split_k_slices) , what C would we expect to get? Seems it's not the same as something like ```Gemm(A1, B1) + Gemm(A2, B2)```, where A1, A2 and B1, B2 are sub matrices of A and B respectively:
```
A(16x16) = A1(16x8) | A2(16x8)

              B1(8x8)
B(16x8) = --------
              B2(8x8)
```

I printed out some intermediate tensor results and noticed that after the first gemm_op, tensor_d still had all zeroes. However, after the first reduction op ```reduce_gemm_splitk_op``` finished, tensor_d got filled in with correct gemm computation results. So, seems to me, somehow this gemm_op with split-k placed intermediate results of Gemm(A1, B1) and Gemm(A2, B2) at workspace_gemm_ptr, where the subsequent reduce_gemm_splitk_op got data. 

However, I am still confused with one more thing. This comes to my second question below.

(2) I could be wrong, but based on my understanding of reduce_splitk kernels, I would expect the reduce_gemm_splitk_op sums up (assume our reduction op is add) ```batch_count``` of MxN matrices, given the following arguments:

```
    typename ReduceGemmSplitK::Arguments reduce_gemm_splitk_arguments{          
        cutlass::MatrixCoord(options.problem_size.n(), options.problem_size.m()), 
        batch_count,
        ...
```

What I am confused is that why we pass beta=-1 to it? In particular, tensor_c seems to contain the same content as A1 at the moment. 

(3) Last, I don't really understand why the second reduction kernel gave us the correct reduction result. For example, when batch_count is 2 and this kernel will just try to sum up 2 of 1 x reduce_vector_length vectors which locate at the place pointed by workspace_vector_ptr. It's hard to link this behavior with row-reduction on A. Well, I guess it might relate to what we placed at workspace_vector_ptr. 

Sorry for asking these silly questions. I am just trying to understand the magic behind it. Thanks!

**Comment by hwu36** [comment]
There is no magic here.  Just standard parallel split k behavior in blas.

We need a temporary workspace to store the immediate results of gemm.  The workspace size equals to `(batch_size x m x n)`.  Every slice is stored in its own `mxn` part inside the workspace.  The reduction kernel adds these `batch_size` `mxn` pieces together at last.  Suppose, we try to do

D = alpha x (A x B) + beta x C

When using parallel splitK, it works like

```
workspace[i] = (A[i] x B[i])                // First gemm kernel
D = alpha x sum(workspace[i]) + beta x C    // Second reduction kernel
```

**Comment by chenyang78** [comment]
@hwu36 Thank you for the explanation! This is the same as I observed. I took another look at the code and saw why we set up those alpha and beta values for split-k gemm, reference gemm and the first reduction kernel that sums up workspace[i]. 

Could you explain a little bit more about the second reduction kernel (i.e. reduce_vector_splitk_op) ? It seems when we compute each ```A[i] x B[i]```, we also put the result of ```reduce(A[i])``` right after the result of ```A[batch_size-1] x B[batch_size-1]``` in the workspace.  Am I correct? Again, thank you for the help!

**Comment by chenyang78** [comment]
PR created:

https://github.com/NVIDIA/cutlass/pull/424

Thanks!

**Comment by hwu36** [comment]
> It seems when we compute each A[i] x B[i], we also put the result of reduce(A[i]) right after the result of A[batch_size-1] x B[batch_size-1] in the workspace. Am I correct?

Correct.  If you manages memory yourself, you can put temporary result anywhere you want.

**Comment by chenyang78** [comment]
This issue was resolved. Closing it. Thanks.
