### ISSUE TITLE
[QST] Does conv2d support asymmetric padding?

### ISSUE THREAD

**Issue by wllvcxz** [NVIDIA/cutlass#425]
**What is your question?**

Hi all:
I am trying to offload conv2d from TVM to cutlass, however I find that `Conv2dProblemSize` only has two parameters `pad_h` and `pad_w` to control the behavior of padding (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/conv2d_problem_size.h#L62) It seems that conv2d only support symmetric padding. 

I am not sure whether have I missed something or currently asymmetric padding is not supported in cutlass conv2d?

Thanks!

**Comment by manishucsd** [comment]
Thanks for the question. 

Although, you only see `pad_h` and `pad_w`, you can support asymmetric padding with CUTLASS convolutions by setting output `P` and `Q` explicitly. 

This question could be helpful for others and I wrote a discussion section to answer this here : https://github.com/NVIDIA/cutlass/discussions/426

**Comment by wllvcxz** [comment]
Thanks for your quick reply!
