### ISSUE TITLE
[BUG] Example '15_ampere_sparse_tensorop_gemm' is not working

### ISSUE THREAD

**Issue by rjfnobre** [NVIDIA/cutlass#428]
Execution of example '15_ampere_sparse_tensorop_gemm' fails.
Compiled with CUDA 11.6. 

I get the following output on both RTX 3060S and A100 GPUs:
```
terminate called after throwing an instance of 'cutlass::cuda_exception'
what():  std::exception
```

**Comment by hwu36** [comment]
Sorry, I cannot reproduce.  Can you find out where the crash happens?

```
[haichengw@ipp1-0234 build]$ ./examples/15_ampere_sparse_tensorop_gemm/15_ampere_sparse_tensorop_gemm 
Passed
```

**Comment by mnicely** [comment]
@rjfnobre are you able to provide @hwu36 with a reproducer?
