### ISSUE TITLE
Does cutlass support multi-GPU.

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/cutlass#43]
Dear sir:
   Does cutlass support multi-GPU automatically.

**Comment by kerrmudgeon** [comment]
CUTLASS uses [CUDA streams](https://devblogs.nvidia.com/gpu-pro-tip-cuda-7-streams-simplify-concurrency/) to launch GEMM kernels and can be used in a multi-GPU application.

The kernels CUTLASS launches are, however, single-GPU operations that an application would need to compose to compute larger computations distributed across multiple GPUs and multiple nodes.
