### ISSUE TITLE
How to use other data types / lower cuda arch for the grouped GEMM?

### ISSUE THREAD

**Issue by Karbo123** [NVIDIA/cutlass#431]
I recently found [grouped GEMM](https://github.com/NVIDIA/cutlass/blob/master/examples/24_gemm_grouped/gemm_grouped.cu) was an useful implementation which avoids writing a slow for loop in our codes, and wanted to extend it by supporting more data types.

The provided example [grouped GEMM](https://github.com/NVIDIA/cutlass/blob/master/examples/24_gemm_grouped/gemm_grouped.cu) seems only implement for half (fp16) precision on an ampere arch (compute capability >= 80). I wonder if the grouped GEMM API can also support other data types such as float32 or float64?

I was a little confused about this configuration in [the template parameter list](https://github.com/NVIDIA/cutlass/blob/master/examples/24_gemm_grouped/gemm_grouped.cu#L1246). The provided example can run smoothly without any errors, but changing these parameters directly will cause a lot of compilation errors for me. I think these parameters are coupled together, and it is hard to just change one of them.

Could you provide other configuration examples for types such as float32 or float64?
Is it possible for the grouped GEMM run on a lower cuda arch (e.g. compute capability < 80)? 
Many thanks!

**Comment by hwu36** [comment]
Thank you for trying it.  Group gemm is powerful.

Different data types and arch impact the available tile sizes.

Example of dgemm (not grouped) is

```
// Gemm operator cutlass_simt_dgemm_128x128_8x2_tt_align1
using cutlass_simt_dgemm_128x128_8x2_tt_align1_base =
  typename cutlass::gemm::kernel::DefaultGemmUniversal<
    double, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 1,    // transposed B operand
    double, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 1,    // transposed A operand
    double, cutlass::layout::RowMajor,
    double,
    cutlass::arch::OpClassSimt,
    cutlass::arch::Sm50,
    cutlass::gemm::GemmShape<128, 128, 8>,
    cutlass::gemm::GemmShape<32, 64, 8>,
    cutlass::gemm::GemmShape<1, 1, 1>,

    cutlass::epilogue::thread::LinearCombination<
      double,
      1,
      double,
      double
    >
,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    2,
    cutlass::arch::OpMultiplyAdd
>::GemmKernel;
```

Example of sgemm (not grouped) is 
```
using cutlass_simt_sgemm_128x128_8x2_tt_align1_base =
  typename cutlass::gemm::kernel::DefaultGemmUniversal<
    float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 1,    // transposed B operand
    float, cutlass::layout::ColumnMajor, cutlass::ComplexTransform::kNone, 1,    // transposed A operand
    float, cutlass::layout::RowMajor,
    float,
    cutlass::arch::OpClassSimt,
    cutlass::arch::Sm50,
    cutlass::gemm::GemmShape<128, 128, 8>,
    cutlass::gemm::GemmShape<32, 64, 8>,
    cutlass::gemm::GemmShape<1, 1, 1>,

    cutlass::epilogue::thread::LinearCombination<
      float,
      1,
      float,
      float
    >
,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
    2,
    cutlass::arch::OpMultiplyAdd
>::GemmKernel;
```
You can get these examples from cutlass profiler.  For example, i get above by

`/home/utils/cmake-3.14.1/bin/cmake .. -DCUTLASS_NVCC_ARCHS=your_arch -DCUTLASS_LIBRARY_KERNELS=sgemm,dgemm`

Then the kernels will be generated under `tools/library/generated/gemm/`

Another way to find available tile size is to find them in our device unit tests: https://github.com/NVIDIA/cutlass/tree/master/test/unit/gemm/device

**Comment by Karbo123** [comment]
Thank you very much!!
