### ISSUE TITLE
[BUG] CMake transitive target doesn't appear to work

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/cutlass#432]
**Describe the bug**
After using `add_subdirectory` on CUTLASS in a CMake project, I'd expect CUTLASS's transitive target(s) to be exported for use in other projects. I have tried the following targets:
```
nvidia::cutlass::CUTLASS
nvidia::cutlass::cutlass
nvidia::cutlass
nvidia::CUTLASS
```

but all of them produce the error: 
```
links to target "nvidia::cutlass::CUTLASS" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

**Steps/Code to reproduce bug**
Import cutlass using `add_subdirectory` and try to use transitive targets inside of `target_link_libraries`.

**Expected behavior**
Includes and libraries would be populated

**Environment details (please complete the following information):**
Ubuntu 20.04
CUTLASS 2.8.0
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] 
Container

**Comment by hwu36** [comment]
@d-k-b

**Comment by GammaPi** [comment]
```
add_library(CUTLASS INTERFACE)
add_library(nvidia::cutlass::cutlass ALIAS CUTLASS)
set_target_properties(CUTLASS PROPERTIES EXPORT_NAME cutlass)
```
It looks like you should use CUTLASS?

**Comment by d-k-b** [comment]
Hey @cliffburdick, I finally got around to fixing and cleaning up some of the CUTLASS CMake code. I tested this out and it worked fine for me using CMake 3.18.

```
cmake_minimum_required(VERSION 3.18 FATAL_ERROR)

project(cutlass_import_example VERSION 0.1 LANGUAGES CXX CUDA)

add_subdirectory(${CUTLASS_DIR} ${CMAKE_CURRENT_BINARY_DIR}/cutlass)

add_executable(example)

target_sources(example PRIVATE main.cpp)

target_include_directories(
  example
  PRIVATE
  ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}
  )

target_link_libraries(
  example
  PRIVATE
  nvidia::cutlass::cutlass
  nvidia::cutlass::library
  )
```

The build included the proper CUTLASS headers and linked with the CUTLASS library. One thing to note, you need to use `nvidia::cutlass::cutlass` as the alias, as CMake is case-sensitive.
