### ISSUE TITLE
[QST] Why part of functions related to uint128_t are not supported on platform other than x86_64?

### ISSUE THREAD

**Issue by Peter9606** [NVIDIA/cutlass#434]
https://github.com/NVIDIA/cutlass/blob/cd39c75e250ef1c3dd11cd59dca4e53efe7d5ea8/include/cutlass/uint128.h#L45-L60

Don't quite know why `__x86_64` is specified here, I tried to remove this constraint and executed reduction test cases on aarch64 platform, and got all cases passed.

**Comment by mnicely** [comment]
This is simply a matter of testing. We haven't tested on `aarch64`.
