### ISSUE TITLE
[QST] Identifier "workspace" is undefined

### ISSUE THREAD

**Issue by SpringWave1** [NVIDIA/cutlass#435]
**identifier "workspace" is undefined**
Hi, i encountered a problem that suggests `identifier "workspace" is undefined`, here is my code
```    
size_t workspace_size = Conv2dFpropInt8::get_workspace_size(arguments);
cutlass::device_memory::allocation<uint8_t> workspace(workspace_size);
```

It also suggests `error: name followed by "::" must be a class or namespace name`
What i am quite confused about is that i have exactly the same code pieces with another executable code. I am pretty wonder about what might i have missed in this part.

**Comment by hwu36** [comment]
You can try to explicitly include some header files.

**Comment by SpringWave1** [comment]
> You can try to explicitly include some header files.

I try to include a header file to explicitly includes cutlass but failed. But i got the workspace created by allocating the output tensor using the torch api :) 
`auto workspace = torch::empty({static_cast<int64_t>(workspace_size)}, torch::dtype(torch::kUInt8).device(torch::kCUDA, 0));`

**Comment by mnicely** [comment]
@SpringWave1 Has your issue been resolved?

**Comment by SpringWave1** [comment]
> @SpringWave1 Has your issue been resolved?

yes, i will close the question.
