### ISSUE TITLE
[QST] perf for ./examples/13_two_tensor_op_fusion/13_fused_two_convs  

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#438]
I am test 2 conv fused perf, why in 13_two_tensor_op_fusion this case, fused conv run slow than no-fused conv, maybe this is just a example to show how to fused two gemm, as for performance, it may need fine-tuning again?
![image](https://user-images.githubusercontent.com/19748572/159403834-b563aef0-f785-4439-86b6-9f86aee07527.png)

**Comment by hwu36** [comment]
Add @jwang323

What version of compiler do you use and have you changed the problem size in the example?

**Comment by hwu36** [comment]
What we got with 11.4 compiler

```
 ./examples/13_two_tensor_op_fusion/13_fused_two_convs
Running on SM75
Running Non-fused back-to-back FP16 Optimized Convolution Fprops...
conv2d 0 time 2.36789 ms
conv2d 1 time 1.48476 ms
total time 3.85265 ms
Pass
Running Fused back-to-back FP16 Optimized Convolution Fprops with shared memory staging...
time 3.58631 ms
```

**Comment by lw921014** [comment]
> Add @jwang323
> 
> What version of compiler do you use and have you changed the problem size in the example?

I use cuda 11.1 and run on T4 with driver version 460. I didnt change the problem size.

> What we got with 11.4 compiler
> 
> ```
>  ./examples/13_two_tensor_op_fusion/13_fused_two_convs
> Running on SM75
> Running Non-fused back-to-back FP16 Optimized Convolution Fprops...
> conv2d 0 time 2.36789 ms
> conv2d 1 time 1.48476 ms
> total time 3.85265 ms
> Pass
> Running Fused back-to-back FP16 Optimized Convolution Fprops with shared memory staging...
> time 3.58631 ms
> ```

![image](https://user-images.githubusercontent.com/19748572/159613154-61f3f476-0c22-4b21-b186-e010ee47df45.png)
I change my cuda into 11.5, but the resutl did meet what I expected. Would you please show your env and run config?

**Comment by hwu36** [comment]
Does `CMAKE_CUDA_COMPILER` in `CMakeCache.txt` point to your 11.5 compiler?

**Comment by hwu36** [comment]
Here is the minimum compiler version you need for different types of kernels

11.3 Tensor Core GEMM
11.4 Tensor Core Conv
11.5 Sparse GEMM
11.6 TF32x3

**Comment by lw921014** [comment]
> Does `CMAKE_CUDA_COMPILER` in `CMakeCache.txt` point to your 11.5 compiler?

![image](https://user-images.githubusercontent.com/19748572/159634686-4e3c1dec-b9ff-4c70-a640-d4821aaa41ff.png)
![image](https://user-images.githubusercontent.com/19748572/159635595-194f9047-10e4-460a-8c18-bf30121204aa.png)
I check my env and compile and rerun, the result can not meet my expection. Do your test run in T4?

**Comment by lw921014** [comment]
> We ran on T4, too. Your number is significantly slower than mine no matter it is fused or not. Do you lock the frequency?

![image](https://user-images.githubusercontent.com/19748572/159833362-d7c54df1-a7e9-44ac-b6f9-aca99862a5e0.png)
I use this cmd to lock my freq in my container, Does it works?

**Comment by hwu36** [comment]
Before you lock the frequency, you need to first set GPU to the persistent mode by using

```
sudo nvidia-smi -i 0 -pm 1
sudo nvidia-smi -lgc xxx -i 0
```

I noticed you locked to T4 peak frequency.  Higher frequency means higher power usage.  When GPU hit power throttle, it will lower the frequency automatically.  T4 has very low power budget so that it is very easy to hit the power throttle.

Maybe you can try to lock at a much lower frequency or do not lock at all.  We didn't lock when we got our number.

**Comment by lw921014** [comment]
> 

Thanks a lot. I update my driver version as from 460 to 470 and then the result aliagn with your's.

**Comment by hwu36** [comment]
Awesome.  Honestly, I don't know that driver can impact the kernel performance that much.

**Comment by lw921014** [comment]
> Awesome. Honestly, I don't know that driver can impact the kernel performance that much.

To be honest, I am shaked by this result. Maybe there are other factor I ignored. If possible, I will double check it, maybe you can also help me verify it if you have free time. Whatever, Thanks a lot, and in recent days, my focus is still on cutlass to obain peek perf. We may keep contact in the future. 
Thanks a lot again.
