### ISSUE TITLE
[QST] HostTensor with page-locked memory

### ISSUE THREAD

**Issue by ttpssabc** [NVIDIA/cutlass#439]
Hi!
Is it possible to create a HostTensor with page-locked host memory like what cudaMallocHost() does?

**Comment by hwu36** [comment]
You can add this functionality by yourself.  The allocation is happened [here](https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/device_memory.h#L49).

Note, `HostTensor` is easier to use and debug. If you want to use it in the production, you may want to manage the memory yourself. CUTLASS kernels only need a device pointer and stride(s) of a matrix/tensor.
