### ISSUE TITLE
[QST] About example 12_gemm_bias_relu

### ISSUE THREAD

**Issue by Exusial** [NVIDIA/cutlass#443]
I tried to compile example 12_gemm_bias_relu with my own makefile (which simply adds the include paths to cutlass header files). That passed compilation but got Runtime Error in running. Then I built the whole cutlass with "cmake .. -DCUTLASS_NVCC_ARCHS=86 && make" everything went alright. What are the differences between these two ways of compilation? My env is RTX 3090 + CUDA 11.

The error reports are as below:
~~~
void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4]: block: [15,3,0], thread: [127,0,0] Assertion `0 && __PRETTY_FUNCTION__` failed.
~~~
Thanks for your help!

**Comment by hwu36** [comment]
you need to specify sm86 in your makefile.

BTW, you need CUDA 11.3 to get good GEMM performance.

**Comment by Exusial** [comment]
Well, thanks for your reply. My makefile is as below(I try to directly compile this .cu example file.)
~~~
/usr/local/cuda/bin/nvcc -I/cutlass/include -I/cutlass/tools/util/include -I/cutlass/examples/common gemm_bias_relu.cu -DCUTLASS_NVCC_ARCHS=86 -o test
~~~
I added that flag to this Makefile and it still reports that Runtime error when running. So what has changed with the flag set on? The source example code should be the same.

**Comment by hwu36** [comment]
you need `-gencode=arch=compute_86,code=sm_86`

**Comment by Exusial** [comment]
That works like magic! Thanks. One more question is about the note in this example file:
~~~
Note this example only works for ColumnMajor output.
~~~
But I changed the layout to RowMajor and it can still pass the reference test. So I'm a little confused of that notes.

**Comment by hwu36** [comment]
You are correct.  The precise way to describe the restriction is that

If the output is column major, the bias has to be per row. i.e. every row has different bias.

If the output is row major, the bias has to be per column, i.e. every column has different bias.

Would you please file a PR to correct it?

**Comment by Exusial** [comment]
OK, I will add your new description to this example.

**Comment by Exusial** [comment]
@hwu36 I'm now trying to remove the bias part of GEMM. But when I set the bias arguments {tensor_c_bias, 0} to NULL in the construction of arguments,  the compiler said "there is no instance of constructor",  how should i fix this?

**Comment by hwu36** [comment]
`{tensor_c_bias, 0}` is a `TensorRef`, not a pointer.  You needs to do `{nullptr, 0}`.
