### ISSUE TITLE
[QST] the backward of GEMM+ReLU epilogue

### ISSUE THREAD

**Issue by Exusial** [NVIDIA/cutlass#445]
Hello, I'm trying to implement the backward of cutlass's fusion of GEMM + ReLU in example 12. The backward requires masking the gradients with the result of the forward phase. So does cutlass have a fusion that can finish the mask + GEMM in a single call like the GEMM+ReLU epilogue in the backward phase? Thanks!

**Comment by hwu36** [comment]
This one? include/cutlass/epilogue/thread/linear_combination_drelu.h

**Comment by Exusial** [comment]
that looks like it! Thank you, I'll give it a try.

**Comment by Exusial** [comment]
I tried but the results are not correct. The LinearCombinationDRelu epilogue requires an additional tensor as the mask tensor for ReLU backward. So I have to provide its TensorRef in the Arguments of the GEMM instance. But where should I put the ref? The arguments contain 4 refs, the first and second are sources, should I provide the mask tensor here?

**Comment by hwu36** [comment]
See this test for example

https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_with_reduction_f16n_f16n_f16n_tensorop_f32_sm75.cu#L115-L157

**Comment by Exusial** [comment]
I checked that example. But it was with reduction. I check the argument struct defined in cutlass/gemm/device/gemm.h, it only allows 4 tensor_ref inputs. But in 

https://github.com/NVIDIA/cutlass/blob/1ac4559d125042d577792c6cb933dd2fbb01a1a9/test/unit/gemm/device/testbed_gemm_with_reduction.h

it contains 7 inputs for tensor_Ref. So if I just want to implement a normal GEMM backward, should I change the GEMM? Thanks
