### ISSUE TITLE
[FEA] FP8 GEMM implementation

### ISSUE THREAD

**Issue by jianyuh** [NVIDIA/cutlass#448]
**Is your feature request related to a problem? Please describe.**
Recently more details about Nvidia's latest H100 GPU are released in https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/ . Tensor Core will support FP8 E4M3 and E5M2 format. Wonder if CUTLASS is going to provide the FP8 GEMM implementation soon.

**Describe the solution you'd like**
Ideally we want FP8 GEMM implementation with FP16/FP32 accumulate for both E4M3 and E5M2 format.

**Describe alternatives you've considered**
This is new feature on new Nvidia hardware.

**Additional context**
None.

**Comment by hwu36** [comment]
Yes, after the toolkit supports it.

**Comment by mnicely** [comment]
@jianyuh is your interest in dense, sparse, or both?

**Comment by jianyuh** [comment]
@mnicely Thanks for checking. We are mostly interested in dense for the 1st step.
