### ISSUE TITLE
includes for coord.h platform.h

### ISSUE THREAD

**Issue by AaronRocinante** [NVIDIA/cutlass#45]
Hi! I added cutlass as a git submodule of a bigger repository. When trying to include the gemm.h header file, the following error occurred:
```               
In file included from /home/aaron/seagate/saber-cpp/cutlass/cutlass/coord.h:32:0,  
from /home/aaron/seagate/saber-cpp/cutlass/cutlass/gemm/gemm.h:34,
from /home/aaron/seagate/saber-cpp/src/matmul.cu:82,
from /home/aaron/seagate/saber-cpp/src/main.cc:6:
/home/aaron/seagate/saber-cpp/cutlass/cutlass/util/platform.h:601:21: error: ‘int4’ was not declared in this scope
 struct alignment_of<int4> {
```

I looks like coord.h only includes platform.h which does not include the vector_types.h from cuda. 

May I know if I'm missing something? Thanks.

**Comment by serach24** [comment]
Hi, I met this exact problem. May I ask if you solved it and how? Thanks.

**Comment by hwu36** [comment]
does it happen when you compile for the host code?  `int4` is supposed to be used in the device code
