### ISSUE TITLE
2 conv fused requirents[QST]

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#455]
For 2 conv fused, I see one [condition](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/b2b_conv2d_run.h#L558) for fused is p1.r == p1.s . It is very strict.
I want to know whether fussion can only be impleted only when the 2nd filter is 1X1？If true, please show me some reason and would it be possible for any size (not only 1X1) to fused in this case(two conv fused)?

**Comment by hwu36** [comment]
> I want to know whether fussion can only be impleted only when the 2nd filter is 1X1

If the 2nd conv filter size is bigger than 1x1,  each threadblock of the 2nd conv needs to fetch the 1st conv results from neighboring threadblocks.  There is no easy way for two threadblocks to communicate.
