### ISSUE TITLE
[QST] the overhead of element-wise fusion in the prologue

### ISSUE THREAD

**Issue by yzhaiustc** [NVIDIA/cutlass#458]
We observe that fusing element-wise computations in the prologue can lead to non-trivial overhead.
From the intuitive perspective, doing fused element-wise computations when the matrix elements are held in registers seems to be not so costly. However, it brings a ~40% perf ovhd to the non-fused baseline in practice.

May I know how we should understand this slowdown? Any comments / corrections are welcome. 
Thanks a lot for your time!

**===== below is the detailed perf data =====**
nvcc11.6, tested on A100, test target: [cutlass-example-26](https://github.com/NVIDIA/cutlass/blob/master/examples/26_ampere_wgrad_mainloop_fusion/ampere_wgrad_mainloop_fusion.cu)

cmd: `./26_ampere_wgrad_mainloop_fusion --benchmark --perf-check`

Referring the non-modified version that can pass the unit test (of course it can) as the **fused-version**.
Contrarily, we commented out the scalar/bias [iterator](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_wgrad_fusion_multistage.h#L475), which is to be fused for element-wise comp with matrix B, and refer it as the **non-fused-version** to visualize the prologue fusion overhead.

Here is detailed comparison. There should be [2x22=44 groups](https://github.com/NVIDIA/cutlass/blob/master/examples/26_ampere_wgrad_mainloop_fusion/ampere_wgrad_mainloop_fusion.cu#L686-#L713) of test data in total. I trimmed some of them since it's too long. As can be seen in the table, element-wise fusion in the prologue leads to ~40% perf ovhd.

</head>
<body>

GFLOPS |   | 1-fused/non-fused
-- | -- | --
non-fused | fused | loss or ovhd
1944.34 | 1109.06 | 0.429596
1952.99 | 1112.07 | 0.430581
500.029 | 275.901 | 0.44823
495.67 | 278.038 | 0.439066
4428.46 | 2461.33 | 0.444202
4444.54 | 2467.9 | 0.444734
1967.52 | 1106.42 | 0.437658
1976.29 | 1107.61 | 0.439551
15161.8 | 8706.31 | 0.425773
15419.9 | 8787.07 | 0.430147
3892 | 2209.74 | 0.432235
3910.36 | 2215.5 | 0.433428
17267.3 | 9693.21 | 0.438638
17574.4 | 9770.87 | 0.444028
7587.87 | 4393.9 | 0.420931
7717.04 | 4444.98 | 0.424005
7630.08 | 4386.37 | 0.425121
7761.78 | 4436.91 | 0.428364
17248.9 | 9646.6 | 0.440741
17530.7 | 9759.49 | 0.443291
...

</body>
</html>

**Comment by hwu36** [comment]
Mainloop fusion will lower the performance which is expected.  The recent compiler uses more registers than before and now the fused kernel spills.  Spilling usually can lower the performance by a lot.

I am thinking of using single buffer in the mainloop to reduce the register usage.

**Comment by hwu36** [comment]
And you are looking at wgrad kernel.  wgrad usually needs splitk to get good performance.

**Comment by yzhaiustc** [comment]
Thank you so much for the valuable input. 
I’ll have a quick try by using a single / fewer reg buffer to address the spilling issue.

**Comment by yzhaiustc** [comment]
Thank you enormously for sharing the insightful suggestions! I shall mark it in mind when practicing.
