### ISSUE TITLE
[QST] Misaligned address

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#459]
I meet same question as this [issue](https://github.com/NVIDIA/cutlass/issues/49) in this case https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/b2b_gemm_f16t_f16n_f16t_tensor_op_f16_sm75.h#L44. 
I see this [issue](https://github.com/NVIDIA/cutlass/issues/49) that this problem has beem solved after 2.0. however I test when m=1, it run ok, but when set k as odd, it face same problem as Misaligned address. Would you please show me some reseans?

**Comment by hwu36** [comment]
We support small alignment in tensor core kernels.  You can use align1 for `m=1` problem sizes depends on your data types and hardware.

Also, `can_implement()` in cutlass requires M/N/K are all multiple of the alignment.  This is too restrictive.  We will relax it in the coming 2.9 so that only the leading dimension needs to be the multiple of the alignment.

**Comment by lw921014** [comment]
> We support small alignment in tensor core kernels. You can use align1 for `m=1` problem sizes depends on your data types and hardware.

The hardware is T4 and data types is half_t and also use tensorcore as configured in [this case ](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/b2b_gemm_f16t_f16n_f16t_tensor_op_f16_sm75.h#L49). For this case, how can we use aligh1, I mean which parameter do we need to change to impl align1?  Further step, if m, k, and n are all odd, (e.g. m = 1, k = 705, n =705), do current code support it when set align1?



> Also, `can_implement()` in cutlass requires M/N/K are all multiple of the alignment. This is too restrictive. We will relax it in the coming 2.9 so that only the leading dimension needs to be the multiple of the alignment.
For `can_implement()` requirenment, I also have some question.
1. Do `can_implement()` mean [this code]( https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/kernel/b2b_gemm.h#L195)
`    if ((problem_size_0.m() % kAlignmentA) || (problem_size_0.k() % kAlignmentA) ||
      (problem_size_0.n() % kAlignmentB) || (problem_size_0.k() % kAlignmentB) ||
      (problem_size_0.m() % kAlignmentC) || (problem_size_0.n() % kAlignmentC) ||
      (problem_size_1.m() % kAlignmentA) || (problem_size_1.k() % kAlignmentA) ||
      (problem_size_1.n() % kAlignmentB) || (problem_size_1.k() % kAlignmentB) ||
      (problem_size_1.m() % kAlignmentC) || (problem_size_1.n() % kAlignmentC)) {

      return Status::kErrorMisalignedOperand;
    }`
2. if true, I find when run fused gemm, `can_implement()` is skiped (I think this should do after [initialize](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/b2b_gemm_run.h#L224), but did not). I want know why?
3. As for new release 2.9, I want to know the exact date for release? (The interval time between 2.7 and 2.8 is three monthes, that mean 2.9 will be released in recent days)

**Comment by hwu36** [comment]
> For this case, how can we use aligh1, I mean which parameter do we need to change to impl align1?

Alignment `A` and  `B` are here if you use `device::gemm`: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm.h#L204-L210 .  Alignment `C` is here : https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination.h#L52 

> Further step, if m, k, and n are all odd, (e.g. m = 1, k = 705, n =705), do current code support it when set align1?

If you set all alignments to 1, you can run the problem size that is all odd numbers.  The performance will be bad.  Padding to better alignment maybe worthwhile.

> Do can_implement() mean [this code](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/kernel/b2b_gemm.h#L195)

Correct.  It can be relaxed to something like

```
    bool isAMisaligned = false;
    bool isBMisaligned = false;
    bool isCMisaligned = false;

    if (platform::is_same<LayoutA, layout::RowMajor>::value) {
      isAMisaligned = problem_size.k() % kAlignmentA;
    } else if (platform::is_same<LayoutA, layout::ColumnMajor>::value) {
      isAMisaligned = problem_size.m() % kAlignmentA;
    } else if (platform::is_same<LayoutA, layout::ColumnMajorInterleaved<32>>::value
            || platform::is_same<LayoutA, layout::ColumnMajorInterleaved<64>>::value) {
      isAMisaligned = problem_size.k() % kAlignmentA;
    }

    if (platform::is_same<LayoutB, layout::RowMajor>::value) {
      isBMisaligned = problem_size.n() % kAlignmentB;
    } else if (platform::is_same<LayoutB, layout::ColumnMajor>::value) {
      isBMisaligned = problem_size.k() % kAlignmentB;
    } else if (platform::is_same<LayoutB, layout::RowMajorInterleaved<32>>::value
            || platform::is_same<LayoutB, layout::RowMajorInterleaved<64>>::value) {
      isBMisaligned = problem_size.k() % kAlignmentB;
    }

    if (platform::is_same<LayoutC, layout::RowMajor>::value) {
      isCMisaligned = problem_size.n() % kAlignmentC;
    } else if (platform::is_same<LayoutC, layout::ColumnMajor>::value) {
      isCMisaligned = problem_size.m() % kAlignmentC;
    } else if (platform::is_same<LayoutC, layout::ColumnMajorInterleaved<32>>::value
            || platform::is_same<LayoutC, layout::ColumnMajorInterleaved<64>>::value) {
      isCMisaligned = problem_size.n() % kAlignmentC;
    }

    if (isAMisaligned) {
      CUTLASS_TRACE_HOST("  returning kErrorMisalignedOperand for A operand");
      return Status::kErrorMisalignedOperand;
    }

    if (isBMisaligned) {
      CUTLASS_TRACE_HOST("  returning kErrorMisalignedOperand for B operand");
      return Status::kErrorMisalignedOperand;
    }

    if (isCMisaligned) {
      CUTLASS_TRACE_HOST("  returning kErrorMisalignedOperand for C operand");
      return Status::kErrorMisalignedOperand;
    }

    CUTLASS_TRACE_HOST("  returning kSuccess");
```

> if true, I find when run fused gemm, can_implement() is skiped (I think this should do after [initialize](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/b2b_gemm_run.h#L224), but did not). I want know why?

We forget to check it.

> As for new release 2.9, I want to know the exact date for release? 

We are working on the final touch.

**Comment by hwu36** [comment]
FYI, 2.9 is out.

**Comment by lw921014** [comment]
> FYI, 2.9 is out.

Perfect. Thanks a log.

**Comment by wzhao18** [comment]
hi @hwu36, I am trying to run some gemm with odd dimensions. I tried to set alignment to 1 as you suggest, but then, since the type that I use is fp16, I will fail [this statis_assert](https://github.com/NVIDIA/cutlass/blob/f4a021660162510572f90ea715b018cff9c0f12f/include/cutlass/arch/memory_sm80.h#L158). May I ask how I can proceed from there?

**Comment by hwu36** [comment]
sm80 `cp.async` requires at least 32bit data.  yours is 16bit.  you may try turing (sm75) style kernel which does not use `cp.async`.
