### ISSUE TITLE
[FEA] b2b gemm fused for FP32 use simt

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#460]
I seem in 2 [gemm fused case](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/fused_gemm.cu), when use tensor core, 2 fused gemm run faster than non-fused gemms.  In real case, there are still cases that must use FP32, However, we didnt support FP32 so far.
Would it be possible for you to support this feature in future release code? I think it will be a very good idea and has great demand in industry.

**Comment by hwu36** [comment]
The benefits of fusing FP32 GEMMs will be reduced since FP32 is more likely to be compute bound than FP16 or INT8.

If you want fast FP32, you can try TF32x1 or TF32x3 kernels depends on your tradeoff between performance and accuracy.

**Comment by lw921014** [comment]
> The benefits of fusing FP32 GEMMs will be reduced since FP32 is more likely to be compute bound than FP16 or INT8.

Ok, thanks a lot.  Do we have such demo code for FP32 or conduct such real experiment before？



> If you want fast FP32, you can try TF32x1 or TF32x3 kernels depends on your tradeoff between performance and accuracy.

So I think there is still a lot of demand for FP32 in real industry.On the one hand, althougn, for ampere, we can do this, but for turning or volta, we can not use FP32.  On the other hand, for some case accuracy can not be sacrificed for example in ctr application.

**Comment by hwu36** [comment]
> Do we have such demo code for FP32 or conduct such real experiment before？

No.  B2B fusion works well when both kernels are memory bound.  SIMT FP32 kernel is usually compute bound.  Fusing will more likely hurt the performance because fused kernel has restriction in selecting tile sizes.

> On the one hand, althougn, for ampere, we can do this, but for turning or volta, we can not use FP32.

True, but we are moving away from volta and turing.  It is time for Ampere and Hopper now.

> On the other hand, for some case accuracy can not be sacrificed for example in ctr application.

TF32x3 can have better accuracy than FP32 though not IEEE compatible.

**Comment by lw921014** [comment]
> TF32x3 can have better accuracy than FP32 though not IEEE compatible.
Sorry, what is TF32x3, what is the difference between TF32x3 and TF32?

**Comment by hwu36** [comment]
Check this example https://github.com/NVIDIA/cutlass/tree/master/examples/27_ampere_3xtf32_fast_accurate_tensorop_gemm

**Comment by lw921014** [comment]
> Check this example https://github.com/NVIDIA/cutlass/tree/master/examples/27_ampere_3xtf32_fast_accurate_tensorop_gemm

ok，thanks a lot
