### ISSUE TITLE
[QST] Request useful script shown in GTC

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#462]
I see in [discution](https://github.com/NVIDIA/cutlass/discussions/427)  about GTC talk (S41606), you have developed a usefully code-gen script, However I did not find it in repo. Would you please tell where I can get it?
![image](https://user-images.githubusercontent.com/19748572/163553707-f609c109-a971-4049-9987-77c5a80b5cd8.png)

**Comment by lw921014** [comment]
> It will be in 2.9

Hi, 2.9 has been released. However, I didnot see this useful script. Would you please tell me where it is?

**Comment by lw921014** [comment]
> It is not ready yet. we will add it as a patch.

Ok. Do we have some expected release date? We need it.

**Comment by lw921014** [comment]
> It is not ready yet. we will add it as a patch.

@hwu36 I see this scipt that you construct an ir for tf for gemm fusion? I guess you team have cooperationship  with tf team?

**Comment by lw921014** [comment]
> > It is not ready yet. we will add it as a patch.
> 
> Ok. Do we have some expected release date? We need it.

@hwu36 we need it in our project. If we can use you prefered work, we can avoid repeated work and reduce more time. Thanks a lot. If needed, we can launch a cooperated project to do it.

**Comment by mnicely** [comment]
Added to 2.11
