### ISSUE TITLE
[QST] Demo on fuse 2 GEMMs with Split K?

### ISSUE THREAD

**Issue by void-main** [NVIDIA/cutlass#463]
**What is your question?**
According to the GTC talk, there's a more general fuse 2 gemm approach that could handle large N (over 512). Could you please share a demo on this approach?

**Comment by hwu36** [comment]
You mean the one mentioned in the 2nd half of this talk "Use CUTLASS to Fuse Multiple GEMMs to Extreme Performance"?

**Comment by void-main** [comment]
@hwu36 yep. Do you guys have any demo on that? 

Also, to me, it's like the Split-K method is a more general approach, does that mean its performance couldn't match the RF-based one? Do you have any guidelines on which method should we choose? Thanks.

**Comment by hwu36** [comment]
We can consider releasing it in the future.  Meanwhile, if you are a business client, you can ask this to your NVIDIA contact.

**Comment by void-main** [comment]
@hwu36 got it, thanks!
