### ISSUE TITLE
[BUG] The base class TensorOpMultiplicand has no inverse() method.

### ISSUE THREAD

**Issue by dxyzab** [NVIDIA/cutlass#464]
In [cutlass](https://github.com/NVIDIA/cutlass/tree/master/include/cutlass)/[layout](https://github.com/NVIDIA/cutlass/tree/master/include/cutlass/layout)/tensor_op_multiplicand_sm75.h

The base class TensorOpMultiplicand has no inverse() method.

The subclasses such as RowMajorTensorOpMultiplicandCrosswise have an inverse() method:

  /// Inverse of layout function, mapping linear offset to logical coordinate
  CUTLASS_HOST_DEVICE
  TensorCoord inverse(LongIndex offset) const {
    PitchLinearCoord coord = layout_.inverse(offset);
    return MatrixCoord(coord.strided(), coord.contiguous());
  }

**Steps/Code to reproduce bug**
Code will not compile if there is a call to inverse method of an instance of RowMajorTensorOpMultiplicandCrosswise as it attempts to use the non existent method of the base class.

**Expected behavior**
Code will not compile.

**Environment details (please complete the following information):**
 - Any

**Additional context**

**Comment by dxyzab** [comment]
Is (offset / stride_[0] * kFactor, offset % stride_[0] * kFactor) correct for the inverse?

**Comment by hwu36** [comment]
`inverse()` is TODO.  Do you have a use case that you need it?

> Is (offset / stride_[0] * kFactor, offset % stride_[0] * kFactor) correct for the inverse?

I dont think it is correct.  When we map coord->offset, we use `xor` (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor_op_multiplicand_sm75.h#L1016).  When we do offset->coord, I think we need `xor` again.
