### ISSUE TITLE
[QST] Write the intermediate accumulator tile from the 1st GEMM in 13_two_tensor_op_fusion to shared memory

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#465]
([code](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/threadblock/b2b_mma_pipelined.h))
Is it a good idea to write the intermediate accumulator tile from the 1st GEMM in 13_two_tensor_op_fusion to shared memory when the first GEMM's N dimension is large (say 256, the example uses 64)? The code needs to read B1 (the 2nd GEMM) from global memory and write to shared memory anyway. So it seems not too bad to add another shared memory read/write to achieve more warp level parallelism in the first and 2nd GEMM?

**Comment by hwu36** [comment]
Correct. This feature will be included in the coming 2.9

**Comment by peisun1115** [comment]
This sounds awesome! Any timeline for 2.9 release (days?, weeks? months?)

**Comment by hwu36** [comment]
Days

**Comment by peisun1115** [comment]
Looking forward! Thanks

**Comment by hwu36** [comment]
2.9 is out :)

**Comment by peisun1115** [comment]
Thank you! That looks great! I also checked the [presentation](https://www.nvidia.com/en-us/on-demand/session/gtcspring22-s41606/) which is quite useful.

I will try it on my own. there is one thing i do not understand from the presentation: why is the performance of writing to shmem usually worse than the version of using spinlock to split K in the 2nd GEMM? Intuitively, as long as we setup Mtile in the first gemm to be small enough, the additional load on shared memory is ok? (i should just try it and profile it but i think if you have some explanation, that can save me a lot of time. )

**Comment by lb1244206405** [comment]
> why is the performance of writing to shmem usually worse than the version of using spinlock to split K in the 2nd GEMM?
Do you mean these atomic implementations? The comparsion is a little bit unfair, since the spinlock reuse the output buffer and the atomic impls use another workspace. And in the presentation, we do have a "fair" comparsion which do the atomic operations in the same output buffer.
