### ISSUE TITLE
[QST] Why tensorop works for fp32 * fp32 -> fp32 gemm

### ISSUE THREAD

**Issue by chrysantd** [NVIDIA/cutlass#466]
Hi, I build cutlass on RTX 2080 Ti with cuda 11.1 successfully. And when I test example 12_gemm_bias_relu which uses tensorop, I modify the ElementInputA and ElementInputB to float type, (and also the dimension size of input matrices), and it works. 

Furthermore, I measure the time the gemm kernel costs. The results show that it only takes about 4 ms to execute the gemm kernel. And when I use cutlass_profiler to test sgemm which uses simt, it takes about 6ms to execute the gemm kernel. I also compare the performance of cublasgemmex for fp32 * fp32 -> fp32,  the time cost is also about 6ms.

The dimension size I used in all experiments is m=2097152, n=128, k=128

I am confused with the results and have two questions. 

1. As far as I know, tensorop does not support fp32 * fp32 -> fp32, so why I can build and run example 12_gemm_bias_relu successfully after changing types?
2. Why does the performance becomes better?

I am new to GPU programming and cutlass, so if there are any mistakes in my questions, please correct me.

**Comment by hwu36** [comment]
> As far as I know, tensorop does not support fp32 * fp32 -> fp32, so why I can build and run example 12_gemm_bias_relu successfully after changing types?

If you have `OpClassTensorOp` when you instantiate your top level templates, CUTLASS will use TF32 tensor core for FP32 input.  CUTLASS will internally convert fp32 into tf32 before calling the tensor core instructions.  It is much faster than SIMT version true FP32 gemm.

If you are not happy with TF32 accuracy and you think true FP32 is too slow, you can use CUTLASS TF32x3 kernel.  Please check https://github.com/NVIDIA/cutlass/tree/master/examples/27_ampere_3xtf32_fast_accurate_tensorop_gemm

Moreover, we codesign cutlass with nvcc team.  To get the best performance, you need to use at least following CUDA version to compile different type of CUTLASS kernels.

11.3 tensor core GEMM
11.4 tensor core CONV
11.5 sparse tensor core GEMM
11.6 tf32x3 GEMM/CONV
