### ISSUE TITLE
Any material to help to understand the xor operation in the layout?

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#470]
I found it hard to comprehend [these pieces of code](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor_op_multiplicand_sm75.h#L182-L186). On a high level, i think it is to resolve bank conflicts. I am wondering how they are designed? Any paper or doc to describe it? How do people usually comprehend these?

Thanks!

**Comment by hwu36** [comment]
xor is used to prevent the bank conflict during shared memory load.  Our previous GTC talks explained the shared memory layout.  Just search cutlass in GTC website.  This example (https://github.com/NVIDIA/cutlass/tree/master/examples/03_visualize_layout) can help you visualize the layout.

If you can read Chinese, you can search cutlass in zhihu.com.  There are some great 3rd party articles explaining the details of cutlass.

**Comment by peisun1115** [comment]
Thanks!
