### ISSUE TITLE
[QST] Permuting input for storage to fragments / shmem in warp GEMM?

### ISSUE THREAD

**Issue by VasuAgrawal** [NVIDIA/cutlass#481]
I'm just getting started with using CUTLASS, so apologies in advance if this is a dumb question.

I'm writing a kernel where each thread is independently generating a small (16 wide) feature vector, and then needs to pass it through an MLP. I want to do this at a warp level (rather than at a thread block level) for now. Looking at the [Gemm API](https://github.com/NVIDIA/cutlass/blob/master/media/docs/gemm_api.md#warp-level-matrix-multiply-api) for warp-level matrix-matrix multiply, I see that:

> The input to a warp-level GEMM operation in CUTLASS must be data in shared memory loaded by iterators or on register-backed fragments.

At the moment, each thread is storing its feature vectors in a strided shared memory buffer (strided by the size of the largest activation in the MLP). However, I don't think this is compatible with CUTLASS? Looking at the [functionality doc](https://github.com/NVIDIA/cutlass/blob/master/media/docs/functionality.md#warp-level-matrix-multiply-with-tensor-cores), I see that:

> TensorOp instructions depend on a permuted shared memory layout that can be efficiently loaded from. 

Is there any example code on how I can put the vectors from each thread into shared memory in the right permuted layout? Alternatively, is it possible to use e.g. warp shuffle operations to directly populate fragments, rather than needing to indirect through shared memory at all?

**Comment by hwu36** [comment]
Do you want to store your data into shared memory and then load it back to do a warp level gemm?  If so, you need to write your own shared memory store function/iterator.

You can take a look at cutlass warp gemm unit tests to get some ideas (https://github.com/NVIDIA/cutlass/tree/master/test/unit/gemm/warp).  We also has a tool (https://github.com/NVIDIA/cutlass/tree/master/examples/03_visualize_layout) to help you visualize the shared memory layout.

In the high level you can consider the shared memory layout as (row ^ col).  Row and col are the coordinates in the shared memory before the permutation.  Our previous GTC talk also explained it.
