### ISSUE TITLE
[QST] about mma arch

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#484]
I have a question, for [mma](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma.h),  I only see declaration of OpMultiplyAdd, OpMultiplyAddSaturate, OpMultiplyAddFastBF16 and so on, however I didnot see any implementation，why？

**Comment by lw921014** [comment]
> I have a question, for [mma](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma.h), I only see declaration of OpMultiplyAdd, OpMultiplyAddSaturate, OpMultiplyAddFastBF16 and so on, however I didnot see any implementation，why？

This struct only used as a tag or just like enum type like following?
enum mmatype {
OpMultiplyAdd,
OpMultiplyAddSaturate,
OpMultiplyAddFastF16,
....
}

**Comment by hwu36** [comment]
They are tags used when instantiating templates.
