### ISSUE TITLE
[BUG] Error encountered in fast_math.h

### ISSUE THREAD

**Issue by SpringWave1** [NVIDIA/cutlass#485]
**Describe the bug**
When i compiled with the latest cutlass, a bug
`cutlass/include/cutlass/fast_math.h(723): error: no suitable conversion function from "__half" to "float" exists` Appeared.

**Steps/Code to reproduce bug**
Compiled cutlass using the python setup?

When I commented the code block mentioned  above, everything else works well.

**Comment by hwu36** [comment]
Thanks for the reporting.  I would need more information to reproduce.

Which program are you building?  What is your compiler version?

What is your cmake and make command line?

**Comment by SpringWave1** [comment]
> Thanks for the reporting. I would need more information to reproduce.
> 
> Which program are you building? What is your compiler version?
> 
> What is your cmake and make command line?

I actually compiled the cutlass with torch cpp extension (nvcc). And here is the compilation code:
```
/usr/local/cuda/bin/nvcc  -I/pytorch/cutlass/include -I/pytorch/cutlass/util/include -I/opt/conda/lib/python3.7/site-packages/torch/include -I/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.7/site-packages/torch/include/TH -I/opt/conda/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.7m -c -c /tmp/pip-req-build-v08we8vy/cutlassconv_kernel.cu -o /tmp/pip-req-build-v08we8vy/build/temp.linux-x86_64-3.7/cutlassconv_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cutlassconv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
```

**Comment by hwu36** [comment]
Yeah, you have lots of `-Dxxx` that do not belong to cutlass.  They may cause unexpected problem.

**Comment by SpringWave1** [comment]
> Yeah, you have lots of `-Dxxx` that do not belong to cutlass. They may cause unexpected problem.

Ok, i will close the issue.

**Comment by SpringWave1** [comment]
> Hi @SpringWave1,
> 
> Have you solve this problem? I face the same problem. What do you need to configure for the pytorch extension?
> 
> thanks a lot! kaixin

I comment this part in source code.

**Comment by Akimoto-Cris** [comment]
Yeah, this can leads to unexpected behaviors. Hope pytorch or cutlass can provide a cleaner solution.
