### ISSUE TITLE
some questions about async copy

### ISSUE THREAD

**Issue by mengchihe** [NVIDIA/cutlass#490]
Hi:

I use cutlass to run some batchGemm op, and find some gap between cutlass/cublas on some cases.
<img width="1115" alt="截屏2022-05-10 下午8 03 01" src="https://user-images.githubusercontent.com/40778923/167624061-e867528f-4a7c-458c-9daf-4fd6513320ea.png">
I did some profiling and find out that maybe the difference is caused by data loading. As in the image above, current is cublas and baseline is cutlass. The difference is that all input data goes from L2 to shared memory in cutlass, but in cublas, there are 975MB data goes from L2 to L1 cache.
<img width="1286" alt="截屏2022-05-10 下午8 07 42" src="https://user-images.githubusercontent.com/40778923/167624835-d939e10f-75b7-40de-b75c-c42e285b78c4.png">
In this image we can see that cutlass/cublas have same async copy instructions(5488640), but the instruction arrive L1 is fewer in cublas(4743168), and the request is also identical.

I find out that both cutlass/cublas use LDGSTS.BYPASS.LTC128B.128 to load data, so I just want to know what cause the difference above, is there another version of async copy, and is this the reason of the performance variance. Thanks.

**Comment by hwu36** [comment]
`BYPASS` means it will bypass L1.

What is the kernel name of cublas kernel?  nsight should tell you.

**Comment by hwu36** [comment]
> seems cublas also call a cutlass kernel? 
correct.

cublas uses a 4 stage 256x64x16 kernel. what do you use?

I can tell that you are using tf32.  It works best if the layout is TN.

**Comment by mengchihe** [comment]
> > seems cublas also call a cutlass kernel?
> > correct.
> 
> cublas uses a 4 stage 256x64x16 kernel. what do you use?
> 
> I can tell that you are using tf32. It works best if the layout is TN.

This case is NN, but TN also have the similar appearance. I set block/warp shape and stage identical to cublas, some case will have the same performance, but still gaps on some case. All the result in nsight are similar, the only difference is that cutlass has far more LOP3(Logic Operation) and twice ISETP(Integer Compare and Set Predicate) than cublas, and cublas has some data go to L1. SO I wonder which of this difference cause the 15% gap, and why these data goes to L1 since I didn't find cublas use any prefetch instruction. Thanks

**Comment by hwu36** [comment]
> cutlass has far more LOP3(Logic Operation) and twice ISETP(Integer Compare and Set Predicate) than cublas,

This could be the reason.  Mainloop can be bloated.  What is your compiler version?

**Comment by mengchihe** [comment]
> > cutlass has far more LOP3(Logic Operation) and twice ISETP(Integer Compare and Set Predicate) than cublas,
> 
> This could be the reason. Mainloop can be bloated. What is your compiler version?

I compiled in nvcr.io/nvidia/pytorch:22.03-py3 docker, which nvcc is 11.6.

But my cutlass code is not latest, I saw that cutlass 2.9 is better with cuda 11.6, I will update my code and try again, thanks a lot.

**Comment by hwu36** [comment]
You can just use cutlass profiler to test the batch gemm performance.  cutlass profiler uses gemm universal (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h), not `GemmBatched`.  

I think the root cause is the NN layout.  cublas can use something that you cannot use.  If possible, try TN layout.

Related, you can also take a look at group gemm (https://github.com/NVIDIA/cutlass/tree/master/examples/24_gemm_grouped).  Group gemm is more general than batch gemm because it does not require all gemms to have the same problem sizes.  You can skip the padding kernel and waste less computing resource.

**Comment by mengchihe** [comment]
> You can just use cutlass profiler to test the batch gemm performance. cutlass profiler uses gemm universal (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h), not `GemmBatched`.
> 
> I think the root cause is the NN layout. cublas can use something that you cannot use. If possible, try TN layout.
> 
> Related, you can also take a look at group gemm (https://github.com/NVIDIA/cutlass/tree/master/examples/24_gemm_grouped). Group gemm is more general than batch gemm because it does not require all gemms to have the same problem sizes. You can skip the padding kernel and waste less computing resource.

I will try this, thank you very much.
