### ISSUE TITLE
[DOC] functionality listing page confusing/insufficient for newbies

### ISSUE THREAD

**Issue by eyalroz** [NVIDIA/cutlass#491]
**Location of incorrect documentation**: The [functionality page](https://github.com/NVIDIA/cutlass/blob/master/media/docs/functionality.md).

**Describe the problems or issues found in the documentation**

People who are not familiar with the library already may not understand some of the abbreviations you use:

* Layout column:
    * 'N' and 'T' abbreviations
    * meaning of set notation regarding layout, i.e. is it "any combination of the items from each set" or "layout involves all items 
in each  set"
   * 'NHWC' and  'NCxHWx' abbreviations
* Opcode column: 'SpTensorOp' vs 'TensorOp' - if this is about precision of the values/registers manipulated, that seems to already be covered by the 'data type' column; and if not - what _does_ that mean?
* data type column:
   * it's not clear whether the numbers are bit sizes or numbers of elements in various axes.
   * Not everyone would know the meaning of 'f', 's', 'b' and 'bf'.

**Steps taken to verify documentation is incorrect**
None?

**Suggested fix for documentation**
* Provide legends for the sets of abbreviations, or links to such legends.
* Provide an explanation of how to read the notations in the layout and data type columns.

**Comment by hwu36** [comment]
`N` `T` `f` `s` `b` `bf` are cublas terminology.  N is column major, T is row major.  `f` is float.  `b` is bit. `s` is singed int.  `bf` is bfloat.

`SpTensorOp` is sparse tensor core which was introduced in ampere.

**Comment by hwu36** [comment]
`NHWC` and `NCxHWx` are cudnn/tensorrt terminology.  Just 4 dimension tensors.

**Comment by eyalroz** [comment]
@hwu36 : Ok, but - it should say that on the functionality page. Not all prospective users know cuBLAS. And I'm not even sure a majority of prospective users know cuDNN. I haven't used any of those, for example - I just need me some convolution primitives.

**Comment by hwu36** [comment]
More explanation is added in the file now. Thanks.
