### ISSUE TITLE
[DOC] Clarify whether 1D convolution functionality is offered

### ISSUE THREAD

**Issue by eyalroz** [NVIDIA/cutlass#494]
**Location of incorrect documentation**: The [functionality page](https://github.com/NVIDIA/cutlass/blob/master/media/docs/functionality.md).

**Describe the problems or issues found in the documentation**
I can't figure whether CUTLASS can help me do 1D, or even 2D, convolution. The table suggests I need to provide some kind of 4D tensor with convolution information - which I don't understand and don't have. Even in the simplest case: I want to convolve 2 1D arrays of the same data type with each other; can I do that with CUTLASS? I can't tell.

**Suggested fix for documentation**
I'm not exactly sure. Perhaps some clarification of what that "4D convolution" input actually means. Perhaps an indication of some things which are _not_ part of the functionality. e.g. "We don't do sparse matrix multiplication" or what-not.

**Comment by mnicely** [comment]
>Even in the simplest case: I want to convolve 2 1D arrays of the same data type with each other; can I do that with CUTLASS? I can't tell.

@eyalroz Something to keep in mind, the intent of CUTLASS is to provide a C++ abstraction to programming Tensor Cores. Performance benefits will come from 2D+ operations
