### ISSUE TITLE
[QST] Divide int32 by power of 2

### ISSUE THREAD

**Issue by nolyn** [NVIDIA/cutlass#496]
Hi. I'm trying to implement a NN, where each layer has input and weights of int8_t and output of int32_t. I want to divide the output of a layer by a power of 2 to get into the int8_t range required for the next layer. I don't want to use intermediate float operations.
How can I do this? I think the question has two aspects:

1. how to do it in cutlass framework
I believe I probably should add an Epilogue class for this. LinearCombinationClamp looks like a good candidate as a basis. And I should replace 
`
NumericArrayConverter<ElementOutput, ElementCompute, kCount, Round> destination_converter;
`
by something that will do my conversion. Or is there a better approach?
2. how to do efficient conversion 
I have to replace this?
```
    static result_type convert(source_type const & s) {

    return static_cast<result_type>(s);
  } 
```
Can I simply write x = x / power_of_2_val and compiler will take care of it? Or I have to implement it myself using tricks like bit shifts etc? Do I have to write implementations for various template specializations, even if I only need one specific one?

Thanks in advance!

**Comment by mnicely** [comment]
According to CUDA Best Practices, you should use bit shifts. 
[11.1.1. Division Modulo Operations](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#division-and-modulo-operations)

**Comment by nolyn** [comment]
Thanks for that link. "The compiler will perform these conversions if n is literal". So I can just write x = x / power_of_2_val and compiler should handle it. There is no mention of signed/unsigned in this. Does it mean, that compiler will use "arithmetic shift" and its safe to right shift negative numbers? In any case if I can just write x = x / power_of_2_val, seems I don't have to care about this detail.

**Comment by mnicely** [comment]
>There is no mention of signed/unsigned in this
That's a good question, and I don't know the answer off top of my head. I'll see what I can find out. In the meantime, you might find [godbolt ](https://godbolt.org/) beneficial for concrete answers to you compiler "what ifs". It allows you to test your ideas and see generated SASS.

**Comment by hwu36** [comment]
The compiler should take care of int div of po2 -> shift optimization whenever it is legal.  If the optimization does not happen, it is a big compiler bug.

You don't need to start from `LinearCombinationClamp`.  This one is needed if the intermediate computation is float which I believe is not your case.

You can just start from `LinearCombination`.  Adding your division either in `destination_converter` or do it explicitly.

**Comment by nolyn** [comment]
> The compiler should take care of "int div of po2 -> shift" optimization whenever it is legal. If the optimization does not happen, it is a big compiler bug.
> 
> You don't need to start from `LinearCombinationClamp`. This one is needed if the intermediate computation is float which I believe is not your case.
> 
> You can just start from `LinearCombination`. Adding your division either in `destination_converter` or do it explicitly.

Thanks for the advice. I did just that. So far it works fine. I just hard coded the value I'm dividing by, but I'll see if I can make it a template argument. 
So my converter is
```
template <
  typename T,
  typename S,
  FloatRoundStyle Round = FloatRoundStyle::round_to_nearest
>
struct NumericConverterRShift {

  using result_type = T;
  using source_type = S;
  static FloatRoundStyle const round_style = Round;

  CUTLASS_HOST_DEVICE
    static result_type convert(source_type const & s) {
    const source_type divisor = (1 << 6 );
    source_type r_shifted = s / divisor;
    return static_cast<result_type>(r_shifted);
  }

  CUTLASS_HOST_DEVICE
    result_type operator()(source_type const &s) {
    return convert(s);
  }
};
```

I don't seem to be needing FloatRoundStyle, I'll try removing it. One thing I noticed is that for shift larger than 6 bits the compiler throws warnings like this
```
[build] ../cutlass/include/cutlass/numeric_conversion.h(638): warning #68-D: integer conversion resulted in a change of sign
[build]           detected during:
```
I can't make sense of this one so far. I'd expect there could be sign change if I do not divide by a large enough number before casting to data type with fewer bits. But this happens when I increase the divisor. 


As a side question, is there an easy way to do something like
```
          cutlass::reference::host::TensorFillRandomUniform(
            a.host_view(),
            1,
            ElementWeight( 1 ),
            ElementWeight( 0 ),
            0
            );
          a = a*255 -  128;
```
I.e. filling randomly with max and min value of the used data type. I think I can use TensorCopy and implement a converter to do this, but maybe there is a better way.

**Comment by hwu36** [comment]
what is your source type of `divisor`?  I think you can just set it as `int32_t` and then your warning would be gone.

You can take a look at it https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/reference/host/tensor_fill.h#L1266-L1298 for you random fill function.

**Comment by nolyn** [comment]
Thanks a lot. Both worked :)
