### ISSUE TITLE
[QST] Should this line be divided by Layout::kFactor?

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#502]
Should [this line](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L616) be divided by Layout::kFactor ? Or it should just use ref.stride(0) (ref from ctor).

stride_ in this class is multiplied by kFactor in line 526 but add_tile_offset is supposed to add an offset based on threadblock tile level

Very likely I am wrong :) but could it be because this code is rarely used as no code needs to set this cord.stride() > 0 ?

**Comment by hwu36** [comment]
I actually thinks you are mostly correct though I am not 100% sure without a unit test to confirm it.  For the `Crosswise` layout, when we move along `K` dimension to compute GEMM, we move along the contiguous dimension.  So coord.stride() is always `0`.

Instead of divide `kFactor`, I think we need to divide `sections_`.  If you are interested, you can make the change and try all the unit tests first.

**Comment by peisun1115** [comment]
Thank you for your response! Why should it be **sections_**? 

Suppose the tensor shape is: pitch linear (128, 64). (c 128, s 64). Threadblock tile is (32, 32). Element = half_t

If i understand correctly,
ref.stride(0) = 128,
Crosswise  = 32,
kFactor = 2,
sections_ = 4,
sections_per_stage_ = 1
Shape::kStrided = 32
kElementsPerAccess = 128 / 16 = 8
stride_ = 128 * 2 / 8 = 32

one strided dim increment should add 
128 * 32 elements?

which is the same as 1 * 32 * 32 *8 = 128 * 32 * **2**

**Comment by hwu36** [comment]
Think it again, now I think you are correct.  In the unit of elements.

`coord.strided() * Crosswise * kFactor * Shape::kStrided / kFactor * sections_ = coord.strided() * Crosswise * Shape::kStrided * sections_ = coord.strided() * stride_ / kFactor * Shape::kStrided `

**Comment by peisun1115** [comment]
Thank you! 

I created a pull request but i am not able test it locally.

it failed to compile. maybe my local gcc version is not compatible. maybe you can just fix it. thanks!

/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:

**Comment by mnicely** [comment]
@peisun1115 did you resolve your issue?

**Comment by peisun1115** [comment]
yes, it is resolved
