### ISSUE TITLE
How to include cutlass?

### ISSUE THREAD

**Issue by eAzure** [NVIDIA/cutlass#504]
**I am a novice in using c++, can you tell me how to include #include <cutlass/cutlass.h> after make? Thanks!**

**Comment by hwu36** [comment]
I dont get your question.

你可以用中文问。

**Comment by eAzure** [comment]
好的，感谢！我跟着QuickStart走到了Using CUTLASS within other applications这一步，现在想跑一下下面的C++代码，提示我fatal error: cutlass/cutlass.h: No such file or directory，我把对应目录加入到LD_LIBRARY_PATH=下，但是没有用，请问该如何修改让include能找到cutlass相关的头文件

**Comment by hwu36** [comment]
you need to add something like `-I/home/scratch.haichengw_gpu/cutlass_2.x/include -I/home/scratch.haichengw_gpu/cutlass_2.x/tools/util/include` to your `nvcc` command line.

**Comment by eAzure** [comment]
Ok, thanks!
