### ISSUE TITLE
[QST] Can kWarpGemmIterations be odd number?

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#505]
Do these [two lines](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_pipelined.h#L294-L295) work if kWarpGemmIterations is an odd number? 

If kWarpGemmIterations is odd (say 3), when warp_mma_k = 2, it will update warp_frag_A[1]. After that,  warp_mma_k = 0 which will use warp_frag_A[0] and update warp_frag_A[1] again. 

Thank you!

**Comment by hwu36** [comment]
We don't support odd number `kWarpGemmIterations`.  A static_assert can be added here.

**Comment by peisun1115** [comment]
Thank you for your reply!
