### ISSUE TITLE
[QST]Got cutlass error: Error Misaligned Operand at

### ISSUE THREAD

**Issue by huangmiumang** [NVIDIA/cutlass#506]
1. The environment is as follows，cutlass  v2.9.0, T4 gpu, cuda 10.2
2. When modify examples/12_gemm_bias_relu/gemm_bias_relu.cu matrix shape
  const int length_m = 5120;
  const int length_n = 4096;
  const int length_k = 4096;
to
  const int length_m = 1;
  const int length_n = 105;
  const int length_k = 107;
it happens error.
3. Is there a way to support arbitrary shapes without affecting performance?
original shape is ok
![image](https://user-images.githubusercontent.com/19187765/170984375-ba7b776d-293a-4ec3-ad74-771bf311474e.png)
modified shape happen error
![image](https://user-images.githubusercontent.com/19187765/170984883-522246a6-d3da-44a8-a875-5f61839a9d51.png)
![image](https://user-images.githubusercontent.com/19187765/170984825-3e9b51bb-0911-4046-901d-d12b0b3b4438.png)

**Comment by hwu36** [comment]
There is an alignment requirement to the problem size.  Check https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L414-L439

If you cannot pad your data to meet the requirement, you need to change your alignment.  The larger the alignment is, the better the performance is.

**Comment by shamomanba** [comment]
Thank you.However, in the actual scene, the shape ranges are very large, only through padding to solve it? cublas api support arbitrary shapes.

**Comment by shamomanba** [comment]
> 
Thank you.However, in the actual scene, the shape ranges are very large, only through padding to solve it? cublas api support arbitrary shapes.
