### ISSUE TITLE
[QST] Why do you need partition_contiguous_idx in Congruous layout (crosswise is always set to 64)?

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#511]
Though you can still partition the layout to be 4 '4x4' (128bits per element) blocks, it seems unnecessary when crosswise is 64 and it just adds more compute? it can just be treated as 1 '8x8' block?

For example, [these lines](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L252-L258),

if (Policy::LdsmShape::kContiguous == 4) {
        // Matrix multiply 1688 A/B
        // Q0 Q1 Q2 Q3 (Q stands for 1 8x128bit block).
        // Four blocks are next to each other in the contiguous dimension.
        partition_contiguous_idx = ((lane_in_quad_pair >> 2) ^ i);
        access_contiguous_idx = (quad_pair ^ lane_in_quad);
        access_strided_idx = lane_in_quad_pair;
      }

Why isn't it just written as the following? 

if (Policy::LdsmShape::kContiguous == 4) {
        // Matrix multiply 1688 A/B
        // Q0 Q1 Q2 Q3 (Q stands for 1 8x128bit block).
        // Four blocks are next to each other in the contiguous dimension.
        partition_contiguous_idx = 0; // not needed, 8x8 block, no partition
        access_contiguous_idx = (quad_pair + (i << 2)) ^   lane_in_quad_pair;
        access_strided_idx = lane_in_quad_pair;
      }

Is there any case where this partition have to happen?

**Comment by peisun1115** [comment]
btw, i also write a simple code to confirm this

https://www.onlinegdb.com/KlmWw-L4r

(for m16n8k16's A operand)

**Comment by hwu36** [comment]
You can understand it as 8x8

**Comment by peisun1115** [comment]
Thanks! Glad that i am not missing anything!
