### ISSUE TITLE
[QST] Wrong comment? 

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#512]
Are [these comments](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L260-L276) inaccurate (the code is correct but not comment)?

The convention ([stated here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L253-L255)) are that the rows represent contiguous dimension. then for m16n8k16 's A operand, shouldn't it be:

Q0 Q1
Q2 Q3
?

As you want to load the two 8x8 blocks in the first *column* before the 2nd column based on the official m16n8k16 doc.

**Comment by hwu36** [comment]
If row represent contiguous dimension, you are correct.  PR?

**Comment by peisun1115** [comment]
thanks for confirming. will send a PR.

Another related question:

is [this](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L406) a bug? should it be 8 * Policy::LdsmShape::kStrided * s * stride_ ?

s is always 0 here. so it wouldn't matter in reality but it seems to be a bug by itself

**Comment by hwu36** [comment]
I think you are correct.

It should be `Policy::kLdsmOpInner * Policy::LdsmShape::kStrided * s * stride_` .  PR?

**Comment by peisun1115** [comment]
Sent a PR. thanks!
