### ISSUE TITLE
[QST] What is this reuse of Rb?

### ISSUE THREAD

**Issue by peisun1115** [NVIDIA/cutlass#515]
I have trouble understanding this comment (https://github.com/NVIDIA/cutlass/blob/12f4108ac2233022b92f0e3533c23bed399fcf45/include/cutlass/gemm/warp/mma_tensor_op.h#L297).

Do you think you can help to explain ?

Many thanks!

**Comment by hwu36** [comment]
```
   _   _
| | | |
| | | |
|_| |_|
```

The visitation order is like this.  down up down up down up.  We tried to reuse the same B operand as long as possible.

**Comment by peisun1115** [comment]
Thanks for the nice figure.

1. Why does this Serpentine visitation  matter ? the same B operand is used for each column.  
2. Why does reusing B operand matter at all? I think they are just in registers? So it doesn't matter whether they are reused? 
3. Why is there a difference between SM80 vs SM75 and lower?
Many thanks for the help!

**Comment by hwu36** [comment]
Sorry, I cannot tell.  Just do it in the same way.

**Comment by peisun1115** [comment]
Np, maybe there are some hidden features

**Comment by peisun1115** [comment]
Relatedly, do you know how many m16n8k8 mma's are needed to hide its instruction latency? I cannot find this anywhere in nvidia's doc.

**Comment by hwu36** [comment]
The compiler will take care of it.  If you are wondering what tile sizes are needed, you can use those listed in the profiler (https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L1104-L1112) .

**Comment by peisun1115** [comment]
I was writing some custom iterators for my problem. I wanted to see how small a tile can be given a fixed number of warps per sm to avoid being limited by mma's own latency (rather than its throughput). i will just benchmark it then. thanks
