### ISSUE TITLE
[QST] how to undersrtand a cutlass kernel name?

### ISSUE THREAD

**Issue by dongxiao92** [NVIDIA/cutlass#520]
**What is your question?**

I'd like to understand if we could recognize which tensor core instruction and what's the data types for a given cutlass kernel. 
For example, for kernel "**cutlass_80_tensorop_s1688gemm_64x64_16x6_tn_align4**", how can I know the data types for the input and output? What't the tensor core intruction used in this kernel?

**Comment by mnicely** [comment]
Most of the information you're looking for is in the `functionality.md`.
https://github.com/NVIDIA/cutlass/blob/master/media/docs/functionality.md
