### ISSUE TITLE
[QST] Problem using cudamalloc to create tensorref

### ISSUE THREAD

**Issue by SpringWave1** [NVIDIA/cutlass#522]
```
cutlass::int4b_t* cutlass_int4b_inp;
cutlass::int4b_t* cutlass_int4b_weight;
num_byte_input = input_N * sizeof(cutlass::int4b_t); 
num_byte_weight = weight_N * sizeof(cutlass::int4b_t);

cudaMalloc((void**)&cutlass_int4b_inp, num_byte_input);
cudaMalloc((void**)&cutlass_int4b_weight, num_byte_weight);

cutlass::TensorRef<ElementInputA, LayoutInputA> input_ref(cutlass_int4b_inp, LayoutInputA::packed(input_size));
cutlass::TensorRef<ElementInputB, LayoutInputB> weight_ref(cutlass_int4b_weight, LayoutInputB::packed(filter_size));
```

Hi, i am trying to use int4b_t conv kernel for T4. And it turns out misalligned cuda memory in execution.
Is the creation process of int4b_t tensors correct? 
Here, filder_size and input_size are two `cutlass::Tensor4DCoord`

**Comment by hwu36** [comment]
What is your problem size?

**Comment by SpringWave1** [comment]
> What is your problem size?
```
 cutlass::conv::Conv2dProblemSize problem_size(      
            input_size,
            filter_size,
            padding,
            conv_stride,
            dilation,
            output_size,
            mode,
            split_k_slices);
```
Where the outputsize is calculated by
```
output_size.n() = input.size(0);
output_size.h() = (input_size.h() + padding.n() + padding.h() - filter_size.h()) / conv_stride.row() + 1;
output_size.w() = (input_size.w() + padding.w() + padding.c() - filter_size.w()) / conv_stride.column() + 1;
output_size.c() = weight.size(0);
```

**Comment by hwu36** [comment]
There is some alignment restriction. I need to know the exact number to help you.

**Comment by SpringWave1** [comment]
input NHWC 256, 14, 14, 512
filder  NHWC 512, 3, 3, 512
output

**Comment by SpringWave1** [comment]
> There is some alignment restriction. I need to know the exact number to help you.



> There is some alignment restriction. I need to know the exact number to help you.

input NHWC 256, 14, 14, 512
filder NHWC 512, 3, 3, 512
output

**Comment by hwu36** [comment]
your size is okay.

the problem is here: `sizeof(cutlass::int4b_t)` is `0`

you need to use `element_number * cutlass::sizeof_bits<cutlass::int4b_t>::value / 8`

**Comment by SpringWave1** [comment]
> your size is okay.
> 
> the problem is here: `sizeof(cutlass::int4b_t)` is `1`
> 
> you need to use `element_number * cutlass::sizeof_bits<cutlass::int4b_t>::value / 8`
Yeah, my problem is partially solved. BTW, what is the restriction of alignment here?

**Comment by hwu36** [comment]
Check this function https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/device/implicit_gemm_convolution.h#L101 for the detail.

By default, you need to have 128 bit alignment which means input/output channel number needs to be multiple of 32 for 4b data.  You can choose to use different alignment in the top level template.

**Comment by mnicely** [comment]
@SpringWave1 were you able to resolve your issue?

**Comment by SpringWave1** [comment]
> @SpringWave1 were you able to resolve your issue?

Yes, I will close issue now.
