### ISSUE TITLE
[DOC]Require detailed description of `xxxThreadMap` and `xxxTileIterator` 

### ISSUE THREAD

**Issue by zhanggefan** [NVIDIA/cutlass#525]
Hi, NVIDIA team!

Thank you for your awesome work!

I am a newbie to this area and I have been trying to learn this framework for months and still made no progress.

What puzzles me is that there are so many kinds of `xxxThreadMap`s and `xxxTileIterator`s. I know that they are for data moving and re-arranging across CPU & GPU memories, but I cannot figure out the difference between different kind of them and their target use scenarios.

By experiments, I also find that there is sort of dependencies between them -- I cannot bind some kind of `xxxThreadMap` to every kind of `xxxTileIterator` otherwise it may pass the compilation without error but would trigger "illegal memory access" at runtime.

> for example if I changed https://github.com/NVIDIA/cutlass/blob/f248e9bdb4a6e59bd665241f11cc76754b3c9429/examples/02_dump_reg_shmem/dump_reg_shmem.cu#L154 from <8, 4> to <4, 8> the program will pass the compilation but raise "illegal memory access" at runtime.

So could you please give me a more detailed description of `xxxThreadMap` and `xxxTileIterator`, or a way to systematically learn their functionalities and their actual runtime behaviors?

Thank you in advance!!

**Comment by hwu36** [comment]
What kind of kernels do you need?  GEMM or CONV, data types, tensor cores or not, architectures, layouts of inputs and outputs, any kernel fusion?

CUTLASS provides lots of modules and I recommend focusing on one kernel as the beginning.  You can insert many printfs to learn the code.  Not all templates are needed by all the cases, you can only focus the ones that are actually used by your case.

Our previous GTC talks discusses the memory movement in details.  https://www.nvidia.com/en-us/on-demand/session/gtcsj20-s21745/ and https://www.nvidia.com/en-us/on-demand/session/gtcsiliconvalley2018-s8854/ .

`ThreadMap` is used to decide the initial position of each thread, how many iterations that each thread will load/store, the distance between two memory accesses.

`predicated_tile_access_iterator_xxx.h` under `include/cutlass/transform/threadblock/` is used to compute the addresses of global memory.   Its constructor initiates each thread to the start position by using `ThreadMap`.  `operator++` moves to the next memory position.  `add_tile_offset()` moves in the unit of tiles.  Its `get` method returns the address for the memory access.  This iterator is used directly by Ampere `cp.async` to load from the global memory.  It is also used underneath `predicated_tile_iterator_xxx.h` which is used by pre Ampere gemm kernels.  In this case, the access iterator will provide the addresses for the upper iterator to load.

`regular_tile_access_iterator_xxx.h` and `regular_tile_iterator_xxx.h` are similar to the above `predicated_tile_access_iterator_xxx.h` and `predicated_tile_iterator_xxx.h`.  The regular iterators are used to do shared memory stores.

There are hidden hand shakes between global memory load, shared memory store, and final shared memory load.  When you change one, you may need to change the other parts too.  That is why you got a failure after you changed the `ThreadMap`.

**Comment by mnicely** [comment]
@zhanggefan were your questions resolved with @hwu36's response?
