### ISSUE TITLE
[QST] How many threads and blocks does cutlass use? (When C is tall in official post)

### ISSUE THREAD

**Issue by Arsmart123** [NVIDIA/cutlass#527]
Hi! I am learning cutlass. And I read this post: [CUTLASS: Fast Linear Algebra in CUDA C++ | NVIDIA Technical Blog](https://developer.nvidia.com/blog/cutlass-linear-algebra-cuda/)
But I can not find official “dispatch_policies.h”, only find one in huggingface’s github!
[pytorch_block_sparse/dispatch_policies.h at master · huggingface/pytorch_block_sparse · GitHub](https://github.com/huggingface/pytorch_block_sparse/blob/master/pytorch_block_sparse/cutlass/gemm/dispatch_policies.h)

Actually I am developing a kernel related to “tall” matmul, which has small N and large M for resulting C(m*n). So I am quite interested in the parameters here:(as shown in the post)

```C++
/// CUTLASS SGEMM example
__global__ void gemm_kernel(void gemm_kernel(
    float *C, float *C, 
    float const *A, float const *A, 
    float const *B, float const *B, 
    int M, int M, 
    int N, int N, 
    int K) {int K) {

    // Define the GEMM tile sizes - discussed in next section// Define the GEMM tile sizes - discussed in next section
    typedef block_task_policy <typedef block_task_policy <
        128, // BlockItemsY: Height in rows of a tile128, // BlockItemsY: Height in rows of a tile
        32, // BlockItemsX - Width in columns of a tile32, // BlockItemsX - Width in columns of a tile
        8, // ThreadItemsY - Height in rows of a thread-tile8, // ThreadItemsY - Height in rows of a thread-tile
        4, // ThreadItemsX - Width in columns of a thread-tile4, // ThreadItemsX - Width in columns of a thread-tile
        8, // BlockItemsK - Depth of a tile8, // BlockItemsK - Depth of a tile
        true, // UseDoubleScratchTiles - whether to double-buffer SMEMtrue, // UseDoubleScratchTiles - whether to double-buffer SMEM
        block_raster_enum::Default // Block rasterization strategy::Default // Block rasterization strategy
    > block_task_policy_t;> block_task_policy_t;

    // Define the epilogue functor// Define the epilogue functor
    typedef gemm::blas_scaled_epilogue<float, float, float> epilogue_op_t ;typedef gemm::blas_scaled_epilogue<float, float, float> epilogue_op_t ;

    // Define the block_task type.// Define the block_task type.
    typedef block_task < typedef block_task < 
        block_task_policy_t, block_task_policy_t, 
        float, float, 
        float, float, 
        matrix_transform_t::NonTranspose, matrix_transform_t::NonTranspose, 
        4, 4, 
        matrix_transform_t::NonTranspose, matrix_transform_t::NonTranspose, 
        4, 4, 
        epilogue_op_t, epilogue_op_t, 
        4, 4, 
        true true 
    > block_task_t;> block_task_t;

    // Declare statically-allocated shared storage// Declare statically-allocated shared storage
    __shared__ block_task_t::scratch_storage_t smem;block_task_t::scratch_storage_t smem;

    // Construct and run the task// Construct and run the task
    block_task_t(block_task_t(
        reinterpret_cast(&smem),reinterpret_cast(&smem),
        &smem,&smem,
        A,,
        B,,
        C,,
        epilogue_op_t(1, 0),epilogue_op_t(1, 0),
        M,,
        N,,
        K).run();).run();
}}
```
**My question is: how many thread and block are allocated here?** I really can not find any info nearby…

Thank you!!!

**Comment by hwu36** [comment]
The code you posted belongs to cutlass 0.1.  The current cutlass looks very different.  Here is how the top level looks like if you use tensor cores: https://github.com/NVIDIA/cutlass/blob/master/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu#L212-L226

thread number is `32 * ShapeMMAThreadBlock::kM / ShapeMMAWarp::kM * ShapeMMAThreadBlock::kN / ShapeMMAWarp::kN * ShapeMMAThreadBlock::kK / ShapeMMAWarp::kK`

threadblock number is `problem_size_M / ShapeMMAThreadBlock::kM * problem_size_N / ShapeMMAThreadBlock::kN * problem_size_K / ShapeMMAThreadBlock::kK`

**Comment by Arsmart123** [comment]
Oh, thank you!! 

1. Actually I am not using tensor core, if you have a version without it, better~

2. Also, I notice here we use 32*128/64*128/64*64/64=128 threads per block. I did not find a version specifically for "tall" matrix (which means, then resulting C has a large M but small N). In  [official post](https://developer.nvidia.com/blog/cutlass-linear-algebra-cuda/) mentioned different policies for different shape. Do you know any dividing policy in the latest cutlass?

Thank you!!!
