### ISSUE TITLE
[DOC] Could you write document for how to use cutlass on windows?

### ISSUE THREAD

**Issue by Arsmart123** [NVIDIA/cutlass#528]
Hi! I am using windows....And I have heard cutlass can be used on windows. Could you write some document to guide us? Thank you!!!

**Comment by mnicely** [comment]
Hi @Arsmart123, have you tried using CUTLASS through WSL2?

**Comment by ziyuhuang123** [comment]
No, I mean....directly use in windows?

**Comment by mhoemmen** [comment]
@ziyuhuang123 @Arsmart123 Greetings!  We have a document explaining how to build CUTLASS on Windows with Visual Studio.  It lives in the repository, in the `media/docs/build` directory.  Here is a link.

https://github.com/NVIDIA/cutlass/blob/main/media/docs/build/building_in_windows_with_visual_studio.md

Please feel free to reopen this issue if you have a more specific question or request.  Thanks for your interest in CUTLASS!
