### ISSUE TITLE
[BUG] miss some include head in cutlass/include/cutlass/epilogue/thread/linear_combination_generic.h

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#530]
**Describe the bug**
when we use [linear_combination_generic](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_generic.h#L63) to generate our own epilogue, we found some compilation error that as follows
![image](https://user-images.githubusercontent.com/19748572/174071675-6c1ce801-043a-4026-b654-92f58d6cb804.png)

**Expected behavior**
we may need to add 

#include "cutlass/epilogue/thread/scale_type.h"

in this [file](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_generic.h#L42)

**Comment by hwu36** [comment]
you are correct.  File a PR?

**Comment by lw921014** [comment]
> File a PR?

OK. Pr is https://github.com/NVIDIA/cutlass/pull/531, please review.
