### ISSUE TITLE
[FEA] Support latest NVCC to compile with cuda10

### ISSUE THREAD

**Issue by Xseventh** [NVIDIA/cutlass#534]
**Is your feature request related to a problem? Please describe.**
recently, I try to compile cutlass with cuda10 and nvcc11.6, because nvcc is not bind with cuda lib. If use nvcc11, we can support more cuda_arch_gencode, and can get more compiler optimize opportunity.

**Describe the solution you'd like**
I found many macro __CUDACC_VER_MAJOR__ for check cuda version in cutlass, but CUDA_VERSION macro can more exactly express current used cuda version. If not necessary required compiler version, we should use CUDA_VERSION to instead of __CUDACC_VER_MAJOR__ macro.

**Comment by hwu36** [comment]
We actually tried `CUDA_VERSION`, but it causes us issues.

We do not recommend to mix different versions of cuda and nvcc, especially the major version number is different.  They are not tested in this way.

**Comment by Xseventh** [comment]
> 

Thanks for your reply, I want to known what issue caused by macro CUDA_VERSION, do you have some comment?
