### ISSUE TITLE
[QST] Any support or examples of uint1_t x int1_t GEMM?

### ISSUE THREAD

**Issue by Akimoto-Cris** [NVIDIA/cutlass#535]
Is `b1 x b1` GEMMs all implemented by XOR that requires `uint1_t x uint1_t` ? 
What if `A=uint1_t` and `B=int1_t` ? (e.g. A is ReLU output, B is weight)

Thanks in advance.

**Comment by hwu36** [comment]
> Is b1 x b1 GEMMs all implemented by XOR that requires uint1_t x uint1_t ?

We supports both `xor_popc` and `and_popc`.  See this one https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma_sm80.h#L2017 and this one https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma_sm80.h#L2084

> What if A=uint1_t and B=int1_t ?

signed `int1_t` is impossible.  sign bit would take the only available bit and you have no place to store the data.

**Comment by Akimoto-Cris** [comment]
Hi @hwu36 , I've seen works that use signed representation, e.g., [Xnor-net: Imagenet classification using binary convolutional neural networks](https://link.springer.com/chapter/10.1007/978-3-319-46493-0_32), who signed representation for both `X` and `W` and supposedly uses XNOR-Bitcount op for conv.
So I think signed 1-bit `W` is a realistic scenario.
