### ISSUE TITLE
[QST] A100 double-precision Tensor Cores ?

### ISSUE THREAD

**Issue by touisteur** [NVIDIA/cutlass#536]
Hi,

is there any support for DP Tensor Cores in cutlass, available or foreseen ?

Thanks in advance

**Comment by hwu36** [comment]
We have many f64 or complex f64 unit tests here: https://github.com/NVIDIA/cutlass/tree/master/test/unit/gemm/device

**Comment by touisteur** [comment]
Thanks a lot to both of you, I have everything I need.

Le jeu. 23 juin 2022 à 05:53, Haicheng Wu ***@***.***> a
écrit :
