### ISSUE TITLE
Can cutpass be considered as the same as cudnn and cublass? If so, what is the difference?

### ISSUE THREAD

**Issue by eAzure** [NVIDIA/cutlass#539]
**Execuse me, can cutlass be considered as the same as cudnn and cublass? If so, what is the difference?**

**Comment by hwu36** [comment]
cutlass overlaps with cudnn and cublass a lot, though not entirely the same as to what features are supported.  The biggest difference is that cutlass is open sourced and the other two are closed sourced.  We discussed when to use what in detail here: https://github.com/NVIDIA/cutlass/discussions/223#discussioncomment-637999

**Comment by eAzure** [comment]
Thanks!
