### ISSUE TITLE
Multiply add batches of matrices of shape [n, 4, 4], [n, 4, 4] and [n,4,4] directly on tensor cores

### ISSUE THREAD

**Issue by guidocalvano** [NVIDIA/cutlass#54]
Will it be possible in the near future to directly use the tensor cores, with batches of matrices of shape [n, 4, 4]?
I imagine a function like this one https://github.com/NVIDIA/cutlass/blob/master/cutlass/gemm/fp16_sgemm_multiply_add.h#L69
now capable of reading three matrices;

a is of type float16 and has shape [n, 4, 4]
b is of type float16 and has shape [n, 4, 4]
c is of type float32 and has shape [n, 4, 4]

Is there some devil in the details I am missing that makes this non-trivial to create? Your documentation states it cannot be done. 

It would be really awesome to have this function for this (relatively) new type of neural network that can reverse engineer scene trees, which operates on 4x4 matrices: https://openreview.net/pdf?id=HJWLfGWRb

I also imagine this very useful for many other applications.

I really hope you will consider making this if it is not too much work.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-65

**Comment by guidocalvano** [comment]
That link is to the most awesome paper on neural nets I've read by the way. I highly recommend it. It's a shame they take a day to train those nets on 8 graphics cards. Imagine how the computer vision would change if they only took a day to train ;)

**Comment by mnicely** [comment]
At this time, tensor core sizes are limited to the set provided in documentation
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#wmma-type-sizes

**Comment by hwu36** [comment]
The link Matt posted is for wmma.  As to native mma, you can check https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-for-mma
