### ISSUE TITLE
[RFE] Optimize the conv-fprop operator

### ISSUE THREAD

**Issue by lixiaolx** [NVIDIA/cutlass#540]
**Is your feature request related to a problem? Please describe.**
When using the -conv-fprop of cutlass to perform the conv operation, it is found that in the entire kernel, the data transmission takes a long time and accounts for a large proportion. The performance of the entire kernel is poor, and the use of sm is not very good
q1: From the perspective of the entire kernel of about 1.2ms, the time-consuming (1.2ms) = data transfer/throughput, so that the entire kernel is transmitting data. Is that reasonable? Is the calculation of tensor core time-consuming, or is it overlapped by transmission?
q2: The L1 hit rate in the picture below is very low. Is this reasonable? If it's unreasonable, is it possible to improve the hit rate?
q3: From the point of view of instruction execution, there are many move instructions in epilogue-broadcast, is this reasonable? Can it be optimized?
![image](https://user-images.githubusercontent.com/17673134/175202525-18338402-f5df-4299-8cb4-50814c9ab895.png)
![image](https://user-images.githubusercontent.com/17673134/175204155-b30038cf-7a61-41e4-a2e2-44102c6a502a.png)
![image](https://user-images.githubusercontent.com/17673134/175204188-3eb93ea0-be91-4fbb-8df4-216e9b75119c.png)

![image](https://user-images.githubusercontent.com/17673134/175204019-3bf94eae-62de-48b6-824b-f93f7265c985.png)

**Describe the solution you'd like**
Can the kernel be further optimized? For example, to reduce the time-consuming of data transmission (such as reducing the amount of data transmission or increasing the transmission bandwidth)?

**Additional context**
GPU：T4
input：N,H,W,C,P,Q,K,R,S,pad_h,stride_h,dilation_h,cost_time,64,56,56,64,56,56,256,1,1,0,1,1
code：
  using ElementAccumulator = cutlass::half_t, 
  using ActivationOp = cutlass::epilogue:: thread ::Identity, 
  using BinaryOp = cutlass::plus,
  using UnaryOp = cutlass::epilogue:: thread ::ReLu
  using ElementA = cutlass::half_t;
  using ElementB = cutlass::half_t;
  using ElementC = cutlass::half_t;
  using ElementD = ElementC;
  using ElementCompute = ElementAccumulator;
using EpilogueOutputOp = cutlass::epilogue:: thread ::LinearCombinationResidualBlock<
    ElementD,
    ElementAccumulator,
    ElementCompute,
    ElementC,
    8,
    ActivationOp,
    BinaryOp,
    UnaryOp> ;
  using Conv2dFpropKernel = typename cutlass::conv:: kernel ::DefaultConv2dFpropWithBroadcast<
    ElementA, cutlass::layout::TensorNHWC,
    ElementB, cutlass::layout::TensorNHWC,
    ElementC, cutlass::layout::TensorNHWC,
    ElementAccumulator,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm75,
    cutlass::gemm::GemmShape<128, 128, 32>,
    cutlass::gemm::GemmShape<64, 64, 32>,
    cutlass::gemm::GemmShape<16, 8, 8>,
    EpilogueOutputOp,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>,
    2,
    cutlass::arch::OpMultiplyAdd,
    cutlass::conv::IteratorAlgorithm::kOptimized,
    cutlass::conv::StrideSupport::kStrided,
    8,
    8>::Kernel;
  using Conv2dFprop = cutlass::conv::device::ImplicitGemmConvolution<Conv2dFpropKernel>;

**Comment by hwu36** [comment]
Your `RSC` is 64 which means your kernel is completely memory bound and only needs 2 iterations of the mainloop.  You can use cutlass profiler (https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md) to profile all available tile sizes to find the best one.  (use `-DCUTLASS_LIBRARY_KERNELS=h1688fprop` in the cmake to enable all sm75 fprop tile sizes).  256x64 may be more useful to you than 128x128.

**Comment by lixiaolx** [comment]
> 256x64 may be more useful to you than 128x128.
I tested it and changed it to:
cutlass::gemm::GemmShape<256, 64, 32>,
cutlass::gemm::GemmShape<64, 64, 32>,
cutlass::gemm::GemmShape<16, 8, 8>,
but it got slower, now it takes 1.8ms to run

**Comment by lixiaolx** [comment]
> maybe you can also try threadblock size 128x64 and warp size 64x32. As I said earlier, this problem size is completely memory bound, Your performance data looks reasonable to me.

I use Driver Version: 440.33.01 CUDA Version: 10.2. I have tried the following combinations on the T4 card, and the performance data are not ideal. Is there any good way to optimize the kernel?
![image](https://user-images.githubusercontent.com/17673134/175448463-881d5e2f-77da-4ee5-b0b2-773d3701b916.png)

**Comment by hwu36** [comment]
Your cuda is too old.  I recommend to use 11.6+.  See https://github.com/NVIDIA/cutlass/discussions/495

Again, your problem size is completely memory bound.  Your perf is not bad.

**Comment by lixiaolx** [comment]
> Your cuda is too old. I recommend to use 11.6+. See #495
> 
> Again, your problem size is completely memory bound. Your perf is not bad.

Have you tested the performance of conv on cuda11.6+? What kind of performance data is it? For example, compared with cudnn

**Comment by hwu36** [comment]
see https://github.com/NVIDIA/cutlass/blob/master/media/images/cutlass-2.9-implicit-gemm-performance.png

**Comment by lixiaolx** [comment]
Ok, thanks, do you have the performance comparison data between the high version of cuda and cuda10.2?

**Comment by hwu36** [comment]
> do you have the performance comparison data between the high version of cuda and cuda10.2?

roughly 10%, but again yours is compute bound.  better codegen cannot help much.

> If only the driver version is upgraded, but the cuda version is not upgraded, will there be a performance improvement?

i think you cannot launch kernel if cuda version and driver version are very different.

**Comment by lixiaolx** [comment]
> roughly 10%, but again yours is compute bound. better codegen cannot help much.

The conv performance is good on the new cuda version. Did you optimize the conv implementation, or did you improve the cuda version simply? If the conv implementation is optimized, can these optimizations be migrated to the old version?

**Comment by hwu36** [comment]
cuda is getting better.
