### ISSUE TITLE
How to build a single example ?[QST]

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#552]
**What is your question?**
I am trying to use cutlass to do gather-gemm-scatter fusion and reading [example 36](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion). Is there any way to build this single example and run it? I've read the quick start but can't find the solution.

**Comment by hwu36** [comment]
make 36_gather_scatter_fusion

**Comment by umiswing** [comment]
> make 36_gather_scatter_fusion

Thanks! It works now. :)
