### ISSUE TITLE
[QST] Is there a more detailed API document?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#555]
**What is your question?**
Hello, I am reading cutlass's [example 36_gather_scatter_fusion](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion) and have confusion about the code(e.g. How to set the argument if I want to write a custom fusion). I read [gemm_api](https://github.com/NVIDIA/cutlass/blob/master/media/docs/gemm_api.md) and [Doxygen documentation](https://nvidia.github.io/cutlass) but find it doesn't help my understanding. Is there a more detailed API document?

**Comment by hwu36** [comment]
doxygen doc is not correct.  

If you understand how to setup and run a cutlass gemm, the gather/scatter example adds two more things

First, it adds three boolean to the end of the top [template list](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal.h#L121-L126) to indicate if you want to do gather/scatter or not.

Second, it adds three pointers to the end of the [argument list](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L170-L172) to passes in small arrays in the device memory.

The example will get indices from these arrays to decide which row/column to gather or scatter data.  It can only gather/scatter columns from/to Column Major matrix or rows from/to Row Major matrix.

**Comment by umiswing** [comment]
@hwu36 
Thanks. And what is the constraint for the data type? I modify the ElementInputA and ElementInputB to float in example 36, and get compilation error.
