### ISSUE TITLE
[QST] conv mode selection in host/convolution.h for Depsep_Fprop conv

### ISSUE THREAD

**Issue by lw921014** [NVIDIA/cutlass#558]
**What is your question?**
In [file](https://github.com/NVIDIA/cutlass/blob/master/tools/util/include/cutlass/util/reference/host/convolution.h#L176), I think 
mode == cutlass::conv::Mode::kCrossCorrelation should be change as mode == cutlass::conv::Mode::kConvolution. Is it correct?

**Comment by hwu36** [comment]
Code is correct, it matches the kernel implementation https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_analytic.h#L207-L213
