### ISSUE TITLE
[QST] How to get `OutputTileThreadMap` for a given threadblock Mma ?

### ISSUE THREAD

**Issue by danthe3rd** [NVIDIA/cutlass#565]
Hello,

I'm having a hard time storing results from a matmul back to global memory. I don't have any specific Epilogue operation to perform, so I was going to use directly `cutlass::epilogue::threadblock::PredicatedTileIterator` and `cutlass::epilogue::warp::FragmentIteratorTensorOp`.
I figured out that I could use this to get those iterators directly:
```c++
using OutputTileThreadMap = typename cutlass::epilogue::threadblock::DefaultThreadMapTensorOp<
  ThreadblockShape,
  typename WarpMmaTensorOp::Shape,
  kPartitionsK,
  output_t,
  kElementsPerAccess
>::Type;
```
However, the thread map is not accurate. `thread_id=0` has an accumulator with values:
```
[result[0,0], result[0,1], result[0,8], result[0,9] ... result[0,24], result[0,25],
result[8,0], result[8,1] ...
result[16,0], ...
...
]
```
But the threadmap created above will store those as if they were:
```
[result[0,0], result[0,1], result[0,64], result[0,65],
result[1,0], result[1,1], ...
result[8,0], result[8,1] ...
...
]
```
with
```c++
Iterations=cutlass::epilogue::threadblock::OutputTileShape<2, 2, 1, 1, 1>
Delta=cutlass::epilogue::threadblock::OutputTileShape<64, 1, 1, 1, 1>
Shape=cutlass::epilogue::threadblock::OutputTileShape<128, 8, 1, 1, 1>
Count=cutlass::epilogue::threadblock::OutputTileShape<1, 4, 1, 1, 4>
```

So my question is the following: **how can I get a corresponding `OutputTileThreadMap` given a properly constructed `threadblock::Mma` (either Pipelined or Multistage)? Or at a higher-level, how do I construct a Predicated-iterator to load from/store to an accumulator.**

Context:
```
ElementA=float
LayoutA=RowMajor
ElementB=float
LayoutB=RowMajor
ElementC=float
LayoutC=RowMajor
OpClass = cutlass::arch::OpClassTensorOp;
Operator = cutlass::arch::OpMultiplyAddFastF32

ThreadblockShape=[32, 128, 32]
WarpShape=[32, 32, 32]
InstructionShape=[16,8,8]
kPartitionsK=1

I'm running on an A100
```

Thanks a lot!

**Comment by hwu36** [comment]
The normal epilogue process is: register->shared memory->register->global memory .  The round trip to the shared memory is to let every thread own 128bit consecutive data so that we can use 128bit vectorized store to efficiently write to the global memory.  `PredicatedTileIterator` is used to do the last step register->global memory.

If you want to skip the shared memory part.  You can just use https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L2383.  This one is used by almost all gemm threadblock unit tests: https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/threadblock/mma_pipelined_testbed.h#L117-L125

**Comment by danthe3rd** [comment]
Thanks for your (quick) reply! Yes I was able to write back to memory using `MmaTensorOpAccumulatorTileIterator` indeed, but it does not check for bounds (which I need).

> register->shared memory->register->global memory

So even if I don't do any compute in the epilogue it's the fastest way to do so. Thanks :)

One additional question: all of the epilogues I see require some `OutputOp` tho - what should I use if I don't need any particular operation?

**Comment by hwu36** [comment]
You can use https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination.h#L66 and set `Scale` in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination.h#L63 to `Nothing` in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/scale_type.h#L54  Then it is not going to do any elementwise operation.

**Comment by danthe3rd** [comment]
Thanks a lot! Really appreciate your help and pointers :)
