### ISSUE TITLE
[QST] How to make example/36_gather_scatter_fusion work with float input type?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#566]
Hello! I am trying to make [examples/36_gather_scatter_fusion](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion) work with float input type. I modify `ElementInputA` and `ElementInputB` to `float` in the example, and it is the only change I make in the source code[(here is the change)](https://github.com/umiswing/cutlass/commit/6291dc7bf0a7e5cd7904bbe662910948dcfd6472), which lead to a compilation error. I read [examples/07_volta_tensorop_gemm](https://github.com/NVIDIA/cutlass/tree/master/examples/07_volta_tensorop_gemm), [examples/08_turing_tensorop_gemm](https://github.com/NVIDIA/cutlass/tree/master/examples/08_turing_tensorop_gemm) and guessed it may cause by the use of MMA instructions on tensor core. However, I run the code on a GPU of NVIDIA Ampere architecture, according to [examples/14_ampere_tf32_tensorop_gemm](https://github.com/NVIDIA/cutlass/tree/master/examples/14_ampere_tf32_tensorop_gemm), it should support fp32 input. Is there any way to make examples/36_gather_scatter_fusion work with float input type?

GPU I use:
`NVIDIA GeForce RTX 3060 Laptop GPU`

[Here is my full code.](https://github.com/umiswing/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu)
[Here is the compilation error I got.](https://raw.githubusercontent.com/umiswing/cutlass/master/compile.error)

**Comment by hwu36** [comment]
If you need to change the data types, you need to change the tile sizes too.  Check these in example 14: https://github.com/NVIDIA/cutlass/blob/master/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu#L189-L194

**Comment by hwu36** [comment]
Great to hear that you got it working.  Feel free to create a PR to add comment that you would like to have.
