### ISSUE TITLE
How many stages can we use in multistage gemm?[QST]

### ISSUE THREAD

**Issue by c90mkl** [NVIDIA/cutlass#567]
There are three stages used In the examples, can we use more stages in Ampere? Is there any performance decreasement if more stages are used?

**Comment by hwu36** [comment]
You can use any stage number >= 3 as long as the shared memory usage is below what the hardware provides.  The shared memory usage is computed in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/threadblock/mma_base.h#L139-L146 .  Padding is 0 in the code.

**Comment by c90mkl** [comment]
Thanks for the answer
