### ISSUE TITLE
[BUG] examples/36_gather_scatter_fusion doesn't pass the test with some shapes

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#570]
**Describe the bug**
[examples/36_gather_scatter_fusion](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion) doesn't pass the test with some shapes `[m,n,k]` and `index_size`

**Steps/Code to reproduce bug**
Build examples/36_gather_scatter_fusion and run it. Following are some shapes which can reproduce the bug:
```shell
$ cd build && make 36_gather_scatter_fusion
$ cd examples/36_gather_scatter_fusion/

$ ./36_gather_scatter_fusion --k=248
Failed!
Dumping results in error_gather_GEMM_scatter_fusion.txt

$ ./36_gather_scatter_fusion --k=256
Failed!
Dumping results in error_gather_GEMM_scatter_fusion.txt

$ ./36_gather_scatter_fusion --index_size=4
Got cutlass error: Error Misaligned Operand at: 370

$ ./36_gather_scatter_fusion --m=64 --n=64 --k=32 --index_size=8
Failed!
Dumping results in error_gather_GEMM_scatter_fusion.txt
```
Default shape in the example is ```[248, 1024, 1024]``` and default index size is ```240``` ([as here](https://github.com/NVIDIA/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu#L126-L127)).

**Environment details (please complete the following information):**
 - Environment location: Bare-metal, NVIDIA GeForce RTX 3060 Laptop GPU

**Additional context**
It seems that I need to change tile size for different shapes? But I am not sure what's the requirements when setting tile size.

**Comment by hwu36** [comment]
Thank you for filing the bug.

The device kernel itself is correct.  The example itself is ill-designed.  We can simplify the example to just gather one input operand.

@shangz-ai

**Comment by umiswing** [comment]
Thanks! Looking for cutlass's update. And would you fix this bug soon? Otherwise I will have to try something else to optimize my program.

**Comment by umiswing** [comment]
Thanks! It works now.
