### ISSUE TITLE
Error: parameter packs not expanded with '...'

### ISSUE THREAD

**Issue by RylanYancey** [NVIDIA/cutlass#573]
Hi, I'm trying to build Cutlass

gcc: 11.2.0
g++: 11.2.0
cmake: 3.22.1
Nvidia Toolkit: 11.5.119
Ubuntu: 22.04 WSL

I git clone'd cutlass repo into wsl
I created a build directory
I ran this cmake command:

cmake .. -DCUTLASS_NVCC_ARCHS="70;75;80" -DCUTLASS_LIBRARY_KERNELS=all -DCUTLASS_ENABLE_CUBLAS=OFF -DCUTLASS_ENABLE_CUDNN=OFF -DCUTLASS_ENABLE_TESTS=OFF 

All is good
run this make command:

 make cutlass_profiler -j4

Error!:
![image](https://user-images.githubusercontent.com/76256852/179837509-73e0b1e8-7ac7-4929-a96b-0f45598aa384.png)

Not sure what to do. Tried using gcc10. no dice.

**Comment by jackkosaian** [comment]
Hi,

Are you able to try this out in Docker? I've tried replicating your setup a bit using the [nvidia/cuda:11.7.0-devel-ubuntu22.04](https://hub.docker.com/layers/cuda/nvidia/cuda/11.7.0-devel-ubuntu22.04/images/sha256-16c790bc3349d70a0416cf8bf1eef9b40433ee907018b5ea32bdbddf75433a9d?context=explore) Docker image, and was unable to replicate the issue.

**Comment by RylanYancey** [comment]
Thank for trying to help me. I'm sorry, but I'm giving up on this.
