### ISSUE TITLE
[QST] Save the first activation result when doing back to back gemm/convolution?

### ISSUE THREAD

**Issue by zihaozou** [NVIDIA/cutlass#579]
I am wondering if it is possible to save the intermediate activation result to global memory when doing the b2b conv/gemm? If yes, could I find any example or are there some places I can look into?

**Comment by hwu36** [comment]
@jwang323

**Comment by hwu36** [comment]
yes.  you just need to call the regular epilogue after the 1st gemm.  Here is the epilogue code https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm.h#L282-L371.  You can ignore all split k code if you don't use it.

You need to insert the epilogue code here https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage.h#L642

More plumbing is also needed.

**Comment by zihaozou** [comment]
Thx! I will try it later.
