### ISSUE TITLE
Performance using matrices with small K

### ISSUE THREAD

**Issue by rjfnobre** [NVIDIA/cutlass#58]
Performance of CUTLASS with large K is great.
I get 35702.8 GFLOPs on a NVIDIA 2070 Super running the performance test with the following command:
./cutlass_perf_test ---m=2048 --n=2048 --k=2048 --kernels=wmma_gemm_f16_tn

However, when K is considerably smaller, I get worse performance, as expected (10182.5 GFLOPs), executing the following command:
./cutlass_perf_test ---m=2048 --n=2048 --k=64 --kernels=wmma_gemm_f16_tn

My application relies on lots multiplications of matrices with small K and large values for M and N.
Is there a way to use CUTLASS that allows me to achieve close to the performance of when using large K?

**Comment by d-k-b** [comment]
There have been many improvements to small-K problem sizes in newer CUTLASS releases. In general, just due to the nature of the problem, small-K will not reach the performance of large-K but there are tricks to help bring them closer in some scenarios. Please give things another try!

**Comment by hwu36** [comment]
CUDA 11.3 significantly improves the performance of Ampere/Turing/Volta Tensor Core kernels. See #241 .

You may want to do the benchmarking again with the latest compiler.
