### ISSUE TITLE
[QST]Wield behavior using padding

### ISSUE THREAD

**Issue by zihaozou** [NVIDIA/cutlass#581]
Hi, I've been building my own CUTLASS convolution wrapper for a while. I met a problem when using the padding function. Here is my [project](https://github.com/zihaozou/my_cutlass).
If the input tensor has 2/4 channels, then we don't need to pad and the code works fine(in the first two tests of [unit test](https://github.com/zihaozou/my_cutlass/blob/master/tests/unit_test.cu)). 

The third test will give a tensor with 1 channel. When it detects the input tensor has a dimension with 1/3 channels, the code will help to [pad it to 2/4 channels](https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L159). The test has no problem until I try to[ move the result to host side](https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/tests/unit_test.cu#L91), the [cudaMemCpy](https://github.com/NVIDIA/cutlass/blob/25ebf15d02f5a201a44ef6f436939d7f44530eea/tools/util/include/cutlass/util/device_memory.h#L90) will throw "cuda error misaligned address". 

Did I use the padding function in the wrong way?

**Comment by hwu36** [comment]
When your channel number is 2/4, do you set the alignment do the correct number (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/default_conv2d_fprop.h#L81-L83)?  They need to be set to 2 or r respectively.

**Comment by zihaozou** [comment]
yes, 
I defined a "kernel template" at [https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L81](https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L81), which passes an Integer "alignment" to set the alignment A and B.

for 3/4 channels, I will use the convolution defined at ([https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L105](https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L105)), which passes "4" to "alignment".

for 1/2 channels, I will use the convolution defined at 
[https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L108](https://github.com/zihaozou/my_cutlass/blob/a93e301d38a5dfe64db8b7a2c8c1048313801b87/includes/cutlass_conv.h#L108), which passes "2" to "alignment".

**Comment by hwu36** [comment]
You can use compute-sanitizer or cuda-memcheck to find which instruction causes problem.

**Comment by zihaozou** [comment]
Oh! I found the problem. I just padded the input tensor and my filter still remained as 1 channel...That's so awkward...but thank you @hwu36 .
