### ISSUE TITLE
[FEA] Do you Plan to Add to Gather/Scatter Kernel Support SIMT SM70

### ISSUE THREAD

**Issue by K-Wu** [NVIDIA/cutlass#583]
**Is your feature request related to a problem? Please describe.**
The example in cutlass/examples/36_gather_scatter_fusion/ currently only support sm75 and sm80 and only tensor op is supported. However, error shows up when I switch the architecture template arguments to sm70 and regular non-tensor-core simt operators. I am wondering if this kernel support non-tensor-core SIMT and volta GPUs. If not, will you be adding support for them in future?

**Describe the solution you'd like**
I would like a GEMM kernel with scatter/gather input/output functionality for regular SIMT for SM70. This is strongly related to the SpMM pattern in DGL and very helpful for us contributors to GNN framework like DGL.

**Describe alternatives you've considered**
Not yet.

**Additional context**
NA

**Comment by hwu36** [comment]
We only focus on ampere now, and have no plan to add more features to older architectures.  That said, pre-ampere simt kernels use the same iterators as sm80 kernels to load and store.  So, gather/scatter implementation should be able to be used in these old simt kernels with some potential plumbing.

**Comment by K-Wu** [comment]
Hello Haicheng,

Thank you for your very detailed comments. They helped me a lot while I am navigating through this complicated repo. It could be great if you could provide some feedbacks on the following questions.

I found classes e.g. `cutlass::gemm::kernel::DefaultGemm` also have scatter/gather arguments. Can I expect them to be ready to work on SM70 with SIMT if I choose scatter/gather iterators? Also, the error message compiler provides during a compile error rarely helps due to layers of templates involved. Is there any general advice on prototyping kernels on top of CUTLASS library?

Again, thank you so much for your efforts in responding this thread. I will close this once I got your reply.

Best Regards,
Kun

**Comment by hwu36** [comment]
> Can I expect them to be ready to work on SM70 with SIMT if I choose scatter/gather iterators?

Yes.  However, it is possible that we missed passing the templates in some classes.

>  Is there any general advice on prototyping kernels on top of CUTLASS library?

nvcc does not provide good error messages.  Just pay attention to the first error.  Sometimes, you need to compare the template arguments or function arguments between different layers one by one.

**Comment by K-Wu** [comment]
Gotcha. Thank you, Haicheng!
