### ISSUE TITLE
[QST]conv2d's strange numerical issue.

### ISSUE THREAD

**Issue by zihaozou** [NVIDIA/cutlass#584]
Hi,
I just developed a convolution operation wrapper based on CUTLASS. ([link](https://github.com/zihaozou/my_cutlass))
The fprop, dgrad and wgrad operators seem to work just fine. But one issue is that the output seems to have some numerical issues. the output will sometimes be different from the reference by 1 bit. I am wondering if this is just due to the type conversion or if it's something that can be avoided.

**Comment by hwu36** [comment]
It is hard to tell without more detail?  It's possible as you said that rounding up/down causes the small difference.  What is your ref?  Could it be your ref's problem?

To figure out the root cause, you need to dump the values after every step.

**Comment by zihaozou** [comment]
For reference, I use the tool offered at https://github.com/NVIDIA/cutlass/blob/25ebf15d02f5a201a44ef6f436939d7f44530eea/tools/util/include/cutlass/util/reference/host/convolution.h

for debugging, is there any tool that can easily dump the GPU allocated memory? compute sanitizer or memcheck can only dump the memory when an error occurs, but there is no error in my case. I am trying to use Cuda-gdb to run to the position where the numerical error was computed, but it is extremely slow to get there.

**Comment by hwu36** [comment]
cutlass host ref code has conversion in the different places than the gpu hw.  it is expected to see small float point difference.  we usually use small int to initialize the data if we want to do bit by bit comparison.  if you use real float point to initialize data, you need to set a epsilon to compare instead of using bit-by-bit.

 https://github.com/NVIDIA/cutlass/tree/master/examples/02_dump_reg_shmem shows how to use some utilities to dump fragment or shared memory (also works for the global memory).

**Comment by zihaozou** [comment]
Thx, 
I tried to use an epsilon in comparison, but some differences even exceed an epsilon of 1e-2. I will further investigate it tomorrow.

**Comment by zihaozou** [comment]
For those who came here with the same issue, this is a bug in CUDA 11.7. To fix it, just update the CUDA to 11.7.1. Nvidia just released its update 1 on CUDA 11.7. In its release note, [it says](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-resolved-issues)
_"During ongoing testing, NVIDIA identified that due to an algorithm error in a very small number of hardest-to-round cases (less than 0.000007% of tested combinations), the results of 64-bit floating-point division in default round-to-nearest-even mode can differ from the IEEE754 standard by 1 least-significant bit in default round-to-nearest-even mode.
Floating-point computations have many sources of error accumulation and most algorithms will not have encountered this discrepancy. NVIDIA recommends that all developers requiring strict IEEE754 compliance update to CUDA Toolkit 11.7 Update 1 or newer.
The affected algorithm is present in both offline compilation as well as just-in-time (JIT) compilation. As JIT compilation is handled by the driver, NVIDIA recommends updating to driver version 515.65.01 when IEEE754 compliance is required and when using JIT.
This is a software algorithm fix and is not tied to specific hardware."_

**Comment by hwu36** [comment]
Thank you for updating us.
