### ISSUE TITLE
[QST] Can CUTLASS be leveraged for a matrix multiply combined with a prefix-sum?

### ISSUE THREAD

**Issue by eaplatanios** [NVIDIA/cutlass#585]
I want to perform the following operation which involves a prefix sum:
```
o_{nhtm} = \sum_i q_{nhti} \sum_{j < t} k_{nhji} * v_{nhjm}
```
In this case, `n` and `h` can both be treated as batch dimensions.

Is this something I could leverage CUTLASS for? And if so, how could I compute it efficiently? I'm very new to CUDA and have no experience with CUTLASS, but for reference, this is my current naive implementation:

```
#define E_BLOCK_SIZE 8

template<typename scalar_t>
using float_accessor = torch::PackedTensorAccessor32<scalar_t, 4, torch::RestrictPtrTraits>;

template<typename scalar_t>
__global__ void causal_dot_product_forward_kernel(
  const float_accessor<scalar_t> q,
  const float_accessor<scalar_t> k,
  const float_accessor<scalar_t> v,
  float_accessor<scalar_t> o,
  const int N,
  const int H,
  const int L,
  const int E,
  const int M
) {
  int n = blockIdx.y;
  int h = blockIdx.z;

  int e_start = blockIdx.x * E_BLOCK_SIZE;
  int m = threadIdx.x % M;

  scalar_t kv[E_BLOCK_SIZE];

  #pragma unroll
  for (int e_local = 0; e_local < E_BLOCK_SIZE; e_local++)
    kv[e_local] = 0;

  for (int t = 0; t < L; t++) {
    scalar_t res = 0;
    #pragma unroll
    for (int e_local = 0; e_local < E_BLOCK_SIZE; e_local++) {
      if (e_start + e_local < E) {
        kv[e_local] += k[n][h][t][e_start + e_local] * v[n][h][t][m];
        res += q[n][h][t][e_start + e_local] * kv[e_local];
      }
    }
    o[n][h][t][m] = res;
  }
}

void causal_dot_product_forward(const torch::Tensor q, const torch::Tensor k, const torch::Tensor v, torch::Tensor o) {
  AT_DISPATCH_FLOATING_TYPES_AND_HALF(q.scalar_type(), "causal_dot_product_forward", [&] {
    torch::DeviceGuard _guard(q.device());
    int N = q.size(0);
    int H = q.size(1);
    int L = q.size(2);
    int E = q.size(3);
    int M = v.size(3);
    dim3 grid_dim((E + E_BLOCK_SIZE - 1) / E_BLOCK_SIZE, N, H);
    dim3 block_dim(M, 1, 1);
    causal_dot_product_forward_kernel<<<grid_dim, block_dim>>>(
      q.packed_accessor32<scalar_t, 4, torch::RestrictPtrTraits>(),
      k.packed_accessor32<scalar_t, 4, torch::RestrictPtrTraits>(),
      v.packed_accessor32<scalar_t, 4, torch::RestrictPtrTraits>(),
      o.packed_accessor32<scalar_t, 4, torch::RestrictPtrTraits>(),
      N, H, L, E, M
    );
  });
}
```

I'm aware that I could potentially leverage shared memory in a smart way that would likely require first transposing my tensors so that the `t` dimension is last, but I'm generally wondering if I could directly leverage CUTLASS to make this efficient without having to worry too much about low-level and architecture-specific details.

Thank you!

**Comment by hwu36** [comment]
cub, thrust, or moderngpu have good prefix sum kernels.  cutlass does not.

**Comment by eaplatanios** [comment]
@hwu36 the operation I want to perform is basically two matrix multiplies where one of them includes this prefix constraint in the terms that get summed. Ideally, I'd like for all of this to be fused and performed in a tiled fashion. Would cub or thrust still be the right answer in this case? I was under the impression that CUTLASS is relevant because of the chained batched matrix multiplies involved in this operation.

**Comment by hwu36** [comment]
i honestly don't have a good idea to do prefix sum and gemm in one kernel.  prefix sum usually requires more than one kernel itself.  Its last step can be fused into cutlass gemm though.

**Comment by eaplatanios** [comment]
That's unfortunate but thanks a lot for your responses @hwu36!
