### ISSUE TITLE
Support basic gemm for unsigned char

### ISSUE THREAD

**Issue by DmiitriyJarosh** [NVIDIA/cutlass#59]
Try to use example of basic gemm with other types: it works if I change float to unsigned int, but produce misaligned address error if i try to use unsigned char. Is it my error or there is no ability to use basic gemm with unsigned char type? 
What I really change can be seen here: [branch unsigned_char of my fork](https://github.com/DmiitriyJarosh/cutlass/tree/unsigned_char)

**Comment by kerrmudgeon** [comment]
Mind trying this out in CUTLASS 2.x?

Note, the "IGEMM" examples are optimized implementations of `s8 * s8 + s32` matrix multiply-adds and may be a good implementation for your use case. Here's a link to the [IGEMM unit tests](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/simt_igemm_nn_sm50.cu#L1191) for example template instances.

If you have access to a Turing architecture GPU, you could try targeting Turing Tensor Cores which greatly accelerate mixed integer matrix operations. Take a look at [08_turing_tensorop_gemm](/examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu).

I'll close this for now. Feel free to re-open if this doesn't address your questions.

Thanks!
