### ISSUE TITLE
[QST]How to make examples/36_gather_scatter_fusion work with all shapes?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#592]
Hello! I try to make [examples/36_gather_scatter_fusion](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion) work with all shapes. It seems that the problem size must be multiples of vectorized memory access in epilogue op and `alignmentA`, `alignmentB` in the `GemmUniversal`. I modify the `alignmentA` and `alignmentB` in the source code. I also modify the vector memory access number in epilogue op. Following is the modification I made:
```C++
using EpilogueOp = cutlass::epilogue::thread::LinearCombination<
    ...
    1,    // <-this is the number of elements per vectorized memory access.
    ...
    >; 
```
```C++
using Gemm = cutlass::gemm::device::GemmUniversal<
                                                  ...
                                                  1,     /*alignmentA*/
                                                  1,     /*alignmengB*/
                                                  ...
                                                 >;
```
And I have some question:

1. Some value for `(vectorized memory access, alignmentA, alignmentB)` seems to be invalid, I set them to (1, 1, 1) and get compile error(the layout is all column major) . Is there some rule I can refer to when setting these value?
2. cutlass seems to have different rule for different layout. I set layout to all row major and (`vectorized memory access`, `alignmentA`, `alignmentB`) to (1, 1, 1), it pass the compilation. But the program doesn't work with all shapes. Is there any thing I miss to make it work for all shapes?

**Comment by hwu36** [comment]
You need to meet the requirements in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L410-L439 which depends on your layouts.  Also, ampere hmma kernels needs at least align2 in the leading dimension for A and B.

I recommend to make your A/B/C leading dimension to be 128bit aligned, otherwise it is not beneficial to use this fused kernel.

**Comment by umiswing** [comment]
@hwu36 Thanks! And does cutlass work correctly with non-128bit-aligned leading dimension matrix? Some error occurs when I test with such shape. If any update is needed in cutlass, I will do some padding to fit the alignment. :)

**Comment by hwu36** [comment]
Should work with small alignment kernels as long as you meet the layout and leading dimension sizerequirements.

**Comment by umiswing** [comment]
@hwu36 so cutlass works for most shapes, and for some shapes that can't meet the requirement, padding could be used to meet the requirement, right?

**Comment by hwu36** [comment]
yes
