### ISSUE TITLE
[QST] How to understand the shape of sm70 warp-level mma?

### ISSUE THREAD

**Issue by cctry** [NVIDIA/cutlass#594]
The mma tensor op of sm70 uses instruction shape of <16,16,4>, but the size of fragment holding one multiplicand is 4. Thus 32 threads requires 128 elements as operand A or B, exceeding the shape 16 x 4. How to understand the layout?

**Comment by hwu36** [comment]
you are asking volta mma ptx 884, not wmma, correct?  in volta mma ptx 884, essentially every 8 threads own a 8x8x4 which is different from turing/ampere.  so every thread has 8x4/8 = 4 elements for A or B.

**Comment by cctry** [comment]
So there are threads in different MMA computation loading the same tile? Could you please point out the code guiding this access pattern?

**Comment by hwu36** [comment]
these two ctors depends on your layout.

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator_sm70.h#L199
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator_sm70.h#L1612

the 1st is for A col, B row
the 2nd is for A row, B col
