### ISSUE TITLE
[QST] Transpose epilogue.

### ISSUE THREAD

**Issue by JamesTheZ** [NVIDIA/cutlass#595]
Does it support transpose operator for CUTLASS epilogue? I want to develop an epilogue with index transformation (e.g., transpose), but am lost in the tile-iterator. Is there some tutorial about the details of the output layout (on shared memory?) and iterator?

For example, it looks like `epilogue::threadblock::DefaultThreadMapTensorOp` describes the output layout information. But I am lost about `using Type = OutputTileOptimalThreadMap`. What does the following code mean?
```
    OutputTileShape<ThreadblockShape::kN, Detail::kTensorOpRows, Detail::WarpCount::kM, 1, 1>,
    OutputTileShape<1, WarpShape::kM / Detail::kTensorOpRows, 1, 1, WarpShape::kM / Detail::kTensorOpRows>,
```
Given block-tile of <128, 128, 32> and warp-tile of <64, 64, 32>, It results in `OutputTileShape<128, 8, 2, 1, 1>` and `OutputTileShape<1, 8, 1, 1, 8>`. I cannot figure out what it means.

**Comment by hwu36** [comment]
we will release epilogue permute in the coming 2.10.

**Comment by JamesTheZ** [comment]
> we will release epilogue permute in the coming 2.10.

Awesome! Is there a planned time when v2.10 will be released?

**Comment by hwu36** [comment]
this month.

**Comment by JamesTheZ** [comment]
> this month.

Thanks! Can't wait.

Is there any explanatory material about epilogue iterator?  I still would like to dig into the details for more customization.
