### ISSUE TITLE
[QST] Does RowMajorTensorOpMultiplicandCongruous support dimension other than 64

### ISSUE THREAD

**Issue by tridao** [NVIDIA/cutlass#599]
It seems `cutlass::layout::RowMajorTensorOpMultiplicandCongruous` only supports `Crosswise=64`?
Is there anyway to load a matrix of shape (128 x 32) from smem?

With the following code I'm running into compiler error:
```
constexpr int kM = 16;
constexpr int kN = 32;
constexpr int kK = 128;
using Shape = cutlass::gemm::GemmShape<kM, kN, kK>;
using InstructionShape = cutlass::gemm::GemmShape<16, 8, 16>;
using Element = cutlass::half_t;
using ElementC = float;
using LayoutA = cutlass::layout::RowMajorTensorOpMultiplicandCrosswise<
    cutlass::sizeof_bits<Element>::value, 64>;
using LayoutB = cutlass::layout::RowMajorTensorOpMultiplicandCongruous<
    cutlass::sizeof_bits<Element>::value, kN>;
using WarpMma = typename cutlass::gemm::warp::DefaultMmaTensorOp<
    Shape, InstructionShape, Element, LayoutA, Element, LayoutB, ElementC,
    cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd, 1, true>::Type;
using LayoutV = typename WarpMma::LayoutB;
```
Error on the last line:
```
/juice2/u/trid/flash-attention/csrc/flash_attn/cutlass/include/cutlass/gemm/warp/mma_tensor_op.h(242): error: incomplete type is not allowed
          detected during:
            instantiation of class "cutlass::gemm::warp::MmaTensorOp<Shape_, ElementA_, LayoutA_, ElementB_, LayoutB_, ElementC_, LayoutC_, Policy_, PartitionsK_, AccumulatorsI
nRowMajor, Enable> [with Shape_=cutlass::gemm::GemmShape<16, 16, 128>, ElementA_=cutlass::half_t, LayoutA_=cutlass::layout::RowMajorTensorOpMultiplicandCrosswise<16, 64>, Eleme
ntB_=cutlass::half_t, LayoutB_=cutlass::layout::RowMajorTensorOpMultiplicandCongruous<16, 16>, ElementC_=float, LayoutC_=cutlass::layout::RowMajor, Policy_=cutlass::gemm::warp:
:MmaTensorOpPolicy<cutlass::arch::Mma<cutlass::gemm::GemmShape<16, 8, 16>, 32, cutlass::half_t, cutlass::layout::RowMajor, cutlass::half_t, cutlass::layout::ColumnMajor, float,
 cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>, cutlass::MatrixShape<1, 1>>, PartitionsK_=1, AccumulatorsInRowMajor=true, Enable=__nv_bool]"
```
If I set `kN = 64`, things work fine. From reading the source [code](https://github.com/NVIDIA/cutlass/blob/497b499d9dfd112e250bb17d31093164ac00ce9e/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L105) my understanding is that `Crosswise` needs to be 64 for this to work?

Context: I'm trying to use Cutlass in [FlashAttention](https://github.com/HazyResearch/flash-attention), and I'm stuck at the step of loading the matrix V from smem to registers: in this case V has the shape (seqlen x head dim), with seqlen=128 and head dim=32. 

Thanks for your help!

Cutlass version: 2.9.1
nvcc: 11.7

**Comment by hwu36** [comment]
Yes, you need to use `Crosswise=64` for your case.  

In the `Congruous` layout, `Crosswise` means how many contiguous elements that you can put in the same row of the cache line of the shared memory which is 128B.  128B is 64 fp16 elements.

K dimension is your leading dimension.  You have 128 elements in your K dimension which can occupy 2 cache lines of the shared memory.

**Comment by tridao** [comment]
Thanks Haicheng.
I'm now trying to construct the smem iterators and WarpMma by constructing MmaCore, but I'm unable to compile when N=32. It compiles fine with N=64.

I'm using 4 warps (128 threads) to multiply matrices 16x128 and 128x32, with sliced-K.
```
using ThreadblockShape = cutlass::gemm::GemmShape<16, 32, 128>;
using WarpShape = cutlass::gemm::GemmShape<16, 32, 32>;
using InstructionShape = cutlass::gemm::GemmShape<16, 8, 16>;
using Element = cutlass::half_t;
using ElementC = float;
using MmaCore = typename cutlass::gemm::threadblock::DefaultMmaCore<
    ThreadblockShape, WarpShape, InstructionShape, Element, cutlass::layout::RowMajor,
    Element, cutlass::layout::RowMajor, ElementC, cutlass::layout::RowMajor,
    cutlass::arch::OpClassTensorOp>;
using WarpMma = typename MmaCore::MmaTensorOp;
```

Error on the last line:
```
/juice2/u/trid/flash-attention/csrc/flash_attn/cutlass/include/cutlass/transform/pitch_linear_thread_map.h(257): error: static assertion failed with "ShapeInAccesses must be divisible by WarpThreadArrangement."
          detected during:
            instantiation of class "cutlass::transform::PitchLinearWarpRakedThreadMap<Shape_, Threads, WarpThreadArrangement_, ElementsPerAccess>::Detail [with Shape_=cutlass::PitchLinearShape<32, 128>, Threads=128, WarpThreadArrangement_=cutlass::PitchLinearShape<8, 4>, ElementsPerAccess=8]"
(291): here
            instantiation of class "cutlass::transform::PitchLinearWarpRakedThreadMap<Shape_, Threads, WarpThreadArrangement_, ElementsPerAccess> [with Shape_=cutlass::PitchLinearShape<32, 128>, Threads=128, WarpThreadArrangement_=cutlass::PitchLinearShape<8, 4>, ElementsPerAccess=8]"
/juice2/u/trid/flash-attention/csrc/flash_attn/cutlass/include/cutlass/transform/threadblock/regular_tile_iterator.h(54): here
            processing of template argument list for "cutlass::transform::threadblock::RegularTileIterator" based on template arguments <cutlass::MatrixShape<128, 32>, cutlass::half_t, cutlass::layout::RowMajorTensorOpMultiplicandCongruous<16, 64>, 0, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::PitchLinearShape<32, 128>, 128, cutlass::PitchLinearShape<8, 4>, 8>>
/juice2/u/trid/flash-attention/csrc/flash_attn/cutlass/include/cutlass/gemm/threadblock/default_mma_core_sm75.h(463): here
            instantiation of class "cutlass::gemm::threadblock::DefaultMmaCore<Shape_, WarpShape_, InstructionShape_, ElementA_, cutlass::layout::RowMajor, ElementB_, cutlass::layout::RowMajor, ElementC_, LayoutC_, cutlass::arch::OpClassTensorOp, 2, Operator_, false, cutlass::arch::CacheOperation::Global, cutlass::arch::CacheOperation::Global, cutlass::ComplexTransform::kNone, cutlass::ComplexTransform::kNone, false> [with Shape_=cutlass::gemm::GemmShape<16, 32, 128>, WarpShape_=cutlass::gemm::GemmShape<16, 32, 32>, InstructionShape_=cutlass::gemm::GemmShape<16, 8, 16>, ElementA_=cutlass::half_t, ElementB_=cutlass::half_t, ElementC_=float, LayoutC_=cutlass::layout::RowMajor, Operator_=cutlass::arch::OpMultiplyAdd]"
```
Seems like by default it constructs a `PitchLinearShape<8, 4>`, but that doesn't work with the matrix B of shape 128 x 32, column major?

**Comment by hwu36** [comment]
This tile size is not what we had in mind when we designed the shared memory iterators.

As you said you need to use `PitchLinearShape<4, 8>`.  4 threads in the contiguous dimension which is N dimension.  Every thread loads 8 elements.  So, 32 elements in N dimension which is your threadblock_n.

You also need to set `Crosswise` in the swizzle layout to be 32 since you have only 32 contiguous data.

You also need to add a partial specialization of `cutlass::layout::TensorOpMultiplicandCongruous<16, 32>` for the shared memory load iterator, its access pattern is similar to https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L1566-L1570.

I may still missing something else.

With all that said, I recommend you use more square-ish and bigger tile size which has better performance because it is more friendly to the memory system.  Cutlass also has better support for these regular tile sizes both functional and performance wise.

**Comment by tridao** [comment]
> You also need to set `Crosswise` in the swizzle layout to be 32 since you have only 32 contiguous data.

Could you say more about which part of cutlass this is?

> You also need to add a partial specialization of cutlass::layout::TensorOpMultiplicandCongruous<16, 32> for the shared memory load iterator

To clarify: I should be using `cutlass::layout::RowMajorTensorOpMultiplicandCongruous<cutlass::sizeof_bits<Element>::value, 32>` and not `cutlass::layout::RowMajorTensorOpMultiplicandCongruous<cutlass::sizeof_bits<Element>::value, 64>`. I'll just need to add the code for the shared memory load iterator to support `Crosswise=32`?

**Comment by hwu36** [comment]
> Could you say more about which part of cutlass this is?

The shared memory layout you need to use is `cutlass::layout::RowMajorTensorOpMultiplicandCongruous<16, 32>`.  Currently, we don't have a partial specialization for it in the shared memory load iterator.  You need to add it yourself.

I just realized that you also need to add shared memory store iterators for `cutlass::layout::RowMajorTensorOpMultiplicandCongruous<16, 32>` in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h.  The logic is similar to https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/transform/threadblock/regular_tile_access_iterator_tensor_op.h#L425-L619 when `Layout::kFactor` is 2.

**Comment by mnicely** [comment]
@tridao Is your issue resolved?

**Comment by tridao** [comment]
Thanks, I've decided to not implement it for dimension 32 for now.
