### ISSUE TITLE
Poor Performance with Int1

### ISSUE THREAD

**Issue by agnusmaximus** [NVIDIA/cutlass#60]
Doing a performance comparison between Int1 (binary gemm) and Sgemm, I'm seeing only a 10x speedup.

Here's what I ran:
```
./cutlass_perf_test --m=1024 --n=32 --k=1024 --kernels=sgemm_nn --iterations=10000
===============================================
[Passed]: sgemm_nn with disposition: passed
Kernel: sgemm_nn
    provider: Cutlass
    problem: 1024-by-32-by-1024, A: column-major, B: column-major, beta: 0, batch: 1
    disposition: passed
    runtime:     0.193089 ms

    performance: 347.553 GFLOPs
```
and
```
./cutlass_perf_test --m=1024 --n=32 --k=32 --kernels=wmma_binary_gemm_tn --iterations=10000
=================================================
[NotVerified]: wmma_binary_gemm_tn with disposition: not_verified
Kernel: wmma_binary_gemm_tn
    provider: Cutlass
    problem: 1024-by-32-by-32, A: row-major, B: column-major, beta: 0, batch: 1
    disposition: not_verified
    runtime:     0.0172656 ms

    performance: 3886.85 GFLOPs
```

In both runs, N=32, M=K=1024 (1024 bits in bgemm, 1024 floats for sgemm).

Comparing the runtimes, we see that binary gemm is only 0.193089/0.0172656 ~ 10x faster than sgemm. I'd expect better performance, somewhere in the 24x - 30x range as operating on bits using popcount should be 32x faster than doing multiply accumulates.

Any idea why this is the case? Appreciate any input here.

**Comment by agnusmaximus** [comment]
Resolved.

**Comment by hwu36** [comment]
CUDA 11.3 significantly improves the performance of Ampere/Turing/Volta Tensor Core kernels. See #241 .

You may want to do the benchmarking again with the latest compiler.
