### ISSUE TITLE
[QST]Cutlass Profiler build issue on Linux

### ISSUE THREAD

**Issue by duli2012** [NVIDIA/cutlass#600]
**What is your question?**
Hi, 

I tried to build cutlass profiler on Linux using the following command:
 cmake .. -DCUTLASS_NVCC_ARCHS='80' -DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_s*fprop_optimized_f16 -DCUTLASS_ENABLE_TESTS=OFF
...
 make cutlass_profiler -j16

 Then I encountered the following errors:
[  5%] Building CUDA object tools/library/CMakeFiles/cutlass_library_objs.dir/src/reference/conv3d.cu.o
cd /mnt/d/repos/cutlass_linux/build/tools/library && /usr/local/cuda-11.7/bin/nvcc  -DCUTLASS_ENABLE_CUBLAS=1 -DCUTLASS_ENABLE_CUDNN=1 -DCUTLASS_NAMESPACE=cutlass -I/mnt/d/repos/cutlass_linux/include -I/mnt/d/repos/cutlass_linux/tools/library/src -I/mnt/d/repos/cutlass_linux/build/tools/library/include -I/mnt/d/repos/cutlass_linux/build/include -I/mnt/d/repos/cutlass_linux/tools/library/include -I/mnt/d/repos/cutlass_linux/tools/util/include  -O3 -DNDEBUG -Xcompiler=-fPIC   -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_TEST_LEVEL=0 -DCUTLASS_TEST_ENABLE_CACHED_RESULTS=1 -DCUTLASS_CONV_UNIT_TEST_RIGOROUS_SIZE_ENABLED=1 -DCUTLASS_DEBUG_TRACE_LEVEL=0 -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_80,code=[sm_80,compute_80] -std=c++11 -x cu -c /mnt/d/repos/cutlass_linux/tools/library/src/reference/conv3d.cu -o CMakeFiles/cutlass_library_objs.dir/src/reference/conv3d.cu.o
make[3]: stat: ../include/cutlass/arch/cache_operation.h: Input/output error
make[3]: *** No rule to make target '../include/cutlass/arch/cache_operation.h', needed by 'tools/library/CMakeFiles/cutlass_library_objs.dir/generated/conv2d/cutlass_tensorop_s1688fprop_optimized_f16_256x128_32x2_nhwc_align8.cu.o'.  Stop.
make[3]: *** Waiting for unfinished jobs....
gcc: error: /mnt/d/repos/cutlass_linux/tools/library/src/reference/conv3d.cu: Input/output error
gcc: warning: ‘-x c++’ after last input file has no effect
gcc: fatal error: no input files
compilation terminated.
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:193: tools/library/CMakeFiles/cutlass_library_objs.dir/src/reference/conv3d.cu.o] Error 1
[  7%] Building CXX object tools/library/CMakeFiles/cutlass_library_objs.dir/generated/initialize_all.cpp.o
cc1plus: fatal error: /mnt/d/repos/cutlass_linux/tools/library/src/reference/initialize_reference_operations.cu: Input/output error
compilation terminated.
[  7%] Building CUDA object tools/library/CMakeFiles/cutlass_library_objs.dir/generated/conv2d/all_conv2d_operations.cu.o
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:141: tools/library/CMakeFiles/cutlass_library_objs.dir/src/reference/initialize_reference_operations.cu.o] Error 1
cd /mnt/d/repos/cutlass_linux/build/tools/library && /usr/bin/c++  -DCUTLASS_ENABLE_CUBLAS=1 -DCUTLASS_ENABLE_CUDNN=1 -DCUTLASS_NAMESPACE=cutlass -I/mnt/d/repos/cutlass_linux/include -I/mnt/d/repos/cutlass_linux/tools/library/src -I/mnt/d/repos/cutlass_linux/build/tools/library/include -I/mnt/d/repos/cutlass_linux/build/include -I/mnt/d/repos/cutlass_linux/tools/library/include -I/mnt/d/repos/cutlass_linux/tools/util/include -isystem /usr/local/cuda-11.7/include  -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/cutlass_library_objs.dir/generated/initialize_all.cpp.o -c /mnt/d/repos/cutlass_linux/build/tools/library/generated/initialize_all.cpp
cd /mnt/d/repos/cutlass_linux/build/tools/library && /usr/local/cuda-11.7/bin/nvcc  -DCUTLASS_ENABLE_CUBLAS=1 -DCUTLASS_ENABLE_CUDNN=1 -DCUTLASS_NAMESPACE=cutlass -I/mnt/d/repos/cutlass_linux/include -I/mnt/d/repos/cutlass_linux/tools/library/src -I/mnt/d/repos/cutlass_linux/build/tools/library/include -I/mnt/d/repos/cutlass_linux/build/include -I/mnt/d/repos/cutlass_linux/tools/library/include -I/mnt/d/repos/cutlass_linux/tools/util/include  -O3 -DNDEBUG -Xcompiler=-fPIC   -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -DCUTLASS_TEST_LEVEL=0 -DCUTLASS_TEST_ENABLE_CACHED_RESULTS=1 -DCUTLASS_CONV_UNIT_TEST_RIGOROUS_SIZE_ENABLED=1 -DCUTLASS_DEBUG_TRACE_LEVEL=0 -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_80,code=[sm_80,compute_80] -std=c++11 -x cu -c /mnt/d/repos/cutlass_linux/build/tools/library/generated/conv2d/all_conv2d_operations.cu -o CMakeFiles/cutlass_library_objs.dir/generated/conv2d/all_conv2d_operations.cu.o
cc1plus: error: /mnt/d/repos/cutlass_linux/build/include: Input/output error
cc1plus: error: /mnt/d/repos/cutlass_linux/tools/library/include: Input/output error
cc1plus: fatal error: /mnt/d/repos/cutlass_linux/build/tools/library/generated/initialize_all.cpp: Input/output error
compilation terminated.
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:206: tools/library/CMakeFiles/cutlass_library_objs.dir/generated/initialize_all.cpp.o] Error 1
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:167: tools/library/CMakeFiles/cutlass_library_objs.dir/src/reduction/init_reduction_operations.cu.o] Error 1
/mnt/d/repos/cutlass_linux/tools/library/src/reference/conv2d.cu:36:10: fatal error: /mnt/d/repos/cutlass_linux/include/cutlass/cutlass.h: Input/output error
   36 | #include "cutlass/cutlass.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:180: tools/library/CMakeFiles/cutlass_library_objs.dir/src/reference/conv2d.cu.o] Error 1
In file included from /usr/local/cuda-11.7/bin/../targets/x86_64-linux/include/cuda_runtime.h:118,
                 from <command-line>:
/usr/local/cuda-11.7/bin/../targets/x86_64-linux/include/crt/device_functions.h:3301:10: fatal error: /mnt/d/repos/cutlass_linux/tools/util/include/surface_functions.h: Input/output error
 3301 | #include "surface_functions.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:219: tools/library/CMakeFiles/cutlass_library_objs.dir/generated/conv2d/all_conv2d_operations.cu.o] Error 1
/mnt/d/repos/cutlass_linux/tools/library/src/handle.cu:39:10: fatal error: /mnt/d/repos/cutlass_linux/tools/library/include/cutlass/library/handle.h: Input/output error
   39 | #include "cutlass/library/handle.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /mnt/d/repos/cutlass_linux/tools/library/src/reduction/reduction_device.cu:36:
/mnt/d/repos/cutlass_linux/tools/library/include/cutlass/library/library.h:59:10: fatal error: /mnt/d/repos/cutlass_linux/tools/library/include/cutlass/library/cutlass/layout/tensor.h: Input/output error
   59 | #include "cutlass/layout/tensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:63: tools/library/CMakeFiles/cutlass_library_objs.dir/src/handle.cu.o] Error 1
compilation terminated.
In file included from /mnt/d/repos/cutlass_linux/include/cutlass/numeric_types.h:88,
                 from /mnt/d/repos/cutlass_linux/tools/library/src/util.cu:35:
/mnt/d/repos/cutlass_linux/include/cutlass/half.h:74:10: fatal error: /mnt/d/repos/cutlass_linux/tools/util/include/cstring: Input/output error
   74 | #include <cstring>
      |          ^~~~~~~~~
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:154: tools/library/CMakeFiles/cutlass_library_objs.dir/src/reduction/reduction_device.cu.o] Error 1
compilation terminated.
make[3]: *** [tools/library/CMakeFiles/cutlass_library_objs.dir/build.make:115: tools/library/CMakeFiles/cutlass_library_objs.dir/src/util.cu.o] Error 1
make[3]: Leaving directory '/mnt/d/repos/cutlass_linux/build'
make[2]: *** [CMakeFiles/Makefile2:1899: tools/library/CMakeFiles/cutlass_library_objs.dir/all] Error 2
make[2]: Leaving directory '/mnt/d/repos/cutlass_linux/build'
make[1]: *** [CMakeFiles/Makefile2:1960: tools/profiler/CMakeFiles/cutlass_profiler.dir/rule] Error 2
make[1]: Leaving directory '/mnt/d/repos/cutlass_linux/build'
make: *** [Makefile:614: cutlass_profiler] Error 2

Could you please help to address this?

Thanks.

Du

**Comment by jackkosaian** [comment]
Hi,

A few questions:

1. Are you running this via WSL?
2. Where is the CUTLASS repository you are trying to build located? Based on this output, it looks like it is under `/mnt/d/`.
3. Does this occur for any CUTLASS build you try to do, or only when building the profiler?

Usually `stat Input/output error` is related to the file system, which is why I asked about (1) and (2) above.

If you are using WSL, but building CUTLASS source that is on a different drive/partition, could you try out putting the CUTLASS source within WSL itself and building?

**Comment by duli2012** [comment]
Thanks a lot, Jack!
Yes, I'm using WSL. Once build cutlass within WSL, problem solved!

I'm closing this issue.
