### ISSUE TITLE
[QST] Is it possible to perform multiple gather-gemm-scatter in one kernel using cutlass?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#601]
Hello! I'm using cutlass to do gather-gemm-scatter fusion (according to [examples/36_gather_scatter_fusion](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion)). My program will generate multiple indices for the same matrix A, B and D, and will perform multiple gather-gemm-scatter in a loop:
```c++
for(i=0;i<indices_num;i++) {
    ...
    typename Gemm::Arguments arguments{
    ...
    a,    // <- reference to matrix A on device
    b,    // <- reference to matrix B on device
    c,    // <- reference to matrix C on device
    d,    // <- reference to matrix D on device
    ...
    a_indices[i],    // <- pointer to index vector to gather A on device
    b_indices[i],    // <- pointer to index vector to gather B on device
    d_indices[i]};   // <- pointer to index vector to scatter D on device
    ...
    status = gemm_op();
    ...
}
```
Is it possible to perform the loop just in one kernel to save kernel launch time using cutlass?

**Comment by hwu36** [comment]
do these index arrays have the same lengths?  if so, you can use batch gemm array to do it.  otherwise, you can use group gemm method.

**Comment by umiswing** [comment]
@hwu36 These index arrays have different lengths. I read the header file of group gemm([cutlass/gemm/device/gemm_grouped.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_grouped.h) and [cutlass/gemm/kernel/gemm_grouped.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_grouped.h)), but it seems that cutlass's group gemm doesn't provide gather-scatter fusion in these two header? Could you point me to the source code I should reference to?

**Comment by hwu36** [comment]
you need to add them yourself.  just some plumbing work.
