### ISSUE TITLE
[QST] How to set tile size for fp64 in examples/36_gather_scatter_fusion?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#612]
Hello! I'm trying to make [examples/36_gather_scatter_fusion](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion) works for fp64. ```A```,```B```,```C``` and ```D``` are all fp64 and row major, with a shape of ```(m,n,k)=(4,4,4)```, and ```index_size=2```.
I found [examples/18_ampere_fp64_tensorop_affine2_gemm](https://github.com/NVIDIA/cutlass/tree/12f4108ac2233022b92f0e3533c23bed399fcf45/examples/18_ampere_fp64_tensorop_affine2_gemm) and set a tile size same as this example:
```c++
// This code section describes the tile size a thread block will compute
using ShapeMMAThreadBlock = cutlass::gemm::GemmShape<128, 128, 16>; 
// This code section describes tile size a warp will compute
using ShapeMMAWarp = cutlass::gemm::GemmShape<32, 64, 16>; 
// This code section describes the size of MMA op
using ShapeMMAOp = cutlass::gemm::GemmShape<8, 8, 4>; 
```
But a complication error occur:
```shell
/home/me/cutlass/include/cutlass/transform/threadblock/predicated_tile_access_iterator.h(353): error: static assertion failed with "Vectors implied by the thread map must be divisible by the access type."
          detected during:
            instantiation of class "cutlass::transform::threadblock::PredicatedTileAccessIterator<Shape_, Element_, cutlass::layout::PitchLinear, AdvanceRank, ThreadMap_, AccessType_, Gather> [with Shape_=cutlass::layout::PitchLinearShape<16, 128>, Element_=double, AdvanceRank=0, ThreadMap_=cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::layout::PitchLinearShape<16, 128>, 256, cutlass::layout::PitchLinearShape<16, 2>, 1>, AccessType_=cutlass::Array<double, 2, true>, Gather=true]" 
```
According to #566, I guess may be I should set the tile size to half of the tile size for fp32, so I set the tile size as:
```c++
using ShapeMMAThreadBlock =
    cutlass::gemm::GemmShape<128, 128, 8>; 
// This code section describes tile size a warp will compute
using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 64, 8>; 
// This code section describes the size of MMA op
using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 4>;
``` 
But a similar complication error occur. :(

What tile size works for fp64? Are there any rules I can refer to to set the correct tile size? By the way, is it possible to change tile size to accelerate?

**Comment by jackkosaian** [comment]
Hi,

The example should work with type `double` if you change `AlignmentA` and `AlignmentB` [here ](https://github.com/NVIDIA/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu#L255-L256)to be 1 each.

\- Jack

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu#L227 also needs to be 1.  We only support align1 for fp64, the same as cublas.

You can find plausible tile sizes in https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L3055-L3067

Tile size can change the performance significantly.

**Comment by umiswing** [comment]
@jackkosaian @hwu36 Hi! I change ```AlignmentA```, ```AlignmentB``` and https://github.com/NVIDIA/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu#L227 to 1. But I still can't compile it with type ```double```.
The error occur:
```shell
/home/me/cutlass/include/cutlass/gemm/warp/mma_tensor_op_policy.h(58): error: incomplete type is not allowed
          detected during:
            instantiation of class "cutlass::gemm::warp::MmaTensorOpPolicy<Operator_, OpDelta_> [with Operator_=cutlass::arch::Mma<ShapeMMAOp, 32, double, cutlass::layout::RowMajor, double, cutlass::layout::ColumnMajor, double, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>, OpDelta_=cutlass::MatrixShape<1, 1>]" 
...
```
Here is my environment:
GPU: GeForce RTX 3060 Mobile / Max-Q
OS: Ubuntu 22.04
nvcc version: V11.3.58
driver version: 515.65.01

**Comment by hwu36** [comment]
check this unit test: https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_f64n_f64t_f64t_tensor_op_f64_sm80.cu#L58-L77

**Comment by umiswing** [comment]
Thanks! It works now. :)
