### ISSUE TITLE
[BUG] Wrong result in integer matrix multiply on ampere

### ISSUE THREAD

**Issue by pchelaa** [NVIDIA/cutlass#619]
**Describe the bug**
When I multiply two identity matrices in int8 on A100 I get wrong result.

**Steps/Code to reproduce bug**
To reproduce run `examples/08_turing_tensorop_gemm` with the following patch
https://gist.github.com/pchelaa/2eed3fccf2b10324f4927e8978c2f17e

It prints https://gist.github.com/pchelaa/492d2fd3a35b7376dcc4b2b5e1e711da

I am using partial specialization of gemm for Ampere Integer Matrix Multiply Interleaved layout https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/default_gemm.h#L335. It seems to me that the layout of matrix B is wrong in it. If I store data in B according to CuBlasLt layout CUBLASLT_ORDER_COL32_2R_4R4 instead of RowMajorInterleaved<32> (but still pass `LayoutB=RowMajorInterleaved<32>` to gemm configuration) I get correct result.

**Comment by hwu36** [comment]
Yep, you figured out almost everything.

The trick is that the B matrix needs to be preprocessed.  You can check this unit test https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/multistage_testbed_interleaved.h#L151-L152
