### ISSUE TITLE
[QST] Question on GTC talk [s31883] Accelerating Convolution with Tensor Cores in CUTLASS

### ISSUE THREAD

**Issue by donglinz** [NVIDIA/cutlass#621]
Dear,

I have some questions on the slides of GTC talk s31883: Accelerating Convolution with Tensor Cores in CUTLASS

On page 9, should we swap the variable s and r since r is the position along filter height and s is the position along filter width?
<img width="784" alt="image" src="https://user-images.githubusercontent.com/12831220/189141615-372f4de4-d28a-4165-9f70-4cdcddf85c0c.png">

On page 12, should crs_residue be npq_residue, as it's calculating index for the output matrix? :
<img width="425" alt="image" src="https://user-images.githubusercontent.com/12831220/189141825-96b9dd81-e2e2-4ce1-af5b-7bbf07ce280f.png">

On page 13, same here, should crs_residue be npq_residue? :
<img width="320" alt="image" src="https://user-images.githubusercontent.com/12831220/189142215-3ee94167-bd09-4589-ac89-a85e0cb3f55a.png">

The talk link: https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s31883/

Thank you!

**Comment by manishucsd** [comment]
Hi @donglinz , 

Thank you for pointing this out. Yes, you are correct. Also, see here: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_analytic.h#L245

I don't see this error propagated further say slide 13. 

>> On page 12, should crs_residue be npq_residue, as it's calculating index for the output matrix? :
Yes, you are correct here as well. Apologies, for the typo and the confusion. 

@hwu36 and @kerrmudgeon is there a way to make these corrections in the [gtcspring21-s31883/](https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s31883/) link?

**Comment by donglinz** [comment]
Thanks for the clarification.

**Comment by donglinz** [comment]
@manishucsd Sorry I have an additional question regarding 23.
The RSC dimension of conv forward seems to be iterated in the order of c/32-r-s-32 according to page 23:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/12831220/190991647-b3df7cb0-b088-4488-aa62-fb5e275d41bd.png">

But on page 15, the iteration order seems to be r-s-c (from slowest changed to fasted changed):
<img width="394" alt="image" src="https://user-images.githubusercontent.com/12831220/190992620-fd851409-8c96-4f80-9b7b-96def0d553fe.png">

I understand the accumulation order on implicit gemm K dimension does not impact correctness. So is this a performance consideration?
