### ISSUE TITLE
[QST] Is it possible to set optimal tile size automatically?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#625]
Hello! I use cutlass in my program. To get the best performance, I do a performance test for each tile size in the [generator.py](https://github.com/NVIDIA/cutlass/blob/b72cbf957df8cf84a6d0ff91c190ad51a9c1d24a/tools/library/scripts/generator.py) to find the optimal one. However, an optimal tile size for the current shape may be the poor tile size for other shapes, and an optimal tile size for the current hardware may be the poor tile size for other hardware. I can't do performance tests for every shape and every hardware. Is it possible to set optimal (or at least nearly optimal) tile size automatically when a new shape or new hardware occurs?

**Comment by hwu36** [comment]
This is a hard problem and there is no easy way around.  You can either profile to pick the best one, or you can run many problem sizes to train a heuristics to pick it for you.
