### ISSUE TITLE
[QST]Any one successfuly compile from pytorch implementation?

### ISSUE THREAD

**Issue by twmht** [NVIDIA/cutlass#640]
**What is your question?**
Hi,

I am trying to compile from https://github.com/MegEngine/cutlass/tree/master/examples/19_large_depthwise_conv2d_torch_extension

But failed from 

![image](https://user-images.githubusercontent.com/1567200/192077307-8cdfdc6a-d7b0-427b-8e2b-f0e1503d573b.png)

Appreciate from any help.

**Comment by hwu36** [comment]
It would be better ask Megvii, not us.  The convolution in their fork is different from ours.  We introduced our first depth wise conv in 2.10 (https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/depthwise_fprop_implicit_gemm_f16nhwc_f16nhwc_f16nhwc_simt_f16_sm60.cu).  We will have a better one in 2.11.

**Comment by twmht** [comment]
Is the depth wise conv introduced from 2.10 optimized for large kernel size (> 7x7) ?

**Comment by hwu36** [comment]
yup. the 2.11 optimized is targeting small filter sizes.

**Comment by twmht** [comment]
thank you. this would help.

**Comment by hwu36** [comment]
add @Ethan-Yan27
