### ISSUE TITLE
[QST] Why keeping `col_permute_` and `row_permute_` as class member in `permute.h`

### ISSUE THREAD

**Issue by Enter-tainer** [NVIDIA/cutlass#644]
**What is your question?**

`col_permute_` and `row_permute_` can be uniquely determined by the input coordinate. They are private, and not being read by any other member functions. It seems that there is no need to store them in the layout class. I think they should be local variables.

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/permute.h#L75-L76

Is there any special concern for keeping them?

**Comment by hwu36** [comment]
You are correct.  They can be local variables.  PR is very welcome.
