### ISSUE TITLE
[BUG] dgrad conv error

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/cutlass#651]
when trying the new pycutlass with below command:

`
python conv2d.py -i 16 8 16 -ta float16 -tb float16 -tc float16 -tacc float32 -m multiply_add -op TensorOp -b 128 128 32 -s 3 -w 2 2 1 -cc 80 -la TensorNHWC -aa 4 -lb TensorNHWC -ab 4 -lc TensorNHWC -ac 4 -te float32 -ep LinearCombination -sw StridedDgradIdentitySwizzle1 -co dgrad -st Strided -ia optimized -sm Serial -k 1 -nhwc 1 256 480 90 -krsc 45 2 2 90 -pad 1 1 1 1 -stride 2 2 -dilation 1 1 -alpha 1.0 -beta 0.0
`

it report error as below, does it mean this shape is not supported by dgrad conv?

`
Traceback (most recent call last):
  File "conv2d.py", line 306, in <module>
    arguments.sync()
  File "/opt/conda/lib/python3.8/site-packages/PyCutlass-0.0.1-py3.8-linux-x86_64.egg/pycutlass/conv2d_operation.py", line 237, in sync
    return super().sync()
  File "/opt/conda/lib/python3.8/site-packages/PyCutlass-0.0.1-py3.8-linux-x86_64.egg/pycutlass/arguments.py", line 112, in sync
    raise RuntimeError("CUDA Error %s" % str(err))
RuntimeError: CUDA Error cudaError_t.cudaErrorMisalignedAddress
`

**Comment by hwu36** [comment]
Your A needs to be align2, your B needs to be align1.  your C needs to be align1.  You can consider to pad your channel to be multiple of 8.  Then you can use align8 everywhere.  Big alignment has much better perf than small alignment.

cc @apuaaChen

**Comment by leiwen83** [comment]
I see. Thx for your reply.
