### ISSUE TITLE
[QST] Support for Jetson AGX Xavier (Compute Capability 72)

### ISSUE THREAD

**Issue by Mluckydwyer** [NVIDIA/cutlass#655]
**What is your question?**

According to the [official Nvidia documentation](https://developer.nvidia.com/embedded/jetson-agx-xavier), the Nvidia Jetson AGX Xavier contains 64 Tensor Cores and has a [CUDA compute capability](https://developer.nvidia.com/cuda-gpus) of 7.2 (72). Yet, when consulting the [CUTLASS functionality documentation](https://github.com/NVIDIA/cutlass/blob/master/media/docs/functionality.md), there is no mention of computing capability 7.2. It is my understanding that CUTLASS should allow for non-Tensor Core implementations to be compiled for this GPU, but there should also be support for the Tensor Core accelerated operations, correct?

Thank you in advance for your assistance. I am just trying to better understand the Tensor Core GEMM library support for Tensor Core-enabled Nvidia Jetson products.

**Comment by hwu36** [comment]
if i remember it correctly, sm72 supports fp16 mma 884 and int8 mma 8816.  However, we only have imma8816 kernels that use `ldmatrix` that is introduced in sm75.  so, only cutlass hmma884 tensor core kernels can run on sm72 now.

**Comment by Mluckydwyer** [comment]
So the primary issues for Cutlass support is the limited data types for the sm72 tensor Cores and the absence of the `ldmatrix` instruction? The matrix can be pre-loaded into shared memory as well, correct? Would that avoid the need of the `ldmatrix` if done manually?

Also, what would be the best way to double check specific support for the AXG Xavier platform? Would the Cutlass tests provided fail if they are not supported (if they compile at all)?

Thank you again!

**Comment by hwu36** [comment]
> Would that avoid the need of the ldmatrix if done manually?
correct.

> what would be the best way to double check specific support for the AXG Xavier platform? 
google it.  the white paper should have the info.

**Comment by Mluckydwyer** [comment]
Thanks for the help. For "AGX Xavier support", I was specifically referring to Cutlass. Is there a Cutlass white paper I am missing? Some searching just turns up the documentation here, some additional blog posts, and academic papers.

**Comment by hwu36** [comment]
cutlass only supports simt kernels and hmma.884 on sm72.

**Comment by Mluckydwyer** [comment]
Alright, thanks!
