### ISSUE TITLE
Run Multiple Gemm Kernels Concurrently

### ISSUE THREAD

**Issue by HenryYihengXu** [NVIDIA/cutlass#66]
Hello! I'm reading the basic_gemm.cu example. I'm trying to run multiple gemm kernels concurrently by calling Gemm::launch(params) multiple times, but it does not seem to work.

I think I have to allocate a stream for each kernel, but I didn't find how to do that. Does anybody have any suggestions on how to run multiple kernels concurrently? Thanks!

**Comment by kerrmudgeon** [comment]
The device-level API in CUTLASS 2.0 accepts a cudaStream_t as one argument (which defaults to null). If specified, this should be a handle to the CUDA stream into which the GEMM kernel is launched. It is also the stream into which related tasks such as a semaphore clearing operation or a reduction kernel are queued.

Here's a reference to the CUDA Runtime API for managing streams.
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM

For examples, consider the CUDA SDK Examples such as "0_Simple/simpleCudaGraphs" described by the [CUDA SDK release notes](https://docs.nvidia.com/cuda/cuda-samples/index.html#new-features).

These are great places to get started, and they are expected to work well with CUTLASS 2.0.

I'll close this issue, but feel free to reopen it if you continue to have problems.

Thanks!
