### ISSUE TITLE
[DOC] Small Typo in batched gemm

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA/cutlass#660]
## Report incorrect documentation

**Location of incorrect documentation**

[batched_gemm](https://github.com/NVIDIA/cutlass/blob/master/examples/05_batched_gemm/batched_gemm.cu#L97)

**Describe the problems or issues found in the documentation**
It should be `batch_stride_A` not `batch_stride_C`

**Comment by mnicely** [comment]
Shipping in 2.11
