### ISSUE TITLE
[QST] How to instantiate only GemmUniversal when building Profiler?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#663]
Hello! I want to find the best GEMM tiling for some input shapes with cutlass's profiler. According to https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md, I execute the following to instantiate all tile sizes.
```shell
$ cmake .. -DCUTLASS_NVCC_ARCHS="70;75;80" -DCUTLASS_LIBRARY_KERNELS=all  -DCUTLASS_UNITY_BUILD_ENABLED=ON
...
$ make cutlass_profiler -j
``` 
But it takes a very long time to build.
I found https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/gemm_operation.py and the ```EmitGemmUniversalInstance``` is all I need. Is there any way to instantiate only GemmUniversal to save building time?

**Comment by hwu36** [comment]
you can use regexp to reduce the number of kernels.  For example, `-DCUTLASS_LIBRARY_KERNELS=*gemm*` only instantiate gemm, or `-DCUTLASS_LIBRARY_KERNELS=*s*gemm*` only instantiate gemm accumulated in fp32.

**Comment by umiswing** [comment]
@hwu36 Thanks! I I run ```cmake .. -DCUTLASS_NVCC_ARCHS="70;75;80" -DCUTLASS_LIBRARY_KERNELS=*gemm* -DCUTLASS_UNITY_BUILD_ENABLED=ON``` and ```make cutlass_profiler``` to instantiate all gemm kernel. 
Then I execute ```./tools/profiler/cutlass_profiler --operation=gemm --m=4002 --n=32 --k=32 --A=f32:row --B=f32:row --C=f32:row --alpha=1 --beta=0 --output=result.csv``` to find the best kernel for my input with [m, n, k]=[4002, 32, 32], all matrices are fp32 and row-major. But none of the kernels is launched. It seems no kernel supports the input with all matrices being row-major. Is there any way to generate kernels support this input? By the way, I actually want to find the best kernel to perform the [gather-gemm-scatter](https://github.com/NVIDIA/cutlass/tree/master/examples/36_gather_scatter_fusion) fusion. Will the best kernel for gemm be the optimal one for gather-gemm-scatter fusion?

**Comment by hwu36** [comment]
> Will the best kernel for gemm be the optimal one for gather-gemm-scatter fusion

Yes.

cutlass profiler only has column major output which is the same as cublas.  to run A:row x B:row -> C:row in the profiler, you can do B:col x A: col -> C: col.  you need so swap `m` and `n` size.

I noticed that all input and output data are fp32.  before ampere, you will launch simt ffma kernels.  on ampere, you will launch simt ffma, tf32x1 tensor core, tf32x3 tensor core kernels.  simt ffma is true fp32 kernel, but it is the slowest.  tf32x1, tf32x3 will use tf32 tensor core to emulate fp32.  tf32x1 is faster but less accurate, tf32x3 is more close to true fp32 but slower.

**Comment by umiswing** [comment]
@hwu36 Thank you. I do ```./tools/profiler/cutlass_profiler --operation=gemm --m=32 --n=4001 --k=32 --A=f32:col --B=f32:col --C=f32:col --alpha=1 --beta=0 --output=result.csv``` and find some fast kernels. But some of these kernels do a transpose again, they calculate B: col x A: col -> C: col in a row-major way (A: row x B: row -> C: row). I am a bit confused about how to pass the arguments. Assuming I want to calculate A: row x B: row -> C: row of shape [m, n, k] with these kernels, should I swap `A` and `B` , `m` and `n` or just keep the order since these kernels do a transpose again?

Following is the kernel picked by the profile tool. I add the ```gather A``` and ```scatter D``` in the template arguments. I guess swapping `A` and `B`, `m` and `n` is the correct way to use this kernel since I get a cutlass misaligned error with [m, n, k] = [4001, 32, 32].
<details>

```c++
  using GemmKernel = typename cutlass::gemm::kernel::DefaultGemmUniversal<
          float,
          cutlass::layout::RowMajor,
          cutlass::ComplexTransform::kNone,
          4,
          float,
          cutlass::layout::RowMajor,
          cutlass::ComplexTransform::kNone,
          4,
          float,
          cutlass::layout::RowMajor,
          float,
          cutlass::arch::OpClassTensorOp,
          cutlass::arch::Sm80,
          cutlass::gemm::GemmShape<256, 64, 16>,
          cutlass::gemm::GemmShape<64, 64, 16>,
          cutlass::gemm::GemmShape<16, 8, 8>,
          cutlass::epilogue::thread::LinearCombination<float, 4, float, float>,
          cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
          4,
          cutlass::arch::OpMultiplyAddFastF16,
          cutlass::gemm::SharedMemoryClearOption::kNone,
          true, // Should I set gather A here?
          false,
          true>::GemmKernel;
  using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;
```
</details>

**Comment by umiswing** [comment]
@hwu36 Would you give this issue a check? By the way, I try to use ```GemmUniversal``` instead of ```GemmUniversalAdapter``` according to #611, keeping the settings picked by the profiler. But it seems to get slower, the performance is different from the ```GemmUniversalAdapter```

**Comment by hwu36** [comment]
256 x 64 looks like a good choice for your 4002x32 problem sizes.  your k is super small, so it is memory bound and suppose to have large variance from run to run.  Do you lock the frequency and power to reduce the variance? Hot cache can also impact the performance measurement.

**Comment by hwu36** [comment]
`GemmUniversal` and `GemmUniversalAdapter` map to the same kernel level code.  so they should have the same perf.  you can compare the ptx to see if they have any material difference.

**Comment by umiswing** [comment]
@hwu36 Thank you! I want to confirm that is it ok to search for the best kernel for A: row x B: row -> C: row in a col-major way: B: col x A: col -> C: col? Just switch m and n when profiling.

**Comment by hwu36** [comment]
yes.  you can double check by printing out the layout and dimension from cutlass.  in the kernel level (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L476), you should see m=4002, n=32, k=32.  and all layouts are row major.

**Comment by umiswing** [comment]
> yes. you can double check by printing out the layout and dimension from cutlass. in the kernel level (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L476), you should see m=4002, n=32, k=32. and all layouts are row major.

Thank you! I will double-check my code.
