### ISSUE TITLE
[QST] What is the rule to set tile size?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#664]
Hello! I am trying to find the best tile size for an input shape ```[m, n, k]``` = ```[220480, 32, 32]``` of fp32 on 3060 GPU. It seems that https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L2314-#L2385 doesn't contain all the tile sizes I can try. I try some tile sizes beyond the generator.py  and have some questions:
1. Why do some tile sizes fail in complication? For example, ```ThreadBlock = [128, 32, 32]; Warp=[64, 32, 16], MMA=[16, 8, 8]``` can pass the complication but ```ThreadBlock = [128, 32, 32]; Warp=[64, 16, 32], MMA=[16, 8, 8]``` fails.
2. My input shape is ```[m, n, k]``` = ```[220480, 32, 32]```, does the tile size with bigger m_tile and smaller n_tile and k_tile has the better performance? Should I make n_tile and k_tile smaller than 32 to avoid some threads being free?

**Comment by hwu36** [comment]
the code you mentioned above is for ampere fp16 input gemm, not fp32.

not all tile sizes are supported.  The common ones are already listed in the code you mentioned.

> My input shape is [m, n, k] = [220480, 32, 32], does the tile size with bigger m_tile and smaller n_tile and k_tile has the better performance? Should I make n_tile and k_tile smaller than 32 to avoid some threads being free?

You are basically correct.  If your C is column major, cutlass will do below transformation automatically, A x B = C:col => B' x A' = C:row.  In this case, you would want m and k tile size to be smaller.  You can just set `-DCUTLASS_LIBRARY_KERNELS=*s*gemm*_f16*align8` to try all supported tile sizes.  I suspect some sm75 kernel will work better for your case.

**Comment by umiswing** [comment]
Thank you :)
