### ISSUE TITLE
Change threadblock tile size of Gemm kernel

### ISSUE THREAD

**Issue by HenryYihengXu** [NVIDIA/cutlass#67]
Hello! I'm reading the basic_gemm.cu example and I'm trying to change the threadblock tile size for the kernel. But I'm not sure where is the right place to change, as the kernel is encapsulated so tight. I tried to change the "cutlass::Shape<8, 128, 128>" in the GemmTraits, but it doesn't compile.

Does anybody have any suggestion on changing the threadblock size of the gemm kernel? Thanks

**Comment by kerrmudgeon** [comment]
Please note that CUTLASS 2.x (November 2019) substantially revises the old codebase.

Here's a unit test verifying [SGEMM for a large 128x128x8 tile size](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/simt_sgemm_nn_sm50.cu#L1193).

Many of the template arguments have sensible defaults, so you should be able to declare an SGEMM operator as follows.

```c++
using ThreadblockShape = cutlass::gemm::GemmShape<128, 128, 8>;
using WarpShape = cutlass::gemm::GemmShape<64, 32, 8>;

using Gemm = cutlass::gemm::device::Gemm<
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::RowMajor,
    float,
    cutlass::arch::OpClassSimt,
    cutlass::arch::Sm50,
    ThreadblockShape,
    WarpShape
>;
```

Changing the `ThreadblockShape` to some integer multiple of the warp shape should yield favorable results.  Here's a 128x32x8 configuration:

```c++
using ThreadblockShape = cutlass::gemm::GemmShape<128, 32, 8>;
using WarpShape = cutlass::gemm::GemmShape<64, 32, 8>;

using Gemm = cutlass::gemm::device::Gemm<
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::ColumnMajor,
    float, cutlass::layout::RowMajor,
    float,
    cutlass::arch::OpClassSimt,
    cutlass::arch::Sm50,
    ThreadblockShape,
    WarpShape
>;
```

You could substitute this definition into the [00_basic_gemm SDK example](/examples/00_basic_gemm/basic_gemm.cu) to try it out.

Thanks!
