### ISSUE TITLE
[BUG] `23_ampere_gemm_operand_reduction_fusion` wrong results when `LayoutOutput=RowMajor`

### ISSUE THREAD

**Issue by danthe3rd** [NVIDIA/cutlass#674]
**Repro**
(1) Change this line in example 23:
```c++
using LayoutOutput = cutlass::layout::ColumnMajor;
```
with:
```c++
using LayoutOutput = cutlass::layout::RowMajor;
```
(2) Test with
```bash
$ make 23_ampere_gemm_operand_reduction_fusion && ./examples/23_ampere_gemm_operand_reduction_fusion/23_ampere_gemm_operand_reduction_fusion --perf-check --ref-check --m=2736 --n=1536 --k=9456
[100%] Building CUDA object examples/23_ampere_gemm_operand_reduction_fusion/CMakeFiles/23_ampere_gemm_operand_reduction_fusion.dir/ampere_gemm_operand_reduction_fusion.cu.o
[100%] Linking CUDA executable 23_ampere_gemm_operand_reduction_fusion
[100%] Built target 23_ampere_gemm_operand_reduction_fusion
ERROR - results miscompared.
ID,M,N,K,SplitK-Slices,Parallel-SplitK,Runtime
gemm_1,2736,1536,9456,1,0,0.371661
```

**More info**
There are some typos I think in the templates, like here, where `ReduceKForA_` is passed as the `PartitionsK` argument
https://github.com/NVIDIA/cutlass/blob/8c1bf9b784a7878b20fef673892f0a1d769fd94c/include/cutlass/gemm/threadblock/default_mma_core_with_reduction.h#L154-L156

https://github.com/NVIDIA/cutlass/blob/8c1bf9b784a7878b20fef673892f0a1d769fd94c/include/cutlass/gemm/warp/default_mma_with_reduction_tensor_op.h#L46-L70

From my runs, it looks like it's actually reducing the operand B instead of A
**setup**
I'm on 4db6a6140e45c4ffe6339c55b43b159602fa1f35

**Comment by hwu36** [comment]
please check #682

**Comment by mnicely** [comment]
@danthe3rd did you have any luck resolving your issues?

**Comment by danthe3rd** [comment]
It's working now with @hwu36 's PR! Thanks a lot - closing the issue
