### ISSUE TITLE
[QST] How do you initialize matrix with host tensor? 

### ISSUE THREAD

**Issue by sungwooahn** [NVIDIA/cutlass#678]
I'm studying about CUTLASS and I can't find a way to initialize a host tensor with my matrix.
Here is my situation.

Let say I have a matrix of input_h[m][n] and input_d[m][n] in host and device memory space. The data value in those are identical.
How can I make a host tensor with any of those sources or put in my values after creating a blank host tensor?

I looked for various ways.
First, tensor_fill.h do not have functions for me because it only fills with same value(TensorFIll()) or some random or Gaussian series.
My case is that I have result matrix on my own and I want to use it.

Second, I found way to access the host tensor array with host_view.ref() function. But, this method requires me to sweep through all elements in matrix for just copying operation. I'm looking for way to just copy the starting address and not copying element single by single.

Third, I tried to first make the TensorRef or TensorView with my "input" matrix. This was successful.
However, I cannot find way to connect this TensorRef or TensorView object to Host Tensor object.
All function calls inside host tensor object cannot be written. (like A.device_data() is for getting the pointer, and can not overwrite it).

In this circumstance, can you give me some help with using CUTLASS with my "input" matrix?
I think there should be a way to use it but I'm missing a very easy and bold and big point. But, can't find it for three days. Please, help me out.

**Comment by hwu36** [comment]
The only thing cutlass needs is a device pointer to the tensor and the strides of every dimensions.  You just need to first initialize your device array in any way you want (e.g. copy from a host array), and second create a `TensorRef` by using this device array pointer and strides.  That is it.  You can then call cutlass kernels upon this `TensorRef`.  You don't have to use `HostTensor` which is convenient in many situations but is not the most efficient in memory management.

**Comment by mnicely** [comment]
@sungwooahn are your questions answered?
