### ISSUE TITLE
cutclass failed to build due to error : Could not detect active GPU device ID with MSVC on windows. 

### ISSUE THREAD

**Issue by spacelg** [NVIDIA/cutlass#68]
cutclass failed to build due to error : Could not detect active GPU device ID with MSVC on windows.  It can be first reproduced on fb335f6 reversion. Could you please help take a look at this? 

Repro Steps:
1. git clone https://github.com/NVIDIA/cutlass d:\Cutclass\src
2. open a clean x64 prompt and browse to D:\CutClass
3. mkdir build_x64 && pushd build_x64
4. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCUTLASS_NVCC_ARCHS=70 ..\src\
5. msbuild /p:Configuration=Release;Platform=x64 CUTLASS.sln /t:Rebuild

[log_x64_build.log](https://github.com/NVIDIA/cutlass/files/3873065/log_x64_build.log)

Error info:
CUSTOMBUILD : *** error : Could not detect active GPU device ID [CUDA driver version is insufficient for CUDA runtime version] [D:\cutclass\build_x64\test\unit\core\test_unit_core.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code -1073741515. [D:\cutclass\build_x64\test\unit\nvrtc\thread\test_unit_nvrtc_thread.vcxproj]

**Comment by d-k-b** [comment]
Hi @spacelg , can you give the installed CUDA driver and toolkit you are using? Also, please attach the output of running CMake.

**Comment by kerrmudgeon** [comment]
Note, I think the next step would be to assess whether your CUDA driver and Toolkit are appropriate and compatible. The recourse would be to install the CUDA 10.2 Toolkit and driver.

https://developer.nvidia.com/cuda-downloads

That may help resolve this telling part of your error report.
`Could not detect active GPU device ID [CUDA driver version is insufficient for CUDA runtime version]`

**Comment by spacelg** [comment]
Hi @d-k-b , Thanks for your reply. Our CUDA Version 10.1.168. Please check the log_x64_cmake.log file in attachment. 

Thanks,
Lin

[log_x64_cmake.log](https://github.com/NVIDIA/cutlass/files/3890470/log_x64_cmake.log)

**Comment by spacelg** [comment]
Hi, @kerrmudgeon , Thanks for your info, I will try CUDA 10.2 later. If works, I will close this ticket.

Thanks,
Lin

**Comment by spacelg** [comment]
Hi, @kerrmudgeon, I download the cuda_10.2.89_win10_network.exe and install. This issue still exits. 
[log_x64_build.log](https://github.com/NVIDIA/cutlass/files/3891110/log_x64_build.log)
[log_x64_cmake.log](https://github.com/NVIDIA/cutlass/files/3891113/log_x64_cmake.log)

And when it fails, there will be a popup box like the following:
The program can't start because nvcuda.dll is missing from your computer. Try reinstalling the program to fix problem.

Do I need to download the exe (local) version?

Thanks,
Lin

**Comment by kerrmudgeon** [comment]
It still sounds like a CUDA Toolkit or driver installation problem. 

I would certainly try the local installer if you haven't yet.

**Comment by QuellaZhang** [comment]
@kerrmudgeon , this issue still exists on NVIDIA CUDA Toolkit 10.2.89 (or NVIDIA CUDA Toolkit 10.2.89.20191206) +MSVC, any suggesstions or workarounds for this?
