### ISSUE TITLE
[FEA] Single Softmax example

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#681]
Hi, I noticed that in new release there is a gemm_softmax example. Is there any example for a single Softmax op?

**Comment by hwu36** [comment]
We don't have one.  I think oneflow has a good one.

**Comment by mnicely** [comment]
@TUMSchieben did you find the oneflow example?

**Comment by TUMSchieben** [comment]
> @TUMSchieben did you find the oneflow example?

Ah yes, I've found it. Thx and I'm wondering if there is any plan that CUTLASS would add such example.

**Comment by hwu36** [comment]
We don't have such a plan at the moment.  oneflow one is pretty good as far as i can tell.
