### ISSUE TITLE
[QST] Does cutlass's gather-gemm-scatter fusion support transpose on intput A?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#684]
Hello! I want to perform a gather-gemm-scatter fusion on ```transpose(A:row) x B:row -> C:row```. ```gatherA``` and ```gatherB``` are both true and ```scatterC``` is false. I can't find an API to transpose input A. I know that just switching the shape [m, k] of input A and setting laytoutA to col-major will transpose A. However, according to https://github.com/NVIDIA/cutlass/blob/master/examples/36_gather_scatter_fusion/gather_scatter_fusion.cu#L55-L57, not all combination are legal. I'm not sure will this be valid input. What's the legal combination?

**Comment by hwu36** [comment]
My understanding is that what you really want to do is A:col x B: row.  If you don't do anything to C, you can select the whole columns from A and select the whole rows from B.
