### ISSUE TITLE
[QST] Does align1 kernel support gather-gemm-scatter fusion?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#686]
I pick an align1 kernel generated by the profiler but get CUDA misaligned address error when using this align1 kernel to do gather-gemm fusion. I'm not sure if there is anything wrong with the input, but the kernel works well with just gemm. Does align1 kernel support gather-gemm-scatter fusion?
Following is the kernel definition, I set GatherA and GatherB to true and set ScatterD to false when launching the kernel:
```c++
template <bool GatherA, bool GatherB, bool ScatterD>
struct cutlass_tensorop_h1688gemm_64x64_32x2_nt_align1 {
  using Gemm = cutlass::gemm::device::GemmUniversal<
      cutlass::half_t,
      cutlass::layout::ColumnMajor,
      cutlass::half_t,
      cutlass::layout::RowMajor,
      cutlass::half_t,
      cutlass::layout::RowMajor,
      cutlass::half_t,
      cutlass::arch::OpClassTensorOp,
      cutlass::arch::Sm75,
      cutlass::gemm::GemmShape<64, 64, 32>,
      cutlass::gemm::GemmShape<32, 32, 32>,
      cutlass::gemm::GemmShape<16, 8, 8>,
      cutlass::epilogue::thread::
          LinearCombination<cutlass::half_t, 1, cutlass::half_t, cutlass::half_t>,
      cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
      2,
      1,
      1,
      cutlass::arch::OpMultiplyAdd,
      cutlass::ComplexTransform::kNone,
      cutlass::ComplexTransform::kNone,
      GatherA,
      GatherB,
      ScatterD>;
};
```

**Comment by hwu36** [comment]
for the tensor core kernels, align1 is very bad for the performance. simply padding to align8 is better than fusing gather.  Due to this, I don't support small alignment kernels in gather fusion.

**Comment by umiswing** [comment]
Thank you! I will give padding to align8 a try!
