### ISSUE TITLE
[BUG]Invoked sm75-specific memory operator on NVIDIA A100

### ISSUE THREAD

**Issue by yz-chen18** [NVIDIA/cutlass#687]
**Describe the bug**
I'm new around cutlass and trying to run some examples on A100, I assigned the architecture to be sm_80 invoking a gemm of fp16xfp16 -> fp16, but it seems that it always gives me the below error at runtime

/include/cutlass/arch/memory_sm75.h:208: void cutlass::arch::ldsm(cutlass::Array<unsigned int, MatrixCount, true> &, const void *) [with Layout = cutlass::layout::RowMajor; int MatrixCount = 4]: block: [1,0,0], thread: [127,0,0] Assertion `0 && __PRETTY_FUNCTION__` failed.

, which I assume to be invoking the memory operator of the wrong architecture. 

**Steps/Code to reproduce bug**
#include <cutlass/numeric_types.h>
#include <cutlass/gemm/device/gemm.h>

#include <cutlass/util/host_tensor.h>

int main() {

  // Define the GEMM operation
  using Gemm = cutlass::gemm::device::Gemm<
    cutlass::half_t,                           // ElementA
    cutlass::layout::ColumnMajor,              // LayoutA
    cutlass::half_t,                           // ElementB
    cutlass::layout::ColumnMajor,              // LayoutB
    cutlass::half_t,                           // ElementOutput
    cutlass::layout::ColumnMajor,              // LayoutOutput
    float,                                     // ElementAccumulator
    cutlass::arch::OpClassTensorOp,            // tag indicating Tensor Cores
    cutlass::arch::Sm80                        // tag indicating target GPU compute architecture
    >;

  Gemm gemm_op;
  cutlass::Status status;

  //
  // Define the problem size
  //
  int M = 512;
  int N = 256;
  int K = 128;

  float alpha = 1.25f;
  float beta = -1.25f;

  //
  // Allocate device memory
  //

  cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> A({M, K});
  cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> B({K, N});
  cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> C({M, N});

  cutlass::half_t const *ptrA = A.device_data();
  cutlass::half_t const *ptrB = B.device_data();
  cutlass::half_t const *ptrC = C.device_data();
  cutlass::half_t       *ptrD = C.device_data();

  int lda = A.device_ref().stride(0);
  int ldb = B.device_ref().stride(0);
  int ldc = C.device_ref().stride(0);
  int ldd = C.device_ref().stride(0);
  //
  // Launch GEMM on the device
  //

  cudaEvent_t st, ed;
  float time;
  cudaEventCreate(&st);
  cudaEventCreate(&ed);

  cudaEventRecord(st);
 
  status = gemm_op({
    {M, N, K},
    {ptrA, lda},            // TensorRef to A device tensor
    {ptrB, ldb},            // TensorRef to B device tensor
    {ptrC, ldc},            // TensorRef to C device tensor
    {ptrD, ldd},            // TensorRef to D device tensor - may be the same as C
    {alpha, beta}           // epilogue operation arguments
  });
  cudaEventRecord(ed);
  cudaEventSynchronize(st);
  cudaEventSynchronize(ed);
  cudaEventElapsedTime(&time, st, ed);

  if (status != cutlass::Status::kSuccess) {
    return -1;
  }

  printf("TFLOPS: %.4f\n", 2.0 * M * N * K / time / 1e9);

  return 0;
}

**Expected behavior**
Produces a rough estimation of TFLOPS, but fails at runtime

**Additional context**
CMakeLists.txt

find_package(CUDA)

cuda_add_executable(main main.cu)

set(CUDA_NVCC_FLAGS "-std=c++11 --ptxas-options=-v -use_fast_math -ccbin g++ -arch=compute_80 -code=sm_80 -expt-relaxed-constexpr")

target_include_directories(main PRIVATE "../../include")
target_include_directories(main PRIVATE "../../tools/util/include")

target_link_directories(main PRIVATE "./")

**Comment by hwu36** [comment]
i need to see everything after device::gemm

**Comment by yz-chen18** [comment]
> i need to see everything after device::gemm

Sorry for that, I've updated the code in the original comment

**Comment by hwu36** [comment]
https://github.com/NVIDIA/cutlass/blob/012c62c748bdd5b2badc3ebe83e0891dee7c4e31/test/unit/gemm/device/gemm_f16n_f16n_f32n_tensor_op_f32_sm80.cu#L57

You can set things to be the same as this unit test.

**Comment by yz-chen18** [comment]
> https://github.com/NVIDIA/cutlass/blob/012c62c748bdd5b2badc3ebe83e0891dee7c4e31/test/unit/gemm/device/gemm_f16n_f16n_f32n_tensor_op_f32_sm80.cu#L57
> 
> You can set things to be the same as this unit test.

int main() {
  using ElementOutput = float;
  using ElementAccumulator = float;

  // Define the GEMM operation
  using Gemm = cutlass::gemm::device::Gemm<
      cutlass::half_t, cutlass::layout::ColumnMajor, cutlass::half_t,
      cutlass::layout::ColumnMajor, ElementOutput, cutlass::layout::ColumnMajor,
      ElementAccumulator, cutlass::arch::OpClassTensorOp, cutlass::arch::Sm80,
      cutlass::gemm::GemmShape<128, 256, 64>,
      cutlass::gemm::GemmShape<64, 64, 64>, cutlass::gemm::GemmShape<16, 8, 16>,
      cutlass::epilogue:: thread::LinearCombination<
          ElementOutput, 128 / cutlass::sizeof_bits<ElementOutput>::value,
          ElementAccumulator, ElementAccumulator>,
      cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>, 3>;

  Gemm gemm_op;
  cutlass::Status status;

  //
  // Define the problem size
  //
  int M = 512;
  int N = 256;
  int K = 128;

  float alpha = 1.25f;
  float beta  = -1.25f;

  //
  // Allocate device memory
  //

  cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> A({M, K});
  cutlass::HostTensor<cutlass::half_t, cutlass::layout::ColumnMajor> B({K, N});
  cutlass::HostTensor<float, cutlass::layout::ColumnMajor> C({M, N});

  cutlass::half_t const *ptrA = A.device_data();
  cutlass::half_t const *ptrB = B.device_data();
  float const *ptrC = C.device_data();
  float       *ptrD = C.device_data();

  int lda = A.device_ref().stride(0);
  int ldb = B.device_ref().stride(0);
  int ldc = C.device_ref().stride(0);
  int ldd = C.device_ref().stride(0);
  //
  // Launch GEMM on the device
  //

  cudaEvent_t st, ed;
  float time;
  cudaEventCreate(&st);
  cudaEventCreate(&ed);

  cudaEventRecord(st);
 
  status = gemm_op({
    {M, N, K},
    {ptrA, lda},            // TensorRef to A device tensor
    {ptrB, ldb},            // TensorRef to B device tensor
    {ptrC, ldc},            // TensorRef to C device tensor
    {ptrD, ldd},            // TensorRef to D device tensor - may be the same as C
    {alpha, beta}           // epilogue operation arguments
  });
  cudaEventRecord(ed);
  cudaEventSynchronize(st);
  cudaEventSynchronize(ed);
  cudaEventElapsedTime(&time, st, ed);


  if (status != cutlass::Status::kSuccess) {
    return -1;
  }

  printf("TFLOPS: %.4f\n", 2.0 * M * N * K / time / 1e9);

  return 0;
}

no, it still produces the same error on A100

**Comment by hwu36** [comment]
Can you run that unit test?

**Comment by hwu36** [comment]
Or just build that unit test

**Comment by yz-chen18** [comment]
the uint test seems to run fine

**Comment by yz-chen18** [comment]
I've confirmed that it is a pure cmake problem, nothing to do with cutlass. sorry for that
