### ISSUE TITLE
[QST] Why did OutputTileOptimalThreadMap::initial_offset() change from CUTLASS_HOST_DEVICE to CUTLASS_DEVICE

### ISSUE THREAD

**Issue by aadulla** [NVIDIA/cutlass#689]
In this PR (https://github.com/NVIDIA/cutlass/pull/615), the attributes of OutputTileOptimalThreadMap::initial_offset() were changed from CUTLASS_HOST_DEVICE to CUTLASS_DEVICE. What was the reason for this change when all of the other *::initial_offset() methods kept CUTLASS_HOST_DEVICE attribute?

**Comment by aadulla** [comment]
Thank you for your quick response! Yes, I see the `__shfl`. My question was moreso as to why this was introduced compared to what was previously there before to calculate the `int warp_idx = thread_idx / kWarpSize;`. What is the reason for the `__shfl_sync` as I assume every thread will still be doing the division but only thread 0 will do the broadcast to all other threads?

**Comment by hwu36** [comment]
nvcc likes to see `__shfl` more than simple division.

**Comment by aadulla** [comment]
Hi, wanted to follow up on this thread. I compiled this `__shfl_sync` sequence and saw that in the PTX every thread still does the divide (in this case a `shr` by 5) and then they do the `shfl.sync.idx` instruction. Could you please clarify what exactly you mean by "nvcc likes to see `__shfl` more than simple division."

**Comment by hwu36** [comment]
It is a preferred way for nvcc to compute warp id by using shfl.
