### ISSUE TITLE
Eigenvector from device code

### ISSUE THREAD

**Issue by sheshappanavar** [NVIDIA/cutlass#69]
Is there a library function in cutlass which can be invoked from the device code to calculate eigenvector from a covariance matrix?

**Comment by kerrmudgeon** [comment]
There are no matrix factorization implementations in CUTLASS. There are however optimized implementations in the [NVIDIA cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html#eig_examples) library which may satisfy your application's needs.

**Comment by sheshappanavar** [comment]
@kerrmudgeon Thanks for the update. I am aware of the NVIDIA cuSolver library. However, the invocation of cuSolver from the device code is [not supported](https://devtalk.nvidia.com/default/topic/1024278/cuda-programming-and-performance/can-a-cuda-kernel-call-cublas-function-or-how-to-call-a-cublas-functions-from-python-/post/5402425/#5402425) since CUDA 10.0

Please correct me if I am wrong. I am looking for alternative ways to calculate eigenvectors from the device code.

Appreciate your work. Thanks

**Comment by tingxueronghua** [comment]
It seems that the link you provided is about cuBLAS? Anyway, I really want to know how you solve the problem at last because I am in a simlilar dilemma...
