### ISSUE TITLE
[BUG] ASM instruction error

### ISSUE THREAD

**Issue by renderist** [NVIDIA/cutlass#690]
**Describe the bug**
On line 454 of include/cutlass/arch/memory.h, the asm instruction ld.shared.v4.u32 looks like it should be a std.shared.v4.u32.
Appears to be a copy and paste error.

**Steps/Code to reproduce bug**
Visual inspection, the function is shared_store<16>(), so would expect it to have a store instruction instead of a load instruction.

**Additional context**
Appears in current Public facing GitHub repository.

**Comment by hwu36** [comment]
yes, you are right.  we will fix in the next release.  thank you.

**Comment by renderist** [comment]
Just curious, is that function being called at all in your tests?

On Nov 7, 2022, at 8:51 PM, Haicheng Wu ***@***.***> wrote:

﻿

yes, you are right. we will fix in the next release. thank you.

**Comment by hwu36** [comment]
no, this one is not needed in real kernels.  so it is not tested.

**Comment by mnicely** [comment]
Fixed in 2.11
