### ISSUE TITLE
[FEA] Split-K mode for group-gemm?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#692]
**Is your feature request related to a problem? Please describe.**
I use cutlass to accelerate backward of sparse convolution. The calculation of d_kernel could be faster with group-gemm. However, the input shape has large k and tiny m and n.
**Describe the solution you'd like**
Split-K mode for group-gemm.

I read https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_grouped and find group-gemm does not support split-k mode. I am trying to add the split-k mode myself (following the implementation in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h) and have some questions:
1. Would Split-K mode works for group-gemm? Would the parallel on the dimension K cause high occupancy and slow down the kernel?
2. Is it challenging to add split-k mode in group-gemm? If it takes a long time to add it myself, I will use the universal gemm to accelerate my backward op first.

**Comment by hwu36** [comment]
> Would Split-K mode works for group-gemm? Would the parallel on the dimension K cause high occupancy and slow down the kernel?

Split-K and group-gemm are both targeting to saturate gpu when M and N are too small to saturate the GPU.  In many cases, you just need one of them.  However, when some of the gemms in the group gemm have larger K, you can split K for these gemms and probably get some extra speedup.

> Is it challenging to add split-k mode in group-gemm?

It is not hard to hard split-K.  If you check kernel level gemm_universal, you can find that split-k just adds some code before and after the mainloop.  Note, we will start rolling out streamk in coming 2.11.  You can check our GTC 22 fall talk about it.  It is a more general version of split-k.

**Comment by umiswing** [comment]
Thank you! I will try to add it myself first. :)
