### ISSUE TITLE
[BUG] Poor Performance in fused gather/scatter GEMM on Turing

### ISSUE THREAD

**Issue by Straw1239** [NVIDIA/cutlass#693]
The example 36_gather_scatter_fusion has very poor performance on Turing: on a 2060 Max-Q, it got 3 TFlop/s, 4 after modifying one of the input matrices to be row major. This is far below even the non-tensor-core throughput of the GPU.

The profiler reports very low utilization, and lots of time spent waiting for uncoalesced loads. There's no evidence of a thermal issue, and the test is too short for the temperature to increase significantly.

To reproduce, modify gather_scatter_fusion.cu as specified in the comments for Turing, then run it, with all size parameters 2048.

Profiler output:

![Screenshot from 2022-11-09 17-50-11](https://user-images.githubusercontent.com/7179467/200912535-adfe7a24-442b-48d8-beec-2e33ba49620d.png)

 - Environment location: Arch Linux, Bare Metal

**Comment by hwu36** [comment]
do you see STACK usage when calling `cuobjdump --dump-resource-usage`?

would you please show the code?

**Comment by Straw1239** [comment]
Oh, I do see stack usage. And, when I compile with the build system instead of nvcc directly, the resulting executable no longer has the stack usage, and achieves 13TFlop/s. My rough estimate of the peak fp16 matmul with fp32 accumulate performance is 19TFlop/s, is this close enough, with the additional gather overhead, to be considered resolved? I think it was mostly the stack issue.

The code itself is example 36 in the repo, with minimal modifications to run on Turing.

Thank you!
