### ISSUE TITLE
[QST] Question about mma_tensor_op_tile_iterator_wmma.h

### ISSUE THREAD

**Issue by xiuyangleiasp** [NVIDIA/cutlass#694]
In class MmaTensorOpWmmaMultiplicandTileIterator, the function operator++() is compute byte_offset with: **byte_offset_ += (elements_offset * sizeof_bits<Element>::value) / 8;** in[L485](https://github.com/NVIDIA/cutlass/blob/06eb90cc0daae633b1e25e80ace1ef81ac158baa/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator_wmma.h#L485)

but in the function operator--(), compute byte_offset with: **byte_offset_ -= (elements_offset + sizeof_bits<Element>::value) / 8;** in[L496](https://github.com/NVIDIA/cutlass/blob/06eb90cc0daae633b1e25e80ace1ef81ac158baa/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator_wmma.h#L496)

the operator++() compute with multiply, but operator() compute with add, Why?

https://github.com/NVIDIA/cutlass/issues/694#tasklist-block-2f067f5e-b73f-48f9-ad3b-0c32edbb020b

**Comment by hwu36** [comment]
I think `operator--()` is wrong.  No kernel actually uses `operator--()` from any iterator.  We can fix in next release.

**Comment by mnicely** [comment]
Fixed in 2.11
