### ISSUE TITLE
[QST] Support for Ada Lovelace Architecture

### ISSUE THREAD

**Issue by VarunMohan** [NVIDIA/cutlass#695]
It was mentioned that the 40 series has access to the Hopper transformer engine. What is the timeline for adding cutlass support for Ada hardware. I noticed that the TransformerEngine [project](https://github.com/NVIDIA/TransformerEngine) also does not have support yet as well.

**Comment by hwu36** [comment]
Ada is sm89, still ampere class chip.  Existing cutlass ampere kernels should just work as long as you use sm89 in the cmake.

**Comment by VarunMohan** [comment]
It was stated that Ada could perform computations in fp8. I was wondering when that would be available on Cutlass

**Comment by hwu36** [comment]
@mnicely

**Comment by mnicely** [comment]
Hi @VarunMohan, excited to see your interest in CUTLASS and our new hardware. We are still finalizing our roadmap and will get back to you shortly. Do you mind providing any insight to your requirements and use case?

**Comment by VarunMohan** [comment]
Hi @mnicely, I wanted to try out some fp8 computations on the 40 series before we could get access to hardware in the Hopper generation.

**Comment by ankan-ban** [comment]
Another use case: The Leela chess zero project (https://lczero.org/) is also waiting for FP8 support to be available on Ada GPUs. They use custom inference code written in Cuda (and using cublas library) and there is interest in trying out cutlass to get access to new Ada features.

**Comment by oscarbg** [comment]
also interested on fp8 Ada cutlass support..

**Comment by mnicely** [comment]
Ada FP8 support available through cuBLAS (GEMMs) and cuDNN (CONVs).

**Comment by jiguanglizipao** [comment]
Does cutlass have any plan to support FP8 GEMMs on Ada Lovelace GPUs?

**Comment by mnicely** [comment]
Yes, in early 2024.

**Comment by oscarbg** [comment]
@mnicely nice.. any limitations/diffs on FP8 support for Ada vs Hopper? I say because cuDNN has doesn't expose FP8 support on Ada as broadly as on Hopper (intentionally/artificially or not I don't know)..

**Comment by mnicely** [comment]
None come to me off the top of my head. And cuDNN's limitations are not intentional. Its functionality is being extended to Ada. I am also the PM for cuDNN. Email me directly and let me know what's missing that you need.

**Comment by oscarbg** [comment]
@mnicely Hi thanks for info.. nice to hear, no HW FP8 limitations on Ada and also CUDNN being extended for Ada to achieve Hopper feature parity.. really no urgent need for anything just tested some of the FP8 samples from cudnn-frontend project (https://github.com/NVIDIA/cudnn-frontend/tree/main/samples) around half a year ago upon purchase of a Ada GPU:
some codes have/had checks like:
fp8_sample.cpp:
"Fusion with fp8 inputs is only supported on Hopper or later"
fp8_flash_mha_sample.cpp:
"Run FP8 BERT Flash Attention: Sample requires Hopper or above GPU"

**Comment by oscarbg** [comment]
@mnicely please don't get angry, as this is probably not the place to ask and would be better to ask you via email as you pointed out, but since this is a simple question, I ask directly:
 another place (lib) missing FP8 support is cuSPARSELt project, it's missing FP8 support (and also Hopper support but has Ada support)..
seems strange as it's perhaps the most "natural" lib to expose support for the new "FP8 Tensor Core"..
side note: perhaps, assuming FP4 support coming in next GPUs "soon"(seeing: https://www.opencompute.org/blog/amd-arm-intel-meta-microsoft-nvidia-and-qualcomm-standardize-next-generation-narrow-precision-data-formats-for-ai) hope FP4 support gets integrated more "easily" once all libs catch up with FP8 support..
