### ISSUE TITLE
[BUG]`arch/arch.h` should be self contained

### ISSUE THREAD

**Issue by Enter-tainer** [NVIDIA/cutlass#709]
**Describe the bug**

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/arch.h uses the macro `CUTLASS_DEVICE`, but does not include `cutlass/cutlass.h`. Users should therefore ensure that `cutlass/cutlass.h` is included before `cutlass/arch/arch.h`.

This can cause problems when the IDE automatically sorts the include order. This can cause `arch.h` appear before `cutlass.h`, resulting in compile errors.

**Expected behavior**

I'm not sure if this behavior is intended or not. I think it should include `cutlass/cutlass.h` so it is self-contained. I can open a PR and fix this if it is desired.

**Comment by hwu36** [comment]
you are correct.  feel free to open a PR.
