### ISSUE TITLE
CMAKE fails if directories have spaces

### ISSUE THREAD

**Issue by gb-esat** [NVIDIA/cutlass#71]
Many thanks for cutlass--I am just getting started but it looks ideal.

I had trouble with cmake when the installation directory had spaces in the path. (In my case, "OneDrive - Company Name"). I believe the problem is here:

https://github.com/NVIDIA/cutlass/blob/master/CUDA.cmake#L209

It seems that cmake interprets the spaces in the path as delimiters. In my case, it failed when it couldn't find "-" above.

When I moved to a path without spaces, it was fine (Visual Studio 2019, community edition).

Thanks!

**Comment by kerrmudgeon** [comment]
Thank you for the report. We will work on this issue.

**Comment by d-k-b** [comment]
Can you please retry with the latest code, we fixed a few issues related to spaces in paths. Reopen if you encounter more problems, thanks!
