### ISSUE TITLE
[BUG] conv3d cutlass_profiler performence testing doesnt show any output

### ISSUE THREAD

**Issue by ligit520** [NVIDIA/cutlass#710]
There is no output when testing the performance of conv3d using cutlass2.10 and cutlass2.11 's cutlass_profiler testing tools. I don't know whether one of my steps went wrong.
Hardware environment ：Tesla V100
Software environment：cuda11.8
run code:
./cutlass_profiler --operation=Conv3d --n=32 --d=16 --h=14 --w=14 --c=8 --k=64 --t=3 --r=3 --s=3 --pad_d=1 --pad_h=1 --pad_w=1 --stride_d=1 --stride::h=1 --stride::w=1 --dilation_d=1 --dilation::h=1 --dilation::w=1 --conv_kind=fprop

Compile command:
cmake .. -DCUTLASS_NVCC_ARCHS=70 -DCUTLASS_LIBRARY_OPERATIONS=conv3d -DCUTLASS_ENABLE_CUDNN=OFF
make cutlass_profiler -j

**Comment by jackkosaian** [comment]
The kernels that can be profiled by the profiler are generated through the [generator.py](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py) script when `cmake` is run. At present, this script does not generate Conv3d kernels for SM70. This can be seen by taking a look at the[ `GenerateSM70_TensorOp_884`](https://github.com/NVIDIA/cutlass/blob/master/tools/library/scripts/generator.py#L967-L1035) function, which does emit GEMM and Conv2d kernels, but not Conv3d kernels.

If you'd like to generate Conv3d fprop kernels as well, you can add the following line [here ](https://github.com/NVIDIA/cutlass/blob/c975e2ccbb2dbf13024568b37ffa3498ed0b3aed/tools/library/scripts/generator.py#L1021) and [here](https://github.com/NVIDIA/cutlass/blob/c975e2ccbb2dbf13024568b37ffa3498ed0b3aed/tools/library/scripts/generator.py#L1036):
```python
CreateConv3dOperator(manifest, LayoutType.TensorNDHWC, tile_descriptions, data_type, 8, conv_kinds=[ConvKind.Fprop])
```

Note that you will need to rerun your `cmake` command to generate these kernels. If successful, you should see kernels populated under `build/tools/library/generated/conv3d/ `.

If you then rerun `make cutlass_profiler -j`, the profiler should be built with these kernels.

**Comment by ligit520** [comment]
@mnicely I tried to follow Jack's response, but it went wrong in `cmake .. -DCUTLASS_NVCC_ARCHS=70 -DCUTLASS_LIBRARY_OPERATIONS=conv3d -DCUTLASS_ENABLE_CUDNN=OFF`

The cmake error is ：CMake Error at tools/library/CMakeLists.txt:110 (message):
  Error generating library instances.

It seems that the CUTLASS2.11 cutlass_profiler test tool does not support SM70  Conv3D profiler now.

**Comment by ligit520** [comment]
Thanks for your response. I tried follow Jack's advice . Conv3d Fprop and Wgrad cutlass profiler are OK. But somthing wrong with Dgrad when `make` .

**Comment by hwu36** [comment]
@manishucsd , do we support dgrad3d on volta?

**Comment by ligit520** [comment]
I tried to add line ` CreateConv3dOperator(manifest, LayoutType.TensorNDHWC, tile_descriptions, data_type, 8, conv_kinds=[ConvKind.Dgrad])`  in L1021 and  L1036 . But it generates many errors when `make` . 
The make log is 
[make_log.txt](https://github.com/NVIDIA/cutlass/files/10128998/make_log.txt)

**Comment by manishucsd** [comment]
I don't see `conv3d_dgrad*sm70.cu` in unit tests, that means I never tried. I put it in the unit test before enabling it in the profiler. If it is not in the unit tests, we have not tried it. I recommend enabling it in the unit test first, probably some missing default template.
