### ISSUE TITLE
[QST] dimension of A matrix in implict GEMM doc

### ISSUE THREAD

**Issue by ijpq** [NVIDIA/cutlass#711]
**What is your question?**
is it supposed [NPQ, RSC] dimension of A matrix rather [NHW, RSC]? "A is a row-major matrix of extent NHW-by-RSC containing activations" indicated in https://github.com/NVIDIA/cutlass/blob/master/media/docs/implicit_gemm_convolution.md

**Comment by hwu36** [comment]
you can understand it as npq.  what really happens is that it loads from nhw tensor, but only npq is inbound.

**Comment by mnicely** [comment]
@ijpq is your questions answered?

**Comment by ijpq** [comment]
yes, thanks a lot.
