### ISSUE TITLE
[QST] INT8 matmul layout (again!)

### ISSUE THREAD

**Issue by david-macleod** [NVIDIA/cutlass#718]
**What is your question?**

Similar questions have been asked previously but I am still slightly confused.

- According to this https://github.com/NVIDIA/cutlass/issues/349 we can use either TN ordered inputs i.e. `row_major`/`col_major` or interleaved, which I presume is `col32`/`col32_2r_4r4` and references the two options here from the cuBLASLt docs. **Is this correct**?
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/17232877/205379717-0ed8c9e4-b42b-4866-a3c9-c2f6296b7557.png">

- However this https://github.com/NVIDIA/cutlass/issues/619 suggests that we have to use the interleaved layouts to get the correct result 

If it is the case that we can use `row_major`/`col_major` order to use int8 tensor cores on Ampere GPUs, why would anyone choose to use the more convoluted interleaved layouts? Are there performance implications dependent on the approach?

**Comment by david-macleod** [comment]
@hwu36 do you happen to know if we would expect the interleaved version to be faster than row major?

**Comment by hwu36** [comment]
As to kernel itself, interleaved is slightly faster.  The benefit will gradually be gone when the problem size grows.  You can use cutlass profiler (https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md) to try them.  However, interleaved layout requires pre process the input matrix B by reordering its columns.  So, if you want to take some adventure to try the interleaved layout, you need to think about the whole picture to see if you can get end-to-end speedup.

**Comment by david-macleod** [comment]
Thanks!
