### ISSUE TITLE
Suggestion for quickstart document

### ISSUE THREAD

**Issue by gb-esat** [NVIDIA/cutlass#72]
Hi. 

Thanks for your good work documenting CUTLASS. In the section about integrating with other applications [0], I think a minimal CMakeLists.txt would be very helpful. 

Thanks!

Gary

[0] https://github.com/NVIDIA/cutlass/blob/master/media/docs/quickstart.md#using-cutlass-within-other-applications

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-64

**Comment by joeylitalien** [comment]
+1, I would really appreciate it because I cannot get this to work whatever I try.

**Comment by Peter9606** [comment]
I've been reading cutlass doc and source code for couple of weeks, but still don't get it. I'm thinking it probably because 1) too many use of compilation time concept 2) there are many "shape"s, which might not be easily understood without pictures.
So my suggestion is will you please add more figures to help people to understand the concept and your design?

**Comment by hwu36** [comment]
CUTLASS is a header library.  Essentially just need to include all the header files and compile with one nvcc line

`nvcc  -Ipath_to_/cutlass/include -Ipath_to_/cutlass/examples/common -Ipath_to/build/include -Ipath_to/cutlass/tools/util/include -isystem=path_to/cuda/include  -O3 -DNDEBUG -Xcompiler=-fPIE   -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1  -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -gencode=arch=compute_75,code=[sm_75,compute_75] -std=c++11 -x cu -c path_to_cu -o path_to_binary`

You can try below command to see an example

`make 08_turing_tensorop_gemm VERBOSE=1`

**Comment by hwu36** [comment]
@Peter9606 , below two GTC talks should be helpful

https://developer.nvidia.com/gtc/2020/video/s21745-vid
https://on-demand.gputechconf.com/gtc/2018/presentation/s8854-cutlass-software-primitives-for-dense-linear-algebra-at-all-levels-and-scales-within-cuda.pdf

Most of the complication comes from address calculation.  Dumping the load/store addresses from the device can help you understand.

examples/03_visualize_layout is also a tool help you visualize the layout for you.

If you could let me know your goal (such as tensor core or not, sm number, data type, mainloop or epilogue, etc.), I can give you more specific help.

**Comment by Peter9606** [comment]
@hwu36  The slides from GTC2020 really helps. Thank you!

Actually I'm thinking of leveraging cutlass to efficiently move memory between GMEM, SMEM and registers and accelerate computing on CUDA cores regards to deep learning, because cutlass is decomposable.  Sure, I'll pop up specific question.

**Comment by hwu36** [comment]
the link i send out includes 2020 video and 2018 slides.

2018 slides talks more about the overview of the gemm computation in cuda.  2020 video focuses more on tensor core computations.
