### ISSUE TITLE
[QST] How to synchronize cutlass gemm in python?

### ISSUE THREAD

**Issue by lichangh20** [NVIDIA/cutlass#737]
Hello all, I want to use cutlass gemm api in python to speed up my program, so I use pybind11 and convert the gemm into a package in python. Now I want to test the speed of gemm package in python, and my test program is like the following:
```python
for i in range(50):
    time2 = time.time()
    matrix_multi = cutlass_gemm_cuda_core.mmul(A，B)    
    time3 = time.time()
    self.time_gemm += time3 - time2
```
in which A is a {M,K} matrix, B is a {K,N} matrix, and cutlass_gemm_cuda_core is my cutlass_gemm_api. Besides, there are also some other operands in the loop.

My question is that : I notice that the step of gemm is not synchronized, so when the program arrives at the step of time3,  the gemm operation is actually not finished yet, and the time is not accurate, so how can I synchronize the gemm operation in python?(like torch.cuda.synchronize in torch)

Many thanks!

**Comment by mnicely** [comment]
Yes. You can use torch or cupy sync functions. Note, those device syncs which may impact performance. Using streams, or even events, are much more lightweight.
