### ISSUE TITLE
[QST]Compilation issue of cutlass profiler

### ISSUE THREAD

**Issue by Harunokaze** [NVIDIA/cutlass#740]
Hello! I have read about compiling cutlass profiler tutorial on [https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md](url). But I still don't understand how to use "--kernels" to restricted set of kernels, like: 

**How can I restrict "--kernels" so that only GEMMs related to cuda core are compiled?**

Thank you!

**Comment by jackkosaian** [comment]
Hi, @Harunokaze.

The `--kernels` argument is used at *execution time* by the CUTLASS profiler to determine which kernels to execute; it does not control which kernels will be emitted and built within the `cutlass_profiler` binary itself.

Control over which kernels are compiled comes through CUTLASS's CMake system using the ` -DCUTLASS_LIBRARY_KERNELS` flag with `cmake`. See if the instructions [here ](https://github.com/NVIDIA/cutlass#building-a-subset-tensor-core-gemm-kernels) help, and feel free to post a follow up if you still have questions.

For your specific case of targetting SIMT-only (CUDA core) GEMMs, you could use ` -DCUTLASS_LIBRARY_KERNELS=*simt*gemm*`. You can list which kernels are emitted by the CMake system (and, thus, which will be compiled when calling `make cutlass_profiler`) by listing the contents of the `tools/library/generated` directory (from within the directory in which you called `cmake`). For the case of GEMMs, these will be under `tools/library/generated/gemm/`, specifically.

**Comment by mnicely** [comment]
@Harunokaze are your issues resolved?
