### ISSUE TITLE
[QST] A kernel for small GEMM

### ISSUE THREAD

**Issue by nnaron** [NVIDIA/cutlass#742]
Hi, 

In which part of the Cutlas code I can find a fast GEMM kernel for samall size rank-k update e.g. 64x64.  I mean multiplying two vector and subtract result from a matrix.  Also e kernel for multiplication of two small square matrix.

**Comment by jackkosaian** [comment]
Hi, @nnaron.

> In which part of the Cutlas code I can find a fast GEMM kernel for samall size rank-k update e.g. 64x64. I mean multiplying two vector and subtract result from a matrix.

CUTLASS currently supports rank-k updates of the form `(alpha * A * (A^T)) + (beta * C)` where `A` is an `N x K` matrix. It seems like your use case may be better supported by the [`syr` operation in cuBLAS](https://docs.nvidia.com/cuda/cublas/index.html#cublas-t-syr).

> Also e kernel for multiplication of two small square matrix.

Have you tried one of the CUTLASS GEMM examples on the architecture you're targeting (e.g., [example 14](https://github.com/NVIDIA/cutlass/blob/master/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu))? You may also find the CUTLASS GEMM unit tests useful (e.g., [here ](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_f16n_f16n_f16t_tensor_op_f32_sm80.cu) and its associated [testbed runner](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/testbed.h)). These kernels should support small-GEMM usecases.

I hope this helps!

**Comment by mnicely** [comment]
@nnaron is your question answered?
