### ISSUE TITLE
[FEA] Performace of depthwise conv2d is much worse than cuDNN

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#757]
When I use example **46_depthwise_simt_conv2dfprop** to run depthwise conv2d workload, with the following problem size:
`./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32`
performance result is:
```
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,112,112,32,32,3,3,32,1,1,1,1,1,0.184323,39.1993
```
The latency is 184.323 us, which is much worse than using cuDNN (I got latency around 7~8 us when using cuDNN).

I'm wondering if this is a normal and expected phenomenon? If yes, is it possible to get a best config of cutlass instance that is competitive to cuDNN results?

Thx in advance!

**Comment by Ethan-Yan27** [comment]
As mentioned in https://github.com/NVIDIA/cutlass/blob/master/examples/46_depthwise_simt_conv2dfprop/depthwise_simt_conv2dfprop.cu#L45-L50, it is good to enable splitk to fully use the GPU SM resource. 
Typically, for ampere, `--spiltk=108` is a good start. You could play with this option for your problem size and GPU.

Here is my local testing result. After enabled splitk, the runtime is around 11.8 us. 
```
# w/o splitk
$ ./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,112,112,32,32,3,3,32,1,1,1,1,1,0.179302,40.297

# w/ splitk
$ ./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32 --splitk=108
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,112,112,32,32,3,3,32,1,1,1,1,108,0.011776,613.565
``` 

To get the best config, please try cutlass_profiler (https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md).
Here is the commandline. Please enable split_k_slices as well. 
```
./cutlass_profiler --operation=Conv2d --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32 --split_k_slices=108 --kernel=.*depthwise.*
```
In my local testing, the best config for this problem size is cutlass_simt_hfprop_fixed_stride_dilation_64x32x9_1x8x8x32_3_filter3x3_stride1x1_dilation1x1_nhwc_depthwise_align8. The runtime is around 11.5 us.

**Comment by hwu36** [comment]
@TUMSchieben , what is the name of the kernel used by cudnn?  What is its grid? You can get these by using nsight.

**Comment by TUMSchieben** [comment]
> As mentioned in https://github.com/NVIDIA/cutlass/blob/master/examples/46_depthwise_simt_conv2dfprop/depthwise_simt_conv2dfprop.cu#L45-L50, it is good to enable splitk to fully use the GPU SM resource. Typically, for ampere, `--spiltk=108` is a good start. You could play with this option for your problem size and GPU.
> 
> Here is my local testing result. After enabled splitk, the runtime is around 11.8 us.
> 
> ```
> # w/o splitk
> $ ./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32
> Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
> conv_1,1,112,112,32,32,3,3,32,1,1,1,1,1,0.179302,40.297
> 
> # w/ splitk
> $ ./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32 --splitk=108
> Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
> conv_1,1,112,112,32,32,3,3,32,1,1,1,1,108,0.011776,613.565
> ```
> 
> To get the best config, please try cutlass_profiler (https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md). Here is the commandline. Please enable split_k_slices as well.
> 
> ```
> ./cutlass_profiler --operation=Conv2d --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32 --split_k_slices=108 --kernel=.*depthwise.*
> ```
> 
> In my local testing, the best config for this problem size is cutlass_simt_hfprop_fixed_stride_dilation_64x32x9_1x8x8x32_3_filter3x3_stride1x1_dilation1x1_nhwc_depthwise_align8. The runtime is around 11.5 us.

OK. I tried `--splitk=108` and the latency for `--n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32` is ~11us.
I also tested other cases, but seems `--splitk` sometimes incurs performance regression. For example:
```
./46_depthwise_simt_conv2dfprop --n=1 --h=7 --w=7 --c=1024 --k=1024 --r=3 --s=3 --g=1024
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,7,7,1024,1024,3,3,1024,1,1,1,1,1,0.008048,112.223
```
But set `--splitk=108` got:
```
./46_depthwise_simt_conv2dfprop --n=1 --h=7 --w=7 --c=1024 --k=1024 --r=3 --s=3 --g=1024 --splitk=108
Layer,N,H,W,C,K,R,S,G,stride_h,stride_w,dilation_h,dilation_w,splitK,Runtime,GFLOPs
conv_1,1,7,7,1024,1024,3,3,1024,1,1,1,1,108,0.0272592,33.1326
```

So is this `--splitk` a trade off and should be carefully tuned for different problem size?
At first glance, `--splitk=108` equals to the number of SMs on A100 GPU. Is there any relationship between these 2 params?

**Comment by TUMSchieben** [comment]
> @TUMSchieben , what is the name of the kernel used by cudnn? What is its grid? You can get these by using nsight.

From nsys, for problem `--n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32`, the used kernel is
`void conv2d_c1_k1_nhwc_kernel<float, float, float, float, float, (int)3, (int)1, (bool)1, (bool)0>(T5, cudnnTensorStruct, const T1 *, cudnnFilterStruct, const T3 *, cudnnConvolutionStruct, T5, cudnnTensorStruct, T2 *, C1K1NhwcParams, int, const T2 *, const T5 *, cudnnActivationStruct)`
and the block/grid setting is
```
grid:  <<<392, 1, 1>>>
block: <<<256, 1, 1>>>
```

**Comment by hwu36** [comment]
Splitk is impacted by the problem size a lot.  For example, if you use 54 SMs without splitK, you can choose to use 2 way splitK to saturate your a100.  You can use the profiler to shmoo different splitk number.

**Comment by hwu36** [comment]
You can also try different tile sizes.

**Comment by TUMSchieben** [comment]
> Splitk is impacted by the problem size a lot. For example, if you use 54 SMs without splitK, you can choose to use 2 way splitK to saturate your a100. You can use the profiler to shmoo different splitk number.

How can I determine the number of SMs used for a given problem size? Is this a pre-calculated value in cutlass?

**Comment by Ethan-Yan27** [comment]
> How can I determine the number of SMs used for a given problem size? Is this a pre-calculated value in cutlass?

It depends on the grid size of depthwise kernel. Please refer to https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/threadblock_swizzle.h#L185-L188. It would compute the grid size of depthwise kernel. 

----
In the example kernel , one threadblock would process 1x8x8x64 output tile at a time, then it would fetch another output tile for computation, until it finishes all the output HW tiles belonging to it. 

So for below two problem sizes you mentioned, if without splitK, the grid size is shown below.  
 - ./46_depthwise_simt_conv2dfprop --n=1 --h=7 --w=7 --c=1024 --k=1024 --r=3 --s=3 --g=1024 :  Grid Size< 1, 16, 1> 
 -  ./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32 :  Grid Size <  1, 1, 1>

The general idea of ​​depthwise splitK is to reduce the amount of work per threadblock and bring more threadblocks to increase parallelism.

> ./46_depthwise_simt_conv2dfprop --n=1 --h=7 --w=7 --c=1024 --k=1024 --r=3 --s=3 --g=1024

The output HxW is just 7x7 and one threadblock already just processes 1 output tile, so splitk feature would not help it. 

>   ./46_depthwise_simt_conv2dfprop --n=1 --h=112 --w=112 --c=32 --k=32 --r=3 --s=3 --g=32

The output HxW is 112x112, which is 196 output blocks per threadblock. That is too much work for one threadblock, so the splitk function can help. 

Hope this helps you understand depthwise splitk better.

**Comment by mnicely** [comment]
@TUMSchieben has your issue been resolved?

**Comment by TUMSchieben** [comment]
> @TUMSchieben has your issue been resolved?

Yes, thank you!
