### ISSUE TITLE
[QST] 3D image gradient calculation

### ISSUE THREAD

**Issue by poretga99** [NVIDIA/cutlass#758]
Hi.

I implemented 3D image central difference gradient calculation using normal CUDA cores and now I'm wondering whether it's possible to speed it up using CUTLASS's functionality.

I have multiple 3D grayscale (single channel) images of same shape (eg. 256x256x256). Image gradient calculation is basically just a convolution with a kernel [-1, 0, 1] in each axis direction. Filters are therefore shaped as 1x1x3, 1x3x1, 3x1x1.

Is it possible to implement such functionality via CUTLASS's Conv3D implementation? If not, do I have any other possible solutions, which would be suitable for such a problem?

**Comment by hwu36** [comment]
i am not familiar with 3D image gradient.  What is the difference from conv3d?  just channel size is 1?
