### ISSUE TITLE
How to cite Cutlass

### ISSUE THREAD

**Issue by daviesthomas** [NVIDIA/cutlass#76]
Quick issue/ request. I'm working on some research that utilizes cutlass sgemm (and batched) and wanting to reference Cutlass if we publish. 

I couldn't find a bibtex anywhere to include and some light googling didn't yield much. Do you guys have an open paper to reference or bibtex you could supply on your readme?

**Comment by hwu36** [comment]
I understand it is a problem since we don't have any paper yet.  Currently, the best way is to either cite our github site or our GTC talks.

**Comment by mnicely** [comment]
@hwu36 @kerrmudgeon Let's get this in 2.9
Reference - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
