### ISSUE TITLE
[QST] INT8 GEMM with FP16 output

### ISSUE THREAD

**Issue by gsujankumar** [NVIDIA/cutlass#767]
Hey I have noticed INT8 gemm with the following settings where we have `float` bias and `float` output works okay:

```
using ElementAccumulator = int32_t;                   // <- data type of accumulator
using ElementComputeEpilogue = float;  // <- data type of epilogue operations
using ElementInputA = int8_t;              // <- data type of elements in input matrix A
using ElementInputB = int8_t;              // <- data type of elements in input matrix B
using ElementOutput = float;                        // <- data type of elements in output matrix D
```

But setting the outputs in `cutlass::half` does not? 
```
using ElementAccumulator = int32_t;                   // <- data type of accumulator
using ElementComputeEpilogue = float;  // <- data type of epilogue operations
using ElementInputA = int8_t;              // <- data type of elements in input matrix A
using ElementInputB = int8_t;              // <- data type of elements in input matrix B
using ElementOutput = cutlass::half;                        // <- data type of elements in output matrix D
```

Is there any specific restriction preventing it? How can this be enabled?

**Comment by hwu36** [comment]
please try copy paste https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h#L187-L223 and change float to int.  we need a new specialization for your case.  if it is working, feel free to open a PR.

**Comment by gsujankumar** [comment]
That resolves some errors:

Now I am running into this error:

```
../../include/cutlass/epilogue/threadblock/epilogue.h(179): error: more than one partial specialization matches the template argument list of class "cutlass::epilogue::threadblock::SharedLoadIteratorMixed<cutlass::epilogue::threadblock::OutputTileOptimalThreadMap<cutlass::epilogue::threadblock::OutputTileShape<128, 8, 2, 1, 1>, cutlass::epilogue::threadblock::OutputTileShape<1, 8, 1, 1, 8>, 128, 8, 16>::CompactedThreadMap, int32_t, 32, 16, 8, 8>"
            "cutlass::epilogue::threadblock::SharedLoadIteratorMixed<ThreadMap_, Element_, 32, 16, 8, 8>"
            "cutlass::epilogue::threadblock::SharedLoadIteratorMixed<ThreadMap_, int32_t, 32, OutputSizeBits_, 8, 8>"
```

**Comment by hwu36** [comment]
you can comment out https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/shared_load_iterator_mixed.h#L251

**Comment by gsujankumar** [comment]
This worked, will PR after some checks. How do I avoid commenting https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/shared_load_iterator_mixed.h#L421 though? It may be needed for INT8 and INT4 output type i am assuming.

**Comment by hwu36** [comment]
The right approach is using type bit sizes instead of data types in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h#L90-L91 and https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/shared_load_iterator_mixed.h#L69

Then int32 and fp32 accumulator type can use the same struct.  fp8 and int8 output can use the same struct, too.

**Comment by mnicely** [comment]
@gsujankumar were you still planning to submit a PR?

**Comment by gsujankumar** [comment]
Here is the PR: https://github.com/NVIDIA/cutlass/pull/812
