### ISSUE TITLE
Required Python version is 3.6: AttributeError: module 'enum' has no attribute 'auto'

### ISSUE THREAD

**Issue by egonzalf** [NVIDIA/cutlass#77]
https://github.com/NVIDIA/cutlass/blob/7c0cd26d13e0e0c41a5b6874f06976575e613e72/tools/library/CMakeLists.txt#L25

This line was missed in the #70 PR

**Comment by kerrmudgeon** [comment]
Looks like we didn't get to this for the last minor release. I expect our recourse will actually be to avoid the dependency on `enum.auto` in an upcoming patch for broader compatibility.

Thank you for pointing this out.

**Comment by d-k-b** [comment]
This should be fixed in CUTLASS 2.2. Please reopen if you see further issues.
