### ISSUE TITLE
[QST] how to correctly set depthwise_conv2d params?

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#770]
Hi,
I've tested `depthwise_conv2d + bias` by slightly modifying **46_depthwise_simt_conv2dfprop**, and the output result is correct when compared with pytorch golden. But for case `depthwise_conv2d + bias + add`, how to adapt the code?

Another question is in **46_depthwise_simt_conv2dfprop**, when setting arguments the code is as follows:
```
typename Direct2dConv::Arguments arguments{problem_size,
                                             tensor_a.device_ref(),
                                             tensor_b.device_ref(),
                                             tensor_c.device_ref(),
                                             tensor_d.device_ref(),
                                             {options.alpha, options.beta},
                                             tensor_b_transpose.device_ref()};
```
I'm wondering what's the purpose of the last parameter _tensor_b_transpose_. In my test, if I set the last parameter the same as _tensor_b_, the output result seems is correct as well. Is there any hint for this?

**Comment by Ethan-Yan27** [comment]
> `depthwise_conv2d + bias + add`

What does the `add` mean? Which operation would you like to do ?

> I'm wondering what's the purpose of the last parameter tensor_b_transpose.

We have a helper kernel to reorder filters before the depthwise kernel starts https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/direct_convolution.h#L170. Example passes the tensor_b_tranpose to helper kernel to not modify the original tensor_b.

**Comment by TUMSchieben** [comment]
> What does the `add` mean? Which operation would you like to do ?

`add` means that after bias_add, there is an extra element wise add op.



> Example passes the tensor_b_tranpose to helper kernel to not modify the original tensor_b.

So from my understanding, if replace `tensor_b_tranpose `with original `tensor_b`, after depthwise kernel completed the content in `tensor_b` would change to the transposed format, is that right?
If that is the case and without using `tensor_b_tranpose`, then does it mean that a second execution of the instance will give wrong results since data in original `tensor_b` has changed?

**Comment by Ethan-Yan27** [comment]
Some files that may be useful for your epilogue work.

- The epilogue entry point: https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue_depthwise.h

- The elementwise operation file:  (alpha * accum + beta *source + unitform) https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination.h

- If you need extra input :  take a look `class PredicatedTileIteratorDirectConv `about how to load and store the output tile from global memory in epilogue : https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/predicated_tile_iterator_direct_conv.h

> If that is the case and without using tensor_b_tranpose, then does it mean that a second execution of the instance will give wrong results since data in original tensor_b has changed?

Yes. Tensor b is not identical to the original data. The helper function would change tensor_b data Storage order .  https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/direct_convolution.h#L206

**Comment by jackkosaian** [comment]
@TUMSchieben, you may also find the [LinearCombinationResidualBlock](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_residual_block.h#L56-L63) epilogue useful. It computes `UnaryOp(BinaryOp(BinaryOp(ActivationOp(TensorOp(X) + bias), residual1), residual2))`. It supports both single-source use cases (i.e., no `residual2`) and double-source use cases (i.e., both `residual1` and `residual2`).

Currently, this is only used in GEMM kernels. You can see an example [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_f16t_f16n_f16t_tensor_op_f16_broadcast_sm80.cu). You may be able to adapt it to convolutions as well.

**Comment by mnicely** [comment]
@TUMSchieben has your issue been resolved?

**Comment by TUMSchieben** [comment]
> @TUMSchieben has your issue been resolved?

Yeah, thx
