### ISSUE TITLE
[FEA] Support fused conv in generator

### ISSUE THREAD

**Issue by ShuaiShao93** [NVIDIA/cutlass#772]
**Is your feature request related to a problem? Please describe.**
I wish I could use CUTLASS to generate fused conv+bn+relu kernels.

**Describe the solution you'd like**
It looks like the fused conv is already supported (examples/25_ampere_fprop_mainloop_fusion), so it only needs to add the support in the generator.

**Additional context**
Fused conv is much more useful than raw conv in inference

**Comment by hwu36** [comment]
First, inference doesn't need batch norm.

We don't add fused kernels into the generator since these  one off kernels are very different from each other and each one of them need different settings.

You could follow examples to set them up in your case.

**Comment by ShuaiShao93** [comment]
> First, inference doesn't need batch norm.

I meant fused conv is more efficient, so it's more useful.

> 
> We don't add fused kernels into the generator since these one off kernels are very different from each other and each one of them need different settings.
> 
> You could follow examples to set them up in your case.

Thanks! I tried setting up a benchmark for int8 fused_conv, but it looks like there is a bug:
```
include/cutlass/conv/threadblock/implicit_gemm_fprop_fusion_multistage.h:544:30: error: no member named 'set_iteration_index' in 'cutlass::transform::threadblock::RegularTileIterator<cutlass::MatrixShape<64, 64>, signed char, cutlass::layout::RowMajorTensorOpMultiplicandCrosswise<8, 64>, 0, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::PitchLinearShape<64, 64>, 128, cutlass::PitchLinearShape<4, 8>, 16>, 16>'
      this->smem_iterator_A_.set_iteration_index(0);
```

It looks like the `set_iteration_index()` and `get()` are missing from [RegularTileIterator](https://github.com/NVIDIA/cutlass/blob/7bdba07310b497e75c8377031e524fadc929b849/include/cutlass/transform/threadblock/regular_tile_iterator_tensor_op.h), can you confirm this?

It looks like there is no unit test for fused conv. If generator support is not needed, can we add some unit tests?

**Comment by ShuaiShao93** [comment]
https://github.com/NVIDIA/cutlass/pull/776 makes it compile. I'm not sure if it's correct tho, since I didn't test the output.

**Comment by ShuaiShao93** [comment]
Just noticed that 25_ampere_fprop_mainloop_fusion doesn't support INT8. This error is meaningless.
