### ISSUE TITLE
Missing file cutlass/gemm/kernel/default_gemm_complex.h

### ISSUE THREAD

**Issue by gb-esat** [NVIDIA/cutlass#78]
Hi

I believe [this include](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_complex.h#L39) is missing. 

BTW, is there an example anywhere for a complex half_t GEMM?

Thanks!

Gary

**Comment by kerrmudgeon** [comment]
We have just added planar complex GEMM kernels targeting Volta and Turing Tensor Cores. These compute the matrix product of matrices of data type `half_t`. 

The planar complex representation is preferred for efficiency, with the the real part of each element stored as a contiguous pitch-linear matrix disjoint from the imaginary part.

Here is an [SDK example](https://github.com/NVIDIA/cutlass/blob/master/examples/10_planar_complex/planar_complex.cu).
