### ISSUE TITLE
[QST] Per-channel scale epilogue 

### ISSUE THREAD

**Issue by david-macleod** [NVIDIA/cutlass#783]
**What is your question?**

Is it possible to implement an epilogue which applies the following `y[i,j].float().mul(s[j]).half()`, so essentially a per-channel scale multiplication (with some type casting). I can see examples of per-channel addition and also examples of elemement-wise scaling, but nothing that has per-channel scaling.

If it's possible pointers in the correct direction would be greatly appreciated, thanks!

**Comment by jackkosaian** [comment]
Hi, @david-macleod.

It sounds like the functionality you're looking for can be achieved by using `DefaultConv2dFpropWithBroadcast`. You can use this kernel with the `LinearCombinationBiasElementwise`, which allows one to perform an [arbitrary binary operation](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/linear_combination_bias_elementwise.h#L64) between the result of the convolution and a bias term on a per-channel basis.

An example of using this method for adding a bias term on a per-channel basis is [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_with_broadcast_sm75.cu#L48-L90). For your usecase, assuming that you don't want to use a particular activation function, you could replace `ReLu` [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_fprop_with_broadcast_sm75.cu#L65) with `cutlass::epilogue::thread::Identity<float>` (defined [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/activation.h#L86-L102)). You could then add an additional template parameter to specialize the `BinaryOp` used by the epilogue to be `multiplies<float>` (defined [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/functional.h#L77-L84)), rather than the default of `plus`. Populating the bias vector with scaling terms should achieve the functionality you're looking for.

For an example of setting the arguments for the resulting kernel, you can refer to the testbed corresponding to the unit test for Conv2d+broadcast [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_with_broadcast_testbed.h#L305-L317).

I hope this helps!

**Comment by david-macleod** [comment]
@jackkosaian thanks for your quick reply! Looks really promising. The only difference between your proposal and my use-case (which I should have clarified) is that I am looking to do an INT8 matmul e.g. `s8 * s8 + => s32`, and looking at the functional `multiplies` it is understandably expecting the same type for lhs and rhs arguments.

Is the solution simply a matter of defining a new version of multiplies that casts  lhs to float, and then casts the output to half as per my requirements, or is there more to it?

**Comment by jackkosaian** [comment]
@david-macleod, that seems like a reasonable solution for your case.

Perhaps something like the following, which uses CUTLASS's [NumericConverter](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/numeric_conversion.h#L66-L87):
```c++
template <typename ElementLhs, typename ElementRhs>
struct multiplies {
  cutlass::NumericConverter<ElementLhs, ElementRhs> convert_rhs_to_lhs;

  CUTLASS_HOST_DEVICE
  ElementLhs operator()(ElementLhs lhs, ElementRhs const &rhs) const {
    lhs *= convert_rhs_to_lhs(rhs);
    return lhs;
  }
};
```

Converting to `cutlass::half_t` within `multiplies<>()` operator itself to return a `cutlass::half_t` should not be necessary, as the epilogue surrounding the use of this `multiplies` specialization should handle this.

**Comment by gsujankumar** [comment]
@jackkosaian  I have a follow up to this, is there anyway we can do `y[i,j].mul(s[j]).mul(d[i])`? I looked at the gemm with multiple sources example; it seems like we can only broadcast across one dimension, is this correct?

**Comment by david-macleod** [comment]
@jackkosaian thanks for the pointer. I have got a working example by modifying the epilogue of the following unit-test as discussed (GELU -> Identity, plus -> multiplies) 

```cpp

TEST(SM80_Device_GemmWithBroadcast_GELU_f16n_f16n_f16n_tensor_op_f32, 128x128_32x3_64x64x32_16x8x16) {
  
  using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombinationBiasElementwise<
    cutlass::half_t,
    float,
    float,
    cutlass::half_t,
    cutlass::half_t,
    8,
    cutlass::epilogue::thread::Identity<float>,
    cutlass::multiplies<float>
  >;

  using GemmKernel = 
    typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
      cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
      cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
      cutlass::half_t, cutlass::layout::RowMajor,
      float,
      cutlass::arch::OpClassTensorOp,
      cutlass::arch::Sm80,
      cutlass::gemm::GemmShape<128, 128, 32>,
      cutlass::gemm::GemmShape<64, 64, 32>,
      cutlass::gemm::GemmShape<16, 8, 16>,
      EpilogueOutputOp,
      cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
      3,
      cutlass::arch::OpMultiplyAdd
  >::GemmKernel;

  using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;

  test::gemm::device::TestAllGemmWithBroadcast<Gemm>();
}
```
However this only appears to work for fp16, if I try to get it working for in8 input and int32 accumulation it fails

```cpp
using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombinationBiasElementwise<
    cutlass::half_t,
    int32_t,
    float,
    cutlass::half_t,
    cutlass::half_t,
    8,
    cutlass::epilogue::thread::Identity<float>,
    cutlass::multiplies<float>
  >;

  using GemmKernel = 
    typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
      int8_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
      int8_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
      cutlass::half_t, cutlass::layout::RowMajor,
      int32_t,
      cutlass::arch::OpClassTensorOp,
      cutlass::arch::Sm80,
      cutlass::gemm::GemmShape<128, 128, 32>,
      cutlass::gemm::GemmShape<64, 64, 32>,
      cutlass::gemm::GemmShape<16, 8, 16>,
      EpilogueOutputOp,
      cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
      3,
      cutlass::arch::OpMultiplyAdd
  >::GemmKernel;

  using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;

  test::gemm::device::TestAllGemmWithBroadcast<Gemm>();
```
  
```
/scratch/cutlass/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h(1160): error: incomplete type is not allowed
          detected during:
            instantiation of class "cutlass::gemm::warp::MmaTensorOpMultiplicandTileIterator<Shape_, Operand_, Element_, cutlass::layout::RowMajorTensorOpMultiplicandCongruous<cutlass::sizeof_bits<Element_>::value, <expression>>, InstructionShape_, OpDelta_, 32, PartitionsK_> [with Shape_=cutlass::MatrixShape<32, 64>, Operand_=cutlass::gemm::Operand::kB, Element_=int8_t, InstructionShape_=cutlass::MatrixShape<16, 8>, OpDelta_=1, PartitionsK_=1]"
```
I was assuming accumulation in `int32_t`, bias (broadcastable tensor) is `cutlass::half_t`. These both get cast to float here
```
FragmentCompute tmp_Accum = NumericArrayConverter<ElementCompute, ElementAccumulator, kElementsPerAccess>()(AB);
    FragmentCompute tmp_C = NumericArrayConverter<ElementCompute, ElementC, kElementsPerAccess>()(frag_C);
```
And then cast back to `cutlass::half_t` on output here

```
NumericArrayConverter<ElementZ, ElementCompute, kElementsPerAccess> convert_z;
    frag_Z = convert_z(result_Z);
```
So probably I have misunderstood the API or this combination of types is not currently supported?

--------------------------------------------------------------------------------------------------------------------

As a sanity check (not actually interested in getting this working) I have also tried replacing all instances of `cutlass::half_t` with `float` in the original unit test and it fails with the following error

``` 
/scratch/cutlass/include/cutlass/gemm/warp/mma_tensor_op_policy.h(58): error: incomplete type is not allowed
          detected during:
            instantiation of class "cutlass::gemm::warp::MmaTensorOpPolicy<Operator_, OpDelta_> [with Operator_=cutlass::arch::Mma<cutlass::gemm::GemmShape<16, 8, 16>, 32, cutlass::tfloat32_t, cutlass::layout::RowMajor, cutlass::tfloat32_t, cutlass::layout::ColumnMajor, float, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>, OpDelta_=cutlass::MatrixShape<1, 1>]"
```
Which appears to be referencing tfloat32 so must be falling back to some default somewhere? (just to reiterate, this is not my target use-case, just tried to simplify the modification)

**Comment by jackkosaian** [comment]
Hi, @david-macleod.

I'm unable to replicate the compilation error you describe with the edits you list. Could you please provide the following information?

1. What commit of CUTLASS are you working from?
2. What CMake command are you using to configure CUTLASS? I used `cmake .. -DCUTLASS_NVCC_ARCHS='80'` when trying to replicate.

> Which appears to be referencing tfloat32 so must be falling back to some default somewhere?

I know this isn't the main issue you're having, but, just to clarify where `tfloat32` is coming from: if using `float` operands with `OpClassTensorOp` on SM80+, CUTLASS will internally convert `float` to `tfloat32` to use `tfloat32` Tensor Core operations. You can find more information on this [here](https://github.com/NVIDIA/cutlass/blob/66d9cddc832c1cdc2b30a8755274f7f74640cfe6/examples/14_ampere_tf32_tensorop_gemm/ampere_tf32_tensorop_gemm.cu#L42-L45).

**Comment by david-macleod** [comment]
Thanks for the info!

I have fixed this current issue (needed to make tensor B ColumnMajor), git commit is `3f2bb177228879`. 

I am currently trying to understand why we need to allocate tensors for C, T, Z (see [link](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/testbed_gemm_with_broadcast.h#L422)), I would have expected the intermediates to only exist in SRAM (given the motivation to fuse the epilogue), but probably I am missing something here.

**Comment by jackkosaian** [comment]
Hi, @david-macleod .

> I am currently trying to understand why we need to allocate memory for C, T, Z

Regarding `C`: the GEMM operation is `(alpha * A * B) + (beta * C)`. Because `C` is an input to this operation, we need to pass it in to the kernel, and, thus, allocate/initialize it in global memory.

Regarding `Z`: this is the output of the fused GEMM + epilogue kernel. Thus, we need to allocate space in global memory to which the kernel will write its results.

Regarding `T`: this is the result of the fused GEMM + epilogue kernel before the elementwise activation function has been applied (see [here](https://github.com/NVIDIA/cutlass/blob/66d9cddc832c1cdc2b30a8755274f7f74640cfe6/include/cutlass/epilogue/thread/linear_combination_bias_elementwise.h#L213-L214)). You are correct that, in some cases, storing this intermediate output is unnecessary (e.g., when performing inference). However, there are other scenarios in which it is helpful to store this intermediate output, such as when the pre-activation-function tensor values may be used in back propagation. If one does not need to store the intermediate tensor, this can be turned off using the `StoreT` template parameter (see [here](https://github.com/NVIDIA/cutlass/blob/66d9cddc832c1cdc2b30a8755274f7f74640cfe6/include/cutlass/epilogue/threadblock/epilogue_with_broadcast.h#L638-L641)).

Note that, even if one writes these intermediates to global memory, one still benefits from fusing the epilogue to the GEMM by avoiding a write/read of the output of the GEMM from global memory to compute the epilogue.

Without epilogue fusion, the general pattern of compute operations and global memory read/write operations would be:
```
Kernel 1: read A/B/C from global memory -> compute D = a*A*B + b*C -> write D to global memory
Kernel 2: read D from global memory -> compute T and Z from D in epilogue -> write T and Z to global memory
```

With epilogue fusion, the pattern would be:
```
Kernel 1: read A/B/C from global memory -> compute D = a*A*B + b*C -> compute T and Z from D in epilogue -> write T and Z to global memory
```

**Comment by david-macleod** [comment]
Thanks a lot! Closing issue

**Comment by erees1** [comment]
@jackkosaian I created this MR https://github.com/NVIDIA/cutlass/pull/838 to upstream the ability to toggle StoreT. Would this be something you would be interested in merging?

**Comment by jackkosaian** [comment]
Thank you for your contribution, @erees1. We'll plan to work on merging it after we tag version 3.0 (which will take place soon).

**Comment by zhoutianzi666** [comment]
Kernel 1: read A/B/C from global memory -> compute D = a*A*B + b*C -> compute T and Z from D in epilogue -> write T and Z to global memory

@jackkosaian why we need write T to global memory？

// Fused testbed
//
//  Y = GEMM(AB, C)
//
//  T[i, j] = BinaryOp(Y[i, j], Broadcast[i])
//
//  Z[i, j] = Elementwise(T[i, j])
//

**Comment by jackkosaian** [comment]
> why we need write T to global memory？

@zhoutianzi666 , storing pre-activation-function activations (`T` in this case) can be useful when computing the backward pass during training. If you don't need these values in your setting, you can set `StoreT` to `false` (see this [PR](https://github.com/NVIDIA/cutlass/pull/838)).

> can we set Z to nullptr to prevent write Z back to global memory？

What would be the use case for this? This would result in ignoring the activation function being computed in the `Z[i, j] = Elementwise(T[i, j])` step you list above. If you wanted to do this, you could expose the `StoreZ` parameter in a similar way to what is done for `StoreT` in #838.

**Comment by zhoutianzi666** [comment]
@jackkosaian   thanks a lot

**Comment by zhoutianzi666** [comment]
> @jackkosaian thanks for the pointer. I have got a fp16 working example by modifying the epilogue of the following unit-test as discussed (GELU -> Identity, plus -> multiplies)
> 
> ```c++
> TEST(SM80_Device_GemmWithBroadcast_GELU_f16n_f16n_f16n_tensor_op_f32, 128x128_32x3_64x64x32_16x8x16) {
>   
>   using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombinationBiasElementwise<
>     cutlass::half_t,
>     float,
>     float,
>     cutlass::half_t,
>     cutlass::half_t,
>     8,
>     cutlass::epilogue::thread::Identity<float>,
>     cutlass::multiplies<float>
>   >;
> 
>   using GemmKernel = 
>     typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
>       cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
>       cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
>       cutlass::half_t, cutlass::layout::RowMajor,
>       float,
>       cutlass::arch::OpClassTensorOp,
>       cutlass::arch::Sm80,
>       cutlass::gemm::GemmShape<128, 128, 32>,
>       cutlass::gemm::GemmShape<64, 64, 32>,
>       cutlass::gemm::GemmShape<16, 8, 16>,
>       EpilogueOutputOp,
>       cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
>       3,
>       cutlass::arch::OpMultiplyAdd
>   >::GemmKernel;
> 
>   using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;
> 
>   test::gemm::device::TestAllGemmWithBroadcast<Gemm>();
> }
> ```
> 
> However this only appears to work for fp16, if I try to get it working for in8 input and int32 accumulation it fails
> 
> ```c++
> using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombinationBiasElementwise<
>     cutlass::half_t,
>     int32_t,
>     float,
>     cutlass::half_t,
>     cutlass::half_t,
>     8,
>     cutlass::epilogue::thread::Identity<float>,
>     cutlass::multiplies<float>
>   >;
> 
>   using GemmKernel = 
>     typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
>       int8_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
>       int8_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
>       cutlass::half_t, cutlass::layout::RowMajor,
>       int32_t,
>       cutlass::arch::OpClassTensorOp,
>       cutlass::arch::Sm80,
>       cutlass::gemm::GemmShape<128, 128, 32>,
>       cutlass::gemm::GemmShape<64, 64, 32>,
>       cutlass::gemm::GemmShape<16, 8, 16>,
>       EpilogueOutputOp,
>       cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
>       3,
>       cutlass::arch::OpMultiplyAdd
>   >::GemmKernel;
> 
>   using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;
> 
>   test::gemm::device::TestAllGemmWithBroadcast<Gemm>();
> ```
> 
>  ```
> /scratch/cutlass/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h(1160): error: incomplete type is not allowed
>           detected during:
>             instantiation of class "cutlass::gemm::warp::MmaTensorOpMultiplicandTileIterator<Shape_, Operand_, Element_, cutlass::layout::RowMajorTensorOpMultiplicandCongruous<cutlass::sizeof_bits<Element_>::value, <expression>>, InstructionShape_, OpDelta_, 32, PartitionsK_> [with Shape_=cutlass::MatrixShape<32, 64>, Operand_=cutlass::gemm::Operand::kB, Element_=int8_t, InstructionShape_=cutlass::MatrixShape<16, 8>, OpDelta_=1, PartitionsK_=1]"
> ```
> 
> I was assuming accumulation in `int32_t`, bias (broadcastable tensor) is `cutlass::half_t`. These both get cast to float here
> 
> ```
> FragmentCompute tmp_Accum = NumericArrayConverter<ElementCompute, ElementAccumulator, kElementsPerAccess>()(AB);
> FragmentCompute tmp_C = NumericArrayConverter<ElementCompute, ElementC, kElementsPerAccess>()(frag_C);
> ```
> 
> And then cast back to `cutlass::half_t` on output here
> 
> ```
> NumericArrayConverter<ElementZ, ElementCompute, kElementsPerAccess> convert_z;
> frag_Z = convert_z(result_Z);
> ```
> 
> So probably I have misunderstood the API or this combination of types is not currently supported?
> 
> As a sanity check (not actually interested in getting this working) I have also tried replacing all instances of `cutlass::half_t` with `float` in the original unit test and it fails with the following error
> 
> ```
> /scratch/cutlass/include/cutlass/gemm/warp/mma_tensor_op_policy.h(58): error: incomplete type is not allowed
>           detected during:
>             instantiation of class "cutlass::gemm::warp::MmaTensorOpPolicy<Operator_, OpDelta_> [with Operator_=cutlass::arch::Mma<cutlass::gemm::GemmShape<16, 8, 16>, 32, cutlass::tfloat32_t, cutlass::layout::RowMajor, cutlass::tfloat32_t, cutlass::layout::ColumnMajor, float, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>, OpDelta_=cutlass::MatrixShape<1, 1>]"
> ```
> 
> Which appears to be referencing tfloat32 so must be falling back to some default somewhere? (just to reiterate, this is not my target use-case, just tried to simplify the modification)

@jackkosaian I replicate the code you modify, it reports:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/39978853/229005642-43db0466-3e36-49bd-a849-7bac2c5a4683.png">

**Comment by zhoutianzi666** [comment]
> > @jackkosaian thanks for the pointer. I have got a fp16 working example by modifying the epilogue of the following unit-test as discussed (GELU -> Identity, plus -> multiplies)
> > ```c++
> > TEST(SM80_Device_GemmWithBroadcast_GELU_f16n_f16n_f16n_tensor_op_f32, 128x128_32x3_64x64x32_16x8x16) {
> >   
> >   using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombinationBiasElementwise<
> >     cutlass::half_t,
> >     float,
> >     float,
> >     cutlass::half_t,
> >     cutlass::half_t,
> >     8,
> >     cutlass::epilogue::thread::Identity<float>,
> >     cutlass::multiplies<float>
> >   >;
> > 
> >   using GemmKernel = 
> >     typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
> >       cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
> >       cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
> >       cutlass::half_t, cutlass::layout::RowMajor,
> >       float,
> >       cutlass::arch::OpClassTensorOp,
> >       cutlass::arch::Sm80,
> >       cutlass::gemm::GemmShape<128, 128, 32>,
> >       cutlass::gemm::GemmShape<64, 64, 32>,
> >       cutlass::gemm::GemmShape<16, 8, 16>,
> >       EpilogueOutputOp,
> >       cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
> >       3,
> >       cutlass::arch::OpMultiplyAdd
> >   >::GemmKernel;
> > 
> >   using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;
> > 
> >   test::gemm::device::TestAllGemmWithBroadcast<Gemm>();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However this only appears to work for fp16, if I try to get it working for in8 input and int32 accumulation it fails
> > ```c++
> > using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombinationBiasElementwise<
> >     cutlass::half_t,
> >     int32_t,
> >     float,
> >     cutlass::half_t,
> >     cutlass::half_t,
> >     8,
> >     cutlass::epilogue::thread::Identity<float>,
> >     cutlass::multiplies<float>
> >   >;
> > 
> >   using GemmKernel = 
> >     typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
> >       int8_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
> >       int8_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
> >       cutlass::half_t, cutlass::layout::RowMajor,
> >       int32_t,
> >       cutlass::arch::OpClassTensorOp,
> >       cutlass::arch::Sm80,
> >       cutlass::gemm::GemmShape<128, 128, 32>,
> >       cutlass::gemm::GemmShape<64, 64, 32>,
> >       cutlass::gemm::GemmShape<16, 8, 16>,
> >       EpilogueOutputOp,
> >       cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
> >       3,
> >       cutlass::arch::OpMultiplyAdd
> >   >::GemmKernel;
> > 
> >   using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;
> > 
> >   test::gemm::device::TestAllGemmWithBroadcast<Gemm>();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > /scratch/cutlass/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h(1160): error: incomplete type is not allowed
> >          detected during:
> >            instantiation of class "cutlass::gemm::warp::MmaTensorOpMultiplicandTileIterator<Shape_, Operand_, Element_, cutlass::layout::RowMajorTensorOpMultiplicandCongruous<cutlass::sizeof_bits<Element_>::value, <expression>>, InstructionShape_, OpDelta_, 32, PartitionsK_> [with Shape_=cutlass::MatrixShape<32, 64>, Operand_=cutlass::gemm::Operand::kB, Element_=int8_t, InstructionShape_=cutlass::MatrixShape<16, 8>, OpDelta_=1, PartitionsK_=1]"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I was assuming accumulation in `int32_t`, bias (broadcastable tensor) is `cutlass::half_t`. These both get cast to float here
> > ```
> > FragmentCompute tmp_Accum = NumericArrayConverter<ElementCompute, ElementAccumulator, kElementsPerAccess>()(AB);
> > FragmentCompute tmp_C = NumericArrayConverter<ElementCompute, ElementC, kElementsPerAccess>()(frag_C);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then cast back to `cutlass::half_t` on output here
> > ```
> > NumericArrayConverter<ElementZ, ElementCompute, kElementsPerAccess> convert_z;
> > frag_Z = convert_z(result_Z);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So probably I have misunderstood the API or this combination of types is not currently supported?
> > As a sanity check (not actually interested in getting this working) I have also tried replacing all instances of `cutlass::half_t` with `float` in the original unit test and it fails with the following error
> > ```
> > /scratch/cutlass/include/cutlass/gemm/warp/mma_tensor_op_policy.h(58): error: incomplete type is not allowed
> >           detected during:
> >             instantiation of class "cutlass::gemm::warp::MmaTensorOpPolicy<Operator_, OpDelta_> [with Operator_=cutlass::arch::Mma<cutlass::gemm::GemmShape<16, 8, 16>, 32, cutlass::tfloat32_t, cutlass::layout::RowMajor, cutlass::tfloat32_t, cutlass::layout::ColumnMajor, float, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAdd>, OpDelta_=cutlass::MatrixShape<1, 1>]"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which appears to be referencing tfloat32 so must be falling back to some default somewhere? (just to reiterate, this is not my target use-case, just tried to simplify the modification)
> 
> @jackkosaian I replicate the code you modify, it reports:
> 
> <img alt="image" width="1182" src="https://user-images.githubusercontent.com/39978853/229005642-43db0466-3e36-49bd-a849-7bac2c5a4683.png">

Building CUDA object test/unit/gemm/device/CMakeFiles/cutlass_test_unit_gemm_device_gemm_with_fused_epilogue_tensorop.dir/gemm_with_broadcast_f16n_f16n_f16n_tensorop_f32_sm75.cu.o
/zhoukangkang/cutlass/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h(244): error: static assertion failed with "ElementOutput needs to be 4 or 8 bit (unsigned) int."

**Comment by hwu36** [comment]
Line 244 now of include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h is not an asset

You need to update your cutlass.

**Comment by zhoutianzi666** [comment]
thanks a lot , I already solved it
