### ISSUE TITLE
[QST] How to add support for full-matrix bias in b2b gemm example?

### ISSUE THREAD

**Issue by rkindi** [NVIDIA/cutlass#784]
Hi, I am trying to add support for a full-matrix bias add in example 13 (b2b fused gemm) after the first of the two fused gemms. Right now, it seems the example only supports vector bias. Inside [b2b_mma_multistage.h](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage.h), I see we [only support vector bias](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage.h#L646-L651).

My thought was somehow I need to get the portion of the full-matrix bias from global mem to the [same format as accum0](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage.h#L496).

I know a common pattern in epilogue is _accumulator in registers [--->](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue.h#L458-L463) smem [--->](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue.h#L484-L485) back to registers in aligned accumulator format to do epilogue computation [--->](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/epilogue.h#L511-L517) store to global mem_. My understanding from [this issue](https://github.com/NVIDIA/cutlass/issues/721) is that we prefer the aligned accumulator format because it lets us do vectorized stores after the epilogue computation to global mem without going back through shared memory which makes sense.

However, in the b2b gemm case, we want the result of the first gemm + matrix bias addition to _remain in the [accumulators so it can be consumed by the second gemm](https://github.com/NVIDIA/cutlass/blob/master/examples/13_two_tensor_op_fusion/threadblock/b2b_mma_multistage.h#L496)_. 

So, somehow we need to go from global memory to accum format. I guess we will experience the same issue as before related to aligned accum format vs unaligned accumulator format -- in the epilogue, it is inefficient to write from registers to global memory with unaligned accumulator format so we go through smem to change to aligned accumulator format; now for the b2b gemm matrix bias for the first gemm, we need to read from global memory to registers in unaligned accumulator format but reading directly from global memory to this format would be inefficient due to non vectorized loads.

I guess we would want something that is effectively the inverse of the epilogue then: read the matrix bias from global memory -> aligned accum format in registers for vectorized loads -> write to smem -> read back into accumulators in unaligned accum format.

Is my line of thinking here correct? I think I need to do something like the following:

| Epilogue  | Matrix Bias Add (Inverse of Epilogue) |
| ------------- | ------------- |
| (1) Save unaligned accum to smem with `accum_fragment_iterator.load(accum_fragment);` and `this->warp_tile_iterator_.store(accum_fragment);`  |  (3) Load from smem to unaligned accum with `accum_fragment_iterator.store(accum_fragment);` and `this->warp_tile_iterator_.load(accum_fragment);` |
| (2) Load from smem accumulators to registers in aligned format with `shared_load_iterator_.load(aligned_accum_fragment[0]);`  | (2) Save aligned registers to smem with  `shared_load_iterator_.store(aligned_accum_fragment[0]);` |
| (3) Load source from global memory with `source_iterator.load(source_fragment);`  | (1) Load source from global memory with `source_iterator.load(aligned_accum_fragment);`  |

Thanks!

cc: @hwu36

**Comment by jwang323** [comment]
Hi @rkindi, the approach described above sounds about right. One thing that I would like to note regarding the performance of loading epilogue is related to the storage location of the accumulator. Example 13 supports both accumulator in RF and Shmem for the 1st GEMM/CONV. Consequently there could be a perf impact on loading epilogue from gmem->shmem->RF vs. gmem->RF depending on the storage location of the accumulator.

**Comment by hwu36** [comment]
@rkindi , @jwang323 is the author of ex13.

You are almost correct in everything you said.  I can understand the left column of your table, but not 100% sure about the right column.  Am I supposed to read it from bottom to top, i.e. (1)->(2)->(3) order.  If so, (1) and (2) can be combined to use `cp.async` which loads data from the global memory to the shared memory in one step without eating up register file.  We use it in the mainloop, e.g. https://github.com/NVIDIA/cutlass/blob/add4ba622f1cdebc145d1df0e9620c3c84c00a52/include/cutlass/gemm/threadblock/mma_multistage.h#L314-L315

I am not sure about what is in (3), you store accum into the shmem first to save some register file for the source matrix?

**Comment by mnicely** [comment]
@rkindi were you able to solve your issues?

**Comment by mnicely** [comment]
Resolved

**Comment by butterluo** [comment]
It could be very appreciated, if there is anyone can share the codes to solve this problem? I encounter same problem too.
