### ISSUE TITLE
[QST] Simultaneous Row-wise and Column-wise broadcast.

### ISSUE THREAD

**Issue by gsujankumar** [NVIDIA/cutlass#785]
Following up from https://github.com/NVIDIA/cutlass/issues/783. Is there anyway we can broadcast 2 vectors across different dimensions for a `gemm`? Specifically, I am interested to see if we can do `y[i,j].mul(s[j]).mul(d[i])` in epilogue where `y[i,j]` is the gemm output, and `d[i]` and `s[j]` are vectors? 

I looked at the gemm with multiple sources example; it seems like we can only broadcast across one dimension ( or implement element-wise operations) is this correct?

**Comment by jackkosaian** [comment]
Hi, @gsujankumar.

CUTLASS does not currently have an epilogue that achieves exactly what you would like, but I believe you could achieve the functionality you desire by using the `EpilogueVisitorModel` (see basic concept [here](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/include/cutlass/epilogue/threadblock/epilogue_with_visitor.h#L53)). PyCUTLASS has examples of [many](https://github.com/NVIDIA/cutlass/tree/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/pycutlass/src/cpp/include/epilogue/epilogue_visitor_op) of these epilogues in C++. Those that seem to be particularly of interest to you would be the [`VistorOpRowBroadcast`](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/pycutlass/src/cpp/include/epilogue/epilogue_visitor_op/visitor_op_row_broadcast.h#L57) and [`VisitorOpColumnBroadcast`](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/tools/library/scripts/pycutlass/src/cpp/include/epilogue/epilogue_visitor_op/visitor_op_column_broadcast.h#L57). You may also be interested in the [`EpilogueVistiorTree`](https://github.com/NVIDIA/cutlass/blob/7bdba07310b497e75c8377031e524fadc929b849/tools/library/scripts/pycutlass/docs/source/md/EpilogueVisitorTree.md), which is an experimental feature that can compose multiple such epilogues together.
