### ISSUE TITLE
[BUG] cutlass 3 build errors

### ISSUE THREAD

**Issue by ipiszy** [NVIDIA/cutlass#788]
**Describe the bug**
cutlass 3 has build errors related to cute.
Lots of tests have build failures. AITemplate unittests also have lots of build failures.
This is a small portion of the error log: https://gist.github.com/ipiszy/5bc5cac3604d12fce13577d6ff0b0499. 

**Steps/Code to reproduce bug**
Check out latest cutlass revision.

export CUDACXX=${CUDA_INSTALL_PATH}/bin/nvcc
mkdir build && cd build
cmake .. -DCUTLASS_NVCC_ARCHS=80   
make test_unit -j

**Expected behavior**

**Environment details (please complete the following information):**
A100 host

**Additional context**

**Comment by thakkarV** [comment]
Can you please also post details about your host compiler version and cuda toolkit versions?

**Comment by ipiszy** [comment]
cuda version: 11.4

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0

gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-17)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mhoemmen** [comment]
Just FYI, GCC 8.5.0 has known regressions regarding fold expressions and overloaded operators.  Using GCC 7.5.0 or (preferred) GCC >= 9 may prove a more pleasant experience for C++ developers.  CUDA 12 + GCC 11 has shown to be even more pleasant.

**Comment by mhoemmen** [comment]
PR #789 has been tested with the most similar environment I had on hand, which was GCC 8.4 and CUDA 11.4.

@ipiszy , if you have the chance, could you please test this with your environment?  Thanks!
