### ISSUE TITLE
Question on how much memory & computation overlap in a GEMM

### ISSUE THREAD

**Issue by ThisIsIsaac** [NVIDIA/cutlass#79]
Do I think of the overall latency as `memory latency + compute latency` or `max(memory latency, compute latency)`? The former would imply that most of memory and compute are not overlapping, and latter would mean the opposite. 

Thanks!

**Comment by kerrmudgeon** [comment]
Yes, ideally data movement can be performed concurrent to computation, and the duration of a particular phase could be modeled as `max(memory_latency, compute_latency)`.
