### ISSUE TITLE
[QST] Should I use 3.x or 2.x API for gmem/smem reading/writing?

### ISSUE THREAD

**Issue by tridao** [NVIDIA/cutlass#792]
I've been going through the documentation for Cutlass 3.x and it seems like a great abstraction.
I'm planning to use Cutlass for gmem/smem reading/writing (e.g., TileIterator), and I'm targeting Turing/Ampere for now.

Should I be using the 2.x API or 3.x API? Is there a performance difference between the two?

My understanding is that Cutlass 2.x implements these as iterators (with custom swizzling to avoid bank conflicts). Cutlass 3.x uses `copy` atom with layout (composed with `Swizzle`).

**Comment by thakkarV** [comment]
Hi @tridao! Thanks a lot for your question and interesting in using CUTLASS. through the CUTLASS library/profiler, and in the collective builders, we only support Hopper kernels for now. That said, the CuTe abstractions and the CUTLASS non-TMA mainloops can support a wide range of GPU architectures, so in theory you should be able to use CUTLASS 3.0 in principle. The mainloop policy you would want for Turing is `MainloopSm70TwoStage` and for Ampere you would want `MainloopSm80CpAsync`. If you want examples of how to build 3.0 API kernels targeting Ampere/Turing, you can take a look at the test cases in various `test/unit/gemm/device/sm80_*.cu` which use kernel recipes defined in `test/unit/gemm/device/default_gemm_configuration.hpp`. Note that these default configs are not officially supported in the 3.0 API, simply used for regression testing our Sm70 and 80 mainloops.


That said, if you just want an off the shelf GEMM kernel or any other fused kernel that 2.x already has support for, I would highly recommend reaching for those recipes as it will likely save you time. If you are looking to customize the kernel instead, I would encourage you to check out CuTe and CUTLASS and implement it through the 3.x API :D

**Comment by tridao** [comment]
Thanks for the pointers! From reading the docs I'm really impressed with the CuTe abstractions so far! It's a very clean design.

I'm looking to customize the kernel. For smem reading/writing, I see that in Cutlass 2.x swizzling is done by [precomputing](https://github.com/NVIDIA/cutlass/blob/add4ba622f1cdebc145d1df0e9620c3c84c00a52/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator.h#L1475) the pointers and then move the pointers around during the iteration.
I haven't tried the API from Cutlass 3.x but it seems like swizzling is computed on the fly during the iteration, by [composing](https://github.com/NVIDIA/cutlass/blob/277bd6e5379e0c1e1eb64db1a654b30e1efddc8e/test/unit/gemm/device/default_gemm_configuration.hpp#L83) a layout with a `Swizzle`. Does that use more/fewer registers? What you guys seen performance difference between the two approaches?

**Comment by thakkarV** [comment]
Thanks for your impression! We are extremely excited for people like you to start hacking with CuTe, and hopefully it will make the experience a lot more pleasant for you :D

As for the swizzles being computed at runtime, that is not quite true. The swizzle layouts in CuTe are compositions of `cute::Layout` with a `cute::Swizzle`, which is of type (`ComposedLayout`)[include/cute/swizzle_layout.hpp]. When a composed layout is sliced (`layout_instace(_,slice,out,mode0)`), it can decay back to a regular layout, and if both of them are static, then the resultant slice is also static -- this means that for most well designed swizzle layouts, there should be no computation happening on the fly, however, if the slice does not decay to a regular layout, the code will still execute correctly, but with runtime swizzling.

For all of our Ampere example kernels, you can print out each tensor's layout in the kernel and see this swizzle smem decaying back to a regular layout. Let's look at `include/cutlass/gemm/collective/sm80_mma_multistage.hpp` for example. On line 180, we create the smem tensor by binding the smem pointer with the layout:

`Tensor sA = make_tensor(make_smem_ptr(storage.smem_a.data()), SmemLayoutA{}); // (BLK_M,BLK_K,PIPE)`

for most Ampere kernels, this will be a swizzled layout. We can confirm this by printing the layout of the tensor at runtime with `print(sA.layout())`. Let's say our smem layout is defined as:

```cpp
  auto swizzle_atom = composition(Swizzle<3,3,3>{},
                                  Layout<Shape <Shape <_2, _4, _2>,Shape <_8, _2,  _2>>,
                                         Stride<Stride<_8,_64,_32>,Stride<_1,_16,_256>>>{});

  auto sA = tile_to_shape(swizzle_atom, make_shape(bM,bK,bP));
```

then if we pick our thread layout for gmem->smem copy carefully, partitioning this smem layout with the thread layout for our gmem copy should result in a thread view of the tensor that has a layout that decays the swizzle away. We can inspect this with prints in the kernel to verify. the following is the output of an example kernel where I take the above smem layout and slice with a compatible thread layout.


```
Full sA layout is:
S<3,3,3> o _0 o ((_2,_4,_2,_8),(_8,_2,_2),_3):((_8,_64,_32,_512),(_1,_16,_256),_4096)

Thread layout for gmem->smem copy is tA:
(_32,_4):(_4,_1)

Result of partitioning sA with tA to produce tAsA is:
(_4,_1,_3):(_128,_0,_512)
```

by the way, let me post script this by saying that if you have a lot of work done already that targets pre-Hopper architectures in 2.x API, please do not feel pressured to migrate it to 3.0. 2.x will be supported for a while, and 3.0 should only be necessary for Hopper.

**Comment by tridao** [comment]
Amazing! Thanks a lot for the explanation @thakkarV.
I've always found smem swizzling to be the trickiest part of writing a fast gemm. It's crazy that you can replace thousands of lines of smem swizzling code with a few lines of well-designed and composable abstractions.

I'm excited to start hacking on CuTe!
