### ISSUE TITLE
[QST] Conv2d Wgrad has low performance when C=4 than cuDNN

### ISSUE THREAD

**Issue by apuaaChen** [NVIDIA/cutlass#793]
Hi!

I'm trying to implement the weight gradient kernel of the first layer in ResNet with cutlass. The problem size is as follows:
* N, H, W, C = 128, 224, 224, 4
* K, R, S = 64, 7, 7
* stride = [2, 2]
* padding = [3, 3]
* dilation = [1, 1]

The kernel takes float16 element_a, element_b, and element_c, with float32 accumulator. I tuned the kernel configuration and the optimal result I got is as follows
* instruction shape: [16, 8, 16]
* threadblock shape: [64, 64, 64]
* warp_shape: [32, 16, 64]
* pipeline stages: 3
* iterator algorithm optimized
* swizzling functor: IdentitySwizzle2
* split-k slices: 160 with serial split-k

However, the result evaluated on A100 is much worse than the `cutlass_cudnn::library::image_network_first_layer_hmma_wgrad_kernel`.  My cutlass kernel takes 1.31 ms, while the cudnn kernel only takes 0.459 us. The profiling also shows huge difference between data loaded from L2 cache:
![image](https://user-images.githubusercontent.com/34239936/215391292-097ee912-4585-4e8f-b8ce-73748143fdc7.png)
(cutlass kernel)
![image](https://user-images.githubusercontent.com/34239936/215391337-e46ddbc5-4f32-4c91-af32-b3a2f3b69615.png)
(cudnn kernel)

One possible reason I guess is that cudnn uses some different iterator algorithm like fixed channels for this special C=4 case. Because in the fprop kernel of the first layer, the fixed_channel iterator is also much faster than the optimized iterator. However, I didn't find the fixed_channel iterator for conv2d_wgrad in https://github.com/NVIDIA/cutlass/tree/master/include/cutlass/conv/threadblock.

By the way, I found that the `can_implement` function in wgrad activation iterator checks alignment of problem_size.K while output gradient iterator checks alignment of problem_size.C, which is different from dgrad iterators. Is this a typo? Or there are additional alignment requirement in wgrad.

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/conv2d_wgrad_activation_tile_access_iterator_optimized.h?plain=1#L307

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/conv2d_wgrad_output_gradient_tile_access_iterator_optimized.h?plain=1#L296

Thanks!

**Comment by hwu36** [comment]
We don't have a special kernel for first layer wgrad.  we welcome the community contribution.  It is actually easier since the output already linearizes RSC.

As to your question about `can_implement`, I think you are correct.

**Comment by apuaaChen** [comment]
Thanks!
