### ISSUE TITLE
[BUG] Int8 + align1 potentialy broken

### ISSUE THREAD

**Issue by masahi** [NVIDIA/cutlass#799]
Hi, [one of tests in TVM](https://github.com/apache/tvm/blob/main/tests/python/contrib/test_cutlass.py#L818) is broken with a compilation error if using the latest cutlass. The following assert added in v2.9 fails:
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h#L244-L251

The test exercises int8 input, int32 output kernel with align1.

This test used to work with the commit c2ee13a0 of cutlass. I don't know if the same template specialization was being used at that commit. Here is the CUDA source generated by TVM that contains the problematic kernel instantiation 
https://gist.github.com/masahi/c99ebdf323d15cad4e61736d3ed45cc5. This code fails to compile with the latest version, while it works for the commit c2ee13a0.

The full compilation options:
```
nvcc --shared -o ./tmp/cutlass.o ./tmp/lib0.cu -c -DCUTLASS_ENABLE_TENSOR_CORE_MMA=1 -gencode=arch=compute_80,code=[sm_80,compute_80] -Xcompiler=-fPIC -Xcompiler=-Wconversion -Xcompiler=-fno-strict-aliasing -O3 -std=c++17 -I/home/masa/projects/dev/relax/python/tvm/contrib/cutlass/../../../../3rdparty/cutlass/include -I/home/masa/projects/dev/relax/python/tvm/contrib/cutlass/../../../../3rdparty/cutlass/tools/util/include -t 12 -I/home/masa/projects/dev/relax/include -I/home/masa/projects/dev/relax/3rdparty/dlpack/include -I/home/masa/projects/dev/relax/3rdparty/dmlc-core/include
```

**Comment by jackkosaian** [comment]
Hi, @masahi.

The partial specialization that is raising the static assertion in question was added to support some of common epilogue patterns that use `int32_t` for the accumulator (e.g., when using `{u}int4_t` or `{u}int8_t` as the output type packed within 128 bits). The issue at hand is that this partial specialization is triggered for any epilogue with `int32_t` as the accumulator, but doesn't support output types other than those in the static assert list.

As a quick way to add back support for the epilogue you're using, you can try adding the following partial specialization to include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h:
```c++
template <
  int ElementsPerAccess,
  typename ThreadblockShape,
  typename WarpShape,
  typename InstructionShape,
  typename ThreadMap
>
struct DefaultIteratorsTensorOp<
  int32_t,
  int32_t,
  ElementsPerAccess,
  ThreadblockShape,
  WarpShape,
  InstructionShape,
  ThreadMap>
{

  using WarpTileIterator = cutlass::epilogue::warp::TileIteratorTensorOp<
    WarpShape,
    InstructionShape,
    int32_t,
    layout::RowMajor
  >;

  using SharedLoadIterator = cutlass::epilogue::threadblock::SharedLoadIterator<
    ThreadMap,
    int32_t
  >;

  static int const kFragmentsPerIteration = 1;
};
```

When I tried this out with the test case you provided (without the TVM parts), the test case compiled properly. I haven't tried running the test case, though, so I might have missed something along those lines.

This is likely not the ideal solution to the issue at hand, but should hopefully allow you to get things running.

I hope this helps!

**Comment by jackkosaian** [comment]
If possible, you could also use alignment of 4 -- this should be faster, and is supported by the existing partial specialization [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h#L139-L161).

Let me know if either of the above work for you.

**Comment by masahi** [comment]
Hi @jackkosaian, thank you for your response. The test case uses an input channel of size 3, so we have to use align1. And since we use cutlass via submodule, we don't want to modify the cutlass code itself. 

This is not an urgent problem, so we can wait until it is fixed on the cutlass side. Can your proposed fix be formally integrated to cutlass?

**Comment by jackkosaian** [comment]
Hi, @masahi. Yes, #807 addresses this.

**Comment by masahi** [comment]
Confirmed that the issue has been fixed. Thank you!
