### ISSUE TITLE
08_turing_tensorop_gemm test

### ISSUE THREAD

**Issue by jinz2014** [NVIDIA/cutlass#80]
Running the 08_turing_tensorop_gemm test on a Quadro RTX 6000  failed. Could you please advise how people can debug ?

Thanks

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+

**Comment by kerrmudgeon** [comment]
Hello.

You must compile this example with CUDA 10.2 Toolkit or later. This is the first Toolkit to expose the Turing Tensor Core instructions directly.

I see from the version string you helpfully included, you're compiling with CUDA 10.1.

Here is the [compatibility table indicating CUDA Toolkit version requirements](https://github.com/NVIDIA/cutlass#compatibility). 

Admittedly, our example should be capable of detecting this and printing the reason also. We'll plan on updating the example with more precise version checks in the near future.

I'll close this comment for now. Feel free to reopen if building with the [latest CUDA Toolkit](https://developer.nvidia.com/cuda-downloads) does not resolve your problem.
