### ISSUE TITLE
[DOC] incorrect comment! [DOC]

### ISSUE THREAD

**Issue by zhoutianzi666** [NVIDIA/cutlass#800]
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://github.com/NVIDIA/cutlass/blob/add4ba622f1cdebc145d1df0e9620c3c84c00a52/include/cutlass/transform/threadblock/regular_tile_iterator_pitch_linear.h#L280

should be specialized for row-major?

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by hwu36** [comment]
yes, it is row major.  we will fix it in the next release.  thank you for pointing it out.

**Comment by mnicely** [comment]
Fixed in 3.1
