### ISSUE TITLE
[QST] - Help to understand DefaultGemmWithBroadcast and RowMajor ColMajor inputs.

### ISSUE THREAD

**Issue by erees1** [NVIDIA/cutlass#801]
I have been trying to understand the specification for the arguments of `DefaultGemmWithBroadcast`, e.g. `TEST(SM75_Device_GemmWithBroadcast_GELU_f16n_f16n_f16n_tensor_op_f32, 128x128x32_64x64x8)` in `test/unit/gemm/device/gemm_with_broadcast_f16n_f16n_f16n_tensorop_f32_sm75.cu`.

I added a bunch of print statments to `test/unit/gemm/device/testbed_gemm_with_broadcast.h` to inspect the strides and layouts of the tensor:
```
[----------] 1 test from SM75_Device_GemmWithBroadcast_RELU_f16n_f16n_f16n_tensor_op_f32
[ RUN      ] SM75_Device_GemmWithBroadcast_RELU_f16n_f16n_f16n_tensor_op_f32.128x128x32_64x64x8
problem: problem_size.m() = 32, problem_size.n() = 64, problem_size.k() = 128
tensor_A.layout().stride(0) = 32
tensor_B.layout().stride(0) = 128
tensor_C.layout().stride(0) = 32
tensor_Z.layout().stride(0) = 32
tensor_Broadcast.layout().stride(0) = 32
tensor_T.layout().stride(0) = 32
tensor_A.layout()(0, 1) = 32
tensor_A.layout()(1, 0) = 1
tensor_B.layout()(0, 1) = 128
tensor_B.layout()(1, 0) = 1
tensor_C.layout()(0, 1) = 32
tensor_C.layout()(1, 0) = 1
tensor_Z.layout()(0, 1) = 32
tensor_Z.layout()(1, 0) = 1
tensor_Broadcast.layout()(0, 1) = 32
tensor_Broadcast.layout()(1, 0) = 1
tensor_T.layout()(0, 1) = 32
tensor_T.layout()(1, 0) = 1
```

given the above and my understanding of the difference between `RowMajor` and `ColumnMajor` e.g. [layout.md](https://github.com/NVIDIA/cutlass/blob/master/media/docs/layout.md) all of the tensors used in the test appear to be `ColumMajor`. This is what confuses me as the test itself specifies the inputs are `RowMajor` [e.g. here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_with_broadcast_f16n_f16n_f16n_tensorop_f32_sm75.cu#L117). 
```cpp
  using GemmKernel = 
    typename cutlass::gemm::kernel::DefaultGemmWithBroadcast<
      cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed B operand
      cutlass::half_t, cutlass::layout::RowMajor, cutlass::ComplexTransform::kNone, 8,    // transposed A operand
      cutlass::half_t, cutlass::layout::RowMajor,
      float,
```
and in `test/unit/gemm/device/testbed_gemm_with_broadcast.h` are [instantiated as such](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/testbed_gemm_with_broadcast.h#L118)
```cpp
struct TestbedGemmWithBroadcast {

  using ElementA = typename Gemm::ElementA;
  using ElementB = typename Gemm::ElementB;
  using OutputOp = typename Gemm::GemmKernel::Epilogue::OutputOp;
  using ElementC = typename Gemm::ElementC;
  using ElementAccumulator = typename Gemm::ElementAccumulator;
  using ElementCOmpute = typename OutputOp::ElementCompute;
  using ElementZ = typename OutputOp::ElementZ;
  using ElementT = typename OutputOp::ElementT;

  /// Initialization
  cutlass::Distribution::Kind init_A;
  cutlass::Distribution::Kind init_B;
  cutlass::Distribution::Kind init_C;
  uint64_t seed;

  cutlass::HostTensor<typename Gemm::ElementA, typename Gemm::LayoutA> tensor_A;          // Input A
  cutlass::HostTensor<typename Gemm::ElementB, typename Gemm::LayoutB> tensor_B;          // Input B
  cutlass::HostTensor<ElementC, typename Gemm::LayoutC> tensor_C;                         // Input C
  cutlass::HostTensor<ElementC, typename Gemm::LayoutC> tensor_Broadcast;                 // Input Broadcast

  cutlass::HostTensor<ElementZ, typename Gemm::LayoutC> tensor_Z;
  cutlass::HostTensor<ElementT, typename Gemm::LayoutC> tensor_T;

  cutlass::HostTensor<ElementAccumulator, typename Gemm::LayoutC> tensor_C_ref;
  cutlass::HostTensor<ElementAccumulator, typename Gemm::LayoutC> tensor_Y_ref;
  cutlass::HostTensor<ElementZ, typename Gemm::LayoutC> tensor_Z_ref;
  cutlass::HostTensor<ElementT, typename Gemm::LayoutC> tensor_T_ref;
```

So I'm just trying to understand whether the inputs need to be `RowMajor` or `ColumnMajor` and what is the reason for this discrepancy, or am I missing something about the implementation.

Thanks for your help!

**Comment by jackkosaian** [comment]
Hi, @erees1. You've touched upon a point that can be a bit confusing at first.

That test creates a `device::`-level GEMM using `GemmUniversalAdapter` [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/gemm/device/gemm_with_broadcast_f16n_f16n_f16n_tensorop_f32_sm75.cu#L132).

Under the hood, `GemmUniversalAdapter` for CUTLASS 2 kernels (the kernel in question is a "CUTLASS 2" kernel) will perform an internal transpose of operands if the `LayoutC` template parameter passed to it is `cutlass::Layout::RowMajor` (see [here](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal_adapter.h#L406-L407)). This "internal transpose" is [achieved ](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal_adapter.h#L423-L435)by CUTLASS's `MapArguments` utility. This utility [swaps and transposes](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_transpose_operands.h#L102-L112) the layouts for operands A and B and transposes layout C. Thus, the kernel in question in your case does actually have operands A, B, and C being column major, as they are transposed under the hood from the row major template parameters passed in to `GemmUniversalAdapter`.

You may also find [this discussion](https://github.com/NVIDIA/cutlass/discussions/666#discussioncomment-3906271) helpful.

**Comment by erees1** [comment]
Thanks for the quick reply @jackkosaian - That helps clear things up.

Just to check I am understanding correctly: 

- If kernel uses `GemmUniversalAdapter` + `LayoutC = RowMajor`, then I should setup my inputs to be the opposite of the layouts I specify to the template and then transpose my output
- If kernel uses `GemmUniversalAdapter` + `LayoutC = ColMajor`, or kernel does not use `GemmUniversalAdapter` (e.g. `Gemm` in `gemm/device/gemm.h` then I should follow what the template says

Thanks, Ed

**Comment by jackkosaian** [comment]
In general, for 2.x kernels, it is easiest to avoid using `GemmUniversalAdapter` altogether to avoid having to reason about these transposes. One should be able to use `GemmUniversal` instead of `GemmUniversalAdapter`. Note that a unit test using `GemmUniversalAdapter` does not mean that the kernel itself requires the use of `GemmUniversalAdapter`.

See [this answer](https://github.com/NVIDIA/cutlass/issues/611#issuecomment-1235036915) for more information.

**Comment by erees1** [comment]
Thanks, I will give that a go.  If I want to use  `cutlass::epilogue::thread::LinearCombinationBiasElementwise` as my epilogue should I use `GemmUniversal` or do I need to to use `GemmUniversalBroadcast`?

**Comment by jackkosaian** [comment]
Good catch. You'll want to use `GemmUniversalWithBroadcast`. In fact, the epilogue you mention is the default epilogue used for that kernel (see [here](https://github.com/NVIDIA/cutlass/blob/66d9cddc832c1cdc2b30a8755274f7f74640cfe6/include/cutlass/gemm/device/gemm_universal_with_broadcast.h#L100)).

**Comment by erees1** [comment]
Thanks for your help - closing!
