### ISSUE TITLE
[QST] Saving accumulators to shared memory in epilogue in Cutlass 3.x

### ISSUE THREAD

**Issue by tridao** [NVIDIA/cutlass#803]
I'm trying to figure out the epilogue of saving accumulators in registers to smem, then loading from smem to registers then finally writing to gmem. I'm using the `m16n8k16` mma instruction Ampere.

In Cutlass 2.x I was using [`SharedLoadIterator`](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/shared_load_iterator.h) to save accumulators to smem, and [`TileIteratorTensorOp`](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/warp/tile_iterator_tensor_op.h) to load from smem back to registers. 

Is there something equivalent in Cutlass 3.x? I see the DefaultEpilogue just writes the accumulators straight from registers to gmem, which might not be efficient since the writes aren't coalesced.

**Comment by thakkarV** [comment]
Hi! Have you seen example 50? It's for the Hopper instruction, but does showcase the `cutlass::epilogue::collective::Epilogue` which does exactly what you're asking about. You may have to modify the swizzle atom itself a little for your particular MMA but overall it'll be similar to example 50

**Comment by tridao** [comment]
I got it to work by adapting example 50! Thanks for the pointer.
