### ISSUE TITLE
[QST] How to use matrix multiply-add operation: F32 = F16 * F16 + F32 of matrix size 8 * 8 * 4 when SmArch = SM80?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#804]
I want to use **matrix multiply-add operation: F32 = F16 * F16 + F32 of matrix size 8 * 8 * 4 on A100**. So I set those arguments and feed them to the Gemm template:
`using ShapeMMAThreadBlock = cutlass::gemm::GemmShape<64, 64, 32>; `
`using ShapeMMAWarp = cutlass::gemm::GemmShape<32, 32, 32>;`
`using ShapeMMAOp = cutlass::gemm::GemmShape<8, 8, 4>;`
`using SmArch = cutlass::arch::Sm80;`
`using Stages = 3`

But I get a **compilation error** : `mma_tensor_op_policy.h(58): error: incomplete type is not allowed`

Then I find that for SM80, the cutlass will use `mma_tensor_op.h` to do the matrix multiply-add on warp level. And this head file only includes :
`#include "cutlass/arch/mma_sm75.h" `
`#include "cutlass/arch/mma_sm80.h"`
 Clearly, it **doesn't include** `mma_sm70.h`. so I can't use the instruction I want.

If I want to use that instruction, I can only set those arguments:
`using SmArch = cutlass::arch::Sm70;`
`using Stages = 2`

But I do want the **architecture to be Sm80**, because I want to use `mma_multistage.h` to do matrix multiply-add operation operation, instead of `mma_pipelined.h`

So how can I use tensor core's matrix multiply-add operation: F32 = F16 * F16 + F32 of matrix size 8 * 8 * 4 when SmArch = SM80? 
Sincerely thank you for your help! :)

**Comment by jackkosaian** [comment]
Using instruction shape `<8, 8, 4>` on SM80 is not expected to achieve high performance. [This note](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-mma) from the PTX documentation indicates this:
> **Note:** mma.sync.m8n8k4 is optimized for target architecture sm_70 and may have substantially reduced performance on other target architectures.

The CUTLASS multistage pipeline helps to feed the faster Tensor Core instructions available on Ampere GPUs. It is unlikely to provide significant benefits for the instruction shape you mention.

If it is possible, it would be preferable for your application to use the `<16, 8, 16>` instruction shape, which should both be faster and allow you to use existing templates in CUTLASS leveraging multistage capabilities.

**Comment by Ther-LF** [comment]
Get it! Thanks! :)
