### ISSUE TITLE
[QST] How to properly use splitK in GEMM?

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#808]
**What is your question?**
Hi,
When using `cutlass::gemm::device::GemmUniversal`, the 1st argument is to choose `cutlass::gemm::GemmUniversalMode`, which is defined in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/gemm.h#L407

I'm wondering how to properly use this parameter when my problem size MNK is different.

E.g. normal GEMM can use `kGemm` and if K is much larger than M&N, then `kGemmSplitKParallel` can be used. Is this setting correct for best performance?

Then for batch gemm I can use `kBatched`, but if I want to use both `kBatched` and `kGemmSplitKParallel`, how to correctly set the parameter?

Thanks in advance!

**Comment by umiswing** [comment]
> E.g. normal GEMM can use kGemm and if K is much larger than M&N, then kGemmSplitKParallel can be used. Is this setting correct for best performance?

For large k, parallel on k-dimesion is necessary, so ```kGemmSplitKParallel``` will be a good choice. You will have to set a split-k size also, some split-k size will slow down your kernel, so be careful. profiler of cutlass can help pick the best config.

If you're not familiar with the profiler, you can check cutlass's doc or read this for tl;dr if you know chinese :): https://github.com/umiswing/cutlassProfilerUsage/blob/main/cutlass_profiler.md

I'm not familiar with cutlass's batch gemm, but cutlass has not support split-k for group gemm yet, and group gemm is similar with batch gemm.

You can check the code under https://github.com/NVIDIA/cutlass/tree/master/include/cutlass/gemm/kernel to confirm, may be gemm_universal.h and gemm_batched.h is what you want.

**Comment by hwu36** [comment]
@umiswing , thank you for helping us answering issues.  you are correct in your answers.

`kGemm` includes both regular gemm and serial splitK gemm.  you can use profiler to choose either using serial splitk or parallel splitk as well as splitk slice number.  usually, large splitk slice number would be better to run with parallel splitk.

batch gemm does not go with splitk since they are both used to saturate gpu.  using only one of them is enough usually.

cutlass 2.11 has streamk now which is a generalized version of splitk, you can check out this example: https://github.com/NVIDIA/cutlass/tree/master/examples/47_ampere_gemm_universal_streamk .  streamk should be better than traditional splitk.

**Comment by TUMSchieben** [comment]
> @umiswing , thank you for helping us answering issues. you are correct in your answers.
> 
> `kGemm` includes both regular gemm and serial splitK gemm. you can use profiler to choose either using serial splitk or parallel splitk as well as splitk slice number. usually, large splitk slice number would be better to run with parallel splitk.
> 
> batch gemm does not go with splitk since they are both used to saturate gpu. using only one of them is enough usually.
> 
> cutlass 2.11 has streamk now which is a generalized version of splitk, you can check out this example: https://github.com/NVIDIA/cutlass/tree/master/examples/47_ampere_gemm_universal_streamk . streamk should be better than traditional splitk.

Thanks for the explanation. For `streamk`, then how to choose a proper `k` for best performance?

**Comment by hwu36** [comment]
Streamk takes care of it for you by default.  You can also try the number yourself as shown in the example.  You can use cutlass profiler to get the best slices number.

**Comment by TUMSchieben** [comment]
> Streamk takes care of it for you by default. You can also try the number yourself as shown in the example. You can use cutlass profiler to get the best slices number.

In example 47(https://github.com/NVIDIA/cutlass/blob/master/examples/47_ampere_gemm_universal_streamk/ampere_gemm_universal_streamk.cu#L350), there is a `split_k` in the argument, is this parameter used to set slices number?

**Comment by hwu36** [comment]
Yes

**Comment by TUMSchieben** [comment]
> Yes

So is `splitK=1` the default mode in which the slices number is auto-selected by the algorithm?

**Comment by hwu36** [comment]
Yes.

Check https://github.com/NVIDIA/cutlass/blob/ce8597dc14b2e84e0661093ed255c888606ef672/include/cutlass/gemm/kernel/gemm_universal_streamk.h#L173

**Comment by TUMSchieben** [comment]
> Yes.
> 
> Check
> 
> https://github.com/NVIDIA/cutlass/blob/ce8597dc14b2e84e0661093ed255c888606ef672/include/cutlass/gemm/kernel/gemm_universal_streamk.h#L173

Hi, I found that currently `cutlass::gemm::threadblock::ThreadblockSwizzleStreamK` cannot work with `cutlass::gemm::device::GemmUniversalWithBroadcast`, the compilation error is:
> error: class "cutlass::gemm::threadblock::ThreadblockSwizzleStreamK" has no member "get_tiled_shape"
Is there any workaround to fix this?

**Comment by hwu36** [comment]
We haven't enable streamk to gemm with epilogue fusion. You can compare gemm with epilogue fusion vs gemm universal, and add the same diff on top of streamk yourself.
