### ISSUE TITLE
compile options

### ISSUE THREAD

**Issue by mahmoodn** [NVIDIA/cutlass#81]
May I know what are the command line options for building basic_gemm?
https://github.com/NVIDIA/cutlass/blob/master/examples/00_basic_gemm/basic_gemm.cu

**Comment by kerrmudgeon** [comment]
I suggest following the one-time build steps described in the [quickstart guide](https://github.com/NVIDIA/cutlass/blob/master/media/docs/quickstart.md#initial-build-steps).

Here's the complete recipe assuming you are compiling for the Turing architecture with CUDA 10.2.

Construct a `build/` directory and run cmake.
```c++
$ mkdir build && cd build

$ export CUDACXX=${CUDA_INSTALL_PATH}/bin/nvcc

$ cmake .. -DCUTLASS_NVCC_ARCHS=75
```

Then you can build strictly the `00_basic_gemm` example from your `build/` directory:
```c++
$ make 00_basic_gemm 
```

And run from your `build/` directory:
```c++
$ ./examples/00_basic_gemm/00_basic_gemm
```
