### ISSUE TITLE
[QST]Can I reproduce the performance on ResNet50?

### ISSUE THREAD

**Issue by Claireeeee** [NVIDIA/cutlass#811]
Hi,

I noticed in the README.md that the performance of cutlass when running Resnet-50 layers on an NVIDIA A100 is compared with cuDNN and the result is showed in a figure. Is the code used in this experiment in the repo? (I didn't found it.) Can I get a copy and try to reproduce the experiment in my own environment?

Thank you so much!

**Comment by hwu36** [comment]
We used [cutlass profiler ](https://github.com/NVIDIA/cutlass/blob/master/media/docs/profiler.md) to get cutlass performance.  You could find resnet50 layer number in [here](https://github.com/NVIDIA/cutlass/blob/master/test/unit/conv/device/conv2d_problems.h#L520).

Your command line would be something like

```--operation=conv2d  - --clock=[your_lock_clock] --conv-kind=fprop } --providers=cutlass --batch-size=34  --split-k-slices=1:6:1  --append=true --output=conv2d_fprop_resnet50_performance.csv, --n=, --h=, --w=, --c=, ...```

You can use *cmake .. -DCUTLASS_NVCC_ARCHS=80 -DCUTLASS_LIBRARY_KERNELS="cutlass_tensorop_f16_s*fprop*_f16*""  to only generate the fprop kernels that use fp16 i/o, fp32 accumulation.

Alternatively, you can use [this](https://github.com/facebookincubator/AITemplate/tree/main/examples/01_resnet-50) to profile cutlass.

**Comment by Claireeeee** [comment]
@hwu36 Thank you so much for your help! Have a good day!
