### ISSUE TITLE
[QST] How to use CUTLASS with CLANG?

### ISSUE THREAD

**Issue by ShuaiShao93** [NVIDIA/cutlass#813]
It seems when compiling with CLANG, the s8 conv is significantly slower than that with NVCC. I used nsight compute to confirm that both CLANG and NVCC compiled kernels utilize IMMA tensor cores, then why is CLANG slower?

And is there any workaround for CLANG? For example, can we use NVCC to compile a Shared Object, and dynamically link it into the main program that's compiled with CLANG? Can we get equivalent latency as a pure NVCC compiled program?

**Comment by hwu36** [comment]
> then why is CLANG slower?
try `cuobjdump --dump-resource-usage` to get the STACK usage from the object file or binary.  If it is non zero, it means clang spills.  That would be my guess.

> For example, can we use NVCC to compile a Shared Object, and dynamically link it into the main program that's compiled with CLANG? 

I haven't tried it myself, but I think it makes sense.

**Comment by ShuaiShao93** [comment]
Thanks!

>try cuobjdump --dump-resource-usage to get the STACK usage from the object file or binary. If it is non zero, it means clang spills. That would be my guess.

You are right. The stack usage of both CLANG and NVCC binaries are non zero, but CLANG is higher than NVCC:
- CLANG: REG:93 STACK:656
- NVCC: REG:232 STACK:288

What does this imply? Does this mean NVCC optimizes it better?

I also did some experiments with 4 different approaches, but it seems the best approach in single-op benchmark doesn't work better in an actual large model, can you give some advice?

1. Pure NVCC
2. Pure CLANG
3. NVCC static lib in CLANG binary
4. NVCC dynamic lib in CLANG binary

- In a single-op benchmark, the latency is:  1 = 3 < 2 < 4
  - 1 = 3: 0.07ms
  - 2: 2.3ms
  - 4: 9ms
- In an actual model: 3 = 4 < 2
  - Not able to test 1

**Comment by ShuaiShao93** [comment]
Actually in both cases, static linking can match the pure nvcc latency. I'll just use it

**Comment by hwu36** [comment]
>     CLANG: REG:93 STACK:656
>     NVCC: REG:232 STACK:288

That does not sound right.  Your number shows that the compiler cannot figure out some compile time constants and has to use the local memory.  What kernel are you building?  What version of cutlass do you use?  We recently fixed a bug in #806 .  What version of nvcc do you use?

**Comment by ShuaiShao93** [comment]
>That does not sound right. Your number shows that the compiler cannot figure out some compile time constants and has to use the local memory. What kernel are you building? What version of cutlass do you use? We recently fixed a bug in https://github.com/NVIDIA/cutlass/pull/806 . What version of nvcc do you use?

DefaultConv2dFpropWithBroadcast with LinearCombinationBiasElementwise.

The CUTLASS commit I'm using is 8b42e751c63ba219755c8ed91af5f6ec1ecc1ee6. I tried patching https://github.com/NVIDIA/cutlass/pull/806 but there is no difference.

nvcc version is 11.2

**Comment by hwu36** [comment]
11.2 is pretty old.  cutlass at least needs 11.3+ to get reasonable performance.  the newer the better.

**Comment by hwu36** [comment]
if it is conv, it needs at least 11.4+.

**Comment by ShuaiShao93** [comment]
I see. We will do an upgrade soon, and will get back later.

So it's expected that NVCC performs better, and it's better to compile the CUTLASS part with NVCC even after the upgrade?

**Comment by hwu36** [comment]
We work with nvcc team together to improve cutlass performance.  We don't run with clang regularly.
