### ISSUE TITLE
[QST] Why does PredicatedTileAccessIteratorPredicates use 2 bits per predicate instead of 1 bit

### ISSUE THREAD

**Issue by tridao** [NVIDIA/cutlass#814]
I see that `PredicatedTileAccessIteratorPredicates` uses 2 [bits](https://github.com/NVIDIA/cutlass/blob/ce8597dc14b2e84e0661093ed255c888606ef672/include/cutlass/transform/threadblock/predicated_tile_access_iterator.h#L91) (4 predicates per byte) to store a predicate. 
There's also the `PackPredicates` class (used in ReLU epilogue) that uses 1 [bit](https://github.com/NVIDIA/cutlass/blob/66d9cddc832c1cdc2b30a8755274f7f74640cfe6/include/cutlass/numeric_conversion.h#L2427) per predicate. 
Out of curiosity, why does one class use 2 bits and the other use 1 bit?

**Comment by hwu36** [comment]
Due to some internal reason.
