### ISSUE TITLE
[QST] is Cutlass support custom Padding Value ？

### ISSUE THREAD

**Issue by huangxiao2008** [NVIDIA/cutlass#817]
In asymmetric quantization，the padding value for an 8bit fprop convolution is Zero_Point according to quantization rules.

However, if I know correct, cutlass provides no such params for users to set the padding value when constructing a quantize conv operator, the default value load from global memory is hardcoded to 0.

So, is there any way for us to set the customized padding value ?

**Comment by hwu36** [comment]
You need to do some source code change.

In conv mainloop, we use `cp_async_zfill` (for example https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_multistage.h#L219) to fill the oob data as 0 in the shared memory.  The call to `valid` will determine if it is oob or not.

you can change it to fill with different values.  for example, we can fill it with nan (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/memory_sm80.h#L189)

**Comment by huangxiao2008** [comment]
> You need to do some source code change.
> 
> In conv mainloop, we use `cp_async_zfill` (for example https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/threadblock/implicit_gemm_multistage.h#L219) to fill the oob data as 0 in the shared memory. The call to `valid` will determine if it is oob or not.
> 
> you can change it to fill with different values. for example, we can fill it with nan (https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/memory_sm80.h#L189)

Thanks， I’ll dive into the code
