### ISSUE TITLE
[QST] Official CUTLASS 3.0 release

### ISSUE THREAD

**Issue by davidthomas426** [NVIDIA/cutlass#824]
**What is your question?**
When will CUTLASS 3.0 get an official release? It's not listed on the GitHub releases page, and there's no tag for it.

**Comment by thakkarV** [comment]
Soon. Since this is a major release, we wanted to have a bigger window for the community to find bugs. We have a few minor fixes to put out, so expect for 3.0 to get tagged in the next few weeks.

**Comment by mnicely** [comment]
Should be tagged this week!
