### ISSUE TITLE
[QST] Does LinearCombinationResidualBlock support "conv2d + biasadd + eltadd + leakyrelu" pattern?

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#825]
**What is your question?**
Hi all,

I'd like to use `LinearCombinationResidualBlock ` to instance **conv2d + biasadd + eltadd + leakyrelu** pattern. I managed to use the following code to instance **conv2d + biasadd + eltadd + relu** pattern:

```
using ThreadblockShape = cutlass::gemm::GemmShape<128, 128, 32>;
using WarpShape = cutlass::gemm::GemmShape<64, 64, 32>;
using InstructionShape = cutlass::gemm::GemmShape<16, 8, 8>;

constexpr int NumStages = 3;

using EpilogueOp = cutlass::epilogue::thread::LinearCombinationResidualBlock<
    ElementOutput,
    ElementAccumulator,
    ElementComputeEpilogue,
    ElementOutput,
    4,
    cutlass::epilogue::thread::Identity,
    cutlass::plus,
    cutlass::epilogue::thread::ReLu>;

using Conv2dFpropKernel = typename cutlass::conv::kernel::DefaultConv2dFpropWithBroadcast<
  ElementInputA, LayoutInputA,
  ElementInputB, LayoutInputB,
  ElementOutput, LayoutOutput,
  ElementAccumulator,
  cutlass::arch::OpClassTensorOp,
  cutlass::arch::Sm80,
  ThreadblockShape,
  WarpShape,
  InstructionShape,
  EpilogueOp,
  cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<4>,
  NumStages,
  cutlass::arch::OpMultiplyAdd,
  cutlass::conv::IteratorAlgorithm::kOptimized,
  cutlass::conv::StrideSupport::kStrided,
  4,
  4
>::Kernel;
```

However, if I change `LinearCombinationResidualBlock` to adapt leakyrelu:

```
using EpilogueOp = cutlass::epilogue::thread::LinearCombinationResidualBlock<
    ElementOutput,
    ElementAccumulator,
    ElementComputeEpilogue,
    ElementOutput,
    4,
    cutlass::epilogue::thread::Identity,
    cutlass::plus,
    cutlass::epilogue::thread::LeakyReLU>;
```

it will give compilation error: 

```
error: no instance of overloaded function "cutlass::epilogue::thread::LeakyReLU<cutlass::Array<T, N, <expression>>>::operator() [with T=float, N=1]" matches the argument list
            argument types are: (cutlass::Array<float, 1, true>)
            object type is: cutlass::epilogue::thread::LeakyReLU<cutlass::Array<float, 1, true>>
```

So does `LinearCombinationResidualBlock `currently support `cutlass::epilogue::thread::LeakyReLU`?

Thanks a lot!

**Comment by hwu36** [comment]
First, you set `ElementsPerAccess` to 4, why your array size `N` is 1.  If it is one, it is a scalar value and you can just use this one https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/activation.h#L173 .  Otherwise, it is really an array, you can use https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/activation.h#L208.

Second, `operator()` expects 2 arguments, not just one.  That is why you got the error.

**Comment by TUMSchieben** [comment]
> First, you set `ElementsPerAccess` to 4, why your array size `N` is 1. If it is one, it is a scalar value and you can just use this one https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/activation.h#L173 . Otherwise, it is really an array, you can use https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/activation.h#L208.

Sorry for the mis-confused error of `ElementsPerAccess`.

> 
> Second, `operator()` expects 2 arguments, not just one. That is why you got the error.

Yes, I noticed that `LeakyReLU<Array<T, N>> operator()` expects 2 arguments, but how to set the extra args in `LinearCombinationResidualBlock` definition?

**Comment by hwu36** [comment]
We can just set the default value to 1 or any other number you want.

Or we can add a new LinearCombinationResidualBlockLeakyRelu
