### ISSUE TITLE
[QST] CUTLASS kernels 8x slower in a model than in a single-kernel benchmark

### ISSUE THREAD

**Issue by ShuaiShao93** [NVIDIA/cutlass#827]
When we run a `--n=1 --h=302 --w=480 --c=16 --k=32 --r=3 --s=3` int8 conv in a standalone benchmark, it only takes 0.1-0.2ms. But when we run it in an actual model that sequentially runs all the ops, I expect it to be as fast as the kernel benchmark, but Nsight System shows it actually takes 1.4ms, which is 8x slower than the kernel benchmark.

Since the model runs all ops sequentially, there should be no resource contention, why does it become so slow?

**Comment by hwu36** [comment]
Are you using an old nsight?  It can slow your system down. You may need to reset it.  New nsight is fine.

**Comment by ShuaiShao93** [comment]
> Are you using an old nsight? It can slow your system down. You may need to reset it. New nsight is fine.

It's a fairly new version. And the model end-to-end latency is only 10% slower when nsys is enabled, so it's probably not the root cause

**Comment by hwu36** [comment]
Btw, have you used cuda graph?

**Comment by hwu36** [comment]
What about using cuda event?  Does slow down appear in other layers?

**Comment by ShuaiShao93** [comment]
> Btw, have you used cuda graph?

No, we have our own runtime that runs all ops sequentially.

> What about using cuda event? Does slow down appear in other layers?

I didn't use cuda event in model benchmark, but we use it in autotuning that finds the fastest kernel for each op. I also observed the slowdown there compared to single op benchmark. (1.5ms -> 0.7ms). Since it also runs all ops sequentially, I guess it's somewhat similar to the full model inference?

**Comment by hwu36** [comment]
You still can run cuda graph which can save you kernel launch time.

I've never heard the problem you have, maybe you can compare cuda event report time with nsight.  Just insert many cuda events everywhere and see where the time goes and compare with nsight.

Are you measuring a cold kernel in both cases or a kernel is already warmed up?

**Comment by ShuaiShao93** [comment]
> You still can run cuda graph which can save you kernel launch time.

How can I inspect the kernel launch time right now? I don't see obvious gap between ops in nsys.

> I've never heard the problem you have, maybe you can compare cuda event report time with nsight. Just insert many cuda events everywhere and see where the time goes and compare with nsight.

I inserted the cuda events for every op, and the cuda event latency can mostly match the nsys, for example, 501us vs 509us, but the same kernel in separate benchmark took only 80us. What do you think can make it slow in a model?

> Are you measuring a cold kernel in both cases or a kernel is already warmed up?

Both are warmed up.

**Comment by hwu36** [comment]
> How can I inspect the kernel launch time right now? I don't see obvious gap between ops in nsys.

you cannot.  it is part of kernel runtime.

Did you lock freq and power when you do apple to apple comparison.  if a kernel hit throttle, its performance can drop a lot.

Another way is to compare with cutlass profiler, you can ignore the epilogue difference in most of the cases.

**Comment by ShuaiShao93** [comment]
> you cannot. it is part of kernel runtime.
> 
> Did you lock freq and power when you do apple to apple comparison. if a kernel hit throttle, its performance can drop a lot.

No, what's the suggested way to lock it?

> Another way is to compare with cutlass profiler, you can ignore the epilogue difference in most of the cases.

Yeah I did it, and the cutlass profiler can match the single-op benchmark I mentioned above. So it's only slow in an actual model that runs many ops sequentially.

**Comment by hwu36** [comment]
Take A100 as example

```
sudo nvidia-smi -i 0 -pm 1 # persistent mode 
sudo nvidia-smi -lgc 1005 -i 0  #set to 1005MHz.  peak of A100 is 1450 MHz
sudo nvidia-smi --power-limit=400 -i 0  # set to 400W, max of A100
```

**Comment by ShuaiShao93** [comment]
Not much difference in both cases

**Comment by hwu36** [comment]
check nsight with both and see what metrics getting worse?

**Comment by ShuaiShao93** [comment]
> check nsight with both and see what metrics getting worse?

What kind of metrics are you referring to?

**Comment by hwu36** [comment]
cache, memory latency, etc.

**Comment by mnicely** [comment]
@ShuaiShao93 can you share a screenshot of the Nsight Systems GUI with this performance issue?

**Comment by ShuaiShao93** [comment]
Sorry, I just realized that the input sizes are different. I thought N dim is always 1, but it's actually not. When I set correct N in benchmark, they can match now.
