### ISSUE TITLE
[QST] How does CUTLASS solve the problem that the problem size cannot be divisible by ShapeMMAThreadBlock?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#831]
I am building an operator based on CUTLASS which utilizes tensor core. For now the operator can only slove the problem size which is divisible by ShapeMMAOp as well as ShapeMMAThreadBlock. 
If I use the operator to solve the problem whose size isn't divisible by ShapeMMAThreadBlock, it will encounter the error: ` Warp illegal address` or `Error Misaligned Operand`. And I have tested the `ampere_tf32_tensorop_gemm.cu` in `examples/14_ampere_tf32_tensorop_gemm` whose result is just the same. 
However, the profiler in `tools/profiler/` can slove the problem whose size is various. So I am wondering is there a trigger in cutlass to open the auto-padding function or any other method to solve this problem?
Sincerely thank you for your help:-)

**Comment by Ther-LF** [comment]
Besides, if I want my operator to achieve a good performance, is it necessary to set the operand A and operand B to be row-major and col-major respectively? Since @kerrmudgeon in this link:[cutlass calculate matrix size problem](https://github.com/NVIDIA/cutlass/issues/75) has said so. 
But I find the codes in `examples/` all use the layout in col-row-row(A-B-C). And some codes that try to construct an gemm operator using mma instruction just use the layout in row-row-row(A-B-C). 
So does layout really matter when using tensor core?

**Comment by hwu36** [comment]
col x row usually has the best perf by a little bit.

**Comment by hwu36** [comment]
In https://github.com/NVIDIA/cutlass/blob/91b8de8d3273f73c1de97312b639084baf3269b0/include/cutlass/gemm/threadblock/mma_multistage.h#L314, when we call `cp_async_zfill` to load data from the global memory to the shared memory, if `iterator_A.valid()` is `false`, zeros will be stored into the shared memory automatically.

**Comment by Ther-LF** [comment]
Thank you for pointing out this usefule function!
To use `cp_async_zfill`, I find that we need to set the `SharedMemoryClearOption` in https://github.com/NVIDIA/cutlass/blob/91b8de8d3273f73c1de97312b639084baf3269b0/include/cutlass/gemm/device/gemm.h#L284 to be `SharedMemoryClearOption::kZfill`.
But there is no way to set this argument in the template class `Gemm`, so I just replace the defalut argument `SharedMemoryClearOption::kNone` in `Gemm` with `SharedMemoryClearOption::kZfill`. 
However, it still can't work. The kernel's `can_implement` function will return the error : `Error Misaligned Operand`. And if I don't care about the error returned and keep going, there will occur an execption : 
``` 
CUDA Exception: Warp Misaligned Address
The exception was triggered at PC 0x555555f55e40 (memory.h:287) 
```
Is there anything wrong?
Here is my test code which I remove most of the unrelevant codes.
```
#include otherfiles...
#include "cutlass/cutlass.h"
#include "cutlass/gemm/device/gemm.h"

/* 
  Set the element type, operator type, sm arch and so on
*/

// This code section describes the tile size a thread block will compute
using ShapeMMAThreadBlock =
    cutlass::gemm::GemmShape<128, 128, 32>;  // <- threadblock tile M = 128, N = 128, K = 32
// This code section describes tile size a warp will compute
using ShapeMMAWarp = cutlass::gemm::GemmShape<64, 32, 32>;  // <- warp tile M = 64, N = 64, K = 32 
// This code section describes the size of MMA op
using ShapeMMAOp = cutlass::gemm::GemmShape<16, 8, 8>;  // <- MMA Op tile M = 8, N = 8, K = 4

using Gemm = cutlass::gemm::device::Gemm<..some argument..>;

int run() {
  // problem size: NOT divisible by ShapeMMAThreadBlock
  const int length_m = 5120;
  const int length_n = 4094;
  const int length_k = 4095;

  // Create a tuple of problem size for matrix multiplication
  cutlass::gemm::GemmCoord problem_size(length_m, length_n, length_k);

  /*
    prepare the operand a,b,c and d
    set the alpha and beta
    get the Arguments structure
  */

  // Instantiate CUTLASS kernel depending on templates
  Gemm gemm_op;
  cutlass::Status status;
  // Check the problem size is supported or not 
  status = gemm_op.can_implement(arguments);
  CUTLASS_CHECK(status);

  status = gemm_op.initialize(arguments, workspace.get());

  // Launch initialized CUTLASS kernel
  status = gemm_op();
}
```
And here is my compiling command:
```
nvcc test.cu -O3 --std=c++11 --gpu-architecture=compute_80 --gpu-code=sm_80,compute_80  -G -g -L /usr/local/lib  -I /usr/local/cuda/samples/common/inc  -I /gitRepo/cutlass/include/ -I /gitRepo/cutlass/tools/util/include/ -I ../common/ -o test
```

**Comment by hwu36** [comment]
what is your data type and layouts?  Your problem is an alignment issue, ie, your leading dimension needs to be the multiple of the alignment.  by default, we assume the alignment to be 128bit which is 8 fp16 or 4 fp32.  Your K is 4095 which is an odd number.

**Comment by Ther-LF** [comment]
Thank you for pointing out this problem!
The matrix A and matrix B's data type are both `cutlass::half`, and their layouts are col x row. So the alignment is `128bit / 16bit = 8`. But the matrix A and matrix B's leading dimension are `length_m = 5120` and `length_n = 4094` respectively, `4094` is not divisible by `8`. 
Based on that, I modify the problem size to be `{5120, 4096, 4095} `. And I set the parameter `SharedMemoryClear` to be `SharedMemoryClearOption::kZfill`. It works well!
But I find that if I set the parameter `SharedMemoryClear` to be `SharedMemoryClearOption::kNone`. It also works well. So there is another question:
In https://github.com/NVIDIA/cutlass/blob/91b8de8d3273f73c1de97312b639084baf3269b0/include/cutlass/gemm/threadblock/mma_multistage.h#L314
If we set the parameter `SharedMemoryClear` to be `SharedMemoryClearOption::kNone`, it will use the function `cutlass::arch::cp_async`. And in [`cutlass::arch::cp_async`](https://github.com/NVIDIA/cutlass/blob/91b8de8d3273f73c1de97312b639084baf3269b0/include/cutlass/arch/memory_sm80.h#L124), if the `pred_guard` is `false`, it just doesn't transfer the data from global memory to shared memory. 
I think if the problem size can't be divisible by ShapeMMAThreadBlock, there will be some content that is redundant in shared memory. And if we don't do anything to this redundant memory, it will keep their original data which may not be zeros. These redundant data will mess up the computation and get a wrong result.
So why `SharedMemoryClearOption::kNone`  can also have a correct result?

**Comment by hwu36** [comment]
you don't need to touch `SharedMemoryClearOption` if you do a regular gemm.

When we load the first threadblock tile, we can load small data from the k dimension.  the extra part will be padded with zero by using zfill.  After the first tile, we load full tiles so we don't have to use zfill version.  For example, if K = 80 and threadblock tile is 32,

1st tile: 16
2nd tile: 32
3rd tile: 32

Half of the 1st tile will be padded with zeros.  when we load some tiles in the future, the 1st tile data will be overwritten.

**Comment by Ther-LF** [comment]
Very clear! I get it! Sincerely thank you for your help! : - ) Closed~

**Comment by Ther-LF** [comment]
I am wondering how cutlass handle the problem that m or n dimensino cannot be divisible by ShapeMMAThreadBlock? For example, if we have the problem size : `{152, 72, 66}` with ShapeMMAThreadBlock to be `{128, 64, 32}`, we can know cutlass partition the problem into this shape from the method mentioned above and the code https://github.com/NVIDIA/cutlass/blob/a31b43b3f3cb609c6ed0b30ca330d766291e84fb/include/cutlass/gemm/kernel/gemm.h#L219 
```
   A:    |--2--|--32--|--32--|           
  ——  
   |
  128
   |
  ——
   |
   24
   |
  ——

   B:    |--64--|--8--|         
  ——  
   |
   2
   |
  ——
   |
   32
   |
  ——
   |
   32
   |
  ——

```
Both of the last tile in m and n dimension can't fill up a threadblock tile, so do they also need a zero padding? I can't find the code that cutlass handle this issue specially. 
Sincerely thank you for your help:-)

**Comment by thakkarV** [comment]
See media/docs/cute/0y_predication.md for details on how we handle partial tiled. The general approach is the compute full tiles only but predicate away the invalid elements during the gmem to smem copy

**Comment by Ther-LF** [comment]
Thank you for pointing out this helpful document! Closed~:-)
