### ISSUE TITLE
[QST] Why is data being read from L2 to L1 cache for CUTLASS GEMM when no data is leaving L1 cache?

### ISSUE THREAD

**Issue by rkindi** [NVIDIA/cutlass#833]
I was running the GEMM problem size and kernel configuration in CUTLASS below & looking at the kernel in Nsight Compute (ncu).  This is a GEMM without any epilogue (beta=0) which can be seen because there is an arrow from "Global" to "Kernel" with 0 requests. However, for some reason, I see some data going from L2 cache to L1 cache. I can see some data that goes from L2, bypassing L1, to shared memory and that part makes sense because of the `cp.async` to load the A and B operands but what is the reason for the other data (63 MB) to be loaded into L1? Furthermore, we can see that there is no data going out from L1 to anywhere else, so there does seem to be a use for the 63 MB of data loaded into L1. I was not able to figure out what explains this behavior. Any thoughts on what this could be?

<img width="1675" alt="Screenshot 2023-02-22 at 12 44 24 PM" src="https://user-images.githubusercontent.com/9440135/220756909-e0e07fd0-e372-4a1e-b639-dd5cde10d3fe.png">

```
// Shape: M=1024, N=8192, K=2048

using EpilogueOutputOp = cutlass::epilogue::thread::LinearCombination<
  cutlass::bfloat16_t, // C, A, B
  8,
  float, // Accum
  float // Compute
>;


using gemm_type = cutlass::gemm::device::GemmUniversal<
  cutlass::bfloat16_t, cutlass::layout::RowMajor,
  cutlass::bfloat16_t, cutlass::layout::RowMajor,
  cutlass::bfloat16_t, cutlass::layout::RowMajor,
  float,
  cutlass::arch::OpClassTensorOp,
  cutlass::arch::Sm80,
  cutlass::gemm::GemmShape<128,128,32>,
  cutlass::gemm::GemmShape<64,64,32>,
  cutlass::gemm::GemmShape<16,8,16>,
  EpilogueOutputOp,
  cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<8>,
  5,
  8,
  8,
  cutlass::arch::OpMultiplyAdd
>;
```

I am using CUTLASS 2.11 with CUDA 11.4.

**Comment by mnicely** [comment]
Resolved
