### ISSUE TITLE
[FEA] Store CUDA kernel launch status / error

### ISSUE THREAD

**Issue by collinmccarthy** [NVIDIA/cutlass#834]
**Is your feature request related to a problem? Please describe.**
I'm benchmarking (a lot) of matrix sizes and some lead to CUDA invalid configuration errors, which is fine because not all problem sizes will work with all tile sizes. But at the device level (for at least [gemm:device::SparseGemm](https://github.com/NVIDIA/cutlass/blob/9cdbe3357082023f4b8ed8cec5bd2280cc874879/include/cutlass/gemm/device/gemm_sparse.h#L484) and [gemm::device::Gemm](https://github.com/NVIDIA/cutlass/blob/9cdbe3357082023f4b8ed8cec5bd2280cc874879/include/cutlass/gemm/device/gemm.h#L496)) we hide the CUDA error by calling `cudaGetLastError()` instead of `cudaPeekLastError()`, and then return `Status::kInternalError` if there was any CUDA error at all. 

**Describe the solution you'd like**
As long as I can figure out what the launch error was, I would be supper happy. Here are some thoughts:
- Use `cudaPeekLastError()` so the user can always access the last error (I understand if you really do want to clear it)
- Return cudaError_t instead of cutlass::Status for `operator()` and `run()` methods at the device level
- Store cudaError_t somewhere in the device-level struct so it can be accessed with something like "getKernelLaunchStatus()" or something (probably makes the most sense)

**Comment by hwu36** [comment]
Did you call `can_implement()`(e.g. https://github.com/NVIDIA/cutlass/blob/9cdbe3357082023f4b8ed8cec5bd2280cc874879/include/cutlass/gemm/device/gemm_universal.h#L354) before running the kernel?  It can tell you if the problem size fit this tile size or not.

**Comment by collinmccarthy** [comment]
I did yes. The problem size ends up launching a grid with grid.y > 65535 (the max that A100 device query reports). I can be more specific about why this is necessary if you'd like.

**Comment by hwu36** [comment]
We can add thread number check to can_implement too

**Comment by collinmccarthy** [comment]
Oh right, if the threadblock size, grid size and shared memory were all checked such that (just) the kernel launch was guaranteed to succeed, that would be great.

**Comment by mnicely** [comment]
Added [here](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/device/gemm_universal_base.h#L239)

**Comment by collinmccarthy** [comment]
Awesome thank you so much!
