### ISSUE TITLE
[QST] Question about transposed matrix while using int4 gemm api

### ISSUE THREAD

**Issue by lichangh20** [NVIDIA/cutlass#837]
Hello, I want to use int4 gemm in cutlass to accelerate my program in pytorch. I notice the the required layout of input matrices is:
```C
using LayoutInputA = cutlass::layout::RowMajor;
using LayoutInputB = cutlass::layout::ColumnMajor;
using LayoutOutput = cutlass::layout::RowMajor;
```
 However, the layout of torch.Tensor is always RowMajor. So I have to use B.t().contiguous() to change it into columnMajor and make sure the result is correct . Nevertheless, the contiguous operation requires memory allocation as well as make a copy of the data, which is very time consuming.

So I am wondering if there's any method that don't need to make memory address contiguous explicitly after transposing the matrix and still get the correct answer, like in Cublas I can use the transpose flag CUBLAS_OP_T to judge if the matrix is transposed.

Many thanks!
```[tasklist]

```

**Comment by hwu36** [comment]
we can only do row x col -> row or row x col-> col .  Otherwise you need to use the interleaved layout which is even more unfriendly.

row x col is what tensor core instruction does which is nature to program with.  Transposing 4bit data on the fly is costly, lots of unpacking and packing.

**Comment by lichangh20** [comment]
All right, so what if I want to do the gemm of A.t().mm(B), like A is a {K,M} matrix and B is a {K,N} matrix, is there some way to indicate that A is transposed or I have to use A_t = A.t().contiguous() to make sure the memory address is contiguous, which is a very time-consuming operation?

**Comment by hwu36** [comment]
you need to transpose it first. i don't think cublas can do row x row with int8 tensor core either.

**Comment by lichangh20** [comment]
>you need to transpose it first. i don't think cublas can do row x row with int8 tensor core either.

Yes, I know I need to transpose it first. But I'm wondering if I can skip the contiguous operation?  i.e. input_matrix.t() instead of input_matrix.t().contiguous()? 

Since contiguous requires memory allocation & data copy, which is time-consuming.

Many thanks!

**Comment by hwu36** [comment]
You need to physically transpose the data, not just tag it.
