### ISSUE TITLE
[BUG] Unhandled cudaErrorMisalignedAddress on host_sync

### ISSUE THREAD

**Issue by Barrot** [NVIDIA/cutlass#848]
**Describe the bug**

A CUDA error is encountered when syncing the conv data from device to host. The error is `cudaErrorMisalignedAddress`.
The test involves a grouped, int4 convolution in the multiple group mode.

**Steps/Code to reproduce bug**

Here are the types, shapes and the general setup:

```cuda
using ElementA = cutlass::int4b_t;
using ElementB = cutlass::int4b_t;
using ElementC = cutlass::int4b_t;
using ElementAccumulator = int32_t;
using ElementCompute = float;

using InputOutputLayout = cutlass::layout::TensorNHWC;
using FilterLayout = cutlass::layout::TensorNHWC;

using Conv2dFpropKernel = typename cutlass::conv::kernel::DefaultConv2dGroupFprop<
    ElementA, InputOutputLayout,
    ElementB, FilterLayout,
    ElementC, InputOutputLayout,
    ElementAccumulator,
    cutlass::arch::OpClassTensorOp,
    cutlass::arch::Sm80,
    cutlass::gemm::GemmShape<64, 64, 64>,
    cutlass::gemm::GemmShape<32, 32, 64>,
    cutlass::gemm::GemmShape<8, 8, 32>,
    cutlass::epilogue::thread::LinearCombination<
        ElementC,
        8,
        ElementAccumulator,
        ElementCompute>,
    cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<>,
    3,
    cutlass::arch::OpMultiplyAddSaturate,
    cutlass::conv::GroupMode::kMultipleGroup,
    cutlass::conv::IteratorAlgorithm::kAnalytic>::Kernel;

using ImplicitGemm = cutlass::conv::device::ImplicitGemmConvolution<Conv2dFpropKernel>;

cutlass::Tensor4DCoord inputSize(1, 256, 256, 128);
cutlass::Tensor4DCoord filterSize(64, 3, 3, 4);
cutlass::Tensor4DCoord paddingSize(1, 1, 1, 1);
cutlass::Tensor4DCoord outputSize(1, 256, 256, 64);
```

The problem size:

```cuda
cutlass::conv::Conv2dProblemSize problemSize(inputTensor.extent(),
                                                 filterTensor.extent(),
                                                 {1, 1, 1, 1},
                                                 {1, 1},
                                                 {1, 1},
                                                 outputTensor.extent(),
                                                 cutlass::conv::Mode::kCrossCorrelation,
                                                 1, 32);
```

All of the tensors are filled in with data and `sync_device()` is called on each.

`can_implement` does not find any errors and the status of the call `implicitGemmOp()` is `cutlass::Status::kSuccess`.

After checking the status of the gemm op call, `sync_host()` is called on the output tensor. (`outputTensor.sync_host()`) and the misaligned memory exception is encountered.

**Expected behavior**

Either the alignment error needs to be caught during the `can_implement` call or the alignment needs to be accounted for in the CUTLASS implementation.

**Environment details (please complete the following information):**
Bare-Metal
CUDA: 12.0
CUTLASS: 2.11
OS: Windows 11
CPU: Ryzen 5950X
GPU: RTX 4090
RAM: 64 GB

**Additional context**
From experimentation, it looks like the issue occurs whenever `inputSize.c() / groups < 32`. For int4, that means 32 * 4-bit = 128-bit alignment is a requirement for CUDA to transfer from the device to the host. But the same requirement does not seem to be required to transfer the other way around since `sync_device()` does not cause any errors.

**Comment by hwu36** [comment]
The error is happened inside the conv kernel, not memory copy.  Memory copy just captures the previous kernel error.

You are correct that the error is about the alignment.  You do not specify the alignment so the templates just pick the default one which is 128bit.  The alignment can be set in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/conv/kernel/default_conv2d_group_fprop.h#L82-L84.  The unit is element.  For example, if element is fp16, the alignment can be set as 8 to be 128bit (16bit x 8).  The biggest alignment of ampere style kernel which uses `cp.async` is 128bit, the smallest is 32bit.  The smaller alignment you use, the worse perf you will get.

I also noticed that you are running 8x8x32 tensor core instruction on ampere. On ampere you can run bigger tensor core instruction which is 16x8x32.

**Comment by hwu36** [comment]
Sorry I should say 16x8x64, then tb size is 64x64x128, warp size 64x64x128

**Comment by Barrot** [comment]
Thank you!
