### ISSUE TITLE
[BUG] Ex 13 (two_tensor_op_fusion) does not work with fp32 accum

### ISSUE THREAD

**Issue by rkindi** [NVIDIA/cutlass#852]
**Describe the bug**

**Steps/Code to reproduce bug**
You can patch [cutlass_ex_13.patch](https://github.com/NVIDIA/cutlass/files/10909731/cutlass_ex_13.patch) to see that when we change the accumulator to float (fused_two_batched_gemms_f16_sm80_rf). In the patch, I shrunk the problem size and included the error dump which shows the expected and computed result. We can see the first 32 columns of the computed result are correct but the rest is not correct.

I am looking for fp16 operands with fp32 accum support because fp16 operands with fp16 accum is not sufficient for my use case.

**Expected behavior**
All columns between computed and expected result should match.

**Environment details (please complete the following information):**
A100 40GB

cc:  @jwang323

**Comment by mnicely** [comment]
Resolved
