### ISSUE TITLE
[QST] Strided read/write for conv2d ops

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#859]
**What is your question?**
Hi all,

does cutlass now support strided read/write for conv2d ops?

E.g., a normal conv2d fprop case is like this: `input: NHWC weight: KRSC --> output: NPQK`

for strided case, I'd like to write results to a buffer with a larger channel dim. That is, the output tensor buffer shape is `[N, P, Q, X]` where `X` is a large number than `K`.

Is there any kernel/utility in cutlass available for this?

Thanks a lot!

**Comment by hwu36** [comment]
Yes, it is easy to do.  Just  still keep the problem size NPQK, but the strides of output tensor to be whatever you want.  For example, https://github.com/NVIDIA/cutlass/blob/master/examples/17_fprop_per_channel_bias/fprop_per_channel_bias.cu#L194 hard code the stride to be 0 to make the tensor essentially a vector.

**Comment by TUMSchieben** [comment]
> Yes, it is easy to do. Just still keep the problem size NPQK, but the strides of output tensor to be whatever you want. For example, https://github.com/NVIDIA/cutlass/blob/master/examples/17_fprop_per_channel_bias/fprop_per_channel_bias.cu#L194 hard code the stride to be 0 to make the tensor essentially a vector.

So for layout `TensorNHWC`, does it mean that we just need to set the strides shown in https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/layout/tensor.h#L103? And in this case, the actual buffer size of the tensor is `N*P*Q*X`, not `N*P*Q*K`?

**Comment by hwu36** [comment]
Yes
