### ISSUE TITLE
CUTLASS with NVIDIA SASSIFI

### ISSUE THREAD

**Issue by fernandoFernandeSantos** [NVIDIA/cutlass#86]
I want to use CUTLASS with [NVIDIA SASSIFI](https://github.com/NVlabs/sassifi.git), however SASSIFI only accepts CUDA 7.0. How hard is to build cutlass examples with CUDA 7.0?

Is there a fast way to remove all includes that depend on CUDA >=9.2?

I've been trying to build 00_basic_gemm example with CUDA 7.0 but no success until now.

**Comment by kerrmudgeon** [comment]
I would recommend investigating [NVBitFI](https://github.com/NVlabs/nvbitfi). 

This is a new fault injection tool (released today!) that should be compatible with modern versions of CUDA. See the [comparison with SASSIFI](https://github.com/NVlabs/nvbitfi#nvbitfi-vs-sassifi) for more details.

CUTLASS benefits greatly from enhancements to the CUDA compiler, and we have not tested it with version of CUDA older than 9.2. Consequently, I would caution against expending significant effort to port it to older versions of the Toolkit.
