### ISSUE TITLE
[QST] Can CUTLASS merge data loaded from small gmem tile's iterator and feed it to the large smem tile's iterator to do large tile's mma?

### ISSUE THREAD

**Issue by Ther-LF** [NVIDIA/cutlass#860]
In my project, I need to load discontinuous and small tiles from global memory and combine them in shared memory to do large tile's mma, which is like what's shown here:
![微信图片_20230310160257](https://user-images.githubusercontent.com/54900723/224258195-54e8ec13-3883-480c-9515-445458ad1c99.png)
In cutlass, we load tiles from global memory using https://github.com/NVIDIA/cutlass/blob/29801e348adc609973cc1e4fba659b3d58384f8e/include/cutlass/gemm/threadblock/default_mma.h#L513  Let's call this iterator `gmem read iterator`. 
And we write tiles to shared memory using https://github.com/NVIDIA/cutlass/blob/29801e348adc609973cc1e4fba659b3d58384f8e/include/cutlass/gemm/threadblock/default_mma_core_sm80.h#L1310 Let's call this iterator `smem write iterator`.
Finally we load tiles from shared memory and feed them to tensor core's registers using
https://github.com/NVIDIA/cutlass/blob/29801e348adc609973cc1e4fba659b3d58384f8e/include/cutlass/gemm/warp/mma_tensor_op.h#L223 Let's call this iterator `smem read iterator`.
Supposing we are dealing with the operand A (col major) and the `smem read iterator` 's tile's shape is <kM, kK>, can we just modify the `gmem read iterator` and `smem write iterator` 's tile's shape to be <kM, kK / n>(kK is divisible by n) to achieve this function?
From https://github.com/NVIDIA/cutlass/blob/29801e348adc609973cc1e4fba659b3d58384f8e/include/cutlass/gemm/threadblock/default_mma_core_sm80.h#L1304
we can know that when the tile's shape has changed, the data corresponding to the thread that needs to be moved will also change, so the data's arrangement will be messed up for large tile but is correct for small tile, which is my major concern. So maybe we can't just split the large tile into small tiles?
Thank you for your suggestions:-)

**Comment by hwu36** [comment]
are you doing affine2?  We can already do it. https://github.com/NVIDIA/cutlass/tree/master/examples/18_ampere_fp64_tensorop_affine2_gemm

**Comment by Ther-LF** [comment]
Affine2 means that every element in the matrix is not consecutive. However, in my situation, the small tiles are discontinuous for each other, but the elements within the small tiles are continuous. So maybe affine2 layout is not suitable for the gmem.

**Comment by Ther-LF** [comment]
The blue blocks in the picture are small tiles and not elements. Maybe it's misleading, my bad:-(

**Comment by thakkarV** [comment]
What you seem to be attempting to implement is a tensor contraction. Can you describe your shapes and strides for the input and output tensors?

**Comment by Ther-LF** [comment]
Here is my situation: supposing we have the normal operand A whose layout is column major and operand B whose layout is row major. The operand A's shape is `<1000, 1000>` and its stride is `1000`. The operand B's shape is `<1000, 100>` and its stride is `100`. Both of their element's type is `FP64`, so they meet the requirement of alignment in CUTLASS and don't need to change anything.
I want to do the gemm with `ThreadBlockShape` to be `<128, 128, 16>`. So here is how the original operand being partitioned in CUTLASS:

![image](https://user-images.githubusercontent.com/54900723/224492804-26d27ad7-abd4-451a-a4a5-608750798be8.png)

No matter what, in the shared memory, we will get the tiles with complete shape of `<128, 16>` and `<16, 128>`. 
However, for some reason, the tiles in the operand is not stored as stated above, it's more like how CUTLASS partition the operands when the `ThreadBlockShape` tis `<128, 128, 8>`:

![image](https://user-images.githubusercontent.com/54900723/224493282-d0db335c-60dd-492c-a229-0ecff966f1b8.png)

Besides, some tiles in this partition can't be used, so when we get the tiles from the gmem we need to fetch them discontinuously, which is like what's shown here:

![image](https://user-images.githubusercontent.com/54900723/224493817-c92e8694-ba9e-4f18-8713-c4f84cb228b7.png)

In this picture, the blue tiles store the useful data while the white tiles store the useless data. I want to merge these useful but small tiles to do large tiles' mma to make better use of computing resources.
To  some degree, it's like tensor contraction since I want to merge small tiles to get large tiles and do large tiles' threadblock-level mma.

**Comment by mnicely** [comment]
@Ther-LF did you resolve your issues?

**Comment by Ther-LF** [comment]
Hi, @mnicely . I have reconsidered this need and found **it's not efficient**, since two distant gmem tiles may greatly **hinder the performance of cache.** Besides, to achieve this function based on the CUTLASS 2.x, I need to modify the `iterator`, `layout` and so on, which is not easy. 
I haven't dive into CUTLASS 3.0, maybe CUTLASS 3.0 will offer more possibilities. :-)

**Comment by mnicely** [comment]
Thanks for letting us know. We will close the issue for now. Feel free to reopen if you decide to continue the effort with v3.x.
