### ISSUE TITLE
[BUG]: Missing comma in asm-definition.

### ISSUE THREAD

**Issue by seanbaxter** [NVIDIA/cutlass#861]
Missing comma at the end of this line breaks my compiler. It ought to break yours too.
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/mma_sm90.h#L248

**Comment by hwu36** [comment]
Man, are you building cutlass now?

**Comment by seanbaxter** [comment]
Yes.

**Comment by hwu36** [comment]
Awesome.  Could you please do us a favor? Building below target with your compiler and let me know the compilation time. No need to run it.  Many thanks in advance.

```
 cmake .. -DCUTLASS_NVCC_ARCHS=90a
 make 49_hopper_gemm_schedules_with_collective_builder
```

**Comment by seanbaxter** [comment]
I don't have sm_90a support yet. That would need a bump to the bleeding edge LLVM build.

**Comment by hwu36** [comment]
What about sm80 stuff?
 
 ```
cmake .. -DCUTLASS_NVCC_ARCHS=80
 make cutlass_test_unit_gemm_device_tensorop_f32_sm80_3x
```

**Comment by seanbaxter** [comment]
I will do that. Give me a minute! (And fix your comma.)

**Comment by thakkarV** [comment]
@seanbaxter the fix is not merged in :) before closing this issue, just wanted to ask if you were able get CUTLASS to build with circle?

**Comment by seanbaxter** [comment]
I'm working on it! Had a problem with `__usAtomicCAS` (the unsigned short CAS from sm_70_rt) breaking LLVM when lowering to `cmpxchg`. Is there a special nvvm intrinsic for that? You want to help me with that? :D
