### ISSUE TITLE
[QST] CuTe kernels with MMA instructions

### ISSUE THREAD

**Issue by sophiawisdom** [NVIDIA/cutlass#864]
I was reading through the CuTe documentation, and while what was there was very good there wasn't very much. I'm not super familiar with CUTLASS/CuTe and so was not sure quite what to do to get fp16/bf16 MMA support working. My understanding from reading through the templates was 1) A/B/C all needed to be in registers and 2) A/B/C all needed to be multidimensional. Is this true?

I could likely get it to work, but even if I could I have low confidence I could get a high-performance matmul (with e.g. optimal register reuse). Are there any examples of CuTe kernels for fp16/bf16 or anything other than SGEMM?

**Comment by thakkarV** [comment]
hi! Are you specifically asking for a single file example kernels or looking for Ampere/Volta kernels out of CUTLASS itself? the former is unfortunately not in our examples/documentation yet, although we hope to add more cute examples over time.

The latter does exist, and I encourage you to check out `test/unit/gemm/device/sm80_gemm_f16_f16_f32_tensor_op_f32.cu`. This contains CUTLASS 3.0 and CuTe implementations of Ampere GEMM kernels that run at great performance while using CuTe end to end to describe all thread and data layouts. This testfile contains fp16 implementations, but bf16 kernels would be identical except for the Element types switched out.

Finally, for 
> My understanding from reading through the templates was 1) A/B/C all needed to be in registers and 2) A/B/C all needed to be multidimensional. Is this true?
This is true for all pre-Hopper kernels. In Hopper sm90a kernels, we source A and B operands from shared memory directly.
