### ISSUE TITLE
[QST] Adding bias to sparse GEMM output

### ISSUE THREAD

**Issue by cgorac** [NVIDIA/cutlass#872]
I'm trying to write CUTLASS code to multiply a sparse matrix A that is in row major layout with a dense matrix B that is in column major layout, and then to add some bias.  All these tensors are of half_t datatype.  The bias vector is 1D, and it should be added to each column of the GEMM result.  So my first approach was to specify bias as matrix C for GEMM, that would be in column major layout, with column stride 0.  However, apparently sparse GEMM does not support tensor C (and thus output tensor D too) in column major layout - even CUTLASS profiler with arguments as follows:
```
cutlass_profiler --operation=spgemm --A=f16 --B=f16 --C=f16 --acum=f32 --m=1024 --k=2048 --n=768
```
will only list combinations where tensor C is in row major layout.  (At least this is the case with CUTLASS 2.10.0, that for now I have to use for compatibility reasons.)

So I am looking into doing this through the epilogue.  I've examined `12_gemm_bias_relu` example, and then tried to utilize `LinearCombinationBiasElementwise<cutlass::half_t, float, float, float, float>` for this purpose.  Am not sure will `LinearCombinationBiasElementwise` even work for my purpose, but it reports compile errors, in particular that `Identity<float>`, that turns out to be the first defaulted argument of `LinearCombinationBiasElementwise` template, does not have `kIsHeavy` - that is true, as `struct Identity` indeed doesn't have such member variable.  I'm wondering how is that possible, i.e. is this template ever instantiated with the default value for this particular argument; but more importantly, my question is: is there any suggestion how to actually apply bias for the situation that I described (except for actually creating 2D tensor for matrix C that will have bias vector repeated over its columns)?

Thanks.

(Edit: Attaching diff vs. `examples/12_gemm_bias_relu/gemm_bias_relu.cu` from CUTLASS 2.10.0, that will trigger error with `struct Identity` not having `kIsHeavy`, and also showing to the some extent what I'm trying to do.)
[diff.txt](https://github.com/NVIDIA/cutlass/files/10995395/diff.txt)

**Comment by cgorac** [comment]
Let me clarify my question, and add some context:

In deep learning, linear layer with $k$ inputs and $m$ outputs is usually implemented through calculation $xW^{T}+b$ where $x_{n\times k}$ matrix represents $n$ inputs with $k$ features, $W_{m\times k}$ is matrix with layer coefficients and $b_{1,m}$ is layer bias row-vector, that is added here to each row or $xW^{T}$ product.  Now, let's say the network is trained, so $W$ and $b$ values are fixed, and it is found that the prediction won't be affected if some $W$ coefficients pruned so that $W$ becomes a matrix in 2:4 sparsity pattern.

To utilize CUTLASS here, the original calculation would have to be changed to $(Wx^{T}+b^{T})^{T}$ instead.  All the tensors are provided in memory in row-major order.  The first part of the calculation, that is $Wx^{T}$ is simple with CUTLASS, as multiplying sparse matrix in row-major layout with dense matrix in column-major layout seems to be supported for any kind of datatype.

However, now elements of vector $b$ are to be added to each column of this matrix product, and I can't find how to do it with CUTLASS; namely, it seems CUTLASS only supports row-major layout for matrix $C$ in $\alpha AB+\beta C$ operation, and CUTLASS epilogue operators implementing adding bias seem to have the same limitation.  Any suggestions here?

**Comment by hwu36** [comment]
we have `kIsHeavy` inside `identity` now https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/thread/activation.h#L89

> elements of vector are to be added to each column of this matrix product

to be clear, is it

```
for (m = 0; m < M; ++m)
  for (n = 0; n < N; ++n)
    D[m, n] = AB[m, n] + C[m]
```

or


```
for (m = 0; m < M; ++m)
  for (n = 0; n < N; ++n)
    D[m, n] = AB[m, n] + C[n]
```

**Comment by cgorac** [comment]
Thanks for your reply.  It's the first one: `D[m, n] = AB[m, n] + C[m]`.

**Comment by hwu36** [comment]
you need to get your hands dirty.  check this line https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h#L407 

`row_offset + thread_start_row_` is the logic row number.  you can use it to index an array `indices_[row_offset + thread_start_row_]`.

**Comment by cgorac** [comment]
Thanks for the hint.  I really appreciate it much, but I'm starring for hour at this file, and other places in the CUTLASS source where `PredicatedTileIterator` is used, and I still have no clue what I'm supposed to do...  Shall I create something alike to `PredicatedTileIterator`, that would get my bias vector through its constructor, and then change `store_with_byte_offset()` method to add corresponding bias vector element?  Then I assume I'd plug this `PredicatedTileIterator`-alike somewhere - I'm really not sure where and how to do it, and then in particular how to pass down the bias vector argument, but I guess at the end I'll specify an epilogue different than `LinearCombination` when instantiating SparseGemm, and it will all work?

**Comment by hwu36** [comment]
you can copy, paste and modify `PredicatedTileIterator` to be the iterator to load your `C` and use it https://github.com/NVIDIA/cutlass/blob/660a05f581257aa06e35d07b3e4df9ab72fa5bba/include/cutlass/gemm/kernel/sparse_gemm.h#L334

**Comment by cgorac** [comment]
Ok, this is the best I was able to come up with: [15_ampere_sparse_tensorop_gemm.zip](https://github.com/NVIDIA/cutlass/files/11190257/15_ampere_sparse_tensorop_gemm.zip).  Unpack this file into `example/15_ampere_sparse_tensorop_gemm`, rebuild this example, and it will work with the bias vector, i.e. C "matrix", supplied in the column-vector format I described above.  It's very ugly to have to keep copies of all these files, slightly changed, from the CUTLASS source tree; also, `SparseGemm::can_implement()` call doesn't work here because CUTLASS would return an alignment error.  But at least it works, and the expected performance is finally there.  Please let me know if there are any improvements possible.
