### ISSUE TITLE
Missing OrderedSequenceBarrier::Params member

### ISSUE THREAD

**Issue by seanbaxter** [NVIDIA/cutlass#877]
This line breaks because `OrderedSequenceBarrier<2, 2>::Params` doesn't have a member `id`.
https://github.com/NVIDIA/cutlass/blob/master/test/unit/pipeline/sequence_barrier.cu#L99

Here's the `Params` definition: 
OrderedSequenceBarrier<>::Params
https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/pipeline.hpp#L457

Is this always built with NDEBUG or something?

**Comment by thakkarV** [comment]
this will be fixed in our upcoming release.

**Comment by mnicely** [comment]
Resolved in 3.1
