### ISSUE TITLE
[BUG] In example'13_two_tensor_op_fusion' the fused version is slower than the non-fused version

### ISSUE THREAD

**Issue by butterluo** [NVIDIA/cutlass#886]
**Describe the bug**
When I run example '13_two_tensor_op_fusion/fused_two_gemms_f16_sm80_shmem.cu' the fused version is slower than the non-fused version.
The log printed is shown below:
Device: NVIDIA GeForce RTX 3050 Laptop GPU
Arch: SM86
Test: gemm f16 shmem staging
Running Non-fused back-to-back FP16 TN GEMMs...
gemm 0 time 0.581747 ms
gemm 1 time 0.396618 ms
Non-fusion time 0.978365 ms
Pass
Running Fused back-to-back FP16 TN GEMMs with shared memory staging...
Fusion time 1.04477 ms
Pass

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

1. compile cutlass using cmake with CUDA11.7
2. run: build/examples/13_two_tensor_op_fusion/13_fused_two_gemms_f16_sm80_shmem

**Expected behavior**
Expected the fused version which fused 2 gemm in 1 kernel should faster than the non-fused version which do 2 gemm using 2 kernel.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] 
Device: NVIDIA GeForce RTX 3050 Laptop GPU
Arch: SM86
CUDA: 11.7

**Additional context**

**Comment by mnicely** [comment]
@butterluo there are known performance issues in the 11.7 compiler. Can you rerun with 11.6 or 11.8?

**Comment by butterluo** [comment]
@mnicely I've rerun it using CUDA 11.8, but the fused version is still slower than the non-fused version.
build/examples/13_two_tensor_op_fusion/13_fused_two_gemms_f16_sm80_shmem
Device: NVIDIA GeForce RTX 3050 Laptop GPU
Arch: SM86
Test: gemm f16 shmem staging
Running Non-fused back-to-back FP16 TN GEMMs...
gemm 0 time 0.581402 ms
gemm 1 time 0.386048 ms
Non-fusion time 0.96745 ms
Pass
Running Fused back-to-back FP16 TN GEMMs with shared memory staging...
Fusion time 1.04445 ms
Pass

**Comment by hwu36** [comment]
This example is written for a100.  a100 has 160KB shmem, 3050 has 100KB shmem.  This example uses extra shmem to store the result from the first gemm.  Its occupancy would be lower on 3050.

**Comment by butterluo** [comment]
@hwu36 I knew this, I've checked (using CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK) that RTX3050 has not enought shmem for this gemm. But why below lines didn't throw error or exception when Cutlass try to set he shmem size ? 
  [https://github.com/NVIDIA/cutlass/blob/66d9cddc832c1cdc2b30a8755274f7f74640cfe6/examples/13_two_tensor_op_fusion/device/b2b_gemm.h#L410-L412](url)

**Comment by butterluo** [comment]
How can I get the maximum shared memory the GPU can support? I query it using cuDeviceGetAttribute function and CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK flag, and the return value is far less than 100KB? @hwu36

**Comment by hwu36** [comment]
you can set your shmem allocation like https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal_base.h#L148-L163

you can get your maxim shmem size like https://github.com/NVIDIA/cutlass/blob/master/examples/43_ell_block_sparse_gemm/ell_block_sparse_gemm.cu#L457-L473

**Comment by butterluo** [comment]
> you can set your shmem allocation like https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/device/gemm_universal_base.h#L148-L163
> 
> you can get your maxim shmem size like https://github.com/NVIDIA/cutlass/blob/master/examples/43_ell_block_sparse_gemm/ell_block_sparse_gemm.cu#L457-L473

thank you :)
