### ISSUE TITLE
Cutclass failed to build when installing higher version of Cuda

### ISSUE THREAD

**Issue by QuellaZhang** [NVIDIA/cutlass#89]
Recently we update cutclass source to latest version e33d90b, it requires higher version of Cuda, Cutclass got the same error after installing cuda v10.2.89 or cuda v10.2.89.20191206, can some one help look? Not sure if we missed something. Related to https://github.com/NVIDIA/cutlass/issues/68. 

BTW, cuda v10.1.243 + cutclass b5cab17 works fine in our testing environment.

**build log**: [cutclass_build.log](https://github.com/NVIDIA/cutlass/files/4686106/cutclass_build.log)

**error message**:  CUSTOMBUILD : *** error : Could not detect active GPU device ID [CUDA driver version is insufficient for CUDA runtime version] 
![Untitled](https://user-images.githubusercontent.com/36754348/82971306-f3dece00-a004-11ea-931f-34dd30e6d5df.png)

**Comment by d-k-b** [comment]
Does nvidia-smi show the correct driver is currently installed? Also, are you able to build and run a CUDA sample such as deviceQuery just to double-check the environment?

**Comment by kerrmudgeon** [comment]
We'd like to close this issue for now since it seems difficult to repro.

I'd suggest downloading and installing the [CUDA 11.1 Toolkit ](https://developer.nvidia.com/cuda-downloads) (released today!) and revisiting.
