### ISSUE TITLE
[QST] [Volta Tensor Cores] Conflict-free shared memory loads for both operand A and B?

### ISSUE THREAD

**Issue by ChieloNewctle** [NVIDIA/cutlass#898]
**What is your question?**

I found [a slide about how CUTLASS directly use Volta Tensor Cores](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9593-cutensor-high-performance-tensor-operations-in-cuda-v2.pdf), which is great and concise. But I still have a question about "conflict-free shared memory loads".

As shown on page 30, it does make sense that there won't be any bank conflict when loading fragments from shared memory for operand matrix A. However, what about matrix B? Both QP0 and QP1 will essentailly access the same fragments in shared memory. Will accessing the same address result in only one read request and no bank conflict?

**Comment by hwu36** [comment]
B loads QP0 and QP2 in the same way as A loads QP0 and QP 1.

**Comment by ChieloNewctle** [comment]
> B loads QP0 and QP2 in the same way as A loads QP0 and QP 1.

But, isn't 128-bit loading done by "T0~T7", "T8~T15", "T16~T23" and "T24~T31"? For example, the first 128-bit row fragment in matrix B is loaded both by "T0~T3" and "T4~T7".

**Comment by hwu36** [comment]
> For example, the first 128-bit row fragment in matrix B is loaded both by T0 and T4.

no.  B is loaded in the exactly same way as A.  They use the same code to do the loading.  You could dump the address to check the mapping.

https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/warp/mma_tensor_op_tile_iterator_sm70.h#L296

**Comment by ChieloNewctle** [comment]
> @ChieloNewctle are your issues resolved?

yes. although there may be bank conflicts, CUTLASS is still performant.
