### ISSUE TITLE
D = alpha * accumulator + beta * source + uniform，can we allow the precision of D  and source not be same？

### ISSUE THREAD

**Issue by zhoutianzi666** [NVIDIA/cutlass#899]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use CUTLASS to do [...]

- `D = alpha * accumulator + beta * source + uniform`
- `ElementOutput_` is the output D precision
- `ElementAccumulator_` is the accumulator precision
- `ElementCompute_` is the alpha beta precision
- but what is the precision of source，they must be same as `ElementOutput_`？

```cpp
/// D = alpha * accumulator + beta * source + uniform
///
template <
  typename ElementOutput_,                             ///< Data type used to load and store tensors
  int Count,                                           ///< Number of elements computed per operation.
                                                       ///< Usually it is 128/sizeof_bits<ElementOutput_>,
                                                       ///< but we use 64 or 32 sometimes when there are not enough data to store
  typename ElementAccumulator_ = ElementOutput_,       ///< Accumulator data type
  typename ElementCompute_ = ElementOutput_,           ///< Data type used to compute linear combination
  ScaleType::Kind Scale = ScaleType::Default,          ///< Control Alpha and Beta scaling
  FloatRoundStyle Round = FloatRoundStyle::round_to_nearest,
  typename ElementSource_ = ElementOutput_
>
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by hwu36** [comment]
in 3.x hopper kernel, yes.

in 2.x style kernels, you need to do the plumbing and change the code.
