### ISSUE TITLE
Question about data types with the cutlass_profiler tool

### ISSUE THREAD

**Issue by rjfnobre** [NVIDIA/cutlass#90]
Does the cutlass_profiler tool support 4-bit unsigned and 1-bit data types?
If so, what are the parameters that one should give to the profiler.

**Comment by hwu36** [comment]
We have 4-bit signed.  For example, you can use this to run 4-bit int

./tools/profiler/cutlass_profiler --m=your_problem_m --n=your_problem_n --k=your_problem_k --kernels=cutlass_tensorop_i8832gemm_s4_128x128_128x2_tn_align32.cu

We don't have 1-bit in the profiler yet.

**Comment by rjfnobre** [comment]
I asked because you had 4-bit unsigned and 1-bit on the profiler bundled with CUTLASS 1.X.
I suppose that functionality is yet to be ported to the profiler in CUTLASS 2.X.

**Comment by hwu36** [comment]
In our newly released 2.2, we include uint4 tensor core kernels in the profiler for both ampere and turing.  You can also find 1-bit tensor core kernels in the profiler.
