### ISSUE TITLE
[Performance] about gemm

### ISSUE THREAD

**Issue by bitxsw93** [NVIDIA/cutlass#907]
Hello:
 Gemm problem size is 4x4096x16384(MxNxK).

Is there any suggestion about setting cutlass gemm threadblock tile size and wrap tile size to get better performance on T4 card??

**Comment by hwu36** [comment]
32x256x32 with splitk or streamk

**Comment by bitxsw93** [comment]
how about Gemm problem size is 1x4096x16384(just gemv)，how to use cutlass to get better performance?

**Comment by hwu36** [comment]
Cutlass has gemv, you could try it. Just search gemv in filename under test/unit/gemm/device for example.

**Comment by mnicely** [comment]
@bitxsw93 are your issues resolved?

**Comment by hwu36** [comment]
we just released new gemv

**Comment by hwu36** [comment]
which one do you run?

**Comment by mnicely** [comment]
@bitxsw93 see performance number in from this [issue](https://github.com/NVIDIA/cutlass/issues/909#issuecomment-1564004072).
