### ISSUE TITLE
how to use wgmma

### ISSUE THREAD

**Issue by mengchihe** [NVIDIA/cutlass#908]
I want to use wgmma and write the code similar to example 48, as listed below

`
using TileShape = Shape<_128,_128,_32>; 
  static constexpr cute::GMMA::Major GmmaMajorA = cute::GMMA::Major::K;
  static constexpr cute::GMMA::Major GmmaMajorB = cute::GMMA::Major::K;

  using SmemLayoutAtomA = decltype(cute::GMMA::smem_selector<
      GmmaMajorA, float, decltype(cute::get<0>(TileShape{})), decltype(cute::get<2>(TileShape{}))>());

  using SmemLayoutA = decltype(tile_to_shape(
      SmemLayoutAtomA{},
      make_shape(shape<0>(TileShape{}), shape<2>(TileShape{}), Int<4>{}),
      Step<_2,_1,_3>{}));

  using TiledMma = decltype(cute::make_tiled_mma(cute::GMMA::ss_op_selector<
      tfloat32_t, tfloat32_t, float, TileShape, GmmaMajorA, GmmaMajorB>()));

  TiledMma tiled_mma;
  auto thread_mma = tiled_mma.get_thread_slice(tid);
  Tensor sA = make_tensor(make_smem_ptr(smem), SmemLayoutA{});
  Tensor tCsA = thread_mma.partition_A(sA); 
  Tensor tCrA = thread_mma.make_fragment_A(tCsA);
`

but this will get floating point exception when I run it, seems occur in get_thread_slice, and it's also wrong when I run tiled_mma.get_thread_slice(0)

I read the code in get_thread_slice and found maybe it is caused by the ThrLayoutVMNK which is (_128,_1,_1,_1):(_1,_0,_0,_0), the stride is strange, is there something wrong in my code? thanks.

**Comment by ccecka** [comment]
Surprisingly, this seems to occur for only a few compilers. This will be included in our update as soon as possible, but in the meantime can you try this patch:
`---
 include/cute/stride.hpp | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/include/cute/stride.hpp b/include/cute/stride.hpp
index d710ab8d1..b50ec9c00 100644
--- a/include/cute/stride.hpp
+++ b/include/cute/stride.hpp
@@ -194,7 +194,12 @@ idx2crd(Index  const& idx,
         return transform(shape, compact_col_major(shape, stride), [&](auto const& s, auto const& d){ return idx2crd(idx,s,d); });
       }
     } else {                                     // "int" "int" "int"
-      return (idx / stride) % shape;
+      if constexpr (is_constant<1, Shape>::value) {
+        // Skip potential stride-0 division
+        return Int<0>{};
+      } else {
+        return (idx / stride) % shape;
+      }
     }
   }
 
--`

**Comment by mengchihe** [comment]
> Surprisingly, this seems to occur for only a few compilers. This will be included in our next update as soon as possible, but in the meantime can you try this patch:
> 
> ```
> ---
>  include/cute/stride.hpp | 7 ++++++-
>  1 file changed, 6 insertions(+), 1 deletion(-)
> 
> diff --git a/include/cute/stride.hpp b/include/cute/stride.hpp
> index d710ab8d1..b50ec9c00 100644
> --- a/include/cute/stride.hpp
> +++ b/include/cute/stride.hpp
> @@ -194,7 +194,12 @@ idx2crd(Index  const& idx,
>          return transform(shape, compact_col_major(shape, stride), [&](auto const& s, auto const& d){ return idx2crd(idx,s,d); });
>        }
>      } else {                                     // "int" "int" "int"
> -      return (idx / stride) % shape;
> +      if constexpr (is_constant<1, Shape>::value) {
> +        // Skip potential stride-0 division
> +        return Int<0>{};
> +      } else {
> +        return (idx / stride) % shape;
> +      }
>      }
>    }
> --
> ```

it works, thanks.
