### ISSUE TITLE
Question how to modify math of the GEMM op

### ISSUE THREAD

**Issue by maljoras** [NVIDIA/cutlass#92]
I would like to implement a modified GEMM computing a matrix product C_ik = \sum |A_ij| |B_jk| , in other words the usual GEMM but with element-wise absolute values. Of course I could write a simple separate kernel computing the absolute values, but that would be a performance and memory hit, because I cannot do it in-place.   How to best make such a custom GEMM kernel that works on several architectures with CUTLASS?  Can I somehow add a transform to the  input iterator in the spirit of CUB's TransformInputIterator (or similar to the CUTLASS's ComplexTransform maybe) ? Should I write my own  iterator for that (but then there seems to be a number of iterators on various hierarchy levels, not sure which one to change)? Or should I modify the math of arch::mma (although then I would need to change it for all architectures it seems)?     Or should I overload the reduction op, to (compute)  and sum the absolute values (but this would only work if the reduction op is on element level and not maybe on tile level, not sure which is the case)?

Is there an easy way to handle this? Thanks a lot.

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-62

**Comment by hwu36** [comment]
You can do the transform here https://github.com/NVIDIA/cutlass/blob/e33d90b36109f67915a80c532ebbb978b72c7bd2/include/cutlass/gemm/threadblock/mma_pipelined.h#L73 .  Pass a functor that can do your math to `TransformA`.  You can write your functor similar to the default `NumericArrayConverter`.
