### ISSUE TITLE
[QST] High level guide to implement 4d convolution based on implicit gemm 

### ISSUE THREAD

**Issue by YuraCobain** [NVIDIA/cutlass#926]
**What is your question?**
Hello,

I would like to implement 4d/5d convolution based on implicit gemm using cutlass. 
One way is to decompose high level convolution into series of 3d problems then use 3d convolution and then stack them back into original space on the host.
However, it looks that for better performance it's better to implement  4d convolution using 3d on device level directly.

Could please describe if it's feasible using cutlass reusable building block and make very high level guide l, source file that should be updated and reference commits that could be used as example?

**Comment by hwu36** [comment]
Thank you for being willing to do it.  We welcome the community to contribute to 4d conv.  It is not difficult at all.

You just need to diff the change of 3d conv and 2d conv, and then do the same thing for 2d conv.

We have 2 set of conv algorithms.  Analytical and Optimized.  You can just focus on Analytical first.  When this is done, extending analytical to optimized is very natural.

Back to the code.  

https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/threadblock/conv2d_fprop_activation_tile_access_iterator_analytic.h is 2d iterator to load activations

https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/threadblock/conv3d_fprop_activation_tile_access_iterator_analytic.h is 3d iterator to load activations

If you diff these 2 files, the main difference is that you have 2 new variables `filter_t_` and `offset_z_` which is used when mapping 3d to 2d.  And that is it.  When you do 4d, just add a couple of new variables to map 4d to 3d.

You can then do the same for the filters.  2d filter:  https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/threadblock/conv2d_fprop_filter_tile_access_iterator_analytic.h    3d filter: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/conv/threadblock/conv3d_fprop_filter_tile_access_iterator_analytic.h

The rest is even easier, create a device and kernel level code just like 3d conv ones to use your new iterators.  That is it.

We have 3d conv unit tests in https://github.com/NVIDIA/cutlass/blob/main/test/unit/conv/device/conv3d_fprop_implicit_gemm_f16ndhwc_f16ndhwc_f32ndhwc_tensor_op_f32_sm80.cu  

You could start from modifying these unit tests!

Good luck and thank you!

**Comment by YuraCobain** [comment]
Thank you for instructions.
After unit test I would like also to do benchmarks via cutlass_profiler.
Could please also give small guidet how to add correctly conv4d to it and tune for the best perfomance?

**Comment by manishucsd** [comment]
I see conv4d, conv5d request. We already have conv2d and conv3d. I would recommend considering developing trulely convNd implementation where conv2d, 3d, 4d, and 5d be implemented using single convNd implementation. N can be another template parameter to your implementation. 

Once you have convNd implementation you can compare the performance of templated convNd implementation against conv2d, i.e., `perf(conv2d) ~= perf(convNd<N=2>).`  

This will reduce the code and you will have both conv4d and conv5d implementation. Yeah, it is more templatized :). I think it is doable. thoughts?

**Comment by YuraCobain** [comment]
Sure, it's feasible, however as you said it's magic(sometimes hell) of C++ template metaprogramming. 
Unfortunately I am short of time to have working 4d convolution so boilerplate but straightforward implementation is preferable right now.
After it I would to try to generalize it.

**Comment by mnicely** [comment]
@YuraCobain is your issue resolved?

**Comment by YuraCobain** [comment]
Actually yes.
At this moment I implemented ugly but working 4d and 5d convolution, however I would like to generalize it and propose convNd PR when I will have enough spare time. 
Thanks.
