### ISSUE TITLE
[QST]How to calculate Dgrad and Wgrad of convolution?

### ISSUE THREAD

**Issue by lk137095576** [NVIDIA/cutlass#928]
**What is your question?**
I profile the convolution kernel with train model in A100 of fp32(no tensor core):
conv2d config:
input:128 * 256 * 56 * 56
kernel_size: 1 * 1
output: 128 * 256 * 28 * 28
stride:2

get the kernel like:(this example is cudnn, but the same result in cutlass)
""void cudnn::detail::dgrad_engine<float, 512, 6, 5, 3, 3, 3, false>........"
It looks like the kernel to caculate dgrad.
I get the caculate method from  https://docs.nvidia.com/deeplearning/performance/dl-performance-convolutional/index.html#imp-gemm-dim
format the conv to gemm:
M: 128 * 56 * 56 = 401408
N: 256
K: 512 * 1 * 1=512
So I get the gemm with M(401408)  N(512) K(256) 
so the ideal time is 2 * M * N * K/fp32_fplos = 2 * 401408  *  512  *  256 / 19500000000000 = 5396 us
but the profile time is  1797us . less than Theoretical time. 
whether I get error MNK ?

**Comment by hwu36** [comment]
It is strided dgrad.  Lots of computations can be skipped.

**Comment by lk137095576** [comment]
> 

@hwu36 Thanks for your reply, can you provide some document to read? I want to know the theorety.

**Comment by hwu36** [comment]
We had a gtc talk several 1 year ago about strided dgrad.  It was from @manishucsd

**Comment by lk137095576** [comment]
> We had a gtc talk several 1 year ago about strided dgrad. It was from @manishucsd

I got it , THANKS.
https://www.nvidia.com/en-us/on-demand/session/gtcspring22-s41996/

**Comment by manishucsd** [comment]
There is no need for another kernel to compute strided dgrad indices. It can be managed in one kernel with some re-shuffling in prologue and shuffling back in original order in epilogue. 

> (no tensor core)
But why no tensor cores. I think CUTLASS strided dgrad might only implemented for Tensor Cores. I haven't looked into the current code, just trying to recall from the time we worked on it.
