### ISSUE TITLE
[QST] using NCxHWx layout for float32 conv2d

### ISSUE THREAD

**Issue by TUMSchieben** [NVIDIA/cutlass#929]
**What is your question?**
Hi all,

I noticed there is `NCxHWx` layout for Implicit GEMM convolution, but there is no example for this. AFAIK, tensorrt sometimes uses this layout in their conv kernels (together with reformat NHWC-->NCxHWx kernels).

What's the benefit of using this layout? And is it possible to use this layout for float32 conv2d ops using cutlass?

Thanks!

**Comment by hwu36** [comment]
This layout can only be used with int8 or int4
