### ISSUE TITLE
[QST] Unexpect result when add_tile_offset alone non-advance rank.

### ISSUE THREAD

**Issue by grimoire** [NVIDIA/cutlass#931]
**What is your question?**
Hi,
I am a little bit confused by `add_tile_offset` in `PredicatedTileAccessIterator`

https://github.com/NVIDIA/cutlass/blob/df02482f1d429281bf7dda498259939cf0e79d06/include/cutlass/transform/threadblock/predicated_tile_access_iterator.h#L527

As the comment indicate `Advances an iterator along logical dimensions of matrix in units of whole tiles`, pointer should be move along both axes with tile strides. But since the pointer is a byte pointer, simply add `Shape::kContiguous * tile_offset.contiguous();` would lead to wrong result when `size_of(Element)!=1`. Why don't we use `add_pointer_offset` here? Or did I misunderstand the usage of this method?

**Comment by hwu36** [comment]
you are right.  we will fix it in the next release.

this line is never used because we move along the `k` dimension when doing gemm.  this line is used if moving along `m` or `n` dimension.

**Comment by mnicely** [comment]
Fixed in 3.1
