### ISSUE TITLE
CUTLASS 2.2 for Ampere?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/cutlass#94]
Hi,
now that CUDA 11 and CUDNN 8 are released.. waiting for CUTLASS 3.0.. :-)

**Comment by cliffburdick** [comment]
CUTLASS 2.2 was announced to support Ampere:

https://developer.nvidia.com/gtc/2020/video/s21745-vid

**Comment by oscarbg** [comment]
sorry.. seen the video two weeks ago.. forgot the version number.. :-)

**Comment by kerrmudgeon** [comment]
Correct, this is CUTLASS 2.2. I have just pushed our branch and will merge it shortly. Feel free to try it out!
