### ISSUE TITLE
[QST] GEMM time increases when using gemm_softmax in example35

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#943]
Hello! I am testing with example35. However, during my testing, I have noticed two things that seem strange. Firstly, when compared to performing gemm+softmax using cublas and cudnn, example35 increases GEMM time by 80% and decreases softmax time by 60%, which ultimately leads to a 30% shorter execution time. Why does the performance of GEMM decrease so much compared with cublas? Secondly, I used cutlass's profiler to choose the best configuration by profiling the same shape (--m=1024, --n=1024, --k=64, --batch_count=768) on GEMM. However, I found that the best configuration suggested by the profiler did not achieve the best performance. Could this be because the profiler cannot profile this pattern accurately?

So sorry for the lack of detail in this issue, I will add more information about how I apply this testing and the output of nsys profiler which displays the GEMM time and softmax time tomorrow.

**Comment by hwu36** [comment]
ex 35 fuses most of the softmax computation into the gemm epilouge.  so the following kernels are light.

**Comment by hwu36** [comment]
@yzhaiustc

**Comment by yzhaiustc** [comment]
Thanks @hwu36 for looping me in. As @hwu36 clarified, the GEMM kernel in example 35 is an custom one with partial reduction ops in softmax fused, so you observed a heavier kernel compared with cuBLAS. 
You're welcome to put follow-up questions regarding example 35 in this thread. Thanks.

**Comment by mnicely** [comment]
@umiswing has your questions been answered?

**Comment by umiswing** [comment]
> @umiswing has your questions been answered?

Oh, yes! Sorry for late reply.
