### ISSUE TITLE
[QST] what is cosize_v<ABlockLayout> in CuTe tutorial?

### ISSUE THREAD

**Issue by rayleizhu** [NVIDIA/cutlass#944]
Is it used to avoid bank conflict? How does it work?

https://github.com/NVIDIA/cutlass/blob/fcfbd23e26328df8c8b720a161ada95a3eb725e8/examples/cute/tutorial/sgemm_nt_1.cu#L77

**Comment by thakkarV** [comment]
Cosize is the codomain's size for a layout. In this specific instance it's important to use cosize instead of size if the layout to allocate the shared memory correctly (non compact layouts have a cosize larger than size)

**Comment by rayleizhu** [comment]
> Cosize is the codomain's size for a layout. In this specific instance it's important to use cosize instead of size of the layout to allocate the shared memory correctly (non compact layouts have a cosize larger than size)

* In a high level, is the goal of using codomain size to avoid bank conflict?
* What do you mean by `non-compact layouts` and `allocate the shared memory correctly`? Can you give an example?

**Comment by YichengDWu** [comment]
Say you have a non-compact layout
```c++
       1    2    3    4    5
    +----+----+----+----+----+
 1  |  1 |  5 |  9 | 13 | 17 |
    +----+----+----+----+----+
 2  |  2 |  6 | 10 | 14 | 18 |
    +----+----+----+----+----+
 3  |  3 |  7 | 11 | 15 | 19 |
    +----+----+----+----+----+
```
The size is 3*5=16, but cosize is 19. `size` is the logical length, `cosize` can be treated as the physical length.

**Comment by mnicely** [comment]
@rayleizhu is you issue resolved?

**Comment by rayleizhu** [comment]
> @rayleizhu is you issue resolved?

Yes, thanks.

**Comment by ngocson2vn** [comment]
For CUTLASS's CuTe newbies like me, the following is a concrete example:
```C++
#include <cstdio>
#include "cute/layout.hpp"

using namespace cute;

int main(int argc, char** argv) {
  Layout layout = make_layout(
    make_shape(Int<3>{}, Int<5>{}),
    make_stride(Int<1>{}, Int<4>{})
  );
  printf("layout: ");
  print_layout(layout);
  printf("\n");

  // domain: what can go into a function
  printf("%17s", "domain: [");
  for (int i = 0; i < size(layout); i++) {
    if (i == 0) { printf("%d", i); } else { printf(", %2d", i); }
  }
  printf("]\n");

  // range: what actually comes out of a function
  printf("%17s", "range: [");
  for (int i = 0; i < size(layout); i++) {
    if (i == 0) { printf("%d", layout(i)); } else { printf(", %2d", layout(i)); }
  }
  printf("]\n");

  // codomain: what may possibly come out of a function
  printf("%17s", "codomain: [");
  for (int i = layout(0); i < (layout(size(layout) - 1) + 1); i++) {
    if (i == 0) { printf("%d", i); } else { printf(", %2d", i); }
  }
  printf("]\n\n");

  // size and cosize
  printf("%14s: %d\n", "size(layout)", (int)size(layout));
  printf("%14s: %d\n", "cosize(layout)", (int)cosize(layout));
  printf("%14s: %d\n", "cosize(layout)", (int)layout(size(layout) - 1) + 1);

  return 0;
}
```

Output:
```Bash
./main
layout: (_3,_5):(_1,_4)
       0    1    2    3    4 
    +----+----+----+----+----+
 0  |  0 |  4 |  8 | 12 | 16 |
    +----+----+----+----+----+
 1  |  1 |  5 |  9 | 13 | 17 |
    +----+----+----+----+----+
 2  |  2 |  6 | 10 | 14 | 18 |
    +----+----+----+----+----+

        domain: [0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]
         range: [0,  1,  2,  4,  5,  6,  8,  9, 10, 12, 13, 14, 16, 17, 18]
      codomain: [0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

  size(layout): 15
cosize(layout): 19
cosize(layout): 19
```

By definition, the variable `layout` is actually a function that maps a **domain** to its **codomain**.  
The domain is `[0, size(layout) - 1] = [0, 14]`.  
The codomain is `[layout(0), layout(14)] = [0, 18]`, which is different from the **range**, as the range represents what actually comes out of the `layout` function.  
The **cosize** is the size of the codomain, which is `19`.
