### ISSUE TITLE
[QST] Hopper's DSMEM feature support

### ISSUE THREAD

**Issue by chengyupku** [NVIDIA/cutlass#949]
Hi,
As we know, Hopper adopts Distributed Shared Memory (DSMEM), which allows the blocks inside the cluster to exchange data.
I have two questions. First, for `wgmma` instruction, when the input is in smem, does `wgmma` only support the smem address inside the local CTA and not the smem address of other CTAs in the cluster? I didn't find it clearly stated in the PTX ISA doc [here](https://docs.nvidia.com/cuda/parallel-thread-execution/#asynchronous-warpgroup-level-matrix-multiply-accumulate-instructions).
Second, I did not find in CUTLASS 3.1 that CUTLASS utilizes the DSMEM feature. Will this feature be supported in the future? Or is this feature of little use in mma since the bandwidth provided by TMA's multicast is already large enough to achieve peak FLOPS?
Thanks!

**Comment by hwu36** [comment]
hopper wgmma is cluser level mma which means it fetches data from all ctas within the cluster.  cutlass 3.1 uses it.

**Comment by chengyupku** [comment]
I haven't fully understood, the doc says `wgmma` is 

> Asynchronous Warpgroup Level Matrix Multiply-Accumulate

It seems that it's warpgroup level. A basic question is whether the threads in warpgroup can exist in different CTA of cluster? If not, then why is `wgmma` a cluster level mma instruction?

**Comment by hwu36** [comment]
sorry, i misstyped.  it is warpgroup level mma.  it needs dsmem to feed the data.

**Comment by chengyupku** [comment]
OK, I got it. So the `a-desc` (the address for input `A` in smem) in `wgmma` issued by a thread can be a smem address of other CTA in the cluster?

**Comment by thakkarV** [comment]
@chengyupku The MMA itself does not make use of DSMEM addresses, however, TMA multicast requires the use of DSMEM, as the transaction barriers that need to be updated for a multicasting TMA need not be in the local CTA's shared memory. See: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/arch/barrier.h#L394

**Comment by chengyupku** [comment]
> @chengyupku The MMA itself does not make use of DSMEM addresses, however, TMA multicast requires the use of DSMEM, as the transaction barriers that need to be updated for a multicasting TMA need not be in the local CTA's shared memory. See: https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/arch/barrier.h#L394

Thanks! :)
