### ISSUE TITLE
Can I fuse Non-Element-wise Operations with GEMM by CUTLASS?

### ISSUE THREAD

**Issue by xmyqsh** [NVIDIA/cutlass#95]
Hello, I found the `Fusing Element-wise Operations with SGEMM` demo introduced by CUTLASS.

Now, I want to `gather` the input feature first, and then run `GEMM`, at last `scatter` to output feature.

Can I fuse these three kernel steps into one fused GEMM by CUTLASS?

If can, how?
If cannot, any other suggestions for this fused gemm requirement?

Aha! Link: https://nvaiinfa.aha.io/features/CUTLASS-60

**Comment by xmyqsh** [comment]
Any reply?
Here is some analyses in more details:
https://github.com/traveller59/spconv/issues/155

**Comment by hwu36** [comment]
@Laurawly @Meteorix , another request for gather/scatter.

**Comment by hwu36** [comment]
also add @shangz-ai
