### ISSUE TITLE
[QST] Is it possible to implement a batch version of Tensor4DPermute0213 as in example 39?

### ISSUE THREAD

**Issue by umiswing** [NVIDIA/cutlass#953]
Hello! The pattern [Tensor4DPermute0213](https://github.com/NVIDIA/cutlass/blob/main/examples/39_gemm_permute/gemm_permute.cu#L225) in example 39 is useful in my system. But the example is a normal GEMM version while I would like to use a batch GEMM version. Is it possible to implement a batch version of this pattern?

**Comment by hwu36** [comment]
I think it can work with batch gemm.  worst case is that you need to write a new functor to permute following the existing example.  @shangz-ai

**Comment by umiswing** [comment]
Thanks. :)
