### ISSUE TITLE
[QST] Basic Questions about ProblemSizes, GemmShapes an Matrix Layouts

### ISSUE THREAD

**Issue by FabianSchuetze** [NVIDIA/cutlass#954]
Thanks for this wonderful repo! It's a pleasure to work with it. 

I have a few beginner questions. I read the documentation and unit tests, but I can only come up with vague answers so I wanted to ask for clarification.

- What is the relationship between the ProblemSize and the ThreadblockShape, WarpShape, and InstructionShape (GemmShapes)? Do I understand correctly that the ProblemSize needs to be (integer) multiple of the ThreadblockShape? Furthermore, the GemmShapes itself are multiples of one another?

- Where can I see which GemmmShapes are legal for a specific ArchTag? I currently use multiples of 32. However, this is based on trial and error and a typical Cuda warp block size of 32.

- Are the same legal (not necessarily optimal) GemmShapes independent of the different data types (int8 and float, for example)? 
 
- Which matrix layouts are compatible with a specific operation? The unit tests document some restrictions, but I would be happy to be able to infer this from a header file or some documentation.

**Comment by hwu36** [comment]
problem size is the gemm problem size you want to run.  it does not have to be the multiple of threadblock size, but it has the alignment restrictions.

instruction shape is the tensor core instruction supported.  cuda ptx doc listed all the available tensor instructions for every arch. you can find the similar info from include/cutlass/arch/mma***.h

fp16 and fp32 tensor core gemms support all combinations of row/col.  int8, int4 only supports row x col or interleaved layout. int1 only supports row x col.

**Comment by FabianSchuetze** [comment]
Thanks a lot for the comment, @hwu36 . These comments are extremely valuable and educational. Just one follow up on: 

>  problem size is the gemm problem size you want to run. it does not have to be the multiple of threadblock size, but it has the alignment restrictions.

Can you elaborate a bit more on the alignment restrictions?

**Comment by hwu36** [comment]
check https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/kernel/gemm_universal.h#L367-L433

**Comment by FabianSchuetze** [comment]
Thanks for the all the answers.
