### ISSUE TITLE
[QST] Is there way to upscale input before convolution?

### ISSUE THREAD

**Issue by YuraCobain** [NVIDIA/cutlass#962]
One way to add numerical stability of tf32 for backward convolution in case of high rank operations (>=3) is to upscale inputs by some constant and after operation downscale output by it.
Of course, for downscaling alpha should be used.

In there way in cutlass to fuse up scaling?

**Comment by YuraCobain** [comment]
Close by pure accident.

**Comment by hwu36** [comment]
you can upscale inside `transform` function (https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/gemm/warp/mma_tensor_op.h#L368).  It currently does some type conversion work, but you can change it to do upscaling.

As to downscaling, you can do it in the elementwise op of the epilogue.  For example, the default and the most common elemenwise operation is https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/thread/linear_combination.h  You can add your downscaling in side `operator()`.

**Comment by YuraCobain** [comment]
Thanks, it is clear.
