### ISSUE TITLE
[QST] Dose DefaultEpilogueSimt support scatterD ? 

### ISSUE THREAD

**Issue by vectorda** [NVIDIA/cutlass#965]
I'm implementing a small-k gather-gemm-scatter fusion kernel using simt. All things go right in gather and accumulation stage. However, incorrect result returns after scattering (I use native `OutputTileOptimalThreadMap` and `epilogue::threadblock::PredicatedTileIterator` as thread map and output iterator respectively). After debugging, I find out the error occurs in method `store_with_byte_offset` group and column cycle  --- https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/threadblock/predicated_tile_iterator.h#L431. Variable `memory_pointer` will increase `ThreadMap::Delta::kColumn (detail::RowArrangement<..., false>::kDeltaColumn == 32)` so that my global write-back address runs two more rows (my problem size N in test is 16) in each iteration. I tried to rewrite thread map but it was incompatible with native output iterator.
So, is there any better way to solve it except rewriting output iterator?
Btw, how to understand concept `group` and `cluster` in `OutputTileShape`?

**Comment by hwu36** [comment]
you can ignore `group` and `cluster`. 

your problem size N is 16, what is your threadblock tile size N?

**Comment by mnicely** [comment]
@vectorda have you resolved your issues?

**Comment by vectorda** [comment]
@mnicely yep. appreciate your help.
