### ISSUE TITLE
[QST] Is possible to add support of single input/output channel for conv3d_fprop?  

### ISSUE THREAD

**Issue by YuraCobain** [NVIDIA/cutlass#966]
**What is your question?**
Backward path of transpose convolution uses fprop on permuted input where input channels and batches are swapped.
However in case of single batch after permutation input tensor has single input channel and such problem size is not supported by conv3d_frop(in my case I used 4d ) .
Is there simple(could be slow performance) solution to support such tensor in cutlass?

**Comment by hwu36** [comment]
you need to add small alignment support to 3d conv.  small aligned 2d conv is added here https://github.com/NVIDIA/cutlass/pull/246 .  Note single channel perf would be pretty bad.

Or is what need is essentially 3d group conv?

**Comment by YuraCobain** [comment]
Thanks for reply.
I will look at 2d case deeper, however first attempt failed.
I am not familiar with conv group feature.
What I need backward for transpose convolution that switch channels and batches dimensions and then perform fprop.
I think about custom iterator that virtually load 128 bits, zero all expect first channel and custom epilogue that write back only the first channel.
Is it feasible?

**Comment by hwu36** [comment]
> I think about custom iterator that virtually load 128 bits, zero all expect first channel and custom epilogue that write back only the first channel.
> Is it feasible?

No if you input is packed.  You will get illegal memory access.

**Comment by YuraCobain** [comment]
It's only possible on the last element of the tensor and this  could be handled specifically. 
Pointer to the global memory is advanced by real numbers of channels, however internally all operations are done by the closest factor of 4, output perform in similar manner.
It could be nice feature to support arbitrary number of channels and provide the optimal performance that is close to nearest factor of 4.

**Comment by hwu36** [comment]
suppose your first element address is 0x0, your second is 0x2, third is 0x4.  you cannot use 128bit load to load from 0x2 or 0x4.  address needs to be 128bit aligned too.  it is hardware requirement in any modern chips.

**Comment by YuraCobain** [comment]
I can read 4 times from address 0x0, after each read shift elements to left to have target element on the right place and zero rest.
After elements per vector reads advance global pointer by 128.

**Comment by hwu36** [comment]
that will be super slow and complicated.

small alignement is much easier to implement.

**Comment by YuraCobain** [comment]
Thanks for clarification.
I will analyze 2d approach you mention.
Could you please point what is the most important piece of code to start from?

**Comment by hwu36** [comment]
just pay attention to the change in `include/cutlass/conv/threadblock/conv2d_fprop_*.h`.  The change is small.

**Comment by hwu36** [comment]
it just split one 128bit load into several small load.  pay attention to the new variable `iteration_vector_`.

**Comment by YuraCobain** [comment]
Small alignment approach solved my issue.
Thanks.

**Comment by hwu36** [comment]
more than welcome to upstream small alignment of conv3d.

**Comment by YuraCobain** [comment]
Unfortunately small alignment was port for conv4d that is not part of official CUTLASS. 
Ideally, I would like to contribute to generic implementation of conNd to have universal tool easily instantiate any high rank convolution in few weeks, hopefully.
