### ISSUE TITLE
[QST] Why __sqrtf run good in Orin(aarch64) but not in RTX3070 x86 ?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/cutlass#972]
One kernel in my code include follow:  
```
    float scalar = 1 / (__sqrtf(size_per_head_ * 1.0f) * q_scaling_);
```  

In Orin , **compile pass, run pass**; 
In RTX3070, **compile pass, run error**, report follow error:   

symbol lookup error: : undefined symbo: __sqrtf     

Why `__sqrtf` run good in Orin(aarch64) but not in RTX3070 x86 ?

And if I use `sqrtf`  https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE_1gcb80df3c252b3feb3cc88f992b955a14
in both arch are run pass.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/#mathematical-functions-appendix   

Envs:  
cuda-11.4   
cudnn 11.6

**Comment by hwu36** [comment]
use `sqrtf` from cuda.  it handles arch, compiler portability issues for you.
