### ISSUE TITLE
Question: Doubt in examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu

### ISSUE THREAD

**Issue by navdeepkk** [NVIDIA/cutlass#98]
Hi, in the file cutlass/examples/08_turing_tensorop_gemm/turing_tensorop_gemm.cu, in line number 80 is the flow correct?
matrix in global memory -> registers -> tile in shared memory -> registers -> mma -> registers ->
output to global memory.
Particularly is the 'registers' after 'global memory' is correct?

**Comment by kerrmudgeon** [comment]
Yes, fetching data from global memory via traditional ld.global instructions in PTX places the data held in registers. The double-buffered pipeline scheme then stores from registers to shared  memory.

NVIDIA Ampere introduces asynchronous copy which moves data directly from global memory to shared memory.  This is described in [NVIDIA Ampere Architecture In-Depth](https://devblogs.nvidia.com/nvidia-ampere-architecture-in-depth/) and implemented in PTX using [`cp.async`](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/memory_sm80.h).

**Comment by navdeepkk** [comment]
@kerrmudgeon Thanks! BTW I am new to GPU programming and want to dive deep into how cutlass is doing things on the tensor core side. What do you say the best approach would be. Diving into the source and seeing how things are being done, and maybe trying to implement a single kernel that does matmul on tensor cores?
