### ISSUE TITLE
[QST] Why cutlass profiler for GEMV shows best perf for s16816gemm & relationship with `mma.sync.aligned`

### ISSUE THREAD

**Issue by fxmarty** [NVIDIA/cutlass#981]
Hi,

Using cutlass profiler with

```
./tools/profiler/cutlass_profiler --operation=Gemm --m=8192 --n=1 --k=8192 --A=f16 --B=f16
```

on an A100, the kernel `cutlass_tensorop_f16_s16816gemm_f16_256x128_32x3_nn_align8` seem to be the best. As my understanding goes, this means that this kernel will at some point issue `mma.sync.aligned.m16n8k16` instructions (referring to [here](https://github.com/NVIDIA/cutlass/blob/fc9ebc645b63f3a6bc80aaefde5c063fb72110d6/tools/library/scripts/gemm_operation.py#L80-L87).

I don't understand why the best choice for GEMV is not rather to issue `mma.sync.aligned.m8n8k4` instructions, since with GEMV we have (mostly) garbage data in the tensor core results. For `mma.sync.aligned.m16n8k16`, only `1/16` of the output is relevant, while for `mma.sync.aligned.m8n8k4` we have `1/8` of the output that is relevant.

Note: I am not sure that my understanding of the kernel name is correct (that is that the `s16816gemm` corresponds to `mma.sync.aligned.m16n8k16`), as https://github.com/NVIDIA/cutlass/blob/main/media/docs/functionality.md#warp-level-matrix-multiply-with-tensor-cores "instruction shape" has much more variety than [Nvidia documentation](https://docs.nvidia.com/cuda/parallel-thread-execution/#matrix-shape) (where only m8n8k4, m16n8k8 and m16n8k16 is available for mma).

Edit: It appears that only `mma.sync.aligned.m16n8k16` is defined in `mma_sm80.h` (https://github.com/NVIDIA/cutlass/blob/fc9ebc645b63f3a6bc80aaefde5c063fb72110d6/include/cutlass/arch/mma_sm80.h#L399). According to https://arxiv.org/abs/2206.02874 the reason may be that on Ampere `m8n8k4` compiles down to FPU instructions
which will eventually run on the CUDA cores. Is this correct?

As a more general question, if you have any insights on why tensor core are preferred for GEMV over cuda cores, that would be helpful!

Thank you!

**Comment by hwu36** [comment]
profiler does not include gemv kernels.

For your case, gemv w/o mma should be faster.

cutlass included gemv in the latest release.

**Comment by fxmarty** [comment]
@hwu36 pytorch picks cublas `ampere_fp16_s16816gemm` kernel as well for GEMV.

> For your case, gemv w/o mma should be faster

Could you give the intuition why? Is my intuition about wasted mma compute correct? I've seen contradictory claims about it.

**Comment by hwu36** [comment]
your understanding is correct.  mma is wastes too much.

**Comment by fxmarty** [comment]
Thank you!

**Comment by hwu36** [comment]
@NVJiangShao
