### ISSUE TITLE
[QST] How to use cutlass_profiler for int8 gemm?

### ISSUE THREAD

**Issue by chenzhengda** [NVIDIA/cutlass#982]
**What is your question?**
Doed cutlass_profiler support  int8 gemm profile?
How to use cutlass_profiler for int8 gemm?

**Comment by jackkosaian** [comment]
Yes, the CUTLASS profiler does support profiling INT8 GEMMs.

To specify a subset of kernels to be compiled in building the profiler, you can use the `CUTLASS_LIBRARY_KERNELS` CMake option (see [here ](https://github.com/nvidia/cutlass#building-a-subset-tensor-core-gemm-kernels) for an example).

Kernels related to INT8 have `s8` in the kernel name (for signed 8-bit integer). To see all of the INT8-related kernels available in the profiler, you can configure CMake with `-DCUTLASS_LIBRARY_KERNELS="*s8*"` and list the generated GEMMs under `build/tools/library/generated/gemm`.

It's not recommended to build the profiler with too many kernels, so you will likely want to refine the argument you pass to `CUTLASS_LIBRARY_KERNELS` further. For example, you could generate a smaller set of INT8 GEMM kernels to be compiled by the profiler using `-DCUTLASS_LIBRARY_KERNELS=cutlass_tensorop_i16832gemm_s8_*_tn_align16`

**Comment by mnicely** [comment]
I believe the question has been resolved
