### ISSUE TITLE
[BUG] ABI alignment error building cutlass_profiler with -DCUTLASS_NVCC_ARCHS=90a

### ISSUE THREAD

**Issue by AshrafMichail** [NVIDIA/cutlass#986]
**Describe the bug**
cutlass_profiler build error when building with -DCUTLASS_NVCC_ARCHS=90a. 
No build errors without the -DCUTLASS_NVCC_ARCHS=90a parameter.

cutlass/include/cutlass/device_kernel.h:107:1: note: the ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
  107 | void device_kernel(CUTLASS_GRID_CONSTANT typename Operator::Params const params)
      | ^~~~~~~~~~~~~

**Steps/Code to reproduce bug**
mkdir cutlass/build_sm90a
cd cutlass/build_sm90a
cmake .. -DCUTLASS_NVCC_ARCHS=90a
cd tools/profiler
make -j16

**Expected behavior**
Build without errors

**Environment details (please complete the following information):**
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Build cuda_12.2.r12.2/compiler.32965470_0

**Comment by hwu36** [comment]
warning or error?

**Comment by AshrafMichail** [comment]
It's a warning treated as an error and no cutluss_profiler is produced.  This doesn't look like an ignorable warning as the problem sounds severe.

**Comment by thakkarV** [comment]
The problem is not severe at all. Please see [#906](https://github.com/NVIDIA/cutlass/issues/906#issuecomment-1494533624)

**Comment by AshrafMichail** [comment]
Suppress with -Wno-psabi so that people know it's not an issue?

**Comment by thakkarV** [comment]
Please see the link above, we have tried many strategies for disabling that output note to no avail

**Comment by AshrafMichail** [comment]
Perhaps add a #message or comment so people know this is benign?  Presently, the way to know this is not an issue is to find issue #906 above or analyze the code.
