### ISSUE TITLE
[QST] CUTLASS 3.x GEMM performance for non-Hopper GPUs

### ISSUE THREAD

**Issue by dchen496** [NVIDIA/cutlass#988]
**What is your question?**

Hi, is it recommended to use CUTLASS 3.x GEMM kernels for non-Hopper architectures with Tensor cores? We'd like to take advantage of the simplicity offered by CuTe. However, we've noticed that the kernel performance is not as good as CUTLASS 2.x yet. 

It seems that things like grid swizzling are not yet supported. If we implemented that, should we expect performance to be on-par with CUTLASS 2.x (at least for the most straightforward tensor core GEMM kernels, ignoring stuff like split/stream-K), or will we run into other issues?

**Comment by hwu36** [comment]
we haven't tuned cutlass 3 for perf on pre hopper architectures.  cutlass 2.x is well tuned.

if you manage to let cutlass 3 generate similar ptx as cutlass 2, then you can get good performance.

**Comment by dchen496** [comment]
Thanks, we will build on top of the CUTLASS 2 kernels then for now.

**Comment by thakkarV** [comment]
@dchen496 I am confused, why would swizzling not be supported? We have test kernels for Ampere, Volta, Turing that do support swizzled smem layouts.
