### ISSUE TITLE
cute performance is lower than expected[QST]

### ISSUE THREAD

**Issue by decioren** [NVIDIA/cutlass#989]
Running the Cute example out of the box, the cute is x2 slower than Cublass for float32 input. Moreover, moving to float16 does not supply the expected x2 speedup (only ~25%).
This is on an Ampere GPU.
Please advise...

**Comment by hwu36** [comment]
cutlass3.x/cute is not optimized on ampere.  you could use cutlass 2.x on ampere to get good performance.

cutlass3.x/cute is awesome on hopper.

**Comment by decioren** [comment]
thank you for your super fast response.

Is there a plan to support better performance at least on ampere in future releases of Cute? (we would not like to support two backends)
also when you say it optimize for Hopper, is Ada Lovelace included,? or is it only for datacenter GPUs?

**Comment by hwu36** [comment]
cute is focusing on hopper now.

ada is an ampere architecture. it needs cutlass 2.x to get the best perf.

**Comment by decioren** [comment]
once again thank you.
Cute is indeed a much more pleasant way to work with cutlass than the 2.x API. If it is ever more generally deployable, count me in.

**Comment by thakkarV** [comment]
@decioren  Just a note, there is no such thing as "CuTe performance". CuTe is merely a programming model. We simply have not implemented CUTLASS 3.x API exposure for pre-Hopper kernels based on CuTe. There should be no pratical limitation in you being able to achieve performance parity with or without CuTe against cuBLAS/CUTLASS Ampere.

**Comment by decioren** [comment]
I am running the example in cutlass\examples\cute\tutorial out of the box.
I also made some modifications for fp16 and the results are similar.
I found no other explicit example for CuTe. Are there other starting points to use?

**Comment by thakkarV** [comment]
CuTe examples are not optimized for performance and are written to walk users through the programming model instead. If you want to benchmark performance of Ampere kernels the closest we have to optimized pure CuTe kernels are the Ampere tests using the 3.x API: https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/sm80_gemm_f16_f16_f32_tensor_op_f32.cu

**Comment by decioren** [comment]
Thanks, I will look into it

**Comment by mnicely** [comment]
@decioren has your issue been resolved?

**Comment by decioren** [comment]
This issue actually moved to another developer. Right now hist decision is not to use cute.

**Comment by mnicely** [comment]
Thanks @decioren, I'm going to close for now. Feel free to reopen if needed.
