### ISSUE TITLE
[QST] Does cutlass profiler search for all possible configurations

### ISSUE THREAD

**Issue by Anjiang-Wei** [NVIDIA/cutlass#990]
I want to tune the implementation to optimize for a specific matrix size. I am wondering what is the right way to do it. Does cutlass profiler search for all possible configurations? (Row major, column major, different GEMM algorithms, and template parameters)?

I tried, and find that Cutlass profiler does not do the all possible searching : I can compile and run the GEMM using tensor core while setting all matrices row major like this example https://github.com/NVIDIA/cutlass/blob/main/examples/47_ampere_gemm_universal_streamk/ampere_gemm_universal_streamk.cu#L127 However, cutlass profiler does not find such kernel -- I ran `./tools/profiler/cutlass_profiler --operation=Gemm --m=1 --n=3072 --k=49152 --A=f16:row --B=f16:row --op_class=tensorop` and all returned results' C and D are column-major, e.g.,
```
1,CUTLASS,gemm,cutlass_tensorop_h1688gemm_64x128_64x2_tt_align1,passed,success,universal,1,3072,49152,f16:row,f16:row,f16:column,f16:column,1,0,serial,1,1,tensorop,f16,64,128,64,1,1,1,2,1,2,2,16,8,8,75,1024,302094336,301996032,0,1.20364,233.747,250.902
```

My compilation command for cutlass is `cmake .. -DCUTLASS_NVCC_ARCHS=80 -DCUTLASS_LIBRARY_KERNELS="tensorop*gemm*"`.

To achieve my ultimate goal of searching all possible different implementations for a specific matrix size (especially for a strange matrix size like `m=1` while `K` and `N` are very big), what should I do? Should I try https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/generator.py ? But the issue https://github.com/NVIDIA/cutlass/issues/809 suggests that generator doesn't cover all possible cases, either.

**Comment by thakkarV** [comment]
If M=1 then your problem is GEMV, have you considered using the GEMV kernel instead? I do not think it has integration into the profiler, but it should get you better or equally good perf without having to search such a wide set of kernels.

**Comment by hwu36** [comment]
cutlass profiler is mimicking cublas, i.e. C and D are all column major.  if the output is row major, we can use this transformation.

A x B = C: row => B' x A' = C: col

cutlass can do this transformation automatically for you.

**Comment by hwu36** [comment]
yes to both.

**Comment by hwu36** [comment]
we also have parallel splitk.  generally speaking, large splitk slice number would prefer parallel splitk which uses a 2nd reduction kernel to finalize the result.

**Comment by hwu36** [comment]
If you think searching the best config is too much especially for the splitk, you can try streamk.

Streamk is not on by default now, just make the change here https://github.com/NVIDIA/cutlass/blob/9b923dd4c47d25c85401dafccb195e544008bad4/tools/library/scripts/generator.py#L51

Streamk is discussed in https://arxiv.org/abs/2301.03598

It can reduce the search space of the performant kernel.
