### ISSUE TITLE
[QST] How can I elementwise scale and convert the output of a enpilogue op? 

### ISSUE THREAD

**Issue by FabianSchuetze** [NVIDIA/cutlass#991]
**What is your question?**

I would like to scale and convert (with clamping) the output of the `cutlass::epilogue::thread::LinearCombinationGELU` epilogue. In essence, I would like to use:
```
D = static_cast<ElementOutput>(gamma * activation(alpha * accumulator + beta * source + uniform))
```
while `gamma`, and  `activation(alpha * accumulator + beta * source + uniform)`  are different types (floats in my case, and ElementOutput is int8). 
 How can I do this? 

I have a few ideas but am not sure what the best way is. I could think of:
- Modify the LinearCombinationGeneric Epilogue and insert a scaling operation before the [destination converter](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/thread/linear_combination_generic.h#L169).  
- Fuse two epilogues. I know [this example](https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/sm90_gemm_f16_f16_f16_tensor_op_f32_cluster_warpspecialized_cooperative_bias_elementwise.cu) should be related, but I do not understand how to relate it to the case here. I guess I would fuse the `LinearCombinationGELU`, and `LinearCombinationClamp` epilogues. 

Can somebody kindly provide any guidance on how to best scale and convert the output of the  LinearCombinationGELU epilogue?

**Comment by hwu36** [comment]
you are correct that you need to clamp if the epilogue compute data type is `fp32` and output data type is `int8_t`.

Assume you are using sm>=72, clamping code is like

https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/epilogue/thread/linear_combination_clamp.h#L435-L445

it converts in the flow: fp32->int32->int8_t

just insert this piece of code into your `LinearCombinationGeneric `

**Comment by FabianSchuetze** [comment]
Ok, thanks a lot @hwu36  for the kind and informative reply!
