### ISSUE TITLE
[QST]What is the naming convention of CUTLASS cuda kernel？

### ISSUE THREAD

**Issue by MalaJeans** [NVIDIA/cutlass#999]
What is the naming convention of CUTLASS cuda kernel？
Such as：
What do they mean：cutlass_tensorop_s1688tf32gemm_256x128_16x3_nn_align4、cutlass_tensorop_tf32_s1688gemm_tf32_256x128_16x3_nn_align4.
Is there any official documentation to refer to？

**Comment by thakkarV** [comment]
https://github.com/NVIDIA/cutlass/blob/main/media/docs/profiler.md#cutlass-30-gemm-procedural-names

You can see how they are created in the [library/](https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/gemm_operation.py#L175)

**Comment by MalaJeans** [comment]
> https://github.com/NVIDIA/cutlass/blob/main/media/docs/profiler.md#cutlass-30-gemm-procedural-names
> 
> You can see how they are created in the [library/](https://github.com/NVIDIA/cutlass/blob/main/tools/library/scripts/gemm_operation.py#L175)

OK. Thank you!  I'll watch it now！

**Comment by mnicely** [comment]
@MalaJeans has your issue been resolved?

**Comment by MalaJeans** [comment]
> @MalaJeans has your issue been resolved?

Yes，I have already resolved it.  Thanks!
